Repository department-of-veterans-affairs/vets-website, pull requests merged in 2018-03, with the labels that each got.

#7363 February claims update
  content/pages/disability-benefits/after-you-apply.md
  content/pages/disability-benefits/apply.md
Labels: claim status, content, nebula

#7263 Content wip discharge link on eligibility pages
  content/pages/burials-and-memorials/eligibility.md
  content/pages/disability-benefits/eligibility.md
  content/pages/education/eligibility.md
  content/pages/employment/job-seekers/register-your-business.md
  content/pages/employment/vocational-rehab-and-employment/eligibility.md
  content/pages/health-care/eligibility.md
  content/pages/health-care/health-conditions/mental-health.md
  content/pages/health-care/health-conditions/mental-health/ptsd.md
  content/pages/health-care/health-conditions/military-sexual-trauma.md
  content/pages/housing-assistance/home-loans/eligibility.md
  content/pages/life-insurance/options-and-eligibility/s-dvi.md
  content/pages/pension/eligibility.md
Labels: in progress

#7351 Removed LOA check and manual redirect for identity proofing in auth flow.
  src/js/auth/containers/AuthApp.jsx
Labels: griffin, identity

#7416 Fixed bug that allowed attempt at account creation even if MHV services were not accessible
  src/js/common/containers/MHVApp.jsx
  src/js/health-records/containers/HealthRecordsApp.jsx
  src/js/messaging/containers/MessagingApp.jsx
  src/js/rx/containers/RxRefillsApp.jsx
Labels: griffin, identity

#7419 content/wip/add-training-to-education-labels
  content/includes/veteran-navigation.html
  content/pages/education/index.md
  script/build.js
Labels: in progress

#7422 Claims Index Page -- Appeals buttons on new lines
  src/js/claims-status/components/appeals-v2/AppealListItemV2.jsx
  test/claims-status/components/appeals-v2/AppealListItemV2.unit.spec.jsx
Labels: in progress

#7425 526 e2e -- The case of the missing page
  test/disability-benefits/526EZ/00-all-fields.e2e.spec.js
  test/disability-benefits/526EZ/schema/maximal-test.json
  test/e2e/disability-benefits-helpers.js
Labels: front end, in progress, unicorns

#7427 Delete googlea8237f98bfe9f1e8.html
  content/pages/googlea8237f98bfe9f1e8.html
Labels: in progress

#7426 Appeals process link
  src/js/claims-status/components/appeals-v2/CurrentStatus.jsx
  src/sass/claims-status.scss
Labels: in progress

#7433 Implements the Email field of the Personalization API
  src/js/personalization/user-profile-beta/actions/index.js
Labels: in progress

#7429 Hide and log unknown events
  src/js/claims-status/components/appeals-v2/Timeline.jsx
  src/js/claims-status/utils/appeals-v2-helpers.jsx
  test/claims-status/components/appeals-v2/Timeline.unit.spec.jsx
Labels: in progress

#7431 Make the (+) clickable
  src/js/claims-status/components/appeals-v2/Expander.jsx
  src/js/claims-status/components/appeals-v2/Timeline.jsx
  src/sass/base/_b-utils.scss
  src/sass/claims-status.scss
  test/claims-status/components/appeals-v2/Timeline.unit.spec.jsx
Labels: in progress

#7432 Add merged status
  src/js/claims-status/utils/appeals-v2-helpers.jsx
Labels: in progress

#7430 Fix IE layout and remove normal layout mode on cropper
  src/js/common/schemaform/containers/FormPage.jsx
  src/js/vic-v2/components/CropperController.jsx
  src/js/vic-v2/components/PhotoField.jsx
  src/js/vic-v2/config/form.js
  src/sass/vic-v2.scss
Labels: in progress

#7436 Personalization: Remove unused files
  src/js/personalization/account-beta/components/FormList.jsx
  src/js/personalization/register-beta/README.md
  src/js/personalization/register-beta/actions/index.js
  src/js/personalization/register-beta/containers/BetaEnrollment.jsx
  src/js/personalization/register-beta/containers/Main.jsx
  src/js/personalization/register-beta/reducers/beta.js
  src/js/personalization/register-beta/reducers/index.js
  src/js/personalization/register-beta/register-beta-entry.jsx
  src/js/personalization/register-beta/routes.jsx
  src/js/personalization/user-profile-beta/components/FormList.jsx
  src/js/personalization/user-profile-beta/components/ProfileAccordion.jsx
  src/js/personalization/user-profile-beta/components/UserDataSection.jsx
Labels: in progress

#7420 content/wip/Add-mention-of-appeals-to-accred-rep
  content/pages/disability-benefits/apply/help.md
Labels: in progress

#7437 Chris and Gina content updates (testing pending)
  src/js/claims-status/components/appeals-v2/AppealsV2TabNav.jsx
  src/js/claims-status/components/appeals-v2/Docket.jsx
  src/js/claims-status/utils/appeals-v2-helpers.jsx
  test/claims-status/components/appeals-v2/AppealsV2TabNav.unit.spec.jsx
  test/claims-status/components/appeals-v2/Docket.unit.spec.jsx
  test/claims-status/utils/helpers.unit.spec.js
Labels: in progress

#7445 Remove one more
  src/js/personalization/user-profile-beta/components/ProfileAccordion.jsx
Labels: in progress

#7441 Fix padding bug
  src/js/claims-status/components/appeals-v2/AppealHeader.jsx
  src/js/claims-status/containers/AppealInfo.jsx
Labels: in progress

#7444 Switch between fieldset and div for object field in forms
  src/js/common/schemaform/fields/ObjectField.jsx
  src/js/common/schemaform/fields/TitleField.jsx
  src/sass/modules/_m-schemaform.scss
  test/common/schemaform/fields/TitleField.unit.spec.jsx
Labels: in progress

#7428 Make array item required
  package.json
  src/js/vre/chapter31/config/form.js
  test/vre/chapter31/config/militaryHistory.unit.spec.jsx
  yarn.lock
Labels: in progress

#7448 Breathing room
  src/sass/claims-status.scss
Labels: in progress

#7424 Autogenerate nonced script tags
  content/includes/footer.html
  content/includes/veteran-navigation.html
  content/pages/404.md
  content/pages/employment/index.md
  content/pages/faq.md
  content/pages/health-care/health-conditions/mental-health.md
  content/pages/health-care/health-conditions/mental-health/depression.md
  content/pages/health-care/health-conditions/mental-health/ptsd.md
  content/pages/health-care/health-conditions/military-sexual-trauma.md
  content/pages/health-care/health-conditions/substance-use-problems.md
  content/pages/health-care/index.md
  content/pages/health-care/schedule-an-appointment.md
  content/pages/housing-assistance/index.md
  content/pages/logout.md
  script/build.js
  script/metalsmith/nonceTransformer.js
  src/js/common/utils/accessible-menus.js
Labels: in progress

#7455 make years of education required
  src/js/vre/chapter31/config/form.js
  test/vre/chapter31/config/educationInformation.unit.spec.jsx
Labels: in progress

#7447 Add e2e test for chapter 36
  package.json
  src/js/vre/chapter36/config/form.js
  test/e2e/vre-ch36-helpers.js
  test/vre/chapter36/00-all-fields.e2e.spec.js
  test/vre/chapter36/config/veteranInformation.unit.spec.jsx
  test/vre/chapter36/schema/maximal-test.json
  yarn.lock
Labels: in progress

#7457 Extract magic CSP string into constant to fix typo
  script/metalsmith/nonceTransformer.js
Labels: in progress

#7221 incorporating updates to avoid dead-ends
  content/pages/faq.md
Labels: in progress

#7449 Update Node and Yarn
  .nvmrc
  Dockerfile
  README.md
  package.json
  script/prebuild.js
  script/reset-environment.sh
  yarn.lock
Labels: in progress

#7461 Missed a spot with old yarn version.
  README.md
Labels: in progress

#7438 Re-title your claims and appeals
  content/includes/footer.html
  content/includes/veteran-navigation.html
  content/pages/disability-benefits/index.md
  content/pages/disability-benefits/track-claims/index.md
  src/js/claims-status/components/AppealLayout.jsx
  src/js/claims-status/containers/AppealInfo.jsx
  src/js/claims-status/containers/YourClaimsPage.jsx
  src/js/claims-status/containers/YourClaimsPageV2.jsx
  test/claims-status/e2e/00.claims-list.e2e.spec.js
Labels: in progress

#7463 Upgrade choma to get random test seed printed for reproducing failures
  yarn.lock
Labels: in progress

#7446 Personalization: Beta Enhancements
  config/webpack.config.js
  content/pages/beta-enrollment/personalization.md
  content/pages/personalization-register-beta/index.md
  src/js/beta-enrollment/actions/index.js
  src/js/beta-enrollment/beta-enrollment-entry.jsx
  src/js/beta-enrollment/containers/BetaEnrollmentButton.jsx
  src/js/beta-enrollment/routes.js
  src/js/common/actions/downtime.js
  src/js/common/actions/index.js
  src/js/common/containers/BetaApp.jsx
  src/js/login/components/SearchHelpSignIn.jsx
  src/js/personalization/account-beta/containers/UserProfileApp.jsx
  src/js/personalization/dashboard-beta/containers/DashboardApp.jsx
  src/js/personalization/user-profile-beta/containers/UserProfileApp.jsx
  src/js/user-profile/reducers/profile.js
Labels: in progress

#7462 Appeals v2 launch cv
  src/js/claims-status/actions/index.jsx
  src/js/claims-status/components/appeals-v2/AppealListItemV2.jsx
  src/js/claims-status/components/appeals-v2/AppealsV2TabNav.jsx
  src/js/claims-status/routes.jsx
  test/claims-status/components/appeals-v2/AppealListItemV2.unit.spec.jsx
  test/claims-status/e2e/00.claims-list.e2e.spec.js
  test/claims-status/e2e/01.claim-status-decision.e2e.spec.js
  test/claims-status/e2e/01.claim-status-est-current.e2e.spec.js
  test/claims-status/e2e/01.claim-status-est-past.e2e.spec.js
  test/claims-status/e2e/01.claim-status-est.e2e.spec.js
  test/claims-status/e2e/01.claim-status.e2e.spec.js
  test/claims-status/e2e/02.claim-files.e2e.spec.js
  test/claims-status/e2e/03.claim-details.e2e.spec.js
  test/claims-status/e2e/04.claim-ask-va.e2e.spec.js
  test/claims-status/e2e/05.claim-additional-evidence.e2e.spec.js
  test/claims-status/e2e/05.claim-document-request.e2e.spec.js
  test/claims-status/e2e/06.claim-estimation.e2e.spec.js
Labels: in progress

#7469 added track claims and appeals to pensions nav
  content/includes/veteran-navigation.html
Labels: in progress

#7464 9178 chapter 31 e2e tests
  src/js/vre/chapter31/config/form.js
  test/e2e/vre-ch31-helpers.js
  test/vre/chapter31/00-all-fields.e2e.spec.js
  test/vre/chapter31/config/workInformation.unit.spec.jsx
  test/vre/chapter31/schema/maximal-test.json
Labels: in progress

#7439 Redirect v1 ids
  src/js/claims-status/actions/index.jsx
  src/js/claims-status/containers/AppealInfo.jsx
  src/js/claims-status/reducers/appeals.js
  src/js/claims-status/utils/appeals-v2-helpers.jsx
  test/claims-status/utils/appealsV2Actions.unit.spec.js
Labels: in progress

#7468 Personalization: Connect Profile to API
  src/js/personalization/user-profile-beta/actions/index.js
  src/js/personalization/user-profile-beta/components/AddressSection.jsx
  src/js/personalization/user-profile-beta/components/AuthApplicationSection.jsx
  src/js/personalization/user-profile-beta/components/EmailSection.jsx
  src/js/personalization/user-profile-beta/components/FormItem.jsx
  src/js/personalization/user-profile-beta/components/HeadingWithEdit.jsx
  src/js/personalization/user-profile-beta/components/Hero.jsx
  src/js/personalization/user-profile-beta/components/LoadingButton.jsx
  src/js/personalization/user-profile-beta/components/PersonalInformation.jsx
  src/js/personalization/user-profile-beta/components/PhoneSection.jsx
  src/js/personalization/user-profile-beta/components/ProfileView.jsx
  src/js/personalization/user-profile-beta/components/ProfileViewModals.jsx
  src/js/personalization/user-profile-beta/containers/UserProfileApp.jsx
  src/js/personalization/user-profile-beta/helpers.jsx
  src/js/personalization/user-profile-beta/reducers/index.js
Labels: in progress

#7387 Partially replaced use of LOA with new 'verified' flag.
  src/js/common/helpers/login-helpers.js
  src/js/common/schemaform/save-in-progress/FormSaved.jsx
  src/js/login/components/Verify.jsx
  src/js/user-profile/components/UserDataSection.jsx
  src/js/user-profile/reducers/profile.js
  src/js/veteran-id-card/containers/VeteranIDCard.jsx
  test/common/schemaform/save-in-progress/FormSaved.unit.spec.jsx
Labels: griffin, identity

#7472 Add cropper unit tests, plus some others for VIC
  script/run-unit-test.sh
  src/js/vic-v2/components/CropperController.jsx
  src/js/vic-v2/config/form.js
  src/js/vic-v2/containers/IntroductionPage.jsx
  test/util/mocha-setup.js
  test/vic-v2/components/CropperController.unit.spec.jsx
  test/vic-v2/config/documents.unit.spec.jsx
  test/vic-v2/config/photo.unit.spec.jsx
  test/vic-v2/containers/IntroductionPage.unit.spec.jsx
Labels: in progress

#7443 subway map css fixups
  content/pages/disability-benefits/claims-appeal.md
  src/sass/base/_va.scss
  src/sass/claims-status.scss
  src/sass/discharge-wizard.scss
  src/sass/modules/_m-downtime-notification.scss
  src/sass/modules/_m-modal.scss
  src/sass/vic-v2.scss
Labels: in progress

#7478 Show cavcOption alert after "What happens next?"
  src/js/claims-status/components/appeals-v2/AlertsList.jsx
  src/js/claims-status/containers/AppealsV2StatusPage.jsx
  src/js/claims-status/utils/appeals-v2-helpers.jsx
Labels: in progress

#7451 Use v2Availability, add messaging
  src/js/claims-status/containers/AppealInfo.jsx
  src/js/claims-status/containers/YourClaimsPageV2.jsx
  src/js/claims-status/reducers/claimsV2.js
  test/claims-status/components/appeals-v2/AppealInfo.unit.spec.jsx
Labels: in progress

#7465 Implemented on-demand session routes
  src/js/common/components/LoginModal.jsx
  src/js/common/components/authentication/LoginPrompt.jsx
  src/js/common/components/authentication/VerifyPrompt.jsx
  src/js/common/helpers/login-helpers.js
  src/js/common/schemaform/save-in-progress/FormSaved.jsx
  src/js/common/schemaform/save-in-progress/SaveInProgressErrorPage.jsx
  src/js/common/utils/helpers.js
  src/js/login/actions/index.js
  src/js/login/components/SearchHelpSignIn.jsx
  src/js/login/components/SignIn.jsx
  src/js/login/components/SignInProfileMenu.jsx
  src/js/login/components/Verify.jsx
  src/js/login/containers/Main.jsx
  src/js/login/reducers/login.js
  src/js/login/utils/helpers.js
  src/js/user-profile/components/UserDataSection.jsx
  src/js/user-profile/containers/UserProfileApp.jsx
  src/js/user-profile/reducers/profile.js
  test/common/components/LoginModal.unit.spec.jsx
  test/common/components/authentication/LoginPrompt.unit.spec.jsx
  test/common/components/authentication/VerifyPrompt.unit.spec.jsx
  test/common/helpers/login-helpers.unit.spec.jsx
  test/e2e/login-helpers.js
  test/login/utils/helpers.unit.spec.js
Labels: in progress

#7477 WIP - Personalization - Update account to settings
  src/js/personalization/account-beta/README.md
  src/js/personalization/account-beta/account-entry.jsx
  src/js/personalization/account-beta/actions/index.js
  src/js/personalization/account-beta/components/AccountMain.jsx
  src/js/personalization/account-beta/components/AccountVerification.jsx
  src/js/personalization/account-beta/components/AuthApplicationSection.jsx
  src/js/personalization/account-beta/components/FormItem.jsx
  src/js/personalization/account-beta/components/LoginSettings.jsx
  src/js/personalization/account-beta/components/MultifactorMessage.jsx
  src/js/personalization/account-beta/components/TermsAndConditions.jsx
  src/js/personalization/account-beta/components/UserDataSection.jsx
  src/js/personalization/account-beta/containers/AccountApp.jsx
  src/js/personalization/account-beta/helpers.jsx
  src/js/personalization/account-beta/reducers/index.js
  src/js/personalization/account-beta/routes.jsx
Labels: in progress

#7421 526 Dev – 4.7 Private records release
  src/js/common/schemaform/definitions/address.js
  src/js/disability-benefits/526EZ/config/form.js
  src/js/disability-benefits/526EZ/helpers.jsx
  test/disability-benefits/526EZ/00-all-fields.e2e.spec.js
  test/disability-benefits/526EZ/config/privateRecordReleases.unit.spec.jsx
  test/disability-benefits/526EZ/schema/maximal-test.json
  test/e2e/disability-benefits-helpers.js
  test/e2e/e2e-helpers.js
Labels: in progress

#7482 ensuring curly quotes and apostrophes for discharge wizard
  src/js/discharge-wizard/components/CarefulConsiderationStatement.jsx
  src/js/discharge-wizard/components/FormQuestions.jsx
  src/js/discharge-wizard/components/InstructionsPage.jsx
  src/js/discharge-wizard/config.js
  src/js/discharge-wizard/containers/GuidancePage.jsx
  src/js/discharge-wizard/containers/RequestDD214.jsx
Labels: in progress

#7476 change of content per issue 6919 to make it less confusing
  src/js/discharge-wizard/containers/GuidancePage.jsx
Labels: in progress

#7481 6568 button needs exit icon
  src/js/discharge-wizard/containers/GuidancePage.jsx
  src/sass/discharge-wizard.scss
Labels: in progress

#7473 Update confirmation page messaging for pension and burials
  src/js/burials/containers/ConfirmationPage.jsx
  src/js/pensions/containers/ConfirmationPage.jsx
  test/burials/containers/ConfirmationPage.unit.spec.jsx
  test/pensions/containers/ConfirmationPage.unit.spec.jsx
Labels: in progress

#7485 Personalization: Integrate w/Service History API route; remove profile picture
  src/js/personalization/user-profile-beta/actions/index.js
  src/js/personalization/user-profile-beta/components/Hero.jsx
  src/js/personalization/user-profile-beta/components/PersonalInformation.jsx
  src/js/personalization/user-profile-beta/components/ProfileView.jsx
  src/js/personalization/user-profile-beta/containers/UserProfileApp.jsx
  src/js/personalization/user-profile-beta/reducers/index.js
  src/js/personalization/user-profile-beta/user-profile-entry.jsx
  src/sass/va-profile.scss
Labels: in progress

#7484 Update heading
  src/js/claims-status/containers/AppealInfo.jsx
Labels: in progress

#7475 Additional document upload
  src/js/common/schemaform/fields/FileField.jsx
  src/js/disability-benefits/526EZ/config/form.js
  src/js/disability-benefits/526EZ/helpers.jsx
  test/disability-benefits/526EZ/00-all-fields.e2e.spec.js
  test/disability-benefits/526EZ/config/documentUpload.unit.spec.jsx
  test/disability-benefits/526EZ/config/evidenceType.unit.spec.jsx
  test/disability-benefits/526EZ/config/privateMedicalRecordsRelease.jsx
  test/disability-benefits/526EZ/config/recordUpload.unit.spec.jsx
Labels: in progress

#7456 Add letters intro page
  content/includes/footer.html
  content/includes/veteran-navigation.html
  content/pages/download-va-letters/index.md
  content/pages/download-va-letters/letters.md
  script/build.js
  src/js/letters/letters-entry.jsx
  src/js/user-profile/components/AuthApplicationSection.jsx
  test/e2e/unauthed-flows.e2e.spec.js
  test/letters/01-authed.e2e.spec.js
Labels: in progress

#7491 Fixed bolding for unread inbox messages
  src/sass/messaging/partials/_messaging-folder.scss
Labels: secure messaging

#7474 Use manifest for app config in build process
  config/webpack.config.js
  docs/StartANewReactApp.md
  package.json
  script/build.js
  script/manifest-helpers.js
  src/js/auth/manifest.json
  src/js/burials/burials-entry.jsx
  src/js/burials/manifest.json
  src/js/claims-status/claims-status-entry.jsx
  src/js/claims-status/manifest.json
  src/js/claims-status/utils/page.js
  src/js/disability-benefits/526EZ/form-entry.jsx
  src/js/disability-benefits/526EZ/manifest.json
  src/js/discharge-wizard/discharge-wizard-entry.jsx
  src/js/discharge-wizard/manifest.json
  src/js/edu-benefits/1990/edu-benefits-entry.jsx
  src/js/edu-benefits/1990/manifest.json
  src/js/edu-benefits/1990e/edu-benefits-entry.jsx
  src/js/edu-benefits/1990e/manifest.json
  src/js/edu-benefits/1990n/edu-benefits-entry.jsx
  src/js/edu-benefits/1990n/manifest.json
  src/js/edu-benefits/1995/edu-benefits-entry.jsx
  src/js/edu-benefits/1995/manifest.json
  src/js/edu-benefits/5490/edu-benefits-entry.jsx
  src/js/edu-benefits/5490/manifest.json
  src/js/edu-benefits/5495/edu-benefits-entry.jsx
  src/js/edu-benefits/5495/manifest.json
  src/js/facility-locator/facility-locator-entry.jsx
  src/js/facility-locator/manifest.json
  src/js/gi/gi-entry.jsx
  src/js/gi/manifest.json
  src/js/hca/hca-entry.jsx
  src/js/hca/manifest.json
  src/js/health-records/health-records-entry.jsx
  src/js/health-records/manifest.json
  src/js/id-card-beta/manifest.json
  src/js/letters/letters-entry.jsx
  src/js/letters/manifest.json
  src/js/login/manifest.json
  src/js/messaging/manifest.json
  src/js/messaging/messaging-entry.jsx
  src/js/pensions/manifest.json
  src/js/pensions/pensions-entry.jsx
  src/js/post-911-gib-status/manifest.json
  src/js/post-911-gib-status/post-911-gib-status-entry.jsx
  src/js/pre-need/manifest.json
  src/js/pre-need/pre-need-entry.jsx
  src/js/rx/manifest.json
  src/js/rx/rx-entry.jsx
  src/js/user-profile/manifest.json
  src/js/veteran-id-card/manifest.json
  src/js/vic-v2/manifest.json
  src/js/vic-v2/veteran-id-card-entry.jsx
  src/js/vre/chapter31/chapter31-entry.jsx
  src/js/vre/chapter31/manifest.json
  src/js/vre/chapter36/chapter36-entry.jsx
  src/js/vre/chapter36/manifest.json
  src/test-support/test-server.js
  yarn.lock
Labels: in progress

#7486 Unit Test Watch
  .eslintignore
  README.md
  package.json
  script/mocha.js
  script/watch.js
  test/pensions/config/childrenInformation.unit.spec.jsx
Labels: front end, in progress, rainbows

#7471 pointing Facility Locator at the new controller for cached data
  src/js/facility-locator/config.js
  test/e2e/facility-helpers.js
Labels: in progress
