Repository department-of-veterans-affairs/vets-website, pull requests merged in 2018-07, with the labels that each got.

#7941 9367 grandfathered bah
  src/applications/gi/actions/index.js
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/reducers/profile.js
  src/applications/gi/selectors/calculator.js
  src/applications/gi/tests/actions/index.unit.spec.js
  src/applications/gi/tests/reducers/calculator.unit.spec.js
Labels: in progress

#7952 Profile360: Show loading indicator during delete
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
  src/applications/personalization/profile360/components/Vet360EditModalActionButtons.jsx
  src/applications/personalization/profile360/reducers/vet360.js
Labels: in progress

#7953 July 2018 monthly disability claim average update
  content/pages/disability-benefits/after-you-apply.md
  content/pages/disability-benefits/apply.md
Labels: in progress

#7940 526 address ux mg
  src/applications/disability-benefits/526EZ/constants.jsx
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/primaryAddress.js
  src/applications/disability-benefits/526EZ/sass/disability-benefits.scss
  src/applications/disability-benefits/526EZ/tests/config/primaryAddress.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/helpers.unit.spec.jsx
Labels: in progress

#7956 Facility Locator search controls tweaks
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/config.js
Labels: facility locator, griffin, in progress

#7957 adjust yellow ribbon amount input behavior
  src/applications/gi/components/Dropdown.jsx
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/sass/gi.scss
  src/applications/gi/selectors/calculator.js
Labels: in progress

#7959 add prefill transform for 1990 email and phone numbers
  src/applications/edu-benefits/1990/config/form.js
  src/applications/edu-benefits/1990/helpers.jsx
  src/applications/edu-benefits/tests/1990/helpers.unit.spec.js
Labels: in progress

#7964 Profile360 adjustments
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/Address.jsx
  src/applications/personalization/profile360/components/AddressSection.jsx
  src/applications/personalization/profile360/components/ContactInformationExplanation.jsx
  src/applications/personalization/profile360/components/MilitaryInformation.jsx
  src/applications/personalization/profile360/components/PersonalInformation.jsx
  src/applications/personalization/profile360/constants/vet360.js
  src/applications/personalization/profile360/util/local-vet360.js
  src/applications/personalization/va-profile/actions/updaters.js
Labels: in progress

#7958 add independent study and priority enrollment filters
  src/applications/gi/components/profile/AdditionalInformation.jsx
  src/applications/gi/components/profile/Programs.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/tests/reducers/filter.unit.spec.js
Labels: in progress

#7962 Update rated disabilities review page title
  src/applications/disability-benefits/526EZ/config/form.js
Labels: in progress

#7967 Allow health services to be filtered in Facility Locator request.
  src/applications/facility-locator/actions/index.js
Labels: facility locator, griffin, in progress

#7930 add dev-preview and preview to the commit trigger
  Jenkinsfile
Labels: in progress

#7968 Set up Opt Out form app scaffold
  content/pages/education/opt-out.md
  content/pages/education/opt-out/form.md
  src/applications/edu-benefits/opt-out/config/form.js
  src/applications/edu-benefits/opt-out/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/opt-out/containers/IntroductionPage.jsx
  src/applications/edu-benefits/opt-out/containers/OptOutApp.jsx
  src/applications/edu-benefits/opt-out/manifest.json
  src/applications/edu-benefits/opt-out/opt-out-entry.jsx
  src/applications/edu-benefits/opt-out/reducers/index.js
  src/applications/edu-benefits/opt-out/routes.jsx
  src/applications/edu-benefits/tests/opt-out/00.opt-out.e2e.spec.js
  src/applications/static-pages/static-pages-entry.js
Labels: in progress

#7924 [WIP] Add unit tests for Profile 360
  package.json
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
  src/applications/personalization/profile360/containers/Vet360ProfileField.jsx
  src/applications/personalization/profile360/selectors.js
  src/applications/personalization/profile360/tests/components/ProfileView.unit.spec.jsx
  src/applications/personalization/profile360/tests/components/Vet360EditModal.unit.spec.jsx
  src/applications/personalization/profile360/tests/components/Vet360EditModalActionButtons.unit.spec.jsx
  src/applications/personalization/profile360/tests/components/Vet360Transaction.unit.spec.jsx
  src/applications/personalization/profile360/tests/components/Vet360TransactionPending.unit.spec.jsx
  src/applications/personalization/profile360/tests/containers/Vet360ProfileField.unit.spec.jsx
  src/applications/personalization/profile360/tests/reducers/index.unit.spec.js
  src/applications/personalization/profile360/tests/reducers/vet360.unit.spec.js
  src/applications/personalization/profile360/tests/selectors.unit.spec.js
Labels: in progress

#7969 [HOLD] Launch Profile-360
  content/pages/profile/index.md
  content/pages/profile360/index.md
  src/applications/personalization/profile360/manifest.json
  src/applications/personalization/va-profile/manifest.json
  src/platform/site-wide/announcements/config/index.js
Labels: in progress

#7970 Set up complaint-tool scaffold
  content/pages/education/complaint-tool.md
  content/pages/education/complaint-tool/form.md
  src/applications/edu-benefits/complaint-tool/complaint-tool-entry.jsx
  src/applications/edu-benefits/complaint-tool/config/form.js
  src/applications/edu-benefits/complaint-tool/containers/ComplaintToolApp.jsx
  src/applications/edu-benefits/complaint-tool/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/complaint-tool/containers/IntroductionPage.jsx
  src/applications/edu-benefits/complaint-tool/manifest.json
  src/applications/edu-benefits/complaint-tool/reducers/index.js
  src/applications/edu-benefits/complaint-tool/routes.jsx
  src/applications/edu-benefits/tests/complaint-tool/00.complaint-tool.e2e.spec.js
Labels: in progress

#7897 Error messages for auth flow failures
  src/applications/auth/containers/AuthApp.jsx
  src/applications/auth/sass/auth.scss
Labels: griffin, identity, in progress

#7973 Set up confirmation page
  src/applications/edu-benefits/opt-out/config/form.js
  src/applications/edu-benefits/opt-out/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/tests/opt-out/containers/ConfirmationPage.unit.spec.jsx
Labels: in progress

#7978 Remove VA-Profile directory
  src/applications/personalization/account/account-entry.jsx
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/applications/personalization/va-profile/README.md
  src/applications/personalization/va-profile/actions/index.js
  src/applications/personalization/va-profile/actions/misc.js
  src/applications/personalization/va-profile/actions/updaters.js
  src/applications/personalization/va-profile/components/AccountMessage.jsx
  src/applications/personalization/va-profile/components/AddressSection.jsx
  src/applications/personalization/va-profile/components/ContactInformation.jsx
  src/applications/personalization/va-profile/components/DowntimeBanner.jsx
  src/applications/personalization/va-profile/components/EmailSection.jsx
  src/applications/personalization/va-profile/components/HeadingWithEdit.jsx
  src/applications/personalization/va-profile/components/Hero.jsx
  src/applications/personalization/va-profile/components/LoadFail.jsx
  src/applications/personalization/va-profile/components/LoadingButton.jsx
  src/applications/personalization/va-profile/components/LoadingSection.jsx
  src/applications/personalization/va-profile/components/MilitaryInformation.jsx
  src/applications/personalization/va-profile/components/PersonalInformation.jsx
  src/applications/personalization/va-profile/components/PhoneSection.jsx
  src/applications/personalization/va-profile/components/ProfileView.jsx
  src/applications/personalization/va-profile/containers/VAProfileApp.jsx
  src/applications/personalization/va-profile/manifest.json
  src/applications/personalization/va-profile/reducers/index.js
  src/applications/personalization/va-profile/routes.jsx
  src/applications/personalization/va-profile/sass/va-profile.scss
  src/applications/personalization/va-profile/tests/components/ContactInformation.unit.spec.jsx
  src/applications/personalization/va-profile/tests/components/EmailSection.unit.spec.jsx
  src/applications/personalization/va-profile/tests/components/ProfileView.unit.spec.jsx
  src/applications/personalization/va-profile/tests/containers/VAProfileApp.unit.spec.jsx
  src/applications/personalization/va-profile/tests/util/index.unit.spec.js
  src/applications/personalization/va-profile/util/sendAndMergeApiRequests.js
  src/applications/personalization/va-profile/va-profile-entry.jsx
Labels: in progress

#7983 Add opt out and complaint tool content pages to ignore list
  content/pages/education/opt-out-information-sharing.md
  content/pages/education/opt-out-information-sharing/form.md
  script/build.js
  src/applications/edu-benefits/opt-out/manifest.json
Labels: in progress

#7979 526 transform submit mg
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/tests/helpers.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/schema/maximal-test.json
Labels: in progress

#7976 11414-breadcrumb-css
  assets/js/breadcrumbs/mobile-breadcrumb.js
  content/includes/breadcrumbs.html
  content/pages/account/index.md
  content/pages/burials-and-memorials/application/530.md
  content/pages/burials-and-memorials/pre-need/form-10007-apply-for-eligibility.md
  content/pages/disability-benefits/apply/form-526-disability-claim.md
  content/pages/education/apply-for-education-benefits/application/1990.md
  content/pages/education/apply-for-education-benefits/application/1990E.md
  content/pages/education/apply-for-education-benefits/application/1990N.md
  content/pages/education/apply-for-education-benefits/application/1995.md
  content/pages/education/apply-for-education-benefits/application/5490.md
  content/pages/education/apply-for-education-benefits/application/5495.md
  content/pages/education/complaint-tool/form.md
  content/pages/education/opt-out-information-sharing/form.md
  content/pages/employment/vocational-rehab-and-employment/application/chapter31.md
  content/pages/employment/vocational-rehab-and-employment/application/chapter36.md
  content/pages/health-care/apply/application.md
  content/pages/pension/application/527EZ.md
  content/pages/profile/index.md
  content/pages/veteran-id-card/apply.md
  content/pages/veteran-id-card/index.md
  package.json
  script/build.js
  script/metalsmith/breadcrumbTransformer.js
  src/applications/discharge-wizard/DischargeWizardApp.jsx
  src/applications/facility-locator/containers/FacilityLocatorApp.jsx
  src/platform/site-wide/sass/style.scss
  yarn.lock
Labels: in progress

#7981 Profile360: Remaining tests
  src/applications/personalization/profile360/actions/index.js
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/EmailEditModal.jsx
  src/applications/personalization/profile360/components/Hero.jsx
  src/applications/personalization/profile360/components/LoadingButton.jsx
  src/applications/personalization/profile360/components/MilitaryInformation.jsx
  src/applications/personalization/profile360/components/PersonalInformation.jsx
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
  src/applications/personalization/profile360/components/Vet360ProfileFieldHeading.jsx
  src/applications/personalization/profile360/components/Vet360TransactionPending.jsx
  src/applications/personalization/profile360/components/Vet360TransactionSuccessBanner.jsx
  src/applications/personalization/profile360/containers/Vet360ProfileField.jsx
  src/applications/personalization/profile360/containers/Vet360TransactionReporter.jsx
  src/applications/personalization/profile360/tests/containers/Vet360TransactionReporter.unit.spec.jsx
  src/applications/personalization/profile360/tests/e2e/profile-360.e2e.spec.js
  src/applications/personalization/profile360/tests/e2e/routes.json
  src/applications/personalization/profile360/tests/selectors.unit.spec.js
  src/applications/personalization/profile360/util/local-vet360.js
Labels: in progress

#7990 Dslogon banner
  content/pages/index.md
Labels: in progress

#7986 526 itf wrapper
  src/applications/disability-benefits/526EZ/Form526EZApp.jsx
  src/applications/disability-benefits/526EZ/actions/index.js
  src/applications/disability-benefits/526EZ/components/FormStartControls.jsx
  src/applications/disability-benefits/526EZ/components/IntroductionPage.jsx
  src/applications/disability-benefits/526EZ/constants.js
  src/applications/disability-benefits/526EZ/containers/ITFWrapper.jsx
  src/applications/disability-benefits/526EZ/reducer.js
  src/applications/disability-benefits/526EZ/tests/actions/actions.unit.spec.js
  src/applications/disability-benefits/526EZ/tests/components/FormStartControls.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/containers/ITFWrapper.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/reducers.unit.spec.js
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/testing/unit/helpers.js
  src/platform/utilities/constants.js
Labels: in progress

#7995 disable ds logon banner
  content/pages/index.md
Labels: in progress

#7960 526 -- chapter 1 content edits
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/paymentInfo.jsx
  src/applications/disability-benefits/526EZ/pages/primaryAddress.js
Labels: front end, in progress, unicorns

#7992 Fix global Moment-formatting issues
  src/applications/claims-status/components/ClaimsDecision.jsx
  src/applications/claims-status/components/appeals-v2/AppealHeader.jsx
  src/applications/claims-status/tests/components/ClaimComplete.unit.spec.jsx
  src/applications/personalization/account/containers/AccountApp.jsx
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/applications/personalization/profile360/components/MilitaryInformation.jsx
  src/applications/personalization/profile360/components/PersonalInformation.jsx
  src/platform/forms/save-in-progress/ApplicationStatus.jsx
  src/platform/forms/save-in-progress/RoutedSavableApp.jsx
  src/platform/site-wide/index.js
  src/platform/site-wide/moment-setup.js
  src/platform/testing/unit/mocha-setup.js
Labels: in progress

#7988 GI Bill Comparison Tool content changes
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/containers/Modals.jsx
Labels: in progress

#7989 Opt out form
  content/pages/education/opt-out-information-sharing/opt-out-form-0993.md
  package.json
  src/applications/edu-benefits/0993/config/form.js
  src/applications/edu-benefits/0993/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/0993/containers/Form0993App.jsx
  src/applications/edu-benefits/0993/containers/IntroductionPage.jsx
  src/applications/edu-benefits/0993/containers/RoutedSavableSinglePageForm.jsx
  src/applications/edu-benefits/0993/containers/RoutedSavableSinglePageFormApp.jsx
  src/applications/edu-benefits/0993/containers/SinglePageForm.jsx
  src/applications/edu-benefits/0993/containers/SinglePageFormApp.jsx
  src/applications/edu-benefits/0993/containers/SubmitButtons.jsx
  src/applications/edu-benefits/0993/containers/SubmitController.jsx
  src/applications/edu-benefits/0993/edu-benefits-entry.jsx
  src/applications/edu-benefits/0993/helpers.js
  src/applications/edu-benefits/0993/manifest.json
  src/applications/edu-benefits/0993/reducers/index.js
  src/applications/edu-benefits/0993/routes.jsx
  src/applications/edu-benefits/opt-out/config/form.js
  src/applications/edu-benefits/opt-out/containers/OptOutApp.jsx
  src/applications/edu-benefits/opt-out/manifest.json
  src/applications/edu-benefits/opt-out/routes.jsx
  src/applications/edu-benefits/tests/0993/00.0093-opt-out.e2e.spec.js
  src/applications/edu-benefits/tests/0993/0993-helpers.js
  src/applications/edu-benefits/tests/0993/config/claimantInfo.unit.spec.js
  src/applications/edu-benefits/tests/0993/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/tests/0993/containers/RoutedSavableSinglePageForm.unit.spec.jsx
  src/applications/edu-benefits/tests/0993/containers/RoutedSavableSinglePageFormApp.unit.spec.jsx
  src/applications/edu-benefits/tests/0993/containers/SinglePageForm.unit.spec.jsx
  src/applications/edu-benefits/tests/0993/containers/SinglePageFormApp.unit.spec.jsx
  src/applications/edu-benefits/tests/0993/containers/SubmitButtons.unit.spec.jsx
  src/applications/edu-benefits/tests/0993/containers/SubmitController.unit.spec.jsx
  src/applications/edu-benefits/tests/0993/schema/maximal-test.json
  src/applications/edu-benefits/tests/opt-out/00.opt-out.e2e.spec.js
  src/applications/personalization/profile360/tests/util/helpers.unit.spec.js
  src/applications/personalization/profile360/util/helpers.jsx
  src/platform/forms/tests/migrations.unit.spec.js
  yarn.lock
Labels: in progress

#7947 Content/wip/opt out static page
  content/pages/education/opt-out-information-sharing.md
Labels: in progress

#7996 11291 add opt out modal
  content/pages/education/gi-bill.md
  content/pages/education/index.md
  content/pages/education/opt-out-information-sharing.md
  src/applications/edu-benefits/components/OptOutWizard.jsx
  src/applications/edu-benefits/components/createOptOutApplicationStatus.jsx
  src/applications/edu-benefits/tests/components/OptOutWizard.unit.spec.jsx
  src/applications/edu-benefits/utils/optOutStatus.js
  src/applications/static-pages/static-pages-entry.js
Labels: in progress

#7993 Add more profile tests
  package.json
  src/applications/personalization/account/tests/components/AccountMain.unit.spec.js
  src/applications/personalization/dashboard/tests/containers/DashboardApp.unit.spec.jsx
  src/applications/personalization/profile360/components/ContactInformationExplanation.jsx
Labels: in progress

#8011 change default zoom level and search radius
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/containers/VAMap.jsx
Labels: facility locator

#8075 using facility classification for va_cemetery type to distinguish between national and state entries
  src/applications/facility-locator/components/FacilityTypeDescription.jsx
  src/applications/facility-locator/components/search-results/FacilityInfoBlock.jsx
  src/applications/facility-locator/containers/FacilityDetail.jsx
Labels: facility locator

#8039 Use localStorage for session data (with feature toggle)
  src/applications/auth/containers/AuthApp.jsx
  src/applications/burials/helpers.jsx
  src/applications/burials/tests/helpers.unit.spec.jsx
  src/applications/claims-status/actions/index.jsx
  src/applications/claims-status/tests/actions.unit.spec.js
  src/applications/claims-status/tests/utils/appealsV2Actions.unit.spec.js
  src/applications/claims-status/tests/utils/helpers.unit.spec.js
  src/applications/claims-status/utils/helpers.js
  src/applications/disability-benefits/526EZ/components/ButtonContainer.jsx
  src/applications/disability-benefits/526EZ/tests/components/DisabilityWizard.unit.spec.jsx
  src/applications/letters/tests/actions/letters.unit.spec.js
  src/applications/pensions/helpers.jsx
  src/applications/pensions/tests/helpers.unit.spec.jsx
  src/applications/post-911-gib-status/tests/actions/post-911-gib-status.unit.spec.js
  src/applications/pre-need/tests/config/burialBenefits.unit.spec.jsx
  src/applications/static-pages/static-page-widgets.js
  src/applications/static-pages/tests/static-page-widgets.unit.spec.js
  src/applications/terms-and-conditions/containers/MhvTermsAndConditions.jsx
  src/applications/verify/containers/VerifyApp.jsx
  src/applications/vic-v2/helpers.jsx
  src/applications/vic-v2/tests/components/PhotoPreview.unit.spec.jsx
  src/applications/vic-v2/tests/helpers.unit.spec.js
  src/platform/forms/save-in-progress/actions.js
  src/platform/forms/save-in-progress/api.js
  src/platform/forms/save-in-progress/savedFormRequest.js
  src/platform/forms/tests/save-in-progress/SaveInProgressErrorPage.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/actions.unit.spec.js
  src/platform/site-wide/user-nav/components/SearchHelpSignIn.jsx
  src/platform/site-wide/user-nav/containers/Main.jsx
  src/platform/site-wide/user-nav/selectors.js
  src/platform/site-wide/user-nav/tests/components/SearchHelpSignIn.unit.spec.jsx
  src/platform/site-wide/user-nav/tests/selectors.unit.spec.js
  src/platform/testing/e2e/auth.js
  src/platform/testing/unit/helpers.js
  src/platform/user/authorization/components/RequiredLoginView.jsx
  src/platform/user/profile/actions/index.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/tests/authorization/components/RequiredLoginView.unit.spec.jsx
  src/platform/utilities/api/index.js
  src/platform/utilities/storage/conditionalStorage.js
Labels: griffin
