Repository department-of-veterans-affairs/vets-website, pull requests merged in 2018-04, with the labels that each got.

#7480 Removed use of LOA in RequiredLoginView
  src/js/claims-status/containers/ClaimsStatusApp.jsx
  src/js/common/components/RequiredLoginView.jsx
  src/js/health-beta/containers/HealthBetaEnrollment.jsx
  src/js/health-records/containers/HealthRecordsApp.jsx
  src/js/id-card-beta/containers/IDCardBetaEnrollment.jsx
  src/js/letters/containers/LettersApp.jsx
  src/js/messaging/containers/MessagingApp.jsx
  src/js/post-911-gib-status/containers/Post911GIBStatusApp.jsx
  src/js/rx/containers/RxRefillsApp.jsx
  src/js/user-profile/containers/UserProfileApp.jsx
  src/js/veteran-id-card/containers/VeteranIDCard.jsx
  test/claims-status/components/ClaimsStatusApp.unit.spec.jsx
  test/common/components/RequiredLoginView.unit.spec.jsx
  test/e2e/login-helpers.js
Labels: griffin, identity, in progress

#7470 8868 evidence summary
  src/js/common/schemaform/fields/FileField.jsx
  src/js/disability-benefits/526EZ/config/form.js
  src/js/disability-benefits/526EZ/helpers.jsx
  src/sass/disability-benefits.scss
  test/common/schemaform/fields/FileField.unit.spec.jsx
  test/disability-benefits/526EZ/00-all-fields.e2e.spec.js
  test/e2e/disability-benefits-helpers.js
Labels: in progress

#7483 9174 526 transform treatments
  src/js/disability-benefits/526EZ/helpers.jsx
  test/disability-benefits/526EZ/helpers.unit.spec.jsx
Labels: in progress

#7505 Improve accuracy of progress bar for Health Records updates
  src/js/health-records/containers/UpdatePage.jsx
  src/js/health-records/reducers/refresh.js
  src/sass/health-records/health-records.scss
  test/health-records/containers/UpdatePage.unit.spec.jsx
  test/health-records/reducers/refresh.unit.spec.js
Labels: blue button, griffin

#7526 Fixed infinite loading on VIC due to invalid user prop.
  src/js/veteran-id-card/containers/VeteranIDCard.jsx
Labels: griffin, identity

#7540 Implemented new Health Records refresh error messages.
  src/js/health-records/containers/DownloadPage.jsx
  test/health-records/containers/DownloadPage.unit.spec.jsx
Labels: blue button, griffin

#7568 Split Login and Verify components into separate apps
  src/js/common/components/RequiredLoginView.jsx
  src/js/login/components/SearchHelpSignIn.jsx
  src/js/login/containers/Main.jsx
  src/js/login/login-entry.jsx
  src/js/login/verify-entry.jsx
  src/js/verify/containers/VerifyApp.jsx
  src/js/verify/manifest.json
  src/js/verify/verify-entry.jsx
  src/sass/login.scss
  test/common/components/RequiredLoginView.unit.spec.jsx
Labels: griffin, identity

#7611 Cleaned up login widget components
  src/js/login/components/SearchHelpSignIn.jsx
  src/js/login/components/SignInModal.jsx
  src/js/login/containers/Main.jsx
  src/sass/login.scss
  src/sass/modules/_m-vet-nav.scss
  test/login/components/SearchHelpSignIn.unit.spec.jsx
Labels: griffin, identity

#7661 Personalization: Add success message
  src/js/personalization/va-profile-beta/actions/index.js
  src/js/personalization/va-profile-beta/components/ProfileView.jsx
  src/js/personalization/va-profile-beta/containers/VAProfileApp.jsx
  src/js/personalization/va-profile-beta/reducers/index.js
Labels: in progress

#7662 [HOLD] Personalization - Turn on for Production
  src/js/personalization/account-beta/manifest.json
  src/js/personalization/beta-enrollment/manifest.json
  src/js/personalization/dashboard-beta/manifest.json
  src/js/personalization/va-profile-beta/manifest.json
Labels: in progress

#7667 Personalization: Add a check for empty array in Service History
  src/js/personalization/va-profile-beta/components/MilitaryInformation.jsx
Labels: in progress

#7668 Fix T&C for Account and Account-Beta
  script/build.js
  src/js/personalization/account-beta/components/AccountMain.jsx
  src/js/personalization/account-beta/components/TermsAndConditions.jsx
  src/js/user-profile/components/UserDataSection.jsx
Labels: in progress

#7671 Fix for Login Modal not closing without redirect
  src/platform/site-wide/login/containers/Main.jsx
Labels: in progress

#7675 Remove saved forms upon deletion
  src/js/personalization/dashboard-beta/actions/index.js
Labels: in progress
