Repository department-of-veterans-affairs/vets-website, pull requests merged in 2018-12, with the labels that each got.

#9148 Bah 781 event description
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/pages/incidentDate.jsx
  src/applications/disability-benefits/all-claims/pages/incidentDescription.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/secondaryIncidentDescription.js
  src/applications/disability-benefits/all-claims/tests/config/781.unit.spec.js
Labels: BAH

#9134 Additional Remarks - Additional changes in behavior - 781a
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/config/schema.js
  src/applications/disability-benefits/all-claims/pages/additionalBehaviorChanges.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/tests/pages/additionalBehaviorChanges.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9155 Bah 781 last incident
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/ptsdFinalIncident.jsx
  src/applications/disability-benefits/all-claims/pages/finalIncident.js
  src/applications/disability-benefits/all-claims/pages/incidentDate.js
  src/applications/disability-benefits/all-claims/pages/incidentDate.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/secondaryFinalIncident.js
  src/applications/disability-benefits/all-claims/tests/pages/finalIncident.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/secondaryFinalncident.unit.spec.jsx
Labels: BAH

#9206 Additional remarks 781 form #9158
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/pages/additionalRemarks781.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/tests/pages/additionalRemarks781.unit.spec.jsx
Labels: BAH

#9137 [All Claims] 781/781a Incident Unit Assignment
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/content/incidentUnitAssignment.jsx
  src/applications/disability-benefits/all-claims/pages/incidentUnitAssignment.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/secondaryIncidentUnitAssignment.js
  src/applications/disability-benefits/all-claims/tests/pages/incidentUnitAssignment.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/secondaryIncidentUnitAssignment.unit.spec.jsx
Labels: BAH

#9123 [All Claims] 781 incident location
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/content/incidentLocation.jsx
  src/applications/disability-benefits/all-claims/pages/incidentLocation.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/secondaryIncidentLocation.js
  src/applications/disability-benefits/all-claims/tests/config/781.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/pages/incidentLocation.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/secondaryIncidentLocation.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9195 Bug fix 781 conclusion
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/ptsdClassification.jsx
  src/applications/disability-benefits/all-claims/content/ptsdTypeInfo.jsx
  src/applications/disability-benefits/all-claims/content/ptsdWalkthroughChoice.jsx
  src/applications/disability-benefits/all-claims/pages/choosePtsdType.js
  src/applications/disability-benefits/all-claims/pages/conclusionAssault.js
  src/applications/disability-benefits/all-claims/pages/conclusionCombat.js
  src/applications/disability-benefits/all-claims/tests/content/ptsdClassification.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9213 4142 Fix Private Medical Records release Page Bug.
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/summaryOfEvidence.jsx
  src/applications/disability-benefits/all-claims/pages/mentalHealthChanges.js
  src/applications/disability-benefits/all-claims/tests/pages/summaryOfEvidence.unit.spec.jsx
Labels: BAH

#9154 Medals or citations page 781
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/content/medals.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/medals.jsx
  src/applications/disability-benefits/all-claims/tests/config/781.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/pages/medals.unit.spec.jsx
Labels: BAH

#9133 Additional Remarks - Changes in behavior - Social 781a
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/socialBehaviorChanges.js
  src/applications/disability-benefits/all-claims/tests/pages/socialBehaviorChanges.unit.spec.jsx
Labels: BAH

#9202 [All Claims] 781 & 4142: Update ancillary upload max file size
  src/applications/disability-benefits/all-claims/constants.js
  src/applications/disability-benefits/all-claims/content/fileUploadDescriptions.jsx
  src/applications/disability-benefits/all-claims/pages/additionalDocuments.js
  src/applications/disability-benefits/all-claims/pages/privateMedicalRecords.js
  src/applications/disability-benefits/all-claims/pages/uploadPersonalPtsdDocuments.js
  src/applications/disability-benefits/all-claims/pages/uploadPtsdDocuments.js
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9232 [Facility Locator] 508 Accessibility Review Changes
  src/applications/facility-locator/components/FacilityTypeDropdown.jsx
  src/applications/facility-locator/components/ServiceTypeAhead.jsx
  src/applications/facility-locator/sass/facility-locator.scss
Labels: 508/Accessibility, front end

#9132 Additional remarks - Work Behavior Changes 781a
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/workBehaviorChanges.jsx
  src/applications/disability-benefits/all-claims/tests/pages/workBehaviorChanges.unit.spec.jsx
Labels: BAH

#9187 Bah 781 individuals involved
  src/applications/disability-benefits/all-claims/components/IndividualsInvolvedCard.jsx
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/config/schema.js
  src/applications/disability-benefits/all-claims/content/individualsInvolved.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/individualsInvolved.js
  src/applications/disability-benefits/all-claims/pages/individualsInvolvedFollowUp.js
  src/applications/disability-benefits/all-claims/tests/pages/individualsInvolved.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/individualsInvolvedFollowUp.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9243 Bah 4142 Bugs
  src/applications/disability-benefits/all-claims/content/privateMedicalRecords.jsx
  src/applications/disability-benefits/all-claims/pages/privateMedicalRecordsRelease.js
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
  src/applications/disability-benefits/all-claims/validations.js
Labels: BAH

#9166 Bah 781a Upload Secondary Sources
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/secondaryUploadSourcesChoice.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/secondaryUploadSources.js
  src/applications/disability-benefits/all-claims/pages/secondaryUploadSourcesChoice.js
  src/applications/disability-benefits/all-claims/tests/config/781.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/pages/privateMedicalRecords.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9250 [FacilityLocator] Provider Locator Address & Map Fixes
  src/applications/facility-locator/api/MockLocatorApi.js
  src/applications/facility-locator/components/LocationMap.jsx
  src/applications/facility-locator/components/search-results/LocationAddress.jsx
  src/applications/facility-locator/components/search-results/LocationDirectionsLink.jsx
  src/applications/facility-locator/constants/index.js
  src/applications/facility-locator/containers/ProviderDetail.jsx
  src/applications/facility-locator/utils/facilityAddress.js
Labels: facility locator, front end

#9230 additional info 8940 with tests
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/unemployabilityAdditionalInformation.jsx
  src/applications/disability-benefits/all-claims/tests/pages/unemployabilityAdditionalInformation.unit.spec.jsx
Labels: BAH

#9228 Bah 8940 supplemental benefits
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/supplementalBenefits.jsx
  src/applications/disability-benefits/all-claims/tests/pages/supplementalBenefits.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/property-names.unit.spec.js
Labels: BAH

#9177 4142 e2e all claims
  src/applications/disability-benefits/all-claims/tests/00-all-fields.e2e.spec.js
  src/applications/disability-benefits/all-claims/tests/disability-benefits-helpers.js
  src/applications/disability-benefits/all-claims/utils.jsx
  src/platform/testing/e2e/auth.js
Labels: BAH

#9244 Bah 8940 change order
  src/applications/disability-benefits/all-claims/config/8940/index.js
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/ancillaryFormsWizardSummary.jsx
  src/applications/disability-benefits/all-claims/pages/hospitalizationHistory.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/tests/pages/hospitalizationHistory.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/unemployabilityFormIntro.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/unemployabilityStatus.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9272 781 medals page and tests update
  src/applications/disability-benefits/all-claims/pages/medals.jsx
  src/applications/disability-benefits/all-claims/tests/pages/medals.unit.spec.jsx
Labels: BAH

#9264 [FacilityLocator] Content & Design Updates from QA Reviews
  src/applications/facility-locator/components/FacilityTypeDropdown.jsx
  src/applications/facility-locator/components/ProviderServiceDescription.jsx
  src/applications/facility-locator/containers/VAMap.jsx
Labels: content, design, facility locator, front end

#9268 [FacilityLocator] Quick "Search" Logic Reversion
  src/applications/facility-locator/containers/VAMap.jsx
Labels: facility locator, front end

#9266 781 individuals involved 2nd support screen
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/pages/individualsInvolved.js
  src/applications/disability-benefits/all-claims/pages/individualsInvolvedFollowUp.js
Labels: BAH

#9278 Use the form526 property
  src/applications/disability-benefits/all-claims/tests/schema/schema.unit.spec.js
Labels: front end, unicorns

#9251 BAH Update to 4142 schema for submission bug
  package.json
  src/applications/disability-benefits/all-claims/config/schema.js
  src/applications/disability-benefits/all-claims/pages/privateMedicalRecordsRelease.js
  yarn.lock
Labels: BAH

#9253 Next Button Bug Fix
  src/applications/disability-benefits/526EZ/components/ButtonContainer.jsx
  src/applications/disability-benefits/526EZ/components/DisabilityWizard.jsx
  src/applications/disability-benefits/526EZ/tests/components/DisabilityWizard.unit.spec.jsx
Labels: BAH

#9269 [All-claims] add cause to PTSD disabilities in transform.
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9260 4142 & 781: BAH Document type display replacement
  src/applications/disability-benefits/all-claims/config/schema.js
  src/applications/disability-benefits/all-claims/pages/additionalDocuments.js
  src/applications/disability-benefits/all-claims/pages/privateMedicalRecords.js
  src/applications/disability-benefits/all-claims/pages/secondaryUploadSources.js
  src/applications/disability-benefits/all-claims/pages/uploadPersonalPtsdDocuments.js
  src/applications/disability-benefits/all-claims/pages/uploadPtsdDocuments.js
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
  src/applications/disability-benefits/all-claims/tests/pages/privateMedicalRecords.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/uploadPtsdDocuments781.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/uploadPtsdDocuments781a.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9221 BAH 781a Other sources of information migration
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/content/secondaryOtherSources.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/secondaryOtherSources.js
  src/applications/disability-benefits/all-claims/pages/secondaryOtherSourcesHelp.js
  src/applications/disability-benefits/all-claims/tests/pages/secondaryOtherSources.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/pages/secondaryOtherSourcesHelp.unit.spec.js
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9285 Summary page shows PTSD type selected during "New Condition" question. NOT the ones selected from the checkboxes#15748
  src/applications/disability-benefits/all-claims/content/ptsdClassification.jsx
  src/applications/disability-benefits/all-claims/content/ptsdTypeInfo.jsx
  src/applications/disability-benefits/all-claims/content/summaryOfDisabilities.jsx
  src/applications/disability-benefits/all-claims/pages/choosePtsdType.js
  src/applications/disability-benefits/all-claims/tests/content/ptsdClassification.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/choosePtsdType.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/schema/maximal-test.json
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/disability-benefits/all-claims/validations.js
Labels: BAH

#9282 Bah 781 508 label bugs
  src/applications/disability-benefits/all-claims/content/incidentUnitAssignment.jsx
  src/applications/disability-benefits/all-claims/pages/additionalRemarks781.jsx
  src/applications/disability-benefits/all-claims/pages/incidentDescription.js
  src/applications/disability-benefits/all-claims/pages/incidentUnitAssignment.js
  src/applications/disability-benefits/all-claims/pages/secondaryIncidentDescription.js
  src/applications/disability-benefits/all-claims/pages/secondaryIncidentUnitAssignment.js
Labels: BAH

#9289 Limited consent bug and tests
  src/applications/disability-benefits/all-claims/pages/privateMedicalRecordsRelease.js
  src/applications/disability-benefits/all-claims/tests/pages/privateMedicalRecordsRelease.unit.spec.jsx
Labels: BAH

#9293 Form 781a Pages out of order: Changes in Social Behavior#15891
  src/applications/disability-benefits/all-claims/config/form.js
Labels: BAH

#9298 21-0781a Form Other Sources of Information Checkbox are not clearing when User changes their answer from yes to no#15926
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9199 Form 21-8940: Ability to populate Impact on recent job applications questions #14538
  src/applications/disability-benefits/all-claims/components/RecentJobApplicationField.jsx
  src/applications/disability-benefits/all-claims/config/8940/index.js
  src/applications/disability-benefits/all-claims/content/recentJobApplications.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/recentJobApplications.js
  src/applications/disability-benefits/all-claims/tests/pages/recentJobApplications.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/property-names.unit.spec.js
Labels: BAH

#9238 Form 21-8940: Ability to populate Recent Education and Training questions#14540
  src/applications/disability-benefits/all-claims/components/EducationTrainingField.jsx
  src/applications/disability-benefits/all-claims/config/8940/index.js
  src/applications/disability-benefits/all-claims/content/recentEducationTraining.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/recentEducationTraining.js
  src/applications/disability-benefits/all-claims/tests/pages/recentEducationTraining.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/property-names.unit.spec.js
Labels: BAH

#9220 Form 21-8940: Ability to populate Recent earnings interview questions#14535
  src/applications/disability-benefits/all-claims/config/8940/index.js
  src/applications/disability-benefits/all-claims/content/recentEarnedIncome.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/recentEarnedIncome.js
  src/applications/disability-benefits/all-claims/tests/pages/recentEarnedIncome.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/property-names.unit.spec.js
Labels: BAH

#9222 Form 21-8940: Ability to populate Impact on military duty interview questions#14537
  src/applications/disability-benefits/all-claims/config/8940/index.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/militaryDutyImpact.js
  src/applications/disability-benefits/all-claims/tests/pages/militaryDutyImpact.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/property-names.unit.spec.js
Labels: BAH

#9246 Form 21-8940: Ability to provide Certification#14543
  src/applications/disability-benefits/all-claims/config/8940/index.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/unemployabilityCertification.js
  src/applications/disability-benefits/all-claims/tests/pages/unemployabilityCertification.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/property-names.unit.spec.js
Labels: BAH

#9311 Bah 781 content and schema fixes
  src/applications/disability-benefits/all-claims/content/incidentDate.jsx
  src/applications/disability-benefits/all-claims/content/incidentLocation.jsx
  src/applications/disability-benefits/all-claims/content/incidentSupport.jsx
  src/applications/disability-benefits/all-claims/pages/secondaryIncidentAuthorities.js
  src/applications/disability-benefits/all-claims/pages/secondaryIncidentDescription.js
  src/applications/disability-benefits/all-claims/pages/secondaryOtherSources.js
  src/applications/disability-benefits/all-claims/pages/secondaryOtherSourcesHelp.js
  src/applications/disability-benefits/all-claims/pages/secondaryUploadSources.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BAH

#9314 Missing "or" on authorities field name
  src/applications/disability-benefits/all-claims/pages/secondaryIncidentAuthorities.js
Labels: BAH
