Repository department-of-veterans-affairs/vets-website, pull requests merged in 2018-06, with the labels that each got.

#7806 AsyncDisplayWidget
  src/applications/disability-benefits/526EZ/components/AsyncDisplayWidget.jsx
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/veteranInfo.js
  src/applications/disability-benefits/526EZ/sass/disability-benefits.scss
  src/applications/disability-benefits/526EZ/tests/components/AsyncDisplayWidget.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/veteranInformation.unit.spec.jsx
Labels: front end, unicorns

#7815 Added empty state messages for Rx.
  src/applications/rx/containers/Active.jsx
  src/applications/rx/containers/History.jsx
  src/applications/rx/reducers/prescriptions.js
Labels: griffin, rx

#7807 Added Health Records E2E test.
  src/applications/health-records/containers/DownloadPage.jsx
  src/applications/health-records/containers/Main.jsx
  src/applications/health-records/tests/00-required.e2e.spec.js
  src/applications/health-records/tests/health-records-helpers.js
  src/platform/testing/e2e/auth.js
Labels: blue button, griffin

#7824 Fixed blank greeting when user has null first name.
  src/platform/site-wide/user-nav/selectors.js
  src/platform/site-wide/user-nav/tests/selectors.unit.spec.js
Labels: identity

#7829 retry around yarn install
  Jenkinsfile
Labels: in progress

#7830 Vet360 profile
  src/applications/personalization/profile360/actions/index.js
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/Address.jsx
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/PhoneSection.jsx
  src/applications/personalization/profile360/constants/countries.json
  src/applications/personalization/profile360/constants/states.json
  src/applications/personalization/profile360/reducers/index.js
  src/applications/personalization/profile360/util/local-vet360.js
Labels: in progress

#7831 Vet360 profile
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/PhoneSection.jsx
Labels: in progress

#7833 Vet360 profile updates
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/AddressSection.jsx
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/PhoneSection.jsx
Labels: in progress

#7835 Vet360 profile
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/actions/updaters.js
Labels: in progress

#7832 Add simple intro tests for edu pages
  src/applications/edu-benefits/1990/config/form.js
  src/applications/edu-benefits/1990/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990e/config/form.js
  src/applications/edu-benefits/1990e/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990n/config/form.js
  src/applications/edu-benefits/1990n/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1995/config/form.js
  src/applications/edu-benefits/1995/containers/IntroductionPage.jsx
  src/applications/edu-benefits/5490/config/form.js
  src/applications/edu-benefits/5490/containers/IntroductionPage.jsx
  src/applications/edu-benefits/5495/config/form.js
  src/applications/edu-benefits/5495/containers/IntroductionPage.jsx
  src/applications/edu-benefits/tests/1990/containers/IntroductionPage.unit.spec.jsx
  src/applications/edu-benefits/tests/1990e/containers/IntroductionPage.unit.spec.jsx
  src/applications/edu-benefits/tests/1990n/containers/IntroductionPage.unit.spec.jsx
  src/applications/edu-benefits/tests/1995/containers/IntroductionPage.unit.spec.jsx
  src/applications/edu-benefits/tests/5490/containers/IntroductionPage.unit.spec.jsx
  src/applications/edu-benefits/tests/5495/containers/IntroductionPage.unit.spec.jsx
Labels: in progress

#7837 Vet360 profile
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/Address.jsx
Labels: in progress

#7838 Profile copy updates
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/components/MilitaryInformation.jsx
  src/applications/personalization/profile360/components/PersonalInformation.jsx
  src/applications/personalization/va-profile/components/MilitaryInformation.jsx
  src/applications/personalization/va-profile/components/PersonalInformation.jsx
Labels: in progress

#7836 Update sip cards in new homepage
  src/applications/personalization/dashboard/components/FormItem.jsx
  src/applications/personalization/dashboard/helpers.jsx
Labels: in progress, rainbows

#7827 adds applicantInfoConditional
  src/applications/disability-benefits/686/config/form.js
  src/applications/disability-benefits/686/helpers.jsx
  src/applications/disability-benefits/686/tests/config/applicantInfo.unit.spec.js
  src/applications/disability-benefits/686/tests/config/applicantInfoConditional.unit.spec.js
Labels: in progress

#7825 Remove homelessness schema and use imported definition instead
  package.json
  src/applications/disability-benefits/526EZ/config/form.js
  yarn.lock
Labels: in progress

#7844 Add submitUrl
  src/applications/disability-benefits/526EZ/config/form.js
Labels: in progress

#7841 Autosuggest safety valve
  src/applications/common/schemaform/fields/AutosuggestField.jsx
Labels: in progress

#7840 Show facility name
  src/applications/disability-benefits/526EZ/helpers.jsx
Labels: in progress

#7845 Change the 526 URL
  content/pages/disability-benefits/apply/form-526-disability-claim.md
  script/build.js
  src/applications/disability-benefits/526EZ/components/ButtonContainer.jsx
  src/applications/disability-benefits/526EZ/manifest.json
  src/applications/disability-benefits/526EZ/tests/00-all-fields.e2e.spec.js
  src/applications/personalization/dashboard/helpers.jsx
  src/applications/user-profile/helpers.jsx
Labels: in progress

#7847 Update copy for HCA confirmation page
  src/applications/hca/containers/ConfirmationPage.jsx
Labels: in progress

#7851 Add element ID to Health Care Apply button
  content/includes/veteran-navigation.html
Labels: in progress

#7852 Migrate HCA to use us-forms-system
  package.json
  src/applications/hca/HealthCareApp.jsx
  src/applications/hca/config/form.js
  src/applications/hca/containers/IntroductionPage.jsx
  src/applications/hca/definitions/dependent.js
  src/applications/hca/helpers.jsx
  src/applications/hca/reducer.js
  src/applications/hca/routes.jsx
  src/applications/hca/tests/00-all-fields.e2e.spec.js
  src/applications/hca/tests/components/DemographicField.unit.spec.jsx
  src/applications/hca/validation.js
  src/platform/forms/components/ApplicantDescription.jsx
  src/platform/forms/components/ServicePeriodView.jsx
  src/platform/forms/save-in-progress/ApplicationStatus.jsx
  src/platform/forms/save-in-progress/DowntimeMessage.jsx
  src/platform/forms/save-in-progress/FormSaved.jsx
  src/platform/forms/save-in-progress/FormStartControls.jsx
  src/platform/forms/save-in-progress/MilitaryPrefillMessage.jsx
  src/platform/forms/save-in-progress/PrefillMessage.jsx
  src/platform/forms/save-in-progress/RoutedSavableApp.jsx
  src/platform/forms/save-in-progress/RoutedSavablePage.jsx
  src/platform/forms/save-in-progress/RoutedSavableReviewPage.jsx
  src/platform/forms/save-in-progress/SaveFormLink.jsx
  src/platform/forms/save-in-progress/SaveInProgressErrorPage.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/forms/save-in-progress/SaveStatus.jsx
  src/platform/forms/save-in-progress/actions.js
  src/platform/forms/save-in-progress/api.js
  src/platform/forms/save-in-progress/helpers.js
  src/platform/forms/save-in-progress/reducers.js
  src/platform/forms/save-in-progress/savedFormRequest.js
  src/platform/forms/save-in-progress/selectors.js
  src/platform/testing/e2e/form-helpers.js
  test/common/schemaform/review/00-complete-form.e2e.spec.js
  test/common/schemaform/review/01-blank-form.e2e.spec.js
  yarn.lock
Labels: in progress

#7793 10326 update error messages
  src/applications/veteran-id-card/components/RequiredVeteranView.jsx
  src/applications/veteran-id-card/config.js
  src/applications/veteran-id-card/config.jsx
  src/applications/veteran-id-card/containers/Main.jsx
  src/applications/veteran-id-card/routes.jsx
  src/applications/veteran-id-card/veteran-id-card-entry.jsx
Labels: in progress

#7839 Facilty type ahead
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/tests/helpers.unit.spec.jsx
Labels: in progress

#7846 526 address logic mg
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/primaryAddress.js
  src/applications/disability-benefits/526EZ/tests/config/primaryAddress.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/schema/initialData.js
Labels: in progress

#7843 10790 686 chap 2
  src/applications/disability-benefits/686/config/form.js
  src/applications/disability-benefits/686/helpers.jsx
  src/applications/disability-benefits/686/tests/config/veteranInfo.unit.spec.js
Labels: in progress

#7856 Profile: Refresh state for profile after Vet360 transaction completes
  src/applications/personalization/profile360/actions/updaters.js
  src/platform/site-wide/user-nav/containers/Main.jsx
  src/platform/user/profile/actions/index.js
  src/platform/user/profile/reducers/index.js
  src/platform/user/profile/utilities/index.js
Labels: in progress

#7850 Update validation for pension and burials file number
  package.json
  src/applications/burials/config/form.js
  src/applications/burials/migrations.js
  src/applications/burials/tests/migrations.unit.spec.js
  src/applications/pensions/config/form.js
  src/applications/pensions/migrations.js
  src/applications/pensions/tests/migrations.unit.spec.js
  yarn.lock
Labels: in progress

#7855 526 Chapter 2 Updated Content
  src/applications/disability-benefits/526EZ/config/form.js
Labels: in progress

#7857 Vet360 profile field copy changes
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/EmailSection.jsx
Labels: in progress

#7823 526 veteran info
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/veteranInfo.js
  src/applications/disability-benefits/526EZ/sass/disability-benefits.scss
Labels: in progress

#7860 prevent null item value
  src/applications/gi/components/search/KeywordSearch.jsx
Labels: in progress

#7834 Diagnostic code map cv
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/reference-helpers.js
  src/applications/disability-benefits/526EZ/tests/config/ratedDisabilities.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/schema/initialData.js
Labels: in progress

#7506 WIP-content-Evidence
  content/includes/breadcrumbs-playbook.html
  content/pages/disability-benefits/after-you-apply/date.md
  content/pages/disability-benefits/apply.md
  content/pages/disability-benefits/apply/claim-types.md
  content/pages/disability-benefits/apply/claim-types/fully-developed-claim.md
  content/pages/disability-benefits/apply/claim-types/in-service.md
  content/pages/disability-benefits/apply/claim-types/new-claim.md
  content/pages/disability-benefits/apply/claim-types/original-claim.md
  content/pages/disability-benefits/apply/claim-types/post-service.md
  content/pages/disability-benefits/apply/claim-types/pre-service.md
  content/pages/disability-benefits/apply/claim-types/predischarge-claim.md
  content/pages/disability-benefits/apply/claim-types/reopened-claim.md
  content/pages/disability-benefits/apply/claim-types/secondary-claim.md
  content/pages/disability-benefits/apply/claim-types/standard-claim.md
  content/pages/disability-benefits/apply/evidence.md
  content/pages/disability-benefits/apply/evidence/decision-ready-claims.md
  content/pages/disability-benefits/apply/evidence/fully-developed-disability-claims.md
  content/pages/disability-benefits/apply/evidence/standard-disability-claims.md
  content/pages/disability-benefits/apply/help.md
  content/pages/disability-benefits/conditions/exposure-to-hazardous-materials/gulf-war-illness.md
  content/pages/disability-benefits/conditions/special-claims.md
  content/pages/disability-benefits/eligibility.md
  content/pages/disability-benefits/eligibility/one-year.md
  content/pages/disability-benefits/eligibility/presumed-disability.md
  content/pages/disability-benefits/eligibility/ratings.md
  script/build.js
Labels: in progress

#7853 Update month abbreviations
  src/platform/startup/moment-setup.js
Labels: in progress

#7858 526 Chapter 3 Content
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/526EZ/helpers.jsx
Labels: in progress

#7854 Migrate first batch of forms
  package.json
  src/applications/veteran-representative/config/form.js
  src/applications/veteran-representative/containers/App.jsx
  src/applications/veteran-representative/containers/IntroductionPage.jsx
  src/applications/veteran-representative/reducers/index.js
  src/applications/veteran-representative/routes.jsx
  src/applications/veteran-representative/tests/00.veteran-representative-entry.e2e.spec.js
  src/applications/veteran-representative/validation.js
  src/applications/vic-v2/VeteranIDCardApp.jsx
  src/applications/vic-v2/components/IdentityFieldsWarning.jsx
  src/applications/vic-v2/config/form.js
  src/applications/vic-v2/containers/IntroductionPage.jsx
  src/applications/vic-v2/helpers.jsx
  src/applications/vic-v2/reducer.js
  src/applications/vic-v2/routes.jsx
  src/applications/vic-v2/tests/00-all-fields.e2e.spec.js
  src/applications/vic-v2/validation.js
  src/applications/vre/chapter31/Chapter31App.jsx
  src/applications/vre/chapter31/components/IntroductionPage.jsx
  src/applications/vre/chapter31/config/form.js
  src/applications/vre/chapter31/reducer.js
  src/applications/vre/chapter31/routes.jsx
  src/applications/vre/chapter36/Chapter36App.jsx
  src/applications/vre/chapter36/components/IntroductionPage.jsx
  src/applications/vre/chapter36/config/form.js
  src/applications/vre/chapter36/helpers.js
  src/applications/vre/chapter36/reducer.js
  src/applications/vre/chapter36/routes.jsx
  src/applications/vre/pages/veteranInfo.js
  src/applications/vre/tests/chapter31/00-all-fields.e2e.spec.js
  src/applications/vre/tests/chapter36/00-all-fields.e2e.spec.js
  yarn.lock
Labels: in progress

#7859 Migrate edu forms 1
  src/applications/edu-benefits/1990/Form1990App.jsx
  src/applications/edu-benefits/1990/config/form.js
  src/applications/edu-benefits/1990/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990/helpers.jsx
  src/applications/edu-benefits/1990/reducer.js
  src/applications/edu-benefits/1990/routes.jsx
  src/applications/edu-benefits/1990e/Form1990eApp.jsx
  src/applications/edu-benefits/1990e/config/form.js
  src/applications/edu-benefits/1990e/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990e/helpers.jsx
  src/applications/edu-benefits/1990e/reducer.js
  src/applications/edu-benefits/1990e/routes.jsx
  src/applications/edu-benefits/1990n/Form1990nApp.jsx
  src/applications/edu-benefits/1990n/config/form.js
  src/applications/edu-benefits/1990n/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990n/helpers.js
  src/applications/edu-benefits/1990n/reducer.js
  src/applications/edu-benefits/1990n/routes.jsx
  src/applications/edu-benefits/tests/1990/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/1990e/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/1990n/01-all-fields.e2e.spec.js
  src/platform/forms/pages/applicantInformation.jsx
Labels: in progress

#7849 Update 2017 yellow ribbon school list
  content/pages/education/gi-bill/yellow-ribbon.md
Labels: in progress

#7866 Migrate remaining edu forms
  src/applications/edu-benefits/1995/Form1995App.jsx
  src/applications/edu-benefits/1995/config/form.js
  src/applications/edu-benefits/1995/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1995/helpers.jsx
  src/applications/edu-benefits/1995/reducer.js
  src/applications/edu-benefits/1995/routes.jsx
  src/applications/edu-benefits/5490/Form5490App.jsx
  src/applications/edu-benefits/5490/config/form.js
  src/applications/edu-benefits/5490/containers/IntroductionPage.jsx
  src/applications/edu-benefits/5490/helpers.jsx
  src/applications/edu-benefits/5490/reducer.js
  src/applications/edu-benefits/5490/routes.jsx
  src/applications/edu-benefits/5495/Form5495App.jsx
  src/applications/edu-benefits/5495/config/form.js
  src/applications/edu-benefits/5495/containers/IntroductionPage.jsx
  src/applications/edu-benefits/5495/helpers.js
  src/applications/edu-benefits/5495/reducer.js
  src/applications/edu-benefits/5495/routes.jsx
  src/applications/edu-benefits/tests/1995/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/5490/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/5495/01-all-fields.e2e.spec.js
Labels: in progress

#7861 Separate getProfile into refresh/restore
  src/applications/personalization/dashboard/actions/index.js
  src/applications/personalization/profile360/actions/updaters.js
  src/platform/site-wide/user-nav/containers/Main.jsx
  src/platform/user/profile/actions/index.js
  src/platform/user/profile/utilities/index.js
Labels: in progress

#7865 Update front end with new pre-need and hca validations
  package.json
  src/applications/hca/config/form.js
  src/applications/hca/config/migrations.js
  src/applications/hca/tests/config/migrations.unit.spec.js
  src/applications/pre-need/config/form.jsx
  yarn.lock
Labels: in progress

#7867 Migrate second batch of forms to external library
  src/applications/disability-benefits/686/config/form.js
  src/applications/disability-benefits/686/containers/Form686App.jsx
  src/applications/disability-benefits/686/containers/IntroductionPage.jsx
  src/applications/disability-benefits/686/helpers.jsx
  src/applications/disability-benefits/686/reducers/index.js
  src/applications/disability-benefits/686/routes.jsx
  src/applications/disability-benefits/686/tests/00-all-fields.e2e.spec.js
  src/applications/disability-benefits/686/validation.js
  src/applications/personalization/dashboard/actions/index.js
  src/applications/personalization/profile360/components/PhoneSection.jsx
  src/applications/personalization/va-profile/components/PhoneSection.jsx
  src/applications/pre-need/PreNeedApp.jsx
  src/applications/pre-need/components/IntroductionPage.jsx
  src/applications/pre-need/components/ServicePeriodView.jsx
  src/applications/pre-need/config/form.jsx
  src/applications/pre-need/reducer.js
  src/applications/pre-need/routes.jsx
  src/applications/pre-need/tests/00-all-fields.e2e.spec.js
  src/applications/pre-need/utils/helpers.js
Labels: in progress

#7871 turning on warning banner for ds logon
  content/includes/homepage-warning.html
  content/pages/index.md
  src/platform/user/authentication/components/SignInModal.jsx
Labels: in progress

#7870 Update labels on 686 applicant page
  src/applications/disability-benefits/686/config/form.js
Labels: in progress

#7868 Migrate Burials Gibs Pensions
  src/applications/burials/BurialsApp.jsx
  src/applications/burials/components/IntroductionPage.jsx
  src/applications/burials/config/form.js
  src/applications/burials/definitions/toursOfDuty.js
  src/applications/burials/helpers.jsx
  src/applications/burials/reducer.js
  src/applications/burials/routes.jsx
  src/applications/burials/tests/00-all-fields.e2e.spec.js
  src/applications/pensions/PensionsApp.jsx
  src/applications/pensions/components/AdditionalSourcesField.jsx
  src/applications/pensions/components/IntroductionPage.jsx
  src/applications/pensions/components/ServicePeriodView.jsx
  src/applications/pensions/config/form.js
  src/applications/pensions/definitions/additionalSources.js
  src/applications/pensions/definitions/expectedIncome.js
  src/applications/pensions/definitions/monthlyIncome.js
  src/applications/pensions/definitions/netWorth.js
  src/applications/pensions/definitions/otherExpenses.js
  src/applications/pensions/helpers.jsx
  src/applications/pensions/migrations.js
  src/applications/pensions/reducer.js
  src/applications/pensions/routes.jsx
  src/applications/pensions/tests/00-all-fields.e2e.spec.js
  src/applications/pensions/validation.js
  src/applications/post-911-gib-status/containers/StatusPage.jsx
Labels: in progress

#7875 Switch remaining references to common/schemaform
  src/applications/edu-benefits/components/EducationView.jsx
  src/applications/edu-benefits/definitions/educationProgram.js
  src/applications/edu-benefits/definitions/postHighSchoolTrainings.js
  src/applications/edu-benefits/definitions/seniorRotc.js
  src/applications/edu-benefits/definitions/toursOfDuty.jsx
  src/applications/edu-benefits/pages/contactInformation.js
  src/applications/edu-benefits/pages/directDeposit.js
  src/applications/edu-benefits/pages/directDepositChange.js
  src/applications/edu-benefits/pages/employmentHistory.js
  src/applications/edu-benefits/pages/oldSchool.js
  src/applications/edu-benefits/pages/schoolSelection.js
  src/applications/edu-benefits/utils/educationStatus.js
  src/applications/edu-benefits/utils/labels.jsx
  src/applications/letters/containers/DownloadLetters.jsx
  src/applications/static-pages/createApplicationStatus.js
  src/applications/vre/chapter31/config/form.js
  src/platform/forms/definitions/nonMilitaryJobs.js
Labels: in progress

#7876 Skip unstable 526 facilities tests
  src/applications/disability-benefits/526EZ/tests/config/vaFacilities.unit.spec.jsx
Labels: in progress

#7879 Fix url path in pension upload config
  src/applications/pensions/config/form.js
Labels: in progress

#7880 Deletion of individual fields on vet360 profile
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/AddressSection.jsx
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/EmailSection.jsx
  src/applications/personalization/profile360/components/FormActionButtons.jsx
  src/applications/personalization/profile360/components/LoadingButton.jsx
  src/applications/personalization/profile360/components/PhoneSection.jsx
  src/applications/personalization/profile360/profile-360-entry.jsx
  src/applications/personalization/profile360/sass/profile-360.scss
Labels: in progress

#7882 removep production check
  src/applications/veteran-id-card/components/RequiredVeteranView.jsx
  src/applications/veteran-id-card/config.jsx
Labels: in progress

#7884 Update vet360 address modals for international addresses
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/Address.jsx
  src/applications/personalization/profile360/components/AddressSection.jsx
Labels: in progress

#7869 DEA and Fry scholarship dollar amount updates
  content/pages/disability-benefits/after-you-apply/date.md
  content/pages/disability-benefits/apply/claim-types.md
  content/pages/disability-benefits/eligibility/one-year.md
  content/pages/education/advanced-training-and-certifications/flight-training.md
  content/pages/education/gi-bill/survivors-dependent-assistance.md
  content/pages/education/gi-bill/survivors-dependent-assistance/dependents-education.md
Labels: in progress

#7885 Remove DOB field from 686
  src/applications/disability-benefits/686/config/form.js
  src/applications/disability-benefits/686/tests/config/veteranInfo.unit.spec.js
Labels: in progress

#7877 Update auto allowance dollar amount
  content/pages/disability-benefits/conditions/special-claims/automobile.md
Labels: in progress

#7883 526 Chapter 4 Copy Edit
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/526EZ/helpers.jsx
Labels: front end, in progress, unicorns

#7889 Update schema for preneed email change
  package.json
  yarn.lock
Labels: in progress

#7872 Profile 360 - Restructure 360 fields into containers; add 360-dedicated reducer
  src/applications/personalization/profile360/actions/index.js
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/AddressEditModal.jsx
  src/applications/personalization/profile360/components/AddressSection.jsx
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/EmailEditModal.jsx
  src/applications/personalization/profile360/components/EmailSection.jsx
  src/applications/personalization/profile360/components/PhoneEditModal.jsx
  src/applications/personalization/profile360/components/PhoneSection.jsx
  src/applications/personalization/profile360/components/ProfileView.jsx
  src/applications/personalization/profile360/components/Transaction.jsx
  src/applications/personalization/profile360/components/Vet360ProfileFieldHeading.jsx
  src/applications/personalization/profile360/components/Vet360Transaction.jsx
  src/applications/personalization/profile360/components/Vet360TransactionPending.jsx
  src/applications/personalization/profile360/containers/VAProfileApp.jsx
  src/applications/personalization/profile360/containers/Vet360ProfileField.jsx
  src/applications/personalization/profile360/containers/Vet360TransactionReporter.jsx
  src/applications/personalization/profile360/reducers/index.js
  src/applications/personalization/profile360/reducers/vet360.js
  src/applications/personalization/profile360/sass/profile-360.scss
  src/applications/personalization/profile360/selectors.js
  src/applications/personalization/profile360/util/local-vet360.js
  src/applications/personalization/profile360/util/transactions.js
Labels: in progress

#7895 Profile 360: Consolidate Update Modal behavior
  src/applications/personalization/profile360/components/AddressEditModal.jsx
  src/applications/personalization/profile360/components/AddressSection.jsx
  src/applications/personalization/profile360/components/EmailEditModal.jsx
  src/applications/personalization/profile360/components/EmailSection.jsx
  src/applications/personalization/profile360/components/PhoneEditModal.jsx
  src/applications/personalization/profile360/components/PhoneSection.jsx
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
  src/applications/personalization/profile360/containers/Vet360ProfileField.jsx
Labels: in progress

#7893 Remove flag from HCA async changes
  src/applications/hca/containers/ConfirmationPage.jsx
  src/applications/hca/helpers.jsx
  src/applications/hca/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: in progress

#7892 Remove minItems from spouse marriages
  src/applications/disability-benefits/686/config/form.js
Labels: in progress

#7842 preview build support
  Jenkinsfile
  config/webpack.config.js
  script/build.js
  src/platform/utilities/environment/index.js
Labels: in progress

#7901 put back the node filter on jenkins job
  Jenkinsfile
Labels: in progress

#7888 VA Facilities Test Fix
  src/applications/disability-benefits/526EZ/tests/config/vaFacilities.unit.spec.jsx
Labels: front end, in progress, unicorns

#7898 Profile360: Add code-specific error messaging for failed/rejected transactions
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
  src/applications/personalization/profile360/components/Vet360EditModalErrorMessage.jsx
  src/applications/personalization/profile360/components/Vet360Transaction.jsx
  src/applications/personalization/profile360/components/Vet360TransactionErrorBanner.jsx
  src/applications/personalization/profile360/components/Vet360TransactionInlineErrorMessage.jsx
  src/applications/personalization/profile360/components/Vet360TransactionPending.jsx
  src/applications/personalization/profile360/containers/Vet360TransactionReporter.jsx
  src/applications/personalization/profile360/sass/profile-360.scss
  src/applications/personalization/profile360/selectors.js
  src/applications/personalization/profile360/util/transactions.js
Labels: in progress

#7896 526 use updated address mg
  package.json
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/526EZ/constants.jsx
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/primaryAddress.js
  src/applications/disability-benefits/526EZ/tests/config/primaryAddress.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/privateMedicalRecordsRelease.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/privateRecordReleases.unit.spec.jsx
  yarn.lock
Labels: in progress

#7878 import from moment startup to fix unstable test
  src/applications/claims-status/components/ClaimsDecision.jsx
Labels: in progress

#7904 Vet360 profile updates for address/phone
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/Address.jsx
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/EmailSection.jsx
  src/applications/personalization/profile360/components/PhoneEditModal.jsx
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
  src/applications/personalization/profile360/sass/profile-360.scss
  src/applications/personalization/profile360/util/local-vet360.js
Labels: in progress

#7902 Swapped in proper 526 content
  content/pages/disability-benefits/apply/form-526-disability-claim.md
Labels: in progress

#7906 Profile 360: Tweaks
  src/applications/personalization/profile360/components/EmailEditModal.jsx
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
  src/applications/personalization/profile360/containers/Vet360ProfileField.jsx
Labels: in progress

#7891 Refactored Facility Locator dropdown components
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/components/FacilityTypeDropdown.jsx
  src/applications/facility-locator/components/Listbox.jsx
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/components/Select.jsx
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/00-required.e2e.spec.js
  src/applications/facility-locator/tests/01-accessibility.e2e.spec.js
  src/applications/facility-locator/utils/helpers.js
Labels: facility locator, griffin, in progress

#7903 526 -- Change all imports to schemaform library
  src/applications/disability-benefits/526EZ/Form526EZApp.jsx
  src/applications/disability-benefits/526EZ/actions/index.js
  src/applications/disability-benefits/526EZ/components/FormStartControls.jsx
  src/applications/disability-benefits/526EZ/components/IntroductionPage.jsx
  src/applications/disability-benefits/526EZ/components/ReviewCardField.jsx
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/526EZ/disabilityIncreaseEntry.js
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/primaryAddress.js
  src/applications/disability-benefits/526EZ/reducer.js
  src/applications/disability-benefits/526EZ/routes.jsx
  src/applications/disability-benefits/526EZ/tests/00-all-fields.e2e.spec.js
Labels: in progress

#7862 526 ITF redux
  src/applications/disability-benefits/526EZ/actions/index.js
  src/applications/disability-benefits/526EZ/reducer.js
  src/applications/disability-benefits/526EZ/tests/actions/actions.unit.spec.js
  src/applications/disability-benefits/526EZ/tests/itfData.js
  src/applications/disability-benefits/526EZ/tests/reducers.unit.spec.js
Labels: in progress

#7873 Hook up payment information to api
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/paymentInfo.js
  src/applications/disability-benefits/526EZ/pages/paymentInfo.jsx
  src/applications/disability-benefits/526EZ/tests/config/paymentInformation.unit.spec.jsx
Labels: in progress

#7910 Define constants for backend services
  src/applications/claims-status/containers/ClaimsStatusApp.jsx
  src/applications/claims-status/containers/YourClaimsPage.jsx
  src/applications/claims-status/containers/YourClaimsPageV2.jsx
  src/applications/claims-status/tests/components/ClaimsStatusApp.unit.spec.jsx
  src/applications/health-beta/containers/HealthBetaEnrollment.jsx
  src/applications/health-records/containers/HealthRecordsApp.jsx
  src/applications/id-card-beta/containers/IDCardBetaEnrollment.jsx
  src/applications/letters/containers/LettersApp.jsx
  src/applications/messaging/containers/MessagingApp.jsx
  src/applications/personalization/account/containers/AccountApp.jsx
  src/applications/personalization/dashboard/containers/ClaimsAppealsWidget.jsx
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/applications/personalization/dashboard/containers/MessagingWidget.jsx
  src/applications/personalization/profile360/containers/VAProfileApp.jsx
  src/applications/personalization/va-profile/containers/VAProfileApp.jsx
  src/applications/post-911-gib-status/containers/Post911GIBStatusApp.jsx
  src/applications/rx/containers/RxRefillsApp.jsx
  src/applications/user-profile/containers/UserProfileApp.jsx
  src/applications/veteran-id-card/containers/VeteranIDCard.jsx
  src/applications/vic-v2/containers/IntroductionPage.jsx
  src/applications/vic-v2/helpers.jsx
  src/platform/user/authorization/components/RequiredLoginView.jsx
  src/platform/user/authorization/containers/MHVApp.jsx
  src/platform/user/profile/constants/backendServices.js
  src/platform/user/tests/authorization/components/RequiredLoginView.unit.spec.jsx
  src/platform/user/tests/authorization/containers/MHVApp.unit.spec.jsx
Labels: in progress

#7913 Profile 360: Check for vet360 in available services before rendering contact information
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/IdentityVerification.jsx
  src/applications/personalization/profile360/components/MVIError.jsx
  src/applications/personalization/profile360/components/MissingVet360IDError.jsx
  src/applications/personalization/profile360/components/ProfileView.jsx
  src/applications/personalization/profile360/containers/VAProfileApp.jsx
  src/applications/personalization/profile360/selectors.js
  src/platform/monitoring/DowntimeNotification/config/services.js
Labels: in progress

#7911 Disability wizard content fix
  src/applications/disability-benefits/526EZ/tests/components/DisabilityWizard.unit.spec.jsx
  src/applications/disability-benefits/526EZ/wizardHelpers.jsx
Labels: in progress

#7915 Profile360: Add flow for validations
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/components/AddressEditModal.jsx
  src/applications/personalization/profile360/components/EmailEditModal.jsx
  src/applications/personalization/profile360/components/PhoneEditModal.jsx
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
  src/applications/personalization/profile360/selectors.js
Labels: in progress

#7907 526 chapter one content mg
  src/applications/disability-benefits/526EZ/components/ReviewCardField.jsx
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/526EZ/constants.jsx
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/paymentInfo.jsx
  src/applications/disability-benefits/526EZ/pages/primaryAddress.js
Labels: in progress

#7921 Remove unnecessary 'note' at bottom of paymentInfo page
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/paymentInfo.jsx
Labels: in progress

#7908 content/WIP add new HC metas
  content/pages/health-care/about-va-health-care/assisted-living-and-home-health-care.md
  content/pages/health-care/about-va-health-care/dental-care.md
  content/pages/health-care/about-va-health-care/va-health-care-and-other-insurance.md
  content/pages/health-care/about-va-health-care/vision-care.md
  content/pages/health-care/about-va-health-care/where-you-get-care.md
  content/pages/health-care/about-va-health-care/your-care-team.md
  content/pages/health-care/after-you-apply.md
  content/pages/health-care/apply.md
  content/pages/health-care/eligibility.md
  content/pages/health-care/health-conditions.md
  content/pages/health-care/health-conditions/conditions-related-to-service-era.md
  content/pages/health-care/health-conditions/conditions-related-to-service-era/cold-war-era.md
  content/pages/health-care/health-conditions/conditions-related-to-service-era/gulf-war.md
  content/pages/health-care/health-conditions/conditions-related-to-service-era/iraq-war.md
  content/pages/health-care/health-conditions/conditions-related-to-service-era/operation-enduring-freedom.md
  content/pages/health-care/health-conditions/conditions-related-to-service-era/vietnam-war.md
  content/pages/health-care/health-conditions/mental-health.md
  content/pages/health-care/health-conditions/mental-health/ptsd.md
  content/pages/health-care/health-conditions/military-sexual-trauma.md
Labels: in progress

#7919 Rename services to externalServices
  src/applications/burials/config/form.js
  src/applications/facility-locator/containers/FacilityLocatorApp.jsx
  src/applications/hca/config/form.js
  src/applications/health-records/containers/HealthRecordsApp.jsx
  src/applications/letters/containers/LettersApp.jsx
  src/applications/messaging/containers/MessagingApp.jsx
  src/applications/pensions/config/form.js
  src/applications/personalization/account/containers/AccountApp.jsx
  src/applications/personalization/dashboard/containers/ClaimsAppealsWidget.jsx
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/DowntimeBanner.jsx
  src/applications/personalization/profile360/components/Hero.jsx
  src/applications/personalization/profile360/components/MilitaryInformation.jsx
  src/applications/personalization/profile360/components/PersonalInformation.jsx
  src/applications/personalization/profile360/components/ProfileView.jsx
  src/applications/personalization/va-profile/components/ContactInformation.jsx
  src/applications/personalization/va-profile/components/DowntimeBanner.jsx
  src/applications/personalization/va-profile/components/Hero.jsx
  src/applications/personalization/va-profile/components/MilitaryInformation.jsx
  src/applications/personalization/va-profile/components/PersonalInformation.jsx
  src/applications/personalization/va-profile/components/ProfileView.jsx
  src/applications/post-911-gib-status/containers/Post911GIBStatusApp.jsx
  src/applications/rx/containers/RxRefillsApp.jsx
  src/applications/user-profile/containers/UserProfileApp.jsx
  src/applications/veteran-id-card/containers/VeteranIDCard.jsx
  src/platform/forms/save-in-progress/RoutedSavableReviewPage.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/monitoring/DowntimeNotification/components/Banner.jsx
  src/platform/monitoring/DowntimeNotification/components/Down.jsx
  src/platform/monitoring/DowntimeNotification/components/DowntimeApproaching.jsx
  src/platform/monitoring/DowntimeNotification/config/externalServiceStatus.js
  src/platform/monitoring/DowntimeNotification/config/externalServices.js
  src/platform/monitoring/DowntimeNotification/containers/DowntimeNotification.jsx
  src/platform/monitoring/DowntimeNotification/index.jsx
  src/platform/monitoring/DowntimeNotification/tests/DowntimeNotification.unit.spec.jsx
  src/platform/monitoring/DowntimeNotification/tests/helpers.unit.spec.js
  src/platform/monitoring/DowntimeNotification/util/helpers.js
  src/platform/user/authentication/components/SignInModal.jsx
Labels: downtime notifications, in progress

#7920 Remove initial data from form config
  src/applications/disability-benefits/526EZ/config/form.js
Labels: in progress

#7922 Transform pre-filled disabilities
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/tests/helpers.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/schema/initialData.js
Labels: in progress

#7923 Profile 360: Add announcement for Vet360; add explanation of Contact Information
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/ContactInformationExplanation.jsx
  src/platform/site-wide/announcements/components/Profile360Intro.jsx
  src/platform/site-wide/announcements/config/index.js
Labels: in progress

#7881 [WIP] 10920-breadcrumb-static-content
  assets/js/breadcrumbs/mobile-breadcrumb.js
  content/includes/breadcrumbs.html
  content/pages/account/index.md
  content/pages/burials-and-memorials/application/530.md
  content/pages/burials-and-memorials/pre-need/form-10007-apply-for-eligibility.md
  content/pages/disability-benefits/apply/form-526-disability-claim.md
  content/pages/education/apply-for-education-benefits/application/1990.md
  content/pages/education/apply-for-education-benefits/application/1990E.md
  content/pages/education/apply-for-education-benefits/application/1990N.md
  content/pages/education/apply-for-education-benefits/application/1995.md
  content/pages/education/apply-for-education-benefits/application/5490.md
  content/pages/education/apply-for-education-benefits/application/5495.md
  content/pages/employment/vocational-rehab-and-employment/application/chapter31.md
  content/pages/employment/vocational-rehab-and-employment/application/chapter36.md
  content/pages/health-care/apply/application.md
  content/pages/pension/application/527EZ.md
  content/pages/profile/index.md
  content/pages/veteran-id-card/apply.md
  content/pages/veteran-id-card/index.md
  package.json
  script/build.js
  script/metalsmith/breadcrumbTransformer.js
  yarn.lock
Labels: in progress

#7926 Profile 360 - Add category-level transaction messaging
  src/applications/personalization/profile360/actions/index.js
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/Vet360TransactionPending.jsx
  src/applications/personalization/profile360/constants/vet360.js
  src/applications/personalization/profile360/containers/Vet360PendingTransactionCategory.jsx
  src/applications/personalization/profile360/sass/profile-360.scss
  src/applications/personalization/profile360/selectors.js
  src/applications/personalization/profile360/util/local-vet360.js
Labels: in progress

#7928 Dashboard - add additional check for document hostname before capturing index route
  src/platform/site-wide/user-nav/components/PersonalizationDropdown.jsx
Labels: in progress

#7914 Add primaryPhone and emailAddress as required
  src/applications/disability-benefits/526EZ/pages/primaryAddress.js
  src/applications/disability-benefits/526EZ/tests/config/primaryAddress.unit.spec.jsx
Labels: front end, in progress, unicorns

#7932 Fix unit test after moment-setup update
  src/applications/claims-status/components/ClaimsDecision.jsx
  src/applications/claims-status/tests/components/ClaimsDecision.unit.spec.jsx
Labels: in progress

#7848 Add drop down
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/components/profile/Programs.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/selectors/calculator.js
  src/applications/gi/tests/reducers/calculator.unit.spec.js
  src/applications/gi/tests/selectors/calculator.unit.spec.js
Labels: in progress, rainbows

#7934 Vet360 address in-line validations
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/components/AddressEditModal.jsx
  src/applications/personalization/profile360/components/EmailEditModal.jsx
  src/applications/personalization/profile360/components/PhoneEditModal.jsx
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
Labels: in progress

#7736 Accommodate MHV upgrade flow and error handling
  src/applications/personalization/account/components/AccountMain.jsx
  src/applications/personalization/account/components/TermsAndConditions.jsx
  src/applications/personalization/account/containers/AccountApp.jsx
  src/applications/user-profile/containers/UserDataSection.jsx
  src/applications/user-profile/containers/UserProfileApp.jsx
  src/platform/user/authorization/containers/MHVApp.jsx
  src/platform/user/profile/actions/mhv.js
  src/platform/user/profile/reducers/index.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/tests/authorization/containers/MHVApp.unit.spec.jsx
  src/platform/user/tests/profile/reducers/index.unit.spec.js
Labels: griffin, identity, in progress

#7641 [WIP] GIBCT Institution STEM indicator
  src/applications/gi/components/profile/AdditionalInformation.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/reducers/filter.js
  src/applications/gi/reducers/search.js
  src/applications/gi/tests/reducers/filter.unit.spec.js
Labels: in progress, rainbows

#7935 Profile 360 - add delay before refreshProfile
  src/applications/personalization/profile360/actions/misc.js
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/Address.jsx
  src/applications/personalization/profile360/components/AddressEditModal.jsx
  src/applications/personalization/profile360/components/PersonalInformation.jsx
  src/applications/personalization/profile360/containers/Vet360ProfileField.jsx
  src/applications/personalization/profile360/manifest.json
  src/applications/personalization/va-profile/components/PersonalInformation.jsx
Labels: in progress

#7936 Revert "Accommodate MHV upgrade flow and error handling (#7736)"
  src/applications/personalization/account/components/AccountMain.jsx
  src/applications/personalization/account/components/TermsAndConditions.jsx
  src/applications/personalization/account/containers/AccountApp.jsx
  src/applications/user-profile/containers/UserDataSection.jsx
  src/applications/user-profile/containers/UserProfileApp.jsx
  src/platform/user/authorization/containers/MHVApp.jsx
  src/platform/user/profile/actions/mhv.js
  src/platform/user/profile/reducers/index.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/tests/authorization/containers/MHVApp.unit.spec.jsx
  src/platform/user/tests/profile/reducers/index.unit.spec.js
Labels: griffin, identity, in progress

#7933 Flip the production bit
  src/applications/disability-benefits/526EZ/manifest.json
Labels: in progress

#7927 526 vet info connect cv
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/526EZ/pages/veteranInfo.js
  src/applications/disability-benefits/526EZ/tests/config/veteranInformation.unit.spec.jsx
Labels: in progress

#7900 Centralize localStorage access into module
  content/includes/footer.html
  package.json
  src/applications/discharge-wizard/containers/GuidancePage.jsx
  src/applications/discharge-wizard/containers/RequestDD214.jsx
  src/applications/personalization/account/components/AccountMain.jsx
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/applications/personalization/dashboard/tests/containers/DashboardApp.unit.spec.jsx
  src/platform/site-wide/announcements/actions/index.js
  src/platform/site-wide/announcements/index.jsx
  src/platform/site-wide/announcements/tests/actions/index.unit.spec.js
  src/platform/utilities/storage/localStorage.js
  yarn.lock
Labels: in progress

#7894 9369 closed schools
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/sass/partials/_gi-search-page.scss
Labels: in progress

#7938 Profile360 UAT Tweaks
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
Labels: in progress

#7942 Updated copy for vet360 profile
  src/applications/personalization/profile360/components/ContactInformationExplanation.jsx
Labels: in progress

#7939 Profile360: Add reducer property for storing pending transaction requests
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/reducers/vet360.js
  src/applications/personalization/profile360/util/local-vet360.js
Labels: in progress

#7890 Add SGLI Open Enrollment System instructions by service branch
  content/pages/life-insurance/options-and-eligibility/sgli.md
Labels: in progress

#7734 Content wip crisis
  content/pages/disability-benefits/conditions/ptsd.md
  content/pages/employment/index.md
  content/pages/health-care/health-conditions/mental-health.md
  content/pages/health-care/health-conditions/mental-health/depression.md
  content/pages/health-care/health-conditions/mental-health/ptsd.md
  content/pages/health-care/health-conditions/mental-health/suicide-prevention.md
  content/pages/health-care/health-conditions/military-sexual-trauma.md
  content/pages/health-care/health-conditions/substance-use-problems.md
  content/pages/health-care/index.md
  content/pages/housing-assistance/index.md
Labels: in progress

#7887 Pension rate updates
  content/pages/pension/rates.md
  content/pages/pension/survivors-pension/rates.md
Labels: in progress

#7943 Profile 360 - remove test code
  src/applications/personalization/profile360/actions/updaters.js
  src/platform/user/profile/actions/index.js
Labels: in progress

#7916 11133 housing zip
  src/applications/gi/actions/index.js
  src/applications/gi/components/profile/Calculator.jsx
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/selectors/calculator.js
  src/applications/gi/tests/actions/index.unit.spec.js
  src/applications/gi/tests/reducers/calculator.unit.spec.js
Labels: in progress

#7945 change order of imports on entry file
  src/applications/veteran-id-card/veteran-id-card-entry.jsx
Labels: in progress

#7946 Profile360: Limit messaging to just one success, one error banner
  src/applications/personalization/profile360/actions/updaters.js
  src/applications/personalization/profile360/containers/Vet360TransactionReporter.jsx
  src/applications/personalization/profile360/reducers/vet360.js
  src/applications/personalization/profile360/selectors.js
  src/platform/user/profile/actions/index.js
Labels: in progress

#7948 Profile360: Add additional Vet360 Address error codes to set
  src/applications/personalization/profile360/util/transactions.js
Labels: in progress

#7949 Profile360: Fix for Edit Phone Field input value not clearing after corresponding field is deleted
  src/applications/personalization/profile360/components/PhoneEditModal.jsx
Labels: in progress

#7944 360 profile formatting for military address
  src/applications/personalization/profile360/components/Address.jsx
  src/applications/personalization/profile360/components/AddressSection.jsx
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/Vet360EditModal.jsx
  src/applications/personalization/profile360/util/local-vet360.js
  src/platform/forms/address/data/states.json
  src/platform/forms/address/index.js
Labels: in progress
