Repository department-of-veterans-affairs/vets-website, pull requests merged in 2018-08, with the labels that each got.

#7937 MHV Upgrade Launch
  src/applications/personalization/account/components/AccountMain.jsx
  src/applications/personalization/account/components/TermsAndConditions.jsx
  src/applications/personalization/account/containers/AccountApp.jsx
  src/applications/personalization/account/tests/components/AccountMain.unit.spec.js
  src/applications/static-pages/tests/application-status.e2e.spec.js
  src/platform/testing/e2e/auth.js
  src/platform/user/authorization/containers/MHVApp.jsx
  src/platform/user/profile/actions/mhv.js
  src/platform/user/profile/reducers/index.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/tests/authorization/containers/MHVApp.unit.spec.jsx
  src/platform/user/tests/profile/reducers/index.unit.spec.js
Labels: griffin, identity, in progress

#8104 Revert "Merge pull request #7937 from department-of-veterans-affairs/…
  src/applications/personalization/account/components/AccountMain.jsx
  src/applications/personalization/account/components/TermsAndConditions.jsx
  src/applications/personalization/account/containers/AccountApp.jsx
  src/applications/personalization/account/tests/components/AccountMain.unit.spec.js
  src/applications/static-pages/tests/application-status.e2e.spec.js
  src/platform/testing/e2e/auth.js
  src/platform/user/authorization/containers/MHVApp.jsx
  src/platform/user/profile/actions/mhv.js
  src/platform/user/profile/reducers/index.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/tests/authorization/containers/MHVApp.unit.spec.jsx
  src/platform/user/tests/profile/reducers/index.unit.spec.js
Labels: griffin

#8118 MHV Upgrade Launch
  src/applications/personalization/account/components/AccountMain.jsx
  src/applications/personalization/account/components/TermsAndConditions.jsx
  src/applications/personalization/account/containers/AccountApp.jsx
  src/applications/personalization/account/tests/components/AccountMain.unit.spec.js
  src/applications/static-pages/tests/application-status.e2e.spec.js
  src/platform/testing/e2e/auth.js
  src/platform/user/authorization/components/RequiredLoginView.jsx
  src/platform/user/authorization/containers/MHVApp.jsx
  src/platform/user/profile/actions/mhv.js
  src/platform/user/profile/reducers/index.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/tests/authorization/containers/MHVApp.unit.spec.jsx
  src/platform/user/tests/profile/reducers/index.unit.spec.js
Labels: griffin, identity

#6841 [DO NOT MERGE] Content and go live branch for pre-need form
  content/includes/veteran-navigation.html
  content/pages/burials-and-memorials/pre-need.md
Labels: in progress

#8144 adding dental to list of health services
  src/applications/facility-locator/config.js
Labels: facility locator

#8162 Block first SiP call
  src/applications/disability-benefits/526EZ/components/FormStartControls.jsx
  src/applications/disability-benefits/526EZ/components/IntroductionPage.jsx
  src/platform/forms/save-in-progress/FormStartControls.jsx
  src/platform/forms/save-in-progress/RoutedSavableApp.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
Labels: front end, unicorns

#8168 Return promise from queryForFacilities tests
  src/applications/disability-benefits/526EZ/tests/helpers.unit.spec.jsx
Labels: front end, unicorns

#8161 Refactor ITFWrapper
  src/applications/disability-benefits/all-claims/containers/ITFWrapper.jsx
Labels: front end, unicorns

#8176 Double restart bugfix cv
  src/applications/disability-benefits/526EZ/Form526EZApp.jsx
  src/applications/disability-benefits/526EZ/components/FormStartControls.jsx
  src/applications/disability-benefits/526EZ/components/IntroductionPage.jsx
  src/platform/forms/save-in-progress/FormStartControls.jsx
  src/platform/forms/save-in-progress/RoutedSavableApp.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/forms/save-in-progress/actions.js
  src/platform/forms/tests/save-in-progress/RoutedSavableApp.unit.spec.jsx
Labels: front end, unicorns

#8189 Refresh user object after MHV upgrade to update access to health services
  src/platform/user/authorization/containers/MHVApp.jsx
  src/platform/user/tests/authorization/containers/MHVApp.unit.spec.jsx
Labels: griffin, identity

#8214 Fix hanging spinner on disability benefits pages
  content/includes/footer.html
  content/pages/disability-benefits/index.md
  docs/ReactOnStaticPages.md
  src/applications/static-pages/static-page-widgets.js
  src/applications/static-pages/tests/static-page-widgets.unit.spec.js
Labels: unicorns

#8212 Fetch user profile after MHV upgrade and before UI updates.
  src/applications/disability-benefits/526EZ/components/IntroductionPage.jsx
  src/applications/hca/tests/hca-helpers.js
  src/applications/personalization/dashboard/components/FormItem.jsx
  src/platform/forms/save-in-progress/ApplicationStatus.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/forms/tests/save-in-progress/ApplicationStatus.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/SaveInProgressIntro.unit.spec.jsx
  src/platform/user/authorization/containers/MHVApp.jsx
  src/platform/user/profile/actions/mhv.js
  src/platform/user/profile/reducers/index.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/tests/authorization/containers/MHVApp.unit.spec.jsx
  src/platform/user/tests/profile/reducers/index.unit.spec.js
Labels: griffin, identity

#8209 adding new page
  va-gov/pages/health-care/get-medical-records.md
  va-gov/pages/health-care/order-hearing-aid-batteries-prosthetic-socks.md
  va-gov/pages/health-care/refill-track-prescriptions.md
  va-gov/pages/health-care/secure-messaging.md
  va-gov/pages/health-care/update-health-information.md
  va-gov/pages/health-care/view-test-lab-results.md
  va-gov/pages/health-care/wellness-programs.md
Labels: content

#8239 Revert "Deleted the email-gathering page and its javascript (#8153)"
  content/pages/disability-benefits/increase-claims-testing.md
  src/applications/disability-benefits/526EZ/components/create526EmailForm.jsx
  src/applications/static-pages/static-pages-entry.js
Labels: front end, unicorns

#8230 Update Fry Scholarship time limits
  content/pages/education/gi-bill/survivors-dependent-assistance/fry-scholarship.md
Labels: content, ed benefits

#8240 Adding asterisks back to clarify eligibility
  content/pages/housing-assistance/adaptive-housing-grants.md
Labels: content, nebula

#8283 Revert "526 confirmation poll (#8113)"
  src/applications/disability-benefits/526EZ/components/ConfirmationPoll.jsx
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/526EZ/constants.js
  src/applications/disability-benefits/526EZ/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/526EZ/content/confirmation-poll.jsx
  src/applications/disability-benefits/526EZ/pages/paymentInfo.jsx
  src/applications/disability-benefits/526EZ/tests/components/ConfirmationPoll.unit.spec.jsx
  src/platform/testing/unit/helpers.js
  src/platform/utilities/api/index.js
Labels: front end, unicorns

#8284 526 confirmation poll take 2
  src/applications/disability-benefits/526EZ/components/ConfirmationPoll.jsx
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/526EZ/constants.js
  src/applications/disability-benefits/526EZ/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/526EZ/content/confirmation-poll.jsx
  src/applications/disability-benefits/526EZ/pages/paymentInfo.jsx
  src/applications/disability-benefits/526EZ/tests/components/ConfirmationPoll.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/containers/ConfirmationPage.unit.spec.jsx
  src/platform/testing/unit/helpers.js
Labels: front end, unicorns

#8224 Fixed redirect issues with MHV upgrade flow.
  src/platform/user/authorization/containers/MHVApp.jsx
Labels: griffin, identity
