Repository department-of-veterans-affairs/vets-website, pull requests merged in 2018-09, with the labels that each got.

#8292 Fixed incorrect object path resulting in incorrect last updated date for facility services
  src/applications/facility-locator/components/ServicesAtFacility.jsx
Labels: facility locator, griffin

#8297 Content/wip/aug avg disability claim days
  content/pages/disability-benefits/after-you-apply.md
  content/pages/disability-benefits/apply.md
Labels: content

#8299 Open redux dev tools on staging
  src/platform/startup/store.js
Labels: front end, sitewide

#8315 Fixed login functionality in user nav and consolidated render logic with use of feature flag
  src/platform/site-wide/index.js
  src/platform/site-wide/user-nav/components/HelpMenu.jsx
  src/platform/site-wide/user-nav/components/SearchHelpSignIn.jsx
  src/platform/site-wide/va-gov-user-nav/components/HelpMenu.jsx
  src/platform/site-wide/va-gov-user-nav/components/SearchHelpSignIn.jsx
  src/platform/site-wide/va-gov-user-nav/containers/Main.jsx
  src/platform/site-wide/va-gov-user-nav/index.js
  src/platform/site-wide/va-gov-user-nav/sass/user-nav.scss
  src/platform/site-wide/va-gov-user-nav/selectors.js
  src/platform/site-wide/va-gov-user-nav/tests/components/SearchHelpSignIn.unit.spec.jsx
  va-gov/includes/top-nav.html
Labels: identity

#8316 Brand consolidation feature flag for relevant user nav components
  src/platform/brand-consolidation/feature-flag.js
  src/platform/site-wide/user-nav/components/HelpMenu.jsx
  src/platform/site-wide/user-nav/components/SearchHelpSignIn.jsx
Labels: identity

#8336 Fixing typo in MVI alert box message
  src/applications/personalization/account/components/AccountMain.jsx
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/applications/personalization/profile360/components/MVIError.jsx
  src/applications/personalization/profile360/vet360/components/base/TransactionErrorBanner.jsx
Labels: content, nebula

#8385 Port search.gov from vets.gov to preview.va.gov
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: search

#8403 ReviewCardField -- Render data type field on review
  src/applications/disability-benefits/all-claims/components/ReviewCardField.jsx
  src/applications/disability-benefits/all-claims/tests/components/ReviewCardField.unit.spec.jsx
  src/platform/forms/save-in-progress/RoutedSavableReviewPage.jsx
  src/platform/forms/save-in-progress/selectors.js
Labels: front end, unicorns

#8286 creating page
  va-gov/pages/education/change-gi-bill-benefits.md
Labels: content

#8473 Modifying API_URL for preview site to point to prod api
  src/platform/utilities/environment/index.js
Labels: devops
