Repository department-of-veterans-affairs/vets-website, pull requests merged in 2019-10, with the labels that each got.

#10803 Add composer.json to allow CMS to install and update via packagist.org.
  composer.json
Labels: cms

#10834 10833 - updated text on receive text message checkbox
  src/platform/user/profile/vet360/components/PhoneField/EditModal.jsx
  src/platform/user/profile/vet360/containers/ProfileField.jsx
  src/platform/user/profile/vet360/containers/ReceiveTextMessages.jsx
Labels: By Light, front end, notifications-settings

#10838 Change LocationHours to a stateless component and show raw hours string
  src/applications/facility-locator/components/LocationHours.jsx
  src/applications/facility-locator/tests/components/LocationHours.unit.spec.js
  src/applications/facility-locator/tests/helpers.unit.spec.js
  src/applications/facility-locator/utils/facilityHours.js
  src/applications/facility-locator/utils/helpers.js
Labels: VSA, facility locator, front end

#10835 Add update-robots build plugin
  src/site/stages/build/index.js
  src/site/stages/build/plugins/update-robots.js
Labels: VSA, current sprint, front end

#10840 10833 notifications text
  src/platform/user/profile/vet360/components/PhoneField/EditModal.jsx
  src/platform/user/profile/vet360/containers/ReceiveTextMessages.jsx
Labels: By Light, front end, notifications-settings

#10820 19738: CT 116: Add ALL SCO Contact Details to VET TEC Profile Page
  src/applications/gi/components/vet-tec/VetTecContactInformation.jsx
  src/applications/gi/components/vet-tec/VetTecScoContact.jsx
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
Labels: BAH

#10788 19652 Fix mailing/physical address combo problems
  .gitignore
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/profile/SchoolLocations.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/components/vet-tec/VetTecSearchResult.jsx
  src/applications/gi/reducers/profile.js
  src/applications/gi/reducers/search.js
  src/applications/gi/reducers/utility.js
  src/applications/gi/tests/reducers/utility.unit.spec.js
  src/applications/gi/utils/helpers.js
Labels: BAH, BAH-QA-needed

#10858 10857 Update isTextPermitted Checkbox Handling in Edit Modal for Mobile Phone
  src/platform/user/profile/vet360/components/PhoneField/EditModal.jsx
Labels: By Light, front end, notifications-settings

#10856 Add ability to change programs when viewing a vet tec profile
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/routes.jsx
  src/applications/gi/sass/gi.scss
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
  src/applications/gi/tests/containers/ProfilePage.unit.spec.js
Labels: BAH

#10854 CT 107: Improve profile question clarity and workflow for international institutions #19703
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/selectors/calculator.js
  src/applications/gi/tests/components/CalculatorForm.unit.spec.jsx
  src/applications/gi/tests/components/SchoolLocations.unit.spec.jsx
  src/applications/gi/tests/gibct-helpers.js
  src/applications/gi/utils/helpers.js
Labels: BAH, BAH-QA-needed

#10867 frontend changes for Versioned School Certifying Official Backend changes
  src/applications/gi/components/vet-tec/VetTecContactInformation.jsx
  src/applications/gi/components/vet-tec/VetTecScoContact.jsx
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
Labels: BAH

#10868 Remove "(optional)" text from street address labels
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/letters/components/Address.jsx
  src/platform/user/profile/vet360/components/AddressField/AddressForm.jsx
Labels: VSA, content, front end, site design, unicorns, website

#10887 Checking "I'll be taking classes outside of the U.S. and U.S. territories” does not use VA/DOD national average. #10889
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/selectors/calculator.js
Labels: BAH

#10880 Migrate letters app address updater to vet360
  src/applications/letters/containers/AddressSection.jsx
  src/applications/letters/containers/Main.jsx
  src/applications/letters/reducers/index.js
  src/applications/letters/tests/01-authed.e2e.spec.js
  src/applications/letters/tests/containers/AddressSection.unit.spec.jsx
  src/applications/letters/tests/containers/Main.unit.spec.jsx
Labels: front end, unicorns

#10907 Prevent undefined JS error in Review accordion
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
Labels: Disability Benefits, front end, unicorns

#10865 Add HLR (Step 1) Review contact details form
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/TODO.md
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/components/MaskedNumber.jsx
  src/applications/disability-benefits/996/components/OptOutFromLegacySystem.jsx
  src/applications/disability-benefits/996/components/WithdrawFromLegacySystem.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/containers/Form0996App.jsx
  src/applications/disability-benefits/996/content/ForwardingAddress.jsx
  src/applications/disability-benefits/996/content/GetFormHelp.jsx
  src/applications/disability-benefits/996/content/OptOutOldAppeals.jsx
  src/applications/disability-benefits/996/form-entry.jsx
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/manifest.json
  src/applications/disability-benefits/996/pages/confirmVeteranDetails.js
  src/applications/disability-benefits/996/pages/contactInformation.js
  src/applications/disability-benefits/996/reducers/index.js
  src/applications/disability-benefits/996/routes.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/00.0996-higher-level-review.e2e.spec.js
  src/applications/disability-benefits/996/tests/components/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/confirmVeteranDetails.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/contactInfo.unit.spec.jsx
  src/applications/disability-benefits/996/tests/schema/initialData.js
  src/applications/disability-benefits/996/tests/validations/validations.unit.spec.js
  src/applications/disability-benefits/996/validations/index.js
  src/applications/disability-benefits/all-claims/content/contactInformation.jsx
Labels: Disability Benefits, VSA, front end, in progress, unicorns, work-in-progress

#10878 updated renderLearnMore method to handle aria-label text
  src/applications/gi/components/search/EligibilityForm.jsx
  src/applications/gi/components/vet-tec/VetTecCalculatorForm.jsx
  src/applications/gi/utils/render.jsx
Labels: BAH, bah-sprint-32

#10873 Implemented 1864 - Add logic to route to type of facility page depend…
  src/applications/vaos/api/index.js
  src/applications/vaos/newAppointmentFlow.js
  src/applications/vaos/tests/newAppointmentFlow.unit.spec.js
Labels: front end

#10881 Kelsonic 2278 sidenav
  src/platform/site-wide/index.js
  src/platform/site-wide/sass/modules/_m-side-nav.scss
  src/platform/site-wide/sass/style.scss
  src/platform/site-wide/side-nav/components/SideNav.js
  src/platform/site-wide/side-nav/helpers.js
  src/platform/site-wide/side-nav/index.js
  src/platform/site-wide/side-nav/tests/components/SideNav.unit.spec.js
  src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid
  src/site/navigation/facility_sidebar_nav.drupal.liquid
  src/site/navigation/sidebar_nav.drupal.liquid
Labels: 508/Accessibility, Epic, VSA, current sprint, enhancement, front end, sitewide

#10915 Update HLR intro page to match design
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/IntroductionPage.unit.spec.jsx
Labels: Disability Benefits, front end, unicorns

#10904 refactor aria-labels for preferred provider learn more buttons
  src/applications/gi/components/CheckboxGroup.jsx
  src/applications/gi/components/vet-tec/VetTecFilterBy.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/constants.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#10920 2442 Added text alert preference to transaction pending message
  src/platform/user/profile/vet360/components/base/TransactionPending.jsx
Labels: 508/Accessibility, By Light, front end, notifications-settings

#10925 Fix missing Cumulative Post-9/11 active duty service Dropdown on Landing Page
  src/applications/gi/components/search/EligibilityForm.jsx
Labels: BAH

#10869 19736: CT 116: Update VET TEC Profile Header Static Content
  src/applications/gi/components/vet-tec/VetTecAdditionalResources.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
  src/applications/gi/utils/helpers.js
Labels: BAH, bah-sprint-32

#10918 BAH 19666: STEM: Remove production flags for STEM Report Updates
  src/applications/edu-benefits/1995/submitForm.js
Labels: BAH

#10932 Kelsonic 2577 update expanded sidenav logic
  src/platform/site-wide/sass/modules/_m-side-nav.scss
  src/platform/site-wide/side-nav/components/SideNav.js
  src/platform/site-wide/side-nav/helpers.js
  src/site/navigation/sidebar_nav.drupal.liquid
Labels: VSA, design, front end, site design

#10906 CT: Update Aria Label Text for Landing Page Learn More Links
  src/applications/gi/components/RadioButtons.jsx
  src/applications/gi/components/search/EligibilityForm.jsx
  src/applications/gi/components/search/LandingPageTypeOfInstitutionFilter.jsx
  src/applications/gi/components/search/OnlineClassesFilter.jsx
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
  src/applications/gi/components/vet-tec/VetTecCalculatorForm.jsx
  src/applications/gi/constants.js
Labels: BAH

#10933 Bah 2muchinfo107 2386
  src/applications/gi/components/profile/Calculator.jsx
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/components/profile/CautionaryInformation.jsx
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/search/EligibilityForm.jsx
Labels: 508/Accessibility, BAH, BAH-IR-needed, BAH-QA-needed

#10899 validation message for school search field
  src/applications/gi/components/search/KeywordSearch.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/tests/components/KeywordSearch.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#10877 [VAOS] Calendar Widget
  src/applications/vaos/components/calendar/CalendarCell.jsx
  src/applications/vaos/components/calendar/CalendarCheckboxOption.jsx
  src/applications/vaos/components/calendar/CalendarNavigation.jsx
  src/applications/vaos/components/calendar/CalendarRadioOption.jsx
  src/applications/vaos/components/calendar/CalendarRow.jsx
  src/applications/vaos/components/calendar/CalendarWeekdayHeader.jsx
  src/applications/vaos/components/calendar/CalendarWidget.jsx
  src/applications/vaos/containers/VAFacilityPage.jsx
  src/applications/vaos/sass/vaos.scss
  src/applications/vaos/tests/components/calendar/CalendarCell.unit.spec.jsx
  src/applications/vaos/tests/components/calendar/CalendarCheckboxOption.unit.spec.jsx
  src/applications/vaos/tests/components/calendar/CalendarNavigation.unit.spec.jsx
  src/applications/vaos/tests/components/calendar/CalendarRadioOption.unit.spec.jsx
  src/applications/vaos/tests/components/calendar/CalendarRow.unit.spec.jsx
  src/applications/vaos/tests/components/calendar/CalendarWeekdayHeader.unit.spec.jsx
  src/applications/vaos/tests/components/calendar/CalendarWidget.unit.spec.jsx
  src/applications/vaos/utils/calendar.js
Labels: 508/Accessibility, design

#10943 2428 Changed Notifications checkbox text.
  src/platform/user/profile/vet360/containers/ReceiveTextMessages.jsx
Labels: 508/Accessibility, By Light, front end, notifications-settings

#10931 Update copy for post911GIBStatusApp
  src/applications/post-911-gib-status/containers/IntroPageSummary.jsx
  src/applications/post-911-gib-status/containers/Post911GIBStatusApp.jsx
Labels: VSA, content

#10911 aria labels for profile page learn more buttons
  src/applications/gi/components/profile/Calculator.jsx
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/search/EligibilityForm.jsx
  src/applications/gi/components/search/LandingPageTypeOfInstitutionFilter.jsx
  src/applications/gi/components/search/OnlineClassesFilter.jsx
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
  src/applications/gi/components/vet-tec/VetTecCalculatorForm.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/constants.js
  src/applications/gi/selectors/calculator.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#10945 2317 Adding new Google Analytics codes for Notifications
  src/platform/user/profile/vet360/constants/index.js
  src/platform/user/profile/vet360/containers/ReceiveTextMessages.jsx
  src/platform/user/profile/vet360/tests/containers/ReceiveTextMessages.unit.spec.jsx
Labels: By Light, front end, notifications-settings

#10936 Update HLR Introduction page content
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
Labels: Disability Benefits, front end, unicorns

#10944 Colmery Sec 107 Analytics
  src/applications/gi/components/profile/CalculatorForm.jsx
Labels: BAH

#10953 Check early if the hashed entry name exists
  src/site/stages/build/plugins/process-entry-names.js
Labels: VSA, bug

#10901 2387: Colmery 107 - Heading H2s should wrap expand/collapse buttons
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#10942 [VAOS] Address high priority accessibility issues in calendar
  src/applications/vaos/components/calendar/CalendarCell.jsx
  src/applications/vaos/components/calendar/CalendarRow.jsx
  src/applications/vaos/components/calendar/CalendarWeekdayHeader.jsx
  src/applications/vaos/components/calendar/CalendarWidget.jsx
  src/applications/vaos/sass/vaos.scss
  src/applications/vaos/tests/components/calendar/CalendarCell.unit.spec.jsx
Labels: 508/Accessibility

#10951 bradl3yC 2636 refactor direct deposit errors
  src/applications/personalization/profile360/tests/util/index.unit.spec.js
  src/applications/personalization/profile360/util/index.js
Labels: VSA

#10939 Kelsonic diff between graphql tome
  src/site/stages/build/drupal/graphql-tome-differences/README.md
  src/site/stages/build/drupal/graphql-tome-differences/block_content.md
  src/site/stages/build/drupal/graphql-tome-differences/consumer.md
  src/site/stages/build/drupal/graphql-tome-differences/crop.md
  src/site/stages/build/drupal/graphql-tome-differences/entity_subqueue.md
  src/site/stages/build/drupal/graphql-tome-differences/file.md
  src/site/stages/build/drupal/graphql-tome-differences/media.md
  src/site/stages/build/drupal/graphql-tome-differences/menu_link_content.md
  src/site/stages/build/drupal/graphql-tome-differences/node.md
  src/site/stages/build/drupal/graphql-tome-differences/paragraph.md
  src/site/stages/build/drupal/graphql-tome-differences/redirect.md
  src/site/stages/build/drupal/graphql-tome-differences/section_association.md
  src/site/stages/build/drupal/graphql-tome-differences/taxonomy_term.md
  src/site/stages/build/drupal/graphql-tome-differences/user.md
Labels: VSA, cms, documentation, enhancement, front end

#10968 Update call center number
  src/applications/post-911-gib-status/containers/IntroPageSummary.jsx
Labels: VSA, content

#10954 CT 107: Remove prod flag for international campus solution #19803
  src/applications/gi/components/profile/CalculatorForm.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#10971 Minor copy updates in markdown files
  src/site/stages/build/drupal/graphql-tome-differences/file.md
  src/site/stages/build/drupal/graphql-tome-differences/menu_link_content.md
  src/site/stages/build/drupal/graphql-tome-differences/node.md
Labels: VSA, documentation

#10958 10795 Changed Profile Notifications Checkbox from environment flag to feature flag
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/ProfileView.jsx
  src/applications/personalization/profile360/selectors.js
  src/platform/user/profile/vet360/components/MobilePhone.jsx
  src/platform/user/profile/vet360/components/PhoneField/EditModal.jsx
  src/platform/user/profile/vet360/components/base/TransactionPending.jsx
  src/platform/user/profile/vet360/containers/ReceiveTextMessages.jsx
  src/platform/user/profile/vet360/tests/components/Transaction.unit.spec.jsx
  src/platform/user/profile/vet360/tests/components/TransactionPending.unit.spec.jsx
  src/platform/user/profile/vet360/tests/containers/ReceiveTextMessages.unit.spec.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: By Light, front end, notifications-settings

#10972 19869: VETTEC Profile page header is missing data
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
Labels: BAH, BAH-QA-needed

#10863 Institution Program Search
  src/applications/gi/actions/index.js
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/reducers/profile.js
  src/applications/gi/reducers/search.js
  src/applications/gi/reducers/utility.js
  src/applications/gi/sass/partials/_gi-search-page.scss
  src/applications/gi/tests/components/CalculatorForm.unit.spec.jsx
  src/applications/gi/tests/components/VetTecProgramSearchResult.unit.spec.jsx
  src/applications/gi/tests/containers/SearchPage.unit.spec.js
  src/applications/gi/tests/reducers/search.unit.spec.js
  src/applications/gi/tests/reducers/utility.unit.spec.js
  src/applications/gi/tests/utils/helpers.unit.spec.js
  src/applications/gi/utils/helpers.js
Labels: BAH, bah-sprint-32

#10984 Improve HLR unit tests
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/tests/components/contestedIssues.unit.spec.jsx
Labels: Disability Benefits, front end, unicorns

#10985 Remove onClick handler in footer
  src/platform/site-wide/va-footer/components/MobileLinks.jsx
Labels: bug, front end

#10983 Higher Level Review: Step 4 (Review/Submit)
  src/applications/disability-benefits/996/config/form.js
Labels: Disability Benefits, front end, unicorns
