Repository department-of-veterans-affairs/vets-website, pull requests merged in 2019-11, with the labels that each got.

#10988 Revert "Bah 2muchinfo107 2386"
  src/applications/gi/components/profile/Calculator.jsx
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/components/profile/CautionaryInformation.jsx
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/search/EligibilityForm.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#10986 Update VET TEC program search result housing amount
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/tests/components/VetTecProgramSearchResult.unit.spec.jsx
Labels: BAH, BAH-IR-needed

#11001 bradleyC 3053 Refactor phone number to tel link
  src/applications/personalization/profile360/containers/PaymentInformation.jsx
Labels: VSA

#10989 HLR: Add Request an Informal Conference (Step 3)
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/TODO.md
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/Form0996App.jsx
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/pages/informalConference.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/informalConference.unit.spec.jsx
  src/applications/disability-benefits/996/tests/schema/initialData.js
  src/applications/disability-benefits/996/tests/validations/validations.unit.spec.js
  src/applications/disability-benefits/996/validations/index.js
Labels: Disability Benefits, front end, in progress, unicorns, work-in-progress

#11004 Kelsonic 3065 update docs for node entity
  src/site/stages/build/process-cms-exports/graphql-cms-export-differences/node.md
  src/site/stages/build/process-cms-exports/tests/entities/index.js
  src/site/stages/build/process-cms-exports/tests/entities/node/landing_page.json
  src/site/stages/build/process-cms-exports/tests/entities/node/page.json
  src/site/stages/build/process-cms-exports/tests/entities/node/publication_listing.json
Labels: VSA, documentation, testing

#11007 SCO: Create Skeleton of SCO Resource Page in Github #19835
  src/site/includes/education-sco.html
  src/site/layouts/page-breadcrumbs.html
Labels: BAH, BAH-QA-needed

#11009 Remove content from warning
  src/applications/disability-benefits/wizard/pages/disagree-file-claim.jsx
Labels: Disability Benefits, front end, unicorns

#10993 CT 116: Update VET TEC Profile Page Content
  src/applications/gi/components/vet-tec/VetTecApplicationProcess.jsx
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/selectors/vetTecCalculator.js
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
  src/applications/gi/tests/selectors/vetTecCalculator.unit.spec.js
Labels: BAH

#11014 SCO: Add right panel content to SCO Skeleton page #19908
  src/site/includes/education-sco.html
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11000 19871: CT 116: Update Contact Details section of the VET TEC Profile Page
  src/applications/gi/components/vet-tec/VetTecContactInformation.jsx
  src/applications/gi/components/vet-tec/VetTecScoContact.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#11013 [IE11 + JAWS] Colmery 107 - Too much information is being read on SELECT menu changes
  src/applications/gi/components/profile/Calculator.jsx
Labels: 508/Accessibility, BAH

#11008 update Vet Tec profile page to include veteran programs
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/components/vet-tec/VetTecPrograms.jsx
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11019 HLR: Add contested issue follow up questions (Step 2c)
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/content/contestedIssueFollowup.js
  src/applications/disability-benefits/996/content/contestedIssues.js
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/pages/confirmVeteranDetails.js
  src/applications/disability-benefits/996/pages/contactInformation.js
  src/applications/disability-benefits/996/pages/contestedIssueFollowup.js
  src/applications/disability-benefits/996/pages/contestedIssues.js
  src/applications/disability-benefits/996/pages/informalConference.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/confirmVeteranDetails.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/contactInfo.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/contestedIssueFollowup.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/contestedIssues.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/informalConference.unit.spec.jsx
  src/applications/disability-benefits/996/tests/schema/initialData.js
  src/applications/disability-benefits/996/tests/validations/validations.unit.spec.js
  src/applications/disability-benefits/996/validations/index.js
Labels: Disability Benefits, front end, in progress, unicorns, work-in-progress

#10995 VET TEC Program Search Filter by Provider
  src/applications/gi/actions/index.js
  src/applications/gi/components/heading/GiBillBreadcrumbs.jsx
  src/applications/gi/components/vet-tec/VetTecFilterBy.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/constants.js
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/reducers/filter.js
  src/applications/gi/reducers/search.js
  src/applications/gi/routes.jsx
  src/applications/gi/tests/components/VetTecFilterBy.unit.spec.jsx
Labels: BAH

#11027 CT 116: Content Changes
  src/applications/gi/components/vet-tec/VetTecApplicationProcess.jsx
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
  src/applications/gi/components/vet-tec/VetTecCalculatorForm.jsx
  src/applications/gi/constants.js
Labels: BAH

#11037 Removing a gating step for Original Claims
  src/applications/disability-benefits/wizard/pages/file-original-claim.jsx
  src/applications/disability-benefits/wizard/pages/index.js
  src/applications/disability-benefits/wizard/pages/original-claim.jsx
  src/applications/disability-benefits/wizard/pages/pageList.js
  src/applications/disability-benefits/wizard/pages/start.jsx
Labels: Disability Benefits, front end, unicorns

#11043 Make address required field for Facility Locator search
  src/applications/facility-locator/components/SearchControls.jsx
Labels: VSA, facility locator, front end

#11053 Make all phone inputs use type="tel"
  src/platform/forms-system/src/js/widgets/PhoneNumberWidget.jsx
  src/platform/forms-system/test/js/widgets/PhoneNumberWidget.unit.spec.jsx
  src/platform/user/profile/vet360/components/PhoneField/EditModal.jsx
Labels: 508/Accessibility, VSA, front end

#11072 Revert step 2 gating removal for 526 form
  src/applications/disability-benefits/wizard/pages/file-original-claim.jsx
  src/applications/disability-benefits/wizard/pages/index.js
  src/applications/disability-benefits/wizard/pages/original-claim.jsx
  src/applications/disability-benefits/wizard/pages/pageList.js
  src/applications/disability-benefits/wizard/pages/start.jsx
Labels: Disability Benefits, front end, unicorns

#11058 Make vet profile email inputs use type="email"
  src/platform/user/profile/vet360/components/EmailField/EditModal.jsx
Labels: 508/Accessibility, VSA, front end

#11044 SCO Event List
  src/applications/static-pages/school-resources/SchoolResources.jsx
  src/applications/static-pages/school-resources/ScoEventsWidget.jsx
  src/applications/static-pages/school-resources/constants/events.json
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/tests/school-resources/ScoEventsWidget.unit.spec.jsx
  src/applications/static-pages/tests/school-resources/constants/validate-event-data.unit.spec.js
Labels: BAH, BAH-QA-needed

#11077 HLR: Update content
  src/applications/disability-benefits/996/TODO.md
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/content/ForwardingAddress.jsx
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/content/OptOutOldAppeals.jsx
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/pages/contactInformation.js
  src/applications/disability-benefits/996/pages/contestedIssueFollowup.js
  src/applications/disability-benefits/996/pages/informalConference.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
Labels: Disability Benefits, front end, unicorns

#11068 SCO Anouncements
  src/applications/static-pages/school-resources/SchoolResources.jsx
  src/applications/static-pages/school-resources/ScoAnnouncementsWidget.jsx
  src/applications/static-pages/school-resources/ScoEventsWidget.jsx
  src/applications/static-pages/school-resources/constants/announcements.json
  src/applications/static-pages/school-resources/constants/constants.js
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/tests/school-resources/ScoAnnouncementsWidget.unit.spec.jsx
  src/applications/static-pages/tests/school-resources/constants/validate-announcements-data.unit.spec.js
  src/applications/static-pages/tests/school-resources/constants/validate-event-data.unit.spec.js
Labels: BAH

#11069 BAH 116 Content Updates 19916 and 19917
  src/applications/gi/components/content/AdditionalResources.jsx
  src/applications/gi/components/heading/GiBillBreadcrumbs.jsx
  src/applications/gi/components/search/EligibilityForm.jsx
  src/applications/gi/components/vet-tec/VetTecAdditionalResources.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11083 Disable form 526 forwarding address
  src/applications/disability-benefits/all-claims/pages/contactInformation.js
  src/applications/disability-benefits/all-claims/tests/pages/contactInformation.unit.spec.jsx
Labels: Disability Benefits, front end, unicorns

#11081 HLR: Design update of step 3
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/pages/informalConference.js
  src/applications/disability-benefits/996/tests/components/informalConference.unit.spec.jsx
  src/applications/disability-benefits/996/tests/validations/validations.unit.spec.js
  src/applications/disability-benefits/996/validations/index.js
Labels: Disability Benefits, front end, unicorns

#11074 CT 116: Update EDU Program File Processing and Data Display #19956
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecContactInformation.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecVeteranPrograms.jsx
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
  src/applications/gi/tests/components/VetTecProgramSearchResult.unit.spec.jsx
  src/applications/gi/utils/helpers.js
Labels: BAH

#11086 HLR: update confirmation page
  src/applications/disability-benefits/996/TODO.md
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/ConfirmationPage.unit.spec.jsx
Labels: Disability Benefits, front end, unicorns

#11082 19959: CT 116: [Chrome & Safari] Link goes to next line when URL is too long
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#11084 VET TEC selected program
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
  src/applications/static-pages/school-resources/constants/announcements.json
Labels: BAH

#11103 Facility Locator should display the hours of operation information sent through the API, rather than interpreting the data
  src/applications/facility-locator/components/LocationHours.jsx
  src/applications/facility-locator/tests/helpers.unit.spec.js
  src/applications/facility-locator/utils/helpers.js
Labels: VSA, facility locator, front end

#11035 GIBCT: Accordion Header Font is Incorrect on the Profile Page #19923
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH, bug

#11108 19964: Lowercase two letters based off of feedback
  src/applications/static-pages/school-resources/ScoEventsWidget.jsx
Labels: BAH

#11096 Fix for search results breadcrumb link
  src/applications/gi/components/heading/GiBillBreadcrumbs.jsx
Labels: BAH

#11100 CT 116 Estimate your benefits NVDA bug #19948
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#11099 SCO: Update UI based on UX team feedback #19965
  src/applications/static-pages/school-resources/ScoAnnouncementsWidget.jsx
  src/applications/static-pages/school-resources/ScoEventsWidget.jsx
  src/site/components/merger-social-sco.html
  src/site/includes/education-sco.html
Labels: BAH, BAH-QA-needed

#11120 Update ReviewFieldTemplate
  src/platform/forms-system/src/js/review/ReviewFieldTemplate.jsx
  src/platform/forms-system/test/js/review/ReviewFieldTemplate.unit.spec.jsx
Labels: front end, platform, unicorns

#11095 Add NavItem, LabelText, ExpandCollapseButton, DuplicateLineLabel
  src/platform/site-wide/sass/modules/_m-side-nav.scss
  src/platform/site-wide/side-nav/components/DuplicateLineLabel.js
  src/platform/site-wide/side-nav/components/ExpandCollapseIcon.js
  src/platform/site-wide/side-nav/components/LabelText.js
  src/platform/site-wide/side-nav/components/NavItem.js
  src/platform/site-wide/side-nav/components/NavItemRow.js
  src/platform/site-wide/side-nav/components/SideNav.js
  src/platform/site-wide/side-nav/helpers.js
  src/platform/site-wide/side-nav/prop-types.js
  src/platform/site-wide/side-nav/tests/components/DuplicateLineLabel.unit.spec.js
  src/platform/site-wide/side-nav/tests/components/ExpandCollapseIcon.unit.spec.js
  src/platform/site-wide/side-nav/tests/components/LabelText.unit.spec.js
  src/platform/site-wide/side-nav/tests/components/NavItem.unit.spec.js
  src/platform/site-wide/side-nav/tests/components/NavItemRow.unit.spec.js
  src/platform/site-wide/side-nav/tests/components/SideNav.unit.spec.js
Labels: VSA, needs peer approval

#11111 Analytics Implementation for VET TEC in the Comparison Tool #3048
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/components/vet-tec/VetTecFilterBy.jsx
Labels: BAH

#11094 3416 - Add QA/testing step(s)/info to PR-template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, vsa-qa

#11092 updated label to stop repeating program name twice
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
Labels: BAH

#11115 19988: AC 1 and 3 for 19988
  src/applications/static-pages/school-resources/constants/announcements.json
  src/applications/static-pages/school-resources/constants/events.json
Labels: BAH

#11132 fix styling issues when screen size is at 481 pixels width
  src/applications/gi/components/search/LandingPageTypeOfInstitutionFilter.jsx
  src/applications/gi/sass/partials/_gi-search-page.scss
Labels: BAH

#11128 GI Bill Comparison Tool VET TEC updates
  src/applications/gi/components/vet-tec/VetTecApplicationProcess.jsx
  src/applications/gi/components/vet-tec/VetTecFilterBy.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/tests/components/VetTecFilterBy.unit.spec.jsx
Labels: BAH

#11127 Analytics Implementation for Resources for Schools [SCO Migration] #3055
  src/applications/static-pages/school-resources/ScoAnnouncementsWidget.jsx
  src/site/components/merger-crosslinks.html
Labels: BAH, BAH-QA-needed

#11129 HLR: Update Informal conference review design
  src/applications/disability-benefits/996/containers/ScheduleTimesReviewField.jsx
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/pages/informalConference.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
Labels: Disability Benefits, front end, in progress, unicorns, work-in-progress

#11137 set aria-hidden to true for GIBCT font awesome icons
  src/applications/gi/components/vet-tec/VetTecFilterBy.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/components/vet-tec/VetTecVeteranPrograms.jsx
Labels: BAH, BAH-IR-needed

#11143 Fix: If a phone number does not exist, the prompt to call should be hidden
  src/applications/facility-locator/containers/FacilityDetail.jsx
Labels: VSA, facility locator, front end

#11139 SCO: Update UI based on UX team feedback #19965
  src/applications/static-pages/school-resources/ScoEventsWidget.jsx
  src/site/components/merger-crosslinks.html
  src/site/components/merger-social-sco.html
Labels: BAH, BAH-QA-needed

#11152 RE: Fix: If a phone number does not exist, the prompt to call should be hidden
  src/applications/facility-locator/containers/FacilityDetail.jsx
Labels: VSA, facility locator, front end

#11118 Fix a11y errors in review form
  src/applications/disability-benefits/all-claims/components/ReviewCardField.jsx
  src/applications/disability-benefits/all-claims/tests/components/ReviewCardField.unit.spec.jsx
  src/platform/forms-system/src/js/components/SchemaForm.jsx
  src/platform/forms-system/src/js/review/ObjectField.jsx
Labels: 508/Accessibility, front end, unicorns

#11150 SCO: Update webinars and events #20010
  src/applications/static-pages/school-resources/ScoAnnouncementsWidget.jsx
  src/applications/static-pages/school-resources/constants/announcements.json
  src/applications/static-pages/school-resources/constants/events.json
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11136 3540: GIBCT Section 116 - Benefit amounts wrap to two lines when zoomed above 300%
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH, BAH-QA-needed

#11138 [COGNITION]: GIBCT Section 116 - Add screen reader only text for the benefit breakdowns by time #3537
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11160 Change nav item color to dark grey on hover
  src/platform/site-wide/sass/modules/_m-side-nav.scss
Labels: VSA, front end

#11164 Remove bottom margin for empty form pages
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
Labels: Disability Benefits, front end, unicorns

#11149 CT 116: Remove production flags for program data iterative solution. #19866
  src/applications/gi/components/vet-tec/VetTecApplicationProcess.jsx
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/components/vet-tec/VetTecSearchResult.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/containers/SearchPage.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11091 bradl3yC 3176 address validation
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/containers/InitializeVet360ID.jsx
  src/platform/user/profile/vet360/containers/Vet360ProfileField.jsx
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/containers/AddressValidationModal.unit.spec.jsx
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
  src/platform/user/profile/vet360/util/local-vet360.js
Labels: VSA

#11178 HLR: Update content after review
  src/applications/disability-benefits/996/TODO.md
  src/applications/disability-benefits/996/components/OptOutFromLegacySystem.jsx
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/containers/ForwardingAddressReviewField.jsx
  src/applications/disability-benefits/996/content/ForwardingAddress.jsx
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/content/contestedIssueFollowup.js
  src/applications/disability-benefits/996/content/contestedIssues.js
  src/applications/disability-benefits/996/pages/contactInformation.js
  src/applications/disability-benefits/996/pages/informalConference.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
Labels: Disability Benefits, front end, unicorns

#11163 Do not render duplicate label + line when the nav item !hasChildren
  src/platform/site-wide/side-nav/components/DuplicateLineLabel.js
Labels: VSA, front end

#11161 Flip chevrons
  src/platform/site-wide/side-nav/components/ExpandCollapseIcon.js
Labels: VSA, front end

#11162 Underline selected nav items that do not have children
  src/platform/site-wide/sass/modules/_m-side-nav.scss
  src/platform/site-wide/side-nav/components/DuplicateLineLabel.js
  src/platform/site-wide/side-nav/components/ExpandCollapseIcon.js
  src/platform/site-wide/side-nav/components/NavItemRow.js
Labels: VSA, front end

#11179 bradl3yC Add missing keys to mock data and response handling
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/tests/actions/transactions.unit.spec.js
  src/platform/user/profile/vet360/util/local-vet360.js
Labels: VSA

#11056 CT 107: Where will you take your classes question should be pre-selected on page load #19859
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/selectors/calculator.js
Labels: BAH

#11188 GIDS: Record Not found error in Sentry Logs #20021
  src/applications/gi/actions/index.js
  src/applications/gi/reducers/profile.js
  src/applications/gi/tests/actions/index.unit.spec.js
Labels: BAH, BAH-QA-needed

#11167 Revert "3416 - Add QA/testing step(s)/info to PR-template. (#11094)"
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, vsa-qa

#11140 20013 CT 116: Update High, Medium, Low 116 UX Feedback items to match DSVA style and standards
  src/applications/gi/components/vet-tec/VetTecAdditionalResources.jsx
  src/applications/gi/components/vet-tec/VetTecApplicationProcess.jsx
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
  src/applications/gi/components/vet-tec/VetTecCalculatorForm.jsx
  src/applications/gi/components/vet-tec/VetTecContactInformation.jsx
  src/applications/gi/components/vet-tec/VetTecFilterBy.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecVeteranPrograms.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/sass/partials/_gi-search-page.scss
  src/applications/gi/sass/partials/_gi-vet-tec.scss
Labels: BAH

#11173 [Find VA Forms] New widget scaffolding
  src/applications/find-va-forms/actions/index.js
  src/applications/find-va-forms/components/Card.jsx
  src/applications/find-va-forms/components/CardRow.jsx
  src/applications/find-va-forms/components/FindVaForms.jsx
  src/applications/find-va-forms/components/TopTasks.jsx
  src/applications/find-va-forms/constants/example.json
  src/applications/find-va-forms/containers/SearchForm.jsx
  src/applications/find-va-forms/containers/SearchResults.jsx
  src/applications/find-va-forms/createFindVaForms.js
  src/applications/find-va-forms/find-va-forms-entry.js
  src/applications/find-va-forms/reducers/index.js
  src/applications/find-va-forms/reducers/query.js
  src/applications/find-va-forms/reducers/searchResults.js
  src/applications/find-va-forms/sass/find-va-forms.scss
  src/applications/find-va-forms/tests/actions/index.unit.spec.js
  src/applications/find-va-forms/tests/components/Card.unit.spec.jsx
  src/applications/find-va-forms/tests/components/CardRow.unit.spec.jsx
  src/applications/find-va-forms/tests/components/FindVaForms.unit.spec.jsx
  src/applications/find-va-forms/tests/components/TopTasks.unit.spec.jsx
  src/applications/find-va-forms/tests/containers/SearchForm.unit.spec.jsx
  src/applications/find-va-forms/tests/reducers/index.unit.spec.js
  src/applications/find-va-forms/tests/reducers/query.unit.spec.js
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
Labels: VSA

#11187 Fix styling issue to before selector for checkbox label
  src/applications/gi/components/Checkbox.jsx
  src/applications/gi/components/CheckboxGroup.jsx
  src/applications/gi/sass/partials/_gi-search-page.scss
Labels: BAH

#11200 removed email and phone number from SCO contact info
  src/applications/gi/components/vet-tec/VetTecScoContact.jsx
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
Labels: BAH

#11203 removing hashing from webfonts
  config/webpack.config.js
Labels: front end

#11198 bradl3yC 3723 Add callTransaction if only 1 address
  src/platform/user/profile/vet360/actions/transactions.js
Labels: VSA

#11168 2487 connect trd to api
  src/applications/personalization/rated-disabilities/actions/index.js
  src/applications/personalization/rated-disabilities/components/PercentageCalloutBox.jsx
  src/applications/personalization/rated-disabilities/components/TotalRatedDisabilities.jsx
  src/applications/personalization/rated-disabilities/reducers/total-disabilities.js
  src/applications/personalization/rated-disabilities/tests/components/TotalRatedDisabilities.unit.spec.jsx
  src/applications/personalization/rated-disabilities/tests/components/TotalRatingStates.unit.spec.jsx
  src/applications/personalization/rated-disabilities/tests/reducers/total-disabilities.unit.spec.js
Labels: VSA

#11202 Remove pittsburgh beta banner for now
  src/site/includes/header.html
Labels: VSA, design, front end

#11211 bradl3yC 3783 Add entire payload and overwrite with first
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
Labels: VSA

#11181 Escape DOM selector for focused element
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
  src/platform/forms-system/test/js/review/ReviewCollapsibleChapter.unit.spec.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, bug, unicorns, work-in-progress
