Repository department-of-veterans-affairs/vets-website, pull requests merged in 2019-05, with the labels that each got.

#10032 16115 - Add aria-label to Dashboard remove-button.
  src/applications/personalization/preferences/components/PreferenceItem.jsx
Labels: 508/Accessibility, front end, website

#10033 Session timeout modal
  src/applications/auth/containers/AuthApp.jsx
  src/platform/site-wide/user-nav/containers/Main.jsx
  src/platform/user/authentication/components/SessionTimeoutModal.jsx
  src/platform/user/profile/actions/index.js
  src/platform/user/profile/utilities/index.js
  src/platform/utilities/api/index.js
Labels: front end, griffin

#10046 Bah colmery 104
  src/applications/gi/selectors/calculator.js
  src/applications/gi/tests/selectors/calculator.unit.spec.js
Labels: BAH

#10031 Delete unused Nightwatch test and helpers
  src/applications/disability-benefits/all-claims/tests/00-all-fields.e2e.spec.js
  src/applications/disability-benefits/all-claims/tests/disability-benefits-helpers.js
Labels: front end, unicorns

#10058 Bah colmery 111
  src/applications/gi/containers/Modals.jsx
Labels: BAH

#10027 15582 file upload btn kybd focus fix
  package.json
  src/platform/forms-system/src/js/utilities/ui/index.js
Labels: 508/Accessibility, front end, website

#10043 18376 create1995 stem
  package.json
  src/applications/edu-benefits/1995-STEM/Form1995StemApp.jsx
  src/applications/edu-benefits/1995-STEM/config/form.js
  src/applications/edu-benefits/1995-STEM/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1995-STEM/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1995-STEM/edu-benefits-entry.jsx
  src/applications/edu-benefits/1995-STEM/helpers.jsx
  src/applications/edu-benefits/1995-STEM/manifest.json
  src/applications/edu-benefits/1995-STEM/reducer.js
  src/applications/edu-benefits/1995-STEM/routes.jsx
  src/applications/edu-benefits/tests/1995-STEM/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/1995-STEM/config/applicantInformation.unit.spec.jsx
  src/applications/edu-benefits/tests/1995-STEM/config/benefitSelection.unit.spec.jsx
  src/applications/edu-benefits/tests/1995-STEM/config/dependents.unit.spec.jsx
  src/applications/edu-benefits/tests/1995-STEM/config/militaryHistory.unit.spec.jsx
  src/applications/edu-benefits/tests/1995-STEM/config/servicePeriods.unit.spec.jsx
  src/applications/edu-benefits/tests/1995-STEM/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/tests/1995-STEM/containers/IntroductionPage.unit.spec.jsx
  src/applications/edu-benefits/tests/1995-STEM/edu-1995-stem-helpers.js
  src/applications/edu-benefits/tests/1995-STEM/schema/maximal-test.json
  src/applications/edu-benefits/tests/1995-STEM/schema/minimal-test.json
  src/applications/edu-benefits/tests/1995-STEM/schema/schema.unit.spec.js
  src/applications/personalization/dashboard/helpers.jsx
  src/applications/personalization/dashboard/tests/helpers.unit.spec.js
  src/applications/personalization/profile360/util/helpers.jsx
  src/platform/forms/tests/migrations.unit.spec.js
  yarn.lock
Labels: BAH

#10063 VET TEC: Update Introduction Page Link #18560
  src/applications/edu-benefits/0994/containers/IntroductionPage.jsx
Labels: BAH

#10002 [Comparison Tool] - Colmery 501
  src/applications/gi/actions/index.js
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/selectors/calculator.js
  src/applications/gi/selectors/estimator.js
  src/applications/gi/tests/actions/index.unit.spec.js
  src/applications/gi/tests/gibct-helpers.js
  src/applications/gi/tests/reducers/calculator.unit.spec.js
  src/applications/gi/tests/selectors/calculator.unit.spec.js
  src/applications/gi/tests/selectors/estimator.unit.spec.js
Labels: BAH

#10082 CT: 105 - Update benefit level options#18517
  src/applications/gi/components/search/EligibilityForm.jsx
Labels: BAH, BAH-QA-needed

#10094 Add Configurations in preparation of 1995 development #18651
  src/applications/edu-benefits/1995/config/form.js
  src/applications/edu-benefits/1995/config/new-chapters.js
  src/applications/edu-benefits/1995/config/original-chapters.js
Labels: BAH

#10092 Bah 18512
  src/applications/gi/actions/index.js
  src/applications/gi/reducers/calculator.js
  src/applications/gi/selectors/calculator.js
  src/applications/gi/selectors/estimator.js
  src/applications/gi/tests/actions/index.unit.spec.js
  src/applications/gi/tests/gibct-helpers.js
  src/applications/gi/tests/reducers/calculator.unit.spec.js
  src/applications/gi/tests/selectors/estimator.unit.spec.js
  src/applications/gi/utils/helpers.js
Labels: BAH

#10065 [Comparison Tool] Update stem language (Colmery 111)
  src/applications/gi/components/profile/AdditionalInformation.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
Labels: BAH

#10115 Redirect to session expired page if a logged out user makes an authorized request
  src/platform/utilities/api/index.js
Labels: front end, griffin

#10121 Comparison Tool: 508 Defect - For IHL facilities, Tuition and Scholarship fields do not have a label#18705
  src/applications/gi/components/profile/CalculatorForm.jsx
Labels: BAH, BAH-QA-needed

#10110 update package.json with new vets-json-schema revision
  package.json
  yarn.lock
Labels: BAH

#10137 STEM: Add Conditional Military History Page to 1995 #18659
  src/applications/edu-benefits/1995/config/form.js
  src/applications/edu-benefits/1995/config/new-chapters.js
  src/applications/edu-benefits/1995/content/activeDuty.jsx
  src/applications/edu-benefits/1995/helpers.jsx
  src/applications/edu-benefits/1995/pages/activeDuty.js
  src/applications/edu-benefits/1995/pages/index.js
  src/applications/edu-benefits/1995/submit-transformer.js
  src/applications/edu-benefits/tests/1995/pages/activeDuty.unit.spec.jsx
  src/applications/edu-benefits/tests/1995/schema/schema.unit.spec.js
Labels: BAH

#10148 Bah 18658
  src/applications/edu-benefits/1995/config/new-chapters.js
  src/applications/edu-benefits/1995/content/stem.jsx
  src/applications/edu-benefits/1995/pages/index.js
  src/applications/edu-benefits/1995/pages/stem.js
  src/applications/edu-benefits/tests/1995/pages/stem.unit.spec.jsx
Labels: BAH
