Repository department-of-veterans-affairs/vets-website, pull requests merged in 2019-12, with the labels that each got.

#11185 Enhance DD save/update error tracking
  src/applications/personalization/profile360/actions/paymentInformation.js
  src/applications/personalization/profile360/containers/PaymentInformation.jsx
  src/applications/personalization/profile360/tests/util/index.unit.spec.js
  src/applications/personalization/profile360/util/index.js
Labels: VSA

#11194 HLR: Create start wizard
  src/applications/disability-benefits/996/components/HLRWizard.jsx
  src/applications/disability-benefits/996/components/createHLRApplicationStatus.jsx
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/content/contestedIssues.js
  src/applications/disability-benefits/996/content/wizardLabels.jsx
  src/applications/disability-benefits/996/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/HLR-wizard.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/996/utils.js
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
Labels: Disability Benefits, VSA, front end, unicorns

#11199 GIBCT non-critical content updates requested during UAT
  src/applications/gi/components/search/EligibilityForm.jsx
  src/applications/gi/components/vet-tec/VetTecApplicationProcess.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/tests/components/EligibilityForm.unit.spec.jsx
Labels: BAH

#11209 20019: SCO: Update page with Design/UAT feedback items
  src/applications/static-pages/school-resources/ScoAnnouncementsWidget.jsx
  src/applications/static-pages/school-resources/ScoEventsWidget.jsx
Labels: BAH

#11166 Kelsonic 3575 remove sidenav on events news releases and stories subpages
  src/site/layouts/event.drupal.liquid
  src/site/layouts/news_story.drupal.liquid
  src/site/layouts/press_release.drupal.liquid
Labels: VSA, front end

#11193 Implement confirmation checkbox on Additional Evidence Upload Screen
  src/applications/claims-status/components/AddFilesForm.jsx
  src/applications/claims-status/components/EvidenceWarning.jsx
  src/applications/claims-status/tests/components/AddFilesForm.unit.spec.jsx
Labels: Disability Benefits, VSA, claim status, front end, unicorns

#11196 updated schema hash for feedback tool
  package.json
  yarn.lock
Labels: BAH

#11201 added basic component structure
  src/applications/personalization/view-dependents/components/ViewDependentsLayout.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsList.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsSidebar.jsx
  src/applications/personalization/view-dependents/containers/ViewDependentsApp.jsx
  src/applications/personalization/view-dependents/manifest.json
  src/applications/personalization/view-dependents/routes.jsx
  src/applications/personalization/view-dependents/sass/view-dependents.scss
  src/applications/personalization/view-dependents/view-dependents-entry.jsx
Labels: VSA

#11231 20013: Resolve item number 19
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/sass/partials/_gi-landing-page.scss
Labels: BAH

#11237 Add VET TEC Program Provider Filter feature flag
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#11234 Fix HLR wizard button issues
  src/applications/disability-benefits/996/components/HLRWizard.jsx
  src/applications/disability-benefits/996/tests/containers/HLR-wizard.unit.spec.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, bug, design, front end, unicorns

#11197 refactor SCO contact info into list with aria labels
  src/applications/gi/components/vet-tec/VetTecContactInformation.jsx
  src/applications/gi/components/vet-tec/VetTecScoContact.jsx
  src/applications/gi/sass/partials/_gi-vet-tec.scss
Labels: BAH

#11212 Add search results and update Redux flow to support API res for VA forms
  src/applications/find-va-forms/actions/index.js
  src/applications/find-va-forms/api/index.js
  src/applications/find-va-forms/constants/index.js
  src/applications/find-va-forms/containers/SearchForm.jsx
  src/applications/find-va-forms/containers/SearchResults.jsx
  src/applications/find-va-forms/createFindVaForms.js
  src/applications/find-va-forms/find-va-forms-entry.js
  src/applications/find-va-forms/helpers/index.js
  src/applications/find-va-forms/reducers/findVAFormsReducer.js
  src/applications/find-va-forms/reducers/index.js
  src/applications/find-va-forms/reducers/query.js
  src/applications/find-va-forms/reducers/searchResults.js
  src/applications/find-va-forms/tests/actions/index.unit.spec.js
  src/applications/find-va-forms/tests/components/Card.unit.spec.jsx
  src/applications/find-va-forms/tests/components/CardRow.unit.spec.jsx
  src/applications/find-va-forms/tests/components/FindVaForms.unit.spec.jsx
  src/applications/find-va-forms/tests/components/TopTasks.unit.spec.jsx
  src/applications/find-va-forms/tests/containers/SearchForm.unit.spec.jsx
  src/applications/find-va-forms/tests/containers/SearchResults.unit.spec.jsx
  src/applications/find-va-forms/tests/helpers/index.unit.spec.js
  src/applications/find-va-forms/tests/reducers/findVAFormsReducer.unit.spec.js
  src/applications/find-va-forms/tests/reducers/index.unit.spec.js
  src/applications/find-va-forms/tests/reducers/query.unit.spec.js
Labels: VSA, design, front end, needs peer approval

#11223 HLR: Fix review page a11y issues
  src/applications/disability-benefits/996/containers/ForwardingAddressReviewField.jsx
  src/applications/disability-benefits/996/containers/ScheduleTimesReviewField.jsx
  src/applications/disability-benefits/all-claims/components/SelectArrayItemsWidget.jsx
  src/platform/forms-system/src/js/review/ArrayField.jsx
  src/platform/forms-system/src/js/review/ObjectField.jsx
  src/platform/forms-system/test/js/review/ObjectField.unit.spec.jsx
  src/platform/forms-system/test/js/review/ReviewCollapsibleChapter.unit.spec.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, front end, unicorns

#11227 bradl3yC 3883 Add edit address link
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/tests/containers/AddressValidationModal.unit.spec.jsx
Labels: VSA

#11135 Fix input typeahead loses focus
  src/applications/facility-locator/components/ServiceTypeAhead.jsx
Labels: VSA, facility locator, front end

#11250 Add copy-entities.js script
  script/copy-entities.js
Labels: front end

#11245 3905 Update error handling, add utility functions
  src/applications/personalization/rated-disabilities/actions/index.js
  src/applications/personalization/rated-disabilities/components/RatedDisabilityList.jsx
  src/applications/personalization/rated-disabilities/components/TotalRatedDisabilities.jsx
  src/applications/personalization/rated-disabilities/tests/components/RatedDisabilityList.unit.spec.jsx
  src/applications/personalization/rated-disabilities/tests/utils/index.unit.spec.js
  src/applications/personalization/rated-disabilities/util/index.js
  yarn.lock
Labels: VSA

#11230 UI changes to the claim status tool to clarify sorting
  src/applications/claims-status/components/appeals-v2/AppealListItemV2.jsx
  src/applications/claims-status/components/appeals-v2/ClaimsListItemV2.jsx
  src/applications/claims-status/tests/components/appeals-v2/AppealListItemV2.unit.spec.jsx
  src/applications/claims-status/tests/components/appeals-v2/ClaimListItemV2.unit.spec.jsx
  src/applications/claims-status/tests/e2e/00.claims-list.e2e.spec.js
Labels: Disability Benefits, VSA, claim status, front end, unicorns

#11246 bradl3yC 3890 Change address validation copy
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/containers/AddressValidationModal.unit.spec.jsx
  src/platform/user/profile/vet360/util/local-vet360.js
Labels: VSA

#11253 bradl3yC 3993 default address selection
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/actions/ui.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/actions/transactions.unit.spec.js
  src/platform/user/profile/vet360/tests/containers/AddressValidationModal.unit.spec.jsx
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
  src/platform/user/profile/vet360/util/local-vet360.js
Labels: VSA

#11243 Get bank info from view:originalBankAccount, if available
  src/applications/disability-benefits/all-claims/components/PaymentView.jsx
Labels: Disability Benefits, VSA, bug, front end, unicorns, work-in-progress

#11174 Redirect from facility detail pages to new VAMC pages
  src/applications/facility-locator/containers/FacilityDetail.jsx
  src/applications/facility-locator/tests/helpers.unit.spec.js
  src/applications/facility-locator/utils/helpers.js
Labels: VSA, facility locator, front end

#11154 VET TEC Provider Filters
  src/applications/gi/actions/index.js
  src/applications/gi/components/vet-tec/VetTecFilterBy.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/reducers/search.js
  src/applications/gi/tests/components/VetTecFilterBy.unit.spec.jsx
  src/applications/gi/tests/reducers/search.unit.spec.js
  src/applications/gi/tests/utils/helpers.unit.spec.js
  src/applications/gi/utils/helpers.js
Labels: BAH

#11240 20061: SCO: Update 'See past announcements' link
  src/applications/static-pages/school-resources/ScoAnnouncementsWidget.jsx
Labels: BAH

#11218 VET TEC program - display "0" hours as "TBD"
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
  src/applications/gi/tests/components/VetTecProgramSearchResult.unit.spec.jsx
Labels: BAH

#11271 Revert "Redirect from facility detail pages to new VAMC pages"
  src/applications/facility-locator/containers/FacilityDetail.jsx
  src/applications/facility-locator/tests/helpers.unit.spec.js
  src/applications/facility-locator/utils/helpers.js
Labels: VSA

#11270 Kelsonic 3997 remove "Home" breadcrumb
  src/platform/site-wide/side-nav/helpers.js
  src/platform/site-wide/side-nav/tests/components/SideNav.unit.spec.js
  src/site/includes/breadcrumbs.drupal.liquid
  src/site/layouts/event.drupal.liquid
  src/site/layouts/events_page.drupal.liquid
  src/site/layouts/health_care_region_health_services_page.drupal.liquid
  src/site/layouts/health_care_region_locations_page.drupal.liquid
  src/site/layouts/news_stories_page.drupal.liquid
  src/site/layouts/news_story.drupal.liquid
  src/site/layouts/press_release.drupal.liquid
  src/site/layouts/press_releases_page.drupal.liquid
Labels: VSA, front end

#11278 Move global.window stub into Mocha hook
  src/applications/find-va-forms/tests/actions/index.unit.spec.js
Labels: VSA

#11284 Add 4 redirects
  src/applications/proxy-rewrite/redirects/disabilityRedirects.json
Labels: VSA, front end

#11291 Refine GA reporting of fraud errors
  src/applications/personalization/profile360/tests/util/index.unit.spec.js
  src/applications/personalization/profile360/util/index.js
Labels: VSA

#11273 bradl3yC 3960 Updates to Address Validation Modal
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/actions/ui.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/tests/actions/transactions.unit.spec.js
Labels: VSA

#11290 Bug fix for accordion headers causing disappearing UI on review page of 526
  src/platform/forms-system/src/js/review/ObjectField.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#11297 bradl3yC 3891 Bad Unit Number
  src/platform/user/profile/constants/addressValidationMessages.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/tests/helpers/addressValidationMessages.unit.spec.js
Labels: VSA

#11294 Remove SideNav on select subpages that contain /safety-security/
  src/site/layouts/health_care_region_detail_page.drupal.liquid
Labels: VSA, front end

#11285 Adding regex to remove violation.help brackets for better rendering.
  src/site/assets/js/execute-axe-check.js
Labels: 508/Accessibility, cms

#11295 4021 - RD layout and accessibility updates
  src/applications/personalization/rated-disabilities/components/RatedDisabilityList.jsx
  src/applications/personalization/rated-disabilities/components/RatedDisabilityListItem.jsx
  src/applications/personalization/rated-disabilities/components/TotalRatedDisabilities.jsx
  src/applications/personalization/rated-disabilities/components/TotalRatingStates.jsx
  src/applications/personalization/rated-disabilities/sass/rated-disabilities.scss
  src/applications/personalization/rated-disabilities/tests/components/RatedDisabilityList.unit.spec.jsx
  src/applications/personalization/rated-disabilities/tests/components/RatedDisabilityListItem.unit.spec.jsx
  src/applications/personalization/rated-disabilities/tests/components/TotalRatedDisabilities.unit.spec.jsx
  src/applications/personalization/rated-disabilities/tests/e2e/ratedDisabilitiesError.e2e.spec.js
  src/applications/personalization/rated-disabilities/tests/e2e/ratedDisabilitiesSuccess.e2e.spec.js
  src/applications/personalization/rated-disabilities/tests/mockdata/error-response.json
Labels: VSA

#11300 Expand test coverage of PaymentInformation action creators
  src/applications/personalization/profile360/actions/paymentInformation.js
  src/applications/personalization/profile360/tests/actions/paymentInformation.unit.spec.js
Labels: VSA

#11292 3943 add logic to vdl
  src/applications/personalization/view-dependents/components/ViewDependentsHeader/ViewDependentsHeader.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsLayout.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsList.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsList/ViewDependentsList.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsList/ViewDependentsListItem.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsSidebar.jsx
  src/applications/personalization/view-dependents/containers/ViewDependentsApp.jsx
  src/applications/personalization/view-dependents/layouts/ViewDependentsLayout.jsx
  src/applications/personalization/view-dependents/layouts/ViewDependentsLists.jsx
Labels: VSA

#11305 Bug fix for missing 526 gating eBenefits details
  src/applications/disability-benefits/wizard/pages/file-original-claim.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#11322 Fixed autocomplete selection search
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
Labels: BAH

#11321 Change View status button to say "View details" in claim status tool
  src/applications/claims-status/components/appeals-v2/AppealListItemV2.jsx
  src/applications/claims-status/components/appeals-v2/ClaimsListItemV2.jsx
Labels: Disability Benefits, VSA, claim status, front end, unicorns

#11312 Kelsonic 3882 column sorting
  package.json
  src/applications/find-va-forms/actions/index.js
  src/applications/find-va-forms/api/index.js
  src/applications/find-va-forms/constants/index.js
  src/applications/find-va-forms/containers/SearchResults.jsx
  src/applications/find-va-forms/helpers/index.js
  src/applications/find-va-forms/reducers/findVAFormsReducer.js
  src/applications/find-va-forms/tests/actions/index.unit.spec.js
  src/applications/find-va-forms/tests/helpers/index.unit.spec.js
  src/applications/find-va-forms/tests/reducers/findVAFormsReducer.unit.spec.js
  yarn.lock
Labels: VSA, front end

#11279 Add MVP of content language linting plugin
  Dockerfile
  script/preview.js
  script/vale/.vale.ini
  script/vale/TEST.md
  script/vale/dictionary.txt
  script/vale/styles/PlainLanguage/Contractions.yml
  script/vale/styles/PlainLanguage/Words.yml
  script/vale/styles/VAgov/Brand.yml
  script/vale/styles/VAgov/JargonMilitary.yml
  script/vale/styles/VAgov/JargonTech.yml
  script/vale/styles/VAgov/JargonVSP.yml
  script/vale/styles/VAgov/Spelling.yml
  src/site/stages/build/options.js
  src/site/stages/build/plugins/inject-vale-linter.js
  src/site/stages/preview/index.js
Labels: cms, content, front end

#11348 Fix async mock of unit test
  src/applications/find-va-forms/actions/index.js
  src/applications/find-va-forms/tests/actions/index.unit.spec.js
Labels: VSA

#11313 Feature/2155 write e2e tests for VA appointment request flow. References #3525 and #3526
  src/applications/vaos/containers/AppointmentsPage.jsx
  src/applications/vaos/tests/e2e/community-care.e2e.spec.js
  src/applications/vaos/tests/e2e/direct-schedule.e2e.spec.js
  src/applications/vaos/tests/e2e/sleep-care.e2e.spec.js
  src/applications/vaos/tests/e2e/va-appointment.e2e.spec.js
  src/applications/vaos/tests/e2e/vaos-helpers.js
Labels: front end

#11347 Fix 4328
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/actions/ui.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/actions/transactions.unit.spec.js
  src/platform/user/profile/vet360/util/local-vet360.js
Labels: VSA

#11350 Remove Yarn from Dockerfile after image update
  Dockerfile
  script/reset-environment.sh
Labels: VSA

#11334 removed online only and distance learning instances
  src/applications/gi/components/profile/Programs.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
Labels: BAH

#11331 Fix letters app vet360 address updater on smaller screens
  src/applications/letters/containers/AddressSection.jsx
  src/applications/letters/sass/letters.scss
Labels: Disability Benefits, VSA, front end, needs peer approval, unicorns, va-letters

#11357 Make sure correct REST method is used to update/save address
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/tests/actions/transactions.unit.spec.js
  src/platform/user/profile/vet360/util/local-vet360.js
Labels: VSA

#11309 3719 add redux to vdl
  src/applications/personalization/view-dependents/components/ViewDependentsList/ViewDependentsList.jsx
  src/applications/personalization/view-dependents/containers/ViewDependentsApp.jsx
  src/applications/personalization/view-dependents/layouts/ViewDependentsLayout.jsx
  src/applications/personalization/view-dependents/layouts/ViewDependentsLists.jsx
  src/applications/personalization/view-dependents/util/index.js
  src/applications/personalization/view-dependents/view-dependents-entry.jsx
Labels: VSA

#11343 Fail build on ERROR commit status & add logging to Jenkins output to mirror Slack notifications.
  Jenkinsfile.content
Labels: devops

#11360 bradl3yC 4213 Add spinner to continue button
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/tests/containers/AddressValidationModal.unit.spec.jsx
Labels: VSA

#11330 4130 sidebar blocks for vdl
  src/applications/personalization/view-dependents/components/ViewDependentsList/ViewDependentsList.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsSidebar/ViewDependentsSidebar.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsSidebar/ViewDependentsSidebarBlock.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsSidebar/ViewDependentsSidebarBlockStates/ViewDependentSidebarBlockStates.jsx
  src/applications/personalization/view-dependents/layouts/ViewDependentsLayout.jsx
  src/applications/personalization/view-dependents/layouts/ViewDependentsLists.jsx
Labels: VSA

#11338 Removing legacy fields from vamc type.
  src/site/stages/build/drupal/graphql/bannerAlerts.graphql.js
  src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js
  src/site/stages/build/drupal/graphql/vamcOperatingStatusAndAlerts.graphql.js
Labels: needs peer approval

#11361 restore address selection radio button
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/util/local-vet360.js
Labels: VSA

#11362 Letters app address updater: initialize Vet360
  src/applications/letters/containers/AddressSection.jsx
Labels: Disability Benefits, VSA, front end, unicorns, va-letters

#11349 remove 'not available programs' column from profile page
  src/applications/gi/components/profile/Programs.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/components/vet-tec/VetTecVeteranPrograms.jsx
Labels: BAH

#11369 bradl3yC 4385 Refactor component to remove console errors
  src/platform/user/profile/vet360/actions/ui.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
Labels: VSA

#11370 changed language in cautionary info
  src/applications/gi/components/profile/CautionaryInformation.jsx
Labels: BAH

#11374 SCO: [serious] <ul> and <ol> must only directly contain <li>, <script> or <template> elements
  src/applications/static-pages/school-resources/ScoAnnouncementsWidget.jsx
  src/applications/static-pages/school-resources/ScoEventsWidget.jsx
Labels: BAH

#11363 Add pagination for results > 10
  src/applications/find-va-forms/actions/index.js
  src/applications/find-va-forms/constants/index.js
  src/applications/find-va-forms/containers/SearchResults.jsx
  src/applications/find-va-forms/helpers/index.js
  src/applications/find-va-forms/reducers/findVAFormsReducer.js
  src/applications/find-va-forms/tests/actions/index.unit.spec.js
  src/applications/find-va-forms/tests/containers/SearchResults.unit.spec.jsx
  src/applications/find-va-forms/tests/helpers/index.unit.spec.js
  src/applications/find-va-forms/tests/reducers/findVAFormsReducer.unit.spec.js
Labels: VSA, design, front end

#11371 Show correct address in address edit modal
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/actions/ui.js
  src/platform/user/profile/vet360/components/AddressField/AddressEditModal.jsx
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/actions/transactions.unit.spec.js
  src/platform/user/profile/vet360/tests/containers/AddressValidationModal.unit.spec.jsx
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA

#11364 Fix Headings on search locations results and detail views
  src/applications/facility-locator/components/LocationHours.jsx
  src/applications/facility-locator/components/LocationMap.jsx
  src/applications/facility-locator/components/search-results/LocationInfoBlock.jsx
  src/applications/facility-locator/tests/00-required.e2e.spec.js
  src/applications/facility-locator/tests/02-breadcrumbs.e2e.spec.js
Labels: VSA, facility locator, front end

#11390 restore address selection radio button
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA

#11354 Replace our mock data with the actual api request
  src/applications/find-va-forms/actions/index.js
  src/applications/find-va-forms/api/index.js
  src/applications/find-va-forms/constants/STUBBED_RESPONSE.js
  src/applications/find-va-forms/constants/example.json
  src/applications/find-va-forms/helpers/index.js
  src/applications/find-va-forms/tests/actions/index.unit.spec.js
  src/applications/find-va-forms/tests/helpers/index.unit.spec.js
Labels: VSA, front end

#11388 remove direct deposit gating
  src/applications/personalization/profile360/components/ProfileView.jsx
  src/applications/personalization/profile360/selectors.js
  src/applications/personalization/profile360/tests/selectors.unit.spec.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA

#11389 bradl3yC 4386 APO DPO FPO functionality
  src/applications/letters/components/ErrorableSelect.jsx
  src/platform/user/profile/vet360/components/AddressField/AddressEditModal.jsx
  src/platform/user/profile/vet360/components/AddressField/AddressForm.jsx
Labels: HOLD, VSA
