Repository department-of-veterans-affairs/vets-website, pull requests merged in 2019-02, with the labels that each got.

#9494 VetTec: Unable to "Continue your application" for 0994 from https://staging.va.gov/education/how-to-apply/#16654
  src/applications/edu-benefits/0994/pages/contactInformation.js
  src/applications/edu-benefits/components/createEducationApplicationStatus.jsx
  src/applications/edu-benefits/tests/0994/pages/contactInformation.unit.spec.jsx
Labels: BAH

#9500 BAH VET TEC Content updates
  src/applications/edu-benefits/0994/components/ApplicantInformation.jsx
  src/applications/edu-benefits/0994/components/EditNote.jsx
  src/applications/edu-benefits/0994/config/form.js
  src/applications/edu-benefits/0994/containers/IntroductionPage.jsx
  src/applications/edu-benefits/0994/content/bankInformation.jsx
  src/applications/edu-benefits/0994/content/benefitsEligibility.jsx
  src/applications/edu-benefits/0994/content/contactInformation.jsx
  src/applications/edu-benefits/0994/content/militaryService.jsx
  src/applications/edu-benefits/0994/pages/highTechIndustry.js
  src/applications/edu-benefits/0994/pages/militaryService.js
  src/applications/edu-benefits/0994/pages/trainingProgramsChoice.js
  src/applications/edu-benefits/0994/pages/trainingProgramsInformation.js
  src/applications/edu-benefits/tests/0994/components/ApplicantInformation.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/containers/IntroductionPage.unit.spec.jsx
  src/applications/personalization/dashboard/helpers.jsx
  src/applications/personalization/profile360/util/helpers.jsx
Labels: BAH

#9512 [Vet Tec] Update transform to filter invalid high technology type
  src/applications/edu-benefits/0994/submit-transformer.js
  src/applications/edu-benefits/tests/0994/schema/maximal-test.json
Labels: BAH

#9502 BAH VET TEC Bank Information Updates
  src/applications/edu-benefits/0994/components/PaymentView.jsx
  src/applications/edu-benefits/0994/config/form.js
  src/applications/edu-benefits/0994/pages/bankInformation.js
  src/applications/edu-benefits/0994/prefill-transformer.js
  src/applications/edu-benefits/tests/0994/pages/bankInformation.unit.spec.js
  src/applications/edu-benefits/tests/0994/schema/maximal-test.json
  src/applications/edu-benefits/tests/0994/schema/prefillData.js
  src/applications/edu-benefits/tests/0994/schema/transformedData.js
Labels: BAH

#9521 BAH Intro Page Content Updates
  src/applications/edu-benefits/0994/containers/IntroductionPage.jsx
Labels: BAH

#9522 [VET TEC] Update vets-json-schema version and update field name
  package.json
  src/applications/edu-benefits/0994/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/0994/pages/benefitsEligibility.js
  src/applications/edu-benefits/0994/pages/highTechIndustry.js
  src/applications/edu-benefits/tests/0994/pages/benefitsEligibility.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/pages/highTechIndustry.unit.spec.js
  src/applications/edu-benefits/tests/0994/schema/maximal-test.json
  src/applications/edu-benefits/tests/0994/schema/minimal-test.json
  src/applications/edu-benefits/tests/0994/schema/transformedData.js
  yarn.lock
Labels: BAH

#9529 VET TEC: Program City, State, Start date not required #16747
  src/applications/edu-benefits/0994/pages/trainingProgramsInformation.js
  src/applications/edu-benefits/0994/submit-transformer.js
  src/applications/edu-benefits/tests/0994/schema/maximal-test.json
Labels: BAH

#9535 On `education/apply-for-education-benefits/application/0994/introduction` "Start application without signing in is displayed"#16777
  src/applications/edu-benefits/0994/config/form.js
  src/applications/edu-benefits/0994/containers/IntroductionPage.jsx
  src/applications/edu-benefits/0994/pages/contactInformation.js
  src/applications/edu-benefits/tests/0994/pages/benefitsEligibility.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/schema/maximal-test.json
  src/applications/edu-benefits/tests/0994/schema/transformedData.js
Labels: BAH

#9540 VET TEC: Veteran Name, DOB, SSN not displaying for some users#16799
  src/applications/edu-benefits/0994/prefill-transformer.js
  src/applications/edu-benefits/tests/0994/prefill-transformer.unit.spec.js
  src/applications/edu-benefits/tests/0994/schema/prefillData.js
Labels: BAH

#9515 VetTec: Write e2e tests for all functionality in the launched product through submission#16633
  src/applications/disability-benefits/686/tests/686-helpers.js
  src/applications/edu-benefits/0994/config/form.js
  src/applications/edu-benefits/tests/0994/e2e/00-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/0994/e2e/vet-tec-helpers.js
  src/applications/edu-benefits/tests/0994/schema/maximal-test.json
  src/applications/edu-benefits/tests/0994/schema/minimal-test.json
  src/applications/edu-benefits/tests/0994/schema/transformedData.js
  src/applications/pensions/tests/pensions-helpers.js
  src/platform/testing/e2e/nightwatch-commands/fillAddress.js
  src/platform/testing/e2e/nightwatch-commands/fillCheckbox.js
  src/platform/testing/e2e/nightwatch-commands/fillCheckboxIf.js
  src/platform/testing/e2e/nightwatch-commands/selectRadio.js
Labels: BAH

#9524 VET TEC: Saved bank information not deleted when new account information #16742
  src/applications/edu-benefits/0994/components/PaymentView.jsx
  src/platform/forms/save-in-progress/ApplicationStatus.jsx
Labels: BAH

#9543 Code changes for Issues 16747, 16821, 16820
  src/applications/edu-benefits/0994/pages/contactInformation.js
  src/applications/edu-benefits/0994/pages/trainingProgramsInformation.js
  src/applications/edu-benefits/tests/0994/pages/contactInformation.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/pages/trainingProgramsInformation.unit.spec.js
Labels: BAH

#9544 Add 0994 fields to schema for 16819, 16795
  package.json
  src/applications/edu-benefits/0994/components/PaymentView.jsx
  src/applications/edu-benefits/0994/pages/contactInformation.js
  src/applications/edu-benefits/0994/pages/trainingProgramsInformation.js
  src/applications/edu-benefits/0994/prefill-transformer.js
  src/applications/edu-benefits/tests/0994/pages/trainingProgramsInformation.unit.spec.js
  src/applications/edu-benefits/tests/0994/schema/maximal-test.json
  src/applications/edu-benefits/tests/0994/schema/prefillData.js
  src/applications/edu-benefits/tests/0994/schema/transformedData.js
  yarn.lock
Labels: BAH

#9576 BAH VET TEC Content Updates
  src/applications/edu-benefits/0994/containers/IntroductionPage.jsx
  src/applications/edu-benefits/0994/content/bankInformation.jsx
  src/applications/edu-benefits/0994/content/contactInformation.jsx
  src/applications/edu-benefits/0994/content/militaryService.jsx
  src/applications/edu-benefits/0994/pages/militaryService.js
  src/applications/edu-benefits/0994/pages/trainingProgramsChoice.js
Labels: BAH

#9572 [VET TEC]Add conditional language to 0994 confirmation page
  src/applications/edu-benefits/0994/containers/ConfirmationPage.jsx
Labels: BAH

#9568 VET TEC: Program City, State, Start date not required #16747
  src/applications/edu-benefits/0994/pages/trainingProgramsInformation.js
  src/applications/edu-benefits/0994/submit-transformer.js
  src/applications/edu-benefits/tests/0994/schema/maximal-test.json
  src/applications/edu-benefits/tests/0994/schema/transformedData.js
Labels: BAH

#9548 BAH Don't display start application button at top only
  src/applications/edu-benefits/0994/containers/IntroductionPage.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/forms/tests/save-in-progress/SaveInProgressIntro.unit.spec.jsx
Labels: BAH

#9564 Vet Tec: pre-filled bank information is not showing on the review page#16850
  src/applications/edu-benefits/0994/components/AddressViewField.jsx
  src/applications/edu-benefits/0994/components/PaymentReviewView.jsx
  src/applications/edu-benefits/0994/components/PaymentView.jsx
  src/applications/edu-benefits/0994/components/PhoneEmailViewField.jsx
  src/applications/edu-benefits/0994/content/contactInformation.jsx
  src/applications/edu-benefits/0994/pages/bankInformation.js
  src/applications/edu-benefits/0994/pages/contactInformation.js
  src/applications/edu-benefits/0994/submit-transformer.js
  src/applications/edu-benefits/0994/utils.jsx
  src/applications/edu-benefits/tests/0994/components/PaymentReviewView.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/components/PaymentView.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/components/VetTecProgramView.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/pages/bankInformation.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/pages/educationCompleted.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/pages/highTechIndustry.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/pages/trainingProgramsChoice.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/pages/trainingProgramsInformation.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/schema/maximal-test.json
  src/applications/edu-benefits/tests/0994/utils.unit.spec.js
Labels: BAH

#9600 [Bug] Hide side-nav on mobile
  src/site/components/navigation-sidebar.html
  src/site/includes/detail-page.html
Labels: front end, website

#9589 Bah vettec test coverage
  src/applications/edu-benefits/0994/content/contactInformation.jsx
  src/applications/edu-benefits/0994/pages/highTechIndustry.js
  src/applications/edu-benefits/tests/0994/components/AddressViewField.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/components/PhoneEmailViewField.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/containers/EducationGate.unit.spec.jsx
  src/applications/edu-benefits/tests/0994/utils.unit.spec.js
Labels: BAH

#9603 Track Interactions with 22-0994 Help Text#16746
  src/applications/edu-benefits/0994/content/bankInformation.jsx
Labels: BAH

#9615 VET TEC: Update page URLs for the workflow #16931
  src/applications/edu-benefits/0994/content/bankInformation.jsx
  src/applications/edu-benefits/0994/manifest.json
  src/applications/edu-benefits/components/EducationWizard.jsx
Labels: BAH

#9617 [VET TEC] Update program info required fields
  src/applications/edu-benefits/0994/pages/trainingProgramsInformation.js
Labels: BAH

#9618 VetTec: Case sensitivity for title on Contact Information page #17022
  src/applications/edu-benefits/0994/config/form.js
  src/applications/edu-benefits/0994/pages/contactInformation.js
  src/applications/edu-benefits/tests/0994/e2e/00-all-fields.e2e.spec.js
  src/applications/personalization/profile360/util/helpers.jsx
Labels: BAH

#9619 [VET TEC] Make required asterisk in-line
  src/applications/edu-benefits/0994/content/benefitsEligibility.jsx
Labels: BAH

#9624 VetTec: Content Updates 17055, 17015
  src/applications/edu-benefits/0994/containers/IntroductionPage.jsx
  src/applications/edu-benefits/0994/content/benefitsEligibility.jsx
Labels: BAH

#9623 [VET TEC] Update bank account helper text
  src/applications/edu-benefits/0994/content/bankInformation.jsx
Labels: BAH

#9631 [VET TEC] High-tech industry language updates
  src/applications/edu-benefits/0994/content/highTechIndustry.jsx
  src/applications/edu-benefits/0994/pages/highTechIndustry.js
Labels: BAH

#9637 Change remandReturn value to match what's coming from Caseflow
  src/applications/claims-status/utils/appeals-v2-helpers.jsx
Labels: front end, unicorns

#9652 BAH - Updating title for bank information page
  src/applications/edu-benefits/0994/config/form.js
  src/applications/edu-benefits/0994/content/bankInformation.jsx
Labels: BAH
