Repository department-of-veterans-affairs/vets-website, pull requests merged in 2019-06, with the labels that each got.

#10163 1995 bah 18656
  src/applications/edu-benefits/1995/config/new-chapters.js
  src/applications/edu-benefits/1995/helpers.jsx
  src/applications/edu-benefits/1995/pages/benefitSelection.js
  src/applications/edu-benefits/1995/pages/index.js
  src/applications/edu-benefits/1995/submit-transformer.js
  src/applications/edu-benefits/tests/1995/pages/benefitSelection.unit.spec.jsx
  src/applications/edu-benefits/utils/labels.jsx
Labels: BAH

#10171 GI Bill Comparison Tool - Remove Production Flags
  src/applications/gi/actions/index.js
  src/applications/gi/components/profile/Calculator.jsx
  src/applications/gi/components/search/EligibilityForm.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/selectors/calculator.old.js
  src/applications/gi/selectors/estimator.js
  src/applications/gi/utils/helpers.js
Labels: BAH, BAH-QA-needed

#10184 Fingerprint claims and appeals fetch errors
  src/applications/claims-status/actions/index.jsx
Labels: front end, unicorns

#10185 Fix all claims analytics functions
  src/applications/disability-benefits/all-claims/analytics-functions.js
Labels: front end, unicorns

#10187 Keep status in Sentry event name
  src/applications/letters/actions/letters.js
Labels: front end, unicorns

#10192 GI Bill Comparison Tool - Colmery 111 - Remove STEM content
  src/applications/gi/components/profile/AdditionalInformation.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/containers/Modals.jsx
Labels: BAH

#10146 Show ESR server errors on Dashboard
  src/applications/hca/actions.js
  src/applications/personalization/dashboard/components/ESRError.jsx
  src/applications/personalization/dashboard/components/ManageYourVAHealthCare.jsx
  src/applications/personalization/dashboard/containers/DashboardAppNew.jsx
Labels: HOLD

#10217 Display correct housing rate by zipcode search result
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/selectors/calculator.js
Labels: BAH

#10220 18817: STEM: Make new 22-1995 questions related to STEM required
  src/applications/edu-benefits/1995/pages/activeDuty.js
  src/applications/edu-benefits/1995/pages/stem.js
Labels: BAH

#10221 18883: STEM: Update 1995 Workflow
  src/applications/edu-benefits/1995/helpers.jsx
Labels: BAH

#10236 Re disable CT 105 features
  src/applications/gi/components/search/EligibilityForm.jsx
Labels: BAH

#10253 Display correct housing rate on profile page for OJT institutions
  src/applications/gi/selectors/calculator.js
  src/applications/gi/tests/selectors/calculator.unit.spec.js
Labels: BAH

#10245 18948: Personal Information page that should not appear when changing answer to STEM question
  src/applications/edu-benefits/1995/config/new-chapters.js
Labels: BAH

#10244 VETTECH - GI Bill Comparison Tool Profile
  src/applications/gi/components/vet-tec/VetTecAdditionalInformation.jsx
  src/applications/gi/components/vet-tec/VetTecAdditionalResources.jsx
  src/applications/gi/components/vet-tec/VetTecApplicationProcess.jsx
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecContactInformation.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/tests/containers/ProfilePage.unit.spec.js
Labels: BAH

#10277 Handling focus and revising a URL handler for keyboard nav.
  src/applications/facility-locator/components/ProviderServiceDescription.jsx
  src/applications/facility-locator/containers/FacilityDetail.jsx
  src/applications/facility-locator/containers/ProviderDetail.jsx
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/sass/facility-locator.scss
Labels: 508/Accessibility, facility locator

#10320 Bah 19016 Update Auto-complete on CT to delay queries between keystrokes
  src/applications/gi/components/search/KeywordSearch.jsx
  src/applications/gi/constants.js
Labels: BAH

#10327 Added Stem scholarship notification to landing page
  src/applications/gi/components/content/StemScholarshipNotification.jsx
  src/applications/gi/containers/LandingPage.jsx
Labels: BAH

#10337 CT 111: Hide STEM Notification #19098
  src/applications/gi/containers/LandingPage.jsx
Labels: BAH

#10324 1995 bah 19026
  src/applications/edu-benefits/components/EducationWizard.jsx
  src/applications/edu-benefits/tests/components/EducationWizard.unit.spec.jsx
Labels: BAH
