Repository department-of-veterans-affairs/vets-website, pull requests merged in 2019-09, with the labels that each got.

#10671 CT 107: Unable to select any other extension besides first extension for question "Where will you take the majority of your classes? (Learn more)" #19638
  src/applications/gi/components/profile/CalculatorForm.jsx
Labels: BAH

#10654 remove break tag to fix alignment for extensions label and 'learn more' button
  src/applications/gi/components/profile/CalculatorForm.jsx
Labels: BAH, BAH-QA-needed

#10673 Remove the log line
  src/site/stages/build/drupal/graphql/GetAllPages.graphql.js
Labels: front end

#10638 VETTEC Search Results Focus Improvements
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/sass/gi.scss
Labels: BAH, bah-ct-116

#10685 Fixed Zipcode validation bug
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/reducers/calculator.js
Labels: BAH

#10677 fixed cautionary table on ipad
  src/applications/gi/components/profile/CautionaryInformation.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH, bah-comparisontool

#10716 Create PROD_FLAG_TEMPLATE.md
  .github/PROD_FLAG_TEMPLATE.md
Labels: BAH

#10699 changed heading levels
  src/applications/gi/components/profile/Calculator.jsx
  src/platform/forms/tests/forms.unit.spec.js
Labels: BAH

#10713 removed prod flag
  src/applications/gi/containers/Modals.jsx
Labels: BAH

#10708 Conditionally post 1995 as 1995s
  src/applications/edu-benefits/1995/submitForm.js
  src/applications/edu-benefits/tests/1995/02-stem-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/1995/edu-1995-helpers.js
Labels: BAH, bah-stem

#10722 GI Bill Comparison Tool School Locations Mobile Improvements
  src/applications/gi/components/profile/SchoolLocations.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#10729 1651: GIBCT® Colmery 107 - Learn more button needs an aria-label for context
  src/applications/gi/components/profile/CalculatorForm.jsx
Labels: BAH

#10712 1640 - GIBCT Screenreader bug - School Location table
  src/applications/gi/components/profile/SchoolLocations.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#10678 add approved programs table to vet tec profile page
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/sass/gi.scss
Labels: BAH, bah-ct-116

#10743 Double-escape the back-reference
  jenkins/common.groovy
Labels: front end

#10690 19534: CT 116: Add SCO information to VET TEC Profile page: Updates to VetTecContactInformation.jsx
  src/applications/gi/components/vet-tec/VetTecContactInformation.jsx
  src/applications/gi/components/vet-tec/VetTecScoContact.jsx
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
Labels: BAH, bah-ct-116

#10739 Remove 107 phase 2 prod flags
  src/applications/gi/components/profile/AdditionalInformation.jsx
  src/applications/gi/components/profile/Calculator.jsx
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/components/search/EligibilityForm.jsx
  src/applications/gi/selectors/calculator.js
Labels: BAH, bah-ct-107

#10710 added SR audio feedback to zipcode entry
  src/applications/gi/components/profile/CalculatorForm.jsx
Labels: BAH, bah-comparisontool

#10738 1707 change disability definition
  src/applications/disability-benefits/all-claims/content/newDisabilityFollowUp.jsx
Labels: Disability Benefits, front end, unicorns

#10760 19704: Phone number information not displaying extension/when no phone number is provided displays a dash
  src/applications/gi/components/vet-tec/VetTecScoContact.jsx
Labels: BAH

#10771 19706: GIBCT: School Locations Table not shown on iPad
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#10767 remove prod flag for cautionary table update
  src/applications/gi/components/profile/CautionaryInformation.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#10781 Kelsonic 484 assistive devices lists nesting
  src/applications/facility-locator/components/AppointmentInfo.jsx
  src/applications/facility-locator/sass/facility-locator.scss
Labels: 508/Accessibility, UserVoice, VSA, front end

#10776 Update CT Landing Page Announcement Content
  src/applications/gi/components/content/BenefitNotification.jsx
  src/applications/gi/components/content/StemScholarshipNotification.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/sass/gi.scss
Labels: BAH

#10759 Remove GI Bill Benefits tool availability note
  src/applications/post-911-gib-status/containers/IntroPageSummary.jsx
Labels: VSA, ed benefits, front end, unicorns, website

#10762 Add wizard up arrow icon & scss definition
  src/applications/static-pages/sass/modules/_m-education-wizard.scss
  src/site/assets/img/arrow-up-white.svg
Labels: Disability Benefits, ed benefits, front end, unicorns

#10792 Kelsonic 1284 update microtags
  src/applications/discharge-wizard/components/InstructionsPage.jsx
  src/applications/post-911-gib-status/containers/IntroPageSummary.jsx
Labels: 508/Accessibility, VSA, content, front end

#10731 Updated contentions list and ordered list by codes
  src/applications/disability-benefits/all-claims/content/disabilityLabels.js
Labels: front end, unicorns

#10694 Refactor capitalizeEachWord and re-enable logging
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/all-claims/components/NewDisability.jsx
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/constants.js
  src/applications/disability-benefits/all-claims/content/confirmation-page.jsx
  src/applications/disability-benefits/all-claims/content/newDisabilityFollowUp.jsx
  src/applications/disability-benefits/all-claims/content/ratedDisabilities.jsx
  src/applications/disability-benefits/all-claims/content/summaryOfDisabilities.jsx
  src/applications/disability-benefits/all-claims/pages/newDisabilityFollowUp.js
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: front end, unicorns

#10789 19718: CT 116: Update SCO Telephone Linked Text
  src/applications/gi/components/vet-tec/VetTecScoContact.jsx
Labels: BAH

#10721 Bah z caftercheck
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/tests/components/CalculatorForm.unit.spec.jsx
  src/applications/gi/tests/reducers/calculator.unit.spec.js
Labels: BAH, bah-sprint-30

#10797 Bah s rzipcode 1655
  src/applications/gi/reducers/calculator.js
  src/applications/gi/tests/reducers/calculator.unit.spec.js
Labels: BAH

#10811 Ensure nested lists are accessible (axe)
  src/applications/facility-locator/components/ProviderDetailBlock.jsx
  src/applications/facility-locator/components/ProviderServiceDescription.jsx
Labels: 508/Accessibility, VSA, front end

#10826 1283: Changed from using isTextable to checking phoneType too be MOBILE
  src/platform/user/profile/vet360/components/PhoneField/EditModal.jsx
  src/platform/user/profile/vet360/containers/ReceiveTextMessages.jsx
  src/platform/user/profile/vet360/tests/containers/ReceiveTextMessages.unit.spec.jsx
Labels: By Light, enhancement, front end, notifications-settings

#10825 Start work on Higher-Level Review form
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/TODO.md
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/components/WithdrawFromLegacySystem.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/containers/Form0996App.jsx
  src/applications/disability-benefits/996/form-entry.jsx
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/manifest.json
  src/applications/disability-benefits/996/reducers/index.js
  src/applications/disability-benefits/996/routes.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/00.0996-higher-level-review.e2e.spec.js
  src/applications/disability-benefits/996/tests/components/IntroductionPage.unit.spec.jsx
  src/applications/personalization/dashboard/helpers.jsx
  src/platform/forms/constants.js
Labels: Disability Benefits, VSA, front end, in progress, unicorns, work-in-progress

#10827 Improve error messaging for Drupal fetch.
  src/site/stages/build/drupal/api.js
Labels: cms
