Repository department-of-veterans-affairs/vets-website, pull requests merged in 2020-03, with the labels that each got.

#11781 Execute data push to measure search performance
  src/applications/facility-locator/components/ResultsList.jsx
Labels: VSA, facility locator, front end

#11783 STEM: Eligibility Fixes
  src/applications/edu-benefits/1995/containers/StemEligibilityView.jsx
  src/applications/edu-benefits/1995/helpers.jsx
  src/applications/edu-benefits/1995/pages/stemEligibility.js
  src/applications/edu-benefits/1995/submit-transformer.js
  src/applications/edu-benefits/tests/1995/helpers.unit.spec.jsx
  src/applications/edu-benefits/tests/1995/schema/e2e-maximal-test.json
  src/applications/edu-benefits/tests/1995/schema/maximal-test.json
  src/applications/edu-benefits/tests/1995/schema/minimal-test.json
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11763 remove prod flag per story 5639
  src/applications/gi/components/profile/InstitutionProfile.jsx
Labels: BAH, BAH-QA-needed

#11791 5503 686 add a spouse
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/current-marriage-information/currentMarriageInformation.js
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/current-marriage-information/helpers.jsx
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/does-live-with-spouse/doesLiveWithSpouse.js
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/does-live-with-spouse/helpers.js
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/index.js
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/spouse-information/spouseInformation.js
  src/applications/disability-benefits/new-686/config/chapters/stepchild-no-longer-part-of-household/stepchild-information/stepchild-information.js
  src/applications/disability-benefits/new-686/config/chapters/stepchild-no-longer-part-of-household/stepchildren/stepchildren.js
  src/applications/disability-benefits/new-686/config/chapters/veteran-information/veteran-address/veteran-address.js
  src/applications/disability-benefits/new-686/config/chapters/veteran-information/veteran-information/veteran-information.js
  src/applications/disability-benefits/new-686/config/form.js
  src/applications/disability-benefits/new-686/config/generic-schema.js
  src/applications/disability-benefits/new-686/tests/config/veteran-information.unit.spec.jsx
Labels: VSA

#11805 6014 686 add spouse unit tests p1
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/spouse-information/spouseInformation.js
  src/applications/disability-benefits/new-686/tests/config/currentMarriageInformation.unit.spec.jsx
  src/applications/disability-benefits/new-686/tests/config/currentSpouseInformation.unit.spec.jsx
  src/applications/disability-benefits/new-686/tests/config/doesLiveWithSpouse.unit.spec.jsx
Labels: VSA

#11811 bradl3yC - 6511 - Revert breaking UX change to modal open and close behavior
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA

#11815 bradl3yC - Set focus back to edit link when modals unmount
  src/platform/user/profile/vet360/components/AddressField/AddressEditModal.jsx
  src/platform/user/profile/vet360/components/base/Vet360Transaction.jsx
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/containers/Vet360ProfileField.jsx
Labels: 508/Accessibility, VSA

#11803 fix `copy mailing address` bugs
  src/platform/user/profile/vet360/components/AddressField/AddressEditModal.jsx
  src/platform/user/profile/vet360/containers/CopyMailingAddress.jsx
  src/platform/user/profile/vet360/tests/containers/CopyMailingAddress.unit.spec.jsx
Labels: VSA

#11797 Fixes format for facilities operating hours
  src/applications/facility-locator/tests/helpers.unit.spec.js
  src/applications/facility-locator/utils/helpers.js
Labels: VSA, facility locator, front end

#11817 1995-STEM Review page: "would you still like to apply" question answer should not be editable until clicking the edit button #6389
  src/applications/edu-benefits/1995/containers/StemEligibilityView.jsx
Labels: BAH

#11819 Update Education benefit forms expiration date
  src/applications/edu-benefits/1995/containers/IntroductionPage.jsx
  src/applications/edu-benefits/5490/containers/IntroductionPage.jsx
Labels: Disability Benefits, VSA, bug, front end

#11814 Adjust Data layer push for search performance analytics
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/components/ResultsList.jsx
Labels: VSA, facility locator, front end

#11812 Update HLR form entry path
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/manifest.json
Labels: Disability Benefits, VSA, front end, unicorns

#11820 6219 686 spouse marriage history part II
  src/applications/disability-benefits/new-686/components/SpouseViewField.jsx
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/current-marriage-information/currentMarriageInformation.js
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/current-spouse-marriage-history-details/currentSpouseMarriageHistoryDetails.js
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/current-spouse-marriage-history-details/helpers.jsx
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/current-spouse-marriage-history/currentSpouseMarriageHistory.js
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/index.js
  src/applications/disability-benefits/new-686/config/form.js
Labels: VSA

#11821 1995-STEM: "Based on you responses" should be "Based on your responses"
  src/applications/edu-benefits/1995/containers/StemEligibilityView.jsx
Labels: BAH

#11827 Move location of AddressValidationModal in component tree
  src/platform/user/profile/vet360/components/AddressField/AddressField.jsx
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/containers/InitializeVet360ID.jsx
  src/platform/user/profile/vet360/containers/Vet360ProfileField.jsx
  src/platform/user/profile/vet360/tests/containers/Vet360ProfileField.unit.spec.jsx
Labels: VSA

#11760 4497: How to Apply Wizard Tracking
  src/applications/edu-benefits/components/EducationWizard.jsx
  src/applications/edu-benefits/tests/components/EducationWizard.unit.spec.jsx
Labels: BAH

#11790 bradl3yC - 5005 - add e2e coverage for address validation
  src/platform/user/profile/vet360/tests/e2e/addressValidation.e2e.spec.js
  src/platform/user/profile/vet360/tests/e2e/routes.json
Labels: VSA

#11825 bradl3yC - 6213 - Google analytics FE work address validation
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
Labels: VSA

#11833 6220 unit tests add spouse p ii
  src/applications/disability-benefits/new-686/config/chapters/report-add-a-spouse/current-spouse-marriage-history/currentSpouseMarriageHistory.js
  src/applications/disability-benefits/new-686/tests/config/spouseMarriageFormerPartners.unit.spec.jsx
  src/applications/disability-benefits/new-686/tests/config/spouseMarriageHistoryDetails.unit.spec.jsx
Labels: VSA

#11829 Update form errors & schema
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/pages/contestedIssueFollowup.js
  src/applications/disability-benefits/996/validations/index.js
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/validations.js
Labels: Disability Benefits, VSA, front end, unicorns

#11841 Remove unused Letters code
  src/applications/letters/actions/letters.js
  src/applications/letters/components/Address.jsx
  src/applications/letters/components/AddressBlock.jsx
  src/applications/letters/components/AddressContent.jsx
  src/applications/letters/components/UpdateFailureAlert.jsx
  src/applications/letters/reducers/index.js
  src/applications/letters/tests/actions/letters.unit.spec.js
  src/applications/letters/tests/components/Address.unit.spec.jsx
  src/applications/letters/tests/components/AddressBlock.unit.spec.jsx
  src/applications/letters/tests/components/AddressContent.unit.spec.jsx
  src/applications/letters/tests/components/UpdateFailureAlert.unit.spec.jsx
  src/applications/letters/tests/reducers/index.unit.spec.js
  src/applications/letters/tests/utils/helpers.unit.spec.jsx
  src/applications/letters/utils/constants.js
  src/applications/letters/utils/helpers.jsx
  src/applications/letters/utils/validations.js
Labels: VSA

#11832 Centralize number to words conversion
  src/applications/disability-benefits/686/helpers.jsx
  src/applications/disability-benefits/686/tests/config/marriageHistory.unit.spec.jsx
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/pensions/helpers.jsx
  src/applications/pensions/tests/components/SpouseMarriageTitle.unit.spec.jsx
  src/applications/pensions/tests/config/marriageHistory.unit.spec.jsx
  src/applications/pensions/tests/config/spouseMarriageHistory.unit.spec.jsx
  src/platform/forms-system/src/js/utilities/data/numberToWords.js
  src/platform/forms-system/test/js/utilities/numberToWords.unit.spec.js
Labels: Disability Benefits, VSA, front end, unicorns

#11843 Change Community pharmacy label
  src/applications/facility-locator/config.js
Labels: VSA, facility locator, front end

#11853 STEM: Rogers STEM Scholarship eligibility page should display when the wrong benefit is selected #6707
  src/applications/edu-benefits/1995/helpers.jsx
  src/applications/edu-benefits/tests/1995/helpers.unit.spec.jsx
Labels: BAH, BAH-IR-needed

#11837 Use profileSchemaForms feature flag
  src/applications/personalization/profile360/components/PaymentInformationEditModal.jsx
  src/applications/personalization/profile360/tests/components/PaymentInformationEditModal.unit.spec.jsx
  src/platform/user/profile/vet360/components/AddressField/AddressEditModal.jsx
  src/platform/user/profile/vet360/components/EmailField/EmailEditModal.jsx
  src/platform/user/profile/vet360/components/PhoneField/PhoneEditModal.jsx
  src/platform/user/profile/vet360/selectors.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA

#11824 add google analytics tracking for 1995 form events
  src/applications/edu-benefits/1995/analytics-functions.js
  src/applications/edu-benefits/1995/containers/StemEligibilityView.jsx
  src/applications/edu-benefits/1995/content/stem.jsx
  src/applications/edu-benefits/1995/submitForm.js
Labels: BAH

#11828 STEM-1995: Deliver STEM Questions Updates in 1995 Form to Production #5727
  src/applications/edu-benefits/1995/config/chapters.js
  src/applications/edu-benefits/1995/content/stem.jsx
  src/applications/edu-benefits/1995/helpers.jsx
  src/applications/edu-benefits/1995/pages/stem.js
  src/applications/edu-benefits/tests/1995/02-stem-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/1995/edu-1995-helpers.js
  src/applications/edu-benefits/tests/1995/schema/e2e-maximal-test.json
Labels: BAH

#11752 5399: Remove Production Flag for 5134
  src/applications/edu-benefits/components/EducationWizard.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11855 bradl3yC - 6715 - Add spinner when using suggested address
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/actions/transactions.unit.spec.js
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA

#11849 [SCREENREADER] Move review page alert directly below accordions
  src/platform/forms-system/src/js/review/SubmitButtons.jsx
  src/platform/forms-system/src/js/review/SubmitController.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, front end, unicorns

#11860 bradl3yC - 6470 - Manage focus of profile section post validate and save
  src/platform/user/profile/vet360/containers/Vet360ProfileField.jsx
Labels: VSA

#11874 [Development] Remove HLR intro page redirect
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
Labels: Disability Benefits, VSA, bug, front end, unicorns

#11872 Suppress display for number of search results
  src/applications/facility-locator/containers/VAMap.jsx
Labels: VSA, facility locator, front end

#11875 Request facilities team front end code ownership
  .github/CODEOWNERS
Labels: VSA, facility locator, front end

#11864 show error alert on validation modal
  src/platform/user/profile/vet360/components/base/Vet360Transaction.jsx
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/containers/ReceiveTextMessages.jsx
  src/platform/user/profile/vet360/containers/Vet360ProfileField.jsx
  src/platform/user/profile/vet360/selectors.js
  src/platform/user/profile/vet360/tests/containers/Vet360ProfileField.unit.spec.jsx
  src/platform/user/profile/vet360/tests/util/transactions.unit.spec.js
  src/platform/user/profile/vet360/util/local-vet360.js
  src/platform/user/profile/vet360/util/transactions.js
  yarn.lock
Labels: VSA

#11869 Add overseas address functionality to 526
  src/applications/disability-benefits/all-claims/pages/contactInformation.js
  src/applications/disability-benefits/all-claims/tests/pages/contactInformation.unit.spec.jsx
Labels: Disability Benefits, VSA, front end

#11844 Add conditional render for PreSubmitSection
  src/platform/forms-system/src/js/components/PreSubmitSection.jsx
  src/platform/forms-system/src/js/review/SubmitButtons.jsx
  src/platform/forms-system/src/js/review/SubmitController.jsx
  src/platform/forms-system/test/js/review/SubmitController.unit.spec.jsx
  yarn.lock
Labels: enhancement, front end, platform

#11893 Fix Higher-Level Review form paths
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/TODO.md
  src/applications/disability-benefits/996/components/FormFooter.jsx
  src/applications/disability-benefits/996/components/OptOutCheckboxWidget.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/content/OptOutOfOldAppeals.jsx
  src/applications/disability-benefits/996/pages/optOutOfOldAppeals.jsx
  src/applications/disability-benefits/996/pages/veteranInformation.js
  src/applications/disability-benefits/996/tests/components/optOutOfOldAppeals.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/veteranInformation.unit.spec.jsx
Labels: Disability Benefits, VSA, bug, front end, unicorns

#11862 MDOT Confirm Page and Title Change
  package.json
  src/applications/disability-benefits/2346/config/form.js
  src/applications/disability-benefits/2346/containers/ConfirmationPage.jsx
  yarn.lock
Labels: VSA, needs peer approval, vsa-benefits-2

#11895 Hotfix for 526 disappearing UI on review page
  src/applications/disability-benefits/all-claims/pages/contactInformation.js
Labels: Disability Benefits, VSA, bug, front end

#11899 [Development] Remove emailUI class
  src/platform/forms-system/src/js/definitions/email.js
Labels: Disability Benefits, VSA, front end, platform

#11847 [SCREENREADER] Review: shift focus to edit button after editing
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
  src/platform/forms-system/src/js/utilities/ui/index.js
  src/platform/forms-system/test/js/utilities/ui.unit.spec.js
  src/platform/forms/sass/_m-schemaform.scss
Labels: 508/Accessibility, Disability Benefits, VSA, front end, unicorns

#11889 Letters app: only request letters when user has a valid address
  src/applications/letters/containers/Main.jsx
Labels: Disability Benefits, VSA, front end, va-letters

#11911 Revert 2 redirects
  src/applications/proxy-rewrite/redirects/crossDomainRedirects.json
Labels: VSA, front end

#11734 Link to urgent care benefit webpage & Remove TriWest Link from Facility Locator
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/containers/VAMap.jsx
Labels: VSA, facility locator, front end

#11909 Kelsonic 5608 use new endpoint
  src/applications/yellow-ribbon/actions/index.js
  src/applications/yellow-ribbon/actions/index.unit.spec.js
  src/applications/yellow-ribbon/api/index.js
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.unit.spec.jsx
  src/applications/yellow-ribbon/reducers/index.js
  src/applications/yellow-ribbon/reducers/index.unit.spec.js
Labels: VSA, front end

#11352 Caregiver Benefits Application (10-10CG) - First Draft
  src/applications/caregivers/10-10CG-schema.json
  src/applications/caregivers/app-entry.jsx
  src/applications/caregivers/components/AdditionalInfo/formInfo.jsx
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/components/NeedHelpFooter/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/components/SignatureInput/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/config/form.js
  src/applications/caregivers/containers/App.jsx
  src/applications/caregivers/containers/ConfirmationPage.jsx
  src/applications/caregivers/containers/IntroductionPage.jsx
  src/applications/caregivers/definitions/caregiverUI.js
  src/applications/caregivers/definitions/constants.js
  src/applications/caregivers/helpers.js
  src/applications/caregivers/manifest.json
  src/applications/caregivers/reducers/index.js
  src/applications/caregivers/routes.jsx
  src/applications/caregivers/sass/caregivers.scss
  src/applications/caregivers/sass/introductionPage.scss
  src/applications/caregivers/sass/needHelpFooter.scss
  src/applications/caregivers/sass/preSubmitCheckboxes.scss
  src/applications/caregivers/tests/00.caregivers.e2e.spec.js
  src/platform/forms/constants.js
  src/platform/forms/tests/forms.unit.spec.js
Labels: front end, infrastructure

#11907 Disable pharmacy option search on Facility Locator
  src/applications/facility-locator/constants/index.js
Labels: VSA, facility locator, front end

#11902 Add "blocked from direct deposit" alert to Profile
  src/applications/personalization/profile360/components/PaymentInformationBlocked.jsx
  src/applications/personalization/profile360/components/ProfileView.jsx
  src/applications/personalization/profile360/containers/PaymentInformation.jsx
  src/applications/personalization/profile360/selectors.js
  src/applications/personalization/profile360/tests/components/PaymentInformationBlocked.unit.spec.jsx
  src/applications/personalization/profile360/tests/components/ProfileView.unit.spec.jsx
  src/applications/personalization/profile360/tests/containers/PaymentInformation.unit.spec.jsx
  src/applications/personalization/profile360/tests/selectors.unit.spec.js
Labels: VSA

#11870 [HOLD until March 18] Remove non-SchemaForm contact info form code
  src/applications/letters/components/ErrorableSelect.jsx
  src/applications/letters/components/ErrorableTextInput.jsx
  src/applications/letters/tests/components/ErrorableSelect.unit.spec.jsx
  src/applications/letters/tests/components/ErrorableTextInput.unit.spec.jsx
  src/applications/personalization/profile360/components/PaymentInformationEditModal.jsx
  src/applications/personalization/profile360/containers/PaymentInformation.jsx
  src/applications/personalization/profile360/tests/components/PaymentInformationEditModal.unit.spec.jsx
  src/applications/personalization/profile360/tests/e2e/profile-360.e2e.spec.js
  src/applications/personalization/profile360/tests/util/paymentInformation.unit.spec.js
  src/applications/personalization/profile360/util/paymentInformation.js
  src/platform/user/profile/vet360/actions/ui.js
  src/platform/user/profile/vet360/components/AddressField/AddressEditModal.jsx
  src/platform/user/profile/vet360/components/AddressField/AddressField.jsx
  src/platform/user/profile/vet360/components/AddressField/AddressForm.jsx
  src/platform/user/profile/vet360/components/EmailField/EmailEditModal.jsx
  src/platform/user/profile/vet360/components/EmailField/EmailField.jsx
  src/platform/user/profile/vet360/components/PhoneField/PhoneEditModal.jsx
  src/platform/user/profile/vet360/components/PhoneField/PhoneField.jsx
  src/platform/user/profile/vet360/components/base/Vet360EditModal.jsx
  src/platform/user/profile/vet360/containers/CopyMailingAddress.jsx
  src/platform/user/profile/vet360/containers/Vet360ProfileField.jsx
  src/platform/user/profile/vet360/tests/actions/ui.unit.spec.js
  src/platform/user/profile/vet360/tests/components/EditModal.unit.spec.jsx
  src/platform/user/profile/vet360/tests/containers/CopyMailingAddress.unit.spec.jsx
Labels: HOLD, VSA

#11868 analytics tracking for exhaustionOfBenefitsAfterPursuingTeachingCert radio button
  src/applications/edu-benefits/1995/submitForm.js
Labels: BAH

#11938 [Development] Update HLR scheduled times review block
  src/applications/disability-benefits/996/containers/ScheduleTimesReviewField.jsx
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
Labels: Disability Benefits, VSA, front end, unicorns

#11925 [Development] Partially implement updated HLR redesign
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/TODO.md
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/containers/AddressViewField.jsx
  src/applications/disability-benefits/996/containers/SelectArrayItemsWidget.jsx
  src/applications/disability-benefits/996/content/GetFormHelp.jsx
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/content/OfficeForReview.jsx
  src/applications/disability-benefits/996/content/contactInformation.jsx
  src/applications/disability-benefits/996/content/contestedIssueFollowup.js
  src/applications/disability-benefits/996/content/contestedIssues.js
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/pages/contactInformation.js
  src/applications/disability-benefits/996/pages/contestedIssueFollowup.js
  src/applications/disability-benefits/996/pages/contestedIssues.js
  src/applications/disability-benefits/996/pages/informalConference.js
  src/applications/disability-benefits/996/pages/officeForReview.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/contactInfo.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/contestedIssueFollowup.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/officeForReview.unit.spec.js
  src/applications/disability-benefits/996/tests/schema/initialData.js
Labels: Disability Benefits, VSA, front end, unicorns

#11930 Updated GIBCT caution flag modal content
  src/applications/gi/containers/Modals.jsx
Labels: BAH

#11852 Add Checkbox group to 1010CG
  script/heroku-postbuild.sh
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/config/form.js
  src/applications/caregivers/definitions/caregiverUI.js
  src/applications/caregivers/definitions/constants.js
  src/applications/caregivers/helpers.js
Labels: UX, enhancement, front end

#11943 Remove caregiver from static heroku build
  script/heroku-postbuild.sh
Labels: bug, front end

#11928 6023 674 p1
  src/applications/disability-benefits/686c-674/config/address-schema.js
  src/applications/disability-benefits/686c-674/config/chapters/674/helpers.jsx
  src/applications/disability-benefits/686c-674/config/chapters/674/index.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-address-marriage-tuition/studentAddressMarriageTuition.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-name-ssn/helpers.jsx
  src/applications/disability-benefits/686c-674/config/chapters/674/student-name-ssn/studentNameSSN.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-school-address/studentSchoolAddress.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-term-dates/studentTermDates.js
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/does-live-with-spouse/doesLiveWithSpouse.js
  src/applications/disability-benefits/686c-674/config/chapters/taskWizard/wizard/wizard.js
  src/applications/disability-benefits/686c-674/config/constants.js
  src/applications/disability-benefits/686c-674/config/form.js
Labels: VSA

#11908 [Development] Add hide empty review uiSchema option
  src/platform/forms-system/src/js/review/ReviewFieldTemplate.jsx
  src/platform/forms-system/test/js/review/ReviewFieldTemplate.unit.spec.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, front end, unicorns

#11944 Add correct feature flip to 1010CG
  src/applications/caregivers/manifest.json
Labels: UX, bug

#11956 Kelsonic 6668 update yr fe with new design spec
  src/applications/yellow-ribbon/actions/index.js
  src/applications/yellow-ribbon/actions/index.unit.spec.js
  src/applications/yellow-ribbon/api/index.js
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/components/SearchResult/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
  src/applications/yellow-ribbon/manifest.json
  src/applications/yellow-ribbon/reducers/index.js
  src/applications/yellow-ribbon/reducers/index.unit.spec.js
Labels: VSA, front end

#11949 Fix text (grammar) on facility locator page detail
  src/applications/facility-locator/containers/FacilityDetail.jsx
Labels: VSA, facility locator, front end

#11888 [GIBS] Expose the tool-status banner as a widget for Drupal consumption
  src/applications/post-911-gib-status/containers/IntroPage.jsx
  src/applications/post-911-gib-status/containers/IntroPageSummary.jsx
  src/applications/post-911-gib-status/containers/ServiceAvailabilityBanner.jsx
  src/applications/post-911-gib-status/containers/StatusPage.jsx
  src/applications/post-911-gib-status/createPost911GiBillStatusWidget.jsx
  src/applications/post-911-gib-status/tests/containers/ServiceAvailabilityBanner.unit.spec.jsx
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
Labels: VSA

#11957 [CMS template] Fix for empty heading
  src/site/paragraphs/list_of_link_teasers.drupal.liquid
Labels: VSA

#11960 Conditionally hide state and city
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.unit.spec.jsx
Labels: VSA, design, front end

#11919 6803 Update CF content on Search Results page
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/tests/components/VetTecProgramSearchResult.unit.spec.jsx
  src/applications/gi/tests/gibct-helpers.js
  src/applications/gi/utils/render.jsx
Labels: BAH

#11952 add new COVID-19 alert to My VA Dashboard
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/applications/personalization/dashboard/covid-19.jsx
  src/applications/personalization/dashboard/tests/containers/DashboardApp.unit.spec.jsx
  src/applications/personalization/dashboard/tests/covid-19.unit.spec.jsx
  src/platform/user/profile/utilities/index.js
  src/platform/user/selectors.js
  src/platform/user/tests/profile/utilities/index.unit.spec.js
  src/platform/user/tests/selectors.unit.spec.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA

#11942 [Development] Update HLR gating wizard
  src/applications/disability-benefits/996/components/HLRWizard.jsx
  src/applications/disability-benefits/996/content/wizardLabels.jsx
  src/applications/disability-benefits/996/tests/containers/HLR-wizard.unit.spec.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#11971 Kelsonic yellow ribbon tweaks
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.unit.spec.jsx
Labels: VSA, front end

#11965 6744 674 p2
  src/applications/disability-benefits/686c-674/config/chapters/674/index.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-income-information/studentIncomeInformation.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-last-term-information/studentLastTerm.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-networth-information/studentNetworthInformation.js
  src/applications/disability-benefits/686c-674/config/constants.js
  src/applications/disability-benefits/686c-674/config/form.js
  src/applications/disability-benefits/686c-674/config/generic-schema.js
  src/applications/disability-benefits/686c-674/tests/config/studentIncomeInformation.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/studentLastTermInfo.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/studentNetworthInformation.unit.spec.jsx
Labels: VSA

#11951 CT: Improve error messaging when there is a timeout#6662
  src/applications/gi/actions/index.js
  src/applications/gi/components/ServiceError.jsx
  src/applications/gi/containers/GiBillApp.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/reducers/constants.js
  src/applications/gi/reducers/profile.js
  src/applications/gi/reducers/search.js
  src/applications/gi/tests/actions/index.unit.spec.js
  src/applications/gi/tests/containers/GiBillApp.unit.spec.js
  src/applications/gi/tests/containers/ProfilePage.unit.spec.js
  src/applications/gi/tests/containers/SearchPage.unit.spec.js
  src/applications/gi/tests/reducers/constants.unit.spec.js
  src/applications/gi/tests/reducers/profile.unit.spec.js
  src/applications/gi/tests/reducers/search.unit.spec.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11976 Fix display phone number bug on cc providers result card
  src/applications/facility-locator/components/search-results/LocationPhoneLink.jsx
Labels: VSA, facility locator, front end

#11939 526: Require conditions to have content
  src/applications/disability-benefits/all-claims/pages/addDisabilities.js
Labels: Disability Benefits, VSA, front end

#11975 Kelsonic 7109 yr bugfix
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
Labels: VSA, front end

#11973 [Development] Complete implementation of HLR redesign
  src/applications/disability-benefits/996/components/GetFormHelp.jsx
  src/applications/disability-benefits/996/components/createHLRApplicationStatus.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/containers/SameOfficeReviewField.jsx
  src/applications/disability-benefits/996/containers/SelectArrayItemsWidget.jsx
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/content/OfficeForReview.jsx
  src/applications/disability-benefits/996/content/contactInformation.jsx
  src/applications/disability-benefits/996/pages/contestedIssues.js
  src/applications/disability-benefits/996/pages/officeForReview.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/contestedIssues.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/officeForReview.unit.spec.js
  src/applications/disability-benefits/996/tests/containers/SameOfficeReviewField.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/ScheduleTimesReviewField.unit.spec.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#11991 removed prod flags for 6662 error message
  src/applications/gi/containers/GiBillApp.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11996 do not show covid19 banner to VISN8 patients
  src/applications/personalization/dashboard/covid-19.jsx
  src/applications/personalization/dashboard/tests/containers/DashboardApp.unit.spec.jsx
Labels: VSA

#11970 526 form - bug fixes for overseas address
  src/applications/disability-benefits/all-claims/pages/contactInformation.js
Labels: Disability Benefits, VSA, bug, front end

#11950 Remove repeated accordion label
  src/platform/site-wide/side-nav/components/DuplicateLineLabel.js
Labels: VSA, facility locator, front end

#11994 686 address schema widget
  src/applications/disability-benefits/686c-674/config/address-schema.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-address-marriage-tuition/studentAddressMarriageTuition.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-last-term-information/studentLastTerm.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-school-address/studentSchoolAddress.js
  src/applications/disability-benefits/686c-674/config/chapters/add-a-child/child-additional-information/child-additional-information.js
  src/applications/disability-benefits/686c-674/config/form.js
  src/applications/disability-benefits/686c-674/tests/config/childAdditionalInformation.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/studentAddressMarriageTuition.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/studentLastTermInfo.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/studentSchoolAddress.unit.spec.jsx
Labels: VSA

#12000 Add bah-code-reviewers for gi and 1995
  .github/CODEOWNERS
Labels: BAH-IR-needed, BAH-QA-needed, bah-comparisontool

#11974 Use new alert text when current date is passed school closure date.
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/tests/utils/render.unit.spec.js
  src/applications/gi/utils/render.jsx
Labels: BAH

#12004 CT: Fix spacing in Search Results Filters
  src/applications/gi/components/CheckboxGroup.jsx
  src/applications/gi/components/RadioButtons.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/sass/gi.scss
  src/applications/gi/sass/partials/_gi-search-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12014 Add original claims as a back end service for accessing the 526 form
  src/applications/disability-benefits/all-claims/containers/RequiredServicesGate.jsx
  src/platform/user/profile/constants/backendServices.js
Labels: Disability Benefits, VSA, front end

#12015 Remove original claims UI gating for 526
  src/applications/disability-benefits/wizard/pages/start.jsx
Labels: Disability Benefits, VSA, front end

#12013 [Development] COGNITION: Show cancel button in review cards
  src/applications/disability-benefits/526EZ/pages/primaryAddress.js
  src/applications/disability-benefits/526EZ/sass/disability-benefits.scss
  src/applications/disability-benefits/996/pages/contactInformation.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/all-claims/pages/contactInformation.js
  src/applications/disability-benefits/all-claims/pages/paymentInformation.js
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/edu-benefits/0994/pages/bankInformation.js
  src/applications/edu-benefits/0994/pages/contactInformation.js
  src/applications/edu-benefits/components/ReviewCardField.jsx
  src/applications/edu-benefits/sass/edu-benefits.scss
  src/platform/forms-system/src/js/components/ReviewCardField.jsx
  src/platform/forms-system/test/js/components/ReviewCardField.unit.spec.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, front end, unicorns

#12024 Wire up to wizard.
  src/applications/disability-benefits/686c-674/config/form.js
Labels: VSA

#12021 fix repeated dash in hours of operation & special string cases
  src/applications/facility-locator/tests/helpers.unit.spec.js
  src/applications/facility-locator/utils/helpers.js
Labels: VSA, facility locator, front end

#12027 Remove link in "no results found" error text.
  src/applications/facility-locator/components/ResultsList.jsx
Labels: VSA, facility locator, front end

#12028 New SetPreferences container for JAWS experiments
  src/applications/personalization/dashboard/routes.jsx
  src/applications/personalization/preferences/containers/JAWSSetPreferences.jsx
Labels: VSA

#12026 change text for school closed flag
  src/applications/gi/tests/utils/render.unit.spec.js
  src/applications/gi/utils/render.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12037 change margin to 8px for caution flags
  src/applications/gi/tests/utils/render.unit.spec.js
  src/applications/gi/utils/render.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12039 Content tweaks
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
Labels: VSA, content, front end

#12038 7281: Update link for 'Suspension of VA Benefits to Five Schools for Deceptive Practices
  src/applications/gi/containers/Modals.jsx
Labels: BAH, BAH-QA-needed

#12035 Abstract states into platform/static-data
  src/applications/yellow-ribbon/actions/index.js
  src/applications/yellow-ribbon/actions/index.unit.spec.js
  src/applications/yellow-ribbon/api/index.js
  src/applications/yellow-ribbon/constants/STATES.json
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.unit.spec.jsx
  src/platform/static-data/STATES.json
Labels: VSA, front end

#12043 the very basics of a new profile-2 app
  src/applications/personalization/profile-2/README.md
  src/applications/personalization/profile-2/components/AccountSecurity.jsx
  src/applications/personalization/profile-2/components/ConnectedApplications.jsx
  src/applications/personalization/profile-2/components/DirectDeposit.jsx
  src/applications/personalization/profile-2/components/MilitaryInformation.jsx
  src/applications/personalization/profile-2/components/PersonalInformation.jsx
  src/applications/personalization/profile-2/components/ProfileHeader.jsx
  src/applications/personalization/profile-2/components/ProfileSideNav.jsx
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/manifest.json
  src/applications/personalization/profile-2/profile-2-entry.jsx
  src/applications/personalization/profile-2/routes.jsx
  src/applications/personalization/profile-2/sass/profile-2.scss
Labels: VSA

#12045 [Development] Remove 526 unneeded reserve data
  src/applications/disability-benefits/all-claims/submit-transformer.js
  src/applications/disability-benefits/all-claims/tests/submit-transformer.unit.spec.js
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: Disability Benefits, VSA, bug, front end, unicorns

#12051 Downcase Territory
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
Labels: VSA, front end

#12050 7280: Removal of production flag for 6848 and 7281
  src/applications/gi/containers/Modals.jsx
Labels: BAH, BAH-QA-needed

#12029 fix Address parameter search bug
  src/applications/facility-locator/actions/index.js
Labels: VSA, facility locator, front end

#11527 Keyboard End-to-end test helpers
  src/applications/edu-benefits/tests/feedback-tool/01.feedback-tool-keyboard.e2e.spec.js
  src/applications/gi/tests/01-keyboard.e2e.spec.js
  src/platform/testing/e2e/nightwatch-assertions/hasFocusableCount.js
  src/platform/testing/e2e/nightwatch-assertions/hasTabbableCount.js
  src/platform/testing/e2e/nightwatch-assertions/isActiveElement.js
  src/platform/testing/e2e/nightwatch-assertions/isDisabledElement.js
  src/platform/testing/e2e/nightwatch-commands/allyEvaluateCheckboxes.js
  src/platform/testing/e2e/nightwatch-commands/allyEvaluateInput.js
  src/platform/testing/e2e/nightwatch-commands/allyEvaluateModalWindow.js
  src/platform/testing/e2e/nightwatch-commands/allyEvaluateRadioButtons.js
  src/platform/testing/e2e/nightwatch-commands/allyEvaluateSelectMenu.js
  src/platform/testing/e2e/nightwatch-commands/checkDisabledElement.js
  src/platform/testing/e2e/nightwatch-commands/repeatKeypress.js
Labels: 508/Accessibility, testing

#12056 Gate new profile-2 app
  src/applications/personalization/account/containers/AccountApp.jsx
  src/applications/personalization/connected-accounts/containers/ConnectedAcctApp.jsx
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/sass/profile-2.scss
  src/applications/personalization/profile360/containers/VAProfileApp.jsx
  src/applications/personalization/rated-disabilities/containers/RatedDisabilitiesApp.jsx
  src/applications/personalization/view-dependents/containers/ViewDependentsApp.jsx
Labels: VSA

#12003 Comparison tool school caution flag updates
  src/applications/gi/components/profile/CautionFlagDetails.jsx
  src/applications/gi/components/profile/CautionFlagHeading.jsx
  src/applications/gi/components/profile/CautionaryInformation.jsx
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/profile/SchoolClosingDetails.jsx
  src/applications/gi/components/profile/SchoolClosingHeading.jsx
  src/applications/gi/tests/components/CautionFlagDetails.unit.spec.jsx
  src/applications/gi/tests/components/CautionFlagHeading.unit.spec.jsx
  src/applications/gi/tests/components/SchoolClosingDetails.unit.spec.jsx
  src/applications/gi/tests/components/SchoolClosingHeading.unit.spec.jsx
Labels: BAH

#12054 [Tech debt] Build global AddressViewField
  src/applications/disability-benefits/526EZ/helpers.jsx
  src/applications/disability-benefits/996/containers/AddressViewField.jsx
  src/applications/disability-benefits/996/content/ForwardingAddress.jsx
  src/applications/disability-benefits/996/pages/contactInformation.js
  src/applications/disability-benefits/all-claims/content/contactInformation.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/edu-benefits/0994/components/AddressViewField.jsx
  src/applications/edu-benefits/0994/pages/contactInformation.js
  src/applications/edu-benefits/tests/0994/components/AddressViewField.unit.spec.jsx
  src/platform/forms-system/src/js/components/AddressViewField.jsx
  src/platform/forms-system/test/js/components/AddressViewField.unit.spec.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#12066 Letters: isAddressEmpty bug fix for null and undefined being passed
  src/applications/letters/tests/utils/helpers.unit.spec.jsx
  src/applications/letters/utils/helpers.jsx
Labels: Disability Benefits, VSA, bug, front end, va-letters

#12062 Feature flag for Stem Scholarship functionality
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed
