Repository department-of-veterans-affairs/vets-website, pull requests merged in 2020-08, with the labels that each got.

#13660 BDD: Remove Separate Form Code
  src/applications/disability-benefits/all-claims/submit-transformer.js
  src/applications/disability-benefits/all-claims/tests/all-claims.cypress.spec.js
  src/applications/disability-benefits/all-claims/tests/automated-tests.puppeteer.spec.js
  src/applications/disability-benefits/all-claims/tests/fixtures/data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/minimal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/minimal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/submit-transformer.unit.spec.js
  src/applications/disability-benefits/bdd/BDDApp.jsx
  src/applications/disability-benefits/bdd/analytics-events.js
  src/applications/disability-benefits/bdd/components/ConfirmationPoll.jsx
  src/applications/disability-benefits/bdd/components/IntroductionPage.jsx
  src/applications/disability-benefits/bdd/components/ValidatedServicePeriodView.jsx
  src/applications/disability-benefits/bdd/config/form.js
  src/applications/disability-benefits/bdd/constants.js
  src/applications/disability-benefits/bdd/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/bdd/content/confirmation-page.jsx
  src/applications/disability-benefits/bdd/content/evidenceTypes.jsx
  src/applications/disability-benefits/bdd/content/militaryHistory.jsx
  src/applications/disability-benefits/bdd/content/separationLocations.js
  src/applications/disability-benefits/bdd/content/serviceTreatmentRecords.jsx
  src/applications/disability-benefits/bdd/content/supportingEvidenceOrientation.jsx
  src/applications/disability-benefits/bdd/form-entry.jsx
  src/applications/disability-benefits/bdd/manifest.json
  src/applications/disability-benefits/bdd/pages/evidenceTypes.js
  src/applications/disability-benefits/bdd/pages/index.js
  src/applications/disability-benefits/bdd/pages/militaryHistory.js
  src/applications/disability-benefits/bdd/pages/serviceTreatmentRecords.js
  src/applications/disability-benefits/bdd/reducers/index.js
  src/applications/disability-benefits/bdd/routes.jsx
  src/applications/disability-benefits/bdd/sass/bdd.scss
  src/applications/disability-benefits/bdd/tests/bdd.cypress.helpers.js
  src/applications/disability-benefits/bdd/tests/bdd.cypress.spec.js
  src/applications/disability-benefits/bdd/tests/fixtures/data/full-781-781a-8940-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/maximal-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/minimal-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/newOnly-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/secondary-new-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/full-781-781a-8940-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/maximal-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/minimal-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/newOnly-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/secondary-new-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/upload-781-781a-8940-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/upload-781-781a-8940-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/mocks/application-submit.json
  src/applications/disability-benefits/bdd/tests/fixtures/mocks/document-upload.json
  src/applications/disability-benefits/bdd/tests/fixtures/mocks/feature-toggles.json
  src/applications/disability-benefits/bdd/tests/fixtures/mocks/in-progress-forms.json
  src/applications/disability-benefits/bdd/tests/fixtures/mocks/payment-information.json
  src/applications/disability-benefits/bdd/validations.js
  src/applications/disability-benefits/wizard/createWizard.jsx
  src/platform/forms/constants.js
Labels: BDD, Disability Benefits, VSA, front end

#13629 11306 Update Search Results page with new filters
  src/applications/gi/components/profile/BenefitsForm.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/components/search/OnlineClassesFilter.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/search/SearchResultGenderFilter.jsx
  src/applications/gi/components/search/SearchResultTypeOfInstitutionFilter.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/sass/partials/_gi-search-page.scss
  src/applications/gi/tests/components/InstitutionFilterForm.unit.spec.jsx
  src/applications/gi/tests/components/InstitutionSearchForm.unit.spec.jsx
  src/applications/gi/tests/components/SearchResult.unit.spec.jsx
  src/applications/gi/utils/data/religiousAffiliations.js
Labels: BAH

#13638 Change logic for CPP search option feature flag
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/api/MockLocatorApi.js
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/config.js
  src/applications/facility-locator/containers/FacilityLocatorApp.jsx
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/routes.jsx
  src/applications/facility-locator/tests/e2e/ccpDisabled.cypress.spec.js
  src/applications/facility-locator/tests/e2e/ccpEnabled.cypress.spec.js
  src/applications/facility-locator/tests/facility-helpers.js
  src/applications/facility-locator/tests/fixtures/toggle-ccp-disabled.json
  src/applications/facility-locator/tests/fixtures/toggle-ccp-enabled.json
  src/applications/facility-locator/utils/selectors.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA, facility locator, front end

#13672 Sanlouise 11552 scroll to alert
  package.json
  src/platform/user/profile/vet360/containers/AddressValidationView.jsx
  yarn.lock
Labels: VSA, front end

#13632 Education Benefits Wizard
  src/applications/edu-benefits/1990/containers/IntroductionPage.jsx
  src/applications/edu-benefits/components/GetFormHelp.jsx
  src/applications/edu-benefits/sass/edu-benefits.scss
  src/applications/edu-benefits/tests/1990/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/1990/containers/IntroductionPage.unit.spec.jsx
  src/applications/edu-benefits/tests/utils/index.js
  src/applications/edu-benefits/tests/wizard/containers/WizardContainer.unit.spec.jsx
  src/applications/edu-benefits/wizard/containers/WizardContainer.jsx
  src/applications/edu-benefits/wizard/pages/ApplyNow.jsx
  src/applications/edu-benefits/wizard/pages/ClaimingBenefitOwnService.jsx
  src/applications/edu-benefits/wizard/pages/NationalCallToService.jsx
  src/applications/edu-benefits/wizard/pages/NewBenefit.jsx
  src/applications/edu-benefits/wizard/pages/STEMScholarship.jsx
  src/applications/edu-benefits/wizard/pages/SponsorDeceased.jsx
  src/applications/edu-benefits/wizard/pages/TransferredBenefits.jsx
  src/applications/edu-benefits/wizard/pages/VetTec.jsx
  src/applications/edu-benefits/wizard/pages/WarningAlert.jsx
  src/applications/edu-benefits/wizard/pages/index.js
  src/applications/edu-benefits/wizard/pages/pageList.js
  src/applications/static-pages/tests/utils/index.js
  src/applications/static-pages/tests/wizard/edu-benefits/index.unit.spec.jsx
  src/applications/static-pages/wizard/index.js
Labels: vsa-benefits-2

#13680 Add tests for editing the four phone number fields
  src/applications/personalization/profile-2/msw-mocks.js
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.delete-email-address.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.edit-email-address.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.edit-telephone.unit.spec.jsx
  src/applications/vaos/tests/list/appointment-list.unit.spec.jsx
Labels: VSA

#13691 11306: update styling based off of ux feedback
  src/applications/gi/components/search/SearchResultGenderFilter.jsx
  src/applications/gi/sass/partials/_gi-search-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13298 Custom Submit Error
  src/applications/caregivers/components/NeedHelpFooter/index.jsx
  src/applications/caregivers/components/SubmitError/index.jsx
  src/applications/caregivers/config/form.js
  src/applications/caregivers/containers/IntroductionPage.jsx
  src/applications/caregivers/definitions/content.js
Labels: enhancement, front end

#13693 [Development] BDD: Fix a11y & other issues
  src/applications/disability-benefits/all-claims/components/ConfirmationPoll.jsx
  src/applications/disability-benefits/all-claims/pages/paymentInformation.js
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
Labels: 508/Accessibility, 526, Disability Benefits, VSA, front end

#13684 11265 - test flipper toggle
  src/applications/static-pages/view-modify-dependent/686-cta/containers/Form686CTA.jsx
Labels: VSA

#13696 Fix IE11 wrapping bug
  src/applications/personalization/profile-2/components/MHVTermsAndConditionsStatus.jsx
Labels: VSA, front end

#13694 dont auto logout the user if we dont have a response from keepalive
  src/platform/utilities/sso/index.js
  src/platform/utilities/tests/sso.unit.spec.js
Labels: bug

#13702 10696 view payments redux unit tests
  src/applications/disability-benefits/view-payments/tests/actions/index.unit.spec.js
  src/applications/disability-benefits/view-payments/tests/helpers.js
  src/applications/disability-benefits/view-payments/tests/reducers/index.unit.spec.js
Labels: VSA

#13703 [Development] BDD: Update e2e tests
  src/applications/disability-benefits/all-claims/tests/all-claims.cypress.spec.js
  src/applications/disability-benefits/all-claims/tests/automated-tests.puppeteer.spec.js
  src/applications/disability-benefits/all-claims/tests/data
  src/applications/disability-benefits/all-claims/tests/fixtures/data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/minimal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/schema/schema.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/submit-transformer.unit.spec.js
Labels: 508/Accessibility, BDD, Disability Benefits, VSA, front end

#13710 [Development] Fix BDD upload medical records header
  src/applications/disability-benefits/all-claims/content/privateMedicalRecords.jsx
  src/applications/disability-benefits/all-claims/pages/privateMedicalRecords.js
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
Labels: BDD, Disability Benefits, VSA, front end

#13722 12038 686 location payload bug
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/current-spouse-marriage-history-details/currentSpouseMarriageHistoryDetails.js
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/veteran-marriage-history-details/veteranMarriageHistoryDetails.js
  src/applications/disability-benefits/686c-674/config/helpers.js
  src/applications/disability-benefits/686c-674/config/utilities.js
  src/applications/disability-benefits/686c-674/tests/e2e/686-spouse-child-divorce-death-test-data.json
Labels: VSA

#13724 Update AdditionalInfoSections to match updated design
  src/applications/personalization/profile-2/sass/connected-apps.scss
Labels: VSA, front end

#13707 Add scrolling to alertboxes direct deposit
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
  src/applications/personalization/profile360/components/PaymentInformationEditModalError.jsx
Labels: VSA, front end

#13728 Css fix
  src/applications/personalization/profile-2/components/MHVTermsAndConditionsStatus.jsx
Labels: VSA, front end

#13713 create feature flag for 1990 wizard
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: vsa-benefits-2

#13642 22-1995 form submit tracking updates
  src/applications/edu-benefits/1995/helpers.jsx
  src/applications/edu-benefits/1995/submitForm.js
  src/applications/edu-benefits/tests/1995/helpers.unit.spec.jsx
  src/applications/edu-benefits/tests/1995/schema/maximal-test.json
  src/applications/edu-benefits/tests/1995/schema/transformedData.js
Labels: BAH

#13744 Update css mobile sub nav
  src/applications/personalization/profile-2/sass/profile-mobile-subnav.scss
Labels: VSA, front end

#13709 Add feature flipper for BDD in all-claims Form
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/config/selectors.js
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/tests/pages/militaryHistory.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/disability-benefits/wizard/pages/bdd.jsx
  src/applications/static-pages/tests/wizard/edu-benefits/index.unit.spec.jsx
  src/applications/static-pages/wizard/index.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: 526, BDD, Disability Benefits, VSA, front end

#13750 Change direct deposit link
  src/platform/site-wide/cta-widget/helpers.js
Labels: VSA, front end

#13747 Update FAQ dropdown spacing
  src/applications/personalization/profile-2/components/personal-information/GenderAndDOBSection.jsx
Labels: VSA, front end

#13746 Update years
  src/applications/yellow-ribbon/components/FindYellowRibbonPage/index.js
  src/applications/yellow-ribbon/components/SearchResultsPage/index.js
Labels: VSA, front end

#13745 Update no results messaging
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.unit.spec.jsx
Labels: VSA, front end

#13715 Updated in progress message to display correct message
  src/applications/personalization/dashboard/helpers.jsx
Labels: BAH, BAH-QA-needed

#13612 1990e Wizard
  src/applications/edu-benefits/1990e/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990e/manifest.json
  src/applications/edu-benefits/selectors/educationWizard.js
  src/applications/edu-benefits/tests/1990e/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/1990e/containers/IntroductionPage.unit.spec.jsx
  src/applications/edu-benefits/tests/utils/index.js
  src/applications/edu-benefits/wizard/containers/WizardContainer.jsx
Labels: vsa-benefits-2

#13763 526/BDD: Show Separation Location for 1-180 Days in Future
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 526, BDD, Disability Benefits, VSA, front end

#13749 Show error on Profile when unable to fetch all required data
  src/applications/personalization/profile-2/components/Profile2Wrapper.jsx
  src/applications/personalization/profile-2/components/personal-information/PersonalInformation.jsx
  src/applications/personalization/profile-2/msw-mocks.js
  src/applications/personalization/profile-2/tests/components/Profile.data-unavailable-error.unit.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.direct-deposit.cypress.spec.js
  src/applications/personalization/profile-2/tests/fixtures/401.json
  src/applications/personalization/profile-2/tests/fixtures/500.json
  src/applications/personalization/profile-2/tests/fixtures/full-name-success.json
  src/applications/personalization/profile-2/tests/fixtures/mhv-has-accepted.json
  src/applications/personalization/profile-2/tests/fixtures/personal-information-502.json
  src/applications/personalization/profile-2/tests/fixtures/personal-information-success.json
  src/applications/personalization/profile-2/tests/fixtures/service-history-502.json
  src/applications/personalization/profile-2/tests/fixtures/service-history-success.json
  src/applications/personalization/profile360/actions/index.js
  src/applications/personalization/profile360/reducers/index.js
  src/applications/personalization/profile360/selectors.js
  src/applications/personalization/profile360/tests/reducers/index.unit.spec.js
  src/applications/personalization/profile360/tests/selectors.unit.spec.js
Labels: VSA

#13686 Urgent care Mashup: Intro and Search box changes
  src/applications/facility-locator/api/MockLocatorApi.js
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/config.js
  src/applications/facility-locator/constants/index.js
  src/applications/facility-locator/constants/mock-facilities-data.js
  src/applications/facility-locator/constants/mock-facility-data-v1.json
  src/applications/facility-locator/constants/mock-facility-data.json
  src/applications/facility-locator/constants/mock-facility-v1.json
  src/applications/facility-locator/constants/mock-geocoding-data.json
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/reducers/searchQuery.js
  src/applications/facility-locator/tests/00-required.e2e.spec.js
  src/applications/facility-locator/tests/01-accessibility.e2e.spec.js
  src/applications/facility-locator/tests/02-breadcrumbs.e2e.spec.js
  src/applications/facility-locator/tests/components/AppointmentInfo.unit.spec.jsx
  src/applications/facility-locator/tests/e2e/accessibility.cypress.spec.js
  src/applications/facility-locator/tests/e2e/search.cypress.spec.js
  src/applications/facility-locator/tests/fixtures/mock-data-v1.json
Labels: VSA, facility locator, front end

#13776 Removed chevron from 10203 exit button
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/containers/InitialConfirmEligibilityView.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13789 BDD: Add Additional 526 pages to BDD Flow
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/minimal-bdd-test.json
Labels: 526, BDD, Disability Benefits, VSA, front end

#13768 11843: 10203 form not showing under "Your Applications"
  src/applications/personalization/dashboard/helpers.jsx
Labels: BAH

#13766 STEM: Signed in - Intro page - Duplicate informational alert and green start application button at top. #12201
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
Labels: BAH

#13790 12202: Update 10203 Confirmation page
  src/applications/edu-benefits/10203/containers/ConfirmationPage.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13777 Fixed content for chapter 3 and intro page
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/10203/content/stemEligibility.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13736 11237 add ga events
  src/applications/disability-benefits/view-payments/actions/index.js
  src/applications/disability-benefits/view-payments/utils.js
Labels: VSA

#13764 Update Google Analytics for the 22-10203
  src/applications/edu-benefits/10203/analytics-functions.js
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/containers/InitialConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/submitForm.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13793 fix breadcrumb on 686
  src/applications/registry.json
Labels: VSA

#13788 Added validation message to Chapter 2 and 6 of 10203
  src/applications/edu-benefits/10203/content/benefitSelection.jsx
  src/applications/edu-benefits/10203/pages/benefitSelection.js
Labels: BAH, BAH-QA-needed

#13798 10203 Review Page Margin Fix
  src/applications/edu-benefits/sass/edu-benefits.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13797 12216: Update 10203 confirmation page content
  src/applications/edu-benefits/10203/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/10203/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#13770 12186: Update Search Results - "Refine search"
  src/applications/gi/components/search/InstitutionSearchForm.jsx
Labels: BAH, BAH-QA-needed

#13818 Focus H2 when Connected Apps loads
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApps.jsx
Labels: VSA

#13822 686 options payload mapping
  src/applications/disability-benefits/686c-674/config/utilities.js
Labels: VSA

#13769 Kelsonic 10756 implement content
  src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js
  src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/LegacyContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/UnauthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/UnauthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/UnauthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/UnauthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/UnauthContent/index.unit.spec.js
  src/platform/utilities/cerner/index.js
Labels: VSA, front end

#13812 10203 Accessibility Fix - Removed Unnecessary Alert
  src/applications/edu-benefits/10203/content/directDeposit.jsx
Labels: BAH

#13688 Update Profile Page with new labels
  src/applications/gi/components/ScorecardTags.jsx
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/tests/components/ScorecardTags.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13656 1010CG Cypress Testing
  src/applications/caregivers/components/PreSubmitInfo/components/SignatureBox/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/tests/e2e/1010cg.cypress.spec.js
  src/applications/caregivers/tests/e2e/fixtures/data/oneSecondaryCaregivers.json
  src/applications/caregivers/tests/e2e/fixtures/data/requiredOnly.json
  src/applications/caregivers/tests/e2e/fixtures/data/twoSecondaryCaregivers.json
  src/applications/caregivers/tests/e2e/fixtures/mocks/feature-toggles.json
Labels: front end, testing, vsa-qa

#13704 Updated VETTEC search results length tag
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/sass/partials/_gi-search-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13774 Sanlouise 11984 add modal cypress tests
  src/applications/personalization/profile-2/tests/e2e/profile.personal-and-contact-information-modals.cypress.spec.js
Labels: VSA, front end

#13835 Update FL intro text
  src/applications/facility-locator/containers/VAMap.jsx
Labels: VSA, facility locator, front end

#13840 Show service type name in search result subhead for VA benefits
  src/applications/facility-locator/components/SearchResultsHeader.jsx
  src/applications/facility-locator/tests/components/search-results/SearchResultsHeader.unit.spec.jsx
Labels: VSA, facility locator, front end

#13836 Update Cerner ID to 757
  src/platform/utilities/cerner/index.js
Labels: VSA, front end

#13809 Focus on H1 when navigating directly to /profile/
  package.json
  src/applications/personalization/profile-2/components/Profile2Router.jsx
  src/applications/personalization/profile-2/components/ProfileMobileSubNav.jsx
  src/applications/personalization/profile-2/components/ProfileSubNav.jsx
  src/applications/personalization/profile-2/components/personal-information/PersonalInformation.jsx
  src/applications/personalization/profile-2/tests/e2e/profile.cypress.spec.js
  yarn.lock
Labels: VSA

#13852 Add "TTY: " in front of 711 <Telephone /> numbers
  src/applications/caregivers/components/NeedHelpFooter/index.jsx
  src/applications/disability-benefits/2346/components/FooterInfo.jsx
  src/applications/disability-benefits/686c-674/components/GetFormHelp.jsx
  src/applications/disability-benefits/686c-674/config/helpers.js
  src/applications/disability-benefits/996/components/GetFormHelp.jsx
  src/applications/disability-benefits/all-claims/containers/MissingServices.jsx
  src/applications/facility-locator/components/VABenefitsCall.jsx
  src/applications/personalization/profile-2/components/direct-deposit/FraudVictimAlert.jsx
  src/applications/personalization/profile360/components/PaymentInformationBlocked.jsx
  src/applications/personalization/profile360/components/PaymentInformationEditModalError.jsx
  src/applications/personalization/profile360/containers/PaymentInformation.jsx
  src/applications/personalization/profile360/tests/components/PaymentInformationEditModalError.unit.spec.jsx
  src/applications/personalization/rated-disabilities/components/RatedDisabilityList.jsx
  src/applications/personalization/rated-disabilities/components/TotalRatingStates.jsx
  src/applications/personalization/view-dependents/layouts/helpers.jsx
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/validate-mhv-account/components/errors/NeedsSSNResolution.jsx
  src/applications/validate-mhv-account/components/errors/NeedsVAPatient.jsx
  src/applications/validate-mhv-account/components/errors/VerificationFailed.jsx
  src/applications/vaos/components/NeedHelp.jsx
  src/platform/site-wide/cta-widget/components/messages/NeedsSSNResolution.jsx
  src/platform/site-wide/cta-widget/components/messages/NeedsVAPatient.jsx
  src/platform/site-wide/cta-widget/components/messages/mvi/NotFound.jsx
  src/platform/site-wide/user-nav/components/HelpMenu.jsx
  src/platform/static-data/CallHRC.jsx
  src/platform/static-data/CallNCACenter.jsx
  src/platform/static-data/CallVBACenter.jsx
Labels: VSA, front end

#13853 Sanlouise 12037 update faq links
  src/applications/personalization/profile-2/components/AccountSecurityContent.jsx
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApps.jsx
  src/applications/personalization/profile-2/tests/components/AccountSecurityContent.unit.spec.jsx
Labels: VSA, front end

#13849 Resubmitting vettec label PR after build failure
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/sass/partials/_gi-search-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13882 Update legacy content on schedule appt page
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/LegacyContent/index.unit.spec.js
Labels: VSA, content, front end

#13814 change 10203 form url and breadcrumb urls
  src/applications/edu-benefits/10203/manifest.json
  src/applications/edu-benefits/10203/tests/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/components/EducationWizard.jsx
  src/applications/registry.json
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13875 10203 - Removed chapter 3 form-page from review page
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/edu-benefits-entry.jsx
  src/applications/edu-benefits/10203/pages/confirmEligibility.js
  src/applications/edu-benefits/10203/sass/10203_stem.scss
Labels: BAH

#13833 [COGNTION]: STEM Standalone - CONSIDER removing the opt-out direct deposit message when users have opted in #12342
  src/applications/edu-benefits/10203/pages/directDeposit.js
Labels: BAH, BAH-QA-needed

#13837 CT-Filter: Gender radio button switching on refresh #12394
  src/applications/gi/components/search/GenderFilter.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/components/search/KeywordSearch.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/tests/components/RadioButtons.unit.spec.jsx
  src/applications/gi/tests/components/search/GenderFilter.unit.spec.jsx
  src/applications/gi/tests/components/search/KeywordSearch.unit.spec.jsx
  src/applications/gi/tests/utils/search.unit.spec.js
  src/applications/gi/utils/search.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13893 fix navigation issue for form 10203
  src/applications/edu-benefits/wizard/pages/ApplyNow.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13896 Add pattern to tty 711 numbers
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/LegacyContent/index.js
Labels: VSA, front end

#13734 Search result items for urgent care search mashup
  src/applications/facility-locator/api/LocatorApi.js
  src/applications/facility-locator/api/MockLocatorApi.js
  src/applications/facility-locator/components/FacilityTypeDescription.jsx
  src/applications/facility-locator/components/ProviderServiceDescription.jsx
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/components/SearchResult.jsx
  src/applications/facility-locator/components/SearchResultsHeader.jsx
  src/applications/facility-locator/components/search-results-items/CCProviderResult.jsx
  src/applications/facility-locator/components/search-results-items/PharmacyResult.jsx
  src/applications/facility-locator/components/search-results-items/UrgentCareResult.jsx
  src/applications/facility-locator/components/search-results-items/VaFacilityResult.jsx
  src/applications/facility-locator/components/search-results-items/common/LocationAddress.jsx
  src/applications/facility-locator/components/search-results-items/common/LocationDirectionsLink.jsx
  src/applications/facility-locator/components/search-results-items/common/LocationInfoBlock.jsx
  src/applications/facility-locator/components/search-results-items/common/LocationOperationStatus.jsx
  src/applications/facility-locator/components/search-results-items/common/LocationPhoneLink.jsx
  src/applications/facility-locator/config.js
  src/applications/facility-locator/constants/mock-facility-data-v1.json
  src/applications/facility-locator/constants/mock-provider-services.json
  src/applications/facility-locator/constants/mock-urgent-care-mashup-data.json
  src/applications/facility-locator/containers/FacilityDetail.jsx
  src/applications/facility-locator/containers/ProviderDetail.jsx
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/api-url-parameters.unit.spec.js
  src/applications/facility-locator/tests/components/CCProviderResult.unit.spec.jsx
  src/applications/facility-locator/tests/components/FacilityTypeDescription.unit.spec.jsx
  src/applications/facility-locator/tests/components/PharmacyResult.unit.spec.jsx
  src/applications/facility-locator/tests/components/UrgentCareAlert.unit.spec.jsx
  src/applications/facility-locator/tests/components/UrgentCareResult.unit.spec.jsx
  src/applications/facility-locator/tests/components/UrgentCareSearch.unit.spec.js
  src/applications/facility-locator/tests/components/VaFacilityResult.unit.spec.jsx
  src/applications/facility-locator/tests/components/__snapshots__/CCProviderResult.unit.spec.jsx.mocha-snapshot
  src/applications/facility-locator/tests/components/__snapshots__/PharmacyResult.unit.spec.jsx.mocha-snapshot
  src/applications/facility-locator/tests/components/__snapshots__/UrgentCareResult.unit.spec.jsx.mocha-snapshot
  src/applications/facility-locator/tests/components/__snapshots__/VaFacilityResult.unit.spec.jsx.mocha-snapshot
  src/applications/facility-locator/tests/components/search-results/LocationDirectionsLink.unit.spec.jsx
  src/applications/facility-locator/tests/components/search-results/LocationInfoBlock.unit.spec.jsx
  src/applications/facility-locator/tests/components/search-results/LocationOperationStatus.unit.spec.jsx
  src/applications/facility-locator/tests/components/search-results/LocationPhoneLink.unit.spec.jsx
  src/applications/facility-locator/tests/components/search-results/SearchResultsHeader.unit.spec.jsx
  src/applications/facility-locator/tests/helpers/facilityAddress.unit.spec.js
  src/applications/facility-locator/utils/facilityAddress.js
  src/applications/facility-locator/utils/helpers.jsx
Labels: VSA, facility locator, front end

#13874 1010CG Download PDF Link on Error
  src/applications/caregivers/components/SubmitError/DownloadLink.jsx
  src/applications/caregivers/components/SubmitError/index.jsx
  src/applications/caregivers/containers/ConfirmationPage.jsx
  src/applications/caregivers/sass/confirmationPrint.scss
Labels: front end

#13904 CT: Search showing "name" when searching on enter #12570
  src/applications/gi/containers/LandingPage.jsx
Labels: BAH, BAH-QA-needed

#13891 Sanlouise 12217 hide military info
  src/applications/personalization/profile-2/sass/personal-contact-information.scss
  src/applications/personalization/profile-2/sass/profile-2.scss
  src/applications/personalization/profile-2/tests/e2e/profile.personal-and-contact-mailing-address.cypress.spec.js
  src/platform/user/profile/vet360/components/AddressField/address-schemas.js
Labels: VSA, front end

#13892 [SEMANTIC MARKUP] Wrap wizard in a form element
  src/applications/static-pages/tests/wizard/edu-benefits/index.unit.spec.jsx
  src/applications/static-pages/wizard/index.js
Labels: 508/Accessibility, VSA, front end

#13909 1010CG Footer 508
  src/applications/caregivers/components/NeedHelpFooter/index.jsx
  src/applications/caregivers/config/form.js
  src/applications/caregivers/tests/e2e/1010cg.cypress.spec.js
Labels: 508/Accessibility, front end

#13888 fix styling on 10203 review chapter
  src/applications/edu-benefits/10203/content/programDetails.jsx
  src/applications/edu-benefits/10203/sass/10203_stem.scss
  src/applications/edu-benefits/sass/edu-benefits.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13918 SSO should redirect the user back to CSS as a last step
  src/platform/utilities/sso/index.js
  src/platform/utilities/tests/sso.unit.spec.js
Labels: bug

#13817 [AXE-CORE] STEM Standalone - ID attribute value MUST be unique #12325
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/10203/content/SaveInProgressIntro.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/forms/tests/save-in-progress/SaveInProgressIntro.unit.spec.jsx
Labels: BAH

#13917 Kelsonic 12446 fix content updates to cerner pages
  src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/UnauthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/UnauthContent/index.js
  src/platform/utilities/cerner/index.js
Labels: VSA, front end

#13799 Edu Wizards: 5495 Setup
  src/applications/edu-benefits/5495/containers/IntroductionPage.jsx
  src/applications/edu-benefits/selectors/educationWizard.js
  src/applications/edu-benefits/tests/5495/containers/IntroductionPage.unit.spec.jsx
Labels: vsa-benefits-2

#13886 EYB: Update GA for Profile Page full size accordions #11001
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/tests/components/AccordionItem.unit.spec.jsx
Labels: BAH

#13928 1010CG noindex for prod testing
  src/applications/caregivers/containers/App.jsx
Labels: front end, testing

#13936 Kelsonic 12649 change get cerner url
  src/platform/utilities/cerner/index.js
Labels: VSA, front end

#13924 Add feature flag support for all Cerner pages
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/App/index.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA, front end

#13942 Remove isCernerLive and fully depend on feature toggles
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/App/index.unit.spec.js
Labels: VSA, front end

#13933 Sanlouise 12565 update links to buttons
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.delete-email-address.unit.spec.jsx
  src/platform/user/profile/vet360/components/base/VAPEditModalActionButtons.jsx
  src/platform/user/profile/vet360/components/base/VAPEditView.jsx
  src/platform/user/profile/vet360/tests/components/VAPEditModalActionButtons.unit.spec.jsx
Labels: VSA, front end

#13903 10203 - Implement EVSS feature flag
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/10203/tests/containers/IntroductionPage.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#13949 [Cerner] Fixes for Flipper feature flag values
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/App/index.js
Labels: VSA, front end

#13839 Sanlouise 12399 update ga
  src/applications/personalization/profile-2/components/connected-apps/actions/index.js
  src/applications/personalization/profile-2/tests/components/connected-apps/actions.unit.spec.js
  src/applications/personalization/profile360/actions/paymentInformation.js
Labels: VSA, front end

#13948 Sanlouise 12127 update phone numbers
  src/applications/personalization/profile-2/sass/personal-contact-information.scss
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.unit.spec.jsx
  src/platform/user/profile/vet360/components/PhoneField/VAPPhoneField.jsx
  src/platform/user/profile/vet360/components/PhoneField/VAPPhoneView.jsx
Labels: VSA, front end

#13930 SaveInProgressIntro revert changes
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/forms/tests/save-in-progress/SaveInProgressIntro.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#13937 10203 school country
  package.json
  src/applications/edu-benefits/10203/helpers.jsx
  src/applications/edu-benefits/10203/pages/programDetails.js
  src/applications/edu-benefits/10203/tests/pages/programDetails.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/schema/e2e-maximal-test.json
  src/applications/edu-benefits/10203/tests/schema/maximal-test.json
  src/applications/edu-benefits/10203/tests/schema/minimal-test.json
  src/applications/edu-benefits/10203/tests/schema/prefillData.js
  src/applications/edu-benefits/10203/tests/schema/transformedData.js
  yarn.lock
Labels: BAH

#13959 Remove `isCernerLive` in selector
  src/applications/vaos/tests/list/appointment-list.unit.spec.jsx
  src/applications/vaos/tests/list/cancel-appointments.unit.spec.jsx
  src/applications/vaos/tests/new-appointment/va-facility-page-multi-site.unit.spec.jsx
  src/applications/vaos/tests/utils/selectors.unit.spec.js
  src/platform/user/profile/reducers/index.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/selectors.js
  src/platform/user/tests/selectors.unit.spec.js
Labels: VSA, front end

#13957 Sanlouise update copy staging review
  src/applications/personalization/profile-2/components/EmailAddressNotification.jsx
  src/applications/personalization/profile-2/components/MilitaryInformation.jsx
  src/applications/personalization/profile-2/components/connected-apps/AdditionalInfoSections.jsx
  src/applications/personalization/profile-2/components/personal-information/EmailInformationSection.jsx
Labels: VSA, front end

#13901 Fix sticky error state after invalid location search
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/components/SearchResultMessage.jsx
  src/applications/facility-locator/constants/index.js
  src/applications/facility-locator/constants/mock-failed-location.json
  src/applications/facility-locator/tests/components/SearchResultMessage.unit.spec.jsx
  src/applications/facility-locator/tests/components/__snapshots__/SearchResultMessage.unit.spec.jsx.mocha-snapshot
  src/applications/facility-locator/tests/e2e/search.cypress.spec.js
Labels: VSA, facility locator, front end

#13974 Fixes
  package.json
  src/applications/personalization/profile-2/sass/personal-contact-information.scss
  src/platform/user/profile/vet360/components/PhoneField/VAPPhoneField.jsx
Labels: VSA, front end

#13985 1010CG IA Feedback
  src/applications/registry.json
Labels: bug, content, front end

#13992 686 copy changes
  src/applications/disability-benefits/686c-674/components/IntroductionPageHeader.jsx
  src/applications/disability-benefits/686c-674/config/chapters/674/student-name-ssn/helpers.jsx
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/spouse-information/spouseInformation.js
  src/applications/disability-benefits/686c-674/config/form.js
  src/applications/registry.json
Labels: VSA

#13978 [Development/QA] Align editable card edit button
  src/platform/forms-system/src/js/fields/ArrayField.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#13963 [Development] Move 526 wizard to intro page
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
  src/applications/disability-benefits/all-claims/components/UpdateMilitaryHistory.jsx
  src/applications/disability-benefits/all-claims/components/ValidatedServicePeriodView.jsx
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/constants.js
  src/applications/disability-benefits/all-claims/containers/WizardContainer.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/pages/veteranInfo.js
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
  src/applications/disability-benefits/all-claims/tests/components/UpdateMilitaryHistory.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/containers/Form526EZApp.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/containers/WizardContainer.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/contactInformation.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/prefill-transformer.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/disability-benefits/constants.js
  src/applications/disability-benefits/wizard/WizardLink.jsx
  src/applications/disability-benefits/wizard/createWizard.jsx
  src/applications/disability-benefits/wizard/pages/bdd.jsx
  src/applications/disability-benefits/wizard/pages/file-bdd.jsx
  src/applications/disability-benefits/wizard/pages/file-claim-early.jsx
  src/applications/disability-benefits/wizard/pages/file-claim.jsx
  src/applications/disability-benefits/wizard/pages/unable-to-file-bdd-production.jsx
  src/applications/disability-benefits/wizard/pages/unable-to-file-bdd.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: 526, Disability Benefits, VSA, front end

#13894 CT-EYB: Remove 'gibctEstimateYourBenefits' Feature Flag Toggle #8004
  src/applications/caregivers/tests/e2e/fixtures/mocks/feature-toggles.json
  src/applications/disability-benefits/996/tests/fixtures/mocks/feature-toggles.json
  src/applications/gi/components/profile/Calculator.jsx
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/components/search/EligibilityForm.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecCalculator.jsx
  src/applications/gi/components/vet-tec/VetTecCalculatorForm.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/tests/components/profile/CalculatorForm.unit.spec.jsx
  src/applications/gi/tests/components/search/EligibilityForm.unit.spec.jsx
  src/applications/gi/tests/components/search/InstitutionSearchForm.unit.spec.jsx
  src/applications/gi/tests/components/vet-tec/VetTecApprovedPrograms.unit.spec.jsx
  src/applications/gi/tests/components/vet-tec/VetTecCalculatorForm.unit.spec.jsx
  src/applications/gi/tests/data/feature-toggles.json
  src/platform/testing/local-dev-mock-api/common.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH, BAH-QA-needed

#14005 Fix headers incrementing sequentially
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/UnauthContent/index.js
Labels: VSA, front end

#14008 updated link
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14009 Empty the export dir, not the whole cache
  src/site/stages/build/drupal/api.js
Labels: cms-transformer

#13585 [Development] Add ArrayField `showSave` option
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/platform/forms-system/src/js/fields/ArrayField.jsx
  src/platform/forms-system/test/js/fields/ArrayField.unit.spec.jsx
Labels: 526, Disability Benefits, VSA, front end

#13998 [Development] Allow dynamic form titles
  src/platform/forms-system/src/js/containers/FormApp.jsx
  src/platform/forms-system/test/js/containers/FormApp.unit.spec.jsx
Labels: 526, Disability Benefits, VSA, front end, unicorns

#14011 BDD: Move Separation Location to its own page to fix review page bug
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/separationLocation.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/pages/separationLocation.js
  src/applications/disability-benefits/all-claims/tests/pages/militaryHistory.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/separationLocation.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/property-names.unit.spec.js
Labels: 526, BDD, Disability Benefits, VSA, front end

#14007 Cypress e2e tests for edu-10203 form
  src/applications/edu-benefits/10203/tests/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/10203/tests/edu-10203.cypress.spec.js
  src/applications/edu-benefits/10203/tests/schema/confirmation-stem-test.json
  src/applications/edu-benefits/10203/tests/schema/e2e-maximal-test.json
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14012 Also add checkbox to residential address
  src/platform/user/profile/vet360/components/AddressField/address-schemas.js
Labels: VSA, front end

#13995 Expand test coverage for search controls and va benefits search
  src/applications/facility-locator/components/LocationHours.jsx
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/constants/mock-la-location.json
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/tests/components/SearchControls.unit.spec.jsx
  src/applications/facility-locator/tests/e2e/search.cypress.spec.js
Labels: VSA, facility locator, front end

#14029 Add download attribute to tag with name
  src/applications/caregivers/components/SubmitError/DownloadLink.jsx
Labels: 508/Accessibility, bug, front end

#14032 Fix styling
  src/platform/user/profile/vet360/components/base/VAPEditModalActionButtons.jsx
  src/platform/user/profile/vet360/components/base/VAPEditView.jsx
Labels: VSA, front end

#14033 Update analytics direct deposit
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
Labels: VSA, front end

#14039 [Development] Fix 526 wizard links
  src/applications/disability-benefits/wizard/pages/file-bdd.jsx
  src/applications/disability-benefits/wizard/pages/file-claim-early.jsx
  src/applications/disability-benefits/wizard/pages/file-claim.jsx
Labels: 526, VSA, front end

#13994 Make Facility Locator responsive
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/components/SearchResultsHeader.jsx
  src/applications/facility-locator/containers/FacilityLocatorApp.jsx
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/e2e/search.cypress.spec.js
Labels: VSA, facility locator, front end

#14041 Use intro page url for wizard check
  src/applications/disability-benefits/wizard/pages/file-bdd.jsx
  src/applications/disability-benefits/wizard/pages/file-claim-early.jsx
  src/applications/disability-benefits/wizard/pages/file-claim.jsx
Labels: 526, VSA, front end

#14047 11307: Correction of 508 defect
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
Labels: BAH

#14035 Add initial e2e tests for schedule-view-va-appointments-page
  src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js
  src/applications/static-pages/health-care-manage-benefits/fixtures/feature-toggles/disabled.json
  src/applications/static-pages/health-care-manage-benefits/fixtures/feature-toggles/enabled.json
  src/applications/static-pages/health-care-manage-benefits/fixtures/user/cerner.json
  src/applications/static-pages/health-care-manage-benefits/fixtures/user/notCerner.json
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/tests/index.cypress.spec.js
Labels: VSA, front end, testing

#14022 Update pharmacy search experience in FL
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/components/search-results-items/PharmacyResult.jsx
  src/applications/facility-locator/components/search-results-items/common/LocationPhoneLink.jsx
  src/applications/facility-locator/config.js
  src/applications/facility-locator/constants/index.js
  src/applications/facility-locator/tests/components/PharmacyResult.unit.spec.jsx
  src/applications/facility-locator/tests/e2e/search.cypress.spec.js
Labels: VSA, facility locator, front end

#13501 [Development] HLR updates
  src/applications/disability-benefits/996/components/GetFormHelp.jsx
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/content/contestableIssueAlerts.jsx
  src/applications/disability-benefits/996/content/contestedIssues.jsx
  src/applications/disability-benefits/996/content/veteranInformation.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
Labels: Disability Benefits, VSA, front end

#14052 [Development] Dynamically update 526 content for BDD flow
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/components/ITFBanner.jsx
  src/applications/disability-benefits/all-claims/components/IntroductionPage.jsx
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/constants.js
  src/applications/disability-benefits/all-claims/containers/AddPerson.jsx
  src/applications/disability-benefits/all-claims/containers/ITFWrapper.jsx
  src/applications/disability-benefits/all-claims/containers/MissingServices.jsx
  src/applications/disability-benefits/all-claims/containers/WizardContainer.jsx
  src/applications/disability-benefits/all-claims/content/introductionPage.jsx
  src/applications/disability-benefits/all-claims/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/disability-benefits/wizard/WizardLink.jsx
  src/applications/disability-benefits/wizard/pages/bdd.jsx
  src/applications/registry.json
  src/platform/forms/tests/forms.unit.spec.js
Labels: BDD, Disability Benefits, VSA, content, front end

#14059 [Development] Remove duplicate 526 title
  src/applications/disability-benefits/all-claims/containers/MissingServices.jsx
Labels: Disability Benefits, VSA, front end

#14046 Fix search button on IE11 and other minor issues
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/sass/facility-locator.scss
Labels: VSA, facility locator, front end
