Repository department-of-veterans-affairs/vets-website, pull requests merged in 2020-06, with the labels that each got.

#12859 added alternate path name staging uses for banner
  src/applications/gi/containers/GiBillApp.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12862 Add non-MVI AlertBox in Account Security
  src/applications/personalization/profile-2/components/AccountSecurityContent.jsx
  src/applications/personalization/profile-2/components/NotInMVI.jsx
  src/applications/personalization/profile-2/tests/components/AccountSecurityContent.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/NotInMVI.unit.spec.jsx
Labels: VSA, front end

#12865 Moved estimate your benefits feature flag work to new branch
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/containers/EstimateYourBenefits.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/tests/data/feature-toggles.json
  src/platform/testing/local-dev-mock-api/common.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12797 Sanlouise 5357 connected apps
  src/applications/personalization/connected-accounts/sass/connected-acct.scss
  src/applications/personalization/profile-2/components/ConnectedApplications.jsx
  src/applications/personalization/profile-2/components/connected-apps/AppDeletedAlert.jsx
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApp.jsx
  src/applications/personalization/profile-2/components/connected-apps/ConnectedAppDeleteModal.jsx
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApps.jsx
  src/applications/personalization/profile-2/components/connected-apps/actions/index.js
  src/applications/personalization/profile-2/components/connected-apps/reducers/connectedApps.js
  src/applications/personalization/profile-2/routes.js
  src/applications/personalization/profile-2/sass/connected-apps.scss
  src/applications/personalization/profile-2/sass/profile-2.scss
  src/applications/personalization/profile360/profile-360-entry.jsx
  src/applications/personalization/profile360/util/connected-apps.js
Labels: VSA, front end

#12823 set SASS lint config file path
  package.json
Labels: developer-experience

#12876 Removed duplicate data layer push for section 103
  src/applications/gi/actions/index.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12840 Scroll radiobuttons and checkboxes into view when selected in iOS Safari.
  src/applications/gi/components/Checkbox.jsx
  src/applications/gi/components/RadioButtons.jsx
  src/applications/gi/utils/helpers.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12833 Updated EYB section labels
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/tests/components/EstimateYourBenefitsForm.unit.spec.jsx
  src/applications/gi/tests/e2e/00-required.e2e.spec.js
  src/applications/gi/tests/e2e/04-dea.e2e.spec.js
  src/applications/gi/tests/e2e/05-ojt.e2e.spec.js
  src/applications/gi/tests/e2e/gibct-helpers.js
Labels: BAH

#12884 Bah e2e failures
  src/applications/gi/tests/e2e/dea-helpers.js
  src/applications/gi/tests/e2e/gibct-helpers.js
Labels: BAH

#12882 [Development] Add HLR print confirmation button
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
Labels: Disability Benefits, VSA, front end, unicorns

#12888 Update mvi alert message account security
  src/applications/personalization/profile-2/components/AccountSecurityContent.jsx
Labels: VSA, front end

#12879 Add optional chaining to props.downtime.message access
  src/platform/forms/components/AuthorizationComponent.jsx
Labels: VSA

#12860 Enable editing phone numbers and addresses
  src/applications/personalization/profile-2/components/ProfileInfoTable.jsx
  src/applications/personalization/profile-2/components/personal-information/AddressesTable.jsx
  src/applications/personalization/profile-2/components/personal-information/PhoneNumbersTable.jsx
  src/applications/personalization/profile-2/tests/components/ProfileInfoTable.unit.spec.js
  src/platform/user/profile/vet360/components/AddressField/AddressEditView.jsx
  src/platform/user/profile/vet360/components/AddressField/VAPAddressField.jsx
  src/platform/user/profile/vet360/components/PhoneField/PhoneEditView.jsx
  src/platform/user/profile/vet360/components/PhoneField/VAPPhoneField.jsx
  src/platform/user/profile/vet360/components/VAPFaxNumber.jsx
  src/platform/user/profile/vet360/components/VAPHomePhone.jsx
  src/platform/user/profile/vet360/components/VAPMailingAddress.jsx
  src/platform/user/profile/vet360/components/VAPMobilePhone.jsx
  src/platform/user/profile/vet360/components/VAPResidentialAddress.jsx
  src/platform/user/profile/vet360/components/VAPWorkPhone.jsx
  src/platform/user/profile/vet360/components/base/VAPEditView.jsx
  src/platform/user/profile/vet360/containers/AddressValidationView.jsx
  src/platform/user/profile/vet360/containers/VAPProfileField.jsx
  src/platform/user/profile/vet360/selectors.js
  src/platform/user/profile/vet360/tests/containers/AddressValidationView.unit.spec.jsx
  src/platform/user/profile/vet360/tests/selectors.unit.spec.js
Labels: VSA

#12887 MDOT Update SIP Link Text
  src/applications/disability-benefits/2346/config/form.js
Labels: VSA, vsa-benefits-2

#12891 Fix a couple Profile 2.0 bugs
  src/applications/personalization/profile-2/components/direct-deposit/DirectDeposit.jsx
  src/applications/personalization/profile-2/routes.js
  src/applications/personalization/profile-2/sass/profile-sidenav.scss
  src/applications/personalization/profiles-wrapper/ProfilesWrapper.jsx
Labels: VSA

#12885 MDOT Footer Updates
  src/applications/disability-benefits/2346/components/FooterInfo.jsx
  src/applications/disability-benefits/2346/config/form.js
Labels: VSA, vsa-benefits-2

#12873 Review Page Bug
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/config/form.js
Labels: bug, front end

#12895 Profile 2.0 - don't focus DD edit button on load
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApp.jsx
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
Labels: VSA

#12894 BDD Military History description
  src/applications/disability-benefits/bdd/pages/militaryHistory.js
Labels: BDD, Disability Benefits, VSA, front end

#12889 GI Bill Comparison Tool - Update search result link
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
Labels: BAH

#12897 MDOT Refactor SASS/CSS
  src/applications/disability-benefits/2346/components/Accessories.jsx
  src/applications/disability-benefits/2346/components/Batteries.jsx
  src/applications/disability-benefits/2346/components/ReviewCardField.jsx
  src/applications/disability-benefits/2346/constants/index.js
  src/applications/disability-benefits/2346/sass/form-2346.scss
Labels: VSA, vsa-benefits-2

#12898 Disable gi e2e that keeps failing
  src/applications/gi/tests/e2e/04-dea.e2e.spec.js
Labels: BAH, BAH-IR-needed

#12869 Restore community care pharmacy searches with feature toggle
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/config.js
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/tests/01-accessibility.e2e.spec.js
  src/applications/facility-locator/utils/selectors.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA, facility locator, front end

#12902 [Development] Show submission id for 526 non-retryable errors
  src/applications/disability-benefits/all-claims/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/all-claims/content/confirmation-page.jsx
Labels: 526, Disability Benefits, VSA, unicorns

#12903 [Development] Update to formation react v5.3.0
  package.json
  yarn.lock
Labels: 508/Accessibility, front end, platform

#12822 EYB: Add conditional indicator to Estimate Your Benefits Section questions #9296
  src/applications/gi/components/profile/BenefitsForm.jsx
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/sass/gi.scss
  src/applications/gi/sass/partials/_gi-landing-page.scss
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/tests/components/BenefitsForm.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#12830 [COGNITION]: EYB - CONSIDER hiding the HR divider from screen readers #9245
  src/applications/gi/components/profile/EstimatedBenefits.jsx
  src/applications/gi/containers/VetTecEstimateYourBenefits.jsx
Labels: BAH

#12906 Show more useful error when user cannot init in VA Profile
  src/platform/user/profile/vet360/components/base/Vet360TransactionErrorBanner.jsx
  src/platform/user/profile/vet360/util/transactions.js
Labels: VSA

#12907 MDOT Batteries Page- Update Alerts and Tests
  src/applications/disability-benefits/2346/components/Batteries.jsx
  src/applications/disability-benefits/2346/tests/Batteries.unit.spec.jsx
Labels: VSA, vsa-benefits-2

#12905 MDT Accessories Page - Update Alerts
  src/applications/disability-benefits/2346/components/Accessories.jsx
  src/applications/disability-benefits/2346/sass/form-2346.scss
  src/applications/disability-benefits/2346/tests/Accessories.unit.spec.jsx
Labels: VSA, vsa-benefits-2

#12690 MDOT- Remove api/
  src/applications/disability-benefits/2346/api/index.js
Labels: VSA, vsa-benefits-2

#12922 Fix a few Profile 2.0 typos
  src/applications/personalization/profile-2/components/Profile2Wrapper.jsx
  src/applications/personalization/profile-2/components/ProfileSideNav.jsx
  src/applications/personalization/profile-2/components/personal-information/ContactInformationSection.jsx
  src/applications/personalization/profile-2/routes.js
  src/applications/personalization/profile-2/tests/components/Profile2.unit.spec.js
  src/platform/user/profile/vet360/components/base/Vet360EditModalActionButtons.jsx
Labels: VSA

#12896 Modal Text Update
  src/applications/gi/containers/Modals.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12914 BDD Introduction Page: Exam Availability Information
  src/applications/disability-benefits/bdd/components/IntroductionPage.jsx
Labels: BDD, Disability Benefits, VSA, front end

#12904 MDT Design Feedback
  src/applications/disability-benefits/2346/components/Accessories.jsx
  src/applications/disability-benefits/2346/components/Batteries.jsx
  src/applications/disability-benefits/2346/components/FooterInfo.jsx
  src/applications/disability-benefits/2346/components/IntroductionPage.jsx
  src/applications/disability-benefits/2346/components/PersonalInfoBox.jsx
  src/applications/disability-benefits/2346/components/ReviewCardField.jsx
  src/applications/disability-benefits/2346/config/form.js
  src/applications/disability-benefits/2346/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/2346/sass/form-2346.scss
  src/applications/disability-benefits/2346/schemas/definitions/2346UI.js
  src/applications/disability-benefits/2346/tests/ConfirmationPage.unit.spec.jsx
Labels: VSA, vsa-benefits-2

#12953 [Development] Add contact info to HLR review
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/config/prefill-transformer.js
  src/applications/disability-benefits/996/containers/ReviewDescription.jsx
  src/applications/disability-benefits/996/content/contactInformation.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/contactInfo.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/ReviewDescription.unit.spec.jsx
  src/applications/disability-benefits/996/tests/prefill-transformer.unit.spec.js
Labels: Disability Benefits, VSA, front end, unicorns

#12954 Update content
  src/applications/yellow-ribbon/components/FindYellowRibbonPage/index.js
Labels: VSA, front end

#12912 Fix lost of previous element focus when exiting out of modal
  src/applications/gi/components/Modal.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12683 Add VS Code workspace extension recommendations
  .gitignore
  .vscode/extensions.json
Labels: developer-experience

#12909 added keypad to eyb number inputs on mobile
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12974 bradl3yC - add routing debt letters
  src/applications/debt-letters/actions/index.js
  src/applications/debt-letters/app-entry.jsx
  src/applications/debt-letters/components/DebtDetails.jsx
  src/applications/debt-letters/components/DebtLetterCard.jsx
  src/applications/debt-letters/components/DebtLettersContainer.jsx
  src/applications/debt-letters/components/DebtLettersList.jsx
  src/applications/debt-letters/components/DebtLettersWrapper.jsx
  src/applications/debt-letters/components/LandingPage.jsx
  src/applications/debt-letters/reducers/index.js
  src/applications/debt-letters/routes.js
  src/applications/debt-letters/tests/DebtLettersWrapper.unit.spec.jsx
Labels: front end, vsa-benefits-2

#12880 [Development] Update HLR schema & reference
  package.json
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/pages/contestedIssues.js
  yarn.lock
Labels: Disability Benefits, VSA, front end, unicorns

#12908 CT-EYB: Update VETTEC profile page behavior based on usability testing findings #9692
  src/applications/gi/components/vet-tec/VetTecApprovedProgramsList.jsx
  src/applications/gi/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/containers/VetTecEstimateYourBenefits.jsx
  src/applications/gi/sass/gi.scss
  src/applications/gi/sass/partials/_gi-vet-tec.scss
  src/applications/gi/tests/components/VetTecApprovedProgramsList.unit.spec.jsx
  src/applications/gi/tests/components/VetTecEstimateYourBenefitsForm.unit.spec.jsx
  src/applications/gi/utils/render.jsx
Labels: BAH, BAH-QA-needed

#12981 CT: Mobile "I'll be taking classes outside of the U.S. and U.S. territories" not selectable #9872
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
Labels: BAH

#12955 fix spacing between learn more button and label text
  src/applications/gi/components/search/CautionaryWarningsFilter.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12991 Remove redirects
  src/applications/proxy-rewrite/redirects/crossDomainRedirects.json
Labels: VSA, front end

#12993 Cleanup Checkbox component
  src/applications/gi/components/Checkbox.jsx
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
Labels: BAH

#12980 CT: Remove prod flag for COVID Notification #9868
  src/applications/gi/containers/GiBillApp.jsx
  src/applications/gi/tests/e2e/01-keyboard.e2e.spec.js
Labels: BAH, BAH-QA-needed

#12946 CT-EYB: Add paging to VETTEC approved programs table. #9722
  src/applications/gi/components/profile/SchoolLocations.jsx
  src/applications/gi/components/vet-tec/VetTecApprovedProgramsList.jsx
Labels: BAH, BAH-QA-needed

#12951 Fix loading state connected apps
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApp.jsx
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApps.jsx
Labels: VSA, front end

#12957 Comparison EYB section update buttons
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/tests/components/EstimateYourBenefitsForm.unit.spec.jsx
Labels: BAH

#13006 MDOT Update Address Schema
  src/applications/disability-benefits/2346/schemas/address-schema.js
Labels: VSA, vsa-benefits-2

#12999 CT: Mobile I'll be taking classes outside of the U.S. and U.S. territories focus on calculation#9951
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/tests/components/EstimateYourBenefitsForm.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#13011 Remove https://benefits.va.gov/compensation/claimexam.asp redirects
  src/applications/proxy-rewrite/redirects/crossDomainRedirects.json
Labels: VSA, front end

#13010 MDOT - Remove fullCountryName variable from AddressViewField
  src/applications/disability-benefits/2346/components/AddressViewField.jsx
  src/applications/disability-benefits/2346/tests/AddressViewField.unit.spec.jsx
Labels: VSA, vsa-benefits-2

#12996 Block DD from unauthorized users
  src/applications/personalization/profile-2/components/Profile2Router.jsx
  src/applications/personalization/profile-2/components/Profile2Wrapper.jsx
  src/applications/personalization/profile-2/components/ProfileSideNav.jsx
  src/applications/personalization/profile-2/routes.js
  src/applications/personalization/profile-2/tests/components/Profile2.unit.spec.js
  src/applications/personalization/profile-2/tests/components/Profile2Router.unit.spec.js
  src/applications/personalization/profiles-wrapper/ProfilesWrapper.jsx
Labels: VSA

#13040 [Development] Fix form 526 a11y & design issues
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
  src/applications/disability-benefits/all-claims/components/EducationTrainingField.jsx
  src/applications/disability-benefits/all-claims/components/EmploymentHistoryCard.jsx
  src/applications/disability-benefits/all-claims/components/HospitalizationPeriodView.jsx
  src/applications/disability-benefits/all-claims/components/IntroductionPage.jsx
  src/applications/disability-benefits/all-claims/components/NewDisability.jsx
  src/applications/disability-benefits/all-claims/components/PeriodOfConfinement.jsx
  src/applications/disability-benefits/all-claims/components/PrivateProviderTreatmentView.jsx
  src/applications/disability-benefits/all-claims/components/SelectArrayItemsWidget.jsx
  src/applications/disability-benefits/all-claims/components/ValidatedServicePeriodView.jsx
  src/applications/disability-benefits/all-claims/constants.js
  src/applications/disability-benefits/all-claims/containers/FormSavedPage.jsx
  src/applications/disability-benefits/all-claims/containers/MissingServices.jsx
  src/applications/disability-benefits/all-claims/content/common.jsx
  src/applications/disability-benefits/all-claims/content/confirmation-page.jsx
  src/applications/disability-benefits/all-claims/content/fullyDevelopedClaim.jsx
  src/applications/disability-benefits/all-claims/content/incidentSupport.jsx
  src/applications/disability-benefits/all-claims/content/itfWrapper.jsx
  src/applications/disability-benefits/all-claims/content/newPTSDFollowUp.jsx
  src/applications/disability-benefits/all-claims/content/unemployabilityDisabilities.jsx
  src/applications/disability-benefits/all-claims/content/vaMedicalRecords.jsx
  src/applications/disability-benefits/all-claims/content/veteranDetails.jsx
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
  src/applications/disability-benefits/all-claims/tests/components/SelectArrayItemsWidget.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/prisonerOfWar.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, front end, unicorns

#13041 Update VETTEC profile "Update benefits" button logic
  src/applications/gi/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
  src/applications/gi/tests/components/VetTecEstimateYourBenefitsForm.unit.spec.jsx
Labels: BAH

#13007 CT-EYB: Too much spacing in the Approved Programs table on mobile view #9960
  src/applications/gi/components/vet-tec/VetTecApprovedProgramsList.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12874 CT: Remove visible focus outline from headers
  src/applications/gi/sass/gi.scss
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#13069 Update dl to ol in ProfileInfoTable
  src/applications/personalization/profile-2/components/ProfileInfoTable.jsx
  src/applications/personalization/profile-2/sass/profile-info-table.scss
  src/applications/personalization/profile-2/tests/components/ProfileInfoTable.unit.spec.js
Labels: VSA, front end

#13092 Linn js qa feedback
  src/applications/caregivers/components/PreSubmitInfo/components/SignatureBox/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/components/SignatureInput/index.jsx
  src/applications/caregivers/config/form.js
  src/applications/caregivers/containers/IntroductionPage.jsx
  src/applications/caregivers/definitions/caregiverUI.js
Labels: bug, front end

#13067 Use the useLocation hook in Profile2Wrapper
  package.json
  src/applications/personalization/profile-2/components/Profile2Wrapper.jsx
  src/applications/personalization/profile-2/tests/components/Profile2.unit.spec.js
  src/applications/personalization/profile-2/tests/unit-test-helpers.spec.js
  src/platform/testing/unit/react-testing-library-helpers.js
  yarn.lock
Labels: VSA

#13099 Update content
  src/applications/static-pages/caregiver-content-toggle/On.jsx
Labels: VSA, front end

#13106 Update Terms and Conditions content
  src/applications/personalization/profile-2/components/MHVTermsAndConditionsStatus.jsx
  src/applications/personalization/profile-2/tests/components/MHVTermsAndConditionsStatus.unit.spec.jsx
Labels: VSA

#13074 Add contact email section to personal information
  src/applications/personalization/profile-2/components/personal-information/EmailInformationSection.jsx
Labels: VSA, front end

#13073 Add education benefits section and shorten DD header
  src/applications/personalization/profile-2/components/direct-deposit/DirectDeposit.jsx
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositInformation.jsx
  src/applications/personalization/profile-2/components/direct-deposit/FraudVictimAlert.jsx
Labels: VSA, front end

#13082 [CI/CD] Update CST e2e tests
  src/applications/claims-status/tests/e2e/00.claims-list-breadcrumb.e2e.spec.js
  src/applications/claims-status/tests/e2e/00.claims-list.e2e.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status-decision.e2e.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status-est-current.e2e.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status-est-past.e2e.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status-est.e2e.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status.e2e.spec.js
  src/applications/claims-status/tests/e2e/02.claim-files.e2e.spec.js
  src/applications/claims-status/tests/e2e/03.claim-details.e2e.spec.js
  src/applications/claims-status/tests/e2e/04.claim-ask-va.e2e.spec.js
  src/applications/claims-status/tests/e2e/05.claim-additional-evidence.e2e.spec.js
  src/applications/claims-status/tests/e2e/05.claim-document-request.e2e.spec.js
  src/applications/claims-status/tests/e2e/06-claim-estimation-breadcrumb.e2e.spec.js
  src/applications/claims-status/tests/e2e/06.claim-estimation.e2e.spec.js
Labels: 508/Accessibility, Disability Benefits, VSA, claim status, front end, unicorns

#13134 MDOT: Update Address Schemas
  src/applications/disability-benefits/2346/components/VeteranInfoBox.jsx
  src/applications/disability-benefits/2346/config/form.js
  src/applications/disability-benefits/2346/constants/index.js
  src/applications/disability-benefits/2346/helpers/index.js
  src/applications/disability-benefits/2346/schemas/2346UI.js
  src/applications/disability-benefits/2346/schemas/address-schema.js
Labels: vsa-benefits-2

#13131 [Development] Update BDD Intro page
  src/applications/disability-benefits/bdd/components/IntroductionPage.jsx
Labels: 508/Accessibility, BDD, Disability Benefits, VSA, front end, unicorns

#12959 Banners 9223
  package.json
  src/applications/static-pages/homepage-banner/HomepageBanner.jsx
  src/applications/static-pages/homepage-banner/createHomepageBanner.js
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/tests/HomepageBanner.unit.spec.jsx
  src/platform/site-wide/announcements/components/Downtime.jsx
  src/platform/site-wide/announcements/components/PreDowntime.jsx
  src/platform/site-wide/announcements/components/PrePreDowntime.jsx
  src/platform/site-wide/announcements/config/index.js
  src/platform/site-wide/announcements/tests/components/Downtime.unit.spec.jsx
  src/platform/site-wide/announcements/tests/components/PreDowntime.unit.spec.jsx
  src/platform/site-wide/announcements/tests/components/PrePreDowntime.unit.spec.jsx
  src/platform/site-wide/banners/components/Banners/index.js
  src/platform/site-wide/banners/components/Banners/index.unit.spec.js
  src/platform/site-wide/banners/components/HomepageBanner/index.js
  src/platform/site-wide/banners/components/HomepageBanner/index.unit.spec.js
  src/platform/site-wide/banners/components/MaintenanceBanner/config.js
  src/platform/site-wide/banners/components/MaintenanceBanner/index.js
  src/platform/site-wide/banners/components/MaintenanceBanner/index.unit.spec.js
  src/platform/site-wide/banners/index.e2e.spec.js
  src/platform/site-wide/banners/index.js
  src/platform/site-wide/banners/styles.scss
  src/platform/site-wide/index.js
  src/site/includes/header.html
  src/site/includes/homepage-banner.liquid
  yarn.lock
Labels: VSA, front end

#12925 Initial migration to v1
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/api/LocatorApi.js
  src/applications/facility-locator/components/ServicesAtFacility.jsx
  src/applications/facility-locator/config.js
  src/applications/facility-locator/containers/FacilityDetail.jsx
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/tests/02-breadcrumbs.e2e.spec.js
  src/applications/facility-locator/tests/api-url-parameters.unit.spec.js
  src/applications/facility-locator/utils/selectors.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA, facility locator, front end

#13122 fixed regex
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13139 Clear timeout to exit edit mode
  src/platform/user/profile/vet360/containers/VAPProfileField.jsx
Labels: VSA

#13023 Sanlouise 9633 tests connected apps
  src/applications/personalization/profile-2/components/connected-apps/actions/index.js
  src/applications/personalization/profile-2/components/connected-apps/reducers/connectedApps.js
  src/applications/personalization/profile-2/tests/components/connected-apps/AppDeletedAlert.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/connected-apps/ConnectedApp.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/connected-apps/ConnectedAppDeleteModal.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/connected-apps/ConnectedApps.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/connected-apps/actions.unit.spec.js
  src/applications/personalization/profile-2/tests/components/connected-apps/reducer.unit.spec.js
Labels: VSA, front end

#13155 MDOT- Fix Military Base Checkbox Path
  src/applications/disability-benefits/2346/schemas/address-schema.js
Labels: vsa-benefits-2

#13136 updated TYY to TTY
  src/applications/gi/components/vet-tec/VetTecApplicationProcess.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13159 Fix fl ccp still to use v0
  src/applications/facility-locator/api/LocatorApi.js
Labels: VSA, facility locator, front end

#13145 [SCREENREADER]: GIBCT EYB - JAWS and IE11 SHOULD NOT announce extra information when I toggle accordions #10200
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
Labels: BAH, BAH-QA-needed

#13116 BDD: Add Separation Location
  src/applications/disability-benefits/all-claims/config/schema.js
  src/applications/disability-benefits/all-claims/submit-transformer.js
  src/applications/disability-benefits/bdd/config/form.js
  src/applications/disability-benefits/bdd/content/militaryHistory.jsx
  src/applications/disability-benefits/bdd/content/separationLocations.js
  src/applications/disability-benefits/bdd/form-entry.jsx
  src/applications/disability-benefits/bdd/pages/militaryHistory.js
  src/applications/disability-benefits/bdd/sass/bdd.scss
  src/applications/disability-benefits/bdd/validations.js
Labels: BDD, Disability Benefits, VSA, front end

#13169 10035 remove duplicate SMS checkbox
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/ProfileView.jsx
  src/applications/personalization/profile360/selectors.js
  src/platform/testing/local-dev-mock-api/common.js
  src/platform/user/profile/vet360/components/MobilePhone.jsx
  src/platform/user/profile/vet360/components/PhoneField/PhoneEditModal.jsx
  src/platform/user/profile/vet360/components/PhoneField/PhoneEditView.jsx
  src/platform/user/profile/vet360/components/PhoneField/VAPPhoneField.jsx
  src/platform/user/profile/vet360/components/VAPMobilePhone.jsx
  src/platform/user/profile/vet360/components/base/Vet360Transaction.jsx
  src/platform/user/profile/vet360/components/base/Vet360TransactionPending.jsx
  src/platform/user/profile/vet360/containers/ReceiveTextMessages.jsx
  src/platform/user/profile/vet360/tests/components/Vet360TransactionPending.unit.spec.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA

#13101 Prevent entering edit mode if already editing another profile field
  src/platform/user/profile/vet360/components/VAPEmail.jsx
  src/platform/user/profile/vet360/components/VAPFaxNumber.jsx
  src/platform/user/profile/vet360/components/VAPHomePhone.jsx
  src/platform/user/profile/vet360/components/VAPMailingAddress.jsx
  src/platform/user/profile/vet360/components/VAPMobilePhone.jsx
  src/platform/user/profile/vet360/components/VAPResidentialAddress.jsx
  src/platform/user/profile/vet360/components/VAPWorkPhone.jsx
  src/platform/user/profile/vet360/constants/index.js
  src/platform/user/profile/vet360/containers/VAPProfileField.jsx
  src/platform/user/profile/vet360/tests/containers/VAPProfileField.unit.spec.jsx
Labels: VSA

#13024 Updated vets-json-schema to version 6.0.3
  package.json
  yarn.lock
Labels: BAH

#13180 [Development] Fix various issues in Form 526
  src/applications/disability-benefits/all-claims/components/EmploymentHistoryCard.jsx
  src/applications/disability-benefits/all-claims/components/HospitalizationPeriodView.jsx
  src/applications/disability-benefits/all-claims/components/IndividualsInvolvedCard.jsx
  src/applications/disability-benefits/all-claims/components/RecentJobApplicationField.jsx
  src/applications/disability-benefits/all-claims/components/UnemployabilityDoctorCareField.jsx
  src/applications/disability-benefits/all-claims/config/781/index.js
  src/applications/disability-benefits/all-claims/containers/RequiredServicesGate.jsx
  src/applications/disability-benefits/all-claims/content/claimExamsInfo.jsx
  src/applications/disability-benefits/all-claims/content/incidentDate.jsx
  src/applications/disability-benefits/all-claims/content/incidentLocation.jsx
  src/applications/disability-benefits/all-claims/content/incidentUnitAssignment.jsx
  src/applications/disability-benefits/all-claims/content/individualsInvolved.jsx
  src/applications/disability-benefits/all-claims/content/mentalHealthChanges.jsx
  src/applications/disability-benefits/all-claims/content/pastEmploymentFormDownload.jsx
  src/applications/disability-benefits/all-claims/content/paymentInformation.jsx
  src/applications/disability-benefits/all-claims/content/physicalHealthChanges.jsx
  src/applications/disability-benefits/all-claims/content/ptsdAdditionalEvents.jsx
  src/applications/disability-benefits/all-claims/content/ptsdAssaultAuthorities.jsx
  src/applications/disability-benefits/all-claims/content/ptsdFinalIncident.jsx
  src/applications/disability-benefits/all-claims/content/ptsdTypeInfo.jsx
  src/applications/disability-benefits/all-claims/content/ptsdWalkthroughChoice.jsx
  src/applications/disability-benefits/all-claims/content/secondaryOtherSources.jsx
  src/applications/disability-benefits/all-claims/content/secondaryUploadSourcesChoice.jsx
  src/applications/disability-benefits/all-claims/content/socialBehaviorChanges.jsx
  src/applications/disability-benefits/all-claims/content/unemployabilityDates.jsx
  src/applications/disability-benefits/all-claims/content/workBehaviorChanges.jsx
  src/applications/disability-benefits/all-claims/pages/additionalBehaviorChanges.js
  src/applications/disability-benefits/all-claims/pages/incidentDate.jsx
  src/applications/disability-benefits/all-claims/pages/incidentDescription.js
  src/applications/disability-benefits/all-claims/pages/individualsInvolvedFollowUp.js
  src/applications/disability-benefits/all-claims/pages/paymentInformation.js
  src/applications/disability-benefits/all-claims/pages/ptsdWalkthroughChoice781.jsx
  src/applications/disability-benefits/all-claims/pages/ptsdWalkthroughChoice781a.jsx
  src/applications/disability-benefits/all-claims/pages/secondaryIncidentDate.jsx
  src/applications/disability-benefits/all-claims/pages/secondaryIncidentDescription.js
  src/applications/disability-benefits/all-claims/tests/pages/pastEmploymentFormDownload.unit.spec.jsx
Labels: 508/Accessibility, BDD, Disability Benefits, VSA, front end, unicorns

#13160 BDD Service Treatment Records
  src/applications/disability-benefits/all-claims/config/schema.js
  src/applications/disability-benefits/all-claims/constants.js
  src/applications/disability-benefits/bdd/config/form.js
  src/applications/disability-benefits/bdd/content/evidenceTypes.jsx
  src/applications/disability-benefits/bdd/content/serviceTreatmentRecords.jsx
  src/applications/disability-benefits/bdd/content/supportingEvidenceOrientation.jsx
  src/applications/disability-benefits/bdd/pages/evidenceTypes.js
  src/applications/disability-benefits/bdd/pages/index.js
  src/applications/disability-benefits/bdd/pages/serviceTreatmentRecords.js
Labels: BDD, Disability Benefits, VSA, front end

#13187 add "set up direct deposit" state
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
  src/applications/personalization/profile-2/tests/components/DirectDepositContent.unit.spec.jsx
Labels: VSA

#13153 1010CG Submits Despite missing signatures
  src/applications/caregivers/components/PreSubmitInfo/components/SignatureBox/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/components/SignatureInput/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
Labels: bug, front end

#13148 Show alert when there are unsaved changes and a navigation event
  src/applications/personalization/profile-2/components/personal-information/PersonalInformation.jsx
  src/platform/user/profile/vet360/actions/ui.js
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA, front end

#13202 [Development] Add MVI call to add person
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/actions/index.js
  src/applications/disability-benefits/all-claims/containers/AddPerson.jsx
  src/applications/disability-benefits/all-claims/reducers/index.js
  src/applications/disability-benefits/all-claims/reducers/mvi.js
  src/applications/disability-benefits/all-claims/tests/actions/actions.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/containers/Form526EZApp.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/reducers.unit.spec.js
Labels: Disability Benefits, VSA, front end, unicorns

#13207 BDD STR Tweaks
  src/applications/disability-benefits/all-claims/content/summaryOfEvidence.jsx
  src/applications/disability-benefits/bdd/config/form.js
  src/applications/disability-benefits/bdd/content/militaryHistory.jsx
Labels: BDD, Disability Benefits, VSA, bug, front end

#13213 MDOT- Add Print Feature to Confirmation Page
  src/applications/disability-benefits/2346/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/2346/sass/form-2346.scss
Labels: vsa-benefits-2

#13195 Fix remove buildtype vagovprod condition with hideHomeBreadcrumb
  src/site/includes/breadcrumbs.drupal.liquid
Labels: VSA, front end

#13178 [Development] Accessibility fixes on review page
  src/platform/forms-system/src/js/review/ObjectField.jsx
  src/platform/forms-system/src/js/widgets/DateWidget.jsx
  src/platform/forms-system/test/js/review/ObjectField.unit.spec.jsx
Labels: 508/Accessibility, BDD, Disability Benefits, VSA, front end

#13197 Add unauth secure messaging content
  src/applications/static-pages/health-care-manage-benefits/secure-messaging/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging/components/App/styles.scss
  src/applications/static-pages/health-care-manage-benefits/secure-messaging/index.js
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
Labels: VSA, front end

#13220 [Development] Add VA employee question to BDD
  src/applications/disability-benefits/bdd/config/form.js
Labels: BDD, Disability Benefits, VSA, front end, unicorns

#13206 Add unauth get medical records page
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/styles.scss
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/index.js
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
Labels: VSA, front end

#13222 Remove "what's my routing number?" text from Direct Deposit
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositInformation.jsx
  src/applications/personalization/profile-2/components/direct-deposit/FraudVictimAlert.jsx
Labels: VSA

#13198 Add unauth view-test-and-lab-results page
  src/applications/static-pages/health-care-manage-benefits/view-test-lab-results-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-lab-results-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/view-test-lab-results-page/components/App/styles.scss
  src/applications/static-pages/health-care-manage-benefits/view-test-lab-results-page/index.js
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
Labels: VSA, front end

#13223 Update Chapter 1 of 10203 Form Workflow to match the prototype
  src/applications/edu-benefits/10203/config/chapters.js
Labels: BAH

#13209 Update padding
  src/platform/user/profile/vet360/components/PhoneField/VAPPhoneField.jsx
Labels: VSA, front end

#13183 Add unauth prescription refills content
  src/applications/static-pages/health-care-manage-benefits/prescriptions-refill-content/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/prescriptions-refill-content/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/prescriptions-refill-content/components/App/styles.scss
  src/applications/static-pages/health-care-manage-benefits/prescriptions-refill-content/index.js
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
Labels: VSA, front end

#13225 EYB: Add GA to Estimate Your Benefits Profile Section #10353
  src/applications/gi/actions/index.js
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
  src/applications/gi/tests/actions/index.unit.spec.js
  src/applications/gi/tests/components/AccordionItem.unit.spec.jsx
  src/applications/gi/tests/components/EstimateYourBenefitsForm.unit.spec.jsx
  src/applications/gi/tests/components/VetTecEstimateYourBenefitsForm.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#13182 [Development] BDD: Add end-to-end tests
  src/applications/disability-benefits/bdd/tests/00.bdd.e2e.spec.js
  src/applications/disability-benefits/bdd/tests/bdd.cypress.helpers.js
  src/applications/disability-benefits/bdd/tests/bdd.cypress.spec.js
  src/applications/disability-benefits/bdd/tests/fixtures/data/full-781-781a-8940-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/maximal-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/minimal-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/newOnly-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/secondary-new-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/full-781-781a-8940-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/maximal-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/minimal-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/newOnly-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/secondary-new-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/transformed-data/upload-781-781a-8940-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/data/upload-781-781a-8940-test.json
  src/applications/disability-benefits/bdd/tests/fixtures/mocks/application-submit.json
  src/applications/disability-benefits/bdd/tests/fixtures/mocks/document-upload.json
  src/applications/disability-benefits/bdd/tests/fixtures/mocks/feature-toggles.json
  src/applications/disability-benefits/bdd/tests/fixtures/mocks/in-progress-forms.json
  src/applications/disability-benefits/bdd/tests/fixtures/mocks/payment-information.json
Labels: 508/Accessibility, BDD, Disability Benefits, VSA, front end, unicorns

#13199 Fix Left Nav loading behavior
  src/platform/site-wide/side-nav/components/NavItem.js
  src/platform/site-wide/side-nav/components/NavItemRow.js
  src/platform/site-wide/side-nav/components/SideNav.js
  src/platform/site-wide/side-nav/tests/components/NavItem.unit.spec.js
  src/platform/site-wide/side-nav/tests/components/NavItemRow.unit.spec.js
Labels: VSA, front end

#13229 Fix return link for news releases
  src/site/layouts/press_release.drupal.liquid
Labels: VSA, front end

#13238 9790: Removal of directDeposit
  src/applications/edu-benefits/10203/config/chapters.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13240 MDOT 500 Alert on Intro Page
  src/applications/disability-benefits/2346/actions/index.js
  src/applications/disability-benefits/2346/components/ErrorMessage.jsx
  src/applications/disability-benefits/2346/tests/ErrorMessage.unit.spec.jsx
Labels: vsa-benefits-2

#13204 Accessibility skip link for EYB form
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/profile/EstimatedBenefits.jsx
  src/applications/gi/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
  src/applications/gi/containers/EstimateYourBenefits.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13256 add optional `addNameAttribute` prop to SchemaForm
  src/platform/forms-system/src/js/components/SchemaForm.jsx
Labels: VSA

#13251 9790: Update name label text for 10203
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/pages/applicantInformation.js
  src/applications/edu-benefits/10203/pages/index.js
Labels: BAH

#13237 9875: Update Chapter 4 of 10203 Form Workflow to match the prototype
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/content/activeDuty.jsx
  src/applications/edu-benefits/10203/pages/activeDuty.js
Labels: BAH, BAH-QA-needed

#13254 10316 vre chp31 form chapters
  .github/CODEOWNERS
  src/applications/vre/28-1900/TODO.md
  src/applications/vre/28-1900/components/VeteranInformationViewComponent.jsx
  src/applications/vre/28-1900/config/chapters/additional-information/additionalInformation.js
  src/applications/vre/28-1900/config/chapters/additional-information/index.js
  src/applications/vre/28-1900/config/chapters/contact-information/contactInformation.js
  src/applications/vre/28-1900/config/chapters/contact-information/index.js
  src/applications/vre/28-1900/config/chapters/contact-information/veteranAddress.js
  src/applications/vre/28-1900/config/chapters/disability-information/disabilityInformation.js
  src/applications/vre/28-1900/config/chapters/disability-information/index.js
  src/applications/vre/28-1900/config/chapters/documnent-upload/documentUpload.js
  src/applications/vre/28-1900/config/chapters/documnent-upload/index.js
  src/applications/vre/28-1900/config/chapters/education-information/educationInformation.js
  src/applications/vre/28-1900/config/chapters/education-information/index.js
  src/applications/vre/28-1900/config/chapters/military-history/index.js
  src/applications/vre/28-1900/config/chapters/military-history/serviceFlags.js
  src/applications/vre/28-1900/config/chapters/military-history/serviceHistory.js
  src/applications/vre/28-1900/config/chapters/veteran-information/index.js
  src/applications/vre/28-1900/config/chapters/veteran-information/veteranInformation.js
  src/applications/vre/28-1900/config/chapters/veteran/index.js
  src/applications/vre/28-1900/config/chapters/veteran/veteran-address/veteranAddress.js
  src/applications/vre/28-1900/config/chapters/veteran/veteran-information/veteranInformation.js
  src/applications/vre/28-1900/config/chapters/work-information/index.js
  src/applications/vre/28-1900/config/chapters/work-information/workInformation.js
  src/applications/vre/28-1900/config/constants.js
  src/applications/vre/28-1900/config/form.js
  src/applications/vre/28-1900/containers/VeteranInformation.jsx
  src/applications/vre/28-1900/sass/28-1900-chapter-31.scss
Labels: VSA

#13105 [CI/CD] Update axe-core
  package.json
  src/applications/claims-status/components/ClaimPhase.jsx
  src/applications/disability-benefits/526EZ/tests/00-all-fields.e2e.spec.js
  src/applications/disability-benefits/526EZ/tests/actions/actions.unit.spec.js
  src/applications/disability-benefits/526EZ/tests/components/AsyncDisplayWidget.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/components/ConfirmationPoll.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/components/DisabilityWizard.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/components/FormStartControls.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/components/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/components/PaymentView.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/documentUpload.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/evidenceType.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/primaryAddress.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/privateRecordChoice.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/ratedDisabilities.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/recordUpload.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/reservesNationalGuardService.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/specialCircumstances.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/config/vaFacilities.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/containers/DisabilityGate.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/helpers.unit.spec.jsx
  src/applications/disability-benefits/526EZ/tests/reducers.unit.spec.js
  src/applications/disability-benefits/526EZ/tests/validations.unit.spec.js
  src/applications/edu-benefits/0994/content/militaryService.jsx
  src/applications/edu-benefits/1990/config/form.js
  src/applications/edu-benefits/definitions/toursOfDuty.jsx
  src/applications/edu-benefits/tests/1990/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/tests/1990/edu-1990-helpers.js
  src/applications/edu-benefits/utils/labels.jsx
  src/platform/testing/e2e/nightwatch-commands/axeCheck.js
  yarn.lock
Labels: 508/Accessibility, front end, in progress

#13262 MDOT- Empty States for Review Page
  src/applications/disability-benefits/2346/components/Batteries.jsx
  src/applications/disability-benefits/2346/components/ReviewPageSupplies.jsx
  src/applications/disability-benefits/2346/tests/ReviewPageSupplies.unit.spec.jsx
Labels: vsa-benefits-2

#13273 focus back to button after closing modal in additional info section
  src/applications/gi/components/Modal.jsx
  src/applications/gi/components/profile/AdditionalInformation.jsx
  src/applications/gi/components/vet-tec/VetTecAdditionalInformation.jsx
  src/applications/gi/containers/Modals.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13258 Enable scroll in side nav on mobile (#9942)
  src/platform/site-wide/sass/modules/_m-side-nav.scss
Labels: VSA, facility locator, front end

#13167 MDOT- Cypress E2E Testing
  src/applications/disability-benefits/2346/config/form.js
  src/applications/disability-benefits/2346/tests/MDOT.cypress.spec.js
  src/applications/disability-benefits/2346/tests/data/happyPath.json
  src/applications/disability-benefits/2346/tests/data/noAccessories.json
  src/applications/disability-benefits/2346/tests/data/noBatteries.json
  src/applications/disability-benefits/2346/tests/data/noTempAddress.json
  src/applications/disability-benefits/2346/tests/data/users/eddieUserData.json
  src/applications/disability-benefits/2346/tests/data/users/gregUserData.json
  src/applications/disability-benefits/2346/tests/data/users/jerryUserData.json
  src/applications/disability-benefits/2346/tests/data/users/markUserData.json
Labels: vsa-benefits-2

#13279 Redirect contact information on Profile 2.0
  src/applications/personalization/profile-2/components/Profile2Router.jsx
Labels: VSA, front end

#13274 Add MVI check for Identity Verification
  src/applications/personalization/profile-2/components/AccountSecurityContent.jsx
Labels: VSA, front end

#13261 Working commit
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
  src/applications/personalization/profile-2/tests/components/DirectDeposit.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/DirectDepositContent.unit.spec.jsx
Labels: VSA, front end

#13277 Form 10203 Chapter 2
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/content/benefitSelection.jsx
  src/applications/edu-benefits/10203/pages/benefitSelection.js
  src/applications/edu-benefits/10203/tests/pages/benefitSelection.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13280 Use live (PPMS) data in review env
  src/applications/facility-locator/api/index.js
Labels: VSA, facility locator, front end

#13283 try to fix random breaking unit tests
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
  src/applications/discharge-wizard/components/FormQuestions.jsx
  src/applications/edu-benefits/0993/containers/FormPage.jsx
  src/applications/pensions/components/AdditionalSourcesField.jsx
  src/applications/vaos/tests/containers/VAOSApp.unit.spec.jsx
  src/platform/forms-system/src/js/containers/FormPage.jsx
  src/platform/forms-system/src/js/fields/ArrayField.jsx
  src/platform/forms-system/src/js/review/ArrayField.jsx
  src/platform/forms-system/src/js/review/ReviewChapters.jsx
  src/platform/forms-system/src/js/review/ReviewPage.jsx
  src/platform/forms/save-in-progress/RoutedSavableApp.jsx
  src/platform/forms/save-in-progress/RoutedSavableReviewPage.jsx
  src/platform/forms/save-in-progress/SaveFormLink.jsx
Labels: VSA

#13259 Remove home "/" breadcrumb accorss VAMC pages
  src/site/layouts/bios_page.drupal.liquid
  src/site/layouts/event_listing.drupal.liquid
  src/site/layouts/health_care_facility_status.drupal.liquid
  src/site/layouts/health_care_local_facility.drupal.liquid
  src/site/layouts/health_care_region_detail_page.drupal.liquid
  src/site/layouts/health_care_region_page.drupal.liquid
  src/site/layouts/leadership_listing.drupal.liquid
  src/site/layouts/person_profile.drupal.liquid
  src/site/layouts/publication_listing.drupal.liquid
  src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
Labels: VSA, front end

#13297 Update otherHealthInsurnceName to be optionally required
  src/applications/caregivers/config/form.js
  src/applications/caregivers/definitions/caregiverUI.js
Labels: VSA, bug

#13264 MDOT- Alert for No Products Selected
  src/applications/disability-benefits/2346/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/2346/tests/ConfirmationPage.unit.spec.jsx
Labels: vsa-benefits-2

#13255 10578: Create Feature Flag for RPO Routing Update
  src/platform/testing/local-dev-mock-api/common.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#13295 add alert when the DD endpoint fails
  src/applications/personalization/profile-2/components/personal-information/GenderAndDOBSection.jsx
  src/applications/personalization/profile-2/components/personal-information/PersonalInformation.jsx
  src/applications/personalization/profile360/actions/paymentInformation.js
  src/applications/personalization/profile360/selectors.js
  src/applications/personalization/profile360/tests/selectors.unit.spec.js
Labels: VSA

#13252 22-10203 - Chapter 3
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/config/form.js
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/containers/StemEligibilityView.jsx
  src/applications/edu-benefits/10203/content/programDetails.jsx
  src/applications/edu-benefits/10203/content/stemEligibility.jsx
  src/applications/edu-benefits/10203/helpers.jsx
  src/applications/edu-benefits/10203/pages/activeDuty.js
  src/applications/edu-benefits/10203/pages/confirmEligibility.js
  src/applications/edu-benefits/10203/pages/index.js
  src/applications/edu-benefits/10203/pages/programDetails.js
  src/applications/edu-benefits/10203/pages/stem.js
  src/applications/edu-benefits/10203/pages/stemEligibility.js
  src/applications/edu-benefits/10203/submit-transformer.js
  src/applications/edu-benefits/10203/submitForm.js
  src/applications/edu-benefits/10203/tests/containers/ConfirmEligibilityView.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/helpers.unit.spec.js
  src/applications/edu-benefits/10203/tests/pages/programDetails.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/pages/stemEligibility.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#13320 [Development[ HLR: Connect frontend to backend endpoints
  src/applications/disability-benefits/996/actions/index.js
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/config/submit-transformer.js
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/containers/Form0996App.jsx
  src/applications/disability-benefits/996/containers/ForwardingAddressReviewField.jsx
  src/applications/disability-benefits/996/containers/ReviewDescription.jsx
  src/applications/disability-benefits/996/containers/SelectArrayItemsWidget.jsx
  src/applications/disability-benefits/996/content/ForwardingAddress.jsx
  src/applications/disability-benefits/996/content/contactInformation.jsx
  src/applications/disability-benefits/996/content/contestableIssueAlerts.jsx
  src/applications/disability-benefits/996/content/contestedIssues.jsx
  src/applications/disability-benefits/996/content/veteranInformation.jsx
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/pages/contestedIssues.js
  src/applications/disability-benefits/996/reducers/contestableIssues.js
  src/applications/disability-benefits/996/reducers/index.js
  src/applications/disability-benefits/996/tests/actions/actions.unit.spec.js
  src/applications/disability-benefits/996/tests/components/contactInfo.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/contestedIssues.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/veteranInformation.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/ReviewDescription.unit.spec.jsx
  src/applications/disability-benefits/996/tests/fixtures/data/maximal-test.json
  src/applications/disability-benefits/996/tests/fixtures/data/transformed-maximal-test.json
  src/applications/disability-benefits/996/tests/reducers/reducers.unit.spec.js
  src/applications/disability-benefits/996/tests/schema/initialData.js
  src/applications/disability-benefits/996/tests/schema/prefill-transformer.unit.spec.js
  src/applications/disability-benefits/996/tests/schema/submit-transformer.unit.spec.js
Labels: Disability Benefits, VSA, front end

#13308 Add cancellation modal to Direct Deposit
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
Labels: VSA, front end

#13322 Handle upcoming and active downtime for Profile 2.0 services
  src/applications/personalization/profile-2/components/AccountSecurity.jsx
  src/applications/personalization/profile-2/components/Profile2Router.jsx
  src/applications/personalization/profile-2/components/personal-information/PersonalInformation.jsx
  src/applications/personalization/profile-2/tests/components/Profile2Router.unit.spec.js
  src/platform/monitoring/DowntimeNotification/components/DowntimeApproaching.jsx
  src/platform/monitoring/DowntimeNotification/components/Wrapper.jsx
  src/platform/monitoring/DowntimeNotification/containers/DowntimeNotification.jsx
Labels: VSA

#13306 Sanlouise 10397 Add cancellation modal to Personal Information
  src/platform/user/profile/vet360/containers/VAPProfileField.jsx
  src/platform/user/profile/vet360/tests/containers/VAPProfileField.unit.spec.jsx
Labels: VSA, front end

#13325 STEM form: Typo and out-of-order checkboxes in Chapter 2 #10744
  src/applications/edu-benefits/10203/content/benefitSelection.jsx
  src/applications/edu-benefits/10203/pages/benefitSelection.js
  src/applications/edu-benefits/10203/tests/pages/benefitSelection.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#13328 Fixed chapter merge error
  src/applications/edu-benefits/10203/config/chapters.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13329 [Development] HLR: Add e2e tests
  src/applications/disability-benefits/996/TODO.md
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/tests/00.0996-higher-level-review.e2e.spec.js
  src/applications/disability-benefits/996/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/fixtures/data/minimal-test.json
  src/applications/disability-benefits/996/tests/fixtures/mocks/application-submit.json
  src/applications/disability-benefits/996/tests/fixtures/mocks/feature-toggles.json
  src/applications/disability-benefits/996/tests/fixtures/mocks/in-progress-forms.json
  src/applications/disability-benefits/996/tests/hlr.cypress.helpers.js
  src/applications/disability-benefits/996/tests/hlr.cypress.spec.js
  src/applications/disability-benefits/bdd/tests/bdd.cypress.spec.js
Labels: Disability Benefits, VSA, front end

#13257 STEM: Update Chapter 5 of 10203 Form Workflow to match the prototype #9876
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/content/directDeposit.jsx
  src/applications/edu-benefits/10203/content/personalInformation.jsx
  src/applications/edu-benefits/10203/pages/directDeposit.js
  src/applications/edu-benefits/10203/pages/index.js
  src/applications/edu-benefits/10203/pages/personalInformation.js
  src/applications/edu-benefits/10203/submit-transformer.js
  src/applications/edu-benefits/10203/tests/01-all-fields.e2e.spec.js
  src/applications/edu-benefits/10203/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/edu-10203-helpers.js
  src/applications/edu-benefits/10203/tests/pages/activeDuty.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/pages/directDeposit.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/pages/personalInformation.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/prefill-transformer.unit.spec.js
  src/applications/edu-benefits/10203/tests/schema/e2e-maximal-test.json
  src/applications/edu-benefits/10203/tests/schema/maximal-test.json
  src/applications/edu-benefits/10203/tests/schema/minimal-test.json
  src/applications/edu-benefits/10203/tests/schema/prefillData.js
  src/applications/edu-benefits/10203/tests/schema/schema.unit.spec.js
  src/applications/edu-benefits/10203/tests/schema/transformedData.js
  src/applications/edu-benefits/10203/tests/submit-transformer.unit.spec.js
Labels: BAH, BAH-QA-needed

#13330 focus the `add...` CTA button when exiting modal
  src/platform/user/profile/vet360/containers/VAPProfileField.jsx
Labels: VSA

#13339 [Development] CST: Update uploaded evidence alert content
  src/applications/claims-status/actions/index.jsx
Labels: Disability Benefits, VSA, claim status, front end
