Repository department-of-veterans-affairs/vets-website, pull requests merged in 2020-04, with the labels that each got.

#12070 Reset `page` to 1 on new search
  src/applications/yellow-ribbon/actions/index.js
  src/applications/yellow-ribbon/actions/index.unit.spec.js
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/components/SearchResult/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.unit.spec.jsx
  src/applications/yellow-ribbon/reducers/index.js
  src/applications/yellow-ribbon/reducers/index.unit.spec.js
Labels: VSA, front end

#12076 Alphabetize states list
  src/platform/static-data/STATES.json
Labels: VSA, front end

#12012 Update footer link and label
  src/platform/static-data/footer-links.json
  src/site/assets/robots.txt
Labels: VSA, front end

#12063 526: Handle rated disabilities in treatment facilities properly
  src/applications/disability-benefits/all-claims/submit-transformer.js
  src/applications/disability-benefits/all-claims/tests/data/transformed-data/secondary-new-test.json
Labels: Disability Benefits, VSA, bug, front end

#12077 Revert "Update footer link and label"
  src/platform/static-data/footer-links.json
  src/site/assets/robots.txt
Labels: VSA, front end

#12078 [Tech debt] Fix axe error
  src/platform/forms-system/src/js/components/FieldTemplate.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, front end, unicorns

#12086 [Development] Fix propTypes setting
  src/platform/forms-system/src/js/components/AddressViewField.jsx
Labels: Disability Benefits, VSA, bug, front end

#12069 add two more visn23 facilities
  src/applications/personalization/dashboard/covid-19.jsx
Labels: VSA

#12072 [Tech debt] Remove unused code in 526
  src/applications/disability-benefits/all-claims/tests/config/submitForm.unit.spec.js
Labels: Disability Benefits, VSA, front end

#12067 [Development] More HLR fixes & updates
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/components/MaskedNumber.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/containers/SelectArrayItemsWidget.jsx
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/pages/contactInformation.js
  src/applications/disability-benefits/996/pages/veteranInformation.js
  src/applications/disability-benefits/996/tests/components/contactInfo.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/veteranInformation.unit.spec.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#12083 7252 686 additional evidence
  src/applications/disability-benefits/686c-674/components/AdditionalEvidence.jsx
  src/applications/disability-benefits/686c-674/config/chapters/add-a-child/add-child-additional-evidence/addChildAdditionalEvidence.js
  src/applications/disability-benefits/686c-674/config/chapters/add-a-child/child-place-of-birth/child-place-of-birth.js
  src/applications/disability-benefits/686c-674/config/chapters/add-a-child/child-place-of-birth/childStatusDescription.jsx
  src/applications/disability-benefits/686c-674/config/chapters/add-a-child/index.js
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/add-spouse-additional-evidence/spouseAdditionalEvidence.js
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/current-marriage-information/currentMarriageInformation.js
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/current-marriage-information/helpers.jsx
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/index.js
  src/applications/disability-benefits/686c-674/config/constants.js
  src/applications/disability-benefits/686c-674/config/form.js
  src/applications/disability-benefits/686c-674/config/generic-schema.js
  src/applications/disability-benefits/686c-674/tests/config/addChildSupportingEvidence.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/addSpouseAdditionalEvidence.unit.spec.jsx
Labels: VSA

#12053 1010CG Redesign
  src/applications/caregivers/components/AdditionalInfo/formInfo.jsx
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/components/NeedHelpFooter/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/config/form.js
  src/applications/caregivers/containers/IntroductionPage.jsx
  src/applications/caregivers/definitions/caregiverUI.js
  src/applications/caregivers/definitions/constants.js
  src/applications/caregivers/sass/caregivers.scss
  src/applications/caregivers/sass/introductionPage.scss
  src/applications/caregivers/sass/needHelpFooter.scss
  src/applications/caregivers/sass/preSubmitCheckboxes.scss
Labels: design, front end

#12096 VACMS-1296: Refactorting graphql for listing pages.
  src/site/components/events_list.drupal.liquid
  src/site/layouts/event_listing.drupal.liquid
  src/site/stages/build/drupal/graphql/eventListingPage.graphql.js
  src/site/stages/build/drupal/graphql/pressReleasesListingPage.graphql.js
  src/site/stages/build/drupal/graphql/storyListingPage.graphql.js
  src/site/stages/build/drupal/metalsmith-drupal.js
Labels: needs peer approval

#12099 Update school_name_in_yr_database to `name`
  src/applications/yellow-ribbon/api/index.js
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/components/SearchResult/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
Labels: VSA, front end

#12103 Update content
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.unit.spec.jsx
  src/applications/yellow-ribbon/reducers/index.js
  src/applications/yellow-ribbon/reducers/index.unit.spec.js
Labels: VSA, front end

#12106 CT: Search results breadcrumb missing #7528
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
Labels: BAH, BAH-QA-needed

#12114 Kelsonic 7464 update yr search results
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/components/SearchResult/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
Labels: VSA, front end

#12117 Update view historical rates links
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
Labels: VSA, content, front end

#12108 Refine profile info save experience
  src/applications/personalization/profile360/tests/e2e/profile-360.e2e.spec.js
  src/applications/personalization/profile360/tests/e2e/routes.json
  src/platform/user/profile/vet360/components/base/Vet360EditModal.jsx
  src/platform/user/profile/vet360/components/base/Vet360Transaction.jsx
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/containers/Vet360ProfileField.jsx
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/components/EditModal.unit.spec.jsx
  src/platform/user/profile/vet360/tests/components/Vet360EditModal.unit.spec.jsx
  src/platform/user/profile/vet360/tests/components/Vet360EditModalActionButtons.unit.spec.jsx
  src/platform/user/profile/vet360/tests/components/Vet360Transaction.unit.spec.jsx
  src/platform/user/profile/vet360/tests/components/Vet360TransactionPending.unit.spec.jsx
  src/platform/user/profile/vet360/tests/containers/Vet360ProfileField.unit.spec.jsx
  src/platform/user/profile/vet360/tests/containers/Vet360TransactionReporter.unit.spec.jsx
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA

#12123 Remove orphaned payment info action/reducer
  src/applications/personalization/profile360/actions/paymentInformation.js
  src/applications/personalization/profile360/components/PaymentInformationEditModal.jsx
  src/applications/personalization/profile360/containers/PaymentInformation.jsx
  src/applications/personalization/profile360/reducers/index.js
  src/applications/personalization/profile360/tests/components/PaymentInformationEditModal.unit.spec.jsx
  src/applications/personalization/profile360/tests/containers/PaymentInformation.unit.spec.jsx
  src/applications/personalization/profile360/tests/reducers/index.unit.spec.js
Labels: VSA

#12125 remove profile-2 from prod
  src/applications/personalization/profile-2/manifest.json
Labels: VSA

#12124 Letters: UI corrections/updates for no address
  src/applications/letters/components/NoAddressBanner.jsx
  src/applications/letters/containers/AddressSection.jsx
Labels: Disability Benefits, VSA, front end, va-letters

#12126 7262 update remaining 686 addresses
  src/applications/disability-benefits/686c-674/config/chapters/674/student-last-term-information/studentLastTerm.js
  src/applications/disability-benefits/686c-674/config/chapters/674/student-term-dates/studentTermDates.js
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/does-live-with-spouse/doesLiveWithSpouse.js
  src/applications/disability-benefits/686c-674/config/chapters/stepchild-no-longer-part-of-household/stepchild-information/stepchild-information.js
  src/applications/disability-benefits/686c-674/config/chapters/veteran-information/veteran-address/veteran-address.js
  src/applications/disability-benefits/686c-674/tests/config/doesLiveWithSpouse.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/stepchildInformation.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/veteranInformation.unit.spec.jsx
Labels: VSA

#12127 Very basic front-loading of profile data
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/tests/components/ProfileWrapper.unit.spec.js
Labels: VSA

#12132 Kelsonic 7106 yr mobile
  src/applications/yellow-ribbon/actions/index.js
  src/applications/yellow-ribbon/components/ComparisonBanner/index.jsx
  src/applications/yellow-ribbon/components/ComparisonBanner/index.unit.spec.jsx
  src/applications/yellow-ribbon/components/FindYellowRibbonPage/index.js
  src/applications/yellow-ribbon/components/FindYellowRibbonPage/index.unit.spec.jsx
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/components/SearchResultsPage/index.js
  src/applications/yellow-ribbon/components/SearchResultsPage/index.unit.spec.jsx
  src/applications/yellow-ribbon/constants/index.js
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.unit.spec.jsx
  src/applications/yellow-ribbon/reducers/index.js
  src/applications/yellow-ribbon/reducers/index.unit.spec.js
Labels: VSA, front end

#12134 bradl3yC - gate cerner widget to staging
  src/applications/personalization/dashboard/components/ManageYourVAHealthCare.jsx
Labels: VSA

#12136 7689-hide-unauthed-start-link
  src/applications/disability-benefits/686c-674/containers/IntroductionPage.jsx
Labels: VSA

#12107 Caution flag filter front end changes
  src/applications/gi/components/search/CautionaryWarningsFilter.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/constants.js
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/reducers/filter.js
  src/applications/gi/tests/components/InstitutionFilterForm.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12110 Accessibility Check
  src/applications/caregivers/components/AdditionalInfo/formInfo.jsx
  src/applications/caregivers/config/form.js
  src/applications/caregivers/containers/IntroductionPage.jsx
  src/applications/caregivers/definitions/caregiverUI.js
Labels: 508/Accessibility, front end

#12128 Institution profile school locations list "view less" scroll fix
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/components/profile/SchoolLocations.jsx
  src/applications/gi/tests/components/SchoolLocations.unit.spec.jsx
Labels: BAH

#12119 Search results caution flag updates
  src/applications/gi/components/profile/CautionFlagDetails.jsx
  src/applications/gi/components/profile/CautionFlagHeading.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/tests/components/CautionFlagDetails.unit.spec.jsx
  src/applications/gi/tests/components/CautionFlagHeading.unit.spec.jsx
  src/applications/gi/tests/components/VetTecProgramSearchResult.unit.spec.jsx
  src/applications/gi/tests/utils/render.unit.spec.js
  src/applications/gi/utils/render.jsx
Labels: BAH, BAH-QA-needed

#12102 Create STEM Scholarship Application Infrastructure
  src/applications/edu-benefits/10203/Form10203App.jsx
  src/applications/edu-benefits/10203/analytics-functions.js
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/config/form.js
  src/applications/edu-benefits/10203/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/10203/containers/StemEligibilityView.jsx
  src/applications/edu-benefits/10203/content/activeDuty.jsx
  src/applications/edu-benefits/10203/content/stem.jsx
  src/applications/edu-benefits/10203/edu-benefits-entry.jsx
  src/applications/edu-benefits/10203/helpers.jsx
  src/applications/edu-benefits/10203/manifest.json
  src/applications/edu-benefits/10203/pages/activeDuty.js
  src/applications/edu-benefits/10203/pages/benefitSelection.js
  src/applications/edu-benefits/10203/pages/index.js
  src/applications/edu-benefits/10203/pages/stem.js
  src/applications/edu-benefits/10203/pages/stemEligibility.js
  src/applications/edu-benefits/10203/prefill-transformer.js
  src/applications/edu-benefits/10203/reducer.js
  src/applications/edu-benefits/10203/routes.jsx
  src/applications/edu-benefits/10203/submit-transformer.js
  src/applications/edu-benefits/10203/submitForm.js
  src/applications/edu-benefits/components/EducationWizard.jsx
  src/applications/edu-benefits/selectors/educationWizard.js
  src/applications/edu-benefits/tests/components/EducationWizard.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12144 Front-load all data for the new Profile
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/tests/components/ProfileWrapper.unit.spec.js
Labels: VSA

#12156 GIBCT: VETTEC Logo and Additional Resources sections not displaying correctly on medium and small screens
  src/applications/gi/components/content/AdditionalResources.jsx
  src/applications/gi/components/vet-tec/VetTecAdditionalResources.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH, BAH-QA-needed

#12157 VET TEC caution flag fix
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
Labels: BAH

#12159 load payment info when props update
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/tests/components/ProfileWrapper.unit.spec.js
Labels: VSA

#12141 Kelsonic 7642 a11y find yr results
  src/applications/yellow-ribbon/actions/index.js
  src/applications/yellow-ribbon/actions/index.unit.spec.js
  src/applications/yellow-ribbon/components/FindYellowRibbonPage/index.js
  src/applications/yellow-ribbon/components/FindYellowRibbonPage/index.unit.spec.jsx
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/components/SearchResultsPage/index.js
  src/applications/yellow-ribbon/components/SearchResultsPage/index.unit.spec.jsx
  src/applications/yellow-ribbon/constants/index.js
  src/applications/yellow-ribbon/constants/index.unit.spec.js
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.unit.spec.jsx
  src/applications/yellow-ribbon/reducers/index.js
  src/applications/yellow-ribbon/sass/yellow-ribbon.scss
Labels: 508/Accessibility, VSA, front end

#12151 fix sass-lint errors
  src/applications/caregivers/sass/caregivers.scss
  src/applications/caregivers/sass/needHelpFooter.scss
  src/applications/disability-benefits/2346/sass/form-2346.scss
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/gi/sass/partials/_gi-search-page.scss
  src/applications/static-pages/sass/modules/_m-education-wizard.scss
  src/applications/vaos/sass/vaos.scss
  src/platform/site-wide/sass/modules/_m-side-nav.scss
Labels: VSA

#12143 update json-schema commit hash
  package.json
  src/platform/forms/constants.js
  src/platform/forms/tests/forms.unit.spec.js
  yarn.lock
Labels: BAH, BAH-IR-needed

#12148 Modularize links
  src/applications/caregivers/components/AdditionalInfo/formInfo.jsx
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/components/NeedHelpFooter/index.jsx
  src/applications/caregivers/config/form.js
  src/applications/caregivers/containers/IntroductionPage.jsx
  src/applications/caregivers/definitions/caregiverUI.js
  src/applications/caregivers/definitions/content.js
Labels: content, front end

#12171 Fix: Caution Flags not showing on search results in production
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/utils/render.jsx
Labels: BAH

#12155 Update the content in the subway map on the form's introduction page
  src/applications/disability-benefits/2346/components/IntroductionPage.jsx
  src/applications/disability-benefits/2346/config/form.js
Labels: needs peer approval

#12160 Remove vaProfileAddressValidation feature flag from FE
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/containers/Vet360ProfileField.jsx
  src/platform/user/profile/vet360/selectors.js
  src/platform/user/profile/vet360/tests/containers/Vet360ProfileField.unit.spec.jsx
  src/platform/user/profile/vet360/tests/selectors.unit.spec.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA

#12169 Change Profile route based on feature flag
  src/applications/personalization/profile-2/selectors.js
  src/platform/site-wide/user-nav/components/PersonalizationDropdown.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA

#12184 Kelsonic 7807 yr a11y tweaks
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
Labels: VSA, front end

#12182 Add link for fiduciary claim
  src/applications/disability-benefits/wizard/pages/decision-review.jsx
Labels: VSA, front end

#11999 MDOT Form 2346 Address Page
  src/applications/disability-benefits/2346/actions/index.js
  src/applications/disability-benefits/2346/components/OrderAccessoriesPageContent.jsx
  src/applications/disability-benefits/2346/components/OrderSupplyPageContent.jsx
  src/applications/disability-benefits/2346/components/PersonalInfoBox.jsx
  src/applications/disability-benefits/2346/components/SelectArrayItemsAccessoriesWidget.jsx
  src/applications/disability-benefits/2346/components/SelectArrayItemsBatteriesWidget.jsx
  src/applications/disability-benefits/2346/components/addressFields/addressCardField.jsx
  src/applications/disability-benefits/2346/components/addressFields/addressViewField.jsx
  src/applications/disability-benefits/2346/components/orderAccessoriesPageContent.jsx
  src/applications/disability-benefits/2346/components/orderSupplyPageContent.jsx
  src/applications/disability-benefits/2346/components/personalInfoBox.jsx
  src/applications/disability-benefits/2346/config/form.js
  src/applications/disability-benefits/2346/constants/index.js
  src/applications/disability-benefits/2346/containers/App.jsx
  src/applications/disability-benefits/2346/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/2346/definitions/2346UI.js
  src/applications/disability-benefits/2346/helpers/index.js
  src/applications/disability-benefits/2346/manifest.json
  src/applications/disability-benefits/2346/reducers/form2346Reducer.js
  src/applications/disability-benefits/2346/sass/form-2346.scss
  src/applications/disability-benefits/2346/schemas/2346-schema.json
  src/applications/disability-benefits/2346/schemas/address-schema.js
  src/applications/disability-benefits/2346/schemas/definitions/2346UI.js
Labels: VSA, front end, needs peer approval, vsa-benefits-2

#12179 Create reusable ProfileInfoTable
  src/applications/personalization/profile-2/components/MilitaryInformation.jsx
  src/applications/personalization/profile-2/components/ProfileHeader.jsx
  src/applications/personalization/profile-2/components/ProfileInfoTable.jsx
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/constants.js
  src/applications/personalization/profile-2/helpers.js
  src/applications/personalization/profile-2/sass/profile-2.scss
  src/applications/personalization/profile-2/sass/profile-info-table.scss
  src/applications/personalization/profile-2/tests/components/ProfileHeader.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/ProfileInfoTable.unit.spec.js
  src/applications/personalization/profile-2/tests/helpers.unit.spec.js
Labels: VSA

#12153 changed primary green button to accurate copy
  src/applications/disability-benefits/2346/components/IntroductionPage.jsx
Labels: needs peer approval

#12152 put need help footer on all form 2346 pages
  src/applications/disability-benefits/2346/components/FooterInfo.jsx
  src/applications/disability-benefits/2346/components/IntroductionPage.jsx
  src/applications/disability-benefits/2346/config/form.js
Labels: needs peer approval

#12193 686-fix-property-name
  src/applications/disability-benefits/686c-674/config/chapters/report-child-stopped-attending-school/child-information/childInformation.js
  src/applications/disability-benefits/686c-674/config/constants.js
  src/applications/disability-benefits/686c-674/config/form.js
Labels: VSA, front end

#12164 Caution flag updates
  src/applications/gi/components/profile/CautionFlagDetails.jsx
  src/applications/gi/components/profile/CautionFlagHeading.jsx
  src/applications/gi/components/profile/SchoolClosingDetails.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/tests/utils/render.unit.spec.js
  src/applications/gi/utils/render.jsx
Labels: BAH

#12189 [ACCESSIBILITY/CI/CD] Update letters e2e tests
  src/applications/letters/tests/01-authed.e2e.spec.js
Labels: 508/Accessibility, Disability Benefits, VSA, front end, testing, unicorns, va-letters

#12199 bradl3yC - 7126 - update form intro page (unauth) messaging
  src/applications/disability-benefits/2346/components/IntroductionPage.jsx
  src/applications/disability-benefits/2346/components/UnverifiedPrefillAlert.jsx
  src/applications/disability-benefits/2346/config/form.js
Labels: vsa-benefits-2

#12198 Make the ProfileInfoTable responsive
  src/applications/personalization/profile-2/components/ProfileInfoTable.jsx
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/sass/profile-info-table.scss
  src/applications/personalization/profile-2/tests/components/ProfileInfoTable.unit.spec.js
Labels: VSA

#12168 Added estimate your benefits sec103 feature flag
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12204 Remove `editModalForm` from Redux
  src/applications/personalization/profile360/reducers/index.js
Labels: VSA

#12200 CF: AXE Error on profile page: Heading levels should only increase by one #7870
  src/applications/gi/components/AlertBox.jsx
  src/applications/gi/components/content/AdditionalResources.jsx
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/components/profile/CautionFlagDetails.jsx
  src/applications/gi/components/profile/CautionFlagHeading.jsx
  src/applications/gi/components/profile/CautionaryInformation.jsx
  src/applications/gi/components/profile/ContactInformation.jsx
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/profile/SchoolClosingDetails.jsx
  src/applications/gi/components/profile/SchoolClosingHeading.jsx
  src/applications/gi/utils/render.jsx
Labels: BAH, BAH-QA-needed

#12196 CT - School location list text
  src/applications/gi/components/profile/SchoolLocations.jsx
Labels: BAH

#12214 bradl3yC - 7158 - Personal Info box styles
  src/applications/disability-benefits/2346/components/PersonalInfoBox.jsx
Labels: vsa-benefits-2

#12178 [Tech debt] Consolidate addresses
  src/applications/disability-benefits/all-claims/config/schema.js
  src/applications/disability-benefits/all-claims/constants.js
  src/applications/veteran-representative/labels.js
  src/applications/vic-v2/components/VeteranIDCard.jsx
  src/applications/vic-v2/definitions/address.js
  src/applications/vic-v2/labels.js
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/platform/forms-system/src/js/definitions/address.js
  src/platform/forms-system/src/js/utilities/address/index.js
  src/platform/forms/address/data/index.js
  src/platform/forms/address/data/labels.js
  src/platform/forms/address/data/military-cities.json
  src/platform/forms/address/data/military-states.json
  src/platform/forms/address/data/states.json
  src/platform/forms/address/index.js
  src/platform/static-data/STATES.json
  src/platform/user/profile/vet360/constants/index.js
  src/platform/user/profile/vet360/constants/states.json
Labels: Disability Benefits, VSA, debt, front end, unicorns

#12202 CT - Caution flag details focus
  src/applications/gi/components/profile/CautionaryInformation.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/containers/ProfilePage.jsx
Labels: BAH

#12215 update vets-json-schema version
  package.json
  src/platform/forms/constants.js
  yarn.lock
Labels: BAH, BAH-IR-needed

#12219 bradl3yC - Correct imports from forms system
  src/applications/disability-benefits/2346/constants/index.js
  src/applications/disability-benefits/2346/schemas/address-schema.js
Labels: vsa-benefits-2

#12213 Use ISO3 country codes for profile addresses
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/components/AddressField/AddressEditModal.jsx
  src/platform/user/profile/vet360/components/AddressField/AddressField.jsx
  src/platform/user/profile/vet360/components/AddressField/address-schemas.js
  src/platform/user/profile/vet360/constants/index.js
  src/platform/user/profile/vet360/containers/CopyMailingAddress.jsx
  src/platform/user/profile/vet360/tests/containers/CopyMailingAddress.unit.spec.jsx
  src/platform/user/profile/vet360/tests/util/transactions.unit.spec.js
  src/platform/user/profile/vet360/util/transactions.js
Labels: VSA

#12210 Add correlation between map pin and cards in search results
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/components/markers/FacilityMarker.jsx
  src/applications/facility-locator/components/search-results/LocationInfoBlock.jsx
  src/applications/facility-locator/constants/index.js
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/sass/facility-locator.scss
Labels: VSA, facility locator, front end

#12223 adjust CSS of military history section
  src/applications/personalization/profile-2/components/MilitaryInformation.jsx
  src/applications/personalization/profile-2/components/ProfileHeader.jsx
  src/applications/personalization/profile-2/components/ProfileInfoTable.jsx
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/helpers.js
  src/applications/personalization/profile-2/sass/profile-2.scss
  src/applications/personalization/profile-2/tests/components/ProfileInfoTable.unit.spec.js
  src/applications/personalization/profile-2/tests/helpers.unit.spec.js
Labels: VSA

#12203 EYB: Create Feature Flag Toggle for Estimate Your Benefits Effort #7780
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#12217 [COGNITION]: GIBCT - Caution flag headings SHOULD be nested properly #7983
  src/applications/gi/components/profile/CautionFlagDetails.jsx
Labels: BAH

#12222 Kelsonic 7979 yr css tweaks
  src/applications/yellow-ribbon/components/FindYellowRibbonPage/index.js
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/components/SearchResultsPage/index.js
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
Labels: VSA, design, front end

#12218 Kelsonic 7791 checkbox yr
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
Labels: VSA, content, front end

#12221 [COGNITION]: GIBCT - caution flags SHOULD NOT announce themselves dynamically to screen readers #7982
  src/applications/gi/components/AlertBox.jsx
Labels: BAH

#12230 [COGNITION]: GIBCT - Single search result SHOULD read "1 result" instead of "1 results" #7991
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/utils/render.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12235 Add support for title-less ProfileInfoTable
  src/applications/personalization/profile-2/components/ProfileInfoTable.jsx
  src/applications/personalization/profile-2/sass/profile-info-table.scss
  src/applications/personalization/profile-2/tests/components/ProfileInfoTable.unit.spec.js
Labels: VSA

#12228 ProfileWrapper loads MHV data on mount
  src/applications/personalization/profile-2/components/MilitaryInformation.jsx
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/tests/components/ProfileWrapper.unit.spec.js
Labels: VSA

#12225 6049 686 e2e spouse and child
  src/applications/disability-benefits/686c-674/config/form.js
  src/applications/disability-benefits/686c-674/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/686c-674/tests/e2e/00-spouse-child-all-fields.e2e.spec.js
  src/applications/disability-benefits/686c-674/tests/e2e/686-test-data.json
  src/applications/disability-benefits/686c-674/tests/e2e/test-helpers.js
Labels: VSA

#12226 update vets-json-schema to latest version
  package.json
  yarn.lock
Labels: BAH

#12233 [COGNITION]: GIBCT - Caution flags' bulleted lists SHOULD have valid HTML for screen reader usability #7987
  src/applications/gi/components/profile/CautionFlagHeading.jsx
Labels: BAH

#12243 Facility Locator does not load in IE11
  src/applications/facility-locator/constants/index.js
Labels: VSA, facility locator, front end

#12237 Bah vettecpage css
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#12244 Addition of general "call first" language to top of Facility Locator …
  src/applications/facility-locator/containers/VAMap.jsx
Labels: VSA, facility locator, front end

#12248 Profile 2.0 tweaks
  src/applications/personalization/profile-2/components/MilitaryInformation.jsx
  src/applications/personalization/profile-2/components/ProfileInfoTable.jsx
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/sass/profile-info-table.scss
Labels: VSA

#12227 5569 BDD Initial Skeleton
  src/applications/disability-benefits/bdd/BDDApp.jsx
  src/applications/disability-benefits/bdd/components/IntroductionPage.jsx
  src/applications/disability-benefits/bdd/config/form.js
  src/applications/disability-benefits/bdd/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/bdd/form-entry.jsx
  src/applications/disability-benefits/bdd/manifest.json
  src/applications/disability-benefits/bdd/reducers/index.js
  src/applications/disability-benefits/bdd/routes.jsx
  src/applications/disability-benefits/bdd/tests/00.bdd.e2e.spec.js
Labels: BDD, Disability Benefits, VSA, front end

#12251 8018 686 update url
  src/applications/disability-benefits/686c-674/config/form.js
  src/applications/disability-benefits/686c-674/manifest.json
  src/applications/disability-benefits/686c-674/tests/e2e/00-spouse-child-all-fields.e2e.spec.js
Labels: VSA

#12260 Update CODEOWNERS for form 10203
  .github/CODEOWNERS
Labels: BAH

#12261 Disable 10203 in production
  src/applications/edu-benefits/10203/manifest.json
Labels: BAH

#12263 Disable 10203 in production attempt #2
  src/applications/edu-benefits/10203/manifest.json
Labels: BAH

#12265 cap street address lines to 35 char
  src/platform/user/profile/vet360/components/AddressField/address-schemas.js
Labels: VSA

#12253 Add e2e tests for YR tool
  src/applications/find-forms/tests/00-required.e2e.spec.js
  src/applications/yellow-ribbon/00-required.e2e.spec.js
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/constants/stub.json
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
Labels: VSA, front end, testing

#12257 Update downtime timestamps
  src/platform/site-wide/announcements/components/Downtime.jsx
  src/platform/site-wide/announcements/components/PreDowntime.jsx
  src/platform/site-wide/announcements/components/PrePreDowntime.jsx
  src/platform/site-wide/announcements/config/index.js
Labels: VSA, front end

#12234 Institution Section 103 Data
  src/applications/gi/components/profile/AdditionalInformation.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH, BAH-QA-needed

#12262 add AccountSecurity component
  src/applications/personalization/profile-2/components/AccountSecurity.jsx
  src/applications/personalization/profile-2/components/AccountSecurityContent.jsx
  src/applications/personalization/profile-2/components/IdentityVerificationStatus.jsx
  src/applications/personalization/profile-2/components/MHVTermsAndConditionsStatus.jsx
  src/applications/personalization/profile-2/components/TwoFactorAuthorizationStatus.jsx
  src/applications/personalization/profile-2/components/Verified.jsx
  src/applications/personalization/profile-2/tests/components/AccountSecurity.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/AccountSecurityContent.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/IdentityVerificationStatus.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/MHVTermsAndConditionsStatus.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/TwoFactorAuthorizationStatus.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/Verified.unit.spec.jsx
Labels: VSA

#12120 7272 Remove STEM Scholarship question from 22-1995 workflow and submission
  src/applications/edu-benefits/1995/config/chapters.js
  src/applications/edu-benefits/1995/helpers.jsx
  src/applications/edu-benefits/components/EducationWizard.jsx
  src/applications/edu-benefits/tests/1995/schema/transformedData.js
Labels: BAH

#12239 fl send community care requests through ccp controller
  src/applications/facility-locator/config.js
  src/applications/facility-locator/tests/api-url-parameters.unit.spec.js
Labels: VSA, facility locator, front end

#12270 add analytics to covid-19 banner
  src/applications/personalization/dashboard/covid-19.jsx
Labels: VSA

#12288 Vettec log adjustment
  src/applications/gi/components/search/LandingPageTypeOfInstitutionFilter.jsx
  src/applications/gi/components/vet-tec/VetTecAdditionalResources.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/sass/partials/_gi-vet-tec.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12280 Institution Profile - cautionary info analytics
  src/applications/gi/components/profile/CautionFlagDetails.jsx
  src/applications/gi/components/profile/CautionFlagHeading.jsx
  src/applications/gi/components/profile/CautionaryInformation.jsx
  src/applications/gi/components/profile/SchoolClosingDetails.jsx
  src/applications/gi/tests/components/CautionFlagDetails.unit.spec.jsx
  src/applications/gi/tests/components/CautionFlagHeading.unit.spec.jsx
  src/applications/gi/tests/components/SchoolClosingDetails.unit.spec.jsx
Labels: BAH

#12281 Kelsonic 7474 download pdf forms tweak ie
  package.json
  src/applications/find-forms/components/SearchResult.jsx
  yarn.lock
Labels: VSA, front end

#12267 BDD: Update claim wizard gating to support navigation to the BDD form
  src/applications/disability-benefits/bdd/constants.js
  src/applications/disability-benefits/wizard/pages/bdd.jsx
  src/applications/disability-benefits/wizard/pages/file-bdd.jsx
  src/applications/disability-benefits/wizard/pages/index.js
  src/applications/disability-benefits/wizard/pages/pageList.js
  src/applications/disability-benefits/wizard/pages/unable-to-file-bdd.jsx
Labels: BDD, Disability Benefits, VSA, front end

#12284 BDD: Introduction page and form.js updates
  src/applications/disability-benefits/bdd/components/IntroductionPage.jsx
  src/applications/disability-benefits/bdd/config/form.js
Labels: BDD, Disability Benefits, VSA, front end

#12180 7753: Remove unnecessary 22-1995 artifacts
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/10203/helpers.jsx
  src/applications/edu-benefits/10203/pages/benefitSelection.js
  src/applications/edu-benefits/10203/submit-transformer.js
Labels: BAH, BAH-QA-needed

#12296 fixed failed Axe test
  src/applications/gi/components/AccordionItem.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12166 Add operating status indicators to search results and facility detail pages
  src/applications/facility-locator/components/search-results/LocationInfoBlock.jsx
  src/applications/facility-locator/constants/index.js
  src/applications/facility-locator/constants/mock-facility-data.json
  src/applications/facility-locator/containers/FacilityDetail.jsx
  src/applications/facility-locator/sass/facility-locator.scss
Labels: VSA, facility locator, front end

#12303 Fix for GIBCT Learn more modals scroll down the page, change focus, when I press TAB
  src/applications/gi/components/Modal.jsx
  src/applications/gi/containers/Modals.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12300 Add comma to address formatter
  src/platform/forms/address/helpers.js
  src/platform/forms/tests/address.unit.spec.js
Labels: VSA, front end

#12308 [Development] Form 526 fixes
  src/applications/disability-benefits/all-claims/containers/ITFWrapper.jsx
  src/applications/disability-benefits/all-claims/content/separationTrainingPay.jsx
  src/platform/forms-system/src/js/helpers.js
  src/platform/forms-system/test/js/helpers.unit.spec.js
  src/platform/forms/tests/validations.unit.spec.js
  src/platform/forms/validations.js
Labels: Disability Benefits, VSA, bug, front end, unicorns

#12314 Remove contact modal from profile
  src/platform/site-wide/announcements/components/Profile360Intro.jsx
  src/platform/site-wide/announcements/config/index.js
Labels: VSA, front end

#12317 Remove personalization announcement
  src/platform/site-wide/announcements/components/PersonalizationBanner.jsx
  src/platform/site-wide/announcements/config/index.js
Labels: VSA, front end

#12326 safer handling of PPIU error responses
  src/applications/personalization/profile360/tests/util/index.unit.spec.js
  src/applications/personalization/profile360/util/index.js
Labels: VSA

#12312 BDD: Step 1 (Service Member)
  src/applications/disability-benefits/bdd/BDDApp.jsx
  src/applications/disability-benefits/bdd/components/IntroductionPage.jsx
  src/applications/disability-benefits/bdd/config/form.js
  src/applications/disability-benefits/bdd/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/bdd/form-entry.jsx
  src/applications/disability-benefits/bdd/reducers/index.js
  src/applications/disability-benefits/bdd/routes.jsx
  src/applications/disability-benefits/bdd/tests/00.bdd.e2e.spec.js
Labels: BDD, Disability Benefits, VSA, front end

#12340 add temporary direct deposit alert
  src/applications/personalization/profile360/containers/PaymentInformation.jsx
Labels: VSA

#12295 bradl3yC -Connect ReviewCardField
  src/applications/disability-benefits/2346/components/ReviewCardField.jsx
  src/applications/disability-benefits/2346/config/form.js
  src/applications/disability-benefits/2346/constants/index.js
  src/applications/disability-benefits/2346/sass/form-2346.scss
  src/applications/disability-benefits/2346/schemas/2346-schema.json
  src/applications/disability-benefits/2346/schemas/address-schema.js
  src/applications/disability-benefits/2346/schemas/definitions/2346UI.js
Labels: vsa-benefits-2

#12345 stop routing to profile-2
  src/platform/site-wide/user-nav/components/PersonalizationDropdown.jsx
Labels: VSA

#12348 Add character limit to street address field
  src/platform/user/profile/vet360/components/AddressField/address-schemas.js
Labels: VSA, front end

#12333 Rough version of proper side nav
  src/applications/personalization/profile-2/components/AccountSecurity.jsx
  src/applications/personalization/profile-2/components/ConnectedApplications.jsx
  src/applications/personalization/profile-2/components/DirectDeposit.jsx
  src/applications/personalization/profile-2/components/PersonalInformation.jsx
  src/applications/personalization/profile-2/components/ProfileHeader.jsx
  src/applications/personalization/profile-2/components/ProfileInfoTable.jsx
  src/applications/personalization/profile-2/components/ProfileSideNav.jsx
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/sass/profile-2.scss
  src/applications/personalization/profile-2/sass/profile-sidenav.scss
Labels: VSA

#12351 [Development] Remove `ratingDecisionId` from 526 submit
  src/applications/disability-benefits/all-claims/config/schema.js
  src/applications/disability-benefits/all-claims/submit-transformer.js
  src/applications/disability-benefits/all-claims/tests/data/transformed-data/full-781-781a-8940-test.json
  src/applications/disability-benefits/all-claims/tests/data/transformed-data/maximal-test.json
  src/applications/disability-benefits/all-claims/tests/data/transformed-data/minimal-test.json
  src/applications/disability-benefits/all-claims/tests/data/transformed-data/secondary-new-test.json
  src/applications/disability-benefits/all-claims/tests/data/transformed-data/upload-781-781a-8940-test.json
Labels: Disability Benefits, VSA, front end, unicorns

#12349 [Development/Discovery] Add 526 v1 comments
  src/applications/disability-benefits/all-claims/prefill-transformer.js
Labels: Disability Benefits, VSA, discovery, front end, unicorns

#11978 7117: Prod flag removal for 6803
  src/applications/gi/components/CheckboxGroup.jsx
  src/applications/gi/components/RadioButtons.jsx
  src/applications/gi/components/profile/CautionaryInformation.jsx
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/sass/gi.scss
  src/applications/gi/sass/partials/_gi-search-page.scss
  src/applications/gi/utils/render.jsx
Labels: BAH

#12356 Prod flag removal for story 7533
  src/applications/gi/components/search/LandingPageTypeOfInstitutionFilter.jsx
  src/applications/gi/components/vet-tec/VetTecAdditionalResources.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12363 [Development] Change review card cancel button style
  src/platform/forms-system/src/js/components/ReviewCardField.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, unicorns

#12369 CF: Production duplicates of caution flag #8413
  src/applications/gi/components/profile/CautionFlagDetails.jsx
  src/applications/gi/components/profile/CautionFlagHeading.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/tests/utils/render.unit.spec.js
  src/applications/gi/utils/render.jsx
Labels: BAH, BAH-QA-needed

#12372 CT-EYB: Put duplicate components behind feature flag
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/containers/EstimateYourBenefits.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/containers/VetTecEstimateYourBenefits.jsx
Labels: BAH, BAH-IR-needed

#12355 Fix error scrolling on profile submission
  src/platform/user/profile/vet360/components/base/Vet360EditModalErrorMessage.jsx
  yarn.lock
Labels: VSA, front end

#12361 BDD Step 2: Military History
  src/applications/disability-benefits/bdd/config/form.js
  src/applications/disability-benefits/wizard/pages/file-bdd.jsx
Labels: BDD, Disability Benefits, VSA, front end

#12310 1010CG Design Update
  package.json
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/components/NeedHelpFooter/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/config/form.js
  src/applications/caregivers/containers/IntroductionPage.jsx
  src/applications/caregivers/definitions/caregiverUI.js
  src/applications/caregivers/definitions/constants.js
  src/applications/caregivers/definitions/content.js
  src/applications/caregivers/sass/caregivers.scss
  src/applications/caregivers/sass/infoModal.scss
  yarn.lock
Labels: Please Review, design, front end

#12393 Kelsonic 8412 yr school website link
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
Labels: VSA, front end

#12396 Revert "add temporary direct deposit alert (#12340)"
  src/applications/personalization/profile360/containers/PaymentInformation.jsx
Labels: VSA

#12332 [Development] Add original claim feature flipper
  src/applications/disability-benefits/all-claims/components/IntroductionPage.jsx
  src/applications/disability-benefits/all-claims/config/selectors.js
  src/applications/disability-benefits/all-claims/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/wizard/pages/bdd.jsx
  src/applications/disability-benefits/wizard/pages/file-original-claim.jsx
  src/platform/user/selectors.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: Disability Benefits, VSA, front end, unicorns

#12401 Comparison tool calculation updates
  src/applications/gi/actions/index.js
  src/applications/gi/components/profile/EybCalculatorForm.jsx
  src/applications/gi/components/profile/EybEligibilityForm.jsx
  src/applications/gi/containers/EstimateYourBenefits.jsx
  src/applications/gi/reducers/calculator.js
  src/applications/gi/tests/00-required.e2e.spec.js
Labels: BAH

#12383 Left Navigation VAMC Design Updates
  src/platform/site-wide/sass/modules/_m-side-nav.scss
  src/platform/site-wide/side-nav/components/LabelText.js
  src/platform/site-wide/side-nav/components/NavItem.js
  src/platform/site-wide/side-nav/components/NavItemRow.js
  src/platform/site-wide/side-nav/tests/components/NavItem.unit.spec.js
  src/platform/site-wide/side-nav/tests/components/NavItemRow.unit.spec.js
Labels: VSA, front end

#12381 CT-EYB: Group Estimate Your Benefits Section Questions to reduce vertical spacing. #8404
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/components/profile/BenefitsForm.jsx
  src/applications/gi/components/profile/EstimatedBenefits.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/containers/EstimateYourBenefits.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/tests/gibct-helpers.js
  src/applications/gi/utils/helpers.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12376 Add functionality to the Profile's mobile side nav
  src/applications/personalization/profile-2/actions.js
  src/applications/personalization/profile-2/components/AccountSecurity.jsx
  src/applications/personalization/profile-2/components/ConnectedApplications.jsx
  src/applications/personalization/profile-2/components/DirectDeposit.jsx
  src/applications/personalization/profile-2/components/MilitaryInformation.jsx
  src/applications/personalization/profile-2/components/MobileMenuTrigger.jsx
  src/applications/personalization/profile-2/components/PersonalInformation.jsx
  src/applications/personalization/profile-2/components/ProfileSideNav.jsx
  src/applications/personalization/profile-2/components/ProfileWrapper.jsx
  src/applications/personalization/profile-2/constants.js
  src/applications/personalization/profile-2/profile-2-entry.jsx
  src/applications/personalization/profile-2/reducers.js
  src/applications/personalization/profile-2/sass/mobile-sidenav-trigger.scss
  src/applications/personalization/profile-2/sass/profile-2.scss
  src/applications/personalization/profile-2/sass/profile-sidenav.scss
Labels: VSA

#12411 CT-EYB: Group Estimate Your Benefits Section Questions to reduce vertical spacing. #8404
  src/applications/gi/components/profile/BenefitsForm.jsx
  src/applications/gi/components/profile/EybCalculatorForm.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/containers/EstimateYourBenefits.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/tests/03-vet-tec.e2e.spec.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12414 BDD Step 3 (Disabilities)
  src/applications/disability-benefits/bdd/config/form.js
Labels: BDD, Disability Benefits, VSA, front end

#12384 [Development] Add an internal form 526 redirect link
  src/applications/disability-benefits/all-claims/content/separationTrainingPay.jsx
  src/applications/disability-benefits/all-claims/content/summaryOfDisabilities.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#12362 Removed unnecessary aria-label and aria-live attributes
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/components/profile/CalculatorForm.jsx
Labels: BAH

#12344 Add closed schools to search results caution flag filter
  src/applications/gi/components/search/CautionaryWarningsFilter.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/reducers/filter.js
  src/applications/gi/tests/reducers/filter.unit.spec.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#12407 Record api request events
  src/applications/yellow-ribbon/actions/index.js
Labels: VSA, front end

#12394 bradl3yC - 8289 - review page
  src/applications/disability-benefits/2346/components/ReviewCardField.jsx
  src/applications/disability-benefits/2346/components/ReviewPageAccessories.jsx
  src/applications/disability-benefits/2346/components/ReviewPageBatteries.jsx
  src/applications/disability-benefits/2346/config/form.js
  src/applications/disability-benefits/2346/sass/form-2346.scss
  src/applications/disability-benefits/2346/schemas/definitions/2346UI.js
Labels: vsa-benefits-2

#12415 BDD Supporting Evidence and Additional Information
  src/applications/disability-benefits/bdd/config/form.js
Labels: BDD, Disability Benefits, VSA, front end

#12398 Update download name to be form-name.pdf
  src/applications/find-forms/components/SearchResult.jsx
Labels: VSA, front end

#12421 [Development] Redirect 526 to correct starting point
  src/applications/disability-benefits/all-claims/content/summaryOfDisabilities.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#12081 Kelsonic 6933 update footer link
  src/platform/static-data/footer-links.json
  src/site/assets/robots.txt
Labels: VSA, front end

#12406 Update international addresses preview handling
  src/platform/forms/address/helpers.js
  src/platform/forms/tests/address.unit.spec.js
  src/platform/user/profile/vet360/components/AddressField/AddressView.jsx
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
Labels: VSA, front end

#12408 [Development/CI/CD] Fix ReviewCardField accessibility
  src/applications/disability-benefits/all-claims/components/PaymentView.jsx
  src/platform/forms-system/src/js/components/ReviewCardField.jsx
  src/platform/forms-system/src/js/review/ObjectField.jsx
  src/platform/forms-system/test/js/components/ReviewCardField.unit.spec.jsx
  src/platform/forms-system/test/js/review/ObjectField.unit.spec.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, front end, unicorns

#12430 add some Profile 2.0 tests
  src/applications/personalization/profile-2/actions.js
  src/applications/personalization/profile-2/components/MobileMenuTrigger.jsx
  src/applications/personalization/profile-2/components/ProfileSideNav.jsx
  src/applications/personalization/profile-2/profile-2-entry.jsx
  src/applications/personalization/profile-2/reducers.js
  src/applications/personalization/profile-2/sass/profile-sidenav.scss
  src/applications/personalization/profile-2/selectors.js
  src/applications/personalization/profile-2/tests/actions.unit.spec.js
  src/applications/personalization/profile-2/tests/reducers.unit.spec.js
  src/applications/personalization/profile-2/tests/selectors.unit.spec.js
Labels: VSA

#12439 Update yarn.lock due to formation-react version bump
  yarn.lock
Labels: VSA, front end

#12441 Remove WelcomeToNewVAModal
  src/platform/site-wide/announcements/components/WelcomeToNewVAModal.jsx
  src/platform/site-wide/announcements/config/index.js
Labels: VSA, front end

#12419 CT-EYB: Group Estimate Your Benefits Section Questions to reduce vertical spacing. #8404
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/components/profile/BenefitsForm.jsx
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/tests/components/BenefitsForm.unit.spec.jsx
  src/applications/gi/tests/components/EstimateYourBenefitsForm.unit.spec.jsx
  src/applications/gi/tests/containers/EstimateYourBenefits.unit.spec.js
  src/applications/gi/tests/data/feature-toggles.json
  src/applications/gi/tests/data/ojt-profile.json
  src/applications/gi/tests/data/ojt-search-results.json
  src/applications/gi/tests/e2e/00-required.e2e.spec.js
  src/applications/gi/tests/e2e/01-keyboard.e2e.spec.js
  src/applications/gi/tests/e2e/02-profile-error.e2e.spec.js
  src/applications/gi/tests/e2e/03-vet-tec.e2e.spec.js
  src/applications/gi/tests/e2e/05-ojt.e2e.spec.js
  src/applications/gi/tests/e2e/gibct-helpers.js
  src/applications/gi/tests/e2e/ojt-helpers.js
  src/applications/gi/tests/e2e/vet-tec-helpers.js
  src/applications/gi/tests/gibct-helpers.js
  src/applications/gi/utils/helpers.js
Labels: BAH, BAH-QA-needed
