Repository department-of-veterans-affairs/vets-website, pull requests merged in 2020-01, with the labels that each got.

#11400 Show validation modal if the confidence score is < 90
  src/platform/user/profile/utilities/index.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/tests/helpers/addressValidationMessages.unit.spec.js
  src/platform/user/profile/vet360/util/local-vet360.js
Labels: VSA

#11407 Code cleanup per recommendations
  src/platform/forms-system/src/js/review/ArrayField.jsx
  src/platform/forms-system/src/js/review/ObjectField.jsx
  src/platform/forms-system/test/js/review/ReviewCollapsibleChapter.unit.spec.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#11398 Add api error handling
  src/applications/find-va-forms/actions/index.js
  src/applications/find-va-forms/containers/SearchResults.jsx
  src/applications/find-va-forms/reducers/findVAFormsReducer.js
  src/applications/find-va-forms/tests/actions/index.unit.spec.js
  src/applications/find-va-forms/tests/containers/SearchResults.unit.spec.jsx
  src/applications/find-va-forms/tests/reducers/findVAFormsReducer.unit.spec.js
Labels: VSA

#11391 Fix disability summary message (form 526)
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/summaryOfDisabilities.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#11373 4300 content adjustments rd
  src/applications/personalization/rated-disabilities/components/RatedDisabilitiesSidebar.jsx
  src/applications/personalization/rated-disabilities/components/RatedDisabilityList.jsx
  src/applications/personalization/rated-disabilities/components/RatedDisabilityView.jsx
  src/applications/personalization/rated-disabilities/components/TotalRatingStates.jsx
  src/applications/personalization/rated-disabilities/tests/components/RatedDisabilityList.unit.spec.jsx
  src/applications/personalization/rated-disabilities/tests/e2e/ratedDisabilitiesSuccess.e2e.spec.js
Labels: VSA

#11403 Clear address validation state on validation error
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
  src/platform/user/profile/vet360/util/local-vet360.js
Labels: VSA

#11411 fix failing unit test
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA

#11409 bradl3yC 4483 Disable update button if no suggestions
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA

#11375 4113 unit tests for vdl
  src/applications/personalization/view-dependents/tests/components/ViewDependentsHeader.unit.spec.jsx
  src/applications/personalization/view-dependents/tests/components/ViewDependentsList.unit.spec.jsx
  src/applications/personalization/view-dependents/tests/components/ViewDependentsListItem.unit.spec.jsx
  src/applications/personalization/view-dependents/tests/components/ViewDependentsSidebar.unit.spec.jsx
  src/applications/personalization/view-dependents/tests/components/ViewDependentsSidebarBlock.unit.spec.jsx
  src/applications/personalization/view-dependents/tests/containers/ViewDependentsApp.unit.spec.jsx
  src/applications/personalization/view-dependents/tests/layouts/ViewDependentsLayout.unit.spec.jsx
  src/applications/personalization/view-dependents/tests/layouts/ViewDependentsLists.unit.spec.jsx
Labels: VSA

#11416 fix failing unit test
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA

#11415 Fix for indentation for extension campus name in school locations
  src/applications/gi/components/profile/SchoolLocations.jsx
  src/applications/gi/components/profile/SchoolLocationsOld.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11420 Claim status tool additional evidence checkbox: remove default error state
  src/applications/claims-status/components/AddFilesForm.jsx
Labels: Disability Benefits, VSA, claim status, front end, unicorns

#11421 Disable HLR forwarding address
  src/applications/disability-benefits/996/pages/contactInformation.js
  src/applications/disability-benefits/996/tests/components/contactInfo.unit.spec.jsx
  src/applications/disability-benefits/996/tests/validations/validations.unit.spec.js
Labels: Disability Benefits, VSA, front end, unicorns

#11419 removed prod flags for 4227 and 4275
  src/applications/gi/components/profile/Programs.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/components/vet-tec/VetTecInstitutionProfile.jsx
  src/applications/gi/components/vet-tec/VetTecVeteranPrograms.jsx
  src/applications/gi/tests/components/VetTecVeteranPrograms.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11399 Prevent ITF alert showing expired future dates
  src/applications/disability-benefits/526EZ/tests/reducers.unit.spec.js
  src/applications/disability-benefits/all-claims/components/ITFBanner.jsx
  src/applications/disability-benefits/all-claims/containers/ITFWrapper.jsx
  src/applications/disability-benefits/all-claims/content/itfWrapper.jsx
  src/applications/disability-benefits/all-claims/reducers/itf.js
  src/applications/disability-benefits/all-claims/tests/automated-tests.puppeteer.spec.js
  src/applications/disability-benefits/all-claims/tests/containers/ITFWrapper.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/disability-benefits-helpers.js
  src/applications/disability-benefits/all-claims/tests/reducers.unit.spec.js
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: Disability Benefits, VSA, bug, front end, unicorns

#11422 Update validation modal proptypes
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
Labels: VSA

#11435 bradl3yC - 4544 - Update react-formation
  package.json
  yarn.lock
Labels: VSA

#11358 Upgrade MapBox SDK
  package.json
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/components/MapboxClient.js
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/utils/mapHelpers.js
  yarn.lock
Labels: VSA, facility locator, front end

#11436 Add new redirects
  src/applications/proxy-rewrite/redirects/otherDomainRedirects.json
Labels: VSA, front end

#11417 Replaced abbrevated state names with fullnames
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/tests/components/InstitutionFilterForm.unit.spec.jsx
  src/applications/gi/utils/helpers.js
Labels: BAH

#11430 GIBCT VET TEC Google Analytics
  src/applications/gi/components/vet-tec/VetTecApprovedPrograms.jsx
  src/applications/gi/components/vet-tec/VetTecCalculatorForm.jsx
  src/applications/gi/tests/components/VetTecApprovedPrograms.unit.spec.jsx
  src/applications/gi/tests/components/VetTecCalculatorForm.unit.spec.jsx
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
Labels: BAH

#11437 bradl3yC 4632 Update Address Validation Button text and form logic
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/containers/AddressValidationModal.unit.spec.jsx
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA

#11414 Enable "go back" links in validation modal messages
  src/platform/user/profile/constants/addressValidationMessages.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/tests/profile/addressValidationMessages.spec.js
Labels: VSA

#11412 Add specific table styling for find-va-forms
  src/applications/find-va-forms/containers/SearchResults.jsx
  src/applications/find-va-forms/sass/find-va-forms.scss
Labels: VSA, front end

#11447 Kelsonic 4700 downtime notification
  package.json
  src/applications/personalization/preferences/tests/e2e/emptyPreferences.e2e.spec.js
  src/platform/site-wide/announcements/components/ScheduledMaintenance.jsx
  src/platform/site-wide/announcements/components/VeteransDayProclamation.jsx
  src/platform/site-wide/announcements/config/index.js
  src/platform/site-wide/announcements/containers/Announcement.jsx
  src/platform/site-wide/announcements/selectors.js
  src/platform/site-wide/moment-setup.js
  yarn.lock
Labels: VSA, front end

#11450 Added helper method to sort states
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/tests/utils/helpers.unit.spec.js
  src/applications/gi/utils/helpers.js
Labels: BAH

#11453 VET TEC program analytics update
  src/applications/gi/components/vet-tec/VetTecCalculatorForm.jsx
  src/applications/gi/tests/components/VetTecCalculatorForm.unit.spec.jsx
Labels: BAH

#11451 VET TEC program filter sort
  src/applications/gi/components/vet-tec/VetTecFilterBy.jsx
  src/applications/gi/tests/components/VetTecFilterBy.unit.spec.jsx
Labels: BAH

#11456 Update copy
  src/applications/find-va-forms/components/TopTasks.jsx
Labels: VSA, front end

#11459 Add www.cem.va.gov redirects and remove legacy otherDomainRedirects.json
  src/applications/proxy-rewrite/redirects/disabilityRedirects.json
  src/applications/proxy-rewrite/redirects/index.js
  src/applications/proxy-rewrite/redirects/otherDomainRedirects.json
Labels: VSA, front end

#11452 HLR: Move opt out of old appeals checkbox into form
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/components/FormFooter.jsx
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/components/OptOutCheckboxWidget.jsx
  src/applications/disability-benefits/996/components/OptOutFromLegacySystem.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/content/OptOutOfOldAppeals.jsx
  src/applications/disability-benefits/996/content/OptOutOldAppeals.jsx
  src/applications/disability-benefits/996/pages/optOutOfOldAppeals.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/confirmVeteranDetails.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/optOutOfOldAppeals.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/schema/initialData.js
  src/applications/disability-benefits/996/validations/index.js
Labels: Disability Benefits, VSA, front end, unicorns

#11465 Remove Issue Date
  src/applications/find-va-forms/containers/SearchResults.jsx
  src/applications/find-va-forms/helpers/index.js
  src/applications/find-va-forms/tests/helpers/index.unit.spec.js
Labels: VSA, front end

#11464 Remove ScheduledMaintenance component and announcements
  src/platform/site-wide/announcements/components/ScheduledMaintenance.jsx
  src/platform/site-wide/announcements/config/index.js
Labels: VSA, front end

#11474 VET TEC profile school certifying officials list display fix
  src/applications/gi/components/vet-tec/VetTecContactInformation.jsx
  src/applications/gi/components/vet-tec/VetTecScoContact.jsx
  src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
  src/applications/gi/tests/components/VetTecContactInformation.unit.spec.jsx
  src/applications/gi/tests/components/VetTecScoContact.unit.spec.jsx
Labels: BAH

#11479 Update all instances of benefit office to regional office
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/manifest.json
  src/applications/personalization/profile360/components/ContactInformationExplanation.jsx
  src/applications/personalization/profile360/components/MilitaryInformation.jsx
  src/applications/personalization/profile360/components/PersonalInformation.jsx
  src/site/layouts/home.drupal.liquid
  src/site/layouts/home.html
Labels: VSA, front end

#11477 bradl3yC - 4837 - Clear address validation errors on initialize
  src/platform/user/profile/vet360/reducers/index.js
  src/platform/user/profile/vet360/tests/reducers/index.unit.spec.js
Labels: VSA

#11328 Change the link on the search results to point to the VAMC
  src/applications/facility-locator/components/search-results/LocationInfoBlock.jsx
  src/applications/facility-locator/tests/helpers.unit.spec.js
  src/applications/facility-locator/utils/helpers.js
Labels: VSA, facility locator, front end

#11124 CT 116: Prod Flag Removal for Contact Info SCO Section #19715
  src/applications/gi/components/vet-tec/VetTecContactInformation.jsx
Labels: BAH, BAH-QA-needed

#11483 Require Character of Service field in 10-10ez
  src/applications/hca/config/form.js
  src/applications/hca/tests/config/serviceInformation.unit.spec.js
Labels: Disability Benefits, VSA, front end, unicorns

#11488 CT 116: Remove Feature Flag for VETTEC programs filter #4709
  src/applications/gi/components/vet-tec/VetTecFilterBy.jsx
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/tests/components/VetTecFilterBy.unit.spec.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#11502 [Development] Replace "apply for" to "file for" content in form 526
  src/applications/disability-benefits/526EZ/config/form.js
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/manifest.json
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/platform/site-wide/cta-widget/helpers.js
  src/site/includes/common-and-popular.html
Labels: Disability Benefits, VSA, front end, unicorns

#11500 [Development] HLR remove "pension" from content
  src/applications/disability-benefits/996/components/HLRWizard.jsx
  src/applications/disability-benefits/996/content/contestedIssues.js
  src/applications/disability-benefits/996/content/wizardLabels.jsx
  src/applications/disability-benefits/996/tests/containers/HLR-wizard.unit.spec.jsx
Labels: Disability Benefits, VSA, front end, unicorns

#11501 bradl3yC - 3219 - Change heading levels per cognition rules
  src/applications/hca/enrollment-status-helpers.jsx
  src/applications/hca/tests/components/HCAEnrollmentStatusFAQ.unit.spec.js
Labels: VSA

#11511 bradl3yC - 2440 - Add aria-label to profile edit links
  src/platform/user/profile/vet360/components/base/Vet360ProfileFieldHeading.jsx
Labels: VSA

#11510 Add client-side redirect
  src/applications/proxy-rewrite/redirects/crossDomainRedirects.json
  src/applications/proxy-rewrite/redirects/index.js
Labels: VSA, front end

#11484 bradl3yC - 2430 - Set focus when phone number is deleted
  src/platform/user/profile/vet360/components/base/Vet360EditModalActionButtons.jsx
  src/platform/user/profile/vet360/containers/Vet360ProfileField.jsx
Labels: VSA

#11512 bradl3yC - 2435 - Add space between phone inputs
  src/platform/user/profile/vet360/components/PhoneField/PhoneEditModal.jsx
Labels: VSA

#11498 Fix auto geolocation enabled on the facility locator
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/tests/mapbox/mapbox-api-services.unit.spec.js
  src/applications/facility-locator/utils/mapHelpers.js
Labels: VSA, facility locator, front end

#11520 4908 686 report marriage of child
  src/applications/disability-benefits/686/config/form.js
Labels: VSA

#11515 Update deploy notify # to #cms-team in Jenkinsfile.
  jenkins/common.groovy
Labels: cms

#11508 [Development] Add reject timer to 526 form submission promise
  src/applications/disability-benefits/all-claims/config/submitForm.js
  src/applications/disability-benefits/all-claims/submit-transformer.js
  src/applications/disability-benefits/all-claims/tests/config/submitForm.unit.spec.js
Labels: Disability Benefits, VSA, front end, unicorns

#11525 [Development] HLR same office checkbox made global in a separate step
  src/applications/disability-benefits/996/20-0996-schema.json
  src/applications/disability-benefits/996/TODO.md
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/content/OfficeForReview.jsx
  src/applications/disability-benefits/996/content/contestedIssueFollowup.js
  src/applications/disability-benefits/996/pages/contestedIssueFollowup.js
  src/applications/disability-benefits/996/pages/officeForReview.js
  src/applications/disability-benefits/996/tests/components/contestedIssueFollowup.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/officeForReview.unit.spec.js
  src/applications/disability-benefits/996/tests/schema/initialData.js
Labels: Disability Benefits, VSA, front end, unicorns

#11547 VAGOV-6419: Update facility operating status intro text.
  src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
Labels: needs peer approval

#11560 Fix letters JS error
  src/applications/letters/tests/utils/helpers.unit.spec.jsx
  src/applications/letters/utils/helpers.jsx
Labels: VSA, bug, front end, unicorns

#11545 Update search results to include new Caution Flag design
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
  src/applications/gi/sass/partials/_gi-search-page.scss
  src/applications/gi/tests/components/VetTecProgramSearchResult.unit.spec.jsx
  src/applications/gi/utils/render.jsx
Labels: BAH

#11561 bradl3yC - 4489 - Add formation classnames to left justify text
  src/platform/user/profile/vet360/components/AddressField/AddressForm.jsx
  src/platform/user/profile/vet360/containers/CopyMailingAddress.jsx
Labels: VSA

#11554 Fix propType error
  src/platform/user/profile/vet360/containers/Vet360ProfileField.jsx
  src/platform/user/profile/vet360/tests/containers/Vet360ProfileField.unit.spec.jsx
Labels: VSA

#11562 removed REAP option from 1995 frontend
  src/applications/edu-benefits/1995/pages/benefitSelection.js
  src/applications/edu-benefits/tests/1995/pages/benefitSelection.unit.spec.jsx
Labels: BAH

#11544 bradl3yC - 2429 - Add tabIndex to requested nodes
  src/applications/personalization/profile360/components/ContactInformation.jsx
  src/applications/personalization/profile360/components/MilitaryInformation.jsx
  src/applications/personalization/profile360/components/PersonalInformation.jsx
  src/applications/personalization/profile360/containers/PaymentInformation.jsx
Labels: VSA

#11578 fixed accordian from reading anything below and fixed enrolled dropdown from reading everything above on option change
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/components/profile/Calculator.jsx
Labels: BAH

#11570 fix styling issues for alert messages
  src/applications/gi/sass/partials/_gi-search-page.scss
Labels: BAH

#11495 Feature/4904 create unit test for add to calendar component
  src/applications/vaos/tests/components/AddToCalendar.unit.spec.jsx
  src/applications/vaos/tests/utils/appointment.unit.spec.jsx
Labels: needs peer approval

#11579 bradl3yC - 5180 - Add helper method to shape payload
  src/platform/user/profile/vet360/actions/transactions.js
Labels: VSA

#11557 4898 686 report dependent death
  src/applications/disability-benefits/686/config/form.js
  src/applications/disability-benefits/686/tests/config/reportDeath.unit.spec.jsx
Labels: VSA

#11592 Remove testing condition flag
  src/applications/facility-locator/components/search-results/LocationInfoBlock.jsx
Labels: VSA, facility locator, front end

#11588 Scroll keyword search input box to center of screen when using small screen resolution
  src/applications/gi/components/Checkbox.jsx
  src/applications/gi/components/Dropdown.jsx
  src/applications/gi/components/RadioButtons.jsx
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/components/search/KeywordSearch.jsx
  src/applications/gi/constants.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#11551 Kelsonic 4803 yr mvp
  src/applications/yellow-ribbon/actions/index.js
  src/applications/yellow-ribbon/actions/index.unit.spec.js
  src/applications/yellow-ribbon/api/index.js
  src/applications/yellow-ribbon/api/index.unit.spec.js
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/components/SearchResult/index.unit.spec.jsx
  src/applications/yellow-ribbon/constants/STATES.json
  src/applications/yellow-ribbon/constants/index.js
  src/applications/yellow-ribbon/constants/index.unit.spec.js
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.unit.spec.jsx
  src/applications/yellow-ribbon/helpers/index.js
  src/applications/yellow-ribbon/helpers/index.unit.spec.js
  src/applications/yellow-ribbon/reducers/index.js
  src/applications/yellow-ribbon/reducers/index.unit.spec.js
  src/applications/yellow-ribbon/routes/index.unit.spec.js
  src/applications/yellow-ribbon/sass/yellow-ribbon.scss
  src/applications/yellow-ribbon/yellow-ribbon-entry.jsx
Labels: VSA, design, front end

#11583 bradl3yC - 5178 - Change condition to render inputs
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
Labels: VSA

#11558 Remove conditional for environment checks for QA
  package.json
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/components/MapboxClient.js
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/utils/mapHelpers.js
Labels: VSA, facility locator, front end

#11589 Add `preserveHiddenData` option to `updateSchemaAndData()`
  src/platform/forms-system/src/js/state/helpers.js
Labels: VSA

#11594 updated commit hash from vets-json-schema and removed prod flag
  package.json
  src/applications/edu-benefits/1995/pages/benefitSelection.js
  src/applications/edu-benefits/utils/labels.jsx
  src/platform/forms/tests/forms.unit.spec.js
  yarn.lock
Labels: BAH

#11609 Mojaray2k 5313 mdt introduction page work set up
  src/applications/disability-benefits/2346/2346-schema.json
  src/applications/disability-benefits/2346/app-entry.jsx
  src/applications/disability-benefits/2346/config/form.js
  src/applications/disability-benefits/2346/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/2346/containers/IntroductionPage.jsx
  src/applications/disability-benefits/2346/definitions/toursOfDuty.js
  src/applications/disability-benefits/2346/helpers.js
  src/applications/disability-benefits/2346/manifest.json
  src/applications/disability-benefits/2346/pages/mdt/2346.md
  src/applications/disability-benefits/2346/reducers/index.js
  src/applications/disability-benefits/2346/routes.jsx
  src/applications/disability-benefits/2346/sass/mdt-introduction.scss
  src/applications/disability-benefits/2346/tests/00.mdt-introduction.e2e.spec.js
Labels: needs peer approval
