Repository department-of-veterans-affairs/vets-website, pull requests merged in 2020-10, with the labels that each got.

#14211 526/BDD and CST: Increase File Size Limit
  src/applications/claims-status/components/AddFilesForm.jsx
  src/applications/claims-status/utils/validations.js
  src/applications/disability-benefits/all-claims/content/fileUploadDescriptions.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 526, BDD, Disability Benefits, VSA, claim status, front end

#14439 Content update for facility locator
  src/applications/facility-locator/containers/VAMap.jsx
Labels: VSA, facility locator, front end

#14418 STEM: Remove 22-10203s from in progress applications that were purposefully exited #13794
  src/applications/edu-benefits/10203/actions/post-911-gib-status.js
  src/applications/edu-benefits/10203/components/ExitApplicationButton.jsx
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/containers/InitialConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/tests/components/ExitApplicationButton.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/containers/ConfirmEligibilityView.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/containers/InitialConfirmEligibilityView.unit.spec.jsx
Labels: BAH

#14425 [AXE-CORE] CTA heading levels SHOULD only increase by one
  src/platform/site-wide/cta-widget/components/CallToActionAlert.jsx
  src/platform/site-wide/cta-widget/components/messages/SignIn.jsx
  src/platform/site-wide/cta-widget/index.js
Labels: 508/Accessibility, Disability Benefits, VSA, front end

#14437 EDU: Create feature flag for education form updates #14064
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#14446 Update Letter Types
  src/applications/letters/utils/constants.js
Labels: VSA

#14438 Add about template
  src/site/layouts/support_resources_detail_page.drupal.liquid
  src/site/stages/build/drupal/graphql/GetAllPages.graphql.js
  src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js
  src/site/stages/build/drupal/graphql/nodeSupportResourcesDetailPage.graphql.js
Labels: VSA, front end

#14441 Add fieldAlert support for each step in step_by_step
  src/site/layouts/step_by_step.drupal.liquid
  src/site/stages/build/drupal/graphql/nodeStepByStep.graphql.js
Labels: VSA, front end

#14405 13784: Update Personal Information Chapter Layout and questions
  package.json
  src/applications/edu-benefits/10203/content/personalInformation.jsx
  src/applications/edu-benefits/10203/pages/personalInformation.js
  src/applications/edu-benefits/10203/sass/10203_stem.scss
  src/applications/edu-benefits/10203/tests/pages/personalInformation.unit.spec.jsx
  yarn.lock
Labels: BAH

#14452 [Development] HLR spot check fixes
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/content/contestedIssues.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
Labels: 508/Accessibility, Disability Benefits, HLR, VSA, front end

#14440 [Search app] Update links on the right rail
  .github/CODEOWNERS
  src/applications/search/containers/SearchApp.jsx
Labels: VSA

#14457 12420 import 28 1900 schema
  package.json
  src/applications/vre/28-1900/config/chapters/additional-information/additionalInformation.js
  src/applications/vre/28-1900/config/chapters/communication-preferences/communicationPreferences.js
  src/applications/vre/28-1900/config/chapters/veteran/veteran-address/veteranAddress.js
  src/applications/vre/28-1900/config/chapters/veteran/veteran-information/veteranInformation.js
  src/applications/vre/28-1900/config/constants.js
  src/applications/vre/28-1900/config/form.js
  src/applications/vre/28-1900/containers/StaticInformationReviewField.jsx
  src/applications/vre/28-1900/tests/config/additionalInformation.unit.spec.jsx
  yarn.lock
Labels: VSA

#14443 Make lastFacilityName and lastFacilityType optionally required
  src/applications/caregivers/definitions/caregiverUI.js
  src/applications/caregivers/helpers.js
Labels: bug, caregivers, front end

#14435 13765: Debt Letters I2 Add Content for Diary Codes
  src/applications/debt-letters/actions/index.js
  src/applications/debt-letters/components/DebtDetails.jsx
  src/applications/debt-letters/components/DebtLetterCard.jsx
  src/applications/debt-letters/components/DebtLettersList.jsx
  src/applications/debt-letters/const/deduction-codes/index.js
  src/applications/debt-letters/const/diary-codes/index.js
Labels: VSA

#14396 Healthcare 12282 landing page
  src/applications/healthcare/questionnaire/app-entry.jsx
  src/applications/healthcare/questionnaire/components/get-help/GetHelpFooter.jsx
  src/applications/healthcare/questionnaire/components/get-help/index.js
  src/applications/healthcare/questionnaire/components/introduction-page/TopAlert.jsx
  src/applications/healthcare/questionnaire/components/introduction-page/index.js
  src/applications/healthcare/questionnaire/config/form.js
  src/applications/healthcare/questionnaire/containers/App.jsx
  src/applications/healthcare/questionnaire/containers/IntroductionPage.jsx
  src/applications/healthcare/questionnaire/sass/footer.scss
  src/applications/healthcare/questionnaire/sass/questionnaire.scss
  src/applications/healthcare/questionnaire/tests/e2e/00.questionnaire.loads.cypress.spec.js
  src/applications/healthcare/questionnaire/tests/e2e/02.questionnaire.form.happy.path.cypress.js
  src/applications/healthcare/questionnaire/tests/e2e/02.questionnaire.form.required.cypress.js
  src/applications/healthcare/questionnaire/tests/e2e/03.questionnaire.landing.page.accessibility.cypress.spec.js
Labels: needs peer approval

#14459 Fix for screen only p on map area
  src/applications/facility-locator/containers/VAMap.jsx
Labels: VSA, facility locator, front end

#14470 Update School, university, program, or training facility you last attended label to match new standards
  src/applications/edu-benefits/pages/oldSchool.js
Labels: BAH

#14403 [Development] Update HLR prefill
  src/applications/disability-benefits/996/config/prefill-transformer.js
  src/applications/disability-benefits/996/config/submit-transformer.js
  src/applications/disability-benefits/996/containers/ReviewDescription.jsx
  src/applications/disability-benefits/996/content/contactInformation.jsx
  src/applications/disability-benefits/996/content/veteranInformation.jsx
  src/applications/disability-benefits/996/tests/components/contactInfo.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/veteranInformation.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/ReviewDescription.unit.spec.jsx
  src/applications/disability-benefits/996/tests/content/contactInformation.unit.spec.jsx
  src/applications/disability-benefits/996/tests/content/veteranInformation.unit.spec.jsx
  src/applications/disability-benefits/996/tests/fixtures/data/maximal-test.json
  src/applications/disability-benefits/996/tests/fixtures/data/minimal-test.json
  src/applications/disability-benefits/996/tests/fixtures/data/transformed-maximal-test.json
  src/applications/disability-benefits/996/tests/hlr.cypress.spec.js
  src/applications/disability-benefits/996/tests/schema/initialData.js
  src/applications/disability-benefits/996/tests/schema/prefill-transformer.unit.spec.js
Labels: Disability Benefits, HLR, VSA, front end

#14413 use session for ssoe transaction
  src/platform/site-wide/ebenefits/tests/selectors.unit.spec.js
  src/platform/user/authentication/selectors.js
  src/platform/user/profile/reducers/index.js
  src/platform/user/profile/utilities/index.js
  src/platform/user/tests/authentication/selectors.unit.spec.js
Labels: bug

#14463 Update Applicant information labels to match new standards
  src/platform/forms/definitions/fullName.js
  src/platform/forms/pages/applicantInformation.jsx
Labels: BAH

#14450 Exclude Mobile Vet Centers from Facility Locator search results
  src/applications/facility-locator/config.js
  src/applications/facility-locator/tests/api-url-parameters.unit.spec.js
Labels: VSA, facility locator, front end

#14458 Fix alert icons for screenreader
  src/applications/facility-locator/components/search-results-items/common/LocationOperationStatus.jsx
  src/applications/facility-locator/tests/components/VaFacilityResult.unit.spec.jsx
Labels: VSA, facility locator, front end

#14482 [Development] HLR: Fix veteran ssn/va file no prefill
  src/applications/disability-benefits/996/content/veteranInformation.jsx
Labels: Disability Benefits, HLR, VSA, front end

#14472 Update Service Before 1977 dependents question
  src/applications/edu-benefits/definitions/serviceBefore1977.jsx
Labels: BAH

#14471 Update Contact Information to match new standards
  package.json
  src/applications/edu-benefits/1990/tests/config/contactInformation.unit.spec.jsx
  src/applications/edu-benefits/pages/contactInformation.js
  src/applications/edu-benefits/utils/labels.jsx
  yarn.lock
Labels: BAH

#14436 GIBCT - institution ratings
  src/applications/gi/components/profile/CautionFlagHeading.jsx
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/components/search/RatedSearchResult.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/tests/utils/helpers.unit.spec.js
  src/applications/gi/tests/utils/render.unit.spec.js
  src/applications/gi/utils/helpers.js
  src/applications/gi/utils/render.jsx
Labels: BAH

#14478 Use fieldRelatedInformation over fieldRelatedLinks
  src/site/includes/related-information.drupal.liquid
  src/site/layouts/checklist.drupal.liquid
  src/site/layouts/faq_multiple_q_a.drupal.liquid
  src/site/layouts/media_list_images.drupal.liquid
  src/site/layouts/media_list_videos.drupal.liquid
  src/site/layouts/q_a.drupal.liquid
  src/site/layouts/step_by_step.drupal.liquid
  src/site/layouts/support_resources_detail_page.drupal.liquid
  src/site/stages/build/drupal/graphql/faqMultipleQa.graphql.js
  src/site/stages/build/drupal/graphql/nodeChecklist.graphql.js
  src/site/stages/build/drupal/graphql/nodeMediaListImages.graphql.js
  src/site/stages/build/drupal/graphql/nodeMediaListVideos.graphql.js
  src/site/stages/build/drupal/graphql/nodeQa.graphql.js
  src/site/stages/build/drupal/graphql/nodeStepByStep.graphql.js
  src/site/stages/build/drupal/graphql/nodeSupportResourcesDetailPage.graphql.js
Labels: VSA, front end

#14480 FL Required fields must be marked in the UI
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/tests/components/SearchControls.unit.spec.jsx
Labels: VSA, facility locator, front end

#14491 [Development] Edit new service period when missing data
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
Labels: 526, BDD, Disability Benefits, VSA, front end

#14473 Update Direct Deposit to match new standards
  src/applications/edu-benefits/pages/directDepositChange.js
  src/applications/edu-benefits/utils/labels.jsx
  src/platform/forms-system/src/js/definitions/bankAccount.js
  src/platform/forms/definitions/bankAccount.js
Labels: BAH

#14498 Handle email address error codes
  src/applications/personalization/profile-2/msw-mocks.js
  src/platform/user/profile/vet360/actions/transactions.js
  src/platform/user/profile/vet360/components/base/Vet360EditModalErrorMessage.jsx
  src/platform/user/profile/vet360/tests/components/Vet360EditModalErrorMessage.unit.spec.jsx
  src/platform/user/profile/vet360/util/transactions.js
Labels: VSA, front end

#14420 Add Pacts for GET service_history endpoint
  src/applications/personalization/profile360/tests/service-history.pact.spec.js
Labels: VSA

#14494 FL: Fix state after failed search
  src/applications/facility-locator/reducers/searchQuery.js
  src/applications/facility-locator/tests/reducers/searchQuery.unit.spec.js
Labels: VSA, facility locator, front end

#14447 EDU: Update 1995 content to match DEPO styles #13965
  src/applications/edu-benefits/1995/config/chapters.js
  src/applications/edu-benefits/1995/config/form.js
  src/applications/edu-benefits/1995/config/oldChapters.js
  src/applications/edu-benefits/1995/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1995/pages/benefitSelection.js
  src/applications/edu-benefits/1995/pages/dependents.js
  src/applications/edu-benefits/1995/pages/index.js
  src/applications/edu-benefits/1995/pages/militaryHistory.js
  src/applications/edu-benefits/1995/pages/newSchool.js
  src/applications/edu-benefits/1995/pages/servicePeriods.js
  src/applications/edu-benefits/pages/oldSchool.js
Labels: BAH

#14505 CT - mobile styling update
  src/applications/gi/components/search/RatedSearchResult.jsx
  src/applications/gi/selectors/estimator.js
Labels: BAH

#14504 Adjustment in data layer for FL map-move event
  src/applications/facility-locator/tests/e2e/gaEvents.cypress.spec.js
  src/applications/facility-locator/utils/analytics.js
Labels: VSA, facility locator, front end

#14212 Add pact tests for facility search
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/api/index.js
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/tests/contract/search.pact.spec.js
Labels: VSA, facility locator, front end, testing

#14493 14407: Removal of id causing mismatch in label and the content
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
Labels: BAH, BAH-QA-needed

#14414 Adding Secondary on Review Error
  src/applications/caregivers/components/PreSubmitInfo/SignatureInput.jsx
Labels: bug, caregivers, front end

#14449 Sanlouise/fix scroll error
  package.json
  src/platform/user/profile/vet360/components/base/VAPEditModalActionButtons.jsx
  yarn.lock
Labels: VSA, front end

#14509 Identify transformers owned by facilities team
  src/site/stages/build/process-cms-exports/transformers/README.md
Labels: cms-transformer

#14529 [Bug] Fix edit mode on new conditions page
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 526, BDD, Disability Benefits, VSA, bug, front end

#14538 Update step by step to support new cardinality
  src/site/layouts/step_by_step.drupal.liquid
Labels: VSA, front end

#14522 [HEADINGS]: GIBCT EYB - Additional resources headings SHOULD be H2s on all three profile types #14419
  src/applications/gi/components/content/AdditionalResources.jsx
  src/applications/gi/components/content/AdditionalResourcesLinks.jsx
  src/applications/gi/components/content/VideoSidebar.jsx
  src/applications/gi/components/vet-tec/VetTecAdditionalResources.jsx
  src/applications/gi/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi/sass/partials/_gi-vet-tec.scss
  src/applications/gi/tests/components/content/AdditionalResources.unit.spec.js
  src/applications/gi/tests/components/content/AdditionalResourcesLinks.unit.spec.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14519 Sanlouise 14012 hide profile error
  src/applications/personalization/profile-2/components/Profile2Wrapper.jsx
  src/applications/personalization/profile-2/tests/components/Profile.data-unavailable-error.unit.spec.js
Labels: VSA, front end

#14513 set focus to input field when it's span is clicked
  src/applications/gi/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
  src/applications/gi/utils/render.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14557 Updated skip to E.Y.B. link on profile page.
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14561 Fix step by step alerts
  src/site/layouts/step_by_step.drupal.liquid
  src/site/stages/build/drupal/graphql/nodeStepByStep.graphql.js
Labels: VSA, front end

#14535 13830: STEM: Remove in-progress application prod flag
  src/applications/edu-benefits/10203/components/ExitApplicationButton.jsx
Labels: BAH, BAH-QA-needed

#14530 CT - Profile ratings
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/components/profile/SchoolCategoryRating.jsx
  src/applications/gi/components/profile/SchoolRatings.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/tests/components/profile/SchoolCategoryRating.unit.spec.jsx
  src/applications/gi/tests/components/profile/SchoolRatings.unit.spec.jsx
  src/applications/gi/tests/components/search/RatedSearchResult.unit.spec.jsx
  src/applications/gi/tests/utils/helpers.unit.spec.js
  src/applications/gi/utils/helpers.js
  src/applications/gi/utils/render.jsx
Labels: BAH

#14563 Added gold outline to EYB link
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14416 BDD: Pull Separation Locations from API
  src/applications/disability-benefits/all-claims/content/separationLocations.js
  src/applications/disability-benefits/all-claims/pages/separationLocation.js
  src/applications/disability-benefits/all-claims/submit-transformer.js
  src/applications/disability-benefits/all-claims/tests/fixtures/data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/minimal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/minimal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/validations.unit.spec.js
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/disability-benefits/all-claims/validations.js
Labels: BDD, Disability Benefits, VSA, front end

#14558 remove 'gibct_filter_enhancement' flag usage
  src/applications/caregivers/tests/e2e/fixtures/mocks/feature-toggles.json
  src/applications/debt-letters/tests/e2e/fixtures/mocks/feature-toggles.json
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/components/search/InstitutionFilterForm.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/components/search/RatedSearchResult.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/search/SearchResultTypeOfInstitutionFilter.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/tests/components/search/InstitutionSearchForm.unit.spec.jsx
  src/applications/gi/tests/components/search/SearchResult.unit.spec.jsx
  src/applications/healthcare/questionnaire/tests/e2e/fixtures/mocks/feature-toggles.disabled.json
  src/applications/healthcare/questionnaire/tests/e2e/fixtures/mocks/feature-toggles.enabled.json
  src/applications/static-pages/health-care-manage-benefits/fixtures/feature-toggles/disabled.json
  src/applications/static-pages/health-care-manage-benefits/fixtures/feature-toggles/enabled.json
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14141 1010CG SaveInProgress bug
  src/applications/caregivers/config/pages/vetMedicalCenter.js
  src/applications/caregivers/routes.jsx
Labels: bug, caregivers, front end

#14573 unit tests for chapter 31 veteran information
  src/applications/vre/28-1900/tests/config/veteranInformation.unit.spec.js
  src/applications/vre/28-1900/tests/helpers.js
Labels: VSA

#14422 Unit Test 10-10CG Transformer methods
  src/applications/caregivers/helpers.js
  src/applications/caregivers/tests/e2e/1010cg.cypress.spec.js
  src/applications/caregivers/tests/e2e/fixtures/data/oneSecondaryCaregivers.json
  src/applications/caregivers/tests/e2e/fixtures/data/requiredOnly.json
  src/applications/caregivers/tests/e2e/fixtures/data/twoSecondaryCaregivers.json
  src/applications/caregivers/tests/helpers.unit.spec.js
Labels: caregivers, front end, testing

#14572 Update connected apps FAQ
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApps.jsx
Labels: VSA, front end

#14574 add test for communication preferences
  src/applications/vre/28-1900/tests/config/communicationPreferences.unit.spec.js
Labels: VSA

#14149 Add third-party app directory
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
  src/applications/third-party-app-directory/actions/index.js
  src/applications/third-party-app-directory/api/index.js
  src/applications/third-party-app-directory/api/stub.js
  src/applications/third-party-app-directory/components/SearchPage/index.jsx
  src/applications/third-party-app-directory/components/SearchResult/index.jsx
  src/applications/third-party-app-directory/constants/CATEGORIES.js
  src/applications/third-party-app-directory/constants/PLATFORMS.js
  src/applications/third-party-app-directory/constants/index.js
  src/applications/third-party-app-directory/containers/App/index.jsx
  src/applications/third-party-app-directory/containers/SearchForm/index.jsx
  src/applications/third-party-app-directory/containers/SearchResults/index.jsx
  src/applications/third-party-app-directory/createThirdPartyApps.js
  src/applications/third-party-app-directory/helpers/index.js
  src/applications/third-party-app-directory/prop-types.js
  src/applications/third-party-app-directory/reducers/index.js
  src/applications/third-party-app-directory/sass/index.scss
  src/applications/third-party-app-directory/third-party-apps-entry.js
Labels: VSA, front end

#14481 13981: Initial Scaffolding of FSR Form
  .github/CODEOWNERS
  src/applications/financial-status-report/app-entry.jsx
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/containers/App.jsx
  src/applications/financial-status-report/containers/ConfirmationPage.jsx
  src/applications/financial-status-report/containers/IntroductionPage.jsx
  src/applications/financial-status-report/manifest.json
  src/applications/financial-status-report/reducers/index.js
  src/applications/financial-status-report/routes.jsx
  src/applications/financial-status-report/sass/financial-status-report.scss
  src/applications/financial-status-report/tests/e2e/fixtures/data/test-data.json
  src/applications/financial-status-report/tests/e2e/fsr-5655.cypress.spec.js
  src/applications/financial-status-report/tests/fsr-5655.unit.spec.js
  src/applications/registry.json
  src/platform/forms/constants.js
Labels: VSA

#14461 Remove feature flag reference for profile 2
  src/applications/personalization/account/containers/AccountApp.jsx
  src/applications/personalization/account/tests/containers/AccountApp.redirect.unit.spec.jsx
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/applications/personalization/dashboard/tests/containers/DashboardApp.unit.spec.jsx
  src/applications/personalization/profile-2/selectors.js
  src/applications/personalization/profile-2/tests/e2e/profile.connected-apps.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.direct-deposit.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.loa1.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.mpi-error.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.not-in-mpi-error.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.personal-and-contact-information-modals.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.personal-and-contact-mailing-address.cypress.spec.js
  src/applications/personalization/profile-2/tests/fixtures/feature-toggles.json
  src/applications/personalization/profile360/tests/e2e/profile-360.e2e.spec.js
  src/applications/personalization/profiles-wrapper/ProfilesWrapper.jsx
  src/platform/site-wide/cta-widget/components/messages/ChangeAddress.jsx
  src/platform/site-wide/user-nav/components/PersonalizationDropdown.jsx
  src/platform/site-wide/user-nav/tests/components/PersonalizationDropdown.unit.spec.jsx
  src/platform/site-wide/user-nav/tests/user-nav.e2e.spec.js
  src/platform/user/profile/vet360/tests/e2e/addressValidation.e2e.spec.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA, front end

#14444 Update comparison tool filter questions text and online school "learn more" modal
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/components/search/LandingPageTypeOfInstitutionFilter.jsx
  src/applications/gi/components/search/OnlineClassesFilter.jsx
  src/applications/gi/components/search/SearchResultTypeOfInstitutionFilter.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/containers/Modals.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14579 14365: Update breadcrumb title and links along with page and form titles
  src/applications/edu-benefits/1995/config/form.js
  src/applications/edu-benefits/1995/containers/IntroductionPage.jsx
  src/applications/registry.json
Labels: BAH, BAH-QA-needed

#14593 Fixed gibctBenefitFilterEnhancement flag
  src/applications/gi/components/profile/BenefitsForm.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/tests/components/search/RatedSearchResult.unit.spec.jsx
Labels: BAH

#14571 move functions from HCA helpers to platform
  .github/CODEOWNERS
  src/applications/hca/helpers.jsx
  src/applications/hca/tests/helpers.unit.spec.jsx
  src/platform/utilities/medical-centers/medical-centers.js
  src/platform/utilities/medical-centers/medical-centers.unit.spec.js
Labels: VSA

#14548 14472: Update link in how to apply wizard content.
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/components/EducationWizard.jsx
  src/applications/edu-benefits/tests/components/EducationWizard.unit.spec.jsx
  src/applications/edu-benefits/wizard/pages/STEMScholarship.jsx
  src/applications/gi/containers/Modals.jsx
Labels: BAH

#14564 CT - minimum ratings to display
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/components/profile/SchoolCategoryRating.jsx
  src/applications/gi/components/profile/SchoolRatings.jsx
  src/applications/gi/components/search/RatedSearchResult.jsx
  src/applications/gi/constants.js
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/tests/components/profile/HeadingSummary.unit.spec.jsx
  src/applications/gi/tests/components/profile/InstitutionProfile.unit.spec.jsx
  src/applications/gi/tests/components/search/RatedSearchResult.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#14612 Added missing word to online classes modal text
  src/applications/gi/containers/Modals.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14604 526/BDD: Move servedInCombatZone Immediately After Military History
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 526, BDD, Disability Benefits, VSA, front end

#14609 [Development] Validate BDD flow
  src/applications/disability-benefits/all-claims/components/UpdateMilitaryHistory.jsx
  src/applications/disability-benefits/all-claims/tests/components/UpdateMilitaryHistory.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 526, BDD, Disability Benefits, VSA, bug, front end

#14595 14634 chp31 adjustments
  src/applications/registry.json
  src/applications/vre/28-1900/components/PreSubmitInfo.js
  src/applications/vre/28-1900/config/chapters/veteran/veteran-address/veteranAddress.js
  src/applications/vre/28-1900/config/form.js
  src/applications/vre/28-1900/containers/IntroductionPage.jsx
  src/applications/vre/28-1900/tests/config/veteranContactInformation.unit.spec.js
Labels: VSA

#14594 Add need more help
  src/site/includes/related-benefit-hubs.drupal.liquid
  src/site/layouts/checklist.drupal.liquid
  src/site/layouts/faq_multiple_q_a.drupal.liquid
  src/site/layouts/media_list_images.drupal.liquid
  src/site/layouts/media_list_videos.drupal.liquid
  src/site/layouts/q_a.drupal.liquid
  src/site/layouts/step_by_step.drupal.liquid
  src/site/layouts/support_resources_detail_page.drupal.liquid
  src/site/stages/build/drupal/graphql/faqMultipleQa.graphql.js
  src/site/stages/build/drupal/graphql/fragments.graphql.js
  src/site/stages/build/drupal/graphql/nodeChecklist.graphql.js
  src/site/stages/build/drupal/graphql/nodeMediaListImages.graphql.js
  src/site/stages/build/drupal/graphql/nodeMediaListVideos.graphql.js
  src/site/stages/build/drupal/graphql/nodeQa.graphql.js
  src/site/stages/build/drupal/graphql/nodeStepByStep.graphql.js
  src/site/stages/build/drupal/graphql/nodeSupportResourcesDetailPage.graphql.js
  src/site/stages/build/drupal/graphql/supportService.graphql.js
Labels: VSA, front end

#14568 Use more granular selector to show/hide Cerner appt widget
  src/applications/personalization/dashboard/components/ManageYourVAHealthCare.jsx
  src/platform/user/selectors.js
  src/platform/user/tests/selectors.unit.spec.js
  src/platform/utilities/cerner/index.js
Labels: VSA

#14607 14639: 1995: Update button and question content
  src/applications/edu-benefits/definitions/serviceBefore1977.jsx
  src/applications/edu-benefits/definitions/toursOfDuty.jsx
  src/platform/forms-system/src/js/fields/ArrayField.jsx
  src/platform/forms-system/src/js/review/ArrayField.jsx
  src/platform/forms-system/test/js/fields/ArrayField.unit.spec.jsx
  src/platform/forms-system/test/js/review/ArrayField.unit.spec.jsx
Labels: BAH

#14637 Ensure related information doesn't render when there's only 1 empty one
  src/site/includes/related-information.drupal.liquid
Labels: VSA, front end

#14638 Category ratings group update
  src/applications/gi/components/profile/SchoolRatings.jsx
  src/applications/gi/tests/components/profile/SchoolRatings.unit.spec.jsx
Labels: BAH

#14601 Caregiver QA feedback
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/components/NeedHelpFooter/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/components/SubmitError/index.jsx
  src/applications/caregivers/containers/ConfirmationPage.jsx
  src/applications/caregivers/definitions/caregiverUI.js
  src/applications/caregivers/definitions/content.js
Labels: caregivers, design, front end

#14615 added print functionality for 1995 confirmation page
  src/applications/edu-benefits/1995/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1995/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14625 Checked tuition values for NaN value updated to N/A
  src/applications/gi/utils/helpers.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14631 updated styling based on UX feedback for 13938
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/components/search/KeywordSearch.jsx
  src/applications/gi/sass/partials/_gi-search-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14646 Add page break for print view 1995 confirmation page
  src/applications/edu-benefits/1995/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/sass/edu-benefits.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14619 Remove edu_benefits_stem_scholarship feature flag
  src/applications/edu-benefits/components/EducationWizard.jsx
  src/applications/edu-benefits/selectors/educationWizard.js
  src/applications/edu-benefits/tests/components/EducationWizard.unit.spec.jsx
  src/applications/gi/tests/data/feature-toggles.json
  src/platform/testing/local-dev-mock-api/common.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#14645 Add tags for each LC template
  src/site/includes/tags.drupal.liquid
  src/site/layouts/checklist.drupal.liquid
  src/site/layouts/faq_multiple_q_a.drupal.liquid
  src/site/layouts/media_list_images.drupal.liquid
  src/site/layouts/media_list_videos.drupal.liquid
  src/site/layouts/q_a.drupal.liquid
  src/site/layouts/step_by_step.drupal.liquid
  src/site/layouts/support_resources_detail_page.drupal.liquid
  src/site/stages/build/drupal/graphql/taxonomy-fragments/termTopics.taxonomy.graphql.js
Labels: VSA, front end

#14648 Add new cerner logic for cerner cta component
  src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/App/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.js
  src/platform/user/selectors.js
  src/platform/utilities/cerner/index.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA, front end

#14657 remove prod flag for comparison tool updates
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/components/search/LandingPageTypeOfInstitutionFilter.jsx
  src/applications/gi/components/search/OnlineClassesFilter.jsx
  src/applications/gi/components/search/SearchResultTypeOfInstitutionFilter.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/tests/e2e/01-keyboard.cypress.spec.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#14659 15111: Modal scrollbar showing on PC Chrome/Firefox/Edge
  src/applications/gi/sass/partials/_gi-modal.scss
Labels: BAH, BAH-QA-needed

#14664 Fetch value of new My VA Dashboard 2.0 feature flag
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA

#14618 13765: Debt Letters Content for Diary Codes
  src/applications/debt-letters/components/DebtDetails.jsx
  src/applications/debt-letters/components/DebtLetterCard.jsx
  src/applications/debt-letters/const/diary-codes/index.js
  src/applications/debt-letters/sass/debt-letters.scss
Labels: VSA

#14670 Add audience topics
  src/site/includes/tags.drupal.liquid
  src/site/stages/build/drupal/graphql/fragments.graphql.js
  src/site/stages/build/drupal/graphql/paragraph-fragments/audienceTopics.paragraph.graphql.js
  src/site/stages/build/drupal/graphql/taxonomy-fragments/audienceBeneficiaries.taxonomy.graphql.js
Labels: VSA, front end

#14683 Change syntax because liquid 🤦‍♂️
  src/site/includes/related-information.drupal.liquid
Labels: VSA, front end

#14684 Only show uniq support services
  src/site/includes/related-benefit-hubs.drupal.liquid
  src/site/stages/build/drupal/graphql/supportService.graphql.js
Labels: VSA, front end

#14653 Remove gibct_search_enhancements flag
  src/applications/gi/actions/index.js
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
  src/applications/gi/tests/actions/index.unit.spec.js
  src/applications/gi/tests/components/search/KeywordSearch.unit.spec.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH, BAH-QA-needed

#14675 BDD: Hide Disability Follow Up Descriptions
  src/applications/disability-benefits/all-claims/constants.js
  src/applications/disability-benefits/all-claims/pages/newDisabilityFollowUp.js
  src/applications/disability-benefits/all-claims/submit-transformer.js
  src/applications/disability-benefits/all-claims/tests/fixtures/data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/minimal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/minimal-bdd-test.json
Labels: BDD, Disability Benefits, VSA, front end

#14698 Move all logic in profile360 to profile
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/applications/personalization/dashboard/dashboard-entry.jsx
  src/applications/personalization/profile/README.md
  src/applications/personalization/profile/actions/index.js
  src/applications/personalization/profile/actions/paymentInformation.js
  src/applications/personalization/profile/components/AccountSecurity.jsx
  src/applications/personalization/profile/components/BankInfoForm.jsx
  src/applications/personalization/profile/components/ContactInformation.jsx
  src/applications/personalization/profile/components/ContactInformationExplanation.jsx
  src/applications/personalization/profile/components/DowntimeBanner.jsx
  src/applications/personalization/profile/components/LoadFail.jsx
  src/applications/personalization/profile/components/MilitaryInformation.jsx
  src/applications/personalization/profile/components/PaymentInformationBlocked.jsx
  src/applications/personalization/profile/components/PaymentInformationEditModalError.jsx
  src/applications/personalization/profile/components/Profile2Router.jsx
  src/applications/personalization/profile/components/Profile2Wrapper.jsx
  src/applications/personalization/profile/components/REMOVAL_PROFILE_NOTES
  src/applications/personalization/profile/components/connected-apps/actions/index.js
  src/applications/personalization/profile/components/direct-deposit/DirectDeposit.jsx
  src/applications/personalization/profile/components/direct-deposit/DirectDepositContent.jsx
  src/applications/personalization/profile/components/personal-information/PersonalInformation.jsx
  src/applications/personalization/profile/constants.js
  src/applications/personalization/profile/manifest.json
  src/applications/personalization/profile/profile-entry.jsx
  src/applications/personalization/profile/reducers/index.js
  src/applications/personalization/profile/sass/profile-360.scss
  src/applications/personalization/profile/sass/user-profile.scss
  src/applications/personalization/profile/selectors.js
  src/applications/personalization/profile/tests/actions/paymentInformation.unit.spec.js
  src/applications/personalization/profile/tests/components/BankInfoForm.unit.spec.jsx
  src/applications/personalization/profile/tests/components/PaymentInformationBlocked.unit.spec.jsx
  src/applications/personalization/profile/tests/components/PaymentInformationEditModalError.unit.spec.jsx
  src/applications/personalization/profile/tests/reducers/index.unit.spec.js
  src/applications/personalization/profile/tests/selectors.unit.spec.js
  src/applications/personalization/profile/tests/service-history.pact.spec.js
  src/applications/personalization/profile/tests/unit-test-helpers.js
  src/applications/personalization/profile/tests/util/index.unit.spec.js
  src/applications/personalization/profile/util/connected-apps.js
  src/applications/personalization/profile/util/index.js
  src/applications/personalization/profile360/constants/index.js
  src/applications/personalization/profile360/manifest.json
  src/applications/registry.json
Labels: VSA, front end

#14706 [Development] Fix post-HLR wizard focus management
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/content/contestedIssues.jsx
  src/applications/disability-benefits/996/helpers.js
Labels: 508/Accessibility, Disability Benefits, HLR, VSA, front end

#14720 [Development] Claim status tool upload fixes
  src/applications/claims-status/components/AddFilesForm.jsx
  src/applications/claims-status/tests/components/AddFilesForm.unit.spec.jsx
  src/applications/claims-status/utils/validations.js
Labels: Disability Benefits, VSA, bug, claim status, front end

#14711 Add benefit hubs and rearrange ending components for LC templates
  src/site/includes/benefit-hubs-links.drupal.liquid
  src/site/includes/how-do-you-rate.drupal.liquid
  src/site/includes/related-benefit-hubs.drupal.liquid
  src/site/includes/related-information.drupal.liquid
  src/site/includes/tags.drupal.liquid
  src/site/layouts/checklist.drupal.liquid
  src/site/layouts/faq_multiple_q_a.drupal.liquid
  src/site/layouts/media_list_images.drupal.liquid
  src/site/layouts/media_list_videos.drupal.liquid
  src/site/layouts/q_a.drupal.liquid
  src/site/layouts/step_by_step.drupal.liquid
  src/site/layouts/support_resources_detail_page.drupal.liquid
  src/site/paragraphs/contact_information.drupal.liquid
  src/site/paragraphs/lists_of_links.drupal.liquid
  src/site/stages/build/drupal/graphql/faqMultipleQa.graphql.js
  src/site/stages/build/drupal/graphql/fragments.graphql.js
  src/site/stages/build/drupal/graphql/nodeChecklist.graphql.js
  src/site/stages/build/drupal/graphql/nodeMediaListImages.graphql.js
  src/site/stages/build/drupal/graphql/nodeMediaListVideos.graphql.js
  src/site/stages/build/drupal/graphql/nodeQa.graphql.js
  src/site/stages/build/drupal/graphql/nodeStepByStep.graphql.js
  src/site/stages/build/drupal/graphql/nodeSupportResourcesDetailPage.graphql.js
  src/site/stages/build/drupal/graphql/paragraph-fragments/contactInformation.paragraph.graphql.js
  src/site/stages/build/drupal/graphql/paragraph-fragments/emailContact.paragraph.graphql.js
  src/site/stages/build/drupal/graphql/paragraph-fragments/phoneNumber.paragraph.graphql.js
Labels: VSA, front end

#14719 Adds a script for diff'ing transformed HTML against graphql-based HTML
  package.json
  script/cms/compare.sh
  script/cms/diff.sh
Labels: cms-transformer

#14506 14420: Responsive tables SHOULD have HTML updated for better mobile presentation
  src/applications/gi/components/ResponsiveTable.jsx
  src/applications/gi/components/profile/SchoolLocations.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
  src/applications/gi/tests/components/ResponsiveTable.unit.spec.jsx
  src/applications/gi/tests/components/profile/SchoolLocations.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#14693 14633 move chp31 wizard
  src/applications/static-pages/static-pages-entry.js
  src/applications/vre/28-1900/config/constants.js
  src/applications/vre/28-1900/config/form.js
  src/applications/vre/28-1900/constants.js
  src/applications/vre/28-1900/containers/App.jsx
  src/applications/vre/28-1900/containers/WizardContainer.jsx
  src/applications/vre/28-1900/tests/e2e/authenticated.cypress.spec.js
  src/applications/vre/28-1900/tests/e2e/unauthenticated.cypress.spec.js
  src/applications/vre/28-1900/wizard/app.js
  src/applications/vre/28-1900/wizard/chapter31Wizard.jsx
  src/applications/vre/28-1900/wizard/pages/index.js
  src/applications/vre/28-1900/wizard/pages/other/isOther.jsx
  src/applications/vre/28-1900/wizard/pages/pageList.js
  src/applications/vre/28-1900/wizard/pages/service-member/01-noHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/02-noVaMemorandum.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/02-yesVaMemorandum.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-noIDES.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-notInterestedInHelp.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-yesIDES.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-yesInterestedInHelp.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/01-noHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/01-yesHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/02-noDisabilityRating.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/03-noActiveDutySeparation.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/03-yesActiveDutySeparation.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/04-notInterestedInEmploymentHelp.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/04-yesInterestedInEmploymentHelp.jsx
  src/applications/vre/components/GetFormHelp.jsx
Labels: VSA

#14095 [DEVELOPMENT|AXE-CORE] Fix ArrayField header level
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
  src/platform/forms-system/src/js/review/ArrayField.jsx
  src/platform/forms-system/test/js/review/ArrayField.unit.spec.jsx
  src/platform/site-wide/sass/shame.scss
Labels: 508/Accessibility, Disability Benefits, VSA

#14732 Remove unused bread layers
  src/site/layouts/basic_landing_page.drupal.liquid
Labels: VSA, front end

#14730 12421 chp31 static vet info unit tests
  src/applications/vre/28-1900/config/form.js
  src/applications/vre/28-1900/tests/components/veteranInformationViewComponent.unit.spec.jsx
Labels: VSA

#14739 Bah 14420 CSS Table Fix
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#14738 MC - Switch dash for 'non-breaking hyphen'...
  src/applications/registry.json
Labels: VSA

#14681 Don't display empty review pages
  src/platform/forms-system/src/js/helpers.js
  src/platform/forms-system/src/js/review/ObjectField.jsx
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
  src/platform/forms-system/test/js/helpers.unit.spec.js
  src/platform/forms-system/test/js/review/ReviewCollapsibleChapter.unit.spec.jsx
Labels: BAH

#14705 13764: Info alerts for debt letters
  src/applications/debt-letters/components/DebtDetails.jsx
  src/applications/debt-letters/components/DebtLetterCard.jsx
  src/applications/debt-letters/const/diary-codes/index.js
  src/applications/debt-letters/tests/DebtLetterCard.unit.spec.js
  src/applications/debt-letters/tests/actions.unit.spec.js
  src/applications/debt-letters/utils/mockResponses.js
Labels: VSA

#14756 send keepalive request without a pre-flight
  src/platform/utilities/sso/keepAliveSSO.js
Labels: bug

#14688 15163: DebtRes Ch1 - Veteran Information
  src/applications/financial-status-report/actions/index.js
  src/applications/financial-status-report/components/ErrorMessage.jsx
  src/applications/financial-status-report/components/GetFormHelp.jsx
  src/applications/financial-status-report/components/VeteranInfoBox.jsx
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/constants/index.js
  src/applications/financial-status-report/containers/App.jsx
  src/applications/financial-status-report/containers/IntroductionPage.jsx
  src/applications/financial-status-report/reducers/index.js
  src/applications/financial-status-report/routes.jsx
  src/applications/financial-status-report/schema/5655-schema.json
  src/applications/financial-status-report/schema/5655-ui.js
  src/applications/financial-status-report/tests/ErrorMessage.unit.spec.jsx
  src/applications/financial-status-report/tests/fsr-5655.unit.spec.js
  src/applications/personalization/dashboard/helpers.jsx
Labels: VSA

#14763 14420: Correct HR styling
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH

#14765 Update telephone numbers in eBenefits applications
  src/applications/disability-benefits/686c-674/config/helpers.js
  src/applications/personalization/rated-disabilities/components/RatedDisabilityList.jsx
  src/applications/personalization/rated-disabilities/components/TotalRatingStates.jsx
  src/applications/personalization/view-dependents/layouts/helpers.jsx
Labels: VSA

#14778 Minor content tweaks
  src/applications/resources-and-support/components/SearchBar.jsx
  src/applications/resources-and-support/components/SearchResult.jsx
  src/site/includes/support_resources_search_bar.drupal.liquid
Labels: VSA, front end

#14779 Update va311 numbers
  package.json
  src/applications/ask-a-question/form/review/error/CallMyVA311.js
  src/applications/caregivers/tests/e2e/1010cg.cypress.spec.js
  src/applications/disability-benefits/686c-674/config/helpers.js
  src/applications/disability-benefits/view-payments/utils.js
  src/applications/personalization/profile/components/connected-apps/AdditionalInfoSections.jsx
  src/applications/personalization/profile/tests/components/alerts/NotInMPIError.unit.spec.jsx
  src/applications/personalization/rated-disabilities/components/RatedDisabilityList.jsx
  src/applications/personalization/rated-disabilities/components/TotalRatingStates.jsx
  src/applications/personalization/view-dependents/layouts/helpers.jsx
  src/applications/validate-mhv-account/components/errors/NeedsVAPatient.jsx
  src/platform/landing-pages/header-footer-data.json
  src/platform/site-wide/cta-widget/components/messages/NeedsVAPatient.jsx
  src/platform/site-wide/user-nav/components/HelpMenu.jsx
  src/platform/static-data/footer-links.json
  yarn.lock
Labels: VSA, front end

#14789 15163: Review Veteran Info
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/schema/5655-schema.json
  src/applications/financial-status-report/schema/5655-ui-schema.js
  src/applications/financial-status-report/schema/5655-ui.js
Labels: VSA

#14790 Dont skip e2e tests for caregivers and version bump formation-react
  package.json
  src/applications/caregivers/tests/e2e/1010cg.cypress.spec.js
  yarn.lock
Labels: VSA, front end
