Repository department-of-veterans-affairs/vets-website, pull requests merged in 2020-12, with the labels that each got.

#15018 Send lat/long and radius to FL api
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/api/LocatorApi.js
  src/applications/facility-locator/config.js
  src/applications/facility-locator/containers/FacilitesMap.jsx
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/tests/api-url-parameters.unit.spec.js
Labels: VSA, facility locator, front end

#15111 CT - Remove prod flags for app reload fix
  src/applications/gi/reducers/eligibility.js
  src/applications/gi/reducers/search.js
Labels: BAH

#15124 [Development] CST: Add password field for encrypted PDF
  src/applications/claims-status/actions/index.jsx
  src/applications/claims-status/components/AddFilesForm.jsx
  src/applications/claims-status/components/UploadStatus.jsx
  src/applications/claims-status/reducers/uploads.js
  src/applications/claims-status/tests/actions.unit.spec.js
  src/applications/claims-status/tests/components/AddFilesForm.unit.spec.jsx
  src/applications/claims-status/tests/components/AdditionalEvidencePage.unit.spec.jsx
  src/applications/claims-status/tests/components/DocumentRequestPage.unit.spec.jsx
  src/applications/claims-status/tests/reducers/uploads.unit.spec.jsx
Labels: Ancillary-Forms, Disability Benefits, VSA, claim status, front end

#15129 15483 accessibility fix
  src/applications/vre/28-1900/config/chapters/communication-preferences/communicationPreferences.js
Labels: VSA

#15136 Mc chp31 orientation ii
  src/applications/vre/28-1900/containers/App.jsx
  src/applications/vre/28-1900/containers/IntroductionPage.jsx
  src/applications/vre/28-1900/containers/OrientationWizardContainer.jsx
  src/applications/vre/28-1900/containers/WizardContainer.jsx
  src/applications/vre/28-1900/orientation/OrientationApp.jsx
  src/applications/vre/28-1900/orientation/StepComponent.jsx
  src/applications/vre/28-1900/orientation/utils.js
  src/applications/vre/28-1900/sass/28-1900-chapter-31.scss
  src/applications/vre/28-1900/tests/e2e/authenticated.cypress.spec.js
  src/applications/vre/28-1900/tests/e2e/unauthenticated.cypress.spec.js
  src/applications/vre/28-1900/wizard/pages/index.js
  src/applications/vre/28-1900/wizard/pages/other/isOther.jsx
  src/applications/vre/28-1900/wizard/pages/pageList.js
  src/applications/vre/28-1900/wizard/pages/service-member/01-noHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/01-yesHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/02-noVaMemorandum.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/02-yesVaMemorandum.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-noIDES.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-notInterestedInHelp.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-yesIDES.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-yesInterestedInHelp.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/isServiceMember.jsx
  src/applications/vre/28-1900/wizard/pages/start.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/01-noHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/01-yesHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/02-disabilityRating.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/02-noDisabilityRating.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/03-noActiveDutySeparation.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/03-yesActiveDutySeparation.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/04-notInterestedInEmploymentHelp.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/04-yesInterestedInEmploymentHelp.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/isVeteran.jsx
Labels: 508/Accessibility, VSA

#15013 Improves Sentry logging on the keepalive endpoint
  src/platform/utilities/sso/keepAliveSSO.js
Labels: front end, identity

#15134 Downtime content update
  src/applications/caregivers/containers/IntroductionPage.jsx
Labels: VSA, caregivers, enhancement, front end

#15125 Restore geolocation via browser for FL
  src/applications/facility-locator/containers/FacilitesMap.jsx
Labels: VSA, facility locator, front end

#15152 CT - VET TEC search fix
  src/applications/gi/containers/VetTecSearchPage.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#15156 Add search ignore list for rs search
  src/applications/resources-and-support/constants/index.js
  src/applications/resources-and-support/hooks/useGetSearchResults.js
Labels: VSA, front end

#15143 Alert boxes MUST NOT have a role="alert" unless they are announcing high priority information
  src/applications/edu-benefits/10203/content/activeDuty.jsx
Labels: BAH

#15110 Srsuddath 3 typeahead analytics
  .gitignore
  src/applications/search/containers/SearchApp.jsx
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
  src/platform/site-wide/user-nav/components/Typeahead.jsx
  src/platform/site-wide/user-nav/tests/components/SearchMenu.unit.spec.jsx
  src/platform/site-wide/user-nav/tests/components/Typeahead.unit.spec.jsx
Labels: VSA, front end

#15165 13017 - Remove duplicate text
  src/applications/disability-benefits/686c-674/config/chapters/add-a-child/child-place-of-birth/childStatusDescription.jsx
Labels: VSA

#15172 Update analytics
  src/applications/resources-and-support/components/SearchBar.jsx
  src/applications/resources-and-support/components/SearchResult.jsx
  src/applications/resources-and-support/hooks/useGetSearchResults.js
Labels: VSA, front end

#15186 Make sure words are lower cased before checking ignore list
  src/applications/resources-and-support/constants/index.js
  src/applications/resources-and-support/hooks/useGetSearchResults.js
Labels: VSA, front end

#15179 [Development] Fix empty array preventing submission
  src/applications/disability-benefits/all-claims/pages/vaMedicalRecords.js
  src/applications/disability-benefits/all-claims/submit-transformer.js
  src/applications/disability-benefits/all-claims/tests/fixtures/data/secondary-new-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/maximal-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/secondary-new-test.json
  src/applications/disability-benefits/all-claims/tests/pages/vaMedicalRecords.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/submit-transformer.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/validations.unit.spec.js
  src/applications/disability-benefits/all-claims/validations.js
Labels: 526, BDD, Disability Benefits, VSA, front end

#15163 16821 update chp36 breadcrumb
  src/applications/registry.json
Labels: VSA

#15194 10279 redundant title text
  src/applications/personalization/rated-disabilities/components/RatedDisabilitiesSidebar.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsSidebar/ViewDependentsSidebarBlockStates/ViewDependentSidebarBlockStates.jsx
Labels: VSA

#15193 [526] Change Confirmation Page submittedAt to timestamp
  src/applications/disability-benefits/all-claims/components/ConfirmationPoll.jsx
Labels: 526, BDD, Disability Benefits, VSA, bug, front end

#15211 bah-code-reviewers as codeowners for 0993
  .github/CODEOWNERS
Labels: BAH

#15212 Updates Session Timeout Modal content
  src/platform/user/authentication/components/SessionTimeoutModal.jsx
Labels: 508/Accessibility, front end, identity

#15218 Fix mega menu bug
  src/platform/site-wide/mega-menu/containers/Main.jsx
Labels: BAH

#15126 Default search area for secondary searches
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/constants/index.js
  src/applications/facility-locator/containers/FacilitesMap.jsx
Labels: VSA, facility locator, front end

#15231 Fix validation error in health_care_local_facility nodes
  src/site/stages/build/process-cms-exports/schemas/input/node-health_care_local_facility.js
Labels: cms-transformer

#15181 Update typeahead Event Logging
  src/applications/search/containers/SearchApp.jsx
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: VSA, front end

#15119 HLR: Gate Users with No Address
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/content/contestableIssueAlerts.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
Labels: Disability Benefits, HLR, VSA, front end

#15230 15545 scaffold view representative
  src/applications/personalization/view-representative/actions/index.js
  src/applications/personalization/view-representative/app-entry.jsx
  src/applications/personalization/view-representative/components/SideBar.jsx
  src/applications/personalization/view-representative/components/ViewRepresentativeBody.jsx
  src/applications/personalization/view-representative/components/ViewRepresentativeDetails.jsx
  src/applications/personalization/view-representative/components/ViewRepresentativeLayout.jsx
  src/applications/personalization/view-representative/containers/ViewRepresentativeApp.jsx
  src/applications/personalization/view-representative/manifest.json
  src/applications/personalization/view-representative/reducers/index.js
  src/applications/personalization/view-representative/routes.jsx
  src/applications/personalization/view-representative/sass/view-representative.scss
  src/applications/personalization/view-representative/static/representative-dummy.js
  src/applications/personalization/view-representative/tests/view-representative.cypress.spec.js
  src/applications/personalization/view-representative/util/index.js
  src/applications/registry.json
Labels: VSA

#15225 [Development] Update 526 new condition page
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
  src/applications/disability-benefits/all-claims/content/addDisabilities.jsx
  src/applications/disability-benefits/all-claims/pages/addDisabilities.js
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
Labels: 508/Accessibility, 526, BDD, Disability Benefits, VSA, front end

#15227 Remove form1995EduUpdates feature flag
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#15210 1995 content updates
  src/applications/edu-benefits/1995/config/chapters.js
  src/applications/edu-benefits/1995/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1995/pages/newSchool.js
  src/applications/edu-benefits/1995/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/pages/oldSchool.js
Labels: BAH

#15245 update view payments breadcrumb
  src/applications/registry.json
Labels: VSA

#15264 Fix typo
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/UnauthContent/index.js
Labels: VSA, front end

#15272 [Development] Add analytics to HLR wizard
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/content/DownloadLink.jsx
  src/applications/disability-benefits/996/wizard/pages/claimType.jsx
  src/applications/disability-benefits/996/wizard/pages/legacyChoice.jsx
  src/applications/disability-benefits/996/wizard/pages/legacyNo.jsx
  src/applications/disability-benefits/996/wizard/pages/legacyYes.jsx
  src/applications/disability-benefits/996/wizard/pages/other.jsx
Labels: Disability Benefits, HLR, VSA, front end

#15267 HLR: Bugfix for No Address Gate
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
Labels: Disability Benefits, HLR, VSA, front end

#15237 Fix event breadcrumbs
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/includes/breadcrumbs.drupal.liquid
  src/site/layouts/event.drupal.liquid
Labels: VSA, front end

#15241 1990n: Form Content Updates #16879
  src/applications/edu-benefits/1990n/config/form.js
  src/applications/edu-benefits/1990n/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990n/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/definitions/toursOfDuty.jsx
  src/applications/edu-benefits/pages/schoolSelection.js
Labels: BAH, BAH-QA-needed

#15284 [Development] Add 526 confirmation print button
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/content/confirmation-page.jsx
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
Labels: 526, BDD, Disability Benefits, VSA, front end

#15293 Set focus on search result header and make search area button assistive
  src/applications/facility-locator/containers/FacilitesMap.jsx
  src/applications/facility-locator/utils/SearchAreaControl.js
Labels: VSA, facility locator, front end

#15295 Fix
  src/site/paragraphs/table.drupal.liquid
Labels: VSA, front end

#15268 0994: Form Content Updates #16721
  src/applications/edu-benefits/0994/config/form.js
  src/applications/edu-benefits/0994/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/0994/pages/contactInformation.js
  src/applications/edu-benefits/0994/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: BAH

#15274 0994: Add ability to print confirmation page #16838
  src/applications/edu-benefits/0994/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/0994/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/10203/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/10203/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/1995/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1995/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/components/ConfirmationPage.jsx
  src/applications/edu-benefits/tests/components/ConfirmationPage.unit.spec.jsx
Labels: BAH

#15291 Remove navigation compass from Facility Locator map
  src/applications/facility-locator/containers/FacilitesMap.jsx
  src/applications/facility-locator/sass/facility-locator.scss
Labels: VSA, facility locator, front end

#15247 16729: 1990 Content update
  src/applications/edu-benefits/1990/config/form.js
  src/applications/edu-benefits/1990/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: BAH

#15222 16898: 5495 Content update.
  src/applications/edu-benefits/5495/config/form.js
  src/applications/edu-benefits/5495/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/5495/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/definitions/sponsorFullName.js
Labels: BAH

#15315 [Development] Various HLR fixes
  src/applications/disability-benefits/996/actions/index.js
  src/applications/disability-benefits/996/components/ContactInformation.jsx
  src/applications/disability-benefits/996/components/ReviewDescription.jsx
  src/applications/disability-benefits/996/components/VeteranInformation.jsx
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/content/contestableIssueAlerts.jsx
  src/applications/disability-benefits/996/pages/informalConference.js
  src/applications/disability-benefits/996/tests/components/ContactInformation.unit.spec.jsx
  src/applications/disability-benefits/996/tests/components/ReviewDescription.unit.spec.jsx
  src/applications/disability-benefits/996/tests/content/veteranInformation.unit.spec.jsx
  src/applications/disability-benefits/996/tests/hlr.cypress.spec.js
  src/applications/disability-benefits/996/wizard/pages/legacyNo.jsx
Labels: Disability Benefits, HLR, VSA, front end

#15258 13015 686 accessible review labels
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/current-spouse-marriage-history-details/currentSpouseMarriageHistoryDetails.js
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/veteran-marriage-history-details/veteranMarriageHistoryDetails.js
  src/applications/disability-benefits/686c-674/config/form.js
  src/applications/disability-benefits/686c-674/config/helpers.js
  src/applications/disability-benefits/686c-674/config/location-schema.js
Labels: 508/Accessibility, VSA

#15312 16621 downtime chp36
  src/applications/vre/28-8832/config/form.js
  src/applications/vre/28-8832/containers/IntroductionPage.jsx
Labels: VSA

#15327 Add caregivers to HCA CodeOwners
  .github/CODEOWNERS
Labels: VSA, caregivers, enhancement, front end

#15330 BDD/526: Rated Disabilities Messaging Tweaks
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/supportingEvidenceOrientation.jsx
  src/applications/disability-benefits/all-claims/content/supportingEvidenceOrientationBDD.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 526, BDD, Disability Benefits, VSA, front end

#15326 Resolve 508 Issue with Table Hierarchy on Review Page
  src/applications/hca/components/DemographicField.jsx
Labels: 508/Accessibility, VSA, bug, caregivers, front end

#15299 17117 update chp36 feature toggle
  src/applications/static-pages/vre-chapter36/Chapter36CTA.js
  src/platform/site-wide/cta-widget/helpers.js
Labels: VSA

#15350 Add hyphen to regex for web build
  src/site/stages/build/drupal/assets.js
Labels: cms

#15325 0994 - Update PhoneEmailViewField.jsx
  src/applications/edu-benefits/0994/components/PhoneEmailViewField.jsx
Labels: BAH

#15322 Added BAH as owner of edu-benefits
  .github/CODEOWNERS
Labels: BAH

#15339 1990n: Add ability to print confirmation page #16880
  src/applications/edu-benefits/1990n/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990n/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/1995/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1995/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/components/ConfirmationPage.jsx
  src/applications/edu-benefits/tests/components/ConfirmationPage.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#15301 1990e: Form Content Updates#16877
  src/applications/edu-benefits/1990e/config/form.js
  src/applications/edu-benefits/1990e/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990e/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#15219 GIBCT Redesign: Create development sandbox #16818
  .github/CODEOWNERS
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/config.js
  src/applications/gi-sandbox/containers/GiBillApp.jsx
  src/applications/gi-sandbox/containers/LandingPage.jsx
  src/applications/gi-sandbox/gi-entry.jsx
  src/applications/gi-sandbox/manifest.json
  src/applications/gi-sandbox/routes.jsx
  src/applications/gi-sandbox/sass/gi-sandbox.scss
  src/applications/registry.json
Labels: BAH, BAH-QA-needed

#15357 CST: Text Change for No Claims (don't direct to eBenefits)
  src/applications/claims-status/components/NoClaims.jsx
Labels: Disability Benefits, VSA, claim status, front end

#15348 Fix - Instruction in empty result-list missing required Facility-type…
  src/applications/facility-locator/components/SearchResultMessage.jsx
  src/applications/facility-locator/tests/components/__snapshots__/SearchResultMessage.unit.spec.jsx.mocha-snapshot
Labels: VSA, facility locator, front end

#15262 5490 content update
  src/applications/edu-benefits/5490/config/form.js
  src/applications/edu-benefits/5490/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/5490/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/definitions/postHighSchoolTrainings.js
Labels: BAH

#15309 0993 content updates
  src/applications/edu-benefits/0993/config/form.js
  src/applications/edu-benefits/0993/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/0993/containers/IntroductionPage.jsx
Labels: BAH

#15373 Fix - When "Search this area" button is introduced, it must be announced and available to assistive technology
  src/applications/facility-locator/containers/FacilitesMap.jsx
Labels: VSA, facility locator, front end

#15333 16899 and 16898 Styling based off UX feedback update
  src/applications/edu-benefits/5495/config/form.js
  src/applications/edu-benefits/5495/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/5495/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: BAH

#15376 Make Search this area button responsive
  src/applications/facility-locator/sass/facility-locator.scss
Labels: VSA, facility locator, front end

#15347 Update downshift implementation
  package.json
  src/platform/site-wide/sass/shame.scss
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
  src/platform/site-wide/user-nav/tests/components/SearchMenu.unit.spec.jsx
  yarn.lock
Labels: VSA, front end

#15378 Fix - When focus moves to the map, the focus halo should be visible
  src/applications/facility-locator/containers/FacilitesMap.jsx
  src/applications/facility-locator/sass/facility-locator.scss
Labels: VSA, facility locator, front end

#15360 1990e: Add ability to print confirmation page#16878
  src/applications/edu-benefits/1990e/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990e/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: BAH

#15383 5490: Add ability to print confirmation page#16895
  src/applications/edu-benefits/5490/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/5490/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#15349 [Development] HLR: Fix a11y issues
  src/applications/disability-benefits/996/components/EligibleIssuesWidget.jsx
  src/applications/disability-benefits/996/components/SelectArrayItemsWidget.jsx
  src/applications/disability-benefits/996/content/contestedIssues.jsx
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/pages/contestedIssues.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/contestedIssues.unit.spec.jsx
Labels: 508/Accessibility, Disability Benefits, HLR, VSA, front end

#15391 [Development] HLR: Make informal conference time selection more accessible
  src/applications/disability-benefits/996/config/submit-transformer.js
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/content/ScheduleTimesReviewField.jsx
  src/applications/disability-benefits/996/pages/informalConference.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/content/InformalConference.unit.spec.jsx
  src/applications/disability-benefits/996/tests/content/ScheduleTimesReviewField.unit.spec.jsx
  src/applications/disability-benefits/996/tests/fixtures/data/maximal-test.json
  src/applications/disability-benefits/996/tests/schema/initialData.js
  src/applications/disability-benefits/996/tests/validations/validations.unit.spec.js
  src/applications/disability-benefits/996/validations/index.js
Labels: 508/Accessibility, Disability Benefits, HLR, VSA, front end

#15392 [Development] Make benefit office link more accessible
  src/applications/disability-benefits/996/wizard/pages/other.jsx
Labels: 508/Accessibility, Disability Benefits, HLR, VSA, front end

#15395 [Development] HLR: Add a11y ref to start button
  src/applications/disability-benefits/996/wizard/pages/legacyNo.jsx
Labels: 508/Accessibility, Disability Benefits, HLR, VSA, front end

#15387 Update typeahead to meet accessibility needs
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
  src/platform/site-wide/user-nav/tests/components/SearchMenu.unit.spec.jsx
Labels: VSA, front end

#15396 17557 chp36 content updates
  src/applications/vre/28-8832/components/GetFormHelp.jsx
  src/applications/vre/28-8832/config/chapters/claimant-information/claimantAddress.js
  src/applications/vre/28-8832/config/chapters/status-selection/status.js
  src/applications/vre/28-8832/config/chapters/veteran-information/veteranInformation.js
  src/applications/vre/28-8832/containers/ConfirmationPage.jsx
  src/applications/vre/28-8832/containers/IntroductionPage.jsx
  src/applications/vre/28-8832/tests/e2e/dependent-workflow.cypress.spec.js
  src/applications/vre/28-8832/tests/e2e/veteran-workflow-not-logged-in.cypress.spec.js
  src/applications/vre/definitions/profileAddress.js
Labels: VSA

#15404 DT-11453 Updating related to data source.
  src/applications/find-forms/components/SearchResult.jsx
  src/applications/find-forms/prop-types.js
Labels: front end

#15340 Edu confirmation page updates
  src/applications/edu-benefits/0994/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/0994/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/10203/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/10203/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/1990/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/1990e/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990e/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/1990n/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990n/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/1995/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1995/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/5490/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/5490/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/5495/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/5495/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/components/ConfirmationPage.jsx
  src/applications/edu-benefits/components/ConfirmationPageContent.jsx
  src/applications/edu-benefits/tests/components/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/tests/components/ConfirmationPageContent.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#15401 Update PW transformers/outputs/inputs to pass the cms-export build
  src/site/stages/build/process-cms-exports/schemas/input/node-support_resources_detail_page.js
  src/site/stages/build/process-cms-exports/schemas/input/paragraph-checklist_item.js
  src/site/stages/build/process-cms-exports/schemas/input/paragraph-q_a_group.js
  src/site/stages/build/process-cms-exports/schemas/input/taxonomy_term-products.js
  src/site/stages/build/process-cms-exports/schemas/output/node-basic_landing_page.js
  src/site/stages/build/process-cms-exports/schemas/output/node-faq_multiple_q_a.js
  src/site/stages/build/process-cms-exports/schemas/output/node-support_resources_detail_page.js
  src/site/stages/build/process-cms-exports/schemas/output/paragraph-alert.js
  src/site/stages/build/process-cms-exports/schemas/output/paragraph-checklist.js
  src/site/stages/build/process-cms-exports/schemas/output/paragraph-checklist_item.js
  src/site/stages/build/process-cms-exports/schemas/output/paragraph-q_a_group.js
  src/site/stages/build/process-cms-exports/schemas/output/taxonomy_term-products.js
  src/site/stages/build/process-cms-exports/transformers/node-basic_landing_page.js
  src/site/stages/build/process-cms-exports/transformers/node-faq_multiple_q_a.js
  src/site/stages/build/process-cms-exports/transformers/node-support_resources_detail_page.js
  src/site/stages/build/process-cms-exports/transformers/paragraph-alert.js
  src/site/stages/build/process-cms-exports/transformers/paragraph-checklist_item.js
  src/site/stages/build/process-cms-exports/transformers/paragraph-q_a_group.js
  src/site/stages/build/process-cms-exports/transformers/taxonomy_term-products.js
Labels: VSA, front end

#15408 [Development] Prevent legend wrapping alert
  src/applications/disability-benefits/996/pages/contestedIssues.js
Labels: 508/Accessibility, Disability Benefits, HLR, VSA, front end

#15413 Correct certification for veteran on 1010cg
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
Labels: bug, caregivers, content

#15412 0993 print updates
  src/applications/edu-benefits/0993/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/0993/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/0993/tests/e2e/00.0993-opt-out.e2e.spec.js
Labels: BAH

#15415 Typeahead Screen Reader Rework - 16965
  src/applications/search/containers/SearchApp.jsx
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: VSA, front end

#15420 [Development] Enable HLR e2e tests
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/tests/fixtures/mocks/user.json
  src/applications/disability-benefits/996/tests/hlr.cypress.spec.js
Labels: 508/Accessibility, Disability Benefits, HLR, VSA, front end

#15139 [Development] HLR no issue content changes
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/content/GetFormHelp.jsx
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/content/OfficeForReview.jsx
  src/applications/disability-benefits/996/content/contestedIssues.jsx
  src/applications/disability-benefits/996/wizard/pages/other.jsx
Labels: Disability Benefits, HLR, VSA, front end

#15427 Add R&S to sitemap
  src/applications/registry.json
  src/site/stages/build/drupal/page.js
  src/site/stages/build/plugins/create-resources-and-support-section.js
Labels: VSA, front end

#15431 Add new sorting for r&s search
  src/applications/resources-and-support/hooks/useGetSearchResults.js
Labels: VSA, front end

#15432 [Development] HLR: Accessibility fixes
  src/applications/disability-benefits/996/components/ContactInformation.jsx
  src/applications/disability-benefits/996/components/EligibleIssuesWidget.jsx
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/content/contestedIssues.jsx
  src/applications/disability-benefits/996/pages/contactInformation.js
  src/applications/disability-benefits/996/tests/components/contestedIssues.unit.spec.jsx
  src/applications/disability-benefits/996/wizard/pages/legacyChoice.jsx
Labels: 508/Accessibility, Disability Benefits, HLR, VSA, front end

#15437 Add escape early and proper onsubmit handler
  src/applications/resources-and-support/components/SearchBar.jsx
Labels: VSA, front end

#15430 Update analytics for search results page
  src/applications/search/containers/SearchApp.jsx
Labels: VSA, front end

#15394 Release new facility locator map to production
  package.json
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/routes.jsx
  src/applications/facility-locator/tests/e2e/gaEvents.cypress.spec.js
  src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js
  src/applications/facility-locator/tests/e2e/search.cypress.spec.js
  src/applications/facility-locator/utils/helpers.jsx
  src/platform/testing/e2e/cypress/support/commands/index.js
  yarn.lock
Labels: VSA, facility locator, front end

#15428 Content updates and turn on view payments and chp36 for prod UAT.
  src/applications/disability-benefits/view-payments/components/view-payments-lists/ViewPaymentsLists.jsx
  src/applications/disability-benefits/view-payments/components/view-payments-lists/helpers.js
  src/applications/disability-benefits/view-payments/tests/e2e/view-payments.cypress.spec.js
  src/applications/registry.json
  src/applications/static-pages/view-payment-history/ViewPaymentHistoryCTA.js
  src/applications/vre/28-8832/containers/ConfirmationPage.jsx
  src/applications/vre/28-8832/tests/e2e/dependent-workflow.cypress.spec.js
  src/applications/vre/28-8832/tests/e2e/veteran-workflow-not-logged-in.cypress.spec.js
Labels: VSA

#15438 17374: School Ratings: Add Google Analytics to track user interaction
  src/applications/gi/components/profile/HeadingSummary.jsx
Labels: BAH, BAH-QA-needed

#15446 STEM: Notify applicant when contacting SCO #17363
  src/applications/edu-benefits/10203/content/programDetails.jsx
  src/applications/edu-benefits/10203/pages/programDetails.js
Labels: BAH, BAH-QA-needed

#15444 Start adding DD for EDU to Profile
  src/applications/personalization/profile/components/direct-deposit/BankInfoCNP.jsx
  src/applications/personalization/profile/components/direct-deposit/BankInfoCNPv2.jsx
  src/applications/personalization/profile/components/direct-deposit/DirectDepositEDUEbenefits.jsx
  src/applications/personalization/profile/components/direct-deposit/DirectDepositV1.jsx
  src/applications/personalization/profile/components/direct-deposit/DirectDepositV2.jsx
  src/applications/personalization/profile/components/direct-deposit/DirectDepositWrapper.jsx
  src/applications/personalization/profile/components/direct-deposit/PaymentHistory.jsx
  src/applications/personalization/profile/routes.js
  src/applications/personalization/profile/selectors.js
  src/applications/personalization/profile/tests/components/direct-deposit/BankInfoCNP.unit.spec.jsx
  src/applications/personalization/profile/tests/components/direct-deposit/DirectDepositV1.unit.spec.jsx
Labels: VSA

#15455 Kelsonic 15649 basic landing page updates
  src/site/layouts/basic_landing_page.drupal.liquid
  src/site/layouts/checklist.drupal.liquid
  src/site/layouts/faq_multiple_q_a.drupal.liquid
  src/site/layouts/media_list_images.drupal.liquid
  src/site/layouts/media_list_videos.drupal.liquid
  src/site/layouts/q_a.drupal.liquid
  src/site/layouts/step_by_step.drupal.liquid
  src/site/layouts/support_resources_detail_page.drupal.liquid
  src/site/paragraphs/contact_information.drupal.liquid
  src/site/paragraphs/lists_of_links.drupal.liquid
  src/site/paragraphs/service_hours.drupal.liquid
  src/site/paragraphs/service_location.drupal.liquid
Labels: VSA, front end

#15380 Replace Community Care service type placeholder
  src/applications/facility-locator/components/SearchResultMessage.jsx
  src/applications/facility-locator/components/ServiceTypeAhead.jsx
Labels: VSA, facility locator, front end

#15463 Update income threshold link in HCA application
  src/applications/hca/helpers.jsx
Labels: VSA, bug, hca

#15468 Hotfix - Removes attachStacktrace property on Sentry
  src/platform/monitoring/sentry.js
Labels: bug, front end

#15469 Srsuddath analytics bug fixes
  src/applications/search/actions/index.js
  src/applications/search/containers/SearchApp.jsx
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: VSA, front end

#15453 EDU Form: Update misc content#17619
  src/applications/edu-benefits/0994/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990e/config/form.js
  src/applications/edu-benefits/sass/edu-benefits.scss
Labels: BAH

#15459 STEM: Create automated decision feature flag#13829 Front end
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#15441 DT-15241 fixed last revision bug.
  src/applications/find-forms/components/SearchResult.jsx
  src/applications/find-forms/constants/index.js
  src/applications/find-forms/helpers/selectors.js
  src/applications/find-forms/tests/components/SearchResult.unit.spec.jsx
Labels: VSA, front end

#15461 DT-17678 508-2 fixing ux and screen reader visibility.
  src/site/layouts/va_form.drupal.liquid
Labels: 508/Accessibility, VSA, front end

#15419 Map displays area searched, even if no results found
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/components/SearchResultMessage.jsx
  src/applications/facility-locator/config.js
  src/applications/facility-locator/containers/FacilitiesMap.jsx
  src/applications/facility-locator/reducers/searchQuery.js
  src/applications/facility-locator/routes.jsx
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/e2e/map-zoom.cypress.spec.js
  src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js
  src/applications/facility-locator/tests/e2e/search.cypress.spec.js
  src/applications/facility-locator/tests/reducers/searchQuery.unit.spec.js
  src/applications/facility-locator/utils/actionTypes.js
  src/applications/facility-locator/utils/analytics.js
Labels: VSA, facility locator, front end

#15496 Set default search radius on FL
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/constants/index.js
  src/applications/facility-locator/tests/helpers/radiusFromBoundingBox.unit.spec.js
  src/applications/facility-locator/utils/facilityDistance.js
Labels: VSA, facility locator, front end

#15407 17107 Happy path Cypress e2e test for COVID-19 vaccine prep tool
  src/applications/coronavirus-vaccination/tests/e2e/fixtures/toggle-covid-feature.json
  src/applications/coronavirus-vaccination/tests/e2e/signup.cypress.spec.js
Labels: testing
