Repository department-of-veterans-affairs/vets-website, pull requests merged in 2020-07, with the labels that each got.

#13336 Add an additional unit test for applicantInformation page in 10203
  src/applications/edu-benefits/10203/tests/pages/applicantInformation.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#13327 BDD: Gating and Exam Information Changes
  src/applications/disability-benefits/all-claims/content/claimExamsInfo.jsx
  src/applications/disability-benefits/wizard/pages/file-bdd.jsx
Labels: BDD, Disability Benefits, VSA, front end

#13344 10203 Chapter 2 and 5 Fixes
  src/applications/edu-benefits/10203/content/benefitSelection.jsx
  src/applications/edu-benefits/10203/pages/benefitSelection.js
  src/applications/edu-benefits/10203/pages/personalInformation.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13343 10203 - Chapter 3 Updates
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/content/programDetails.jsx
  src/applications/edu-benefits/10203/pages/programDetails.js
Labels: BAH

#13315 Add CernerCTA
  src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js
  src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.unit.spec.js
  src/platform/utilities/constants.js
Labels: VSA, front end

#13299 10634: Yellow Ribbon drop-downs not behaving correctly
  src/applications/gi/components/Dropdown.jsx
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/sass/gi.scss
Labels: BAH, BAH-QA-needed

#13309 Comparison tool search enhancements - fuzzy search
  src/applications/gi/actions/index.js
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#13294 convert Direct Deposit tests to use React Testing Library and MSW (Mock Service Workers)
  package.json
  src/applications/personalization/profile-2/msw-mocks.js
  src/applications/personalization/profile-2/tests/components/DirectDepositContent.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/Profile2.unit.spec.js
  src/applications/personalization/profile-2/tests/unit-test-helpers.js
  src/applications/personalization/profile360/components/BankInfoForm.jsx
  src/applications/vaos/tests/utils/eligibility.unit.spec.js
  src/platform/testing/unit/helpers.js
  yarn.lock
Labels: VSA

#13290 Updated abbrevation in OJT for better understanding
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/profile/EstimatedBenefits.jsx
  src/applications/gi/selectors/calculator.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13350 [Development] Add copy of exam info to CST sidebar
  src/applications/claims-status/components/AskVAQuestions.jsx
  src/applications/claims-status/components/CopyOfExam.jsx
  src/applications/claims-status/components/appeals-v2/AppealHelpSidebar.jsx
  src/applications/claims-status/containers/AppealInfo.jsx
  src/applications/claims-status/tests/components/appeals-v2/AppealHelpSidebar.unit.spec.jsx
  src/applications/claims-status/tests/components/appeals-v2/AppealInfo.unit.spec.jsx
Labels: Disability Benefits, VSA, claim status, front end

#13346 MDOT: Partially submitted orders error alert
  src/applications/disability-benefits/2346/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/2346/tests/ConfirmationPage.unit.spec.jsx
Labels: vsa-benefits-2

#13356 Fix loading screen issue on profile
  src/applications/personalization/profiles-wrapper/ProfilesWrapper.jsx
Labels: VSA, front end

#13362 Comparison Tool - Fuzzy Search feature flag fix
  src/applications/gi/actions/index.js
  src/applications/gi/tests/actions/index.unit.spec.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13359 [Development] Disable CST DurationCard
  src/applications/claims-status/components/appeals-v2/DurationCard.jsx
  src/applications/claims-status/tests/components/appeals-v2/Duration.unit.spec.jsx
Labels: Disability Benefits, VSA, claim status, front end

#13361 Kelsonic 10859 legacy content
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/LegacyContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/LegacyContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/LegacyContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/LegacyContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/LegacyContent/index.unit.spec.js
Labels: VSA, front end

#13319 Fix position of search button on tablets.
  README.md
  package.json
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/sass/facility-locator.scss
  yarn.lock
Labels: VSA, facility locator, front end

#13367 CT - Yellow Ribbon drop-downs not behaving correctly #10634
  src/applications/gi/components/Dropdown.jsx
  src/applications/gi/sass/gi.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13363 Text change for scholarship input label
  src/applications/gi/components/profile/CalculatorForm.jsx
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/vet-tec/VetTecCalculatorForm.jsx
  src/applications/gi/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
  src/applications/gi/containers/Modals.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13143 10167: Add aria-label to Estimate Your Benefits CalculatorResultRow
  src/applications/gi/components/profile/EstimatedBenefits.jsx
  src/applications/gi/sass/partials/_gi-profile-page.scss
Labels: BAH, BAH-QA-needed

#12838 CT-103: Remove 'eduSection103' Feature Flag #8201
  src/applications/gi/components/profile/AdditionalInformation.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/tests/components/AdditionalInformation.unit.spec.jsx
  src/applications/gi/tests/data/feature-toggles.json
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH, BAH-QA-needed

#13016 MDOT Updates + Display Custom Content on Forms
  src/applications/disability-benefits/2346/components/IntroductionPage.jsx
  src/applications/disability-benefits/2346/config/form.js
  src/applications/personalization/dashboard/helpers.jsx
  src/platform/forms-system/src/js/components/FormNav.jsx
  src/platform/forms-system/src/js/constants.js
  src/platform/forms-system/test/js/components/FormNav.unit.spec.jsx
  src/platform/forms/save-in-progress/ApplicationStatus.jsx
  src/platform/forms/save-in-progress/FormStartControls.jsx
  src/platform/forms/save-in-progress/RoutedSavablePage.jsx
  src/platform/forms/save-in-progress/RoutedSavableReviewPage.jsx
  src/platform/forms/save-in-progress/SaveInProgressErrorPage.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/forms/save-in-progress/SaveStatus.jsx
  src/platform/forms/save-in-progress/constants.js
  src/platform/forms/tests/save-in-progress/ApplicationStatus.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/FormStartControls.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/RoutedSavablePage.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/SaveInProgressErrorPage.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/SaveInProgressIntro.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/SaveStatus.unit.spec.jsx
Labels: vsa-benefits-2

#13378 Add Cerner facility IDs constant and use it as source of truth
  src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.js
  src/platform/utilities/cerner/index.js
  src/platform/utilities/constants.js
Labels: VSA, front end

#13371 [Development] Show back pay details in CST complete step
  src/applications/claims-status/components/ClaimComplete.jsx
  src/applications/claims-status/components/ClaimDetailLayout.jsx
  src/applications/claims-status/components/ClaimPhase.jsx
  src/applications/claims-status/components/ClaimsTimeline.jsx
  src/applications/claims-status/components/ClaimsUnavailable.jsx
  src/applications/claims-status/components/CompleteDetails.jsx
  src/applications/claims-status/components/NeedFilesFromYou.jsx
  src/applications/claims-status/components/appeals-v2/AppealListItemV2.jsx
  src/applications/claims-status/components/appeals-v2/ClaimsListItemV2.jsx
  src/applications/claims-status/containers/ClaimStatusPage.jsx
  src/applications/claims-status/reducers/claim-detail.js
  src/applications/claims-status/sass/claims-status.scss
  src/applications/claims-status/tests/components/ClaimComplete.unit.spec.jsx
  src/applications/claims-status/tests/components/ClaimsTimeline.unit.spec.jsx
  src/applications/claims-status/tests/components/appeals-v2/AppealListItemV2.unit.spec.jsx
  src/applications/claims-status/tests/components/appeals-v2/ClaimListItemV2.unit.spec.jsx
  src/applications/claims-status/tests/e2e/01.claim-status.e2e.spec.js
  src/applications/claims-status/utils/helpers.js
Labels: 508/Accessibility, Disability Benefits, VSA, claim status, front end

#13369 Fix Service-type dropdown is disabled for Vet Centers facility-type.
  src/applications/facility-locator/components/SearchControls.jsx
Labels: VSA, facility locator, front end

#12839 [Development] Add message for users missing an ID
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/containers/MissingServices.jsx
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
  src/applications/disability-benefits/all-claims/tests/containers/Form526EZApp.unit.spec.jsx
Labels: 526, Disability Benefits, VSA, front end, unicorns

#13377 10836 686 review page update
  src/applications/disability-benefits/686c-674/components/CustomPreSubmitInfo.js
  src/applications/disability-benefits/686c-674/config/form.js
Labels: VSA

#13383 1010CG IA Implementation
  src/applications/caregivers/manifest.json
  src/applications/registry.json
Labels: UX, front end, vsa-benefits-2

#13386 Change title of 10203 form
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/config/form.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13400 remove link from stem eligibility details in form 10203 Review Application Chapter
  src/applications/edu-benefits/10203/content/stemEligibility.jsx
  src/applications/edu-benefits/10203/pages/stemEligibility.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13385 [Development] Add HLR analytics
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/config/submit-transformer.js
  src/applications/disability-benefits/996/config/submitForm.js
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/schema/submitForm.unit.spec.js
  src/applications/personalization/dashboard/helpers.jsx
Labels: Disability Benefits, VSA, front end

#13405 upgrade to formation 6.9.3
  package.json
  yarn.lock
Labels: BAH

#13391 526: Military History Separation Date Validation
  src/applications/disability-benefits/all-claims/components/ValidatedServicePeriodView.jsx
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/bddRedirect.jsx
  src/applications/disability-benefits/all-claims/pages/bddGoBack.jsx
  src/applications/disability-benefits/all-claims/pages/bddRedirect.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/pages/verifyBdd.jsx
  src/applications/disability-benefits/all-claims/tests/pages/bddGoBack.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/pages/bddRedirect.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/verifyBdd.unit.spec.jsx
Labels: 526, Disability Benefits, VSA, front end

#13407 Update wording from revision date to form last updated
  src/applications/find-forms/components/SearchResult.jsx
  src/applications/find-forms/tests/components/SearchResult.unit.spec.jsx
Labels: VSA, front end

#13379 STEM: Update form 22-10203 submission. #7857
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/edu-benefits/10203/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/10203/pages/personalInformation.js
  src/applications/edu-benefits/10203/submit-transformer.js
  src/applications/edu-benefits/10203/submitForm.js
  src/applications/edu-benefits/10203/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/edu-10203-helpers.js
  src/applications/edu-benefits/10203/tests/schema/e2e-maximal-test.json
  src/applications/edu-benefits/10203/tests/schema/maximal-test.json
  src/applications/edu-benefits/10203/tests/schema/minimal-test.json
  src/applications/edu-benefits/10203/tests/schema/transformedData.js
  src/applications/edu-benefits/10203/tests/submit-transformer.unit.spec.js
  src/applications/edu-benefits/sass/edu-benefits.scss
  src/applications/registry.json
Labels: BAH

#13415 Change provider detail facility type to match search type
  src/applications/facility-locator/containers/ProviderDetail.jsx
Labels: VSA, facility locator, front end

#13392 Bah intro 10203
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/10203/content/SaveInProgressIntro.jsx
  src/applications/edu-benefits/10203/tests/containers/IntroductionPage.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13418 Better transformer error logging
  src/site/stages/build/process-cms-exports/index.js
Labels: cms-transformer

#13398 Improve screen reader behavior for left nav "In this section" link
  src/platform/site-wide/side-nav/components/SideNav.js
Labels: VSA, front end

#13419 MDOT- Update Analytics
  src/applications/disability-benefits/2346/components/Accessories.jsx
  src/applications/disability-benefits/2346/components/Batteries.jsx
  src/applications/disability-benefits/2346/config/form.js
Labels: vsa-benefits-2

#13409 Add single BreadCrumb to LOA1
  src/applications/personalization/profile-2/components/Profile2Router.jsx
  src/applications/personalization/profile-2/components/Profile2Wrapper.jsx
Labels: VSA, front end

#13423 [SCREENREADER] Add role="alert" to submit error alert
  src/platform/forms-system/src/js/review/SubmitButtons.jsx
  src/platform/forms-system/test/js/review/SubmitButtons.unit.spec.jsx
Labels: 508/Accessibility, Disability Benefits, VSA, bug, front end

#13401 [Development] Add HLR feature flipper flag
  src/applications/disability-benefits/996/components/HLRWizard.jsx
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/content/contestableIssueAlerts.jsx
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/tests/containers/HLR-wizard.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: Disability Benefits, VSA, front end

#13388 1010CG GTM Tracking Events
  src/applications/caregivers/config/form.js
  src/applications/caregivers/containers/IntroductionPage.jsx
Labels: VSA, enhancement, front end

#13448 [Development] CST: Show message when no claims present
  src/applications/claims-status/containers/YourClaimsPageV2.jsx
  src/applications/claims-status/tests/components/YourClaimsPageV2.unit.spec.jsx
  src/applications/claims-status/tests/e2e/00.claims-list-empty.e2e.spec.js
  src/applications/claims-status/tests/e2e/claims-status-helpers.js
Labels: Disability Benefits, VSA, bug, claim status, front end

#13420 Sanlouise 10596 profile content edits
  src/applications/personalization/profile-2/components/EmailAddressNotification.jsx
  src/applications/personalization/profile-2/components/IdentityNotVerified.jsx
  src/applications/personalization/profile-2/components/NotInMVI.jsx
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
  src/applications/personalization/profile-2/components/personal-information/ContactInformationSection.jsx
  src/applications/personalization/profile-2/components/personal-information/EmailInformationSection.jsx
  src/applications/personalization/profile-2/components/personal-information/PersonalInformation.jsx
  src/applications/personalization/profile-2/tests/components/IdentityNotVerified.unit.spec.jsx
  src/platform/user/profile/vet360/components/AddressField/address-schemas.js
  src/platform/user/profile/vet360/components/PhoneField/VAPPhoneField.jsx
  src/platform/user/profile/vet360/components/PhoneField/VAPPhoneView.jsx
  src/platform/user/profile/vet360/containers/ReceiveTextMessages.jsx
Labels: VSA, front end

#13447 Add connected apps errors
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApps.jsx
Labels: VSA, front end

#13358 Release VAMC pages with hideHomeBreadcrumb option on prod
  src/site/includes/breadcrumbs.drupal.liquid
Labels: VSA, front end

#13466 Remove /mo from institution Estimate Your Benefits
  src/applications/gi/components/profile/EstimatedBenefits.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13463 added /mo visually and per month for screen readers
  src/applications/gi/components/profile/SchoolLocations.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13459 Fix bug with Profile 2.0 contact info fields reverting to old data mid-save.
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
  src/platform/user/profile/vet360/components/base/VAPEditView.jsx
  src/platform/user/profile/vet360/components/base/Vet360Transaction.jsx
  src/platform/user/profile/vet360/containers/AddressValidationView.jsx
  src/platform/user/profile/vet360/containers/VAPProfileField.jsx
  src/platform/user/profile/vet360/tests/containers/VAPProfileField.unit.spec.jsx
Labels: VSA

#13470 CT: School names expand over the center line of the cards. #11159
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx
Labels: BAH

#13404 Sanlouise 10422 hide military section
  src/applications/personalization/profile-2/components/Profile2Router.jsx
  src/applications/personalization/profile-2/components/Profile2Wrapper.jsx
  src/applications/personalization/profile-2/constants.js
  src/applications/personalization/profile-2/routes.js
  src/applications/personalization/profile-2/tests/components/Profile2.unit.spec.js
  src/applications/personalization/profile-2/tests/components/Profile2Router.unit.spec.js
Labels: VSA, front end

#13460 MDOT: Remove 5 month alerts
  src/applications/disability-benefits/2346/components/Accessories.jsx
  src/applications/disability-benefits/2346/components/Batteries.jsx
  src/applications/disability-benefits/2346/tests/Accessories.unit.spec.jsx
  src/applications/disability-benefits/2346/tests/Batteries.unit.spec.jsx
Labels: vsa-benefits-2

#13411 10203 form prefill
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/content/stem.jsx
  src/applications/edu-benefits/10203/prefill-transformer.js
  src/applications/edu-benefits/10203/tests/containers/ConfirmEligibilityView.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/schema/prefillData.js
Labels: BAH

#13430 Fix phone number formatting. Add links.
  src/applications/facility-locator/components/search-results/LocationPhoneLink.jsx
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/components/LocationPhoneLink.unit.spec.jsx
  src/applications/facility-locator/tests/helpers/helpers.unit.spec.js
  src/applications/facility-locator/tests/helpers/phoneNumbers.unit.spec.js
  src/applications/facility-locator/utils/phoneNumbers.js
Labels: VSA, facility locator, front end

#13490 Update order account security for a11y
  src/applications/personalization/profile-2/components/AccountSecurityContent.jsx
  src/applications/personalization/profile-2/components/EmailAddressNotification.jsx
  src/applications/personalization/profile-2/tests/components/AccountSecurityContent.unit.spec.jsx
Labels: VSA, front end

#13368 Consistent community urgent care search
  src/applications/facility-locator/components/ProviderServiceDescription.jsx
  src/applications/facility-locator/components/SearchResult.jsx
  src/applications/facility-locator/components/search-results/LocationInfoBlock.jsx
  src/applications/facility-locator/components/search-results/LocationPhoneLink.jsx
  src/applications/facility-locator/constants/index.js
  src/applications/facility-locator/containers/UrgentCareAlert.jsx
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/tests/components/UrgentCareAlert.unit.spec.js
  src/applications/facility-locator/tests/components/UrgentCareSearch.unit.spec.js
  src/applications/facility-locator/utils/helpers.js
Labels: VSA, facility locator, front end

#13487 Fix sentence case issues on Facility Locator pages
  src/applications/facility-locator/components/LocationHours.jsx
  src/applications/facility-locator/components/LocationMap.jsx
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/components/search-results/LocationPhoneLink.jsx
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/tests/components/LocationPhoneLink.unit.spec.jsx
Labels: VSA, facility locator, front end

#13357 MDOT: Alert for Failed Order Submissions
  src/applications/disability-benefits/2346/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/2346/sass/form-2346.scss
  src/applications/disability-benefits/2346/tests/ConfirmationPage.unit.spec.jsx
Labels: vsa-benefits-2

#13455 [Development] Fix HLR a11y issues discovered with WAVE
  src/applications/disability-benefits/996/components/HLRWizard.jsx
  src/applications/disability-benefits/996/components/IntroductionPage.jsx
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/containers/SelectArrayItemsWidget.jsx
  src/applications/disability-benefits/996/content/InformalConference.jsx
  src/applications/disability-benefits/996/pages/informalConference.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
Labels: 508/Accessibility, Disability Benefits, VSA, front end

#13469 BDD: Fully Developed Claim
  src/applications/disability-benefits/bdd/config/form.js
Labels: BDD, Disability Benefits, VSA, front end

#13491 Minor copy fix
  src/applications/personalization/profile-2/constants.js
Labels: VSA, front end

#13349 Change focus to sub accordion on "update benefits" button press
  src/applications/gi/components/AccordionItem.jsx
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/profile/EstimatedBenefits.jsx
  src/applications/gi/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
  src/applications/gi/containers/VetTecEstimateYourBenefits.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13496 Update spacing connected apps
  src/applications/personalization/profile-2/components/connected-apps/AdditionalInfoSections.jsx
  src/applications/personalization/profile-2/components/connected-apps/AppDeletedAlert.jsx
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApps.jsx
Labels: VSA, front end

#13375 Fix initial form fields bug in phone section
  src/platform/user/profile/vet360/containers/VAPProfileField.jsx
  src/platform/user/profile/vet360/reducers/index.js
Labels: VSA, front end

#13500 1010CG confirmation header order
  src/applications/caregivers/containers/ConfirmationPage.jsx
Labels: 508/Accessibility, bug, front end

#13498 New mobile nav
  src/applications/personalization/profile-2/components/MobileMenuTrigger.jsx
  src/applications/personalization/profile-2/components/Profile2Wrapper.jsx
  src/applications/personalization/profile-2/components/ProfileMobileSubNav.jsx
  src/applications/personalization/profile-2/components/ProfileSideNav.jsx
  src/applications/personalization/profile-2/components/ProfileSubNav.jsx
  src/applications/personalization/profile-2/sass/_shared.scss
  src/applications/personalization/profile-2/sass/mobile-sidenav-trigger.scss
  src/applications/personalization/profile-2/sass/profile-2.scss
  src/applications/personalization/profile-2/sass/profile-mobile-subnav.scss
  src/applications/personalization/profile-2/sass/profile-sidenav.scss
  src/applications/personalization/profile-2/sass/profile-subnav.scss
Labels: VSA

#13493 Remove detail page links from community care provider search results
  src/applications/facility-locator/components/search-results/LocationDirectionsLink.jsx
  src/applications/facility-locator/components/search-results/LocationInfoBlock.jsx
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/components/search-results/LocationInfoBlock.unit.spec.jsx
  src/applications/facility-locator/tests/components/search-results/LocationPhoneLink.unit.spec.jsx
Labels: VSA, facility locator, front end

#13505 Update broken links
  src/platform/landing-pages/header-footer-data.json
  src/site/layouts/health_care_region_page.drupal.liquid
Labels: VSA, front end

#13506 filter subnav routes when user is LOA1
  src/applications/personalization/profile-2/components/ProfileMobileSubNav.jsx
  src/applications/personalization/profile-2/components/ProfileSubNav.jsx
Labels: VSA

#13453 10774: STEM: Add Entitlement Remaining alert to 10203 introduction page
  src/applications/edu-benefits/10203/actions/post-911-gib-status.js
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/10203/edu-benefits-entry.jsx
  src/applications/edu-benefits/10203/reducers/index.js
  src/applications/edu-benefits/10203/reducers/post911GIBStatus.js
  src/applications/edu-benefits/10203/tests/actions/post-911-gib-status.unit.spec.js
  src/applications/edu-benefits/10203/tests/containers/IntroductionPage.unit.spec.jsx
Labels: BAH

#13510 526: Move Military History and Alternate Names to 2nd and 3rd Pages
  src/applications/disability-benefits/all-claims/config/form.js
Labels: 526, BDD, Disability Benefits, VSA, front end

#13508 11212 reorder 686 chapters
  src/applications/disability-benefits/686c-674/config/chapters/report-divorce/former-spouse-information/formerSpouseInformation.js
  src/applications/disability-benefits/686c-674/config/form.js
  src/applications/disability-benefits/686c-674/tests/e2e/00-child-marriage-report-death-stepchild-left-child-stopped-school.e2e.spec.js
  src/applications/disability-benefits/686c-674/tests/e2e/00-spouse-child-all-fields.e2e.spec.js
  src/applications/disability-benefits/686c-674/tests/e2e/00-spouse-report-divorce.e2e.spec.js
  src/applications/disability-benefits/686c-674/tests/e2e/686-test-data.json
  src/applications/disability-benefits/686c-674/tests/e2e/add-child-and-674.e2e.spec.js
  src/applications/disability-benefits/686c-674/tests/e2e/child-report-divorce.e2e.spec.js
  src/applications/disability-benefits/686c-674/tests/e2e/test-helpers.js
Labels: VSA

#13486 Bah jawsbug 10200
  src/applications/gi/components/profile/AdditionalInformation.jsx
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/vet-tec/VetTecAdditionalInformation.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13492 VBA Change Call-First to Online Tools and Customer Service Number on Detail page
  src/applications/facility-locator/components/FacilityTypeDescription.jsx
  src/applications/facility-locator/components/VABenefitsCall.jsx
  src/applications/facility-locator/containers/FacilityDetail.jsx
  src/applications/facility-locator/tests/components/FacilityTypeDescription.unit.spec.jsx
  src/applications/facility-locator/tests/components/VABenefitsCall.unit.spec.jsx
Labels: VSA, facility locator, front end

#13513 Update 10203 submit transformer
  src/applications/edu-benefits/10203/submit-transformer.js
  src/applications/edu-benefits/10203/tests/schema/maximal-test.json
  src/applications/edu-benefits/10203/tests/schema/minimal-test.json
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13517 11266 686 route gating
  src/applications/disability-benefits/686c-674/containers/App.jsx
Labels: VSA

#13519 Update 10203 IntroductionPage
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/10203/content/SaveInProgressIntro.jsx
  src/applications/edu-benefits/10203/tests/containers/IntroductionPage.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13525 10203: Personal Information Switch Preferred Contact to Radio buttons
  src/applications/edu-benefits/10203/content/personalInformation.jsx
  src/applications/edu-benefits/10203/pages/personalInformation.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13518 Update vets-json-schema to fix postal code validation on 1010CG
  package.json
  yarn.lock
Labels: bug, front end

#13532 Refactor 1010CG pages into page files
  src/applications/caregivers/config/form.js
  src/applications/caregivers/config/pages/hasSecondaryCaregiver.js
  src/applications/caregivers/config/pages/index.js
  src/applications/caregivers/config/pages/primaryContact.js
  src/applications/caregivers/config/pages/primaryHealthCoverage.js
  src/applications/caregivers/config/pages/primaryInfo.js
  src/applications/caregivers/config/pages/secondaryCaregiverContact.js
  src/applications/caregivers/config/pages/secondaryInfo.js
  src/applications/caregivers/config/pages/secondaryTwoContactInfo.js
  src/applications/caregivers/config/pages/secondaryTwoInfoi.js
  src/applications/caregivers/config/pages/vetContactInfo.js
  src/applications/caregivers/config/pages/vetInfo.js
  src/applications/caregivers/config/pages/vetMedicalCenter.js
  src/applications/caregivers/helpers.js
Labels: front end

#13530 added ctFilterEnhancement feature flag
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13529 Kelsonic 9841 update tty numbers
  src/applications/auth/containers/AuthApp.jsx
  src/applications/caregivers/components/NeedHelpFooter/index.jsx
  src/applications/disability-benefits/2346/components/FooterInfo.jsx
  src/applications/disability-benefits/686c-674/components/GetFormHelp.jsx
  src/applications/disability-benefits/686c-674/config/helpers.js
  src/applications/disability-benefits/996/components/GetFormHelp.jsx
  src/applications/disability-benefits/all-claims/containers/MissingServices.jsx
  src/applications/gi/components/vet-tec/VetTecApplicationProcess.jsx
  src/applications/hca/components/GetFormHelp.jsx
  src/applications/hca/containers/IntroductionPage.jsx
  src/applications/personalization/profile-2/components/MilitaryInformation.jsx
  src/applications/personalization/profile-2/components/connected-apps/AdditionalInfoSections.jsx
  src/applications/personalization/profile-2/components/direct-deposit/FraudVictimAlert.jsx
  src/applications/personalization/profile360/components/MilitaryInformation.jsx
  src/applications/personalization/profile360/components/PaymentInformationBlocked.jsx
  src/applications/personalization/profile360/components/PaymentInformationEditModalError.jsx
  src/applications/personalization/profile360/containers/PaymentInformation.jsx
  src/applications/personalization/profile360/tests/components/PaymentInformationBlocked.unit.spec.jsx
  src/applications/personalization/profile360/tests/components/PaymentInformationEditModalError.unit.spec.jsx
  src/applications/personalization/rated-disabilities/components/RatedDisabilityList.jsx
  src/applications/personalization/rated-disabilities/components/TotalRatingStates.jsx
  src/applications/personalization/view-dependents/layouts/helpers.jsx
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/UnauthContent/index.js
  src/applications/validate-mhv-account/components/errors/DeactivatedMHVId.jsx
  src/applications/validate-mhv-account/components/errors/MultipleMHVIds.jsx
  src/applications/validate-mhv-account/components/errors/NeedsSSNResolution.jsx
  src/applications/validate-mhv-account/components/errors/NeedsVAPatient.jsx
  src/applications/validate-mhv-account/components/errors/VerificationFailed.jsx
  src/applications/validate-mhv-account/containers/CreateMHVAccountFailed.jsx
  src/applications/validate-mhv-account/containers/UpgradeAccountFailed.jsx
  src/applications/vaos/components/NeedHelp.jsx
  src/applications/vaos/tests/components/NeedHelp.unit.spec.jsx
  src/applications/verify/containers/VerifyApp.jsx
  src/applications/vre/components/GetFormHelp.jsx
  src/platform/site-wide/cta-widget/components/messages/DeactivatedMHVIds.jsx
  src/platform/site-wide/cta-widget/components/messages/MultipleIds.jsx
  src/platform/site-wide/cta-widget/components/messages/NeedsSSNResolution.jsx
  src/platform/site-wide/cta-widget/components/messages/NeedsVAPatient.jsx
  src/platform/site-wide/cta-widget/components/messages/RegisterFailed.jsx
  src/platform/site-wide/cta-widget/components/messages/UpgradeFailed.jsx
  src/platform/site-wide/cta-widget/components/messages/mvi/NotFound.jsx
  src/platform/site-wide/user-nav/components/HelpMenu.jsx
  src/platform/site-wide/va-footer/components/CrisisPanel.jsx
  src/platform/static-data/CallHRC.jsx
  src/platform/static-data/CallNCACenter.jsx
  src/platform/static-data/CallVBACenter.jsx
  src/platform/user/authorization/containers/MHVApp.jsx
Labels: VSA, content, front end

#13542 Hide new condition if claimType set
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/pages/claimType.jsx
Labels: 526, Disability Benefits, VSA, front end

#13551 add view payments to registry
  src/applications/registry.json
Labels: VSA

#13547 Expand on cy.login() to accept optional mock user data
  src/applications/disability-benefits/2346/tests/MDOT.cypress.spec.js
  src/platform/testing/e2e/cypress/support/commands/login.js
Labels: VSA

#13543 11337 update 686 form
  src/applications/disability-benefits/686c-674/manifest.json
  src/applications/personalization/dashboard/helpers.jsx
  src/applications/registry.json
  src/platform/forms/constants.js
  src/platform/forms/tests/forms.unit.spec.js
Labels: VSA

#13554 MDOT: Update e2e now that MDOT is in prod
  src/applications/disability-benefits/2346/tests/MDOT.cypress.spec.js
  src/applications/disability-benefits/2346/tests/data/happyPath.json
  src/applications/disability-benefits/2346/tests/data/noAccessories.json
  src/applications/disability-benefits/2346/tests/data/noBatteries.json
  src/applications/disability-benefits/2346/tests/data/noTempAddress.json
Labels: vsa-benefits-2

#13474 Remove custom banners code and replace with design system components
  package.json
  src/applications/hca/tests/components/HCAEnrollmentStatusWarning.unit.spec.js
  src/applications/personalization/profile-2/tests/components/DirectDepositContent.unit.spec.jsx
  src/platform/site-wide/banners/components/Banners/index.js
  src/platform/site-wide/banners/components/Banners/index.unit.spec.js
  src/platform/site-wide/banners/components/HomepageBanner/index.js
  src/platform/site-wide/banners/components/HomepageBanner/index.unit.spec.js
  src/platform/site-wide/banners/components/MaintenanceBanner/index.js
  src/platform/site-wide/banners/components/MaintenanceBanner/index.unit.spec.js
  src/platform/site-wide/banners/config/maintenanceBanner.js
  src/platform/site-wide/banners/index.js
  src/platform/site-wide/banners/styles.scss
  yarn.lock
Labels: VSA, front end

#13544 VBA Facilities Missing Service Listings
  src/applications/facility-locator/components/ServicesAtFacility.jsx
  src/applications/facility-locator/tests/components/ServicesAtFacility.unit.spec.jsx
Labels: VSA, facility locator, front end

#13516 Sanlouise 11196 align checkmarks
  src/applications/personalization/profile-2/components/AccountSecurityContent.jsx
  src/applications/personalization/profile-2/components/MHVTermsAndConditionsStatus.jsx
  src/applications/personalization/profile-2/components/ProfileHeader.jsx
  src/applications/personalization/profile-2/components/ProfileInfoTable.jsx
  src/applications/personalization/profile-2/components/TwoFactorAuthorizationStatus.jsx
  src/applications/personalization/profile-2/components/Verified.jsx
  src/applications/personalization/profile-2/components/direct-deposit/DirectDepositContent.jsx
  src/applications/personalization/profile-2/tests/components/Verified.unit.spec.jsx
Labels: VSA, front end

#13564 Add manage your VA debt widget
  src/platform/site-wide/cta-widget/helpers.js
Labels: VSA, front end

#13565 Update rootUrl and breadcrumbs
  src/applications/disability-benefits/view-payments/containers/helpers.js
  src/applications/disability-benefits/view-payments/manifest.json
  src/applications/registry.json
  yarn.lock
Labels: VSA

#13514 Hide VAMC SideNav sub-items on mobile
  src/platform/site-wide/side-nav/components/NavItem.js
  src/platform/site-wide/side-nav/components/SideNav.js
  src/platform/site-wide/side-nav/tests/components/NavItem.unit.spec.js
Labels: 508/Accessibility, VSA, front end

#13566 [Development] Show error message when no new conditions added
  src/applications/disability-benefits/all-claims/components/NewDisability.jsx
  src/applications/disability-benefits/all-claims/pages/addDisabilities.js
  src/applications/disability-benefits/all-claims/pages/claimType.jsx
  src/applications/disability-benefits/all-claims/tests/pages/addDisabilities.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/disability-benefits/all-claims/validations.js
Labels: 526, Disability Benefits, VSA, bug, front end

#13560 Updated intro 10203 page
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13563 STEM: Update Education Benefits on the application Summary page #11504
  src/platform/forms-system/src/js/review/widgets.jsx
  src/platform/forms-system/test/js/review/widgets.unit.spec.jsx
Labels: BAH

#13545 10985: Link gibctSearchEnhancements feature flag to fuzzy_search, upd…
  src/applications/gi/actions/index.js
  src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
  src/applications/gi/containers/VetTecSearchPage.jsx
Labels: BAH

#13573 [Development] Change new condition error message
  src/applications/disability-benefits/all-claims/pages/addDisabilities.js
Labels: 526, Disability Benefits, VSA, front end

#13567 change prefill alert message on 10203 form
  src/applications/edu-benefits/10203/content/ApplicantDescription.jsx
  src/applications/edu-benefits/10203/content/PrefillMessage.jsx
  src/applications/edu-benefits/10203/pages/applicantInformation.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13550 BDD to all-claims: Copy components, add isBDD logic to depends, allow BDD in Military History, separate STRs
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/evidenceTypesBDD.jsx
  src/applications/disability-benefits/all-claims/content/militaryHistory.jsx
  src/applications/disability-benefits/all-claims/content/separationLocations.js
  src/applications/disability-benefits/all-claims/content/serviceTreatmentRecords.jsx
  src/applications/disability-benefits/all-claims/content/supportingEvidenceOrientationBDD.jsx
  src/applications/disability-benefits/all-claims/pages/evidenceTypesBDD.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/pages/serviceTreatmentRecords.js
  src/applications/disability-benefits/all-claims/tests/pages/evidenceTypesBDD.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/militaryHistory.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/serviceTreatmentRecords.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/property-names.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/validations.unit.spec.js
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/disability-benefits/all-claims/validations.js
Labels: 526, BDD, Disability Benefits, VSA, front end

#13569 added gibctCh33BenefitRateUpdate feature flag to vets-website
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13591 update housing payment text
  src/applications/edu-benefits/10203/content/activeDuty.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13539 Move connected app error upward
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApps.jsx
Labels: VSA, front end

#13562 Remove unneeded height on address validation input
  src/applications/personalization/profile-2/components/Verified.jsx
  src/applications/personalization/profile360/sass/profile-360.scss
  src/platform/user/profile/vet360/containers/AddressValidationModal.jsx
  src/platform/user/profile/vet360/containers/AddressValidationView.jsx
Labels: VSA, front end

#13584 Audit phone numbers for aria-label attribute
  src/applications/caregivers/containers/IntroductionPage.jsx
  src/applications/caregivers/definitions/content.js
Labels: 508/Accessibility, front end

#13574 Sanlouise 11567 gtm updates
  src/applications/personalization/profile-2/components/AccountSecurityContent.jsx
  src/applications/personalization/profile-2/components/MHVTermsAndConditionsStatus.jsx
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApp.jsx
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApps.jsx
  src/applications/personalization/profile-2/components/connected-apps/actions/index.js
  src/applications/personalization/profile-2/tests/components/connected-apps/actions.unit.spec.js
Labels: VSA, front end

#13578 updated cumulative post 9/11 selection options and updated modal text
  src/applications/gi/components/profile/BenefitsForm.jsx
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/components/profile/InstitutionProfile.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/containers/EstimateYourBenefits.jsx
  src/applications/gi/containers/GiBillApp.jsx
  src/applications/gi/containers/LandingPage.jsx
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/containers/ProfilePage.jsx
  src/applications/gi/containers/SearchPage.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13580 match keepalive response on transaction id
  src/platform/site-wide/user-nav/containers/AutoSSO.jsx
  src/platform/site-wide/user-nav/tests/containers/AutoSSO.unit.spec.jsx
  src/platform/user/authentication/selectors.js
  src/platform/user/tests/authentication/selectors.unit.spec.js
  src/platform/utilities/sso/index.js
  src/platform/utilities/sso/keepAliveSSO.js
  src/platform/utilities/tests/sso.unit.spec.js
Labels: bug

#13586 Add tests to confirm that Profile 2.0 sections are properly gated
  src/applications/personalization/profile-2/tests/e2e/profile.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.direct-deposit.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.loa1.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.military-information.cypress.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.non-vet.cypress.spec.js
  src/applications/personalization/profile-2/tests/fixtures/payment-information/direct-deposit-deceased.json
  src/applications/personalization/profile-2/tests/fixtures/payment-information/direct-deposit-fiduciary.json
  src/applications/personalization/profile-2/tests/fixtures/payment-information/direct-deposit-incompetent.json
  src/applications/personalization/profile-2/tests/fixtures/payment-information/direct-deposit-is-not-eligible.json
  src/applications/personalization/profile-2/tests/fixtures/payment-information/direct-deposit-is-not-set-up.json
  src/applications/personalization/profile-2/tests/fixtures/users/user-loa1.json
  src/applications/personalization/profile-2/tests/fixtures/users/user-non-vet.json
Labels: VSA

#13568 Fix invalid dates for facility satisfaction/wait time data
  src/applications/facility-locator/components/AccessToCare.jsx
  src/applications/facility-locator/components/AppointmentInfo.jsx
  src/applications/facility-locator/tests/components/AccessToCare.unit.spec.jsx
  src/applications/facility-locator/tests/components/AppointmentInfo.unit.spec.jsx
Labels: VSA, facility locator, front end

#13581 Update styles on responsive tables
  src/applications/disability-benefits/view-payments/components/responsive-table/ResponsiveTable.jsx
  src/applications/disability-benefits/view-payments/components/view-payments-lists/payments/Payments.jsx
  src/applications/disability-benefits/view-payments/reducers/index.js
  src/applications/disability-benefits/view-payments/sass/ResponsiveTable.scss
  src/applications/disability-benefits/view-payments/sass/view-payments.scss
Labels: VSA

#13597 [Development] Route BDD to all-claims
  src/applications/disability-benefits/wizard/pages/file-bdd.jsx
  src/applications/personalization/dashboard/helpers.jsx
  src/applications/registry.json
Labels: 526, BDD, Disability Benefits, VSA, front end

#13602 updated chapter 5 page 1 and 2
  src/applications/edu-benefits/10203/content/directDeposit.jsx
  src/applications/edu-benefits/10203/pages/directDeposit.js
  src/applications/edu-benefits/10203/pages/personalInformation.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13593 Fix connected apps timestamp issue
  src/applications/personalization/profile-2/components/connected-apps/ConnectedApp.jsx
Labels: VSA, front end

#13604 11652 - Mc update form686 flipper widget
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/view-modify-dependent/686-cta/containers/Form686CTA.jsx
  src/applications/static-pages/view-modify-dependent/686-cta/containers/Form686ContentReveal.jsx
  src/applications/static-pages/view-modify-dependent/686-cta/create686CcontentReveal.js
  src/applications/static-pages/view-modify-dependent/686-cta/form686CTA.js
  src/applications/static-pages/widgetTypes.js
  src/platform/site-wide/cta-widget/helpers.js
Labels: VSA

#12669 [Development] Add save-in-progress dev modal
  src/platform/forms/sass/_m-schemaform.scss
  src/platform/forms/save-in-progress/RoutedSavablePage.jsx
  src/platform/forms/save-in-progress/RoutedSavableReviewPage.jsx
  src/platform/forms/save-in-progress/SaveFormLink.jsx
  src/platform/forms/save-in-progress/SaveInProgressDevModal.jsx
  src/platform/forms/tests/save-in-progress/SaveInProgressDevModal.unit.spec.jsx
Labels: Disability Benefits, front end, work-in-progress

#13625 [Development] Revert hiding new condition step
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/pages/claimType.jsx
Labels: 526, Disability Benefits, VSA, bug, front end

#13587 Only show When to use this form header when fieldVAFormUsage is truthy
  src/site/layouts/va_form.drupal.liquid
Labels: VSA, front end

#13608 Bah chapter5 typo
  src/applications/edu-benefits/10203/content/directDeposit.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13536 Restore facility search results summary
  src/applications/facility-locator/components/FacilityTypeDescription.jsx
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/components/SearchResultsHeader.jsx
  src/applications/facility-locator/components/search-results/LocationInfoBlock.jsx
  src/applications/facility-locator/containers/FacilityDetail.jsx
  src/applications/facility-locator/containers/VAMap.jsx
  src/applications/facility-locator/tests/components/FacilityTypeDescription.unit.spec.jsx
  src/applications/facility-locator/tests/components/search-results/SearchResultsHeader.unit.spec.jsx
  src/applications/facility-locator/tests/e2e/search.cypress.spec.js
Labels: 508/Accessibility, VSA, facility locator, front end

#13610 Use sentence case for facility dropdowns
  src/applications/facility-locator/components/FacilityTypeDropdown.jsx
  src/applications/facility-locator/config.js
Labels: VSA, facility locator, front end

#13595 Hide Header when errors fetching full name
  src/applications/personalization/profile-2/components/Profile2Wrapper.jsx
  src/applications/personalization/profile-2/components/ProfileHeader.jsx
  src/applications/personalization/profile-2/tests/components/Profile2.unit.spec.js
  src/applications/personalization/profile-2/tests/components/Profile2Wrapper.unit.spec.js
  src/applications/personalization/profile-2/tests/e2e/profile.cypress.spec.js
  src/applications/personalization/profile360/actions/index.js
  src/applications/personalization/profile360/reducers/index.js
  src/applications/personalization/profile360/tests/reducers/index.unit.spec.js
Labels: VSA, front end

#13621 22-10203: add chapter 2 confirm eligibility page
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/containers/InitialConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/pages/index.js
  src/applications/edu-benefits/10203/pages/initialConfirmEligibility.js
  src/applications/edu-benefits/10203/tests/containers/InitialConfirmEligibilityView.unit.spec.jsx
Labels: BAH

#13609 Update GA for connected apps
  src/applications/personalization/profile-2/components/connected-apps/actions/index.js
Labels: VSA, front end

#13606 All-claims skip additional disability benefits
  src/applications/disability-benefits/all-claims/config/form.js
Labels: 526, BDD, Disability Benefits, VSA, front end

#13657 removed content doc error
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13637 [Development] Update vets-json-schema
  package.json
  src/platform/forms/tests/forms.unit.spec.js
  yarn.lock
Labels: VSA, front end

#13627 Bah chapter3 update
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/content/stemEligibility.jsx
  src/applications/edu-benefits/10203/pages/confirmEligibility.js
  src/applications/edu-benefits/10203/pages/stemEligibility.js
  src/applications/edu-benefits/sass/edu-benefits.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13626 Update 10203 Chapter 6 based on user testing updates
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/10203/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13614 Remove show more specialty and fix rendered list
  package.json
  src/applications/facility-locator/components/AccessToCare.jsx
  src/applications/facility-locator/components/AppointmentInfo.jsx
  src/applications/facility-locator/components/ServicesAtFacility.jsx
  src/applications/facility-locator/constants/mock-facility-v0.json
  src/applications/facility-locator/constants/mock-facility-v1.json
  src/applications/facility-locator/tests/components/AppointmentInfo.unit.spec.jsx
  src/applications/facility-locator/tests/components/__snapshots__/AppointmentInfo.unit.spec.jsx.mocha-snapshot
  src/applications/facility-locator/tests/helpers/formatServiceName.unit.spec.js
  src/applications/facility-locator/utils/formatServiceName.js
  src/platform/testing/unit/mocha.opts
  yarn.lock
Labels: VSA, facility locator, front end

#13662 Use sentence case for service types on facility detail page
  src/applications/facility-locator/components/AppointmentInfo.jsx
  src/applications/facility-locator/components/ServicesAtFacility.jsx
Labels: VSA, facility locator, front end

#13665 add optional chaining
  src/applications/disability-benefits/686c-674/config/chapters/674/student-address-marriage-tuition/studentAddressMarriageTuition.js
Labels: VSA

#13655 Add some tests for Personal Info section
  src/applications/personalization/profile-2/msw-mocks.js
  src/applications/personalization/profile-2/tests/components/DirectDepositContent.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.add-email-address.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.unit.spec.jsx
  src/applications/personalization/profile-2/tests/unit-test-helpers.js
  src/platform/user/profile/vet360/components/ContactInfoForm.jsx
  src/platform/user/profile/vet360/components/base/VAPEditView.jsx
  src/platform/user/profile/vet360/components/base/Vet360TransactionPending.jsx
  src/platform/user/profile/vet360/containers/AddressValidationView.jsx
  src/platform/user/profile/vet360/containers/VAPProfileField.jsx
  src/platform/user/profile/vet360/util/local-vet360.js
Labels: VSA

#13664 Fixed Chapter 3 UX feedback issues
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#13673 Update prod legacy content for appts page
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/LegacyContent/index.js
Labels: VSA, front end

#13667 Default fieldTimeout to 0
  src/site/stages/build/process-cms-exports/transformers/paragraph-react_widget.js
Labels: cms-transformer

#13674 11265 test 686 widget
  src/applications/static-pages/view-modify-dependent/686-cta/containers/Form686CTA.jsx
  src/platform/site-wide/cta-widget/helpers.js
Labels: VSA

#13675 Update coronavirus message on facility locator page
  src/applications/facility-locator/containers/VAMap.jsx
Labels: VSA, facility locator, front end

#13676 Add additional "delete email address" tests
  src/applications/personalization/profile-2/msw-mocks.js
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.add-email-address.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.delete-email-address.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.edit-email-address.unit.spec.jsx
  src/applications/personalization/profile-2/tests/components/personal-information/PersonalInformation.unit.spec.jsx
  src/applications/personalization/profile-2/tests/unit-test-helpers.js
  src/platform/user/profile/vet360/components/base/VAPEditView.jsx
Labels: VSA
