Repository department-of-veterans-affairs/vets-website, pull requests merged in 2021-05, with the labels that each got.

#16996 [DON'T MERGE UNTIL DRUPAL IS READY] Remove support for audience tags in clp
  src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
Labels: VSA, front end

#16960 add click tracking to best bets
  src/applications/search/containers/SearchApp.jsx
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
  src/platform/site-wide/user-nav/tests/e2e/00-required.cypress.spec.js
Labels: VSA, front end

#16885 [MERGE 05/03] Add redirect
  src/applications/proxy-rewrite/redirects/crossDomainRedirects.json
Labels: VSA, front end

#16980 Custom checkbox values in review
  src/platform/forms-system/src/js/review/widgets.jsx
  src/platform/forms-system/test/js/review/widgets.unit.spec.jsx
Labels: NOD, VSA, front end, vsa-claims-appeals

#17047 NOD: Add E2E Cypress tests
  src/applications/appeals/10182/components/ContactInformation.jsx
  src/applications/appeals/10182/components/NewIssuesField.jsx
  src/applications/appeals/10182/tests/10182-notice-of-disagreement.cypress.spec.js
  src/applications/appeals/10182/tests/fixtures/mocks/application-submit.json
  src/applications/appeals/10182/tests/fixtures/mocks/in-progress-forms.json
  src/applications/appeals/10182/tests/fixtures/mocks/mock-upload.json
  src/applications/appeals/10182/tests/fixtures/mocks/user.json
  src/applications/appeals/10182/tests/nod.cypress.helpers.js
Labels: 508/Accessibility, NOD, VSA, front end, testing, vsa-claims-appeals

#16992 Modify SEARCH_IGNORE_LIST + `countKeywordsFound`
  src/applications/resources-and-support/constants/index.js
  src/applications/resources-and-support/hooks/useGetSearchResults.js
Labels: VSA, front end

#17029 NOD: add more unit tests & content changes
  src/applications/appeals/10182/components/EligibleIssuesWidget.jsx
  src/applications/appeals/10182/components/ReviewDescription.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/tests/pages/contestableIssues.unit.spec.jsx
  src/applications/appeals/10182/tests/schema/initialData.js
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/upload.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17063 Update HLR breadcrumb labels
  src/applications/registry.json
Labels: HLR, VSA, vsa-claims-appeals

#17066 Conditionally render connect with us section + update text order
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#17078 Fix calendar links
  src/applications/static-pages/ics-generator.js
  src/site/includes/social-share.drupal.liquid
Labels: VSA, front end

#17031 Upload buton aria-label fix
  src/platform/forms-system/src/js/fields/FileField.jsx
  src/platform/forms-system/test/js/fields/FileField.unit.spec.jsx
Labels: 508/Accessibility, NOD, VSA, vsa-claims-appeals

#17054 Upload file: change delete file button style
  src/platform/forms-system/src/js/fields/FileField.jsx
  src/platform/forms-system/test/js/fields/FileField.unit.spec.jsx
Labels: 508/Accessibility, NOD, VSA, front end, vsa-claims-appeals

#17084 updating codeowners for Identity
  .github/CODEOWNERS
Labels: Identity

#17105 Fix NOD uploads
  src/applications/appeals/10182/utils/upload.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17107 Fix intro PDF download link on 10-10CG
  src/applications/caregivers/containers/IntroductionPage.jsx
Labels: VSA, bug, caregivers, front end

#17074 GI-Sandbox GIDS api v1
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/SearchForm.jsx
  src/applications/gi-sandbox/config.js
  src/applications/gi-sandbox/containers/LandingPage.jsx
  src/applications/gi-sandbox/reducers/search.js
  src/applications/gi-sandbox/tests/components/SearchForm.unit.spec.jsx
Labels: BAH

#16505 Move only-used-once templates into main media_list_images template + tweak styilng
  src/platform/site-wide/sass/shame.scss
  src/site/includes/image_detail_mobile_responsive.drupal.liquid
  src/site/includes/images_list_with_additional_info_component.drupal.liquid
  src/site/layouts/media_list_images.drupal.liquid
Labels: VSA, front end

#17035 Update 10-10CG Signature Box Content
  src/applications/caregivers/components/PreSubmitInfo/SignatureCheckbox.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/definitions/content.js
  src/applications/caregivers/sass/signatureBox.scss
  src/applications/caregivers/tests/e2e/1010cg.cypress.spec.js
Labels: caregivers, content, front end

#17126 Revert "Fix intro PDF download link on 10-10CG"
  src/applications/caregivers/containers/IntroductionPage.jsx
Labels: VSA, caregivers, content, front end

#17114 add debounce
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: VSA, front end

#17067 Accessibility issues for facility locator manual geolocation
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/reducers/searchQuery.js
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/components/SearchControls.unit.spec.jsx
  src/applications/facility-locator/tests/e2e/accessibility.cypress.spec.js
  src/applications/facility-locator/utils/actionTypes.js
Labels: facility locator

#17025 Connect signature page to BE for POA signature
  src/applications/caregivers/components/PreSubmitInfo/SignatureCheckbox.jsx
  src/applications/caregivers/components/PreSubmitInfo/SignatureInput.jsx
  src/applications/caregivers/components/PreSubmitInfo/SubmitLoadingIndicator.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/definitions/content.js
  src/applications/caregivers/sass/signatureBox.scss
  src/applications/caregivers/tests/e2e/fixtures/data/oneSecondaryCaregivers.json
  src/applications/caregivers/tests/e2e/fixtures/data/requiredOnly.json
  src/applications/caregivers/tests/e2e/fixtures/data/secondaryOneOnly.json
  src/applications/caregivers/tests/e2e/fixtures/data/twoSecondaryCaregivers.json
  src/applications/caregivers/tests/helpers.unit.spec.js
Labels: caregivers, enhancement, front end

#17052 NOD: Update path
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/manifest.json
  src/applications/registry.json
Labels: NOD, VSA, front end, vsa-claims-appeals

#17118 23531: Sandbox card styling
  src/applications/gi-sandbox/components/SearchResultCard.jsx
  src/applications/gi-sandbox/components/SearchResults.jsx
  src/applications/gi-sandbox/containers/LandingPage.jsx
  src/applications/gi-sandbox/sass/partials/_gi-search-page.scss
Labels: BAH

#17099 Vet center - finalize centralized content
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/includes/vet_center_health_services.liquid
  src/site/layouts/tests/vet_center/fixtures/featuredContentData.json
  src/site/layouts/tests/vet_center/fixtures/vet_center_escanaba_data.json
  src/site/layouts/vet_center.drupal.liquid
  src/site/paragraphs/q_a.accordion_panel.drupal.liquid
  src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
Labels: VSA, front end, vet-center

#17130 21574 dep verification api call
  src/applications/disability-benefits/686c-674/config/chapters/674/student-name-ssn/studentNameSSN.js
  src/applications/personalization/view-dependents/components/ViewDependentsHeader/ViewDependentsHeader.jsx
  src/applications/personalization/view-dependents/containers/ViewDependentsApp.jsx
  src/applications/personalization/view-dependents/layouts/ViewDependentsLayout.jsx
  src/applications/static-pages/dependency-verification/actions/index.js
  src/applications/static-pages/dependency-verification/components/dependencyVerificationFooter.jsx
  src/applications/static-pages/dependency-verification/components/dependencyVerificationHeader.jsx
  src/applications/static-pages/dependency-verification/components/dependencyVerificationModal.jsx
  src/applications/static-pages/dependency-verification/reducers/index.js
  src/applications/static-pages/dependency-verification/tests/dependency-verification.cypress.spec.js
  src/applications/static-pages/dependency-verification/tests/fixtures/diaries.json
  src/applications/static-pages/dependency-verification/utils.js
Labels: VSA

#17085 10-10CG POA Document Upload BE Integration
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/config/chapters/signAsRepresentative/uploadPOADocument.js
  src/applications/caregivers/config/form.js
  src/applications/caregivers/helpers.js
Labels: VSA, caregivers, enhancement, front end

#17145 NOD: Split up issues page
  src/applications/appeals/10182/components/AddIssuesField.jsx
  src/applications/appeals/10182/components/EligibleIssuesWidget.jsx
  src/applications/appeals/10182/components/IssueCard.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/content/additionalIssues.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/pages/additionalIssues.js
  src/applications/appeals/10182/pages/additionalIssuesIntro.js
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/components/AddIssuesField.unit.spec.jsx
  src/applications/appeals/10182/tests/components/EligibleIssuesWidget.unit.spec.jsx
  src/applications/appeals/10182/tests/fixtures/data/maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/minimal-test.json
  src/applications/appeals/10182/tests/fixtures/data/transformed-minimal-test.json
  src/applications/appeals/10182/tests/pages/additionalIssues.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/additionalIssuesIntro.unit.spec.js
  src/applications/appeals/10182/tests/pages/contestableIssues.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/submit.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17117 Update links from accesstocare.va.gov/sign-in-help to help desk + 711
  src/applications/auth/containers/AuthApp.jsx
  src/platform/static-data/SubmitSignInForm.jsx
  src/platform/user/profile/vap-svc/components/base/VAPServiceTransactionErrorBanner.jsx
Labels: VSA, front end

#17168 Staging Review Accessibility Fixes for 10-10CG POA work
  src/applications/caregivers/components/PreSubmitInfo/SignatureCheckbox.jsx
  src/applications/caregivers/components/PreSubmitInfo/SignatureInput.jsx
  src/applications/caregivers/config/chapters/signAsRepresentative/uploadPOADocument.js
  src/applications/caregivers/config/form.js
  src/applications/caregivers/sass/signatureBox.scss
Labels: 508/Accessibility, bug, caregivers, front end

#17170 24196 update chp31 routing
  src/applications/vre/28-1900/TODO.md
  src/applications/vre/28-1900/containers/FormApp.jsx
  src/applications/vre/28-1900/containers/IntroductionPage.jsx
  src/applications/vre/28-1900/routes.jsx
  src/applications/vre/28-1900/tests/e2e/chapter31-wizard.cypress.spec.js
Labels: VSA

#17187 Update copy
  src/applications/claims-status/components/StemDeniedDetails.jsx
Labels: VSA, front end

#17192 Srsuddath 24305 debounce suggestions
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: front end

#17226 NOD: Add area of disagreement pages
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/config/submit-transformer.js
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
  src/applications/appeals/10182/pages/areaOfDisagreement.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/10182-notice-of-disagreement.cypress.spec.js
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/10182/tests/fixtures/data/maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/minimal-test.json
  src/applications/appeals/10182/tests/fixtures/data/transformed-maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/transformed-minimal-test.json
  src/applications/appeals/10182/tests/nod.cypress.helpers.js
  src/applications/appeals/10182/tests/pages/areaOfDisagreement.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/submit.js
  src/applications/appeals/10182/utils/ui.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17225 Lower Typeahead Debounce threshold
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: VSA, front end

#17159 Create "Update tuition and housing estimates" component
  src/applications/gi-sandbox/components/AccordionDropdown.jsx
  src/applications/gi-sandbox/components/Dropdown.jsx
  src/applications/gi-sandbox/components/SearchResults.jsx
  src/applications/gi-sandbox/sass/partials/_gi-search-controls.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17231 NOD: Add opt-in page
  src/applications/appeals/10182/components/OptInWidget.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/content/OptIn.jsx
  src/applications/appeals/10182/pages/optIn.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/components/OptInWidget.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/optIn.unit.spec.jsx
Labels: NOD, VSA, front end, vsa-claims-appeals

#17207 Add Covid 19 scheduling links to facility search results
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/components/search-results-items/Covid19Result.jsx
  src/applications/facility-locator/components/search-results-items/common/Covid19PhoneLink.jsx
  src/applications/facility-locator/components/search-results-items/common/LocationDirectionsLink.jsx
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/components/search-results/common/Covid19PhoneLink.unit.spec.jsx
  src/applications/facility-locator/utils/selectors.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA, facility locator, front end

#17229 Sandbox search cleanup
  src/applications/gi-sandbox/components/SearchAccordion.jsx
  src/applications/gi-sandbox/components/SearchResults.jsx
  src/applications/gi-sandbox/containers/SearchSchools.jsx
  src/applications/gi-sandbox/containers/TuitionAndHousingEstimates.jsx
Labels: BAH

#17239 NOD: Add summary page
  src/applications/appeals/10182/components/ShowIssuesList.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/content/OptIn.jsx
  src/applications/appeals/10182/content/issueSummary.js
  src/applications/appeals/10182/pages/areaOfDisagreement.js
  src/applications/appeals/10182/pages/issueSummary.js
  src/applications/appeals/10182/tests/components/ShowIssuesList.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/issueSummary.unit.spec.jsx
Labels: NOD, VSA, front end, vsa-claims-appeals

#17245 NOD: Upload PDFs only
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/content/EvidenceUpload.jsx
  src/applications/appeals/10182/tests/fixtures/data/maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/transformed-maximal-test.json
Labels: NOD, VSA, front end, vsa-claims-appeals

#17255 NOD: Fix unique IDs & error messaging
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/ui.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17237 CT sandbox updated estimates selector to use institutions attributes
  src/applications/gi-sandbox/selectors/estimator.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17197 Comparison Tool Sandbox Name Search Autocomplete
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/PreviewBanner.jsx
  src/applications/gi-sandbox/components/SearchForm.jsx
  src/applications/gi-sandbox/components/search/KeywordSearch.jsx
  src/applications/gi-sandbox/components/search/SearchTabs.jsx
  src/applications/gi-sandbox/containers/GiBillApp.jsx
  src/applications/gi-sandbox/containers/LandingPage.jsx
  src/applications/gi-sandbox/containers/LocationSearchForm.jsx
  src/applications/gi-sandbox/containers/NameSearchForm.jsx
  src/applications/gi-sandbox/reducers/autocomplete.js
  src/applications/gi-sandbox/reducers/index.js
  src/applications/gi-sandbox/reducers/preview.js
  src/applications/gi-sandbox/reducers/search.js
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/tests/components/PreviewBanner.unit.spec.jsx
  src/applications/gi-sandbox/tests/components/SearchForm.unit.spec.jsx
  src/applications/gi-sandbox/tests/components/search/KeywordSearch.unit.spec.jsx
  src/applications/gi-sandbox/tests/components/search/SearchTabs.unit.spec.jsx
  src/applications/gi-sandbox/tests/containers/GiBillApp.unit.spec.jsx
  src/applications/gi-sandbox/tests/containers/LandingPage.unit.spec.jsx
  src/applications/gi-sandbox/tests/data/calculator-constants.json
  src/applications/gi-sandbox/tests/helpers.js
Labels: BAH, BAH-QA-needed

#16424 Updating the Nightwatch axeCheckJS helper method for e2e tests
  Jenkinsfile
  src/applications/burials/tests/00-all-fields.e2e.spec.js
  src/applications/pensions/tests/00-all-fields.e2e.spec.js
  src/platform/landing-pages/dev-template.ejs
  src/platform/site-wide/tests/sitemap/sample.spec.js
  src/platform/site-wide/tests/sitemap/sitemap-1.spec.js
  src/platform/site-wide/tests/sitemap/sitemap-2.spec.js
  src/platform/site-wide/tests/sitemap/sitemap-3.spec.js
  src/platform/site-wide/tests/sitemap/sitemap-4.spec.js
  src/platform/site-wide/tests/sitemap/sitemap-helpers.js
  src/platform/testing/e2e/nightwatch-commands/axeCheck.js
Labels: 508/Accessibility, testing

#17260 Vet center css fixes
  src/applications/static-pages/sass/modules/_m-facilities.scss
Labels: VSA, vet-center

#17273 23998 - update chapter 31 education question
  package.json
  src/applications/vre/28-1900/config/chapters/additional-information/additionalInformation.js
  src/applications/vre/28-1900/tests/config/additionalInformation.unit.spec.jsx
  src/applications/vre/28-1900/tests/e2e/formDataSets/chapter31-maximal.json
  yarn.lock
Labels: VSA

#17196 CT Redesign: Create/Update sandbox location search service #23654
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/MapboxClient.js
  src/applications/gi-sandbox/components/SearchResults.jsx
  src/applications/gi-sandbox/components/location/SearchResults.jsx
  src/applications/gi-sandbox/components/search/SearchTabs.jsx
  src/applications/gi-sandbox/constants.js
  src/applications/gi-sandbox/containers/GiBillApp.jsx
  src/applications/gi-sandbox/containers/LandingPage.jsx
  src/applications/gi-sandbox/containers/LocationSearchForm.jsx
  src/applications/gi-sandbox/containers/NameSearchForm.jsx
  src/applications/gi-sandbox/reducers/search.js
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-search-location.scss
  src/applications/gi-sandbox/utils/mapHelpers.js
  src/applications/gi-sandbox/utils/mapboxToken.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17289 Update expiration
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
Labels: HLR, VSA, front end, vsa-claims-appeals

#17261 Removed VRRAP UX feedback prodflags
  src/applications/edu-benefits/1990s/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990s/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990s/pages/application.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17272 add logic to clear suggestions
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: VSA, front end

#17274 Add yarn build:production
  README.md
  package.json
Labels: BAH

#17293 24311 update email validation
  src/applications/disability-benefits/686c-674/config/chapters/veteran-information/veteran-address/veteran-address.js
  src/applications/lgy/coe/config/chapters/applicant/applicantContactInformation.js
  src/applications/vre/28-1900/config/chapters/veteran/veteran-address/veteranAddress.js
  src/applications/vre/28-8832/config/chapters/claimant-information/claimantAddress.js
Labels: VSA

#17300 Remove POA attachment if yes/no/no is not yes
  src/applications/caregivers/helpers.js
  src/applications/caregivers/tests/e2e/fixtures/data/signAsRepresentativeNo.json
  src/applications/caregivers/tests/helpers.unit.spec.js
Labels: bug, caregivers, front end

#17285 Remove confirmation email from FSR
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/pages/veteran/contact.js
  src/applications/financial-status-report/tests/e2e/fixtures/data/maximal.json
  src/applications/financial-status-report/tests/e2e/fixtures/data/minimal.json
Labels: enhancement, front end, vsa-benefits-2

#17296 526: Submit clean mailingAddress
  src/applications/disability-benefits/all-claims/prefill-transformer.js
  src/applications/disability-benefits/all-claims/submit-transformer.js
  src/applications/disability-benefits/all-claims/tests/fixtures/data/maximal-test.json
  src/applications/disability-benefits/all-claims/tests/prefill-transformer.unit.spec.js
Labels: 526, VSA, front end, vsa-claims-appeals

#17302 25042 - zipcode restrict to 5 digits
  src/applications/vre/definitions/profileAddress.js
Labels: VSA

#17311 Fix NOD edit button overlap
  src/applications/appeals/10182/sass/10182-nod.scss
Labels: NOD, VSA, front end, vsa-claims-appeals

#17314 wrap payload in form convention
  src/applications/static-pages/dependency-verification/actions/index.js
Labels: VSA

#17262 Create unique IDs for array content
  src/platform/forms-system/src/js/fields/ObjectField.jsx
  src/platform/forms-system/test/js/fields/ObjectField.unit.spec.jsx
Labels: 508/Accessibility, NOD, VSA, vsa-claims-appeals

#17310 Hotfix/lazyload
  src/applications/login/containers/SignInApp.jsx
  src/platform/site-wide/user-nav/containers/Main.jsx
  src/platform/site-wide/user-nav/tests/containers/Main.unit.spec.jsx
Labels: Identity

#17323 NOD: Conditionally set additional issues view
  src/applications/appeals/10182/components/AddIssuesField.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/tests/components/AddIssuesField.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17295 23597: Add filter panel to ct sandbox
  src/applications/gi-sandbox/components/SearchResults.jsx
  src/applications/gi-sandbox/components/location/SearchResults.jsx
  src/applications/gi-sandbox/containers/Modals.jsx
  src/applications/gi-sandbox/containers/NameSearchForm.jsx
  src/applications/gi-sandbox/containers/RefineYourSearch.jsx
  src/applications/gi-sandbox/reducers/filters.js
  src/applications/gi-sandbox/utils/helpers.js
  src/applications/gi-sandbox/utils/search.js
Labels: BAH, BAH-QA-needed

#17332 23597: update filters on search and auto complete
  src/applications/gi-sandbox/containers/NameSearchForm.jsx
Labels: BAH

#17336 NOD: Maintain disagreement choices
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/pages/areaOfDisagreement.js
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
Labels: NOD, VSA, vsa-claims-appeals

#17342 Srsuddath improve typeahead clickthrough tracking
  src/applications/search/containers/SearchApp.jsx
Labels: VSA, front end

#17359 NOD: Update intro page content
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/containers/IntroductionPage.jsx
Labels: NOD, VSA, front end, vsa-claims-appeals

#17247 CT Redesign: Add Map control and update search results view for Location search #23686
  src/applications/gi-sandbox/components/location/SearchResults.jsx
  src/applications/gi-sandbox/tests/containers/LandingPage.unit.spec.jsx
Labels: BAH

#17370 NOD: Fix IE11 edit button placement
  src/applications/appeals/10182/sass/10182-nod.scss
Labels: NOD, VSA, front end, vsa-claims-appeals

#17363 CT Sandbox Location Results Loading Indicator
  src/applications/gi-sandbox/components/SearchResults.jsx
  src/applications/gi-sandbox/components/location/SearchResults.jsx
  src/applications/gi-sandbox/components/search/SearchResults.jsx
  src/applications/gi-sandbox/components/search/SearchTabs.jsx
  src/applications/gi-sandbox/containers/LandingPage.jsx
  src/applications/gi-sandbox/sass/partials/_gi-search-location.scss
  src/applications/gi-sandbox/tests/components/search/SearchTabs.unit.spec.jsx
Labels: BAH

#17286 CT Sandbox - Location autocomplete
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/Dropdown.jsx
  src/applications/gi-sandbox/components/search/KeywordSearch.jsx
  src/applications/gi-sandbox/components/search/LocationSearchResults.jsx
  src/applications/gi-sandbox/components/search/NameResults.jsx
  src/applications/gi-sandbox/components/search/SearchResults.jsx
  src/applications/gi-sandbox/components/search/SearchTabs.jsx
  src/applications/gi-sandbox/containers/LocationSearchForm.jsx
  src/applications/gi-sandbox/containers/NameSearchForm.jsx
  src/applications/gi-sandbox/containers/RefineYourSearch.jsx
  src/applications/gi-sandbox/containers/SearchPage.jsx
  src/applications/gi-sandbox/reducers/autocomplete.js
  src/applications/gi-sandbox/reducers/filters.js
  src/applications/gi-sandbox/reducers/search.js
  src/applications/gi-sandbox/routes.jsx
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-autocomplete.scss
  src/applications/gi-sandbox/tests/components/search/KeywordSearch.unit.spec.jsx
  src/applications/gi-sandbox/utils/helpers.js
Labels: BAH

#17373 Increase logging level for unit tests during PR builds
  Jenkinsfile
Labels: BAH

#17385 NOD: content updates
  src/applications/appeals/10182/components/AddIssuesField.jsx
  src/applications/appeals/10182/components/ContactInformation.jsx
  src/applications/appeals/10182/components/ReviewDescription.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/containers/ConfirmationPage.jsx
  src/applications/appeals/10182/content/OptIn.jsx
  src/applications/appeals/10182/content/additionalIssues.jsx
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/content/evidenceIntro.jsx
  src/applications/appeals/10182/content/hearingType.js
  src/applications/appeals/10182/content/issueSummary.js
  src/applications/appeals/10182/content/representative.js
  src/applications/appeals/10182/pages/additionalIssuesIntro.js
  src/applications/appeals/10182/pages/evidenceUpload.jsx
  src/applications/appeals/10182/pages/homeless.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/upload.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, vsa-claims-appeals

#17297 Vet center - "Nearby locations" should be retrieved from Lighthouse if not published
  src/applications/static-pages/facilities/vet-center/components/VetCenterImageSection.jsx
  src/applications/static-pages/facilities/vet-center/components/VetCenterInfoSection.jsx
  src/applications/static-pages/facilities/vet-center/createNearByVetCenters.jsx
  src/applications/static-pages/facilities/vet-center/nearByVetCenters.jsx
  src/applications/static-pages/static-pages-entry.js
Labels: VSA, front end, vet-center

#17397 NOD: Revert disagreement validation
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17396 25333 - re-insert videos into vre orientation
  src/applications/vre/28-1900/orientation/StepComponent.jsx
  src/applications/vre/28-1900/orientation/utils.js
Labels: VSA

#17340 Unbold FSR Benefits Labels
  src/applications/financial-status-report/components/Benefits.jsx
Labels: front end, vsa-benefits-2

#17394 Update Preferred Provider Checkbox Selection and State field for SearchResultCard
  src/applications/gi-sandbox/components/search/SearchResultCard.jsx
  src/applications/gi-sandbox/containers/RefineYourSearch.jsx
  src/applications/gi-sandbox/reducers/filters.js
  src/applications/gi-sandbox/utils/helpers.js
Labels: BAH, BAH-QA-needed

#17415 CT Redesign: Pins on location search map persist after selecting a smaller distance #25338
  src/applications/gi-sandbox/components/search/LocationSearchResults.jsx
Labels: BAH
