Repository department-of-veterans-affairs/vets-website, pull requests merged in 2021-10, with the labels that each got.

#18931 508 [SCREENREADER]: Hide progress button icons from screen-readers
  src/platform/forms-system/src/js/components/ProgressButton.jsx
  src/platform/forms-system/test/js/components/ProgressButton.unit.spec.jsx
Labels: 508/Accessibility, front end, vsa-claims-appeals, VSA

#18974 updates cerner url
  src/applications/login/components/VerifyPage.jsx
  src/platform/utilities/cerner/index.js
Labels: Identity

#19000 508: [COGNITIION, SCREEN READER] Add aria-attributes to sign in button
  src/applications/static-pages/cta-widget/components/CallToActionAlert.jsx
  src/applications/static-pages/cta-widget/components/messages/SignIn.jsx
  src/applications/static-pages/cta-widget/index.js
  src/applications/static-pages/cta-widget/tests/index.unit.spec.js
  src/platform/forms/save-in-progress/FormStartControls.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/forms/tests/save-in-progress/FormStartControls.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/SaveInProgressIntro.unit.spec.jsx
Labels: 508/Accessibility, front end, vsa-claims-appeals, VSA

#19020 Update content
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/UnauthContent/index.js
Labels: front end, VSA

#19015 HLR v2 content update
  src/applications/disability-benefits/996/content/contestedIssues.jsx
  src/applications/disability-benefits/996/pages/homeless.js
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/wizard/WizardContainer.unit.spec.jsx
  src/applications/disability-benefits/996/wizard/WizardContainer.jsx
Labels: front end, vsa-claims-appeals, VSA, HLR

#19032 Promote to prod
  src/applications/static-pages/ask-va/components/App/index.js
  src/applications/static-pages/ask-va/components/App/index.unit.spec.js
  src/applications/static-pages/ask-va/index.js
Labels: front end, VSA

#19051 HLR: Update link to other benefit addresses
  src/applications/disability-benefits/996/constants.js
Labels: 508/Accessibility, front end, vsa-claims-appeals, VSA, HLR

#19060 CST: Add link to mobile app store
  src/applications/claims-status/components/MobileAppMessage.jsx
  src/applications/claims-status/containers/YourClaimsPageV2.jsx
  src/applications/claims-status/tests/components/MobileAppMessage.unit.spec.jsx
Labels: enhancement, front end, claim status, vsa-claims-appeals, VSA
