Repository department-of-veterans-affairs/vets-website, pull requests merged in 2021-11, with the labels that each got.

#19246 CST: Show mobile alert in production
  src/applications/claims-status/components/MobileAppMessage.jsx
Labels: front end, claim status, vsa-claims-appeals, VSA

#19284 HLR: move wizard to `/start` in production
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/Form0996App.jsx
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/routes.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/hlr-wizard.cypress.spec.js
  src/applications/disability-benefits/996/tests/hlr.cypress.spec.js
  src/applications/disability-benefits/996/wizard/WizardContainer.jsx
  src/applications/disability-benefits/996/wizard/pages/legacyNo.jsx
Labels: front end, vsa-claims-appeals, VSA, HLR

#18764 Add AutoSuggest Field highlighting
  src/platform/forms-system/src/js/fields/AutosuggestField.jsx
  src/platform/forms-system/test/js/fields/AutosuggestField.unit.spec.jsx
Labels: enhancement, front end, vsa-claims-appeals, VSA, 526

#19296 update tests
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.unit.spec.jsx
  src/applications/search/tests/e2e/01-required.cypress.spec.js
  src/platform/site-wide/user-nav/tests/e2e/00-required.cypress.spec.js
Labels: front end, VSA

#19303 NOD: Fix issue card margins
  src/applications/appeals/10182/sass/10182-nod.scss
Labels: front end, vsa-claims-appeals, VSA, NOD

#19263 Removes v0 references
  src/applications/personalization/profile/components/account-security/AccountSecurityContent.jsx
  src/applications/personalization/profile/components/account-security/TwoFactorAuthorizationStatus.jsx
  src/applications/static-pages/cta-widget/components/messages/mvi/NotAuthorized.jsx
  src/applications/static-pages/cta-widget/index.js
  src/applications/verify/containers/VerifyApp.jsx
  src/platform/user/authentication/components/SessionTimeoutModal.jsx
  src/platform/user/authentication/components/SignInModal.jsx
  src/platform/user/authentication/utilities.js
  src/platform/user/tests/authentication/utilities.unit.spec.js
Labels: Identity, Tech Debt

#18466 Github Actions (daily-deploy) -- Enable daily deploy in github action for prod
  .github/workflows/continuous-integration.yml
  .github/workflows/daily-deploy-production.yml
  Jenkinsfile
Labels: DO NOT MERGE

#19312 32179: setLoginAttempted handled in "login" and reduce magic strings for auth events
  src/applications/disability-benefits/view-payments/components/IdentityNotVerified.jsx
  src/applications/hca/containers/IntroductionPage.jsx
  src/applications/login/components/VerifyPage.jsx
  src/applications/personalization/components/IdentityNotVerified.jsx
  src/applications/personalization/profile/components/account-security/TwoFactorAuthorizationStatus.jsx
  src/applications/personalization/profile/components/alerts/SetUpVerifiedIDMeAlert.jsx
  src/applications/static-pages/cta-widget/index.js
  src/applications/vre/28-1900/components/IdentityNotVerified.jsx
  src/platform/user/authentication/constants.js
  src/platform/user/authentication/utilities.js
  src/platform/user/tests/authentication/utilities.unit.spec.js
  src/platform/utilities/sso/index.js
  src/platform/utilities/tests/sso.unit.spec.js
Labels: Identity

#19254 Add header v2 styling and boilerplate
  src/applications/proxy-rewrite/partials/header.js
  src/platform/landing-pages/dev-template.ejs
  src/platform/site-wide/header/components/App/index.unit.spec.js
  src/platform/site-wide/header/components/Header/index.js
  src/platform/site-wide/header/components/Header/index.unit.spec.js
  src/platform/site-wide/header/components/Logo/index.js
  src/platform/site-wide/header/components/Logo/index.unit.spec.js
  src/platform/site-wide/header/components/LogoRow/index.js
  src/platform/site-wide/header/components/LogoRow/index.unit.spec.js
  src/platform/site-wide/header/components/LogoRow/styles.scss
  src/platform/site-wide/header/components/MenuItemLevel1/index.js
  src/platform/site-wide/header/components/MenuItemLevel1/index.unit.spec.js
  src/platform/site-wide/header/components/MenuItemLevel2/index.js
  src/platform/site-wide/header/components/MenuItemLevel2/index.unit.spec.js
  src/platform/site-wide/header/components/OfficialGovtWebsite/index.js
  src/platform/site-wide/header/components/OfficialGovtWebsite/index.unit.spec.js
  src/platform/site-wide/header/components/OfficialGovtWebsite/styles.scss
  src/platform/site-wide/header/components/SubMenu/index.js
  src/platform/site-wide/header/components/SubMenu/index.unit.spec.js
  src/platform/site-wide/header/components/VeteranCrisisLine/index.js
  src/platform/site-wide/header/components/VeteranCrisisLine/index.unit.spec.js
  src/platform/site-wide/header/containers/Menu/actions.js
  src/platform/site-wide/header/containers/Menu/actions.unit.spec.js
  src/platform/site-wide/header/containers/Menu/constants.js
  src/platform/site-wide/header/containers/Menu/index.js
  src/platform/site-wide/header/containers/Menu/index.unit.spec.js
  src/platform/site-wide/header/containers/Menu/reducer.js
  src/platform/site-wide/header/containers/Menu/reducer.unit.spec.js
  src/platform/site-wide/header/containers/Menu/styles.scss
  src/platform/site-wide/header/helpers/index.js
  src/platform/site-wide/header/index.cypress.spec.js
  src/platform/site-wide/header/index.js
  src/platform/site-wide/user-nav/components/SearchHelpSignIn.jsx
  src/platform/site-wide/user-nav/containers/Main.jsx
  src/platform/startup/store.js
  src/site/assets/img/header-logo-v2.png
Labels: front end, VSA

#19315 Add custom path parameter to `goToPath` function
  src/platform/forms-system/src/js/containers/FormPage.jsx
  src/platform/forms-system/src/js/routing.js
  src/platform/forms-system/test/js/containers/FormPage.unit.spec.jsx
  src/platform/forms-system/test/js/routing.unit.spec.js
Labels: front end, vsa-claims-appeals, VSA, HLR, NOD

#19334 Add force edit mode & callbacks to ContactInformationField
  src/platform/user/profile/vap-svc/components/ContactInformationField.jsx
  src/platform/user/profile/vap-svc/tests/components/ContactInformationField.unit.spec.jsx
Labels: front end, vsa-claims-appeals, VSA, HLR, NOD

#19338 Add medical copays CTA widget
  src/applications/static-pages/medical-copays-cta/components/App/index.js
  src/applications/static-pages/medical-copays-cta/components/App/index.unit.spec.js
  src/applications/static-pages/medical-copays-cta/index.js
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
Labels: front end, VSA

#19357 Kelsonic header v2 fixes
  src/applications/proxy-rewrite/proxy-rewrite-entry.jsx
  src/platform/site-wide/header/components/Header/index.js
  src/platform/site-wide/header/components/LogoRow/index.js
  src/platform/site-wide/header/components/LogoRow/styles.scss
  src/platform/site-wide/header/components/MenuItemLevel1/index.js
  src/platform/site-wide/header/components/SubMenu/index.js
  src/platform/site-wide/header/containers/Menu/index.js
  src/platform/site-wide/index.js
  src/platform/site-wide/legacy/menu.js
  src/platform/site-wide/va-footer/components/Footer.jsx
  src/platform/site-wide/va-footer/index.js
Labels: front end, VSA

#19342 Srsuddath dropdown updates
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
  src/applications/search/components/SearchDropdown/SearchDropdownStyles.scss
  src/applications/search/containers/SearchApp.jsx
  src/applications/search/search-entry.jsx
  src/platform/site-wide/header/containers/Menu/index.js
  src/platform/site-wide/header/containers/Menu/styles.scss
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
  src/platform/site-wide/user-nav/index.js
  src/platform/site-wide/user-nav/sass/user-nav.scss
Labels: front end, VSA

#19364 Reverts new Modal work
  src/applications/login/components/FedWarning.jsx
  src/applications/login/components/SignInButtons.jsx
  src/applications/login/containers/SignInApp.jsx
  src/platform/site-wide/user-nav/sass/user-nav.scss
  src/platform/user/authentication/components/SignInModal.jsx
Labels: Identity

#19369 Sentence case megamenu items
  src/platform/landing-pages/header-footer-data.json
Labels: front end, VSA

#19361 Srsuddath dropdown component consistency update
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
  src/applications/search/containers/SearchApp.jsx
  src/platform/site-wide/header/containers/Menu/index.js
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: front end, VSA

#19376 Bug: Fix invalid RegExp
  src/platform/forms-system/src/js/fields/AutosuggestField.jsx
  src/platform/forms-system/src/js/utilities/data/escapeRegExp.js
  src/platform/forms-system/test/js/fields/AutosuggestField.unit.spec.jsx
  src/platform/forms-system/test/js/utilities/escapeRegExp.unit.spec.js
Labels: bug, front end, vsa-claims-appeals, VSA, 526

#19363 add search-location flag
  src/applications/find-forms/actions/index.js
  src/applications/resources-and-support/components/SearchBar.jsx
  src/applications/resources-and-support/hooks/useGetSearchResults.js
  src/applications/search/actions/index.js
  src/applications/search/containers/SearchApp.jsx
  src/applications/yellow-ribbon/actions/index.js
  src/platform/site-wide/header/helpers/index.js
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: front end, VSA

#19343 31523: Remove validate-mhv-account application
  script/github-actions/select-cypress-tests.js
  src/applications/static-pages/cta-widget/constants.js
  src/applications/static-pages/cta-widget/index.js
  src/applications/validate-mhv-account/components/MessageTemplate.jsx
  src/applications/validate-mhv-account/components/errors/DeactivatedMHVId.jsx
  src/applications/validate-mhv-account/components/errors/GenericError.jsx
  src/applications/validate-mhv-account/components/errors/MultipleMHVIds.jsx
  src/applications/validate-mhv-account/components/errors/NeedsSSNResolution.jsx
  src/applications/validate-mhv-account/components/errors/NeedsVAPatient.jsx
  src/applications/validate-mhv-account/components/errors/VerificationFailed.jsx
  src/applications/validate-mhv-account/constants.js
  src/applications/validate-mhv-account/containers/CreateMHVAccount.jsx
  src/applications/validate-mhv-account/containers/CreateMHVAccountFailed.jsx
  src/applications/validate-mhv-account/containers/ErrorMessage.jsx
  src/applications/validate-mhv-account/containers/Main.jsx
  src/applications/validate-mhv-account/containers/UpgradeAccountFailed.jsx
  src/applications/validate-mhv-account/containers/UpgradeMHVAccount.jsx
  src/applications/validate-mhv-account/containers/ValidateMHVAccount.jsx
  src/applications/validate-mhv-account/containers/VerifyIdentity.jsx
  src/applications/validate-mhv-account/manifest.json
  src/applications/validate-mhv-account/routes.jsx
  src/applications/validate-mhv-account/validate-mhv-account-entry.jsx
Labels: Identity

#19326 26995 - Add 'submit-application' aria and id tag for proper accessibility screen reader operation
  src/applications/edu-benefits/0994/config/form.js
  src/applications/edu-benefits/0994/containers/PreSubmitInfo.jsx
  src/applications/edu-benefits/0994/tests/containers/PreSubmitInfo.unit.spec.jsx
  src/platform/forms-system/src/js/components/ProgressButton.jsx
  src/platform/forms-system/src/js/review/submit-states/ClientError.jsx
  src/platform/forms-system/src/js/review/submit-states/Default.jsx
  src/platform/forms-system/src/js/review/submit-states/Pending.jsx
  src/platform/forms-system/src/js/review/submit-states/Submitted.jsx
  src/platform/forms-system/src/js/review/submit-states/ThrottledError.jsx
  src/platform/forms-system/src/js/review/submit-states/ValidationError.jsx
  src/platform/forms-system/test/js/review/SubmitController.unit.spec.jsx
  src/platform/forms-system/test/js/review/submit-states/ClientError.unit.spec.jsx
  src/platform/forms-system/test/js/review/submit-states/Default.unit.spec.jsx
  src/platform/forms-system/test/js/review/submit-states/GenericError.unit.spec.jsx
  src/platform/forms-system/test/js/review/submit-states/Pending.unit.spec.jsx
  src/platform/forms-system/test/js/review/submit-states/Submitted.unit.spec.jsx
  src/platform/forms-system/test/js/review/submit-states/ThrottledError.unit.spec.jsx
  src/platform/forms-system/test/js/review/submit-states/ValidationError.unit.spec.jsx
  src/platform/forms/tests/forms.unit.spec.js
Labels: in progress

#19392 control focus and tweak aria labels
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19371 HLR: Add edit contact info page loop
  src/applications/disability-benefits/996/components/ContactInformation.jsx
  src/applications/disability-benefits/996/components/EditContactInfo.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/ContactInformation.unit.spec.jsx
  src/applications/disability-benefits/996/tests/fixtures/mocks/telephone-update-success.json
  src/applications/disability-benefits/996/tests/fixtures/mocks/telephone-update.json
  src/applications/disability-benefits/996/tests/fixtures/mocks/user.json
  src/applications/disability-benefits/996/tests/hlr-contact-loop.cypress.spec.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: front end, vsa-claims-appeals, VSA, HLR

#19389 Add boilerplate for events v2 app
  src/applications/static-pages/events/components/App/index.js
  src/applications/static-pages/events/components/App/index.unit.spec.js
  src/applications/static-pages/events/helpers/index.js
  src/applications/static-pages/events/helpers/index.unit.spec.js
  src/applications/static-pages/events/index.js
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: front end, VSA

#19408 Fix styling of header logo on safari
  src/platform/site-wide/header/components/LogoRow/styles.scss
Labels: front end, VSA

#19400 change headings
  src/applications/resources-and-support/components/ResourcesAndSupportSearchApp.jsx
  src/applications/resources-and-support/components/SearchBar.jsx
  src/applications/resources-and-support/components/SearchResult.jsx
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19409 Tweak styling and focus behavior
  src/platform/site-wide/header/components/MenuItemLevel1/index.js
  src/platform/site-wide/header/components/MenuItemLevel2/index.js
  src/platform/site-wide/header/containers/Menu/index.js
  src/platform/site-wide/header/containers/Menu/index.unit.spec.js
  src/platform/site-wide/header/containers/Menu/reducer.js
  src/platform/site-wide/header/containers/Menu/reducer.unit.spec.js
  src/platform/site-wide/header/containers/Menu/styles.scss
Labels: front end, VSA

#19407 32640: Disable login.gov auth when logging into MHV App
  src/applications/login/components/SignInButtons.jsx
  src/applications/login/containers/SignInApp.jsx
  src/platform/user/authentication/components/SignInModal.jsx
  src/platform/user/authentication/selectors.js
  src/platform/user/authentication/utilities.js
  src/platform/user/tests/authentication/utilities.unit.spec.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
  src/platform/utilities/sso/index.js
  src/platform/utilities/tests/sso.unit.spec.js
Labels: Identity

#19417 Tweak styling
  src/platform/site-wide/header/containers/Menu/styles.scss
Labels: front end, VSA

#19419 HLR v2: Update content
  src/applications/disability-benefits/996/components/ContactInformation.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
Labels: front end, vsa-claims-appeals, VSA, HLR

#19413 fix alignment issue on ie11
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
  src/applications/search/components/SearchDropdown/SearchDropdownStyles.scss
Labels: front end, VSA

#19416 32928: Login.gov - FIX GA Success Event | Add Correct Verify Copy
  src/applications/auth/containers/AuthApp.jsx
  src/applications/verify/containers/VerifyApp.jsx
Labels: Identity

#19424 fix tabbingg issue
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19337 [25411]: Add Self-Identifying Gender Identity (SIGI) to 10-10EZ
  package.json
  src/applications/hca/HealthCareApp.jsx
  src/applications/hca/config/chapters/vaBenefits/pensionInformation.js
  src/applications/hca/config/chapters/veteranInformation/birthSex.js
  src/applications/hca/config/chapters/veteranInformation/demographicInformation.js
  src/applications/hca/config/chapters/veteranInformation/maritalStatus.js
  src/applications/hca/config/chapters/veteranInformation/veteranGender.js
  src/applications/hca/config/form.js
  src/applications/hca/tests/components/DemographicField.unit.spec.jsx
  src/applications/hca/tests/config/veteranInformation.unit.spec.jsx
  src/applications/hca/tests/hca.cypress.spec.js
  src/applications/hca/tests/mocks/feature-toggles.json
  src/applications/hca/tests/schema/maximal-test.json
  src/platform/utilities/feature-toggles/featureFlagNames.js
  yarn.lock
Labels: front end, hca, caregivers

#19340 [30671]: SIGI American Indian feature toggle
  package.json
  src/applications/hca/HealthCareApp.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
  yarn.lock
Labels: front end, hca, caregivers

#19341 [30672]: SIGI American Indian page
  src/applications/hca/HealthCareApp.jsx
  src/applications/hca/config/chapters/veteranInformation/americanIndian.js
  src/applications/hca/config/form.js
Labels: front end, hca, caregivers

#19437 Srsuddath dropdown scrolling behavior
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19433 FIX: Verify signInMethod logic
  src/applications/verify/containers/VerifyApp.jsx
Labels: Identity

#19429 Kelsonic 32940 search header v2
  src/platform/site-wide/header/components/LogoRow/index.js
  src/platform/site-wide/header/components/LogoRow/index.unit.spec.js
  src/platform/site-wide/header/components/MenuItemLevel1/index.js
  src/platform/site-wide/header/components/MenuItemLevel1/index.unit.spec.js
  src/platform/site-wide/header/components/MenuItemLevel2/index.js
  src/platform/site-wide/header/components/MenuItemLevel2/index.unit.spec.js
  src/platform/site-wide/header/components/OfficialGovtWebsite/index.js
  src/platform/site-wide/header/components/OfficialGovtWebsite/index.unit.spec.js
  src/platform/site-wide/header/components/Search/index.js
  src/platform/site-wide/header/components/Search/index.unit.spec.js
  src/platform/site-wide/header/components/Search/styles.scss
  src/platform/site-wide/header/components/SubMenu/index.js
  src/platform/site-wide/header/components/SubMenu/index.unit.spec.js
  src/platform/site-wide/header/containers/Menu/index.js
  src/platform/site-wide/header/containers/Menu/index.unit.spec.js
  src/platform/site-wide/header/containers/Menu/styles.scss
  src/platform/site-wide/header/index.js
Labels: front end, VSA

#19443 update ally message
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19442 32908: 2 new flags for loginGov on unified sign in | Event updates
  src/applications/auth/containers/AuthApp.jsx
  src/applications/login/components/SignInButtons.jsx
  src/applications/login/containers/SignInApp.jsx
  src/platform/user/authentication/selectors.js
  src/platform/user/authentication/utilities.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: Identity

#19453 Kelsonic 33027 tweak header v2 auth
  src/platform/site-wide/header/components/LogoRow/styles.scss
  src/platform/site-wide/header/components/Search/index.js
Labels: front end, VSA

#19447 Update megamenu item
  src/platform/landing-pages/header-footer-data.json
  src/platform/site-wide/mega-menu/tests/megaMenu.cypress.spec.js
Labels: front end, VSA

#19461 Attempt to fix footer on proxy rewrites
  src/applications/proxy-rewrite/proxy-rewrite-entry.jsx
  src/platform/site-wide/va-footer/components/Footer.jsx
  src/platform/site-wide/va-footer/index.js
Labels: front end, VSA

#19467 re-add option tag
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19470 fix status message
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19471 Update a11y for search in header v2
  src/platform/site-wide/header/components/Search/index.js
Labels: front end, VSA

#19468 Fix to move info under page title
  src/applications/hca/config/chapters/vaBenefits/pensionInformation.js
Labels: bug, content, hca, caregivers

#19484 Srsuddath 32552 facilities health connect number
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/components/search-results-items/VaFacilityResult.jsx
  src/applications/facility-locator/components/search-results-items/common/LocationPhoneLink.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: front end, VSA

#19485 CST: Add OmniChannel link
  src/applications/claims-status/components/AskVAQuestions.jsx
  src/applications/claims-status/tests/components/AskVAQuestions.unit.spec.jsx
  src/applications/claims-status/tests/components/YourClaimsPageV2.unit.spec.jsx
  src/applications/claims-status/tests/components/appeals-v2/AppealHelpSidebar.unit.spec.jsx
  src/applications/claims-status/tests/components/appeals-v2/AppealInfo.unit.spec.jsx
  src/applications/claims-status/utils/omniChannel.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: enhancement, front end, claim status, vsa-claims-appeals, VSA

#19492 Srsuddath dropdown a11y fixes
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19496 Srsuddath dropdown a11y fixes
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19498 Add analytic events for header v2
  src/platform/site-wide/header/components/MenuItemLevel1/index.js
  src/platform/site-wide/header/components/MenuItemLevel2/index.js
  src/platform/site-wide/header/components/OfficialGovtWebsite/index.js
Labels: front end, VSA

#19499 fix focus issue
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19507 move prop to state
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19504 33189: ID.me Sign In Inline SVG
  src/platform/user/authentication/components/IDMeSVG.jsx
  src/platform/user/authentication/components/NewDesignButtons.jsx
Labels: Identity

#19530 turn off user agent autocomplete for input field
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19539 Add analytic events
  src/platform/site-wide/header/components/LogoRow/index.js
  src/platform/site-wide/header/components/SubMenu/index.js
Labels: front end, VSA
