Repository department-of-veterans-affairs/vets-website, pull requests merged in 2021-07, with the labels that each got.

#17616 Updating README local IP address instructions
  README.md
Labels: documentation

#17749 526: Use wizard action link
  src/applications/disability-benefits/wizard/WizardLink.jsx
Labels: 526, VSA, front end, vsa-claims-appeals

#17752 Update lgbt to lgbtq+
  src/platform/landing-pages/header-footer-data.json
Labels: VSA, front end

#17746 Fix facility feeback health when 0 values
  src/applications/static-pages/facilities/FacilityPatientSatisfactionScoresWidget.jsx
  src/applications/static-pages/tests/facilities/FacilityPatientSatisfactionScoresWidget.unit.spec.jsx
  src/applications/static-pages/tests/facilities/mockFacilitiesData.js
Labels: VSA, front end, vamc-facilities

#17742 Implemented walk-in availability to COVID 19 related search results
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/components/search-results-items/Covid19Result.jsx
  src/applications/facility-locator/components/search-results-items/common/Covid19PhoneLink.jsx
  src/applications/facility-locator/utils/featureFlagSelectors.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: front end

#17761 526: Update page title & breadcrumbs
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/components/IntroductionPage.jsx
  src/applications/disability-benefits/all-claims/constants.js
  src/applications/disability-benefits/all-claims/tests/containers/IntroductionPage.unit.spec.jsx
Labels: 526, VSA, front end, vsa-claims-appeals

#17623 Move save-in-progress link on review & submit page
  src/platform/forms/components/review/PreSubmitSection.jsx
  src/platform/forms/save-in-progress/RoutedSavableReviewPage.jsx
  src/platform/forms/tests/components/review/PreSubmitSection.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/RoutedSavableReviewPage.unit.spec.jsx
Labels: 508/Accessibility, VSA, front end

#17647 Reenable cypress for FSR
  src/applications/financial-status-report/tests/e2e/fsr-5655-wizard.cypress.spec.js
Labels: front end, testing, vsa-benefits-2

#17747 FSR Code Style
  src/applications/debt-letters/components/DebtLettersDownload.jsx
  src/applications/financial-status-report/actions/index.js
  src/applications/financial-status-report/components/AvailableDebts.jsx
  src/applications/financial-status-report/components/Benefits.jsx
  src/applications/financial-status-report/components/DebtCard.jsx
  src/applications/financial-status-report/components/EmploymentRecord.jsx
  src/applications/financial-status-report/components/FileUploader.jsx
  src/applications/financial-status-report/components/FinancialOverview.jsx
  src/applications/financial-status-report/components/GetFormHelp.jsx
  src/applications/financial-status-report/components/ResolutionDebtCards.jsx
  src/applications/financial-status-report/components/VeteranInfoBox.jsx
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/containers/App.jsx
  src/applications/financial-status-report/containers/ConfirmationPage.jsx
  src/applications/financial-status-report/containers/IntroductionPage.jsx
  src/applications/financial-status-report/pages/assets/other/records.js
  src/applications/financial-status-report/pages/assets/recreationalVehicles/records.js
  src/applications/financial-status-report/pages/assets/vehicles/records.js
  src/applications/financial-status-report/pages/expenses/repayments/records.js
  src/applications/financial-status-report/pages/veteran/contact.js
  src/applications/financial-status-report/wizard/WizardContainer.jsx
  src/applications/financial-status-report/wizard/components/Contacts.jsx
  src/applications/financial-status-report/wizard/pages/Appeals.jsx
  src/applications/financial-status-report/wizard/pages/Copays.jsx
  src/applications/financial-status-report/wizard/pages/Error.jsx
  src/applications/financial-status-report/wizard/pages/MakePayment.jsx
  src/applications/financial-status-report/wizard/pages/VetTec.jsx
  src/applications/financial-status-report/wizard/pages/Waivers.jsx
Labels: Tech Debt, front end, vsa-benefits-2

#17764 Add Nutrition, Podiatry, Caregiver support health services for search
  src/applications/facility-locator/config.js
  src/applications/facility-locator/tests/e2e/facilitySearch.cypress.spec.js
Labels: VSA, facility locator, front end

#17766 Profile page sections setup
  src/applications/gi-sandbox/components/IconWithInfo.jsx
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
  src/applications/gi-sandbox/components/profile/JumpLink.jsx
  src/applications/gi-sandbox/components/profile/ProfileSection.jsx
  src/applications/gi-sandbox/containers/ProfilePageHeader.jsx
  src/applications/gi-sandbox/sass/partials/_gi-profile-page.scss
  src/applications/gi-sandbox/utils/render.jsx
Labels: BAH, BAH-QA-needed

#17586 Srsuddath search UI overhaul 24988
  .husky/_/husky.sh
  src/applications/search/actions/index.js
  src/applications/search/components/SearchBreadcrumbs.jsx
  src/applications/search/containers/SearchApp.jsx
  src/applications/search/reducers/index.js
  src/applications/search/styles.scss
  src/applications/search/tests/e2e/00-required.cypress.spec.js
  src/applications/search/tests/search.pact.spec.js
  src/applications/search/utils.js
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
  src/platform/site-wide/user-nav/tests/e2e/00-required.cypress.spec.js
Labels: VSA, front end

#17731 508|NOD: Unique IDs in Array items
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
  src/applications/appeals/10182/pages/areaOfDisagreement.js
  src/platform/forms-system/src/js/components/FieldTemplate.jsx
  src/platform/forms-system/src/js/fields/ObjectField.jsx
  src/platform/forms-system/src/js/review/ReviewFieldTemplate.jsx
  src/platform/forms-system/src/js/widgets/TextWidget.jsx
  src/platform/forms-system/test/js/components/FieldTemplate.unit.spec.jsx
  src/platform/forms-system/test/js/fields/ObjectField.unit.spec.jsx
  src/platform/forms-system/test/js/review/ReviewFieldTemplate.unit.spec.jsx
  src/platform/forms-system/test/js/widgets/TextWidget.unit.spec.jsx
Labels: 508/Accessibility, NOD, VSA, front end, vsa-claims-appeals

#17748 CT Redesign: Add "Payments made to school" calculations to compare page
  src/applications/gi-sandbox/containers/ComparePage.jsx
  src/applications/gi-sandbox/selectors/compare.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17781 Update LocationSearchResults.jsx
  src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx
Labels: BAH

#17790 HLR: Validation error fix
  src/applications/disability-benefits/996/config/submit-transformer.js
  src/applications/disability-benefits/996/tests/fixtures/data/minimal-test.json
  src/applications/disability-benefits/996/tests/fixtures/data/one-conference-time-test.json
  src/applications/disability-benefits/996/tests/fixtures/data/transformed-minimal-test.json
  src/applications/disability-benefits/996/tests/fixtures/data/transformed-one-conference-time-test.json
  src/applications/disability-benefits/996/tests/schema/submit-transformer.unit.spec.js
  src/applications/disability-benefits/996/tests/validations/validations.unit.spec.js
  src/applications/disability-benefits/996/validations/index.js
Labels: HLR, VSA, front end, vsa-claims-appeals

#17801 Sandbox Institution profile cleanup
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
Labels: BAH

#17809 [508|NOD] Create unique aria-labels on edit buttons
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
  src/applications/appeals/10182/pages/areaOfDisagreement.js
Labels: 508/Accessibility, NOD, VSA, front end, vsa-claims-appeals

#17816 Sandbox switch to components for LearnMoreLabel and VetTecLogo
  src/applications/gi-sandbox/components/LearnMoreLabel.jsx
  src/applications/gi-sandbox/components/VetTecLogo.jsx
  src/applications/gi-sandbox/components/content/AdditionalResources.jsx
  src/applications/gi-sandbox/components/profile/BenefitsForm.jsx
  src/applications/gi-sandbox/components/profile/CalculateYourBenefitsForm.jsx
  src/applications/gi-sandbox/components/search/OnlineClassesFilter.jsx
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
  src/applications/gi-sandbox/containers/ComparePage.jsx
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
  src/applications/gi-sandbox/containers/VetTecEstimateYourBenefits.jsx
  src/applications/gi-sandbox/utils/render.jsx
Labels: BAH

#17778 Debt Letters Class to Functional Components
  src/applications/debt-letters/components/DebtDetails.jsx
  src/applications/debt-letters/components/DebtLetterCard.jsx
  src/applications/debt-letters/components/DebtLettersDownload.jsx
  src/applications/debt-letters/components/DebtLettersSummary.jsx
  src/applications/debt-letters/components/DebtLettersTable.jsx
  src/applications/debt-letters/components/DebtLettersWrapper.jsx
Labels: Tech Debt, front end, vsa-benefits-2

#17794 CT Redesign: Create "Getting started with benefits" component for profile page#26735
  src/applications/gi-sandbox/components/profile/GettingStartedWithBenefits.jsx
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-profile-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17836 508|NOD: Fix headers on area of disagreement page
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
Labels: 508/Accessibility, NOD, VSA, front end, vsa-claims-appeals

#17803 CT Redesign: Create "Academics" component for profile page #26820
  src/applications/gi-sandbox/components/content/modals/AccreditationModalContent.jsx
  src/applications/gi-sandbox/components/content/modals/CreditTrainingModalContent.jsx
  src/applications/gi-sandbox/components/content/modals/IndependentStudyModalContent.jsx
  src/applications/gi-sandbox/components/content/modals/PriorityEnrollmentModalContent.jsx
  src/applications/gi-sandbox/components/content/modals/SingleContactModalContent.jsx
  src/applications/gi-sandbox/components/content/modals/YellowRibbonModalContent.jsx
  src/applications/gi-sandbox/components/profile/Academics.jsx
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
  src/applications/gi-sandbox/components/profile/Programs.jsx
  src/applications/gi-sandbox/components/profile/SchoolLocations.jsx
  src/applications/gi-sandbox/constants.js
  src/applications/gi-sandbox/containers/Modals.jsx
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/utils/helpers.js
Labels: BAH

#17830 Deprecate AlertBox for va-alert on Debt Letters
  src/applications/debt-letters/components/DebtDetails.jsx
  src/applications/debt-letters/components/ErrorAlerts.jsx
  src/applications/debt-letters/sass/debt-letters.scss
Labels: Tech Debt, front end, vsa-benefits-2

#17834 CT Redesign: Create "Contact Information" component for profile page #26835
  src/applications/gi-sandbox/components/content/modals/FacilityCodeModalContent.jsx
  src/applications/gi-sandbox/components/content/modals/IpedsCodeModalContent.jsx
  src/applications/gi-sandbox/components/content/modals/OpeCodeModalContent.jsx
  src/applications/gi-sandbox/components/profile/ContactInformation.jsx
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
  src/applications/gi-sandbox/constants.js
  src/applications/gi-sandbox/containers/Modals.jsx
Labels: BAH

#17818 Remove redirect, add logic to handle empty searches
  src/applications/search/actions/index.js
  src/applications/search/containers/SearchApp.jsx
  src/applications/search/reducers/index.js
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
  src/platform/site-wide/user-nav/tests/e2e/00-required.cypress.spec.js
Labels: VSA, front end

#17823 Updated AlertBox to va-alert
  src/applications/financial-status-report/components/ErrorMessage.jsx
  src/applications/financial-status-report/tests/ErrorMessage.unit.spec.jsx
Labels: Tech Debt, front end, vsa-benefits-2

#17783 26290 remove ssn and va filenumber from chapter 31
  package.json
  src/applications/vre/28-1900/config/chapters/veteran/veteran-information/veteranInformation.js
  src/applications/vre/28-1900/tests/config/veteranInformation.unit.spec.js
  src/applications/vre/28-1900/tests/e2e/formDataSets/chapter31-maximal.json
  yarn.lock
Labels: VSA

#17843 Added ratings section to sandbox profile page
  src/applications/gi-sandbox/components/profile/SchoolCategoryRating.jsx
  src/applications/gi-sandbox/components/profile/SchoolRatings.jsx
  src/applications/gi-sandbox/sass/partials/_gi-profile-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17844 CT Redesign: Update visual elements of the search page based on UX feedback #27150
  src/applications/gi-sandbox/components/search/SearchTabs.jsx
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/containers/FilterYourResults.jsx
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
  src/applications/gi-sandbox/containers/TuitionAndHousingEstimates.jsx
  src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx
  src/applications/gi-sandbox/containers/search/NameSearchResults.jsx
  src/applications/gi-sandbox/sass/gi.scss
Labels: BAH

#17869 Remove covid sticky banner
  src/platform/site-wide/announcements/components/CovidVaccineSignUp.jsx
  src/platform/site-wide/announcements/config/index.js
  src/platform/site-wide/banners/components/Banners/index.js
Labels: VSA, front end

#17871 Remove disabled functionality from R&S search
  src/applications/resources-and-support/components/SearchBar.jsx
Labels: VSA, front end

#17762 526: Move initial route to `/start` page
  src/applications/disability-benefits/all-claims/containers/ITFWrapper.jsx
  src/applications/disability-benefits/all-claims/routes.jsx
  src/applications/disability-benefits/all-claims/tests/routes.unit.spec.js
  src/applications/disability-benefits/wizard/WizardLink.jsx
Labels: 526, VSA, front end, vsa-claims-appeals

#17831 NOD: Allow inline contact info updates
  src/applications/appeals/10182/components/ContactInformation.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/reducers/index.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/components/ContactInformation.unit.spec.jsx
  src/applications/appeals/10182/validations.js
  src/platform/user/profile/vap-svc/components/EmailField/EmailField.jsx
  src/platform/user/profile/vap-svc/components/PhoneField/PhoneField.jsx
  src/platform/user/profile/vap-svc/containers/VAPServiceProfileField.jsx
Labels: NOD, VSA, front end, vsa-claims-appeals

#17833 Caution flags and student complaints
  src/applications/gi-sandbox/components/content/modals/AllCampusesModalContent.jsx
  src/applications/gi-sandbox/components/content/modals/StudentComplaintsModalContent.jsx
  src/applications/gi-sandbox/components/profile/CautionaryInformation.jsx
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
  src/applications/gi-sandbox/containers/Modals.jsx
  src/applications/gi-sandbox/sass/partials/_gi-profile-page.scss
Labels: BAH

#17882 NOD: Use mobile over home phone
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/10182/tests/fixtures/mocks/user.json
Labels: NOD, VSA, front end, vsa-claims-appeals

#17879 Pre-need: Content updates & fixes
  src/applications/pre-need/components/IntroductionPage.jsx
  src/applications/pre-need/manifest.json
Labels: VSA, front end, pre-need, vsa-claims-appeals

#17877 CT Redesign: Add content for when no search results are displayed #23952
  src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx
  src/applications/gi-sandbox/containers/search/NameSearchResults.jsx
  src/applications/gi-sandbox/reducers/filters.js
  src/applications/gi-sandbox/selectors/filters.js
Labels: BAH

#17845 Update compare page content
  src/applications/gi-sandbox/components/CompareGrid.jsx
  src/applications/gi-sandbox/containers/ComparePage.jsx
Labels: BAH, BAH-QA-needed

#17865 Added vettec profile Page framework
  src/applications/gi-sandbox/components/profile/ContactInformation.jsx
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/containers/ProfilePageHeader.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17886 Add Original Issue section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: BAH

#17889 Replace `*` in ui:order
  src/applications/pre-need/tests/schema/error-example.json
  src/applications/pre-need/utils/helpers.js
Labels: VSA, bug, front end, pre-need, vsa-claims-appeals

#17876 Allow `*` in ui:order properties
  src/platform/forms-system/src/js/helpers.js
  src/platform/forms-system/src/js/review/ObjectField.jsx
  src/platform/forms-system/test/js/review/ObjectField.unit.spec.jsx
Labels: VSA, front end, pre-need, vsa-claims-appeals

#17864 CT Redesign: Update search result cards UI & content based on UX feedback #27177
  src/applications/gi-sandbox/components/SchoolClassification.jsx
  src/applications/gi-sandbox/containers/ProfilePageHeader.jsx
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
  src/applications/gi-sandbox/containers/search/NameSearchResults.jsx
  src/applications/gi-sandbox/sass/partials/_gi-search-page.scss
Labels: BAH

#17846 26436: Update form for legislative changes effective 8/1
  src/applications/edu-benefits/5490/components/BenefitSelectionWarning.jsx
  src/applications/edu-benefits/5490/components/applicantInformationUpdate.jsx
  src/applications/edu-benefits/5490/config/form.js
  src/applications/edu-benefits/5490/containers/PreSubmitInfo.jsx
  src/applications/edu-benefits/5490/helpers.jsx
  src/applications/edu-benefits/5490/tests/config/benefitHistory.unit.spec.jsx
  src/applications/edu-benefits/pages/schoolSelection.js
  src/applications/edu-benefits/utils/labels.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17848 [184] Upload Formatted Test Coverage Report to S3
  .github/workflows/daily-coverage-report.yml
  package.json
Labels: front end

#17912 526: Update to use `va-alert` WC
  src/applications/disability-benefits/all-claims/components/PaymentView.jsx
  src/applications/disability-benefits/all-claims/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/all-claims/containers/MissingServices.jsx
  src/applications/disability-benefits/all-claims/containers/RequiredServicesGate.jsx
  src/applications/disability-benefits/all-claims/content/adaptiveBenefits.jsx
  src/applications/disability-benefits/all-claims/content/addDisabilities.jsx
  src/applications/disability-benefits/all-claims/content/claimExamsInfo.jsx
  src/applications/disability-benefits/all-claims/content/confirmation-page.jsx
  src/applications/disability-benefits/all-claims/content/confirmation-poll.jsx
  src/applications/disability-benefits/all-claims/content/itfWrapper.jsx
  src/applications/disability-benefits/all-claims/content/ratedDisabilities.jsx
  src/applications/disability-benefits/all-claims/content/serviceTreatmentRecords.jsx
  src/applications/disability-benefits/all-claims/tests/components/PaymentView.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/containers/Form526EZApp.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/containers/RequiredServicesGate.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/adaptiveBenefits.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/addDisabilities.unit.spec.jsx
Labels: 526, VSA, front end, vsa-claims-appeals

#17892 CT Redesign: Add compare drawer functionality to profile page
  src/applications/gi-sandbox/containers/CompareDrawer.jsx
  src/applications/gi-sandbox/containers/ProfilePage.jsx
Labels: BAH

#17917 27204 migrate vsa-eben form apps va alert
  src/applications/disability-benefits/686c-674/config/chapters/veteran-information/veteran-information/VeteranInformationComponent.js
  src/applications/disability-benefits/686c-674/config/helpers.js
  src/applications/disability-benefits/686c-674/containers/IntroductionPage.jsx
  src/applications/disability-benefits/686c-674/sass/alertOverride.scss
  src/applications/disability-benefits/686c-674/sass/new-686.scss
  src/applications/disability-benefits/686c-674/tests/config/veteranInformation.unit.spec.jsx
  src/applications/lgy/coe/config/chapters/applicant/ApplicantInformationSummary.js
  src/applications/lgy/coe/sass/coe.scss
  src/applications/vre/28-1900/components/IdentityNotVerified.jsx
  src/applications/vre/28-1900/components/VeteranInformationViewComponent.jsx
  src/applications/vre/28-8832/config/chapters/claimant-information/staticClaimantComponent.jsx
  src/applications/vre/28-8832/containers/IntroductionPage.jsx
Labels: VSA

#17909 Add conditional display logic to the ratings functionality.
  src/applications/gi-sandbox/containers/ComparePage.jsx
  src/applications/gi-sandbox/containers/ProfilePageHeader.jsx
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
Labels: BAH, BAH-QA-needed

#17925 Sandbox Vet Tec Fixes
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/containers/ProfilePageHeader.jsx
Labels: BAH

#17927 26768 standardize input length on 686
  src/applications/disability-benefits/686c-674/config/chapters/add-a-child/child-information/child-information.js
  src/applications/disability-benefits/686c-674/config/chapters/report-dependent-death/dependent-information/dependentInformation.js
Labels: VSA

#17935 27444 update statelist for 686, ch31, ch36
  package.json
  src/applications/disability-benefits/686c-674/config/address-schema.js
  src/applications/vre/definitions/profileAddress.js
  yarn.lock
Labels: VSA

#17930 CT Redesign: Update Navigation controls on the profile page
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/BackToTop.jsx
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
  src/applications/gi-sandbox/components/profile/JumpLink.jsx
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/containers/CompareDrawer.jsx
  src/applications/gi-sandbox/containers/ProfilePage.jsx
  src/applications/gi-sandbox/reducers/compare.js
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-back-to-top.scss
Labels: BAH

#17904 [184] Move Upload Coverage Report Logic to CI GHA
  .github/workflows/continuous-integration.yml
  .github/workflows/daily-coverage-report.yml
  jenkins/common.groovy
Labels: front end

#17948 Remove PTSD questions from BDD flow
  src/applications/disability-benefits/all-claims/tests/fixtures/data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BDD, VSA, front end, vsa-claims-appeals

#17944 Add accordion-section-label to accordion analytics event
  src/applications/static-pages/subscribeAccordionEvents.js
  src/applications/static-pages/tests/subscribeAccordionEvents.unit.spec.js
  src/platform/site-wide/component-library-analytics-setup.js
Labels: VSA, front end

#17933 Profile: Update alert in edit modal
  src/applications/appeals/10182/components/ContactInformation.jsx
  src/platform/user/profile/vap-svc/components/PhoneField/PhoneField.jsx
  src/platform/user/profile/vap-svc/components/base/VAPServiceEditModal.jsx
  src/platform/user/profile/vap-svc/components/base/VAPServiceEditModalErrorMessage.jsx
  src/platform/user/profile/vap-svc/containers/VAPServiceProfileField.jsx
  src/platform/user/profile/vap-svc/tests/components/VAPServiceEditModalErrorMessage.unit.spec.jsx
  src/platform/user/profile/vap-svc/util/transactions.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17956 remove meta from title
  src/applications/search/constants/stub.json
  src/applications/search/containers/SearchApp.jsx
  src/applications/search/utils.js
Labels: VSA, front end

#17953 27572 add ga event chp31
  src/applications/vre/28-1900/orientation/StepComponent.jsx
Labels: VSA

#17961 HLR: Update to use `va-alert` WC
  src/applications/disability-benefits/996/content/contestableIssueAlerts.jsx
  src/applications/disability-benefits/996/content/contestedIssues.jsx
  src/applications/disability-benefits/996/tests/components/contestedIssues.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
Labels: HLR, VSA, front end, vsa-claims-appeals

#17954 NOD: Update content
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
  src/applications/appeals/10182/content/boardReview.js
  src/applications/appeals/10182/content/hearingType.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17958 Add aria-labelledBy to search landmark
  src/applications/search/containers/SearchApp.jsx
Labels: 508/Accessibility, VSA, front end

#17913 CT Sandbox - small screen/mobile component configuration
  src/applications/gi-sandbox/components/search/SearchTabs.jsx
  src/applications/gi-sandbox/containers/SearchPage.jsx
  src/applications/gi-sandbox/containers/search/LocationSearchForm.jsx
  src/applications/gi-sandbox/containers/search/NameSearchForm.jsx
Labels: BAH, BAH-QA-needed

#17966 CST: Update to use `va-alert` WC
  src/applications/claims-status/components/ClaimEstimate.jsx
  src/applications/claims-status/tests/e2e/01.claim-status-est-current.cypress.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status-est-past.cypress.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status-est.cypress.spec.js
Labels: VSA, claim status, front end, vsa-claims-appeals

#17975 NOD: Fix headers on review & submit page
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
Labels: 508/Accessibility, NOD, VSA, front end, vsa-claims-appeals

#17974 Dedupe search role landmarks in SearchApp
  src/applications/search/containers/SearchApp.jsx
Labels: 508/Accessibility, VSA, front end

#17952 Add Chapter 33 Alert Debt Letters
  src/applications/debt-letters/components/DebtLettersList.jsx
  src/applications/debt-letters/components/DebtLettersSummary.jsx
  src/applications/debt-letters/components/ExpandableAlert.jsx
  src/applications/debt-letters/sass/debt-letters.scss
  src/applications/debt-letters/sass/partials/_expandable-alert.scss
Labels: content, front end, vsa-benefits-2

#17980 Add alert spacing on debt letters ch33 alert
  src/applications/debt-letters/components/DebtLettersSummary.jsx
Labels: bug, front end, vsa-benefits-2

#17970 [184] Push Coverage Report to S3 Bucket instead of Upload/Download Artifact
  .github/workflows/continuous-integration.yml
  jenkins/common.groovy
Labels: front end

#17986 BDD: Revert removal of PTSD from flow
  src/applications/disability-benefits/all-claims/tests/fixtures/data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/maximal-bdd-test.json
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BDD, VSA, front end, vsa-claims-appeals

#17895 Bah 27258
  src/applications/edu-benefits/5490/helpers.jsx
  src/applications/gi-sandbox/components/vet-tec/GettingStartedWithVetTec.jsx
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/sass/partials/_gi-vet-tec.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17957 CT Redesign: Create VETTEC "Calculate your benefits" and "Approved programs" components
  src/applications/gi-sandbox/components/VetTecLogo.jsx
  src/applications/gi-sandbox/components/content/AdditionalResources.jsx
  src/applications/gi-sandbox/components/content/AdditionalResourcesLinks.jsx
  src/applications/gi-sandbox/components/vet-tec/VetTecApprovedProgramsList.jsx
  src/applications/gi-sandbox/containers/VetTecEstimateYourBenefits.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17992 26460: Remove production flags for 5490 update.
  src/applications/edu-benefits/5490/config/form.js
  src/applications/edu-benefits/5490/containers/PreSubmitInfo.jsx
  src/applications/edu-benefits/5490/helpers.jsx
  src/applications/edu-benefits/pages/schoolSelection.js
Labels: BAH

#17906 Debt Letters Refresh Bug
  src/applications/debt-letters/app-entry.jsx
  src/applications/debt-letters/components/DebtCardsList.jsx
  src/applications/debt-letters/components/DebtDetails.jsx
  src/applications/debt-letters/components/DebtLetterCard.jsx
  src/applications/debt-letters/components/DebtLettersDownload.jsx
  src/applications/debt-letters/components/ErrorAlerts.jsx
  src/applications/debt-letters/components/HowDoIPay.jsx
  src/applications/debt-letters/routes.js
  src/applications/debt-letters/tests/DebtCardsList.unit.spec.js
  src/applications/debt-letters/tests/DebtLettersDownload.unit.spec.js
Labels: bug, front end, vsa-benefits-2

#18012 Always show close
  src/platform/site-wide/banners/components/Banners/index.js
Labels: VSA, front end

#18000 update compare cards
  src/applications/gi-sandbox/containers/ComparePage.jsx
  src/applications/gi-sandbox/sass/partials/_gi-compare-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#18020 HLR: Move wizard to `/start` path
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/Form0996App.jsx
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/routes.jsx
  src/applications/disability-benefits/996/tests/containers/FormApp.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/hlr-wizard.cypress.spec.js
  src/applications/disability-benefits/996/tests/hlr.cypress.spec.js
  src/applications/disability-benefits/996/tests/routes.unit.spec.js
  src/applications/disability-benefits/996/tests/wizard/WizardContainer.unit.spec.jsx
  src/applications/disability-benefits/996/tests/wizard/utils.unit.spec.js
  src/applications/disability-benefits/996/wizard/WizardContainer.jsx
  src/applications/disability-benefits/996/wizard/pages/legacyNo.jsx
  src/applications/disability-benefits/996/wizard/utils.js
Labels: HLR, VSA, front end, vsa-claims-appeals

#18010 Deprecates v0 logins
  src/applications/login/components/VerifyPage.jsx
  src/platform/user/authentication/utilities.js
  src/platform/user/tests/authentication/utilities.unit.spec.js
Labels: Identity

#16431 Add review & submit error links
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/pages/retirementPay.js
  src/applications/disability-benefits/all-claims/reviewErrors.js
  src/applications/disability-benefits/all-claims/validations.js
  src/platform/forms-system/docs/images/custom-review-error-text.png
  src/platform/forms-system/docs/images/error-text-based-on-error-name.png
  src/platform/forms-system/docs/reviewErrors.md
  src/platform/forms-system/src/js/review/ArrayField.jsx
  src/platform/forms-system/src/js/review/ReviewChapters.jsx
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
  src/platform/forms-system/src/js/review/SubmitButtons.jsx
  src/platform/forms-system/src/js/review/SubmitController.jsx
  src/platform/forms-system/src/js/review/submit-states/ErrorLinks.jsx
  src/platform/forms-system/src/js/review/submit-states/ValidationError.jsx
  src/platform/forms-system/src/js/utilities/data/reduceErrors.js
  src/platform/forms-system/src/js/utilities/review/index.js
  src/platform/forms-system/src/js/utilities/ui/index.js
  src/platform/forms-system/test/js/review/ArrayField.unit.spec.jsx
  src/platform/forms-system/test/js/review/SubmitButtons.unit.spec.jsx
  src/platform/forms-system/test/js/review/submit-states/ErrorLinks.unit.spec.jsx
  src/platform/forms-system/test/js/review/submit-states/ValidationError.unit.spec.jsx
  src/platform/forms-system/test/js/utilities/reduceErrors.unit.spec.js
  src/platform/forms-system/test/js/utilities/ui.unit.spec.js
  src/platform/forms/components/review/FormSaveErrorMessage.jsx
  src/platform/forms/tests/forms.unit.spec.js
Labels: 508/Accessibility, 526, BDD, VSA, front end, vsa-claims-appeals

#18018 Sandbox demo fixes
  src/applications/gi-sandbox/components/BackToTop.jsx
  src/applications/gi-sandbox/containers/CompareDrawer.jsx
  src/applications/gi-sandbox/containers/ComparePage.jsx
  src/applications/gi-sandbox/containers/SearchPage.jsx
  src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx
  src/applications/gi-sandbox/reducers/search.js
  src/applications/gi-sandbox/routes.jsx
  src/applications/gi-sandbox/sass/partials/_gi-search-location.scss
  src/applications/gi-sandbox/selectors/search.js
Labels: BAH

#17951 24707: Update name search results display on mobile viewports
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
  src/applications/gi-sandbox/containers/search/NameSearchResults.jsx
  src/applications/gi-sandbox/sass/partials/_gi-search-page.scss
Labels: BAH, BAH-QA-needed

#17984 CT Redesign: Update location search results display on mobile viewports
  src/applications/gi-sandbox/containers/SearchPage.jsx
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
  src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-search-form.scss
  src/applications/gi-sandbox/sass/partials/_gi-search-location.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#18044 526: Add alert for Veteran's missing DOB
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/containers/MissingServices.jsx
  src/applications/disability-benefits/all-claims/tests/containers/Form526EZApp.unit.spec.jsx
Labels: 526, VSA, front end, vsa-claims-appeals

#17999 Kelsonic 25036 react widget config
  src/applications/static-pages/widgetTypes.js
  src/platform/site-wide/cta-widget/constants.js
  src/platform/site-wide/cta-widget/ctaWidgets.js
  src/platform/site-wide/cta-widget/helpers.js
  src/platform/site-wide/cta-widget/index.js
  src/platform/site-wide/cta-widget/tests/ctaWidgets.unit.spec.js
  src/platform/site-wide/cta-widget/tests/helpers.unit.spec.js
  src/platform/site-wide/cta-widget/tests/index.unit.spec.js
Labels: VSA, front end, work-in-progress

#18045 Bah 28005
  src/applications/gi-sandbox/components/profile/CalculateYourBenefitsForm.jsx
  src/applications/gi-sandbox/containers/ProfilePageHeader.jsx
  src/applications/gi-sandbox/sass/partials/_gi-profile-page.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#18069 27357: [MCP] copays page footer
  src/applications/medical-copays/components/Balances.jsx
  src/applications/medical-copays/components/GetHelp.jsx
  src/applications/medical-copays/components/OverviewPage.jsx
  src/applications/medical-copays/components/StatusAlert.jsx
  src/applications/medical-copays/containers/DetailPage.jsx
  src/applications/medical-copays/containers/MedicalCopaysApp.jsx
  src/applications/medical-copays/containers/OverviewPage.jsx
  src/applications/medical-copays/routes.jsx
  src/applications/medical-copays/utils/helpers.js
Labels: MCP, vsa-benefits-2

#18081 27356: [MCP] copay balance alert
  src/applications/medical-copays/components/StatusAlert.jsx
  src/applications/medical-copays/containers/OverviewPage.jsx
  src/applications/medical-copays/sass/medical-copays.scss
  src/applications/medical-copays/sass/partials/_expandable-alert.scss
Labels: MCP, vsa-benefits-2
