Repository department-of-veterans-affairs/vets-website, pull requests merged in 2021-04, with the labels that each got.

#16615 1990s: add missing entryName to app-entry.jsx
  src/applications/edu-benefits/1990s/app-entry.jsx
Labels: BAH

#16600 22198: Update spacing based off UX feedback
  src/applications/claims-status/components/StemDeniedDetails.jsx
Labels: BAH

#16479 Add initial yes/no page for 10-10CG POA
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/config/chapters/signAsRepresentative/signAsRepresentativeYesNo.js
  src/applications/caregivers/config/form.js
  src/applications/caregivers/definitions/constants.js
Labels: caregivers, front end

#16611 [508 Focus management ]526: Focus document type select after upload
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 508/Accessibility, BDD, VSA, front end, vsa-claims-appeals

#16610 Bah 22068
  src/applications/edu-benefits/1990s/containers/IntroductionPage.jsx
Labels: BAH, BAH-QA-needed

#16624 Update createEmbedYouTubeVideoURL method to add in missing www
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
Labels: VSA, front end

#16566 22194: Update spacing for 0994 under date selection
  src/applications/edu-benefits/0994/content/militaryService.jsx
Labels: BAH

#16599 Update vets-json-schema
  package.json
  src/applications/edu-benefits/10203/tests/pages/personalInformation.unit.spec.jsx
  src/applications/edu-benefits/1990/config/form.js
  src/applications/edu-benefits/1990/tests/config/contactInformation.unit.spec.jsx
  src/applications/edu-benefits/1990/tests/config/secondaryContact.unit.spec.jsx
  src/applications/edu-benefits/1990e/config/form.js
  src/applications/edu-benefits/1995/config/form.js
  src/applications/edu-benefits/tests/pages/contactInformation.unit.spec.jsx
  yarn.lock
Labels: BAH

#16637 Updated root url and breadcrumbs for 1990s VRRAP
  src/applications/edu-benefits/1990s/manifest.json
  src/applications/registry.json
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16651 DT-14432 - Adding logic for using form name translation in es
  src/site/layouts/va_form.drupal.liquid
Labels: 508/Accessibility, VSA, front end

#16632 1990s confirmation
  src/applications/edu-benefits/1990s/config/form.js
  src/applications/edu-benefits/1990s/containers/ConfirmationPage.jsx
  src/applications/edu-benefits/1990s/sass/1990s.scss
  src/applications/edu-benefits/1990s/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/edu-benefits/components/ConfirmationPageContent.jsx
Labels: BAH

#16643 [COGNITION]: Split up upload pages
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/evidenceTypesBDD.jsx
  src/applications/disability-benefits/all-claims/content/fileUploadDescriptions.jsx
  src/applications/disability-benefits/all-claims/content/privateMedicalRecords.jsx
  src/applications/disability-benefits/all-claims/pages/additionalDocuments.js
  src/applications/disability-benefits/all-claims/pages/evidenceTypesBDD.js
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/privateMedicalRecords.js
  src/applications/disability-benefits/all-claims/pages/privateMedicalRecordsAttachments.js
  src/applications/disability-benefits/all-claims/pages/serviceTreatmentRecords.js
  src/applications/disability-benefits/all-claims/pages/serviceTreatmentRecordsAttachments.js
  src/applications/disability-benefits/all-claims/tests/pages/privateMedicalRecords.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/privateMedicalRecordsAttachments.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/serviceTreatmentRecords.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/serviceTreatmentRecordsAttachments.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 508/Accessibility, 526, BDD, VSA, front end, vsa-claims-appeals

#16602 Add wrapping ul tags
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/LegacyContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/UnauthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/UnauthContent/index.js
Labels: VSA, front end

#16622 1990S - Form updates
  src/applications/edu-benefits/10203/pages/directDeposit.js
  src/applications/edu-benefits/1990s/content/directDeposit.jsx
  src/applications/edu-benefits/1990s/pages/application.js
  src/applications/edu-benefits/1990s/submit-transformer.js
Labels: BAH

#16639 update text
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/config/chapters/primary/hasPrimaryCaregiver.js
  src/applications/caregivers/config/chapters/secondaryOne/hasSecondaryCaregiver.js
  src/applications/caregivers/sass/caregivers.scss
  src/applications/caregivers/sass/label.scss
Labels: caregivers, content, front end

#16669 VRRAP: Update Form Page Content #22658
  src/applications/edu-benefits/1990s/config/form.js
  src/applications/edu-benefits/1990s/pages/application.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16664 Updated Intro page content
  src/applications/edu-benefits/1990s/containers/IntroductionPage.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16648 Refactor and Fix Search This Area Button
  src/applications/facility-locator/components/SearchAreaControl.jsx
  src/applications/facility-locator/containers/FacilitiesMap.jsx
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/e2e/map-zoom.cypress.spec.js
  src/applications/facility-locator/utils/SearchAreaControl.js
  src/applications/facility-locator/utils/helpers.jsx
Labels: VSA, facility locator, front end

#16557 10-10CG POA Document Upload
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/config/chapters/signAsRepresentative/signAsRepresentativeYesNo.js
  src/applications/caregivers/config/chapters/signAsRepresentative/uploadPOADocument.js
  src/applications/caregivers/config/form.js
  src/applications/caregivers/definitions/constants.js
Labels: caregivers, front end

#16641 Add selected props to radio widgets
  src/platform/forms-system/src/js/widgets/RadioWidget.jsx
  src/platform/forms-system/src/js/widgets/YesNoWidget.jsx
  src/platform/forms-system/test/js/widgets/RadioWidget.unit.spec.jsx
  src/platform/forms-system/test/js/widgets/YesNoWidget.unit.spec.jsx
Labels: 508/Accessibility, 526, BDD, VSA, front end, vsa-claims-appeals

#16673 VACMS-4850: Removing admin taxonomy fields from graphql that will be removed from cms.
  src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
  src/site/stages/build/drupal/graphql/taxonomy-fragments/administration.taxonomy.graphql.js
Labels: cms

#16695 Added authorized users only functionality to VRRAP
  src/applications/edu-benefits/0994/Form0994App.jsx
  src/applications/edu-benefits/0994/tests/containers/EducationGate.unit.spec.jsx
  src/applications/edu-benefits/1990s/containers/App.jsx
  src/applications/edu-benefits/1990s/containers/IntroductionPage.jsx
  src/applications/edu-benefits/containers/EducationGate.jsx
  src/platform/site-wide/cta-widget/helpers.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16670 VRRAP: Update Review Page #22658
  src/applications/edu-benefits/1990s/config/form.js
  src/applications/edu-benefits/1990s/containers/PreSubmitInfo.jsx
  src/applications/edu-benefits/1990s/pages/application.js
  src/applications/edu-benefits/1990s/submit-transformer.js
  src/applications/edu-benefits/1990s/tests/containers/PreSubmitInfo.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#16629 Vet Center main page - Locations and contact information section (address, image, static map, hours)
  src/applications/facility-locator/tests/helpers/formatHours.unit.spec.js
  src/applications/facility-locator/utils/formatHours.js
  src/applications/static-pages/facilities/createFacilityPage.js
  src/applications/static-pages/facilities/createVetCentersHours.jsx
  src/applications/static-pages/facilities/vetCentersHours.jsx
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/tests/facilities/vetCenterHours.unit.spec.jsx
  src/site/filters/liquid.js
  src/site/includes/image_and_static_map.liquid
  src/site/includes/vet_center_hours.liquid
  src/site/layouts/health_care_local_facility.drupal.liquid
  src/site/layouts/vet_center.drupal.liquid
  src/site/stages/build/drupal/graphql/vetCenter.graphql.js
  src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js
Labels: VSA, front end, vet-center

#16705 remove duplicate section from review page
  src/applications/vre/28-1900/config/form.js
Labels: VSA

#16704 Chapter 31 add feature gate to app page
  src/applications/vre/28-1900/constants.js
  src/applications/vre/28-1900/containers/App.jsx
  src/applications/vre/28-1900/containers/OrientationWizardContainer.jsx
  src/applications/vre/28-1900/tests/e2e/chapter31-maximal.cypress.spec.js
Labels: VSA

#16667 Change all secondary buttons to va action links on CLP
  package.json
  src/applications/static-pages/sass/static-pages.scss
  src/site/layouts/campaign_landing_page.drupal.liquid
  yarn.lock
Labels: VSA, front end

#16711 Chapter 31 fix additional info bug
  src/applications/vre/28-1900/config/chapters/additional-information/additionalInformation.js
Labels: VSA

#16714 added a null check to country in helpers
  src/applications/gi/utils/helpers.js
Labels: BAH, BAH-QA-needed

#16689 Add representative signature on review page
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/SignatureCheckbox.jsx
  src/applications/caregivers/components/PreSubmitInfo/SignatureInput.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/config/chapters/signAsRepresentative/signAsRepresentativeYesNo.js
  src/applications/caregivers/config/chapters/signAsRepresentative/uploadPOADocument.js
  src/applications/caregivers/definitions/content.js
Labels: caregivers, enhancement, front end

#16716 Letters: Remove progressbar role from header wrap
  src/applications/letters/components/StepHeader.jsx
  src/applications/letters/tests/components/StepHeader.unit.spec.jsx
Labels: 508/Accessibility, VSA, front end, va-letters, vsa-claims-appeals

#16723 22668 chp31 content updates
  src/applications/vre/28-1900/config/chapters/communication-preferences/helpers.js
  src/applications/vre/28-1900/config/chapters/veteran/veteran-information/veteranInformation.js
  src/applications/vre/28-1900/containers/IntroductionPage.jsx
  src/applications/vre/28-1900/containers/OrientationWizardContainer.jsx
  src/applications/vre/28-1900/orientation/OrientationApp.jsx
  src/applications/vre/28-1900/orientation/utils.js
  src/applications/vre/28-1900/wizard/pages/service-member/02-noVaMemorandum.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/02-yesVaMemorandum.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-yesIDES.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/02-yesDisabilityRating.jsx
  src/applications/vre/28-8832/containers/IntroductionPage.jsx
  src/applications/vre/components/GetFormHelp.jsx
Labels: VSA

#16724 1990s form updates
  src/applications/edu-benefits/1990s/pages/application.js
  src/applications/registry.json
Labels: BAH

#16697 22126: Frontend modifications to support 1990s prefill
  src/applications/edu-benefits/1990s/config/form.js
  src/applications/edu-benefits/1990s/prefill-transformer.js
Labels: BAH, BAH-QA-needed

#16734 Update POA Content on 10-10CG
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/config/chapters/signAsRepresentative/signAsRepresentativeYesNo.js
  src/applications/caregivers/config/chapters/signAsRepresentative/uploadPOADocument.js
  src/applications/caregivers/definitions/content.js
Labels: content, front end

#16728 22970: Update OMBInfo to be specific to 1990s
  src/applications/edu-benefits/1990s/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990s/content/OMBInfo.jsx
Labels: BAH, BAH-QA-needed

#16733 NOD: Build & Test api endpoints
  src/applications/appeals/10182/actions/index.js
  src/applications/appeals/10182/components/VeteranInformation.jsx
  src/applications/appeals/10182/config/prefill-transformer.js
  src/applications/appeals/10182/config/submit-transformer.js
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/ConfirmationPage.jsx
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/helpers.js
  src/applications/appeals/10182/reducers/contestableIssues.js
  src/applications/appeals/10182/reducers/index.js
  src/applications/appeals/10182/tests/actions/actions.unit.spec.js
  src/applications/appeals/10182/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/10182/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/appeals/10182/tests/fixtures/data/maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/transformed-maximal-test.json
  src/applications/appeals/10182/tests/schema/prefill-transformer.unit.spec.js
  src/applications/appeals/10182/tests/schema/submit-transformer.unit.spec.js
  src/applications/appeals/10182/tests/utils/dates.unit.spec.js
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/utils/dates.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/validations.js
  src/applications/registry.json
Labels: NOD, VSA, front end, vsa-claims-appeals

#16750 Fix Content Typos on 10-10cg POA
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/config/chapters/signAsRepresentative/signAsRepresentativeYesNo.js
Labels: caregivers, content, front end

#16727 Letters: clean up progress header
  src/applications/letters/components/StepHeader.jsx
  src/applications/letters/containers/DownloadLetters.jsx
  src/applications/letters/tests/components/StepHeader.unit.spec.jsx
Labels: 508/Accessibility, VSA, front end, va-letters, vsa-claims-appeals

#16708 Add "Need Help" footer to VRRAP/1990S intro page
  src/applications/edu-benefits/1990s/config/form.js
Labels: BAH

#16767 1990s: Auto-Fill not working for all users on Staging #23124
  src/applications/edu-benefits/1990s/prefill-transformer.js
  src/applications/edu-benefits/1990s/tests/prefill-transformer.unit.spec.js
  src/applications/edu-benefits/1990s/tests/schema/prefillData.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16769 23130: Update text for 1990s Program information section
  src/applications/edu-benefits/1990s/pages/application.js
Labels: BAH, BAH-QA-needed

#16745 DT-18438 adding aria attributes Find Forms
  src/applications/find-forms/components/FindVaForms.jsx
Labels: 508/Accessibility

#16762 Update claim list styling
  src/applications/claims-status/components/StemClaimListItem.jsx
  src/applications/claims-status/components/appeals-v2/AppealListItemV2.jsx
  src/applications/claims-status/components/appeals-v2/ClaimsListItemV2.jsx
  src/applications/claims-status/sass/claims-status.scss
  src/applications/claims-status/tests/e2e/00.claims-list.e2e.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status-decision.e2e.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status-est-current.e2e.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status-est-past.e2e.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status-est.e2e.spec.js
  src/applications/claims-status/tests/e2e/01.claim-status.e2e.spec.js
  src/applications/claims-status/tests/e2e/02.claim-files.e2e.spec.js
  src/applications/claims-status/tests/e2e/03.claim-details.e2e.spec.js
  src/applications/claims-status/tests/e2e/04.claim-ask-va.e2e.spec.js
  src/applications/claims-status/tests/e2e/05.claim-additional-evidence.e2e.spec.js
  src/applications/claims-status/tests/e2e/05.claim-document-request.e2e.spec.js
  src/applications/claims-status/tests/e2e/06-claim-estimation-breadcrumb.e2e.spec.js
  src/applications/claims-status/tests/e2e/06.claim-estimation.e2e.spec.js
Labels: BAH

#16784 Remove trailing chevrons from action links
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#16779 NOD: Add various pages
  src/applications/appeals/10182/components/EligibleIssuesWidget.jsx
  src/applications/appeals/10182/components/IssueCards.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/IntroductionPage.jsx
  src/applications/appeals/10182/content/OptIn.jsx
  src/applications/appeals/10182/content/boardReview.js
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/manifest.json
  src/applications/appeals/10182/pages/boardReview.js
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/pages/hasRep.js
  src/applications/appeals/10182/pages/homeless.js
  src/applications/appeals/10182/pages/repInfo.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/appeals/10182/tests/fixtures/data/transformed-maximal-test.json
  src/applications/appeals/10182/validations.js
  src/applications/registry.json
Labels: NOD, VSA, front end, vsa-claims-appeals

#16796 Add new footer link
  src/platform/landing-pages/header-footer-data.json
  src/platform/static-data/footer-links.json
Labels: VSA, front end

#16788 Updates Cerner staging URL
  src/applications/personalization/dashboard/tests/components/cerner-widgets.unit.spec.js
  src/platform/user/authentication/utilities.js
  src/platform/utilities/cerner/index.js
  src/platform/utilities/tests/sso.unit.spec.js
Labels: Identity

#16786 VRRAP: Update content based on DEPO midpoint review #23138
  src/applications/edu-benefits/1990s/components/PaymentReviewView.jsx
  src/applications/edu-benefits/1990s/components/PaymentView.jsx
  src/applications/edu-benefits/1990s/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990s/content/directDeposit.jsx
  src/applications/edu-benefits/1990s/pages/application.js
  src/applications/edu-benefits/1990s/pages/directDeposit.jsx
  src/applications/edu-benefits/1990s/prefill-transformer.js
  src/applications/edu-benefits/1990s/tests/schema/prefillData.js
  src/applications/edu-benefits/1990s/utils.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16751 School Ratings: Update google analytics tracking of ratings accordions #22199
  src/applications/gi/components/profile/SchoolCategoryRating.jsx
  src/applications/gi/tests/components/profile/SchoolCategoryRating.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#16804 20138: Removal of edu_form_omb_and_expiration feature flag
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#16793 DT-23068 - Added application to codeowners before work starts.
  .github/CODEOWNERS
Labels: VSA, front end

#16813 Handle malformed data in phoneNumberArrayToObject filter
  src/site/filters/phoneNumberArrayToObject.js
  src/site/filters/tests/phoneNumberArrayToObject.spec.js
Labels: VSA, front end, vamc-facilities

#16790 [COGNITION]: STEM Automated Decision - Consider adding an aria-describedby to the inside/outside US parentheticals
  src/applications/claims-status/components/StemAskVAQuestions.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16802 23017 Chapter 31 - put form and orientation on separate routes
  src/applications/vre/28-1900/components/FormInProgressNotification.jsx
  src/applications/vre/28-1900/constants.js
  src/applications/vre/28-1900/containers/App.jsx
  src/applications/vre/28-1900/containers/FormApp.jsx
  src/applications/vre/28-1900/containers/IntroductionPage.jsx
  src/applications/vre/28-1900/containers/OrientationWizardContainer.jsx
  src/applications/vre/28-1900/orientation/OrientationApp.jsx
  src/applications/vre/28-1900/routes.jsx
  src/applications/vre/28-1900/tests/e2e/chapter31-maximal.cypress.spec.js
  src/applications/vre/28-1900/tests/e2e/chapter31-wizard.cypress.spec.js
  src/applications/vre/28-1900/wizard/pages/service-member/02-yesVaMemorandum.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-yesIDES.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/02-yesDisabilityRating.jsx
  src/applications/vre/28-8832/components/GetFormHelp.jsx
  src/applications/vre/28-8832/config/form.js
Labels: VSA

#16819 VRRAP: Staging error on submission #23325
  src/applications/edu-benefits/1990s/config/form.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16817 Add concat as a liquid filter
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
Labels: VSA, front end

#16810 1990S Email Validation
  src/applications/edu-benefits/1990s/pages/application.js
Labels: BAH

#16816 NOD: Add upload pages
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/content/EvidenceUpload.jsx
  src/applications/appeals/10182/content/evidenceIntro.jsx
  src/applications/appeals/10182/pages/evidenceIntro.js
  src/applications/appeals/10182/pages/evidenceUpload.jsx
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/pages/evidenceIntro.unit.spec.js
  src/applications/appeals/10182/tests/pages/evidenceUpload.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/upload.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#16806 Trim leading + trailing whitespace
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#16752 Use action link in save-in-progress component to start form
  src/platform/forms/save-in-progress/FormStartControls.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/forms/tests/save-in-progress/FormStartControls.unit.spec.jsx
Labels: NOD, VSA, vsa-claims-appeals

#16830 Updated direct deposit payment label for 1990s
  src/applications/edu-benefits/1990s/components/PaymentView.jsx
Labels: BAH

#16824 23332: VRRAP: Update breadcrumb and direct deposit
  src/applications/edu-benefits/1990s/pages/directDeposit.jsx
  src/applications/registry.json
Labels: BAH

#16318 Convert VAMC policies page to use the new hardened content model
  src/site/README.md
  src/site/filters/liquid.js
  src/site/includes/dynamic-content.drupal.liquid
  src/site/layouts/vamc_system_policies_page.drupal.liquid
  src/site/stages/build/drupal/graphql/GetAllPages.graphql.js
  src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js
  src/site/stages/build/drupal/graphql/vamcPoliciesPage.graphql.js
  src/site/stages/build/drupal/individual-queries.js
  src/site/stages/build/drupal/metalsmith-drupal.js
  src/site/stages/build/drupal/page.js
  src/site/stages/build/plugins/download-drupal-assets.js
  src/site/stages/build/plugins/modify-dom/update-external-links.js
Labels: VSA, front end, vamc-facilities

#16836 DT-18434 Find Forms - Adding lang attributre
  src/applications/find-forms/components/FormTitle.jsx
  src/applications/find-forms/components/SearchResult.jsx
  src/applications/find-forms/tests/components/FormTitle.unit.spec.jsx
Labels: 508/Accessibility

#16706 Vet center location page
  src/applications/static-pages/sass/modules/_m-facilities.scss
  src/site/includes/breadcrumbs.drupal.liquid
  src/site/includes/facilityListing.drupal.liquid
  src/site/includes/operatingStatusFlagsLinks.drupal.liquid
  src/site/includes/operation_status_information.liquid
  src/site/includes/vet_center_address_phone_image.liquid
  src/site/layouts/health_care_local_facility.drupal.liquid
  src/site/layouts/tests/includes/operatingStatusFlagsLinks.unit.spec.js
  src/site/layouts/vet_center.drupal.liquid
  src/site/layouts/vet_center_locations_list.drupal.liquid
  src/site/stages/build/drupal/graphql/vetCenter.graphql.js
  src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js
Labels: VSA, front end, vet-center

#16814 DT-21944 Discharge Widget change of PDF for interm fix
  src/applications/discharge-wizard/utils.jsx
Labels: VSA, front end

#16827 Kelsonic 22181 searchable content field
  src/applications/resources-and-support/hooks/useGetSearchResults.js
  src/site/stages/build/plugins/create-resources-and-support-section.js
Labels: VSA, front end

#16858 Add dataLayer attributes to VAMC accordions
  src/applications/static-pages/subscribeAccordionEvents.js
  src/site/facilities/facility_health_service.drupal.liquid
  src/site/layouts/health_care_local_facility.drupal.liquid
Labels: VSA, front end, vamc-facilities

#16861 VRRAP: Set configuration prod status to true #23451
  src/applications/registry.json
Labels: BAH

#16795 FSR Wizard Screen Reader Enchantment
  src/applications/financial-status-report/wizard/DelayedLiveRegion.jsx
  src/applications/financial-status-report/wizard/WizardContainer.jsx
  src/applications/financial-status-report/wizard/pages/Appeals.jsx
  src/applications/financial-status-report/wizard/pages/Benefits.jsx
  src/applications/financial-status-report/wizard/pages/Copays.jsx
  src/applications/financial-status-report/wizard/pages/Dependents.jsx
  src/applications/financial-status-report/wizard/pages/Disagree.jsx
  src/applications/financial-status-report/wizard/pages/Error.jsx
  src/applications/financial-status-report/wizard/pages/LessThanFive.jsx
  src/applications/financial-status-report/wizard/pages/MakePayment.jsx
  src/applications/financial-status-report/wizard/pages/RogersStem.jsx
  src/applications/financial-status-report/wizard/pages/Submit.jsx
  src/applications/financial-status-report/wizard/pages/VetTec.jsx
  src/applications/financial-status-report/wizard/pages/Waivers.jsx
Labels: 508/Accessibility, bug, front end, vsa-benefits-2

#16863 update analytics
  src/applications/caregivers/containers/App.jsx
Labels: caregivers, front end

#16860 Remove CLP auth on non-staging/prod envs (e.g. preview server)
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#16867 Vet center - Add prepare for visit section
  src/applications/static-pages/facilities/vetCentersHours.jsx
  src/site/layouts/tests/vet_center/fixtures/vet_center_escanaba_data.json
  src/site/layouts/tests/vet_center/vet_center.drupal.unit.spec.js
  src/site/layouts/vet_center.drupal.liquid
  src/site/stages/build/drupal/graphql/vetCenter.graphql.js
Labels: VSA, front end, vet-center

#16884 DT-18434 refactored form title with a11y
  src/applications/find-forms/components/FormTitle.jsx
Labels: 508/Accessibility

#16871 Revert "Add sitemap a11y tests back to master branch Jenkins workflow"
  Jenkinsfile
Labels: HOLD

#16899 NOD: Combine issue field & widget
  src/applications/appeals/10182/components/CheckboxReviewWidget.jsx
  src/applications/appeals/10182/components/ContactInformation.jsx
  src/applications/appeals/10182/components/EligibleIssuesWidget.jsx
  src/applications/appeals/10182/components/IssueCard.jsx
  src/applications/appeals/10182/components/IssueCards.jsx
  src/applications/appeals/10182/components/NewIssuesField.jsx
  src/applications/appeals/10182/components/VeteranInformation.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/config/submit-transformer.js
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/ConfirmationPage.jsx
  src/applications/appeals/10182/content/OptIn.jsx
  src/applications/appeals/10182/content/boardReview.js
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/content/representative.js
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/pages/repInfo.js
  src/applications/appeals/10182/reducers/contestableIssues.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/appeals/10182/tests/fixtures/data/maximal-test.json
  src/applications/appeals/10182/tests/schema/initialData.js
  src/applications/appeals/10182/tests/utils/dates.unit.spec.js
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/utils/dates.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/submit.js
  src/applications/appeals/10182/utils/ui.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#16908 Add isPreview to logic
  src/site/blocks/alert.drupal.liquid
Labels: VSA, front end

#16896 Kelsonic 23418 campaign mission act analytics
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#16895 STEM Claim Status GTM Tracking
  src/applications/claims-status/components/StemAskVAQuestions.jsx
  src/applications/claims-status/components/StemDeniedDetails.jsx
Labels: BAH

#16917 NOD: General cleanup
  src/applications/appeals/10182/components/ContactInformation.jsx
  src/applications/appeals/10182/components/IssueCard.jsx
  src/applications/appeals/10182/components/VeteranInformation.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/config/submit-transformer.js
  src/applications/appeals/10182/containers/IntroductionPage.jsx
  src/applications/appeals/10182/content/OptIn.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/content/representative.js
  src/applications/appeals/10182/content/saveInProgress.js
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/pages/evidenceUpload.jsx
  src/applications/appeals/10182/pages/hasRep.js
  src/applications/appeals/10182/pages/repInfo.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/fixtures/data/maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/transformed-maximal-test.json
  src/applications/appeals/10182/tests/schema/initialData.js
  src/applications/appeals/10182/utils/submit.js
  src/applications/appeals/10182/utils/upload.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#16897 Add appointment phone and info link to Covid-19 search results
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/components/search-results-items/Covid19Result.jsx
  src/applications/facility-locator/components/search-results-items/common/Covid19PhoneLink.jsx
  src/applications/facility-locator/components/search-results-items/common/LocationDistance.jsx
  src/applications/facility-locator/components/search-results-items/common/LocationPhoneLink.jsx
  src/applications/facility-locator/constants/mock-facility-v1-covid19.json
  src/applications/facility-locator/containers/FacilitiesMap.jsx
  src/applications/facility-locator/tests/components/search-results/Covid19Result.unit.spec.jsx
  src/applications/facility-locator/tests/components/search-results/LocationDistance.unit.spec.jsx
  src/applications/facility-locator/tests/components/search-results/VaFacilityResult.unit.spec.jsx
  src/applications/facility-locator/tests/components/search-results/common/Covid19PhoneLink.unit.spec.jsx
Labels: VSA, facility locator, front end

#16920 NOD: Add hearing type page
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/content/hearingType.js
  src/applications/appeals/10182/pages/hearingType.js
  src/applications/appeals/10182/utils/helpers.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#16912 GIDS: Profile page mailing zip incorrect #23638
  src/applications/gi/components/profile/HeadingSummary.jsx
  src/applications/gi/components/profile/SchoolLocations.jsx
  src/applications/gi/components/search/RatedSearchResult.jsx
  src/applications/gi/components/search/SearchResult.jsx
  src/applications/gi/reducers/utility.js
  src/applications/gi/tests/reducers/utility.unit.spec.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16764 Wire up FSR SignatureBox to FormBuilder
  src/applications/financial-status-report/components/PreSubmitSignature.jsx
Labels: bug, front end, vsa-benefits-2

#16900 Vet center - services accordions
  src/applications/static-pages/facilities/vetCentersHours.jsx
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/includes/vet_center_health_services.liquid
  src/site/includes/vet_center_services.liquid
  src/site/layouts/tests/vet_center/fixtures/vet_center_escanaba_data.json
  src/site/layouts/tests/vet_center/vet_center.drupal.unit.spec.js
  src/site/layouts/vet_center.drupal.liquid
Labels: VSA, front end, vet-center

#16946 CT Redesign: Create copy of profile pages for use in sandbox #23581
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/AccordionItem.jsx
  src/applications/gi-sandbox/components/AlertBox.jsx
  src/applications/gi-sandbox/components/EstimateYourBenefitsSummarySheet.jsx
  src/applications/gi-sandbox/components/ProfileNavBar.jsx
  src/applications/gi-sandbox/components/ProfileSection.jsx
  src/applications/gi-sandbox/components/ResponsiveTable.jsx
  src/applications/gi-sandbox/components/content/AdditionalResources.jsx
  src/applications/gi-sandbox/components/content/AdditionalResourcesLinks.jsx
  src/applications/gi-sandbox/components/profile/AdditionalInformation.jsx
  src/applications/gi-sandbox/components/profile/BenefitsForm.jsx
  src/applications/gi-sandbox/components/profile/CautionFlagDetails.jsx
  src/applications/gi-sandbox/components/profile/CautionFlagHeading.jsx
  src/applications/gi-sandbox/components/profile/CautionaryInformation.jsx
  src/applications/gi-sandbox/components/profile/ContactInformation.jsx
  src/applications/gi-sandbox/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi-sandbox/components/profile/EstimatedBenefits.jsx
  src/applications/gi-sandbox/components/profile/Graph.jsx
  src/applications/gi-sandbox/components/profile/HeadingSummary.jsx
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
  src/applications/gi-sandbox/components/profile/Programs.jsx
  src/applications/gi-sandbox/components/profile/SchoolCategoryRating.jsx
  src/applications/gi-sandbox/components/profile/SchoolClosingDetails.jsx
  src/applications/gi-sandbox/components/profile/SchoolClosingHeading.jsx
  src/applications/gi-sandbox/components/profile/SchoolLocations.jsx
  src/applications/gi-sandbox/components/profile/SchoolRatings.jsx
  src/applications/gi-sandbox/components/profile/ScoContact.jsx
  src/applications/gi-sandbox/components/search/OnlineClassesFilter.jsx
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/components/vet-tec/VetTecAdditionalInformation.jsx
  src/applications/gi-sandbox/components/vet-tec/VetTecApplicationProcess.jsx
  src/applications/gi-sandbox/components/vet-tec/VetTecApprovedProgramsList.jsx
  src/applications/gi-sandbox/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
  src/applications/gi-sandbox/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi-sandbox/components/vet-tec/VetTecVeteranPrograms.jsx
  src/applications/gi-sandbox/constants.js
  src/applications/gi-sandbox/containers/EstimateYourBenefits.jsx
  src/applications/gi-sandbox/containers/GiBillApp.jsx
  src/applications/gi-sandbox/containers/ProfilePage.jsx
  src/applications/gi-sandbox/containers/VetTecEstimateYourBenefits.jsx
  src/applications/gi-sandbox/reducers/calculator.js
  src/applications/gi-sandbox/reducers/index.js
  src/applications/gi-sandbox/routes.jsx
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-profile-page.scss
  src/applications/gi-sandbox/sass/partials/_gi-search-controls.scss
  src/applications/gi-sandbox/selectors/calculator.js
  src/applications/gi-sandbox/selectors/estimator.js
  src/applications/gi-sandbox/selectors/vetTecCalculator.js
  src/applications/gi-sandbox/selectors/vetTecEstimator.js
  src/applications/gi-sandbox/utils/helpers.js
  src/applications/gi-sandbox/utils/render.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16956 Update aria-label for progressbar to have a default value
  src/site/paragraphs/react_widget.drupal.liquid
Labels: VSA, front end

#16950 Comparison Sandbox Search UI Update
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/Dropdown.jsx
  src/applications/gi-sandbox/components/SearchForm.jsx
  src/applications/gi-sandbox/containers/LandingPage.jsx
  src/applications/gi-sandbox/reducers/index.js
  src/applications/gi-sandbox/reducers/search.js
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-search-page.scss
  src/applications/gi-sandbox/sass/partials/_gi-vet-tec.scss
  src/applications/gi-sandbox/tests/components/SearchForm.unit.spec.jsx
Labels: BAH

#16966 updated vbbp link
  src/applications/edu-benefits/1990s/content/directDeposit.jsx
Labels: BAH, BAH-IR-needed

#16977 NOD: add more unit tests & cleanup
  src/applications/appeals/10182/components/CheckboxReviewWidget.jsx
  src/applications/appeals/10182/components/EligibleIssuesWidget.jsx
  src/applications/appeals/10182/components/IssueCard.jsx
  src/applications/appeals/10182/components/NewIssuesField.jsx
  src/applications/appeals/10182/components/VeteranInformation.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/ConfirmationPage.jsx
  src/applications/appeals/10182/content/OptIn.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/content/hearingType.js
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/components/EligibleIssuesWidget.unit.spec.jsx
  src/applications/appeals/10182/tests/components/IssueCard.unit.spec.jsx
  src/applications/appeals/10182/tests/components/NewIssuesField.unit.spec.jsx
  src/applications/appeals/10182/tests/components/ReviewDescription.unit.spec.jsx
  src/applications/appeals/10182/tests/components/VeteranInformation.unit.spec.jsx
  src/applications/appeals/10182/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/boardReview.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/contactInfo.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/hasRep.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/hearingType.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/veteranInfo.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/veteranInformation.unit.spec.jsx
  src/applications/appeals/10182/tests/reducers/reducers.unit.spec.js
  src/applications/appeals/10182/tests/utils/dates.unit.spec.js
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/utils/dates.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/submit.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#16937 23443: Add I certify statement to Review Application chapter
  src/applications/edu-benefits/0994/config/form.js
  src/applications/edu-benefits/0994/containers/PreSubmitInfo.jsx
  src/applications/edu-benefits/0994/tests/containers/PreSubmitInfo.unit.spec.jsx
  src/applications/edu-benefits/1990s/containers/PreSubmitInfo.jsx
  src/applications/edu-benefits/containers/PreSubmitInfo.jsx
  src/applications/edu-benefits/tests/containers/PreSubmitInfo.unit.spec.jsx
Labels: BAH, BAH-QA-needed

#16970 Tweak tags styling
  src/site/includes/tags.drupal.liquid
Labels: VSA, front end

#16981 DT-23155 Discharge Wizard Refactor and addition of tests
  src/applications/discharge-wizard/actions.js
  src/applications/discharge-wizard/actions/index.js
  src/applications/discharge-wizard/components/DischargeWizardApp.jsx
  src/applications/discharge-wizard/components/FormQuestions.jsx
  src/applications/discharge-wizard/components/InstructionsPage.jsx
  src/applications/discharge-wizard/constants/index.js
  src/applications/discharge-wizard/containers/FormPage.jsx
  src/applications/discharge-wizard/containers/GuidancePage.jsx
  src/applications/discharge-wizard/containers/RequestDD214.jsx
  src/applications/discharge-wizard/helpers/index.jsx
  src/applications/discharge-wizard/reducers/discharge-wizard.js
  src/applications/discharge-wizard/routes.jsx
  src/applications/discharge-wizard/tests/00-required.e2e.spec.js
  src/applications/discharge-wizard/tests/actions/index.unit.spec.js
  src/applications/discharge-wizard/tests/components/CarefulConsiderationStatement.unit.spec.js
  src/applications/discharge-wizard/tests/components/FormQuestions.unit.spec.js
  src/applications/discharge-wizard/tests/components/InstructionsPage.unit.spec.js
  src/applications/discharge-wizard/tests/containers/FormPage.unit.spec.js
  src/applications/discharge-wizard/tests/containers/GuidancePage.unit.spec.js
  src/applications/discharge-wizard/tests/containers/RequestDD214.unit.spec.js
  src/applications/discharge-wizard/tests/e2e/discharge-wizard.cypress.spec.js
  src/applications/discharge-wizard/tests/reducer/index.unit.spec.js
Labels: VSA

#16983 Add support for audience_beneficiaries and non beneficiaries
  src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
Labels: VSA, front end

#17002 Text change for 0994
  src/applications/edu-benefits/0994/containers/PreSubmitInfo.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16955 Update FSR Page Content
  src/applications/debt-letters/const/deduction-codes/index.js
  src/applications/financial-status-report/components/AvailableDebts.jsx
  src/applications/financial-status-report/components/FinancialOverview.jsx
  src/applications/financial-status-report/components/PreSubmitSignature.jsx
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/containers/ConfirmationPage.jsx
  src/applications/financial-status-report/wizard/pages/Submit.jsx
Labels: content, front end, vsa-benefits-2

#16975 Update Global Content for Consistency with Platform
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/pages/veteran/contact.js
Labels: content, front end, vsa-benefits-2

#16973 Vet center - main page cc content sections
  src/applications/static-pages/facilities/vetCentersHours.jsx
  src/applications/static-pages/sass/modules/_m-facilities.scss
  src/site/includes/vet_center_featured_content.liquid
  src/site/includes/vet_center_services.liquid
  src/site/layouts/tests/vet_center/fixtures/vet_center_escanaba_data.json
  src/site/layouts/tests/vet_center/vet_center.drupal.unit.spec.js
  src/site/layouts/vet_center.drupal.liquid
  src/site/stages/build/drupal/graphql/vetCenter.graphql.js
Labels: VSA, front end, vet-center

#17012 Filter out unpublished services from VAMC location pages
  src/site/layouts/health_care_local_facility.drupal.liquid
  src/site/layouts/tests/vamc/fixtures/health_care_local_facility_no_phone_mental.json
  src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionHealthServices.node.graphql.js
  src/site/stages/build/drupal/graphql/healthCareLocalFacilityPage.graphql.js
  src/site/stages/build/drupal/graphql/healthServicesListingPage.graphql.js
  src/site/stages/build/drupal/graphql/paragraph-fragments/serviceLocation.paragraph.graphql.js
Labels: VSA, front end, vamc-facilities

#17014 Add go back to VA.gov button on FSR confirmation page
  src/applications/financial-status-report/containers/ConfirmationPage.jsx
Labels: UX, front end, vsa-benefits-2

#16986 Update 10-10CG Sign as Representative Content
  src/applications/caregivers/components/AdditionalInfo/index.jsx
  src/applications/caregivers/components/PreSubmitInfo/SignatureCheckbox.jsx
  src/applications/caregivers/components/PreSubmitInfo/index.jsx
  src/applications/caregivers/config/chapters/signAsRepresentative/uploadPOADocument.js
  src/applications/caregivers/definitions/content.js
  src/applications/caregivers/sass/caregivers.scss
  src/applications/caregivers/sass/signatureBox.scss
Labels: caregivers, content, front end

#16978 DT-23851 FAF 508-1
  src/site/layouts/va_form.drupal.liquid
Labels: 508/Accessibility

#16882 VRRAP: Set configuration prod status to true #23451
  src/applications/registry.json
Labels: BAH

#17028 22660 - Chp 31 Orientation update
  src/applications/vre/28-1900/orientation/OrientationApp.jsx
  src/applications/vre/28-1900/orientation/StepComponent.jsx
  src/applications/vre/28-1900/orientation/utils.js
  src/applications/vre/28-1900/tests/e2e/chapter31-wizard.cypress.spec.js
Labels: VSA

#17024 24010 chp31 loa check
  src/applications/vre/28-1900/components/IdentityNotVerified.jsx
  src/applications/vre/28-1900/containers/FormApp.jsx
  src/applications/vre/28-1900/tests/e2e/chapter31-loa1.cypress.spec.js
Labels: VSA
