Repository department-of-veterans-affairs/vets-website, pull requests merged in 2021-12, with the labels that each got.

#19548 Bump component library version
  package.json
  yarn.lock
Labels: vsa-claims-appeals, VSA

#19554 HLR: Fix other benefits anchor
  src/applications/disability-benefits/996/constants.js
Labels: front end, vsa-claims-appeals, VSA, HLR

#19526 Add events app boilerplate
  src/applications/static-pages/events/components/App/index.js
  src/applications/static-pages/events/components/App/index.unit.spec.js
  src/applications/static-pages/events/helpers/index.js
  src/applications/static-pages/events/index.js
Labels: front end, VSA

#19561 Do not lazy load in header v2 for faster rendering time
  src/applications/static-pages/events/index.js
Labels: front end, VSA

#19270 [MCP]: Download PDF Statements
  src/applications/medical-copays/components/DownloadStatement.jsx
  src/applications/medical-copays/components/DownloadStatements.jsx
  src/applications/medical-copays/components/PDFStatementList.jsx
  src/applications/medical-copays/containers/DetailPage.jsx
  src/applications/medical-copays/utils/mockData.js
Labels: front end, debt, MCP

#19574 Add analytic event on component did mount for header v2
  src/platform/site-wide/header/components/App/index.js
Labels: front end, VSA

#19596 33470: Adds unit test to validate login buttons passing proper arguments
  src/platform/user/authentication/components/NewDesignButtons.jsx
  src/platform/user/authentication/constants.js
  src/platform/user/tests/authentication/components/loginButtons.unit.spec.js
  src/platform/user/tests/authentication/utilities.unit.spec.js
Labels: Identity

#19509 Uploads: Verify file extension matches format
  src/applications/claims-status/components/AddFilesForm.jsx
  src/applications/claims-status/tests/components/AddFilesForm.unit.spec.jsx
  src/applications/financial-status-report/components/FileUploader.jsx
  src/platform/forms-system/src/js/fields/FileField.jsx
  src/platform/forms-system/src/js/utilities/file/arrayIncludesArray.js
  src/platform/forms-system/src/js/utilities/file/checkForEncryptedPdf.js
  src/platform/forms-system/src/js/utilities/file/checkIsEncryptedPdf.js
  src/platform/forms-system/src/js/utilities/file/checkTypeAndExtensionMatches.js
  src/platform/forms-system/src/js/utilities/file/index.js
  src/platform/forms-system/src/js/utilities/file/readAndCheckFile.js
  src/platform/forms-system/test/js/fields/FileField.unit.spec.jsx
  src/platform/forms-system/test/js/utilities/file.unit.spec.js
  src/platform/testing/e2e/cypress/support/commands/upload.js
Labels: enhancement, front end, vsa-claims-appeals, VSA, 526

#19606 33471: Remove login_old_design flag and code
  src/applications/gi/tests/e2e/mock-feature_toggles.js
  src/applications/login/containers/SignInApp.jsx
  src/platform/user/authentication/components/FedWarning.jsx
  src/platform/user/authentication/components/LoginButtons.jsx
  src/platform/user/authentication/components/OriginalDesignButtons.jsx
  src/platform/user/authentication/components/SignInModal.jsx
  src/platform/user/authentication/selectors.js
  src/platform/user/tests/authentication/components/loginButtons.unit.spec.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: Identity

#19629 Fix tabbing issue
  src/applications/find-forms/components/SearchResult.jsx
Labels: front end, VSA

#19630 33831: Remove SSO Announcement Modal
  src/platform/site-wide/announcements/components/SingleSignOnInfoModal.jsx
  src/platform/site-wide/announcements/config/index.js
  src/platform/site-wide/announcements/tests/components/SingleSignOnInfoModal.unit.spec.jsx
Labels: Identity

#19636 fix box shadow for dropdown component
  src/applications/search/components/SearchDropdown/SearchDropdownStyles.scss
Labels: front end, VSA

#18516 Github Actions (CI) -- Disable Jenkins CI and persist RI
  .github/workflows/continuous-integration.yml
  Jenkinsfile
  script/github-actions/trigger-jenkins.js
Labels: DO NOT MERGE

#19687 Change `veteran-programs` ids to something else
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/platform/site-wide/va-footer/components/MobileLinks.jsx
Labels: front end, VSA

#19693 HLR: prevent JS error
  src/applications/disability-benefits/996/components/ContactInformation.jsx
  src/applications/disability-benefits/996/tests/components/ContactInformation.unit.spec.jsx
Labels: bug, front end, vsa-claims-appeals, VSA, HLR

#19709 Add cross-domain redirect
  src/applications/proxy-rewrite/redirects/crossDomainRedirects.json
Labels: front end, VSA

#19715 HLR: Accessibility fixes
  src/applications/disability-benefits/996/components/EligibleIssuesWidget.jsx
  src/applications/disability-benefits/996/content/areaOfDisagreement.jsx
  src/applications/disability-benefits/996/pages/issueSummary.js
  src/applications/disability-benefits/996/utils/ui.js
Labels: 508/Accessibility, front end, vsa-claims-appeals, VSA, HLR

#15203 [Development] Remove all reference to faxing in form 526 & CST
  src/applications/claims-status/actions/index.jsx
  src/applications/claims-status/components/AddFilesForm.jsx
  src/applications/claims-status/components/MailMessage.jsx
  src/applications/claims-status/containers/AdditionalEvidencePage.jsx
  src/applications/claims-status/containers/DocumentRequestPage.jsx
  src/applications/claims-status/reducers/uploads.js
  src/applications/claims-status/tests/actions.unit.spec.js
  src/applications/claims-status/tests/components/AddFilesForm.unit.spec.jsx
  src/applications/claims-status/tests/reducers/uploads.unit.spec.jsx
  src/applications/claims-status/utils/appeals-v2-helpers.jsx
  src/applications/disability-benefits/all-claims/content/instructionalPart3.jsx
  src/applications/disability-benefits/all-claims/content/pastEmploymentFormDownload.jsx
Labels: front end, claim status, vsa-claims-appeals, VSA, 526

#19696 [eBenefits] Convert AdditionalInfo to va-additional-info component
  src/applications/disability-benefits/686c-674/config/address-schema.js
  src/applications/disability-benefits/686c-674/config/chapters/add-a-child/child-place-of-birth/childStatusDescription.jsx
  src/applications/disability-benefits/686c-674/config/chapters/add-a-child/child-place-of-birth/notSelfSufficientDescription.jsx
  src/applications/disability-benefits/686c-674/config/chapters/household-income/helpers.js
  src/applications/disability-benefits/686c-674/config/chapters/report-add-a-spouse/current-marriage-information/helpers.jsx
  src/applications/lgy/coe/form/config/chapters/loans/loanIntent.js
  src/applications/lgy/coe/form/containers/introduction-content/loggedInContent.jsx
  src/applications/personalization/view-representative/components/ViewRepresentativeDetails.jsx
Labels: Tech Debt

#19697 [eBenefits] Convert LoadingIndicator to va-loading-indicator component
  src/applications/disability-benefits/686c-674/containers/App.jsx
  src/applications/disability-benefits/686c-674/containers/IntroductionPage.jsx
  src/applications/disability-benefits/view-payments/README.md
  src/applications/disability-benefits/view-payments/components/view-payments-lists/ViewPaymentsLists.jsx
  src/applications/personalization/rated-disabilities/components/RatedDisabilityList.jsx
  src/applications/personalization/rated-disabilities/components/TotalRatedDisabilities.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsList/ViewDependentsList.jsx
  src/applications/personalization/view-dependents/layouts/ViewDependentsLayout.jsx
  src/applications/personalization/view-dependents/manage-dependents/containers/ManageDependentsApp.jsx
  src/applications/personalization/view-representative/components/ViewRepresentativeBody.jsx
  src/applications/vre/28-1900/components/VeteranInformationViewComponent.jsx
  src/applications/vre/28-1900/containers/FormApp.jsx
Labels: Tech Debt

#19704 Kelsonic 32600 events v2 app
  src/applications/static-pages/events/components/App/index.js
  src/applications/static-pages/events/components/App/index.unit.spec.js
  src/applications/static-pages/events/components/Results/index.js
  src/applications/static-pages/events/components/Results/index.unit.spec.js
  src/applications/static-pages/events/components/Search/index.js
  src/applications/static-pages/events/components/Search/index.unit.spec.js
  src/applications/static-pages/events/helpers/index.js
  src/applications/static-pages/events/helpers/index.unit.spec.js
Labels: front end, VSA

#19728 Srsuddath find forms staging fixes
  src/applications/find-forms/components/SearchResult.jsx
  src/applications/find-forms/containers/SearchResults.jsx
  src/applications/find-forms/helpers/index.js
  src/applications/find-forms/tests/containers/SearchResults.unit.spec.jsx
Labels: front end, VSA

#19754 add keypress handler
  src/applications/find-forms/components/SearchResult.jsx
Labels: front end, VSA

#19755 fix camelcase of keyCode
  src/applications/find-forms/components/SearchResult.jsx
  src/applications/search/components/SearchDropdown/SearchDropdownComponent.js
Labels: front end, VSA

#19775 Updating BVA link and removing WARMS link
  src/applications/search/containers/SearchApp.jsx
Labels: front end, VSA

#19774 Abstract main Events component into separate folder/files
  src/applications/static-pages/events/components/App/index.js
  src/applications/static-pages/events/components/App/index.unit.spec.js
  src/applications/static-pages/events/components/Events/constants.js
  src/applications/static-pages/events/components/Events/constants.unit.spec.js
  src/applications/static-pages/events/components/Events/index.js
  src/applications/static-pages/events/components/Events/index.unit.spec.js
  src/applications/static-pages/events/components/Search/index.js
  src/applications/static-pages/events/components/Search/index.unit.spec.js
  src/applications/static-pages/events/helpers/index.js
Labels: front end, VSA

#19782 Update submit button naming
  src/applications/static-pages/events/components/Search/index.js
  src/applications/static-pages/events/components/Search/index.unit.spec.js
Labels: front end, VSA
