Repository department-of-veterans-affairs/vets-website, pull requests merged in 2021-06, with the labels that each got.

#17412 23966 remove chp31 feature toggle
  src/applications/static-pages/vre-chapter31/Chapter31CTA.js
  src/applications/static-pages/vre-chapter31/buildChapter31Content.js
  src/applications/vre/28-1900/components/FormInProgressNotification.jsx
  src/applications/vre/28-1900/containers/App.jsx
  src/applications/vre/28-1900/containers/FormApp.jsx
  src/applications/vre/28-1900/tests/e2e/chapter31-loa1.cypress.spec.js
  src/applications/vre/28-1900/tests/e2e/chapter31-maximal.cypress.spec.js
  src/applications/vre/28-1900/tests/e2e/chapter31-wizard.cypress.spec.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA

#17430 526: Fix address prefill
  src/applications/disability-benefits/all-claims/pages/contactInformation.js
  src/applications/disability-benefits/all-claims/prefill-transformer.js
  src/applications/disability-benefits/all-claims/tests/prefill-transformer.unit.spec.js
Labels: 526, VSA, bug, front end, vsa-claims-appeals

#17441 NOD: Content updates
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/ConfirmationPage.jsx
  src/applications/appeals/10182/containers/IntroductionPage.jsx
  src/applications/appeals/10182/content/OptIn.jsx
  src/applications/appeals/10182/content/boardReview.js
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/content/evidenceIntro.jsx
  src/applications/appeals/10182/content/hearingType.js
  src/applications/appeals/10182/content/representative.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17448 Fix Styling Bugs on FSR Intro Wizard
  src/applications/debt-letters/components/DebtLettersDownload.jsx
  src/applications/financial-status-report/sass/financial-status-report.scss
  src/applications/financial-status-report/wizard/pages/Error.jsx
  src/applications/financial-status-report/wizard/pages/RogersStem.jsx
  src/applications/financial-status-report/wizard/pages/VetTec.jsx
Labels: bug, front end, vsa-benefits-2

#17021 Add new experiment with sorting
  src/applications/resources-and-support/hooks/useGetSearchResults.js
Labels: VSA, front end

#17453 NOD: Fix Cypress upload test
  src/applications/appeals/10182/tests/10182-notice-of-disagreement.cypress.spec.js
  src/applications/appeals/10182/tests/fixtures/data/example-upload.pdf
Labels: NOD, VSA, front end, vsa-claims-appeals

#17463 NOD: Various fixes
  src/applications/appeals/10182/components/AddIssuesField.jsx
  src/applications/appeals/10182/content/issueSummary.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/pages/issueSummary.unit.spec.jsx
Labels: NOD, VSA, front end, vsa-claims-appeals

#17464 NOD: Remove header inside legend. Fix 508 defect
  src/applications/appeals/10182/components/AddIssuesField.jsx
Labels: 508/Accessibility, NOD, VSA, front end, vsa-claims-appeals

#17459 Increment formation version
  package.json
  yarn.lock
Labels: VSA, front end

#17432 Fix debt letters download error content bug
  src/applications/debt-letters/components/DebtLettersDownload.jsx
Labels: bug, content, front end, vsa-benefits-2

#17484 24718: Update 2 questions due to legislative changes.
  src/applications/edu-benefits/1990e/config/form.js
  src/applications/edu-benefits/1990e/helpers.jsx
  src/applications/edu-benefits/pages/schoolSelection.js
Labels: BAH, BAH-QA-needed

#17405 5490 content updates
  src/applications/edu-benefits/5490/components/BenefitSelectionWarning.jsx
  src/applications/edu-benefits/5490/config/form.js
  src/applications/edu-benefits/5490/helpers.jsx
  src/applications/edu-benefits/5490/tests/config/sponsorInformation.unit.spec.jsx
  src/applications/edu-benefits/5490/tests/helpers.unit.spec.js
Labels: BAH

#17498 NOD: Use mobile then home phone, show note if missing
  src/applications/appeals/10182/components/ContactInformation.jsx
  src/applications/appeals/10182/components/ReviewDescription.jsx
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/tests/components/ContactInformation.unit.spec.jsx
  src/applications/appeals/10182/tests/components/ReviewDescription.unit.spec.jsx
Labels: NOD, VSA, front end, vsa-claims-appeals

#17494 NOD: Add headings to checkbox labels
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
Labels: 508/Accessibility, NOD, VSA, front end, vsa-claims-appeals

#17503 NOD: Add decision date validation
  src/applications/appeals/10182/pages/additionalIssues.js
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17492 VRRAP: Update introduction content #24562
  src/applications/edu-benefits/1990s/containers/IntroductionPage.jsx
Labels: BAH

#17470 CT Sandbox - Institution Compare Drawer
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/search/LocationSearchResults.jsx
  src/applications/gi-sandbox/components/search/NameResults.jsx
  src/applications/gi-sandbox/containers/CompareDrawer.jsx
  src/applications/gi-sandbox/containers/SearchPage.jsx
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
  src/applications/gi-sandbox/reducers/compare.js
  src/applications/gi-sandbox/reducers/index.js
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-compare-drawer.scss
Labels: BAH

#17508 NOD|508: Fix edit button aria-label
  src/applications/appeals/10182/components/IssueCard.jsx
Labels: 508/Accessibility, NOD, VSA, front end, vsa-claims-appeals

#17474 Refactor Code Style for Debt Letters
  src/applications/debt-letters/components/DebtCardsList.jsx
  src/applications/debt-letters/components/DebtDetails.jsx
  src/applications/debt-letters/components/DebtLetterCard.jsx
  src/applications/debt-letters/components/DebtLettersDownload.jsx
  src/applications/debt-letters/components/DebtLettersList.jsx
  src/applications/debt-letters/components/DebtLettersSummary.jsx
  src/applications/debt-letters/components/DebtLettersTable.jsx
  src/applications/debt-letters/components/DebtLettersWrapper.jsx
  src/applications/debt-letters/components/ErrorAlerts.jsx
  src/applications/debt-letters/components/HowDoIPay.jsx
  src/applications/debt-letters/components/MobileTableView.jsx
  src/applications/debt-letters/components/NeedHelp.jsx
  src/applications/debt-letters/const/deduction-codes/index.js
  src/applications/debt-letters/const/diary-codes/index.js
  src/applications/debt-letters/tests/reducers.unit.spec.js
Labels: Tech Debt, front end, vsa-benefits-2

#17425 Vet center expandable status component
  .github/CODEOWNERS
  src/applications/static-pages/facilities/vet-center/createExpandableOperatingStatus.jsx
  src/applications/static-pages/sass/modules/_m-operating-status.scss
  src/applications/static-pages/sass/static-pages.scss
  src/applications/static-pages/shared/ExpandableOperatingStatus.jsx
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/tests/facilities/ExpandableOperatingStatus.unit.spec.jsx
Labels: VSA, front end, vet-center

#17518 NOD: Refactor code to reduce complexity
  src/applications/appeals/10182/components/AddIssues.jsx
  src/applications/appeals/10182/components/AddIssuesField.jsx
  src/applications/appeals/10182/utils/helpers.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17461 Bah 10203 updates
  src/applications/edu-benefits/10203/analytics-functions.js
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/containers/InitialConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/10203/content/programDetails.jsx
  src/applications/edu-benefits/10203/helpers.jsx
  src/applications/edu-benefits/10203/pages/programDetails.js
  src/applications/edu-benefits/10203/pages/stemEligibility.js
  src/applications/edu-benefits/10203/sass/10203_stem.scss
  src/applications/edu-benefits/10203/tests/containers/ConfirmEligibilityView.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/containers/InitialConfirmEligibilityView.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/edu-benefits/10203/tests/edu-10203.cypress.spec.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17509 FSR Intro Wizard Content Updates
  src/applications/financial-status-report/wizard/pages/Appeals.jsx
  src/applications/financial-status-report/wizard/pages/Benefits.jsx
  src/applications/financial-status-report/wizard/pages/Decision.jsx
  src/applications/financial-status-report/wizard/pages/Dependents.jsx
  src/applications/financial-status-report/wizard/pages/Disagree.jsx
  src/applications/financial-status-report/wizard/pages/Error.jsx
  src/applications/financial-status-report/wizard/pages/Recipients.jsx
  src/applications/financial-status-report/wizard/pages/Reconsider.jsx
Labels: bug, content, front end, vsa-benefits-2

#17529 NOD: Fix additionalIssues validation
  src/applications/appeals/10182/pages/additionalIssues.js
  src/applications/appeals/10182/tests/components/AddIssuesField.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/additionalIssues.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/contestableIssues.unit.spec.jsx
  src/applications/appeals/10182/tests/schema/initialData.js
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17523 Vet centers fixes - include operating status on nearby vet centers
  src/applications/static-pages/facilities/vet-center/buildOperatingStatusProps.js
  src/applications/static-pages/facilities/vet-center/components/VetCenterInfoSection.jsx
  src/applications/static-pages/facilities/vet-center/createExpandableOperatingStatus.jsx
  src/applications/static-pages/facilities/vet-center/nearByVetCenters.jsx
Labels: VSA, front end, vet-center

#17489 CT Redesign: The one were it scrolls and stays open
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/SearchAccordion.jsx
  src/applications/gi-sandbox/components/search/LocationSearchResults.jsx
  src/applications/gi-sandbox/components/search/NameResults.jsx
  src/applications/gi-sandbox/components/search/SearchTabs.jsx
  src/applications/gi-sandbox/containers/RefineYourSearch.jsx
  src/applications/gi-sandbox/containers/TuitionAndHousingEstimates.jsx
  src/applications/gi-sandbox/reducers/eligibility.js
  src/applications/gi-sandbox/reducers/filters.js
  src/applications/gi-sandbox/utils/helpers.js
Labels: BAH

#17535 Update component library
  package.json
  yarn.lock
Labels: VSA, front end

#17544 526|508: Add aria-describedby to wizard
  src/applications/disability-benefits/wizard/pages/appeals.jsx
  src/applications/disability-benefits/wizard/pages/bdd.jsx
  src/applications/disability-benefits/wizard/pages/disagree-file-claim.jsx
  src/applications/disability-benefits/wizard/pages/file-bdd.jsx
  src/applications/disability-benefits/wizard/pages/file-claim-early.jsx
  src/applications/disability-benefits/wizard/pages/file-claim.jsx
  src/applications/disability-benefits/wizard/pages/start.jsx
  src/applications/disability-benefits/wizard/pages/unable-to-file-bdd.jsx
Labels: 508/Accessibility, 526, VSA, front end, vsa-claims-appeals

#17543 CT Sandbox: Collapse accordions on map marker click
  src/applications/gi-sandbox/components/SearchAccordion.jsx
  src/applications/gi-sandbox/components/search/SearchTabs.jsx
  src/applications/gi-sandbox/containers/RefineYourSearch.jsx
  src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx
Labels: BAH

#17549 HLR: remove feature flag
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/content/contestableIssueAlerts.jsx
  src/applications/disability-benefits/996/helpers.js
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/996/tests/fixtures/mocks/feature-toggles.json
  src/applications/disability-benefits/996/tests/hlr-wizard.cypress.spec.js
  src/applications/disability-benefits/996/tests/hlr.cypress.spec.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: HLR, VSA, front end, vsa-claims-appeals

#17455 CT Redesign: Apply filters when searching
  src/applications/gi-sandbox/reducers/filters.js
  src/applications/gi-sandbox/utils/helpers.js
Labels: BAH

#17558 BDD: Show separation location for qualified activated reservists
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/tests/migrations/migrations.unit.spec.js
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: BDD, VSA, bug, front end, vsa-claims-appeals

#17548 Move finish app later link
  src/applications/edu-benefits/0993/containers/FormPage.jsx
  src/applications/edu-benefits/0993/containers/RoutedSavableFormPage.jsx
  src/platform/forms-system/src/js/containers/FormPage.jsx
  src/platform/forms/save-in-progress/RoutedSavablePage.jsx
  src/platform/forms/save-in-progress/SaveFormLink.jsx
  src/platform/forms/tests/save-in-progress/SaveFormLink.unit.spec.jsx
Labels: 508/Accessibility, VSA, front end

#17540 Update FSR URL to /request-debt-help-form-5655
  src/applications/debt-letters/components/NeedHelp.jsx
  src/applications/financial-status-report/manifest.json
  src/applications/financial-status-report/tests/e2e/fsr-5655-wizard.cypress.spec.js
Labels: enhancement, front end, vsa-benefits-2

#17575 NOD: sort issues
  src/applications/appeals/10182/components/ContactInformation.jsx
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17582 Add e2e tests for mega menu
  src/platform/site-wide/mega-menu/components/Column.jsx
  src/platform/site-wide/mega-menu/components/MegaMenu.jsx
  src/platform/site-wide/mega-menu/components/MenuSection.jsx
  src/platform/site-wide/mega-menu/components/SubMenu.jsx
  src/platform/site-wide/mega-menu/tests/megaMenu.cypress.spec.js
  src/platform/testing/e2e/megamenu/megamenu.e2e.spec.js
  src/platform/testing/e2e/megamenu/megamenu.js
Labels: VSA, front end

#17552 25559: Update search results card content and layout
  src/applications/gi-sandbox/components/CautionFlagAdditionalInfo.jsx
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
  src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-search-page.scss
Labels: BAH

#17580 25545 scaffold auto coe page
  src/applications/lgy/coe/actions/index.js
  src/applications/lgy/coe/components/CertificateDownload.jsx
  src/applications/lgy/coe/components/FormApplicationSteps.jsx
  src/applications/lgy/coe/components/GetFormHelp.jsx
  src/applications/lgy/coe/config/form.js
  src/applications/lgy/coe/constants.js
  src/applications/lgy/coe/containers/App.jsx
  src/applications/lgy/coe/containers/EligibilityApp.jsx
  src/applications/lgy/coe/containers/IntroductionPage.jsx
  src/applications/lgy/coe/reducers/index.js
  src/applications/lgy/coe/routes.jsx
Labels: VSA

#17452 Allow for edit on accordion open and bypass edit button
  src/applications/financial-status-report/config/form.js
Labels: bug, front end, vsa-benefits-2

#17554 CT Sandbox: Compare View
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/CompareGrid.jsx
  src/applications/gi-sandbox/components/GiBillBreadcrumbs.jsx
  src/applications/gi-sandbox/components/RatingsStars.jsx
  src/applications/gi-sandbox/components/profile/HeadingSummary.jsx
  src/applications/gi-sandbox/components/profile/SchoolCategoryRating.jsx
  src/applications/gi-sandbox/components/profile/SchoolRatings.jsx
  src/applications/gi-sandbox/components/search/SearchTabs.jsx
  src/applications/gi-sandbox/containers/CompareDrawer.jsx
  src/applications/gi-sandbox/containers/ComparePage.jsx
  src/applications/gi-sandbox/containers/GiBillApp.jsx
  src/applications/gi-sandbox/containers/SearchPage.jsx
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
  src/applications/gi-sandbox/reducers/compare.js
  src/applications/gi-sandbox/routes.jsx
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-compare-drawer.scss
  src/applications/gi-sandbox/sass/partials/_gi-compare-page.scss
  src/applications/gi-sandbox/utils/helpers.js
  src/applications/gi-sandbox/utils/render.jsx
Labels: BAH

#17592 NOD: Add area of disagreement hint text
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/content/OptIn.jsx
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
  src/applications/appeals/10182/pages/areaOfDisagreement.js
  src/applications/appeals/10182/tests/utils/disagreement.unit.spec.js
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/utils/disagreement.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/submit.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17581 CT Sandbox - Compare view updates
  src/applications/gi-sandbox/components/CompareGrid.jsx
  src/applications/gi-sandbox/components/RemoveCompareSelectedModal.jsx
  src/applications/gi-sandbox/containers/CompareDrawer.jsx
  src/applications/gi-sandbox/containers/ComparePage.jsx
  src/applications/gi-sandbox/reducers/compare.js
  src/applications/gi-sandbox/sass/partials/_gi-compare-page.scss
Labels: BAH

#17568 24719: Remove prod flag for 24718
  src/applications/edu-benefits/1990e/config/form.js
  src/applications/edu-benefits/pages/schoolSelection.js
Labels: BAH, BAH-QA-needed

#17598 Update HLR mock dates
  src/applications/disability-benefits/996/tests/fixtures/data/maximal-test.json
  src/applications/disability-benefits/996/tests/fixtures/data/minimal-test.json
  src/applications/disability-benefits/996/tests/fixtures/data/transformed-maximal-test.json
  src/applications/disability-benefits/996/tests/fixtures/mocks/in-progress-forms.json
  src/applications/disability-benefits/996/tests/hlr.cypress.helpers.js
Labels: HLR, VSA, front end, vsa-claims-appeals

#17596 NOD: Fix Edit alignment
  src/applications/appeals/10182/sass/10182-nod.scss
Labels: NOD, VSA, front end, vsa-claims-appeals

#17590 Add aria-describedby option to TextWidget
  src/platform/forms-system/src/js/widgets/TextWidget.jsx
  src/platform/forms-system/test/js/widgets/TextWidget.unit.spec.jsx
Labels: 508/Accessibility, NOD, VSA, front end, vsa-claims-appeals

#17601 Fix spouse income section heading on FSR
  src/applications/financial-status-report/pages/income/spouse/additionalIncome/index.js
Labels: bug, content, front end, vsa-benefits-2

#17603 NOD: Fix evidence upload bug
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/utils/submit.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17593 Edu Form 5490: Remove prod flags
  src/applications/edu-benefits/5490/components/BenefitSelectionWarning.jsx
  src/applications/edu-benefits/5490/config/form.js
Labels: BAH

#17555 CT Redesign: Update name/location search functionality #25098
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/constants.js
  src/applications/gi-sandbox/containers/GiBillApp.jsx
  src/applications/gi-sandbox/containers/LocationSearchForm.jsx
  src/applications/gi-sandbox/containers/NameSearchForm.jsx
  src/applications/gi-sandbox/containers/RefineYourSearch.jsx
  src/applications/gi-sandbox/containers/TuitionAndHousingEstimates.jsx
  src/applications/gi-sandbox/reducers/filters.js
  src/applications/gi-sandbox/reducers/search.js
  src/applications/gi-sandbox/utils/helpers.js
Labels: BAH

#17610 fix typo
  src/applications/lgy/coe/components/CertificateDownload.jsx
Labels: VSA

#17612 CT Sandbox: Location Map Marker not scrolling onClick
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
  src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx
  src/applications/gi-sandbox/sass/partials/_gi-search-location.scss
Labels: BAH

#17617 NOD: Update show additional issues page logic
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17614 Fix - UI for expandable operating status icon padding on IE
  src/applications/static-pages/sass/modules/_m-operating-status.scss
Labels: VSA, front end, vet-center

#17557 CT Redesign: Add Use my current location functionality
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/containers/LocationSearchForm.jsx
  src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx
  src/applications/gi-sandbox/reducers/search.js
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-search-location.scss
  src/applications/gi-sandbox/utils/helpers.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17618 Vrrap analytics
  src/applications/edu-benefits/1990s/analytics/analytics-events.js
  src/applications/edu-benefits/1990s/analytics/analytics-functions.js
  src/applications/edu-benefits/1990s/app-entry.jsx
  src/applications/edu-benefits/1990s/config/form.js
  src/applications/edu-benefits/1990s/pages/directDeposit.jsx
Labels: BAH, BAH-QA-needed

#17630 Add feature toggle for medical copays app
  src/applications/financial-status-report/utils/helpers.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: MCP, front end, vsa-benefits-2

#17642 10203: Update clinical training section content
  src/applications/edu-benefits/components/EducationWizard.jsx
  src/applications/edu-benefits/tests/components/EducationWizard.unit.spec.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17644 CT: Add VRRAP Participant indicator to institution profile page
  src/applications/gi/components/profile/AdditionalInformation.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17659 NOD: Filter out contestable issues with no title
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17661 NOD: Remove representative pages
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/config/submit-transformer.js
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/IntroductionPage.jsx
  src/applications/appeals/10182/content/representative.js
  src/applications/appeals/10182/pages/hasRep.js
  src/applications/appeals/10182/pages/repInfo.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/fixtures/data/maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/minimal-test.json
  src/applications/appeals/10182/tests/fixtures/data/transformed-maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/transformed-minimal-test.json
  src/applications/appeals/10182/tests/pages/hasRep.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/optIn.unit.spec.jsx
  src/applications/appeals/10182/tests/schema/initialData.js
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/submit.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17669 526: Move wizard to /start
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/components/IntroductionPage.jsx
  src/applications/disability-benefits/all-claims/containers/WizardContainer.jsx
  src/applications/disability-benefits/all-claims/routes.jsx
  src/applications/disability-benefits/all-claims/tests/all-claims-wizard.cypress.spec.js
  src/applications/disability-benefits/all-claims/tests/all-claims.cypress.spec.js
  src/applications/disability-benefits/all-claims/tests/containers/Form526EZApp.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/containers/WizardContainer.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/fixtures/mocks/user.json
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/disability-benefits/wizard/wizard-utils.js
  src/platform/testing/e2e/cypress/support/form-tester/index.js
Labels: 526, VSA, front end, vsa-claims-appeals

#17646 10203: Remove prod flag and set feature flag to ON for legislative form updates #25701
  src/applications/edu-benefits/10203/config/chapters.js
  src/applications/edu-benefits/10203/containers/ConfirmEligibilityView.jsx
  src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
  src/applications/edu-benefits/10203/content/programDetails.jsx
  src/applications/edu-benefits/10203/pages/programDetails.js
  src/applications/edu-benefits/10203/pages/stemEligibility.js
  src/applications/edu-benefits/components/EducationWizard.jsx
Labels: BAH

#17671 NOD: Various fixes
  src/applications/appeals/10182/containers/IntroductionPage.jsx
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/issueSummary.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
Labels: 508/Accessibility, NOD, VSA, front end, vsa-claims-appeals

#17665 CT Redesign: Format of the ratings information is incorrect #26430
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
Labels: BAH

#17657 CT: Add Learn more to "Are you an in-state student?" question #25982
  src/applications/gi-sandbox/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi-sandbox/constants.js
  src/applications/gi-sandbox/containers/Modals.jsx
  src/applications/gi-sandbox/utils/helpers.js
  src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
  src/applications/gi/constants.js
  src/applications/gi/containers/Modals.jsx
  src/applications/gi/utils/helpers.js
Labels: BAH

#17666 CT: Make VRRAP Indicator a Learn More Link #26407
  src/applications/gi-sandbox/components/profile/AdditionalInformation.jsx
  src/applications/gi-sandbox/containers/Modals.jsx
  src/applications/gi/components/profile/AdditionalInformation.jsx
  src/applications/gi/containers/Modals.jsx
Labels: BAH

#17663 added VETTEC program length to compare
  src/applications/gi-sandbox/containers/ComparePage.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#17672 Fix undefined schema error
  src/platform/forms-system/src/js/state/helpers.js
  src/platform/forms-system/test/js/state/helpers.unit.spec.js
Labels: 526, VSA, bug, front end, vsa-claims-appeals

#17684 Fix onClick typo
  src/applications/static-pages/facilities/vet-center/components/VetCenterInfoSection.jsx
Labels: VSA, vet-center

#17699 Make sorting logic on staging go to prod
  src/applications/resources-and-support/hooks/useGetSearchResults.js
Labels: VSA, front end

#17694 526: Remove VA treatment end date
  package.json
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/config/schema.js
  src/applications/disability-benefits/all-claims/content/vaMedicalRecords.jsx
  src/applications/disability-benefits/all-claims/pages/vaMedicalRecords.js
  src/applications/disability-benefits/all-claims/tests/fixtures/data/maximal-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/secondary-new-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/maximal-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/secondary-new-test.json
  src/applications/disability-benefits/all-claims/tests/pages/vaMedicalRecords.unit.spec.jsx
  yarn.lock
Labels: 526, VSA, front end, vsa-claims-appeals

#17679 26302: Update profile page header content
  src/applications/gi-sandbox/components/CautionFlagAdditionalInfo.jsx
  src/applications/gi-sandbox/components/profile/HeadingSummary.jsx
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/components/vet-tec/VetTecHeadingSummary.jsx
  src/applications/gi-sandbox/containers/ProfilePageHeader.jsx
  src/applications/gi-sandbox/containers/SearchResultCard.jsx
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-profile-page.scss
  src/applications/gi-sandbox/utils/render.jsx
Labels: BAH, BAH-QA-needed

#17707 Bug: Fix wizard form start link
  src/applications/disability-benefits/all-claims/tests/all-claims-wizard.cypress.spec.js
  src/applications/disability-benefits/wizard/wizard-utils.js
Labels: 526, VSA, front end, vsa-claims-appeals

#17713 NOD: Update user info
  src/applications/appeals/10182/components/ContactInformation.jsx
  src/applications/appeals/10182/pages/contactInfo.js
  src/applications/appeals/10182/tests/10182-notice-of-disagreement.cypress.spec.js
  src/applications/appeals/10182/tests/components/ContactInformation.unit.spec.jsx
  src/applications/appeals/10182/tests/fixtures/data/maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/minimal-test.json
  src/applications/appeals/10182/tests/fixtures/data/transformed-maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/transformed-minimal-test.json
  src/applications/appeals/10182/tests/fixtures/mocks/user.json
  src/applications/appeals/10182/tests/nod.cypress.helpers.js
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/validations.js
Labels: NOD, VSA, front end, vsa-claims-appeals

#17715 [ON-HOLD] Remove all Find VA Benefits FE code
  src/applications/personalization/dashboard/components/Dashboard.jsx
  src/applications/personalization/dashboard/containers/DashboardApp.jsx
  src/applications/personalization/dashboard/containers/DashboardAppWrapper.jsx
  src/applications/personalization/dashboard/reducers/index.js
  src/applications/personalization/dashboard/routes.jsx
  src/applications/personalization/dashboard/tests/e2e/dashboard-e2e-helpers.js
  src/applications/personalization/dashboard/tests/e2e/dashboard.all-widgets.cypress.spec.js
  src/applications/personalization/dashboard/tests/e2e/dashboard.find-benefits-empty.cypress.spec.js
  src/applications/personalization/dashboard/tests/e2e/dashboard.find-benefits-selected.cypress.spec.js
  src/applications/personalization/dashboard/tests/e2e/dashboard.minimal-widgets.cypress.spec.js
  src/applications/personalization/preferences/actions/index.js
  src/applications/personalization/preferences/components/PreferenceItem.jsx
  src/applications/personalization/preferences/components/PreferenceList.jsx
  src/applications/personalization/preferences/components/PreferenceOption.jsx
  src/applications/personalization/preferences/constants.js
  src/applications/personalization/preferences/containers/JAWSSetPreferences.jsx
  src/applications/personalization/preferences/containers/PreferencesWidget.jsx
  src/applications/personalization/preferences/containers/SetPreferences.jsx
  src/applications/personalization/preferences/helperComponents.jsx
  src/applications/personalization/preferences/helpers.jsx
  src/applications/personalization/preferences/reducers/index.js
  src/applications/personalization/preferences/sass/preferences.scss
  src/applications/personalization/preferences/tests/actions/index.unit.spec.js
  src/applications/personalization/preferences/tests/components/PreferenceItem.unit.spec.jsx
  src/applications/personalization/preferences/tests/components/PreferenceList.unit.spec.jsx
  src/applications/personalization/preferences/tests/components/PreferenceOption.unit.spec.jsx
  src/applications/personalization/preferences/tests/containers/PreferencesWidget.unit.spec.jsx
  src/applications/personalization/preferences/tests/containers/SetPreferences.unit.spec.jsx
  src/applications/personalization/preferences/tests/helpers.unit.spec.jsx
  src/applications/personalization/preferences/tests/reducers/index.unit.spec.js
Labels: HOLD

#17716 Add support for cross-domain catch-all redirects + implement VAMC redirects
  src/applications/proxy-rewrite/redirects/crossDomainRedirects.json
  src/applications/proxy-rewrite/redirects/index.js
  src/applications/proxy-rewrite/tests/redirects/index.unit.spec.js
Labels: VSA, front end

#17683 Emergency mashup
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/api/MockLocatorApi.js
  src/applications/facility-locator/components/PaginationWrapper.jsx
  src/applications/facility-locator/components/ResultsList.jsx
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/components/SearchResultsHeader.jsx
  src/applications/facility-locator/components/search-results-items/EmergencyCareResult.jsx
  src/applications/facility-locator/components/search-results-items/common/CCProviderPhoneLink.jsx
  src/applications/facility-locator/config.js
  src/applications/facility-locator/constants/index.js
  src/applications/facility-locator/constants/mock-emergency-care-mashup-data.json
  src/applications/facility-locator/constants/mock-provider-services.json
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/components/EmergencyCareResult.unit.spec.jsx
  src/applications/facility-locator/tests/e2e/facilitySearch.cypress.spec.js
  src/applications/facility-locator/tests/e2e/providerSearch.cypress.spec.js
Labels: VSA, facility locator, front end

#17732 Remove 3 redirects
  src/applications/proxy-rewrite/redirects/crossDomainRedirects.json
  src/applications/proxy-rewrite/tests/redirects/index.unit.spec.js
Labels: VSA, front end

#17720 CT Sandbox - Search improvements
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/search/NameResults.jsx
  src/applications/gi-sandbox/containers/LocationSearchForm.jsx
  src/applications/gi-sandbox/containers/NameSearchForm.jsx
  src/applications/gi-sandbox/containers/RefineYourSearch.jsx
  src/applications/gi-sandbox/containers/SearchPage.jsx
  src/applications/gi-sandbox/containers/search/NameSearchResults.jsx
  src/applications/gi-sandbox/reducers/search.js
  src/applications/gi-sandbox/utils/helpers.js
Labels: BAH, BAH-IR-needed, BAH-QA-needed
