Repository department-of-veterans-affairs/vets-website, pull requests merged in 2021-02, with the labels that each got.

#15811 Add styling to CLP sections
  .github/CODEOWNERS
  src/platform/site-wide/sass/modules/_m-campaign-landing-page.scss
  src/platform/site-wide/sass/style.scss
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#15625 Remove 1010cg feature toggle
  src/applications/caregivers/containers/App.jsx
  src/applications/caregivers/tests/e2e/fixtures/mocks/feature-toggles.json
  src/applications/static-pages/caregiver-content-toggle/Off.jsx
  src/applications/static-pages/caregiver-content-toggle/On.jsx
  src/applications/static-pages/caregiver-content-toggle/createCaregiverContentToggle.js
  src/applications/static-pages/caregiver-content-toggle/widget.jsx
  src/applications/static-pages/static-pages-entry.js
  src/applications/static-pages/widgetTypes.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: Product Approved, Tech Debt, VSA, caregivers

#15867 Fix years on outreach and events pages
  src/site/includes/date.drupal.liquid
Labels: VSA, front end

#15883 [Development] Add 526 wizard Cypress tests
  src/applications/disability-benefits/all-claims/tests/all-claims-wizard.cypress.spec.js
Labels: 508/Accessibility, 526, BDD, Disability Benefits, VSA, front end

#15886 Update connect with us section
  src/site/layouts/campaign_landing_page.drupal.liquid
  src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
Labels: VSA, front end

#15856 [Development] Add HLR wizard Cypress tests
  src/applications/disability-benefits/996/tests/hlr-wizard.cypress.spec.js
Labels: 508/Accessibility, Disability Benefits, HLR, VSA, front end

#15862 Removed prod flag
  src/applications/gi/components/profile/ContactInformation.jsx
Labels: BAH

#15893 [Development] BDD: Replace buttons that should be links
  src/applications/disability-benefits/all-claims/containers/WizardContainer.jsx
  src/applications/disability-benefits/all-claims/content/confirmation-page.jsx
  src/applications/disability-benefits/all-claims/tests/containers/WizardContainer.unit.spec.jsx
Labels: 508/Accessibility, 526, BDD, Disability Benefits, VSA, front end

#15907 18808 chp31 cypress migration
  src/applications/vre/28-1900/tests/e2e/chapter31-maximal.cypress.spec.js
Labels: VSA

#15879 17564 manage dependents toggle
  src/applications/personalization/view-dependents/components/ViewDependentsList/ViewDependentsList.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsList/ViewDependentsListItem.jsx
  src/applications/personalization/view-dependents/containers/ViewDependentsApp.jsx
  src/applications/personalization/view-dependents/layouts/ViewDependentsLayout.jsx
  src/applications/personalization/view-dependents/layouts/ViewDependentsLists.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA

#15767 Add redirects [merge 02/03]
  src/applications/proxy-rewrite/redirects/crossDomainRedirects.json
Labels: VSA, front end

#15821 [Development] Add options to restart form & wizard
  src/applications/disability-benefits/996/components/createHLRApplicationStatus.jsx
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/disability-benefits/996/wizard/pages/legacyNo.jsx
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/containers/WizardContainer.jsx
  src/applications/disability-benefits/all-claims/tests/containers/Form526EZApp.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/containers/WizardContainer.unit.spec.jsx
  src/applications/disability-benefits/wizard/createWizard.jsx
  src/applications/disability-benefits/wizard/wizard-utils.js
  src/applications/static-pages/wizard/index.js
  src/applications/vre/28-8832/config/form.js
  src/applications/vre/28-8832/constants.js
  src/applications/vre/28-8832/containers/App.jsx
  src/applications/vre/28-8832/containers/WizardContainer.jsx
  src/applications/vre/28-8832/wizard/pages/ApplyLaterNotification.jsx
  src/applications/vre/28-8832/wizard/pages/DischargeNotification.jsx
  src/applications/vre/28-8832/wizard/pages/IneligibleNotice.jsx
  src/applications/vre/28-8832/wizard/pages/StartForm.jsx
  src/platform/forms/save-in-progress/ApplicationStatus.jsx
  src/platform/forms/save-in-progress/FormStartControls.jsx
  src/platform/forms/save-in-progress/RoutedSavableApp.jsx
  src/platform/forms/save-in-progress/selectors.js
  src/platform/forms/tests/forms.unit.spec.js
  src/platform/forms/tests/save-in-progress/ApplicationStatus.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/FormStartControls.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/RoutedSavableApp.unit.spec.jsx
  src/platform/site-wide/wizard/index.js
Labels: 526, BDD, Disability Benefits, HLR, VSA, front end

#15929 Update component library package.
  package.json
  yarn.lock
Labels: dependencies, front end

#15813 HCA Form Config Chapter/Page Refactor
  src/applications/hca/config/chapters/householdInformation/annualIncome.js
  src/applications/hca/config/chapters/householdInformation/deductibleExpenses.js
  src/applications/hca/config/chapters/householdInformation/dependentInformation.js
  src/applications/hca/config/chapters/householdInformation/financialDisclosure.js
  src/applications/hca/config/chapters/householdInformation/spouseInformation.js
  src/applications/hca/config/chapters/insuranceInformation/general.js
  src/applications/hca/config/chapters/insuranceInformation/medicare.js
  src/applications/hca/config/chapters/insuranceInformation/vaFacility.js
  src/applications/hca/config/chapters/militaryService/additionalInformation.js
  src/applications/hca/config/chapters/militaryService/documentUpload.js
  src/applications/hca/config/chapters/militaryService/serviceInformation.js
  src/applications/hca/config/chapters/vaBenefits/basicInformation.js
  src/applications/hca/config/chapters/veteranInformation/birthInformation.js
  src/applications/hca/config/chapters/veteranInformation/contactInformation.js
  src/applications/hca/config/chapters/veteranInformation/demographicInformation.js
  src/applications/hca/config/chapters/veteranInformation/personalnformation.js
  src/applications/hca/config/chapters/veteranInformation/veteranAddress.js
  src/applications/hca/config/chapters/veteranInformation/veteranHomeAddress.js
  src/applications/hca/config/form.js
  src/applications/hca/config/migrations.js
  src/applications/hca/definitions/dependent.js
  src/applications/hca/helpers.jsx
  src/applications/hca/validation.js
Labels: Design Approved, Tech Debt, caregivers, front end, hca

#15933 19137 686 pension questions
  package.json
  src/applications/disability-benefits/686c-674/config/chapters/674/student-school-address/studentSchoolAddress.js
  src/applications/disability-benefits/686c-674/config/chapters/report-dependent-death/dependent-additional-information/dependentAdditionalInformation.js
  src/applications/disability-benefits/686c-674/config/chapters/report-divorce/former-spouse-information/formerSpouseInformation.js
  src/applications/disability-benefits/686c-674/tests/config/reportDeathAdditionalInformation.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/reportDivorce.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/studentSchoolAddress.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/e2e/fixtures/add-child-add-674.json
  yarn.lock
Labels: VSA

#15943 [508] BDD: Wrap separation location input in fieldset
  src/applications/disability-benefits/all-claims/pages/separationLocation.js
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
Labels: 508/Accessibility, BDD, Disability Benefits, VSA, front end

#15948 Kelsonic 17513 clp transformers
  .github/CODEOWNERS
  src/site/stages/build/process-cms-exports/schemas/input/media-document_external.js
  src/site/stages/build/process-cms-exports/schemas/input/node-campaign_landing_page.js
  src/site/stages/build/process-cms-exports/schemas/input/paragraph-link_teaser_with_image.js
  src/site/stages/build/process-cms-exports/schemas/input/taxonomy_term-audience_tags.js
  src/site/stages/build/process-cms-exports/schemas/output/media-document_external.js
  src/site/stages/build/process-cms-exports/schemas/output/node-campaign_landing_page.js
  src/site/stages/build/process-cms-exports/schemas/output/paragraph-link_teaser_with_image.js
  src/site/stages/build/process-cms-exports/schemas/output/taxonomy_term-audience_tags.js
  src/site/stages/build/process-cms-exports/transformers/README.md
  src/site/stages/build/process-cms-exports/transformers/media-document_external.js
  src/site/stages/build/process-cms-exports/transformers/node-campaign_landing_page.js
  src/site/stages/build/process-cms-exports/transformers/paragraph-link_teaser_with_image.js
  src/site/stages/build/process-cms-exports/transformers/taxonomy_term-audience_tags.js
Labels: VSA, front end

#15947 18809 - view payments - update cy.route to cy.intercept
  src/applications/disability-benefits/view-payments/tests/e2e/view-payments.cypress.spec.js
Labels: VSA

#15866 18861: Display EVSS warning when remaining entitlement is > 180 days
  src/applications/edu-benefits/10203/helpers.jsx
Labels: BAH

#15953 Remove unused fields from event transformer
  src/site/stages/build/process-cms-exports/schemas/output/node-event.js
  src/site/stages/build/process-cms-exports/schemas/output/node-event_listing.js
  src/site/stages/build/process-cms-exports/transformers/node-event.js
Labels: vamc-facilities

#15959 Pretty print json
  script/cms/compare-json.js
Labels: VSA, front end

#15966 Update 686 e2e cy.route to cy.intercept
  src/applications/disability-benefits/686c-674/tests/e2e/686C-674-ancilliary.cypress.spec.js
  src/applications/disability-benefits/686c-674/tests/e2e/686C-674.cypress.spec.js
Labels: VSA

#15976 [Tech debt] Update Cypress tests
  src/applications/disability-benefits/996/tests/hlr-wizard.cypress.spec.js
  src/applications/disability-benefits/996/tests/hlr.cypress.spec.js
  src/applications/disability-benefits/all-claims/tests/all-claims-wizard.cypress.spec.js
  src/applications/disability-benefits/all-claims/tests/all-claims.cypress.spec.js
Labels: 526, BDD, Disability Benefits, HLR, Tech Debt, VSA, front end

#15979 19452 686 file upload language
  src/applications/disability-benefits/686c-674/config/chapters/add-a-child/child-place-of-birth/childStatusDescription.jsx
Labels: VSA

#15981 Update component-library
  package.json
  yarn.lock
Labels: front end

#15983 526/BDD: Handle Submission ID on Confirmation Page
  src/applications/disability-benefits/all-claims/content/confirmation-page.jsx
Labels: 526, BDD, Disability Benefits, VSA, front end

#15897 DT-18854 Added Search Tips for Yellow Ribbon
  src/applications/yellow-ribbon/actions/index.js
  src/applications/yellow-ribbon/components/SearchResult/index.jsx
  src/applications/yellow-ribbon/components/SearchResult/index.unit.spec.jsx
  src/applications/yellow-ribbon/components/SearchResultsPage/index.js
  src/applications/yellow-ribbon/constants/index.js
  src/applications/yellow-ribbon/constants/index.unit.spec.js
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx
  src/applications/yellow-ribbon/helpers/selectors.js
  src/applications/yellow-ribbon/reducers/index.js
  src/applications/yellow-ribbon/reducers/index.unit.spec.js
  src/applications/yellow-ribbon/sass/yellow-ribbon.scss
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA, front end

#15986 Fix focus on search this area button (FL)
  src/applications/facility-locator/containers/FacilitiesMap.jsx
  src/applications/facility-locator/utils/helpers.jsx
Labels: VSA, facility locator, front end

#16002 Fixed a small typo
  src/applications/yellow-ribbon/constants/index.js
Labels: VSA, front end

#16003 CT Sandbox Profile page setup
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/ProfileSection.jsx
  src/applications/gi-sandbox/components/ScorecardTags.jsx
  src/applications/gi-sandbox/components/ServiceError.jsx
  src/applications/gi-sandbox/components/profile/HeadingSummary.jsx
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
  src/applications/gi-sandbox/components/vet-tec/HeadingSummary.jsx
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/constants.js
  src/applications/gi-sandbox/containers/LandingPage.jsx
  src/applications/gi-sandbox/containers/ProfilePage.jsx
  src/applications/gi-sandbox/reducers/profile.js
  src/applications/gi-sandbox/reducers/utility.js
  src/applications/gi-sandbox/routes.jsx
  src/applications/gi-sandbox/utils/data/religiousAffiliations.js
  src/applications/gi-sandbox/utils/helpers.js
  src/applications/gi-sandbox/utils/render.jsx
Labels: BAH, BAH-IR-needed

#15998 [508] 526 wizard additional info & errors
  src/applications/disability-benefits/996/components/ContactInformation.jsx
  src/applications/disability-benefits/wizard/pages/bdd.jsx
  src/applications/disability-benefits/wizard/pages/disagree-file-claim.jsx
  src/applications/disability-benefits/wizard/pages/file-bdd.jsx
  src/applications/disability-benefits/wizard/pages/index.js
  src/applications/disability-benefits/wizard/pages/pageList.js
  src/applications/disability-benefits/wizard/pages/unable-to-file-bdd-production.jsx
  src/applications/disability-benefits/wizard/pages/unable-to-file-bdd.jsx
  src/applications/static-pages/tests/wizard/bdd-526.unit.spec.jsx
  src/applications/static-pages/tests/wizard/edu-benefits.unit.spec.jsx
  src/applications/static-pages/wizard/index.js
Labels: 508/Accessibility, 526, BDD, Disability Benefits, VSA, front end

#15935 [508] Date widget a11y updates
  src/applications/coronavirus-vaccination/tests/e2e/hideauth.cypress.spec.js
  src/applications/coronavirus-vaccination/tests/e2e/signup.cypress.spec.js
  src/applications/disability-benefits/686c-674/tests/e2e/686C-674-ancilliary.cypress.spec.js
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/tests/validations.unit.spec.js
  src/applications/vaos/tests/e2e/vaos-cypress-schedule-appointment-helpers.js
  src/platform/forms-system/src/js/helpers.js
  src/platform/forms-system/src/js/utilities/date/index.js
  src/platform/forms-system/src/js/utilities/validations/index.js
  src/platform/forms-system/src/js/validation.js
  src/platform/forms-system/src/js/widgets/DateWidget.jsx
  src/platform/forms-system/test/js/validation.unit.spec.js
  src/platform/forms/validations.js
Labels: 508/Accessibility, 526, BDD, Disability Benefits, VSA, front end

#15949 Added new sorting options for Find Forms
  src/applications/find-forms/components/SearchResult.jsx
  src/applications/find-forms/constants/index.js
  src/applications/find-forms/containers/SearchResults.jsx
  src/applications/find-forms/helpers/index.js
  src/applications/find-forms/tests/components/SearchResult.unit.spec.jsx
  src/applications/find-forms/tests/helpers/index.unit.spec.js
Labels: VSA, front end

#16016 Remove facilities API query
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 526, BDD, Disability Benefits, VSA, front end

#15819 DT 18950 removing sorting toggle with launch of feature.
  .github/CODEOWNERS
  src/applications/find-forms/containers/SearchResults.jsx
  src/applications/find-forms/helpers/selectors.js
  src/applications/find-forms/tests/containers/SearchResults.unit.spec.jsx
  src/applications/find-forms/tests/e2e/00-required.cypress.spec.js
Labels: VSA, front end

#16020 Set wizard start button type
  src/applications/static-pages/wizard/index.js
Labels: 508/Accessibility, 526, BDD, Disability Benefits, VSA, bug, front end

#15875 monthYearRange: Support Equal Months
  src/applications/disability-benefits/all-claims/pages/vaMedicalRecords.js
  src/platform/forms-system/src/js/definitions/monthYearRange.js
  src/platform/forms-system/src/js/utilities/validations/index.js
  src/platform/forms-system/src/js/validation.js
  src/platform/forms-system/test/js/validation.unit.spec.js
Labels: 526, BDD, Disability Benefits, VSA, front end, platform

#16028 Add proper error class to Date
  src/platform/forms-system/src/js/components/FieldTemplate.jsx
Labels: Disability Benefits, VSA, bug, front end

#16037 Update component-library
  package.json
  src/applications/personalization/profile/tests/components/direct-deposit/PaymentInformationEditError.unit.spec.jsx
  yarn.lock
Labels: 508/Accessibility, VSA

#16026 Kelsonic 19500 clp refinement
  src/applications/coronavirus-screener/tests/00.coronavirus-screener.e2e.spec.js
  src/platform/site-wide/sass/modules/_m-campaign-landing-page.scss
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/includes/header.html
  src/site/layouts/basic_landing_page.drupal.liquid
  src/site/layouts/campaign_landing_page.drupal.liquid
  src/site/layouts/checklist.drupal.liquid
  src/site/layouts/event.drupal.liquid
  src/site/layouts/faq_multiple_q_a.drupal.liquid
  src/site/layouts/health_care_local_facility.drupal.liquid
  src/site/layouts/health_care_region_page.drupal.liquid
  src/site/layouts/media_list_images.drupal.liquid
  src/site/layouts/media_list_videos.drupal.liquid
  src/site/layouts/news_story.drupal.liquid
  src/site/layouts/office.drupal.liquid
  src/site/layouts/page.drupal.liquid
  src/site/layouts/person_profile.drupal.liquid
  src/site/layouts/publication_listing.drupal.liquid
  src/site/layouts/q_a.drupal.liquid
  src/site/layouts/step_by_step.drupal.liquid
  src/site/layouts/support_resources_detail_page.drupal.liquid
  src/site/layouts/va_form.drupal.liquid
  src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
Labels: VSA, front end

#16012 Wrap My VA v2 in LoginRequired and Downtime components
  src/applications/personalization/dashboard-2/components/Dashboard.jsx
  src/applications/personalization/dashboard-2/tests/e2e/dashboard-loa1.cypress.spec.js
  src/applications/personalization/dashboard-2/tests/e2e/upcoming-downtime.cypress.spec.js
  src/applications/personalization/dashboard-2/useDowntimeApproachingRenderMethod.jsx
  src/applications/personalization/profile/components/Profile.jsx
  src/applications/personalization/profile/tests/components/Profile.unit.spec.js
  src/platform/user/authorization/components/RequiredLoginView.jsx
  src/platform/user/tests/authorization/components/RequiredLoginView.unit.spec.jsx
Labels: VSA

#16038 19652 chp31 update orientation copy
  src/applications/vre/28-1900/config/form.js
  src/applications/vre/28-1900/constants.js
  src/applications/vre/28-1900/containers/App.jsx
  src/applications/vre/28-1900/containers/OrientationWizardContainer.jsx
  src/applications/vre/28-1900/orientation/OrientationApp.jsx
  src/applications/vre/28-1900/orientation/StepComponent.jsx
  src/applications/vre/28-1900/orientation/utils.js
  src/applications/vre/28-1900/tests/e2e/chapter31-maximal.cypress.spec.js
  src/applications/vre/28-1900/wizard/pages/other/isOther.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/02-yesVaMemorandum.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-yesIDES.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/02-yesDisabilityRating.jsx
Labels: VSA

#16051 Switch to 526 Save-in-progress endpoint
  src/applications/disability-benefits/all-claims/local-dev-mock-api/index.js
  src/applications/disability-benefits/all-claims/tests/all-claims.cypress.spec.js
  src/applications/disability-benefits/all-claims/tests/disability-benefits-helpers.js
  src/applications/disability-benefits/all-claims/tests/fixtures/mocks/in-progress-forms.json
  src/platform/forms/constants.js
  src/platform/forms/helpers.js
  src/platform/forms/save-in-progress/actions.js
  src/platform/forms/save-in-progress/api.js
  src/platform/forms/tests/save-in-progress/actions.unit.spec.js
Labels: 526, BDD, Disability Benefits, VSA, front end

#16062 fix tag variable names
  src/applications/gi/components/profile/HeadingSummary.jsx
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16060 19553 remove payments feature toggle
  src/applications/disability-benefits/view-payments/tests/e2e/view-payments.cypress.spec.js
  src/applications/personalization/view-representative/reducers/index.js
  src/applications/personalization/view-representative/tests/reducers/index.unit.spec.js
  src/applications/static-pages/view-payment-history/ViewPaymentHistoryCTA.js
  src/platform/site-wide/cta-widget/helpers.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA

#16072 Accessibility updates to 526 wizard
  src/applications/disability-benefits/wizard/pages/unable-to-file-bdd.jsx
Labels: 508/Accessibility, 526, Disability Benefits, VSA, front end

#16082 Revert SiP 526 endpoint change
  src/applications/disability-benefits/all-claims/local-dev-mock-api/index.js
  src/applications/disability-benefits/all-claims/tests/all-claims.cypress.spec.js
  src/applications/disability-benefits/all-claims/tests/disability-benefits-helpers.js
  src/applications/disability-benefits/all-claims/tests/fixtures/mocks/in-progress-forms.json
  src/platform/forms/constants.js
  src/platform/forms/tests/save-in-progress/actions.unit.spec.js
Labels: 526, Disability Benefits, VSA, bug, front end

#16004 Handle operationalHoursSpecialInstructions field for VA health
  src/applications/facility-locator/components/LocationHours.jsx
  src/applications/facility-locator/containers/FacilityDetail.jsx
  src/applications/facility-locator/tests/components/LocationHours.unit.spec.jsx
  src/applications/facility-locator/utils/selectors.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: VSA, facility locator, front end

#16070 Kelsonic 16749 clp analytics
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/includes/social-share.drupal.liquid
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#16084 Sort suggestions by length
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: VSA, front end

#16080 Removed OMB/Expiration date feature flag
  src/applications/edu-benefits/0994/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990e/containers/IntroductionPage.jsx
  src/applications/edu-benefits/1990n/containers/IntroductionPage.jsx
  src/applications/edu-benefits/5495/containers/IntroductionPage.jsx
Labels: BAH

#16058 Flatten 1010cg UI schema
  src/applications/ask-a-question/form/contactInformation/contactInformationPage.js
  src/applications/caregivers/config/chapters/primary/primaryContact.js
  src/applications/caregivers/config/chapters/primary/primaryHealthCoverage.js
  src/applications/caregivers/config/chapters/primary/primaryInfo.js
  src/applications/caregivers/config/chapters/secondaryOne/hasSecondaryCaregiver.js
  src/applications/caregivers/config/chapters/secondaryOne/secondaryCaregiverContact.js
  src/applications/caregivers/config/chapters/secondaryOne/secondaryInfo.js
  src/applications/caregivers/config/chapters/secondaryTwo/secondaryTwoContactInfo.js
  src/applications/caregivers/config/chapters/secondaryTwo/secondaryTwoInfo.js
  src/applications/caregivers/config/chapters/veteran/vetContactInfo.js
  src/applications/caregivers/config/chapters/veteran/vetInfo.js
  src/applications/caregivers/config/chapters/veteran/vetMedicalCenter.js
  src/applications/caregivers/config/form.js
  src/applications/caregivers/definitions/UIDefinitions/caregiverUI.js
  src/applications/caregivers/definitions/UIDefinitions/sharedUI.js
  src/applications/caregivers/definitions/UIDefinitions/veteranUI.js
  src/applications/caregivers/definitions/caregiverUI.js
  src/applications/caregivers/definitions/constants.js
  src/applications/caregivers/helpers.js
Labels: Tech Debt, caregivers, front end

#16089 Update styling to match style guide
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
  src/platform/site-wide/user-nav/tests/components/SearchMenu.unit.spec.jsx
Labels: VSA, front end

#16069 Dt 19332 refactor e2e yr
  src/applications/find-forms/tests/e2e/find-forms-required.cypress.spec.js
  src/applications/yellow-ribbon/00-required.e2e.spec.js
  src/applications/yellow-ribbon/containers/SearchForm/index.jsx
  src/applications/yellow-ribbon/containers/SearchForm/index.unit.spec.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
  src/applications/yellow-ribbon/containers/SearchResults/index.unit.spec.jsx
  src/applications/yellow-ribbon/e2e/tests/yellow-ribbon.cypress.spec.js
Labels: VSA, front end

#16097 Bug - Updates Auth error screen content
  src/applications/auth/containers/AuthApp.jsx
Labels: Identity

#16098 [508] Add unique aria-labels on array card buttons
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
  src/applications/disability-benefits/all-claims/components/ConditionReviewField.jsx
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
Labels: 508/Accessibility, 526, Disability Benefits, VSA, front end

#16056 feature/16544axe-4-bump - Bumping axe to current version 4.1.1 in CI/CD pipeline
  package.json
  src/platform/forms-system/src/js/components/ProgressBar.jsx
  src/platform/forms-system/src/js/fields/FileField.jsx
  src/platform/forms-system/test/js/components/ProgressBar.unit.spec.jsx
  src/platform/testing/e2e/cypress/support/commands/axeCheck.js
  yarn.lock
Labels: 508/Accessibility, testing

#16042 Get letters after address verification
  src/applications/letters/routes.jsx
Labels: Disability Benefits, VSA, bug, front end, va-letters

#16094 Find Forms 508 screen reader fixes.
  src/applications/find-forms/containers/SearchResults.jsx
Labels: 508/Accessibility, VSA, front end

#15950 Remove address feature toggle from HCA
  src/applications/hca/HealthCareApp.jsx
  src/applications/hca/config/chapters/veteranInformation/veteranAddress.js
  src/applications/hca/config/chapters/veteranInformation/veteranHomeAddress.js
  src/applications/hca/config/form.js
  src/applications/hca/helpers.jsx
  src/applications/hca/tests/config/veteranInformation.unit.spec.jsx
  src/applications/hca/tests/fixtures/mocks/toggle-off-multiple-address-1010ez.json
  src/applications/hca/tests/fixtures/mocks/toggle-on-multiple-address-1010ez.json
  src/applications/hca/tests/hca.cypress.spec.js
  src/applications/hca/tests/schema/foreign-address-test.json
  src/applications/hca/tests/schema/minimal-test.json
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: Tech Debt, caregivers, front end, hca

#16099 DT-18234 & DT-18470 Adjusting Google Analytics
  src/applications/yellow-ribbon/actions/index.js
  src/applications/yellow-ribbon/containers/SearchResults/index.jsx
Labels: VSA, front end

#16102 18981 view dependents schemaform
  src/applications/personalization/view-dependents/components/ViewDependentsFormStates/BuildFormlett.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsFormStates/ViewDependentsChildForm.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsFormStates/ViewDependentsSpouseForm.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsList/ViewDependentsList.jsx
  src/applications/personalization/view-dependents/components/ViewDependentsList/ViewDependentsListItem.jsx
  src/applications/personalization/view-dependents/manage-dependents/containers/ManageDependentsApp.jsx
  src/applications/personalization/view-dependents/manage-dependents/redux/actions.js
  src/applications/personalization/view-dependents/manage-dependents/redux/reducers.js
  src/applications/personalization/view-dependents/manage-dependents/schemas.js
  src/applications/personalization/view-dependents/reducers/index.js
  src/applications/personalization/view-dependents/sass/view-dependents.scss
Labels: VSA

#16117 Updates error message page for failed logins
  src/applications/auth/containers/AuthApp.jsx
Labels: Identity

#16091 Srsuddath 19682 analytics fixes
  src/applications/find-forms/actions/index.js
  src/applications/resources-and-support/components/SearchBar.jsx
  src/applications/resources-and-support/hooks/useGetSearchResults.js
  src/applications/search/actions/index.js
  src/applications/yellow-ribbon/actions/index.js
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: VSA, front end

#16108 Minor clp tweaks
  src/site/layouts/campaign_landing_page.drupal.liquid
  src/site/stages/build/drupal/graphql/landingPage.graphql.js
Labels: VSA, front end

#16122 Hard code see more stories cta
  src/applications/health-care-questionnaire/list/tests/e2e/03.downtime.notifier.cypress.spec.js
  src/applications/health-care-questionnaire/questionnaire/tests/e2e/06.downtime.notifier.cypress.spec.js
  src/applications/yellow-ribbon/actions/index.js
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#16032 CT: Create desktop sticky nav custom component #19569
  src/applications/gi-sandbox/components/ProfileNavBar.jsx
  src/applications/gi-sandbox/components/ProfileSection.jsx
  src/applications/gi-sandbox/components/profile/HeadingSummary.jsx
  src/applications/gi-sandbox/components/profile/InstitutionProfile.jsx
  src/applications/gi-sandbox/components/vet-tec/HeadingSummary.jsx
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/containers/GiBillApp.jsx
  src/applications/gi-sandbox/containers/LandingPage.jsx
  src/applications/gi-sandbox/sass/gi-sandbox.scss
  src/applications/gi-sandbox/sass/partials/_gi-modal.scss
  src/applications/gi-sandbox/sass/partials/_gi-profile-page.scss
  src/applications/gi-sandbox/sass/partials/_gi-vet-tec.scss
Labels: BAH, BAH-IR-needed, BAH-QA-needed

#16078 Clear control for search input in FL
  src/applications/facility-locator/actions/index.js
  src/applications/facility-locator/components/SearchControls.jsx
  src/applications/facility-locator/containers/FacilitiesMap.jsx
  src/applications/facility-locator/reducers/searchQuery.js
  src/applications/facility-locator/sass/facility-locator.scss
  src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js
  src/applications/facility-locator/utils/actionTypes.js
Labels: VSA, facility locator, front end

#16128 Update youtube url func
  src/site/filters/liquid.js
Labels: VSA, front end

#16110 Remove legacy health care manage benefits pages
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/LegacyContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/LegacyContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/LegacyContent/index.unit.spec.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/App/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/LegacyContent/index.js
  src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/LegacyContent/index.unit.spec.js
Labels: VSA, front end

#16115 CT: Create mobile sticky nav custom component #19721
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/ProfileNavBar.jsx
  src/applications/gi-sandbox/components/vet-tec/InstitutionProfile.jsx
  src/applications/gi-sandbox/constants.js
  src/applications/gi-sandbox/containers/GiBillApp.jsx
  src/applications/gi-sandbox/sass/gi-sandbox.scss
  src/applications/gi-sandbox/sass/partials/_gi-profile-page.scss
  src/applications/gi-sandbox/sass/partials/_gi-vet-tec.scss
  src/applications/gi-sandbox/utils/render.jsx
Labels: BAH, BAH-QA-needed

#16130 18983 view dependents child schema
  src/applications/personalization/view-dependents/components/ViewDependentsList/ViewDependentsListItem.jsx
  src/applications/personalization/view-dependents/manage-dependents/schemas.js
Labels: VSA

#16112 Removed gibctBenefitFilterEnhancement Feature Flag
  src/applications/gi/components/profile/BenefitsForm.jsx
  src/applications/gi/components/search/InstitutionSearchForm.jsx
  src/applications/gi/components/search/OnlineClassesFilter.jsx
  src/applications/gi/containers/SearchPage.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: BAH

#16087 10-10CG SSN removed party bug
  src/applications/caregivers/helpers.js
  src/applications/caregivers/tests/helpers.unit.spec.js
Labels: bug, caregivers, front end

#16143 Kelsonic update clp minor fixes
  src/platform/site-wide/sass/modules/_m-campaign-landing-page.scss
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#16114 [508] Form array buttons need unique aria-labels
  src/applications/disability-benefits/996/pages/contestedIssues.js
  src/applications/disability-benefits/996/pages/sameOffice.js
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
  src/applications/disability-benefits/all-claims/pages/addDisabilities.js
  src/applications/disability-benefits/all-claims/pages/militaryHistory.js
  src/applications/disability-benefits/all-claims/pages/newDisabilityFollowUp.js
  src/applications/disability-benefits/all-claims/pages/prisonerOfWar.js
  src/applications/disability-benefits/all-claims/pages/vaMedicalRecords.js
  src/applications/pre-need/utils/helpers.js
  src/platform/forms-system/src/js/components/ProgressButton.jsx
  src/platform/forms-system/src/js/fields/ArrayField.jsx
  src/platform/forms-system/src/js/review/ArrayField.jsx
  src/platform/forms-system/src/js/review/ObjectField.jsx
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
  src/platform/forms-system/test/js/fields/ArrayField.unit.spec.jsx
  src/platform/forms-system/test/js/review/ArrayField.unit.spec.jsx
  src/platform/forms-system/test/js/review/ObjectField.unit.spec.jsx
Labels: 508/Accessibility, 526, BDD, Disability Benefits, VSA, front end

#16157 Add back to top component to clp
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#16148 Make FL query attributes visible for troubleshooting
  src/applications/facility-locator/config.js
  src/applications/facility-locator/containers/FacilitiesMap.jsx
  src/applications/facility-locator/tests/api-url-parameters.unit.spec.js
Labels: VSA, facility locator, front end

#16164 Remove some section padding for clp
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front end

#16171 Update suggestion formatting
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: VSA, front end

#16168 Fix 526 validation issue
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/tests/validations.unit.spec.js
  src/applications/disability-benefits/all-claims/validations.js
Labels: 526, BDD, VSA, bug, front end, vsa-claims-appeals

#16177 Srsuddath search analytics tagging
  src/applications/find-forms/actions/index.js
  src/applications/resources-and-support/components/SearchBar.jsx
  src/applications/resources-and-support/hooks/useGetSearchResults.js
  src/applications/search/actions/index.js
  src/applications/search/containers/SearchApp.jsx
  src/applications/yellow-ribbon/actions/index.js
  src/platform/site-wide/user-nav/components/SearchMenu.jsx
Labels: VSA, front end

#16174 Remove 526 axe color contrast exception
  src/applications/disability-benefits/all-claims/tests/all-claims.cypress.spec.js
Labels: 508/Accessibility, 526, BDD, VSA, front end, vsa-claims-appeals

#16180 19770 view dependents parent flow
  src/applications/personalization/view-dependents/layouts/ViewDependentsLayout.jsx
  src/applications/personalization/view-dependents/manage-dependents/schemas.js
Labels: VSA

#16167 Tweak error messaging for graphql errors
  src/site/stages/build/drupal/api.js
Labels: VSA, front end

#16183 Minor content tweak
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/UnauthContent/index.js
Labels: VSA, front end

#16189 526: Force text wrap of long disability names
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
  src/applications/disability-benefits/all-claims/components/NewDisability.jsx
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
Labels: 526, VSA, bug, front end, vsa-claims-appeals

#16185 update vets-json-schema version
  package.json
  yarn.lock
Labels: VSA

#16191 Small change on form details button
  src/site/layouts/va_form.drupal.liquid
Labels: VSA, front end

#16162 Comparison Sandbox - Search Controls
  src/applications/gi-sandbox/actions/index.js
  src/applications/gi-sandbox/components/AccordionDropdown.jsx
  src/applications/gi-sandbox/components/Checkbox.jsx
  src/applications/gi-sandbox/components/CheckboxGroup.jsx
  src/applications/gi-sandbox/components/Dropdown.jsx
  src/applications/gi-sandbox/components/GiBillBreadcrumbs.jsx
  src/applications/gi-sandbox/components/LearnMoreLabel.jsx
  src/applications/gi-sandbox/components/Modal.jsx
  src/applications/gi-sandbox/components/RadioButtons.jsx
  src/applications/gi-sandbox/components/SearchBenefits.jsx
  src/applications/gi-sandbox/components/content/YellowRibbonModalContent.jsx
  src/applications/gi-sandbox/constants.js
  src/applications/gi-sandbox/containers/GiBillApp.jsx
  src/applications/gi-sandbox/containers/LandingPage.jsx
  src/applications/gi-sandbox/containers/Modals.jsx
  src/applications/gi-sandbox/containers/SearchSchools.jsx
  src/applications/gi-sandbox/gi-entry.jsx
  src/applications/gi-sandbox/reducers/constants.js
  src/applications/gi-sandbox/reducers/eligibility.js
  src/applications/gi-sandbox/reducers/filters.js
  src/applications/gi-sandbox/reducers/index.js
  src/applications/gi-sandbox/reducers/modals.js
  src/applications/gi-sandbox/reducers/preview.js
  src/applications/gi-sandbox/sass/gi-sandbox.scss
  src/applications/gi-sandbox/sass/gi.scss
  src/applications/gi-sandbox/sass/partials/_gi-autocomplete.scss
  src/applications/gi-sandbox/sass/partials/_gi-landing-page.scss
  src/applications/gi-sandbox/sass/partials/_gi-preview-banner.scss
  src/applications/gi-sandbox/sass/partials/_gi-search-page.scss
  src/applications/gi-sandbox/sass/partials/_gi-vet-tec.scss
  src/applications/gi-sandbox/utils/helpers.js
Labels: BAH

#16198 20153 686 income questions
  package.json
  src/applications/disability-benefits/686c-674/config/chapters/674/student-name-ssn/studentNameSSN.js
  src/applications/disability-benefits/686c-674/config/chapters/report-child-stopped-attending-school/child-information/childInformation.js
  src/applications/disability-benefits/686c-674/config/chapters/report-dependent-death/dependent-additional-information/dependentAdditionalInformation.js
  src/applications/disability-benefits/686c-674/config/chapters/report-divorce/former-spouse-information/formerSpouseInformation.js
  src/applications/disability-benefits/686c-674/config/chapters/report-marriage-of-child/child-information/childInformation.js
  src/applications/disability-benefits/686c-674/config/chapters/taskWizard/wizard/helpers.jsx
  src/applications/disability-benefits/686c-674/config/helpers.js
  src/applications/disability-benefits/686c-674/tests/config/reportChildStoppedAttendingSchool.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/reportMarriageOfChild.unit.spec.jsx
  src/applications/disability-benefits/686c-674/tests/config/studentNameSSN674.unit.spec.jsx
  yarn.lock
Labels: VSA

#16202 Update CT Sandbox Search Labels
  src/applications/gi-sandbox/containers/SearchSchools.jsx
Labels: BAH

#16205 Prevent duplicate new disabilities
  src/applications/disability-benefits/all-claims/components/ArrayField.jsx
  src/applications/disability-benefits/all-claims/pages/addDisabilities.js
  src/applications/disability-benefits/all-claims/sass/disability-benefits.scss
  src/applications/disability-benefits/all-claims/tests/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils.jsx
  src/applications/disability-benefits/all-claims/validations.js
Labels: 526, BDD, VSA, bug, front end, vsa-claims-appeals
