Repository department-of-veterans-affairs/vets-website, pull requests merged in 2022-12, with the labels that each got.

#22727 update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Identity

#22839 48749 - [eFSR] Resolution Option Explainer Enhancement
  src/applications/financial-status-report/components/ResolutionExplainerWidget.jsx
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/pages/index.js
  src/applications/financial-status-report/pages/resolution/resolutionExplainer.js
Labels: front end, vsa-benefits-2

#22418 47691 SiS Enabled Sign-in Redirect Bug Fix
  src/applications/claims-status/containers/ClaimsStatusApp.jsx
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/view-payments/containers/App.jsx
  src/applications/edu-benefits/containers/EducationGate.jsx
  src/applications/letters/containers/LettersApp.jsx
  src/applications/lgy/coe/status/containers/App.jsx
  src/applications/messages/components/Table.jsx
  src/applications/mhv/secure-messaging/containers/AppOld.jsx
  src/applications/personalization/dashboard/components/Dashboard.jsx
  src/applications/personalization/profile/components/Profile.jsx
  src/applications/personalization/profile/tests/components/Profile.unit.spec.js
  src/applications/personalization/rated-disabilities/containers/RatedDisabilitiesApp.jsx
  src/applications/personalization/view-dependents/containers/ViewDependentsApp.jsx
  src/applications/personalization/view-representative/containers/ViewRepresentativeApp.jsx
  src/applications/post-911-gib-status/containers/Post911GIBStatusApp.jsx
  src/applications/vaos/components/EnrolledRoute.jsx
  src/applications/veteran-id-card/containers/VeteranIDCard.jsx
  src/platform/user/authorization/components/RequiredLoginView.jsx
  src/platform/user/tests/authorization/components/RequiredLoginView.unit.spec.jsx
Labels: Identity

#22875 Add setFormData to CustomPage on review & submit page
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
  src/platform/forms-system/test/js/review/ReviewCollapsibleChapter.unit.spec.jsx
Labels: bug, forms-library

#22880 Supplemental Claim | Update evidence uploads
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/content/evidenceUpload.jsx
  src/applications/appeals/995/content/evidenceUploadOther.jsx
  src/applications/appeals/995/pages/evidenceUpload.js
  src/applications/appeals/995/pages/evidenceUploadOther.js
  src/applications/appeals/995/tests/pages/evidenceUpload.unit.spec.js
  src/applications/appeals/995/tests/pages/evidenceUploadOther.unit.spec.jsx
  src/applications/appeals/995/utils/upload.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#22921 50152 - [eFSR] - Add Navigation Testing to EFSR E2E Tests
  src/applications/financial-status-report/components/GrossMonthlyIncomeInput.jsx
  src/applications/financial-status-report/tests/e2e/efsr-5655.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/pages/employment/EnhancedVeteranEmploymentHistory.js
Labels: front end, vsa-benefits-2

#22925 Supplemental Claims | No modals on first entry
  src/applications/appeals/995/components/EvidencePrivateRecords.jsx
  src/applications/appeals/995/components/EvidenceVaRecords.jsx
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceVaRecords.unit.spec.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#22964 Certificate of Eligibility | Make PDF download directly
  src/applications/lgy/coe/shared/components/ReviewAndDownload.jsx
  src/applications/lgy/coe/shared/tests/components/ReviewAndDownload.unit.spec.jsx
  src/applications/lgy/coe/status/components/DocumentList/ListItem.jsx
  src/applications/lgy/coe/status/tests/components/DocumentList/List.unit.spec.jsx
  src/applications/lgy/coe/status/tests/components/DocumentList/ListItem.unit.spec.jsx
Labels: front end, benefits-team-1, squad-2, COE

#22965 Certificate of Eligibility | Fix logic issues
  src/applications/lgy/coe/form/config/chapters/loans/loanHistory.js
  src/applications/lgy/coe/form/config/chapters/loans/loanIntent.js
  src/applications/lgy/coe/form/constants.js
  src/applications/lgy/coe/form/tests/config/loans/loanHistory.unit.spec.jsx
  src/applications/lgy/coe/form/tests/config/loans/loanIntent.unit.spec.jsx
  src/applications/lgy/coe/form/tests/fixtures/mocks/submitted.js
  src/applications/lgy/coe/form/tests/validations.unit.spec.js
  src/applications/lgy/coe/form/validations.js
Labels: front end, benefits-team-1, squad-2, COE

#22933 Add Datadog UX Monitoring to Health Care application
  src/applications/hca/app-entry.jsx
  src/applications/hca/config/form.js
  src/applications/hca/containers/App.jsx
  src/applications/hca/hooks/useBrowserMonitoring.jsx
  src/applications/hca/manifest.json
  src/applications/hca/routes.jsx
  src/applications/hca/tests/e2e/fixtures/mocks/feature-toggles-aiq.json
  src/applications/hca/tests/e2e/fixtures/mocks/feature-toggles-shortForm.json
  src/applications/hca/tests/e2e/fixtures/mocks/feature-toggles.json
  src/applications/hca/tests/utils/selectors/feature-toggles.unit.spec.js
  src/applications/hca/tests/utils/selectors/selectors.unit.spec.js
  src/applications/hca/utils/helpers.js
  src/applications/hca/utils/selectors/feature-toggles.js
  src/applications/hca/utils/selectors/index.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: DO NOT MERGE

#22974 Supplemental Claims | Attempt to fix flaky tests
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceVaRecords.unit.spec.jsx
Labels: bug, front end, squad-2, Supplemental Claims

#22946 Supplemental Claims | Update content & error messages
  src/applications/appeals/995/components/EditContactInfo.jsx
  src/applications/appeals/995/components/EvidencePrivateRecordsRequest.jsx
  src/applications/appeals/995/components/ShowIssuesList.jsx
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/content/IssueSummary.jsx
  src/applications/appeals/995/content/addIssue.jsx
  src/applications/appeals/995/content/contestableIssues.jsx
  src/applications/appeals/995/content/evidenceUpload.jsx
  src/applications/appeals/995/content/evidenceVaRecords.jsx
  src/applications/appeals/995/content/issueSummary.jsx
  src/applications/appeals/995/pages/evidenceUploadOther.js
  src/applications/appeals/995/pages/evidenceVaRecordsRequest.js
  src/applications/appeals/995/pages/issueSummary.js
  src/applications/appeals/995/sass/995-supplemental-claim.scss
  src/applications/appeals/995/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidencePrivateRecordsRequest.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceVaRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/ShowIssuesList.unit.spec.jsx
  src/applications/appeals/995/tests/content/IssueSummary.unit.spec.jsx
  src/applications/appeals/995/tests/pages/evidenceUploadOther.unit.spec.jsx
  src/applications/appeals/995/tests/pages/evidenceVaRecordsRequest.unit.spec.jsx
  src/applications/appeals/995/tests/validations/date.unit.spec.js
  src/applications/appeals/995/tests/validations/evidence.unit.spec.js
  src/applications/appeals/995/validations/date.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#22979 Supplemental Claims | Add private records authorization warning
  src/applications/appeals/995/components/EvidencePrivateRecordsAuthorization.jsx
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/content/evidencePrivateRecordsAuthorization.jsx
  src/applications/appeals/995/content/evidenceVaRecords.jsx
  src/applications/appeals/995/content/noticeOfAcknowledgement.jsx
  src/applications/appeals/995/pages/evidencePrivateRecordsAuthorization.js
  src/applications/appeals/995/tests/components/EvidencePrivateRecordsAuthorization.unit.spec.jsx
  src/applications/appeals/995/tests/pages/evidencePrivateRecordsAuthorization.unit.spec.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#22992 Supplemental Claims | Update content & fix alert visibility
  src/applications/appeals/995/components/AddIssue.jsx
  src/applications/appeals/995/components/EvidenceSummary.jsx
  src/applications/appeals/995/components/EvidenceSummaryReview.jsx
  src/applications/appeals/995/components/PrimaryPhone.jsx
  src/applications/appeals/995/components/VeteranInformation.jsx
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/containers/IntroductionPage.jsx
  src/applications/appeals/995/content/IssueSummary.jsx
  src/applications/appeals/995/content/contestableIssues.jsx
  src/applications/appeals/995/content/evidencePrivateLimitation.js
  src/applications/appeals/995/content/evidencePrivateRecords.jsx
  src/applications/appeals/995/content/evidenceSummary.jsx
  src/applications/appeals/995/content/evidenceSummaryLists.jsx
  src/applications/appeals/995/content/evidenceUpload.jsx
  src/applications/appeals/995/content/evidenceUploadOther.jsx
  src/applications/appeals/995/content/evidenceWillUpload.jsx
  src/applications/appeals/995/pages/evidenceWillUpload.js
  src/applications/appeals/995/sass/995-supplemental-claim.scss
  src/applications/appeals/995/subtask/pages/start.jsx
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceSummary.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceSummaryReview.unit.spec.jsx
  src/applications/appeals/995/tests/content/evidenceSummaryLists.unit.spec.jsx
  src/applications/appeals/995/tests/pages/evidenceUploadOther.unit.spec.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims
