Repository department-of-veterans-affairs/vets-website, pull requests merged in 2022-07, with the labels that each got.

#21545 SaveInProgressIntro default heading update
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
Labels: 508/Accessibility

#21550 CDP - 42709 - Bold Link in Debt Details Card
  src/applications/combined-debt-portal/debt-letters/components/DebtSummaryCard.jsx
  src/applications/combined-debt-portal/debt-letters/tests/e2e/debt-letters.cypress.spec.js
Labels: front end, vsa-benefits-2

#21548 CDP - 43601 - Implement Not Enrolled in Healthcare Alert
  src/applications/combined-debt-portal/combined/components/Balances.jsx
  src/applications/combined-debt-portal/combined/components/MCPAlerts.jsx
  src/applications/combined-debt-portal/combined/tests/e2e/combined-debt-portal.cypress.spec.js
  src/applications/combined-debt-portal/combined/tests/e2e/helpers/cdp-helpers.js
  src/applications/combined-debt-portal/medical-copays/containers/DetailPage.jsx
Labels: front end, vsa-benefits-2

#21570 42872 - [CDP] - Incorporate accessibility feedback from the midpoint review: 'Check details' link
  src/applications/combined-debt-portal/debt-letters/components/DebtSummaryCard.jsx
  src/applications/combined-debt-portal/medical-copays/components/BalanceCard.jsx
Labels: front end, vsa-benefits-2

#21580 [CDP] 42785 Copay - Updating helper links to use relative paths
  src/applications/combined-debt-portal/medical-copays/components/DisputeCharges.jsx
Labels: front end, vsa-benefits-2

#21578 42872 - CDP - Aria-DescribedBy Updates
  src/applications/combined-debt-portal/debt-letters/components/DebtSummaryCard.jsx
  src/applications/combined-debt-portal/medical-copays/components/BalanceCard.jsx
Labels: front end, vsa-benefits-2

#21579 Supplemental Claims | Add placeholder pages & functions
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/config/prefill-transformer.js
  src/applications/appeals/995/config/submit-transformer.js
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/content/addIssue.jsx
  src/applications/appeals/995/content/contestableIssues.jsx
  src/applications/appeals/995/migrations/index.js
  src/applications/appeals/995/pages/addIssue.js
  src/applications/appeals/995/pages/benefitType.js
  src/applications/appeals/995/pages/certifcationAndSignature.js
  src/applications/appeals/995/pages/claimantName.js
  src/applications/appeals/995/pages/claimantType.js
  src/applications/appeals/995/pages/contactInfo.js
  src/applications/appeals/995/pages/contestableIssues.js
  src/applications/appeals/995/pages/evidencePrivateAdd.js
  src/applications/appeals/995/pages/evidencePrivateRecords.js
  src/applications/appeals/995/pages/evidencePrivateUpload.js
  src/applications/appeals/995/pages/evidenceSummary.js
  src/applications/appeals/995/pages/evidenceTypes.js
  src/applications/appeals/995/pages/evidenceUpload.js
  src/applications/appeals/995/pages/evidenceVaRecords.js
  src/applications/appeals/995/pages/issueSummary.js
  src/applications/appeals/995/pages/noticeOfAcknowledgement.js
  src/applications/appeals/995/pages/optIn.js
  src/applications/appeals/995/pages/veteranInfo.js
  src/applications/appeals/995/utils/dates.js
  src/applications/appeals/995/utils/helpers.js
  src/applications/appeals/995/utils/replace.js
  src/applications/appeals/995/utils/submit.js
  src/applications/appeals/995/utils/ui.js
  src/applications/appeals/995/validations/date.js
  src/applications/appeals/995/validations/index.js
  src/applications/appeals/995/validations/issues.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#21600 CDP - Staging Review - Launch Blocker - Aria Description with Extra Character
  src/applications/combined-debt-portal/debt-letters/components/DebtSummaryCard.jsx
Labels: front end, vsa-benefits-2

#21607 43971 - CDP - [Markup and meta data] HTML markup isn't valid. (09.01.1) - Staging Review Launch Blocker
  src/applications/combined-debt-portal/debt-letters/components/DebtSummaryCard.jsx
Labels: front end, vsa-benefits-2

#21613 43973 - CDP - Markup and meta data] HTML markup isn't valid. (09.01.2) - Staging Review Launch Blocker
  src/applications/combined-debt-portal/medical-copays/components/BalanceCard.jsx
Labels: front end, vsa-benefits-2

#21529 1010CG Added signAsRepresentative to submission payload
  src/applications/caregivers/helpers.js
Labels: DO NOT MERGE

#21627 43970 & 43974 - CDP - Staging Review - Header Element Changes
  src/applications/combined-debt-portal/debt-letters/components/DebtDetailsCard.jsx
  src/applications/combined-debt-portal/debt-letters/components/DebtSummaryCard.jsx
  src/applications/combined-debt-portal/debt-letters/tests/DebtDetailsCard.unit.spec.js
  src/applications/combined-debt-portal/debt-letters/tests/DebtSummaryCard.unit.spec.js
  src/applications/combined-debt-portal/debt-letters/tests/e2e/details-card-content.cypress.spec.js
Labels: front end, vsa-benefits-2

#21614 [CDP] Updating setfocus for each page
  src/applications/combined-debt-portal/combined/containers/OverviewPage.jsx
  src/applications/combined-debt-portal/combined/utils/helpers.js
  src/applications/combined-debt-portal/debt-letters/containers/DebtDetails.jsx
  src/applications/combined-debt-portal/debt-letters/containers/DebtLettersDownload.jsx
  src/applications/combined-debt-portal/debt-letters/containers/DebtLettersSummary.jsx
  src/applications/combined-debt-portal/debt-letters/utils/page.js
  src/applications/combined-debt-portal/medical-copays/containers/DetailPage.jsx
  src/applications/combined-debt-portal/medical-copays/containers/HTMLStatementPage.jsx
  src/applications/combined-debt-portal/medical-copays/containers/OverviewPage.jsx
Labels: front end, vsa-benefits-2

#21629 [CDP] MCP Fixing download statement focus highlighting when selected
  src/applications/combined-debt-portal/medical-copays/components/DownloadStatement.jsx
Labels: front end, vsa-benefits-2

#21590 [CDP] New URL update
  src/applications/combined-debt-portal/combined/components/OtherVADebts.jsx
  src/applications/combined-debt-portal/combined/containers/CombinedPortalApp.jsx
  src/applications/combined-debt-portal/combined/containers/OverviewPage.jsx
  src/applications/combined-debt-portal/combined/manifest.json
  src/applications/combined-debt-portal/combined/tests/e2e/combined-debt-portal.cypress.spec.js
  src/applications/combined-debt-portal/debt-letters/containers/DebtDetails.jsx
  src/applications/combined-debt-portal/debt-letters/containers/DebtLettersDownload.jsx
  src/applications/combined-debt-portal/debt-letters/containers/DebtLettersSummary.jsx
  src/applications/combined-debt-portal/debt-letters/tests/e2e/debt-alerts.cypress.spec.js
  src/applications/combined-debt-portal/debt-letters/tests/e2e/debt-letters.cypress.spec.js
  src/applications/combined-debt-portal/debt-letters/tests/e2e/details-card-content.cypress.spec.js
  src/applications/combined-debt-portal/debt-letters/tests/e2e/summary-card-content.cypress.spec.js
  src/applications/combined-debt-portal/medical-copays/containers/DetailPage.jsx
  src/applications/combined-debt-portal/medical-copays/containers/HTMLStatementPage.jsx
  src/applications/combined-debt-portal/medical-copays/containers/OverviewPage.jsx
  src/applications/combined-debt-portal/medical-copays/tests/e2e/cdp-alert.cypress.spec.js
  src/applications/combined-debt-portal/medical-copays/tests/e2e/mcp.cypress.spec.js
  src/applications/combined-debt-portal/medical-copays/tests/e2e/statements.cypress.spec.js
  src/applications/static-pages/cta-widget/ctaWidgets.js
Labels: front end, vsa-benefits-2

#21640 Supplemental Claims | Add contact information pages
  src/applications/appeals/995/components/ContactInformation.jsx
  src/applications/appeals/995/components/EditContactInfo.jsx
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/containers/App.jsx
  src/applications/appeals/995/content/GetFormHelp.jsx
  src/applications/appeals/995/content/contestableIssues.jsx
  src/applications/appeals/995/pages/contactInfo.js
  src/applications/appeals/995/pages/contactInformation.js
  src/applications/appeals/995/reducers/index.js
  src/applications/appeals/995/sass/995-supplemental-claim.scss
  src/applications/appeals/995/tests/pages/contactInformation.unit.spec.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#21648 [CDP] Adding colon to end of sentence before list
  src/applications/combined-debt-portal/combined/components/ComboAlerts.jsx
  src/applications/combined-debt-portal/combined/utils/alert-messages.jsx
Labels: front end, vsa-benefits-2

#21646 Supplemental Claims | Add Veteran Information page
  src/applications/appeals/995/components/VeteranInformation.jsx
  src/applications/appeals/995/pages/veteranInfo.js
  src/applications/appeals/995/tests/components/VeteranInformation.unit.spec.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#21678 ArrayField component - Ensures that focus is set on “Add another xyz” button once “xyz” is removed
  src/platform/forms-system/src/js/fields/ArrayField.jsx
Labels: 508/Accessibility

#21677 Ensure that the FieldTemplate text description appears first
  src/platform/forms-system/src/js/components/FieldTemplate.jsx
Labels: 508/Accessibility

#21685 43976 - CDP - [Other - Accessibility] Almost-match between visible text and screen reader only text. (00.00.2)
  src/applications/combined-debt-portal/medical-copays/components/HTMLStatementLink.jsx
Labels: front end, vsa-benefits-2

#21694 [CDP] Updated content page cta widget
  src/applications/static-pages/cta-widget/ctaWidgets.js
Labels: front end, vsa-benefits-2

#21699 Ensure error message associated with the ReviewCollapsibleChapter component's accordion button is described by the button's text
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
Labels: 508/Accessibility

#21695 43977 - [CDP] - [Other - Accessibility] Recommend review for redundant ARIA.
  src/applications/combined-debt-portal/combined/components/BalanceCard.jsx
Labels: front end, vsa-benefits-2

#21692 [CDP] 44004 - Fixing Margin issues
  src/applications/combined-debt-portal/combined/containers/CombinedPortalApp.jsx
Labels: front end, vsa-benefits-2

#21504 FieldTemplate error accessibility improvements
  src/platform/forms-system/src/js/components/FieldTemplate.jsx
Labels: 508/Accessibility

#21713 `ReviewCollapsibleChapter` component edit button accessibility improvements
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
Labels: 508/Accessibility

#21732 [CDP] 44003 - Updated breadcrumbs across app for accuracy consistency
  src/applications/combined-debt-portal/combined/containers/OverviewPage.jsx
  src/applications/combined-debt-portal/debt-letters/containers/DebtDetails.jsx
  src/applications/combined-debt-portal/debt-letters/containers/DebtLettersDownload.jsx
  src/applications/combined-debt-portal/debt-letters/containers/DebtLettersSummary.jsx
  src/applications/combined-debt-portal/medical-copays/containers/DetailPage.jsx
  src/applications/combined-debt-portal/medical-copays/containers/HTMLStatementPage.jsx
  src/applications/combined-debt-portal/medical-copays/containers/OverviewPage.jsx
Labels: front end, vsa-benefits-2

#21731 [CDP] 43978 Updating icon styling for consistency
  src/applications/combined-debt-portal/combined/sass/combined-debt-portal.scss
  src/applications/combined-debt-portal/debt-letters/const/diary-codes/debtSummaryCardContent.js
  src/applications/combined-debt-portal/medical-copays/components/BalanceCard.jsx
  src/applications/combined-debt-portal/medical-copays/sass/medical-copays.scss
Labels: front end, vsa-benefits-2

#21740 [CDP] 43979 - Fixing debt letter table formatting
  src/applications/combined-debt-portal/debt-letters/const/diary-codes/index.js
Labels: front end, vsa-benefits-2

#21736 Ensure that the item name in the ArrayField heading does not render `undefined`
  src/platform/forms-system/src/js/review/ArrayField.jsx
Labels: bug, 508/Accessibility

#21766 42013 - [CDP] - Debt letter download page updates due to VBMS endpoint being back up
  src/applications/combined-debt-portal/debt-letters/components/Alerts.jsx
Labels: front end, vsa-benefits-2

#21768 [cFSR] Adding feature toggle for Combined FSR experience
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: front end, vsa-benefits-2

#21697 VAMC-9797: Update crisis line phone number.
  src/applications/check-in/pre-check-in/pages/Introduction/IntroductionDisplay.jsx
  src/applications/health-care-questionnaire/shared/components/footer/NeedHelpSmall.jsx
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.js
  src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/UnauthContent/index.js
  src/applications/vaos/new-appointment/components/DateTimeSelectPage/WaitTimeAlert.jsx
  src/applications/vaos/new-appointment/components/ReasonForAppointmentPage.jsx
  src/applications/virtual-agent/components/page/Disclaimer.jsx
  src/platform/site-wide/tests/accessible-modal.cypress.spec.js
  src/platform/site-wide/va-footer/components/CrisisPanel.jsx
Labels: ⭐️ Public Websites

#21769 Supplemental Claims | Add evidence pages
  src/applications/appeals/995/components/LocationField.jsx
  src/applications/appeals/995/components/PrivateProviderTreatmentView.jsx
  src/applications/appeals/995/config/form-4142-schema.json
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/content/evidencePrivateChoice.jsx
  src/applications/appeals/995/content/evidencePrivateRecords.jsx
  src/applications/appeals/995/content/evidencePrivateUpload.jsx
  src/applications/appeals/995/content/evidenceTypes.jsx
  src/applications/appeals/995/content/evidenceVaRecords.jsx
  src/applications/appeals/995/pages/evidencePrivateAdd.js
  src/applications/appeals/995/pages/evidencePrivateChoice.js
  src/applications/appeals/995/pages/evidencePrivateRecords.js
  src/applications/appeals/995/pages/evidencePrivateUpload.js
  src/applications/appeals/995/pages/evidenceTypes.js
  src/applications/appeals/995/pages/evidenceVaRecords.js
  src/applications/appeals/995/sass/995-supplemental-claim.scss
  src/applications/appeals/995/utils/dates.js
  src/applications/appeals/995/utils/helpers.js
  src/applications/appeals/995/utils/upload.js
  src/applications/appeals/995/validations/date.js
  src/applications/appeals/995/validations/evidence.js
Labels: front end, squad-2, Supplemental Claims

#21800 Supplemental Claims | Add supporting evidence upload & summary pages
  src/applications/appeals/995/components/LocationField.jsx
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/content/evidenceSummary.jsx
  src/applications/appeals/995/content/evidenceUpload.jsx
  src/applications/appeals/995/pages/evidencePrivateUpload.js
  src/applications/appeals/995/pages/evidenceSummary.js
  src/applications/appeals/995/pages/evidenceUpload.js
  src/applications/appeals/995/tests/fixtures/data/test-data.json
  src/applications/appeals/995/utils/helpers.js
  src/applications/appeals/995/utils/upload.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims
