Repository department-of-veterans-affairs/vets-website, pull requests merged in 2022-01, with the labels that each got.

#19783 Ensure startsAt and endsAt uses timezone
  src/applications/static-pages/events/components/Results/index.js
Labels: front end, VSA

#19723 Add chaining to mailingAddress checks
  src/applications/disability-benefits/all-claims/pages/contactInformation.js
Labels: front end, vsa-claims-appeals, VSA, 526

#19789 Modify events apply filters styling
  src/applications/static-pages/events/components/Events/index.js
  src/applications/static-pages/events/components/Search/index.js
  src/platform/site-wide/sass/shame.scss
Labels: front end, VSA

#19680 33472: Logic Strings Const-afied | Login Component Split Up
  src/applications/auth/containers/AuthApp.jsx
  src/applications/burials/tests/e2e/fixtures/mocks/mockUser.js
  src/applications/edu-benefits/1995/tests/e2e/fixtures/mocks/mockUser.js
  src/applications/hca/tests/fixtures/mocks/mockUser.js
  src/applications/health-care-questionnaire/questionnaire/tests/e2e/fixtures/users/user-basic.js
  src/applications/health-care-questionnaire/shared/api/local-mock-api/feature-flip-error.js
  src/applications/health-care-questionnaire/shared/api/local-mock-api/index.js
  src/applications/login/components/VerifyPage.jsx
  src/applications/login/containers/SignInApp.jsx
  src/applications/pensions/tests/fixtures/mocks/mockUser.js
  src/applications/personalization/common/helpers.js
  src/applications/personalization/profile/components/Profile.jsx
  src/applications/personalization/profile/components/account-security/TwoFactorAuthorizationStatus.jsx
  src/applications/personalization/profile/components/contact-information/email-addresses/EmailAddressNotification.jsx
  src/applications/personalization/profile/components/contact-information/email-addresses/EmailInformationSection.jsx
  src/applications/personalization/profile/components/direct-deposit/DirectDeposit.jsx
  src/applications/personalization/profile/tests/components/Profile.unit.spec.js
  src/applications/personalization/profile/tests/components/alerts/Profile.data-unavailable-error.unit.spec.js
  src/applications/personalization/profile/tests/e2e/address-validation/user.js
  src/applications/personalization/profile/tests/e2e/direct-deposit/gating.cypress.spec.js
  src/applications/personalization/profile/tests/e2e/direct-deposit/unsupported-signin-provider.cypress.spec.js
  src/applications/personalization/profile/tests/fixtures/users/user-vap-error.js
  src/applications/personalization/profile/tests/fixtures/users/user.js
  src/applications/static-pages/cta-widget/components/messages/mvi/NotAuthorized.jsx
  src/applications/static-pages/cta-widget/index.js
  src/platform/forms/tests/fixtures/mocks/mockUser.js
  src/platform/site-wide/user-nav/components/PersonalizationDropdown.jsx
  src/platform/testing/e2e/cypress/support/commands/login.js
  src/platform/testing/local-dev-mock-api/common.js
  src/platform/user/authentication/components/CreateAccountLink.jsx
  src/platform/user/authentication/components/LoginButton.jsx
  src/platform/user/authentication/components/LoginButtons.jsx
  src/platform/user/authentication/components/LoginContainer.jsx
  src/platform/user/authentication/components/SessionTimeoutModal.jsx
  src/platform/user/authentication/components/SignInModal.jsx
  src/platform/user/authentication/constants.js
  src/platform/user/authentication/utilities.js
  src/platform/user/tests/authentication/components/loginButtons.unit.spec.js
  src/platform/user/tests/authentication/utilities.unit.spec.js
  src/platform/user/tests/profile/utilities/index.unit.spec.js
  src/platform/utilities/sso/constants.js
  src/platform/utilities/sso/index.js
  src/platform/utilities/sso/keepAliveSSO.js
  src/platform/utilities/tests/sso.unit.spec.js
Labels: Identity

#19790 HLR: prevent duplicate API calls
  src/applications/disability-benefits/996/containers/Form0996App.jsx
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/tests/containers/FormApp.unit.spec.jsx
Labels: front end, vsa-claims-appeals, VSA, HLR

#19794 Tsimmz 33084 update typeahead 2 cypress tests
  src/applications/search/tests/e2e/01-required.cypress.spec.js
  src/applications/search/tests/page-object/searchComponent.js
Labels: front end, VSA

#19808 HLR: Replace `AdditionalInfo` with web component
  src/applications/disability-benefits/996/content/contestableIssues.jsx
  src/applications/disability-benefits/996/content/contestedIssues.jsx
Labels: front end, vsa-claims-appeals, VSA, HLR, Tech Debt

#19813 526: Replace `AdditionalInfo` with web component
  src/applications/disability-benefits/all-claims/containers/FormSavedPage.jsx
  src/applications/disability-benefits/all-claims/content/evidenceTypes.jsx
  src/applications/disability-benefits/all-claims/content/evidenceTypesBDD.jsx
  src/applications/disability-benefits/all-claims/content/incidentDate.jsx
  src/applications/disability-benefits/all-claims/content/incomeDetails.jsx
  src/applications/disability-benefits/all-claims/content/itfWrapper.jsx
  src/applications/disability-benefits/all-claims/content/newDisabilityFollowUp.jsx
  src/applications/disability-benefits/all-claims/content/privateMedicalRecords.jsx
  src/applications/disability-benefits/all-claims/content/privateMedicalRecordsRelease.jsx
  src/applications/disability-benefits/all-claims/content/ptsdTypeInfo.jsx
  src/applications/disability-benefits/all-claims/content/ptsdWalkthroughChoice.jsx
  src/applications/disability-benefits/all-claims/content/recentEarnedIncome.jsx
  src/applications/disability-benefits/all-claims/content/recentJobApplications.jsx
  src/applications/disability-benefits/all-claims/content/secondaryOtherSources.jsx
  src/applications/disability-benefits/all-claims/content/separationLocation.jsx
  src/applications/disability-benefits/all-claims/content/unemployabilityDates.jsx
  src/applications/disability-benefits/all-claims/content/unemployabilityDisabilities.jsx
  src/applications/disability-benefits/all-claims/pages/contactInformation.js
  src/applications/disability-benefits/all-claims/pages/supplementalBenefits.jsx
  src/applications/disability-benefits/all-claims/pages/terminallyIll.js
Labels: front end, vsa-claims-appeals, VSA, 526, Tech Debt

#19817 526: Replace `LoadingIndicator` with web component
  src/applications/disability-benefits/all-claims/Form526EZApp.jsx
  src/applications/disability-benefits/all-claims/containers/AddPerson.jsx
  src/applications/disability-benefits/all-claims/containers/ITFWrapper.jsx
  src/applications/disability-benefits/all-claims/content/confirmation-poll.jsx
  src/applications/disability-benefits/all-claims/tests/components/ConfirmationPoll.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/containers/Form526EZApp.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/containers/ITFWrapper.unit.spec.jsx
Labels: front end, vsa-claims-appeals, VSA, 526, Tech Debt

#19810 Update sorting logic
  src/applications/static-pages/events/helpers/index.js
  src/applications/static-pages/events/index.js
Labels: front end, VSA

#19824 Fix parseISODate for partial strings
  src/platform/forms-system/src/js/helpers.js
  src/platform/forms-system/test/js/helpers.unit.spec.js
Labels: front end, vsa-claims-appeals, VSA, HLR

#19827 Add edge case so that custom date range can select today with results
  src/applications/static-pages/events/helpers/index.js
Labels: front end, VSA

#19826 HLR v2: Require day & month in decision date
  src/applications/disability-benefits/996/validations/issues.js
Labels: front end, vsa-claims-appeals, VSA, HLR

#19830 HLR: Update content to match design
  src/applications/disability-benefits/996/content/addIssue.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
Labels: bug, front end, vsa-claims-appeals, VSA, HLR

#19833 HLR v2: Focus & scroll to alert when visible
  src/applications/disability-benefits/996/content/contestableIssues.jsx
Labels: 508/Accessibility, front end, vsa-claims-appeals, VSA, HLR

#19840 HLR v2: Update content in additional-info
  src/applications/disability-benefits/996/content/contestableIssues.jsx
Labels: front end, vsa-claims-appeals, VSA, HLR

#19841 HLR v2: Fix wizard invalid ID in `aria-describedby`
  src/applications/disability-benefits/996/wizard/pages/claimType.jsx
Labels: 508/Accessibility, front end, vsa-claims-appeals, VSA, HLR

#19836 HLR: Fix contact info header levels
  src/applications/disability-benefits/996/components/ContactInformation.jsx
Labels: 508/Accessibility, front end, vsa-claims-appeals, VSA, HLR

#19848 HLR: Edit contact link aria-labels
  src/applications/disability-benefits/996/components/ContactInformation.jsx
Labels: 508/Accessibility, front end, vsa-claims-appeals, VSA, HLR

#19849 update from form ID to formName
  src/applications/find-forms/components/FormTitle.jsx
  src/applications/find-forms/components/SearchResult.jsx
  src/applications/find-forms/tests/components/FormTitle.unit.spec.jsx
Labels: front end, VSA

#19852 Kelsonic 34958 error handling design
  src/applications/static-pages/events/components/Search/index.js
  src/platform/site-wide/sass/shame.scss
Labels: front end, VSA

#19853 HLR v2: Update content
  src/applications/appeals/10182/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/components/IssueCardV2.jsx
  src/applications/disability-benefits/996/containers/ConfirmationPage.jsx
  src/applications/disability-benefits/996/tests/utils/replace.unit.spec.js
  src/applications/disability-benefits/996/utils/replace.js
Labels: front end, vsa-claims-appeals, VSA, HLR, NOD

#19854 Add font weight bold to error messaging
  src/applications/static-pages/events/components/Search/index.js
Labels: front end, VSA

#19857 SiP: Remove period from link content
  src/platform/forms-system/src/js/constants.js
  src/platform/forms/tests/components/review/PreSubmitSection.unit.spec.jsx
Labels: content, front end, vsa-claims-appeals, VSA, HLR

#19869 Update valid form checking
  src/applications/find-forms/tests/widgets/createInvalidPdfAlert.unit.spec.js
  src/applications/find-forms/widgets/createFindVaFormsPDFDownloadHelper/index.js
Labels: front end, VSA

#19875 Update required labels from * to (Required)
  src/applications/static-pages/events/components/Search/index.js
Labels: front end, VSA

#19876 Update required label coloring
  src/applications/static-pages/events/components/Search/index.js
Labels: front end, VSA

#19877 526: Remove empty facilities before submission
  src/applications/disability-benefits/all-claims/tests/utils/submit.unit.spec.js
  src/applications/disability-benefits/all-claims/utils/submit.js
Labels: bug, front end, vsa-claims-appeals, VSA, 526

#19887 hlr update to va-loading-indicator
  src/applications/disability-benefits/996/containers/Form0996App.jsx
  src/applications/disability-benefits/996/containers/IntroductionPage.jsx
  src/applications/disability-benefits/996/tests/containers/FormApp.unit.spec.jsx
  src/applications/disability-benefits/996/tests/containers/IntroductionPage.unit.spec.jsx
Labels: front end, vsa-claims-appeals, VSA, HLR, Tech Debt

#19886 TSimmz 34156 Search UI consistency
  src/applications/resources-and-support/components/ResourcesAndSupportSearchApp.jsx
  src/applications/resources-and-support/components/SearchBar.jsx
  src/applications/resources-and-support/components/SearchResult.jsx
Labels: front end, VSA

#19896 526: Change schema to fix validation
  src/applications/disability-benefits/all-claims/pages/vaMedicalRecords.js
  src/applications/disability-benefits/all-claims/tests/pages/vaMedicalRecords.unit.spec.jsx
Labels: bug, front end, vsa-claims-appeals, VSA, 526

#19897 526: Prevent `ratedDisabilities` override in non-production
  src/applications/disability-benefits/all-claims/components/SelectArrayItemsWidget.jsx
  src/applications/disability-benefits/all-claims/tests/components/SelectArrayItemsWidget.unit.spec.jsx
Labels: front end, vsa-claims-appeals, VSA, 526

#19837 34430: Streamline/Cleanup Login Components
  src/applications/login/components/SignInWrapper.jsx
  src/applications/login/components/VerifyPage.jsx
  src/applications/login/containers/SignInApp.jsx
  src/platform/user/authentication/components/DowntimeBanner.js
  src/platform/user/authentication/components/LoginActions.jsx
  src/platform/user/authentication/components/LoginButton.jsx
  src/platform/user/authentication/components/LoginContainer.jsx
  src/platform/user/authentication/components/LoginHeader.jsx
  src/platform/user/authentication/components/LoginInfo.jsx
  src/platform/user/authentication/components/LogoutAlert.jsx
  src/platform/user/authentication/components/SignInModal.jsx
  src/platform/user/authentication/components/index.jsx
  src/platform/user/tests/authentication/components/loginActions.unit.spec.js
Labels: Identity

#19909 HLR v2: Conditionally show legacy opt-in page
  src/applications/disability-benefits/996/config/form.js
  src/applications/disability-benefits/996/constants.js
  src/applications/disability-benefits/996/containers/Form0996App.jsx
  src/applications/disability-benefits/996/reducers/contestableIssues.js
  src/applications/disability-benefits/996/tests/utils/helpers.unit.spec.js
  src/applications/disability-benefits/996/utils/helpers.js
Labels: front end, vsa-claims-appeals, VSA, HLR

#19910 fix search analytics tagging
  src/applications/search/containers/SearchApp.jsx
Labels: front end, VSA

#19873 Add timezone to SiP time
  src/applications/burials/tests/e2e/application-status.cypress.spec.js
  src/applications/burials/tests/e2e/fixtures/mocks/mockUser.js
  src/applications/edu-benefits/1995/tests/e2e/edu-1995-application-status.cypress.spec.js
  src/applications/edu-benefits/1995/tests/e2e/fixtures/mocks/mockUser.js
  src/applications/hca/tests/e2e/application-status.cypress.spec.js
  src/applications/hca/tests/e2e/fixtures/mockUser.js
  src/applications/pensions/tests/application-status.cypress.spec.js
  src/applications/pensions/tests/fixtures/mocks/mockUser.js
  src/platform/forms/save-in-progress/ApplicationStatus.jsx
  src/platform/forms/save-in-progress/FormSaved.jsx
  src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
  src/platform/forms/save-in-progress/SaveStatus.jsx
  src/platform/forms/tests/fixtures/mocks/mockUser.js
  src/platform/forms/tests/save-in-progress/01-sip-autosave.cypress.spec.js
  src/platform/forms/tests/save-in-progress/01-sip-finish-later.cypress.spec.js
  src/platform/forms/tests/save-in-progress/01-sip-load-fail.cypress.spec.js
  src/platform/forms/tests/save-in-progress/01-sip-review.cypress.spec.js
  src/platform/forms/tests/save-in-progress/ApplicationStatus.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/FormSaved.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/SaveInProgressIntro.unit.spec.jsx
  src/platform/forms/tests/save-in-progress/SaveStatus.unit.spec.jsx
Labels: 508/Accessibility, content, front end, vsa-claims-appeals, VSA

#19948 letters update to va-loading-indicator
  src/applications/letters/containers/Main.jsx
  src/applications/letters/tests/containers/Main.unit.spec.jsx
Labels: front end, va-letters, vsa-claims-appeals, VSA, Tech Debt

#19965 replace old link with new one
  src/applications/disability-benefits/all-claims/content/common.jsx
  src/platform/site-wide/va-footer/components/CrisisPanel.jsx
Labels: front end, VSA

#19946 526: Bypass PTSD questions
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/content/ptsdBypassContent.jsx
  src/applications/disability-benefits/all-claims/pages/index.js
  src/applications/disability-benefits/all-claims/pages/ptsdBypassCombat.js
  src/applications/disability-benefits/all-claims/pages/ptsdBypassNonCombat.js
  src/applications/disability-benefits/all-claims/tests/all-claims.cypress.spec.js
  src/applications/disability-benefits/all-claims/tests/fixtures/data/full-781-781a-8940-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/minimal-skip-781.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/minimal-skip-781.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/upload-781-781a-8940-test.json
  src/applications/disability-benefits/all-claims/tests/pages/ptsdBypassCombat.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/ptsdBypassNonCombat.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/utils/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils/index.jsx
Labels: front end, vsa-claims-appeals, VSA, 526

#19966 HLR v2: Update add issue page content
  src/applications/disability-benefits/996/components/AddIssue.jsx
  src/applications/disability-benefits/996/content/addIssue.jsx
  src/applications/disability-benefits/996/sass/0996-higher-level-review.scss
  src/applications/disability-benefits/996/tests/components/AddIssue.unit.spec.js
  src/applications/disability-benefits/996/utils/helpers.js
  src/applications/disability-benefits/996/validations/issues.js
Labels: 508/Accessibility, content, front end, vsa-claims-appeals, VSA, HLR

#19989 526: Include non-active duty dates in treatment period checks
  src/applications/disability-benefits/all-claims/tests/validations.unit.spec.js
  src/applications/disability-benefits/all-claims/validations.js
Labels: bug, front end, vsa-claims-appeals, VSA, 526

#19996 34447: Adds a space between TTY and phone number
  src/platform/static-data/SubmitSignInForm.jsx
Labels: Identity

#19999 NOD: add contact info list loop
  src/applications/appeals/10182/components/ContactInformation.jsx
  src/applications/appeals/10182/components/EditContactInfo.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/tests/10182-contact-loop.cypress.spec.js
  src/applications/appeals/10182/tests/components/ContactInformation.unit.spec.jsx
  src/applications/appeals/10182/tests/fixtures/mocks/profile-status.json
  src/applications/appeals/10182/tests/fixtures/mocks/telephone-update-success.json
  src/applications/appeals/10182/tests/fixtures/mocks/telephone-update.json
  src/applications/appeals/10182/tests/fixtures/mocks/user.json
  src/applications/appeals/10182/tests/nod.cypress.helpers.js
  src/applications/appeals/10182/tests/pages/contactInfo.unit.spec.jsx
Labels: front end, vsa-claims-appeals, VSA, NOD

#20001 claims status tool update to va-loading-indicator
  src/applications/claims-status/components/ClaimDetailLayout.jsx
  src/applications/claims-status/containers/AdditionalEvidencePage.jsx
  src/applications/claims-status/containers/AppealInfo.jsx
  src/applications/claims-status/containers/AppealStatusPage.jsx
  src/applications/claims-status/containers/DocumentRequestPage.jsx
  src/applications/claims-status/containers/StemClaimStatusPage.jsx
  src/applications/claims-status/containers/YourClaimsPageV2.jsx
  src/applications/claims-status/tests/components/AdditionalEvidencePage.unit.spec.jsx
  src/applications/claims-status/tests/components/ClaimDetailLayout.unit.spec.jsx
  src/applications/claims-status/tests/components/DocumentRequestPage.unit.spec.jsx
  src/applications/claims-status/tests/components/YourClaimsPageV2.unit.spec.jsx
  src/applications/claims-status/tests/components/appeals-v2/AppealInfo.unit.spec.jsx
Labels: front end, claim status, vsa-claims-appeals, VSA, Tech Debt

#20009 minor style tweak
  src/applications/static-pages/events/components/Results/index.js
Labels: front end, VSA

#19967 32922: Adds ?next=loginModal functionality to open page with login modal opened by default
  src/applications/verify/containers/VerifyApp.jsx
  src/platform/site-wide/user-nav/containers/Main.jsx
  src/platform/site-wide/user-nav/tests/containers/Main.unit.spec.jsx
Labels: Identity

#20025 526: Add PTSD description when 781 bypassed
  src/applications/disability-benefits/all-claims/content/ptsdBypassContent.jsx
  src/applications/disability-benefits/all-claims/pages/ptsdBypassCombat.js
  src/applications/disability-benefits/all-claims/pages/ptsdBypassNonCombat.js
  src/applications/disability-benefits/all-claims/tests/fixtures/data/full-781-781a-8940-test.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/minimal-skip-781.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/transformed-data/minimal-skip-781.json
  src/applications/disability-benefits/all-claims/tests/fixtures/data/upload-781-781a-8940-test.json
  src/applications/disability-benefits/all-claims/tests/utils/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils/index.jsx
  src/applications/disability-benefits/all-claims/utils/submit.js
Labels: front end, vsa-claims-appeals, VSA, 526

#20040 NOD: switch to va-additional-info WC
  src/applications/appeals/10182/containers/IntroductionPage.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/content/evidenceIntro.jsx
Labels: front end, vsa-claims-appeals, VSA, NOD

#20047 NOD: show loading indicator
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
Labels: front end, vsa-claims-appeals, VSA, NOD

#20038 NOD: Use add item list loop
  src/applications/appeals/10182/components/AddIssue.jsx
  src/applications/appeals/10182/components/AddIssues.jsx
  src/applications/appeals/10182/components/AddIssuesField.jsx
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/components/EligibleIssuesWidget.jsx
  src/applications/appeals/10182/components/IssueCard.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/content/addIssue.jsx
  src/applications/appeals/10182/content/additionalIssues.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/content/issueSummary.js
  src/applications/appeals/10182/pages/addIssue.js
  src/applications/appeals/10182/pages/additionalIssues.js
  src/applications/appeals/10182/pages/additionalIssuesIntro.js
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/10182-notice-of-disagreement.cypress.spec.js
  src/applications/appeals/10182/tests/components/AddIssuesField.unit.spec.jsx
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/10182/tests/components/IssueCard.unit.spec.jsx
  src/applications/appeals/10182/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/10182/tests/fixtures/data/maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/minimal-test.json
  src/applications/appeals/10182/tests/pages/additionalIssues.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/additionalIssuesIntro.unit.spec.js
  src/applications/appeals/10182/tests/pages/contestableIssues.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/issueSummary.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/dates.unit.spec.js
  src/applications/appeals/10182/tests/utils/helpers.unit.spec.js
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/tests/validations.unit.spec.js
  src/applications/appeals/10182/tests/validations/date.unit.spec.js
  src/applications/appeals/10182/tests/validations/index.unit.spec.js
  src/applications/appeals/10182/tests/validations/issues.unit.spec.js
  src/applications/appeals/10182/utils/dates.js
  src/applications/appeals/10182/utils/helpers.js
  src/applications/appeals/10182/utils/replace.js
  src/applications/appeals/10182/utils/submit.js
  src/applications/appeals/10182/validations.js
  src/applications/appeals/10182/validations/date.js
  src/applications/appeals/10182/validations/index.js
  src/applications/appeals/10182/validations/issues.js
Labels: front end, vsa-claims-appeals, VSA, NOD

#20066 CST: Fix some linting issues
  src/applications/claims-status/actions/index.jsx
  src/applications/claims-status/components/AddFilesForm.jsx
  src/applications/claims-status/components/ClaimPhase.jsx
  src/applications/claims-status/components/MailMessage.jsx
  src/applications/claims-status/containers/AdditionalEvidencePage.jsx
  src/applications/claims-status/containers/DocumentRequestPage.jsx
  src/applications/claims-status/reducers/uploads.js
  src/applications/claims-status/sass/claims-status.scss
  src/applications/claims-status/tests/actions.unit.spec.js
  src/applications/claims-status/tests/components/AddFilesForm.unit.spec.jsx
  src/applications/claims-status/tests/e2e/page-objects/TrackClaimsPage.js
  src/applications/claims-status/tests/reducers/uploads.unit.spec.jsx
Labels: 508/Accessibility, front end, claim status, vsa-claims-appeals, VSA

#20082 NOD/HLR v2: Add next step instructions
  .eslintrc.js
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/disability-benefits/996/content/contestableIssues.jsx
  src/applications/disability-benefits/996/content/contestedIssues.jsx
Labels: front end, vsa-claims-appeals, VSA, HLR, NOD
