Repository department-of-veterans-affairs/vets-website, pull requests merged in 2023-06, with the labels that each got.

#24198 57110 Update phone number on alert
  src/applications/disability-benefits/all-claims/containers/MissingServices.jsx
Labels: disability-experience

#24414 Supplemental Claims | Fix confirmation page focus
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/containers/ConfirmationPage.jsx
  src/applications/appeals/995/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/appeals/995/tests/utils/focus.unit.spec.js
  src/applications/appeals/995/utils/focus.js
Labels: bug, 508/Accessibility, front end, benefits-team-1, squad-2, Supplemental Claims

#24424 Supplemental Claim | Fix confirmation page initial focus for Safari
  src/applications/appeals/995/containers/ConfirmationPage.jsx
Labels: bug, 508/Accessibility, front end, benefits-team-1, squad-2, Supplemental Claims

#24451 Notice of Disagreement | Add review errors
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/content/reviewErrors.js
Labels: bug, 508/Accessibility, front end, NOD, benefits-team-1, squad-2

#24315 56920 First pass of sync 526EZ online form with paper form
  src/applications/disability-benefits/all-claims/config/form.js
  src/applications/disability-benefits/all-claims/tests/pages/hospitalizationHistory.unit.spec.jsx
  src/applications/disability-benefits/all-claims/tests/pages/incomeDetails.unit.spec.jsx
Labels: disability-experience

#24467 Global | Fix review & submit page error style
  src/applications/financial-status-report/sass/financial-status-report.scss
  src/platform/forms-system/src/js/review/ArrayField.jsx
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
  src/platform/forms-system/test/js/review/ArrayField.unit.spec.jsx
  src/platform/forms-system/test/js/review/ReviewCollapsibleChapter.unit.spec.jsx
  src/platform/forms/sass/_m-schemaform.scss
Labels: bug, front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#24471 Notice of Disagreement | Show confirmation modal when removing an issue
  src/applications/appeals/10182/components/AddIssue.jsx
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/components/IssueCard.jsx
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/content/addIssue.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/10182-notice-of-disagreement.cypress.spec.js
  src/applications/appeals/10182/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/10182/tests/components/IssueCard.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/focus.unit.spec.js
  src/applications/appeals/10182/utils/focus.js
Labels: front end, NOD, benefits-team-1, squad-2

#24272 56514 conditional rendering cerner styling
  src/applications/login/containers/SignInApp.jsx
  src/platform/site-wide/mega-menu/components/MegaMenu.jsx
  src/platform/site-wide/user-nav/components/SearchHelpSignIn.jsx
Labels: Identity

#24523 Appeals | Fix date formatting
  src/applications/appeals/10182/components/AddIssue.jsx
  src/applications/appeals/10182/tests/utils/replace.unit.spec.js
  src/applications/appeals/10182/utils/replace.js
  src/applications/appeals/995/components/AddIssue.jsx
  src/applications/appeals/995/tests/utils/replace.unit.spec.js
  src/applications/appeals/995/utils/replace.js
  src/applications/appeals/996/components/AddIssue.jsx
  src/applications/appeals/996/tests/utils/replace.unit.spec.js
  src/applications/appeals/996/utils/replace.js
Labels: bug, front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#24528 Notice of Disagreement | Prevent JS error with undefined disagreement options
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/utils/submit.js
Labels: bug, front end, NOD, benefits-team-1, squad-2

#24538 Appeals | Prevent JS error with undefined addError function
  src/applications/appeals/10182/tests/validations/index.unit.spec.js
  src/applications/appeals/10182/validations/index.js
  src/applications/appeals/995/tests/validations/validations.unit.spec.js
  src/applications/appeals/995/validations/index.js
  src/applications/appeals/996/tests/validations/validations.unit.spec.js
  src/applications/appeals/996/validations/index.js
Labels: bug, front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#24565 Platform | Fix prop types
  src/platform/forms-system/src/js/components/ReviewCardField.jsx
  src/platform/forms-system/src/js/containers/FormPage.jsx
  src/platform/forms/save-in-progress/FormSaved.jsx
  src/platform/forms/save-in-progress/RoutedSavablePage.jsx
  src/platform/forms/save-in-progress/RoutedSavableReviewPage.jsx
Labels: bug, front end, 526, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#24553 Prevent JS error when page object is undefined
  src/platform/forms-system/src/js/components/FormNav.jsx
  src/platform/forms-system/test/js/components/FormNav.unit.spec.jsx
Labels: bug, front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#24573 Save-in-progress | Validate returnUrl metadata
  src/platform/forms/save-in-progress/FormStartControls.jsx
  src/platform/forms/save-in-progress/RoutedSavableApp.jsx
  src/platform/forms/tests/save-in-progress/RoutedSavableApp.unit.spec.jsx
Labels: bug, front end, platform, 526

#24586 59319 unorder lists
  src/applications/check-in/components/AppointmentBlock.jsx
  src/applications/check-in/day-of/pages/Confirmation/CheckInConfirmation.jsx
  src/applications/check-in/pre-check-in/tests/e2e/pages/Introduction.js
  src/applications/check-in/sass/check-in.scss
Labels: 508/Accessibility

#24584 Notice of Disagreement | Add Google Analytics to radios
  src/applications/appeals/10182/pages/boardReview.js
  src/applications/appeals/10182/pages/evidenceIntro.js
  src/applications/appeals/10182/pages/hearingType.js
  src/applications/appeals/10182/pages/homeless.js
  src/platform/forms-system/src/js/widgets/RadioWidget.jsx
  src/platform/forms-system/src/js/widgets/YesNoWidget.jsx
  src/platform/forms-system/test/js/widgets/RadioWidget.unit.spec.jsx
  src/platform/forms-system/test/js/widgets/YesNoWidget.unit.spec.jsx
Labels: front end, platform, NOD, analytics, benefits-team-1, squad-2

#24607 HLR & SC | Set up radio button tracking
  src/applications/appeals/995/components/EvidencePrivateRecordsRequest.jsx
  src/applications/appeals/995/components/PrimaryPhone.jsx
  src/applications/appeals/995/content/evidenceWillUpload.jsx
  src/applications/appeals/995/pages/evidencePrivateRequest.js
  src/applications/appeals/995/pages/evidenceVaRecordsRequest.js
  src/applications/appeals/995/pages/evidenceWillUpload.js
  src/applications/appeals/995/tests/components/EvidencePrivateRecordsRequest.unit.spec.jsx
  src/applications/appeals/995/tests/components/PrimaryPhone.unit.spec.jsx
  src/applications/appeals/995/tests/pages/evidenceVaRecordsRequest.unit.spec.jsx
  src/applications/appeals/995/tests/pages/evidenceWillUpload.unit.spec.jsx
  src/applications/appeals/996/content/InformalConference.jsx
  src/applications/appeals/996/pages/homeless.js
  src/applications/appeals/996/pages/informalConference.js
  src/applications/appeals/996/pages/informalConferenceTimeV2.js
  src/applications/appeals/996/tests/pages/InformalConference.unit.spec.jsx
  src/applications/appeals/996/tests/pages/homeless.unit.spec.js
  src/applications/appeals/996/tests/pages/informalConferenceTimeV2.unit.spec.js
Labels: front end, platform, HLR, analytics, benefits-team-1, squad-2, Supplemental Claims

#24619 HLR | Fix conference time label in GA
  src/applications/appeals/996/config/form.js
  src/applications/appeals/996/content/InformalConference.jsx
  src/applications/appeals/996/pages/informalConference.js
  src/applications/appeals/996/pages/informalConferenceRep.js
  src/applications/appeals/996/pages/informalConferenceTime.js
  src/applications/appeals/996/pages/informalConferenceTimeRep.js
  src/applications/appeals/996/sass/0996-higher-level-review.scss
  src/applications/appeals/996/tests/pages/informalConferenceRep.unit.spec.js
  src/applications/appeals/996/tests/pages/informalConferenceTime.unit.spec.js
  src/applications/appeals/996/tests/pages/informalConferenceTimeRep.unit.spec.js
Labels: front end, HLR, analytics, benefits-team-1, squad-2

#24623 HLR | Remove buggy code
  src/applications/appeals/996/containers/IntroductionPage.jsx
Labels: bug, front end, HLR, benefits-team-1, squad-2

#24591 Removed aria-live on nav section (all back to last screen)
  src/applications/check-in/components/BackButton.jsx
Labels: 508/Accessibility

#24640 Appeals | Add NOD & SC to my-va
  src/applications/personalization/dashboard/helpers.jsx
Labels: front end, NOD, benefits-team-1, squad-2, Supplemental Claims

#24671 Add CustomPage noop navigation functions on review & submit
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
  src/platform/forms-system/test/js/review/ReviewCollapsibleChapter.unit.spec.jsx
Labels: bug, front end, benefits-team-1, squad-2, Supplemental Claims

#24675 NOD | Add & focus on unique H3
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/components/VeteranInformation.jsx
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/containers/ConfirmationPage.jsx
  src/applications/appeals/10182/containers/IntroductionPage.jsx
  src/applications/appeals/10182/content/EvidenceUpload.jsx
  src/applications/appeals/10182/content/FilingDeadlines.jsx
  src/applications/appeals/10182/content/GetFormHelp.jsx
  src/applications/appeals/10182/content/addIssue.jsx
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
  src/applications/appeals/10182/content/boardReview.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/content/evidenceIntro.jsx
  src/applications/appeals/10182/content/hearingType.js
  src/applications/appeals/10182/content/homeless.jsx
  src/applications/appeals/10182/content/issueSummary.js
  src/applications/appeals/10182/content/saveInProgress.js
  src/applications/appeals/10182/pages/boardReview.js
  src/applications/appeals/10182/pages/contactInfo.js
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/pages/hearingType.js
  src/applications/appeals/10182/pages/homeless.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/validations/index.unit.spec.js
  src/applications/appeals/10182/utils/focus.js
  src/applications/appeals/10182/utils/ui.js
  src/applications/appeals/10182/utils/upload.js
  src/applications/appeals/10182/validations/index.js
Labels: 508/Accessibility, front end, NOD, benefits-team-1, squad-2

#24346 57342 - EFSR - Move Employment Dates to New Screens
  src/applications/financial-status-report/components/EmploymentHistorySummaryCard.jsx
  src/applications/financial-status-report/components/EmploymentWorkDates.jsx
  src/applications/financial-status-report/components/EnhancedEmploymentRecord.jsx
  src/applications/financial-status-report/components/EnhancedSpouseEmploymentRecord.jsx
  src/applications/financial-status-report/components/GrossMonthlyIncomeInput.jsx
  src/applications/financial-status-report/components/PayrollDeductionChecklist.jsx
  src/applications/financial-status-report/components/PayrollDeductionInputList.jsx
  src/applications/financial-status-report/components/SpouseAdditionalIncomeInputList.jsx
  src/applications/financial-status-report/components/SpouseEmploymentQuestion.jsx
  src/applications/financial-status-report/components/SpouseEmploymentWorkDates.jsx
  src/applications/financial-status-report/components/SpouseGrossMonthlyIncomeInput.jsx
  src/applications/financial-status-report/components/SpousePayrollDeductionChecklist.jsx
  src/applications/financial-status-report/components/SpousePayrollDeductionInputList.jsx
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/constants/index.js
  src/applications/financial-status-report/pages/income/employmentEnhanced/EmploymentHistoryWidget.jsx
  src/applications/financial-status-report/pages/income/employmentEnhanced/SpouseEmploymentHistoryWidget.jsx
  src/applications/financial-status-report/tests/e2e/fixtures/data/efsr-maximal.json
  src/applications/financial-status-report/tests/unit/efsr-transform.unit.spec.jsx
  src/applications/financial-status-report/tests/unit/efsr-unit-maximal.json
  src/applications/financial-status-report/utils/helpers.js
  src/applications/financial-status-report/utils/transform.js
Labels: front end, vsa-benefits-2

#24693 HLR | Add & focus on unique H3
  src/applications/appeals/996/components/VeteranInformation.jsx
  src/applications/appeals/996/config/form.js
  src/applications/appeals/996/containers/IntroductionPage.jsx
  src/applications/appeals/996/content/InformalConference.jsx
  src/applications/appeals/996/content/OptIn.jsx
  src/applications/appeals/996/content/addIssue.jsx
  src/applications/appeals/996/content/areaOfDisagreement.jsx
  src/applications/appeals/996/content/homeless.jsx
  src/applications/appeals/996/content/issueSummary.jsx
  src/applications/appeals/996/pages/homeless.js
  src/applications/appeals/996/sass/0996-higher-level-review.scss
  src/applications/appeals/996/tests/hlr-wizard.cypress.spec.js
  src/applications/appeals/996/tests/pages/areaOfDisagreement.unit.spec.jsx
  src/applications/appeals/996/tests/pages/homeless.unit.spec.js
  src/applications/appeals/996/utils/focus.js
  src/applications/appeals/996/wizard/WizardContainer.jsx
Labels: 508/Accessibility, front end, HLR, benefits-team-1, squad-2

#24701 [MHV-45980] Remove attachment modal - 59491
  src/applications/mhv/secure-messaging/components/AttachmentsList.jsx
  src/applications/mhv/secure-messaging/components/ComposeForm/ComposeForm.jsx
  src/applications/mhv/secure-messaging/components/ComposeForm/DraftSavedInfo.jsx
  src/applications/mhv/secure-messaging/components/Modals/RemoveAttachmentModal.jsx
  src/applications/mhv/secure-messaging/sass/secure-messaging.scss
  src/applications/mhv/secure-messaging/tests/components/Modals/RemoveAttachmentsModal.unit.spec.jsx
  src/applications/mhv/secure-messaging/tests/e2e/keyboard-nav-test/secure-messaging-compose-keyboard-nav-send.cypress.spec.js
  src/applications/mhv/secure-messaging/util/constants.js
Labels: 508/Accessibility
