Repository department-of-veterans-affairs/vets-website, pull requests merged in 2023-01, with the labels that each got.

#23042 51389 - EFSR - Remove Unused GA from end of Form
  src/applications/financial-status-report/containers/ConfirmationPage.jsx
Labels: front end, vsa-benefits-2

#23049 Supplemental Claims | Add contact info page inline on review & submit
  src/applications/appeals/995/components/ContactInfo.jsx
  src/applications/appeals/995/components/ContactInfoReview.jsx
  src/applications/appeals/995/components/ContactInformation.jsx
  src/applications/appeals/995/components/EditContactInfo.jsx
  src/applications/appeals/995/components/PrimaryPhone.jsx
  src/applications/appeals/995/components/PrimaryPhoneReview.jsx
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/content/contactInfo.jsx
  src/applications/appeals/995/content/primaryPhone.js
  src/applications/appeals/995/pages/contactInformation.js
  src/applications/appeals/995/sass/995-supplemental-claim.scss
  src/applications/appeals/995/tests/components/ContactInfo.unit.spec.jsx
  src/applications/appeals/995/tests/components/ContactInfoReview.unit.spec.jsx
  src/applications/appeals/995/tests/components/ContactInformation.unit.spec.jsx
  src/applications/appeals/995/tests/components/PrimaryPhone.unit.spec.jsx
  src/applications/appeals/995/tests/components/PrimaryPhoneReview.unit.spec.jsx
  src/applications/appeals/995/tests/pages/contactInfo.unit.spec.jsx
  src/applications/appeals/995/tests/pages/contactInformation.unit.spec.jsx
  src/applications/appeals/995/tests/utils/contactInfo.unit.spec.js
  src/applications/appeals/995/utils/contactInfo.js
  src/platform/forms-system/src/js/containers/FormPage.jsx
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23074 Supplemental Claims | Fix a11y issues on review & submit
  src/applications/appeals/995/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/components/EvidencePrivateLimitation.jsx
  src/applications/appeals/995/components/EvidencePrivateRecords.jsx
  src/applications/appeals/995/components/EvidencePrivateRecordsAuthorization.jsx
  src/applications/appeals/995/components/EvidencePrivateRecordsRequest.jsx
  src/applications/appeals/995/components/EvidenceSummary.jsx
  src/applications/appeals/995/components/EvidenceSummaryLists.jsx
  src/applications/appeals/995/components/EvidenceSummaryReview.jsx
  src/applications/appeals/995/components/EvidenceVaRecords.jsx
  src/applications/appeals/995/components/IssueCard.jsx
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/content/IssueSummary.jsx
  src/applications/appeals/995/content/contestableIssues.jsx
  src/applications/appeals/995/content/evidencePrivateLimitation.js
  src/applications/appeals/995/content/evidencePrivateRecordsRequest.jsx
  src/applications/appeals/995/content/evidenceSummaryLists.jsx
  src/applications/appeals/995/content/noticeOfAcknowledgement.jsx
  src/applications/appeals/995/pages/contestableIssues.js
  src/applications/appeals/995/pages/evidencePrivateRequest.js
  src/applications/appeals/995/pages/evidenceVaRecordsRequest.js
  src/applications/appeals/995/pages/evidenceWillUpload.js
  src/applications/appeals/995/pages/issueSummary.js
  src/applications/appeals/995/tests/995-contact-loop.cypress.spec.js
  src/applications/appeals/995/tests/995-supplemental-claim.cypress.spec.js
  src/applications/appeals/995/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidencePrivateRecordsRequest.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceSummary.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceSummaryLists.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceSummaryReview.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceVaRecords.unit.spec.jsx
  src/applications/appeals/995/tests/pages/evidenceWillUpload.unit.spec.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23082 Supplemental Claims | Show alert when missing DoB or SSN
  src/applications/appeals/995/components/MissingInfo.jsx
  src/applications/appeals/995/components/NeedsToVerify.jsx
  src/applications/appeals/995/containers/IntroductionPage.jsx
  src/applications/appeals/995/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/appeals/995/tests/fixtures/mocks/user.json
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23085 Supplemental Claims | Fix form submission
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/config/submit-transformer.js
  src/applications/appeals/995/config/submitForm.js
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/containers/App.jsx
  src/applications/appeals/995/pages/evidenceUpload.js
  src/applications/appeals/995/pages/primaryPhone.js
  src/applications/appeals/995/sass/995-supplemental-claim.scss
  src/applications/appeals/995/tests/995-supplemental-claim.cypress.spec.js
  src/applications/appeals/995/tests/config/submit-transformer.unit.spec.js
  src/applications/appeals/995/tests/config/submitForm.unit.spec.js
  src/applications/appeals/995/tests/fixtures/data/maximal-test.json
  src/applications/appeals/995/tests/fixtures/data/minimal-test.json
  src/applications/appeals/995/tests/fixtures/data/transformed-maximal-test.json
  src/applications/appeals/995/tests/utils/submit.unit.spec.js
  src/applications/appeals/995/tests/utils/upload.unit.spec.js
  src/applications/appeals/995/utils/submit.js
  src/applications/appeals/995/utils/upload.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23106 Supplemental Claims | Submission Confirmation Page
  src/applications/appeals/995/containers/ConfirmationPage.jsx
  src/applications/appeals/995/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/check-in/components/pages/AppointmentDetails/AppointmentDetails.unit.spec.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23087 Supplemental Claims - Update Content
  src/applications/appeals/995/content/evidenceUpload.jsx
  src/applications/appeals/995/pages/evidenceUpload.js
  src/applications/lgy/coe/form/config/chapters/documents/fileUpload.js
  src/platform/forms-system/src/js/definitions/file.js
Labels: front end, platform, benefits-team-1, Supplemental Claims

#23109 Supplemental Claims | Fix limited consent
  src/applications/appeals/995/components/EvidenceSummary.jsx
  src/applications/appeals/995/components/EvidenceSummaryReview.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23118 Supplemental Claim | Testing fixes
  src/applications/appeals/995/components/EvidencePrivateRecords.jsx
  src/applications/appeals/995/components/EvidenceVaRecords.jsx
  src/applications/appeals/995/containers/IntroductionPage.jsx
  src/applications/appeals/995/tests/995-contact-loop.cypress.spec.js
  src/applications/appeals/995/tests/995-supplemental-claim.cypress.spec.js
  src/applications/appeals/995/tests/fixtures/mocks/in-progress-forms.json
  src/applications/appeals/995/tests/fixtures/mocks/prefill.json
  src/applications/appeals/995/tests/routes.unit.spec.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23121 Supplemental Claims | Submission Confirmation Page - Buttons Text Fixes
  src/applications/appeals/995/containers/ConfirmationPage.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23123 Supplemental Claims | Hide bottom form start link when missing info
  src/applications/appeals/995/containers/IntroductionPage.jsx
  src/applications/appeals/995/tests/containers/IntroductionPage.unit.spec.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23136 Update focusElement behavior
  src/platform/forms-system/src/js/utilities/ui/index.js
  src/platform/forms-system/test/js/utilities/ui.unit.spec.js
  src/platform/utilities/ui/index.js
Labels: bug, 508/Accessibility, platform, benefits-team-1, squad-2

#23138 Supplemental Claims | Fix SubTask radio keyboard interaction
  src/applications/appeals/995/subtask/pages/start.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23144 526 | Hide PTSD questions in BDD flow
  src/applications/disability-benefits/all-claims/tests/utils/utils.unit.spec.jsx
  src/applications/disability-benefits/all-claims/utils/index.jsx
Labels: front end, BDD, 526, benefits-team-1, squad-2, Supplemental Claims

#23159 Supplemental Claims | Insert vs append evidence entries
  src/applications/appeals/995/components/EvidencePrivateRecords.jsx
  src/applications/appeals/995/components/EvidenceVaRecords.jsx
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceVaRecords.unit.spec.jsx
  src/applications/appeals/995/tests/validations/evidence.unit.spec.js
  src/applications/appeals/995/validations/evidence.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23170 Supplemental Claims | Add custom submission error
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/content/submissionError.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23167 48748 - [eFSR] Bankruptcy History Enhancements
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/pages/bankruptcy/enhancedRecords.js
  src/applications/financial-status-report/pages/index.js
  src/applications/financial-status-report/tests/e2e/efsr-5655.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/fixtures/data/efsr-maximal.json
Labels: front end, vsa-benefits-2

#23183 [eFSR-48747] Content start your request
  src/applications/financial-status-report/components/Alerts.jsx
  src/applications/financial-status-report/containers/App.jsx
Labels: vsa-benefits-2

#23218 Supplemental Claims | Support no evidence submissions
  src/applications/appeals/995/components/ContactInfoReview.jsx
  src/applications/appeals/995/components/EvidenceSummary.jsx
  src/applications/appeals/995/components/EvidenceSummaryReview.jsx
  src/applications/appeals/995/components/PrimaryPhoneReview.jsx
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/containers/IntroductionPage.jsx
  src/applications/appeals/995/content/evidenceSummary.jsx
  src/applications/appeals/995/content/noticeOfAcknowledgement.jsx
  src/applications/appeals/995/pages/noticeOfAcknowledgement.js
  src/applications/appeals/995/sass/995-supplemental-claim.scss
  src/applications/appeals/995/subtask/pages/start.jsx
  src/applications/appeals/995/tests/995-supplemental-claim.cypress.spec.js
  src/applications/appeals/995/tests/components/EvidenceSummary.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceSummaryReview.unit.spec.jsx
  src/applications/appeals/995/tests/config/submit-transformer.unit.spec.js
  src/applications/appeals/995/tests/fixtures/data/maximal-test.json
  src/applications/appeals/995/tests/fixtures/data/minimal-test.json
  src/applications/appeals/995/tests/fixtures/data/no-evidence-test.json
  src/applications/appeals/995/tests/fixtures/data/transformed-no-evidence-test.json
  src/applications/appeals/995/tests/validations/evidence.unit.spec.js
  src/applications/appeals/995/validations/evidence.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23206 Benefits | Replace React radio button component with web components
  src/applications/appeals/10182/components/AddIssue.jsx
  src/applications/appeals/995/components/AddIssue.jsx
  src/applications/appeals/995/components/EvidenceVaRecords.jsx
  src/applications/appeals/996/components/AddIssue.jsx
  src/applications/appeals/996/tests/hlr-keyboard-only.cypress.spec.js
  src/applications/appeals/996/tests/hlr-wizard.cypress.spec.js
  src/applications/appeals/996/tests/hlr.cypress.spec.js
  src/applications/appeals/996/tests/wizard/WizardContainer.unit.spec.jsx
  src/applications/appeals/996/wizard/pages/claimType.jsx
  src/applications/disability-benefits/all-claims/tests/all-claims-wizard.cypress.spec.js
  src/applications/disability-benefits/all-claims/tests/containers/WizardContainer.unit.spec.jsx
  src/applications/disability-benefits/wizard/pages/appeals.jsx
  src/applications/disability-benefits/wizard/pages/bdd.jsx
  src/applications/disability-benefits/wizard/pages/start.jsx
  src/applications/static-pages/wizard/tests/bdd-526.unit.spec.jsx
  src/applications/vre/28-1900/tests/e2e/chapter31-wizard.cypress.spec.js
  src/applications/vre/28-1900/wizard/pages/other/isOther.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/01-noHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/01-yesHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/02-noVaMemorandum.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/02-yesVaMemorandum.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-noIDES.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/03-yesIDES.jsx
  src/applications/vre/28-1900/wizard/pages/service-member/isServiceMember.jsx
  src/applications/vre/28-1900/wizard/pages/start.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/01-noHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/01-yesHonorableDischarge.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/02-noDisabilityRating.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/02-yesDisabilityRating.jsx
  src/applications/vre/28-1900/wizard/pages/veteran/isVeteran.jsx
  src/applications/vre/28-8832/tests/e2e/dependent-workflow.cypress.spec.js
  src/applications/vre/28-8832/tests/e2e/veteran-workflow-not-logged-in.cypress.spec.js
  src/applications/vre/28-8832/wizard/pages/ApplyLaterNotification.jsx
  src/applications/vre/28-8832/wizard/pages/BeginFormNow.jsx
  src/applications/vre/28-8832/wizard/pages/DischargeNotification.jsx
  src/applications/vre/28-8832/wizard/pages/DischargeStatus.jsx
  src/applications/vre/28-8832/wizard/pages/IneligibleNotice.jsx
  src/applications/vre/28-8832/wizard/pages/Start.jsx
  src/applications/vre/28-8832/wizard/pages/StartForm.jsx
  src/applications/vre/28-8832/wizard/pages/VREBenefits.jsx
  src/applications/vre/28-8832/wizard/pages/VRECounselorNotification.jsx
  src/applications/vre/28-8832/wizard/pages/VaEducationBenefits.jsx
Labels: front end, HLR, NOD, benefits-team-1, squad-2, VR&E

#23226 Supplemental Claims | remove evidenceSubmission with no evidence
  src/applications/appeals/995/tests/fixtures/data/transformed-no-evidence-test.json
  src/applications/appeals/995/tests/utils/submit.unit.spec.js
  src/applications/appeals/995/utils/submit.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#23246 Supplemental Claims | Fix OMB number
  src/applications/appeals/995/containers/IntroductionPage.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#22220 41632 - 526ez keyboard only e2e tests (ch. 1, non-BDD)
  src/applications/disability-benefits/all-claims/tests/all-claims-keyboard-only.cypress.spec.js
  src/platform/testing/e2e/cypress/support/commands/keyboardNavigation.js
Labels: Stale

#23249 Certificate of Eligibility | Move loan intent into history page
  src/applications/lgy/coe/form/config/chapters/loans/index.js
  src/applications/lgy/coe/form/config/chapters/loans/loanHistory.js
  src/applications/lgy/coe/form/config/chapters/loans/loanIntent.js
  src/applications/lgy/coe/form/config/form.js
  src/applications/lgy/coe/form/config/schemaImports.js
  src/applications/lgy/coe/form/constants.js
  src/applications/lgy/coe/form/tests/coe-keyboard-only.cypress.spec.js
  src/applications/lgy/coe/form/tests/coe.cypress.spec.js
  src/applications/lgy/coe/form/tests/config/loans/loanHistory.unit.spec.jsx
  src/applications/lgy/coe/form/tests/config/loans/loanIntent.unit.spec.jsx
  src/applications/lgy/coe/form/tests/fixtures/data/maximal-test.json
  src/applications/lgy/coe/form/tests/fixtures/data/transformed-maximal-test.json
  src/applications/lgy/coe/form/tests/fixtures/mocks/prefill.json
  src/applications/lgy/coe/shared/components/StatusAlert/statuses/Available.jsx
  src/applications/lgy/coe/shared/components/StatusAlert/statuses/Denied.jsx
  src/applications/lgy/coe/shared/components/StatusAlert/statuses/Eligible.jsx
  src/applications/lgy/coe/shared/components/StatusAlert/statuses/Ineligible.jsx
  src/applications/lgy/coe/shared/components/StatusAlert/statuses/Pending.jsx
Labels: front end, benefits-team-1, squad-2, COE

#23253 File uploads | update jpeg signatures
  src/platform/forms-system/src/js/utilities/file/checkTypeAndExtensionMatches.js
  src/platform/forms-system/test/js/utilities/file.unit.spec.js
Labels: front end, platform, benefits-team-1, squad-2, COE
