Repository department-of-veterans-affairs/vets-website, pull requests merged in 2023-10, with the labels that each got.

#25945 NOD | Prevent SiP overwrite of preloaded data
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/tests/10182-notice-of-disagreement.cypress.spec.js
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
Labels: bug, front end, NOD, squad-2, Supplemental Claims

#26017 DR | Move appeals issue card to shared folder
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/components/IssueCard.jsx
  src/applications/appeals/995/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/components/IssueCard.jsx
  src/applications/appeals/995/tests/components/IssueCard.unit.spec.jsx
  src/applications/appeals/995/tests/pages/contestableIssues.unit.spec.js
  src/applications/appeals/996/components/ContestableIssuesWidget.jsx
  src/applications/appeals/996/tests/components/IssueCard.unit.spec.jsx
  src/applications/appeals/shared/components/IssueCard.jsx
  src/applications/appeals/shared/tests/components/IssueCard.unit.spec.jsx
Labels: front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#26014 Fix undefined disagreementOptions error
  src/applications/appeals/shared/components/AreaOfDisagreement.jsx
  src/applications/appeals/shared/tests/components/AreaOfDisagreement.unit.spec.jsx
Labels: bug, front end, HLR, NOD, benefits-team-1, squad-2

#26027 HLR | Fix no loaded alert visibility
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/996/components/ContestableIssuesWidget.jsx
  src/applications/appeals/996/tests/components/ContestableIssuesWidget.unit.spec.jsx
Labels: bug, front end, HLR, squad-2

#26018 SC | Switch to use platform profile
  src/applications/appeals/995/components/ContactInfo.jsx
  src/applications/appeals/995/components/ContactInfoReview.jsx
  src/applications/appeals/995/components/EditContactInfo.jsx
  src/applications/appeals/995/config/form.js
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/containers/App.jsx
  src/applications/appeals/995/containers/IntroductionPage.jsx
  src/applications/appeals/995/content/contactInfo.jsx
  src/applications/appeals/995/pages/contactInformation.js
  src/applications/appeals/995/tests/995-contact-loop.cypress.spec.js
  src/applications/appeals/995/tests/components/ContactInfo.unit.spec.jsx
  src/applications/appeals/995/tests/components/ContactInfoReview.unit.spec.jsx
  src/applications/appeals/995/tests/containers/App.unit.spec.jsx
  src/applications/appeals/995/tests/pages/contactInfo.unit.spec.jsx
  src/applications/appeals/995/tests/utils/contactInfo.unit.spec.js
  src/applications/appeals/995/utils/contactInfo.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#26035 SC | Setup Datadog RUM dashboard
  src/applications/appeals/10182/components/VeteranInformation.jsx
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/995/components/EvidencePrivateRecords.jsx
  src/applications/appeals/995/components/EvidenceSummaryLists.jsx
  src/applications/appeals/995/components/EvidenceVaRecords.jsx
  src/applications/appeals/995/components/PrimaryPhoneReview.jsx
  src/applications/appeals/995/components/VeteranInformation.jsx
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/containers/App.jsx
  src/applications/appeals/995/containers/ConfirmationPage.jsx
  src/applications/appeals/995/content/IssueSummary.jsx
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceSummaryLists.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceVaRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/PrimaryPhoneReview.unit.spec.jsx
  src/applications/appeals/995/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/appeals/995/tests/content/IssueSummary.unit.spec.jsx
  src/applications/appeals/996/components/VeteranInformation.jsx
  src/applications/appeals/996/constants.js
  src/applications/appeals/996/containers/ConfirmationPage.jsx
  src/applications/appeals/996/containers/Form0996App.jsx
  src/applications/appeals/shared/utils/useBrowserMonitoring.js
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#26059 NOD prototype | Update breadcrumbs
  src/applications/appeals/testing/containers/IntroductionPage.jsx
Labels: front end, NOD, benefits-team-1, squad-2

#26043 64435 - [SW] - Staging Review - Components or patterns don't align with guidelines, contact information (63675) (Post Launch)
  src/applications/financial-status-report/components/contactInfo/EditContactInfo.jsx
  src/applications/personalization/profile/components/ProfileInformationEditView.jsx
Labels: front end, vsa-benefits-2

#26057 PR to refactor submit utils - Appeals
  src/applications/appeals/10182/components/AddIssue.jsx
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/config/submit-transformer.js
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/utils/submit.js
  src/applications/appeals/995/components/AddIssue.jsx
  src/applications/appeals/995/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/config/submit-transformer.js
  src/applications/appeals/995/tests/utils/helpers.unit.spec.js
  src/applications/appeals/995/tests/utils/submit.unit.spec.js
  src/applications/appeals/995/utils/helpers.js
  src/applications/appeals/995/utils/submit.js
  src/applications/appeals/996/components/AddIssue.jsx
  src/applications/appeals/996/components/ContestableIssuesWidget.jsx
  src/applications/appeals/996/config/submit-transformer.js
  src/applications/appeals/996/tests/utils/submit.unit.spec.js
  src/applications/appeals/996/utils/helpers.js
  src/applications/appeals/996/utils/submit.js
  src/applications/appeals/shared/tests/utils/issues.unit.spec.js
  src/applications/appeals/shared/utils/issues.js
  src/applications/appeals/shared/utils/submit.js
Labels: front end, Tech Debt, benefits-team-1, squad-2

#26133 NOD | v2 fixes
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/tests/10182-keyboard-only.cypress.spec.js
  src/applications/appeals/10182/tests/fixtures/mocks/vamc-ehr.json
Labels: bug, front end, NOD, benefits-team-1, squad-2

#26217 NOD | Redirect to v2 questions
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/content/extensionRequest.jsx
  src/applications/appeals/10182/migrations/02-redirect-to-v2-questions.js
  src/applications/appeals/10182/migrations/index.js
  src/applications/appeals/10182/pages/extensionRequest.js
  src/applications/appeals/10182/sass/10182-nod.scss
  src/applications/appeals/10182/tests/migrations/02-redirect-to-v2-questions.unit.spec.js
  src/applications/appeals/10182/tests/pages/extensionRequest.unit.spec.jsx
Labels: enhancement, front end, NOD, benefits-team-1, squad-2

#26160 SC | Add validation to profile address
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/content/reviewErrors.js
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/content/reviewErrors.js
  src/applications/appeals/995/pages/contactInformation.js
  src/applications/appeals/995/tests/validations/validations.unit.spec.js
  src/applications/appeals/995/validations/index.js
  src/applications/appeals/996/config/form.js
  src/applications/appeals/996/pages/contactInformation.js
  src/applications/appeals/shared/content/contactInfo.js
  src/applications/appeals/shared/content/reviewErrors.js
  src/applications/appeals/shared/tests/validatiions/contactInfo.unit.spec.js
  src/applications/appeals/shared/tests/validations/areaOfDisagreements.unit.spec.js
  src/applications/appeals/shared/tests/validations/contactInfo.unit.spec.js
  src/applications/appeals/shared/validations/contactInfo.js
  src/platform/forms-system/src/js/components/ContactInfo.jsx
  src/platform/forms-system/src/js/components/ContactInfoReview.jsx
  src/platform/forms-system/src/js/definitions/profileContactInfo.js
  src/platform/forms-system/src/js/helpers.js
  src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx
  src/platform/forms-system/src/js/utilities/data/profile.js
  src/platform/forms-system/src/js/utilities/validations/index.js
  src/platform/forms-system/test/js/components/ContactInfo.unit.spec.jsx
  src/platform/forms-system/test/js/components/ContactInfoReview.unit.spec.jsx
  src/platform/forms-system/test/js/definitions/profileContactInfo.unit.spec.jsx
  src/platform/forms-system/test/js/helpers.unit.spec.js
  src/platform/forms-system/test/js/review/ReviewCollapsibleChapter.unit.spec.jsx
  src/platform/forms-system/test/js/utilities/profile.unit.spec.js
  src/platform/forms-system/test/js/utilities/validations.unit.spec.js
Labels: bug, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#26235 NOD | Ensure API-loaded issues are in place
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
Labels: front end, NOD, benefits-team-1, squad-2

#26255 Supplemental Claim | Remove required address
  src/applications/appeals/995/pages/contactInformation.js
Labels: bug, front end, benefits-team-1, squad-2, Supplemental Claims

#26285 NOD | Redirect to new v2 questions
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/content/extensionRequest.jsx
  src/applications/appeals/10182/migrations/02-redirect-to-v2-questions.js
  src/applications/appeals/10182/migrations/index.js
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/10182/tests/migrations/02-redirect-to-v2-questions.unit.spec.js
  src/applications/appeals/10182/tests/pages/extensionRequest.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/redirect.unit.spec.js
  src/applications/appeals/10182/utils/redirect.js
Labels: enhancement, front end, NOD, benefits-team-1, squad-2

#26342 Update cypress real events
  src/platform/testing/package.json
  yarn.lock
Labels: dependencies, benefits-team-1, squad-2, Supplemental Claims

#26357 Fix appeals keyboard-only e2e tests
  src/applications/appeals/10182/tests/10182-keyboard-only.cypress.spec.js
  src/applications/appeals/996/tests/hlr-keyboard-only.cypress.spec.js
Labels: front end, testing, HLR, NOD, benefits-team-1, squad-2

#26367 DR | Cleanup & fix end-to-end tests
  src/applications/appeals/10182/tests/10182-contact-loop.cypress.spec.js
  src/applications/appeals/10182/tests/10182-keyboard-only.cypress.spec.js
  src/applications/appeals/10182/tests/10182-notice-of-disagreement.cypress.spec.js
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/10182/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/10182/tests/fixtures/mocks/user.json
  src/applications/appeals/10182/tests/nod.cypress.helpers.js
  src/applications/appeals/995/tests/995-contact-loop.cypress.spec.js
  src/applications/appeals/995/tests/995-subtask.cypress.spec.js
  src/applications/appeals/995/tests/995-supplemental-claim.cypress.spec.js
  src/applications/appeals/995/tests/995.cypress.helpers.js
  src/applications/appeals/995/tests/fixtures/mocks/profile-status.json
  src/applications/appeals/995/tests/fixtures/mocks/vapProfile.json
  src/applications/appeals/996/config/form.js
  src/applications/appeals/996/content/areaOfDisagreement.jsx
  src/applications/appeals/996/pages/areaOfDisagreement.js
  src/applications/appeals/996/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/996/tests/fixtures/mocks/contestable-issues.json
  src/applications/appeals/996/tests/fixtures/mocks/profile-status.json
  src/applications/appeals/996/tests/fixtures/mocks/telephone-update-success.json
  src/applications/appeals/996/tests/fixtures/mocks/telephone-update.json
  src/applications/appeals/996/tests/fixtures/mocks/user.json
  src/applications/appeals/996/tests/fixtures/mocks/vamc-ehr.json
  src/applications/appeals/996/tests/hlr-contact-loop.cypress.spec.js
  src/applications/appeals/996/tests/hlr-keyboard-only.cypress.spec.js
  src/applications/appeals/996/tests/hlr-wizard.cypress.spec.js
  src/applications/appeals/996/tests/hlr.cypress.helpers.js
  src/applications/appeals/996/tests/hlr.cypress.spec.js
  src/applications/appeals/996/tests/pages/areaOfDisagreement.unit.spec.jsx
  src/applications/appeals/996/tests/validations/issues.unit.spec.js
  src/applications/appeals/996/utils/ui.js
  src/applications/appeals/996/validations/issues.js
  src/applications/appeals/shared/tests/cypress.helpers.js
  src/applications/appeals/shared/tests/cypress.setup.js
  src/applications/appeals/shared/tests/fixtures/mocks/contestable-issues.json
  src/applications/appeals/shared/tests/fixtures/mocks/feature-toggles.json
  src/applications/appeals/shared/tests/fixtures/mocks/profile-address-validation.json
  src/applications/appeals/shared/tests/fixtures/mocks/profile-address.json
  src/applications/appeals/shared/tests/fixtures/mocks/profile-email.json
  src/applications/appeals/shared/tests/fixtures/mocks/profile-phone.json
  src/applications/appeals/shared/tests/fixtures/mocks/profile-status.json
  src/applications/appeals/shared/tests/fixtures/mocks/profile-telephone-update-success.json
  src/applications/appeals/shared/tests/fixtures/mocks/profile-telephone-update.json
  src/applications/appeals/shared/tests/fixtures/mocks/user-transition-availabilities.json
  src/applications/appeals/shared/tests/fixtures/mocks/user-update.json
  src/applications/appeals/shared/tests/fixtures/mocks/user.json
  src/applications/appeals/shared/tests/fixtures/mocks/vamc-ehr.json
  src/applications/appeals/shared/tests/fixtures/mocks/vapProfile.json
Labels: front end, testing, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#26441 HLR | Switch to use shared code
  src/applications/appeals/996/config/submit-transformer.js
  src/applications/appeals/996/tests/utils/submit.unit.spec.js
  src/applications/appeals/996/utils/submit.js
Labels: bug, front end, HLR, benefits-team-1, squad-2

#26433 Fix flaky unit test
  src/applications/appeals/995/tests/components/EvidenceVaRecords.unit.spec.jsx
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#26414 Extending travel pilot for 657GB
  src/applications/check-in/utils/pilotFeatures/index.js
Labels: DO NOT MERGE
