Repository department-of-veterans-affairs/vets-website, pull requests merged in 2023-11, with the labels that each got.

#26307 67089 MHV landing page shows no health data message
  src/applications/mhv/landing-page/components/CardLayout.jsx
  src/applications/mhv/landing-page/components/HubLinks.jsx
  src/applications/mhv/landing-page/components/LandingPage.jsx
  src/applications/mhv/landing-page/components/NavCard.jsx
  src/applications/mhv/landing-page/components/NoHealthAlert.jsx
  src/applications/mhv/landing-page/containers/App.jsx
  src/applications/mhv/landing-page/selectors/hasHealthData.js
  src/applications/mhv/landing-page/selectors/index.js
  src/applications/mhv/landing-page/selectors/isLandingPageEnabledForUser.js
  src/applications/mhv/landing-page/tests/containers/App.unit.spec.jsx
  src/applications/mhv/landing-page/tests/e2e/app-enabled/disabled.cypress.spec.js
  src/applications/mhv/landing-page/tests/e2e/app-enabled/enabled.cypress.spec.js
  src/applications/mhv/landing-page/tests/e2e/restrict-by-facilities-list/facilities.access.cypress.spec.js
  src/applications/mhv/landing-page/tests/e2e/restrict-by-facilities-list/facilities.content.cypress.spec.js
  src/applications/mhv/landing-page/tests/e2e/restrict-cerner-patients/cerner.patients.cypress.spec.js
  src/applications/mhv/landing-page/tests/selectors/hasHealthData.unit.spec.js
  src/applications/mhv/landing-page/tests/selectors/isLandingPageEnabledForUser.unit.spec.js
  src/applications/mhv/landing-page/utilities/data/index.js
Labels: my-health-CTO-HEALTH-TEAM

#26580 [CST] Migrating Breadcrumbs React component to va-breadcrumb web component
  src/applications/claims-status/components/ClaimsBreadcrumbs.jsx
  src/applications/claims-status/tests/e2e/page-objects/TrackClaimsPage.js
Labels: Claim Status Tool

#26494 PR to move Container shared code into shared files | DR
  src/applications/appeals/10182/containers/ConfirmationPage.jsx
  src/applications/appeals/995/containers/ConfirmationPage.jsx
  src/applications/appeals/996/containers/ConfirmationPage.jsx
  src/applications/appeals/shared/components/DateSubmitted.jsx
  src/applications/appeals/shared/components/IssuesSubmitted.jsx
  src/applications/appeals/shared/utils/issues.jsx
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims

#26426 DR | Show contact info missing or invalid on review & submit
  src/applications/_mock-form/config/form.js
  src/applications/appeals/995/pages/contactInformation.js
  src/platform/forms-system/src/js/components/ContactInfoReview.jsx
  src/platform/forms-system/src/js/definitions/profileAddress.js
  src/platform/forms-system/src/js/definitions/profileContactInfo.js
  src/platform/forms-system/src/js/utilities/data/profile.js
  src/platform/forms-system/test/js/components/ContactInfoReview.unit.spec.jsx
  src/platform/forms-system/test/js/definitions/profileContactInfo.unit.spec.jsx
  src/platform/forms-system/test/js/utilities/profile.unit.spec.js
  src/platform/forms/tests/validations.unit.spec.js
  src/platform/forms/validations.js
Labels: bug, front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#26654 [Rated Disabilities] Migrating fom react-router v3 -> v6
  src/applications/rated-disabilities/containers/App.jsx
  src/applications/rated-disabilities/rated-disabilities-entry.jsx
  src/applications/rated-disabilities/routes.jsx
  src/applications/rated-disabilities/tests/containers/App.unit.spec.jsx
Labels: Rated Disabilities

#26668 DR | Move contestable issues widget to shared folder
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/995/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/996/components/ContestableIssuesWidget.jsx
  src/applications/appeals/996/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/shared/actions/index.js
  src/applications/appeals/shared/components/ContestableIssues.jsx
  src/applications/appeals/shared/tests/components/ContestableIssues.unit.spec.jsx
Labels: front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#26683 [CST] Updating tab design
  src/applications/claims-status/components/ClaimDetailLayout.jsx
  src/applications/claims-status/components/TabItem.jsx
  src/applications/claims-status/components/TabNav.jsx
  src/applications/claims-status/components/appeals-v2/AppealsV2TabNav.jsx
  src/applications/claims-status/components/evss/ClaimDetailLayout.jsx
  src/applications/claims-status/containers/AppealInfo.jsx
  src/applications/claims-status/containers/ClaimStatusPage.jsx
  src/applications/claims-status/containers/DetailsPage.jsx
  src/applications/claims-status/containers/FilesPage.jsx
  src/applications/claims-status/containers/YourClaimsPageV2.jsx
  src/applications/claims-status/sass/claims-status.scss
  src/applications/claims-status/tests/components/TabItem.unit.spec.jsx
  src/applications/claims-status/tests/components/TabNav.unit.spec.jsx
  src/applications/claims-status/tests/components/appeals-v2/AppealsV2TabNav.unit.spec.jsx
  src/applications/claims-status/tests/e2e/07.appeal-status.cypress.spec.js
  src/applications/claims-status/tests/e2e/page-objects/TrackClaimsPage.js
Labels: Claim Status Tool

#26738 SC | Add BGS, MVI & appeals downtime services
  src/applications/appeals/10182/config/form.js
  src/applications/appeals/995/config/form.js
  src/applications/appeals/996/config/form.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#26745 [CST] Followup a11y fixes
  src/applications/claims-status/components/ClaimDetailLayout.jsx
  src/applications/claims-status/components/appeals-v2/AppealsV2TabNav.jsx
  src/applications/claims-status/containers/AppealsV2DetailPage.jsx
  src/applications/claims-status/containers/AppealsV2StatusPage.jsx
  src/applications/claims-status/containers/ClaimStatusPage.jsx
  src/applications/claims-status/containers/DetailsPage.jsx
  src/applications/claims-status/containers/FilesPage.jsx
  src/applications/claims-status/sass/claims-status.scss
  src/applications/claims-status/utils/page.js
Labels: Claim Status Tool

#26718 DR | Move Veteran Information component to shared
  src/applications/appeals/10182/components/VeteranInformation.jsx
  src/applications/appeals/10182/pages/veteranInfo.js
  src/applications/appeals/10182/tests/components/VeteranInformation.unit.spec.jsx
  src/applications/appeals/995/components/VeteranInformation.jsx
  src/applications/appeals/995/pages/veteranInfo.js
  src/applications/appeals/995/tests/components/VeteranInformation.unit.spec.jsx
  src/applications/appeals/996/pages/veteranInformation.js
  src/applications/appeals/996/tests/components/veteranInformation.unit.spec.jsx
  src/applications/appeals/shared/components/VeteranInformation.jsx
  src/applications/appeals/shared/tests/components/VeteranInformation.unit.spec.jsx
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims

#26769 [CST] Adding Downtime Notifications to the app
  src/applications/claims-status/containers/ClaimsStatusApp.jsx
  src/applications/claims-status/sass/claims-status.scss
Labels: Claim Status Tool

#26758 DR | Moving some utilities to shared
  src/applications/appeals/10182/components/AddIssue.jsx
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/components/AddIssue.jsx
  src/applications/appeals/995/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/tests/validations/validations.unit.spec.js
  src/applications/appeals/995/validations/index.js
  src/applications/appeals/996/components/AddIssue.jsx
  src/applications/appeals/996/components/ContestableIssuesWidget.jsx
  src/applications/appeals/996/tests/validations/validations.unit.spec.js
  src/applications/appeals/996/validations/index.js
  src/applications/appeals/shared/utils/addIssue.js
  src/applications/appeals/shared/validations/index.js
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims

#26761 DR | Moving some utilities to shared part 2
  src/applications/appeals/10182/components/AddIssue.jsx
  src/applications/appeals/10182/content/addIssue.jsx
  src/applications/appeals/10182/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/10182/tests/validations/issues.unit.spec.js
  src/applications/appeals/10182/validations/issues.js
  src/applications/appeals/995/components/AddIssue.jsx
  src/applications/appeals/995/components/EvidencePrivateRecords.jsx
  src/applications/appeals/995/components/EvidenceVaRecords.jsx
  src/applications/appeals/995/components/PrimaryPhone.jsx
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/995/tests/validations/issues.unit.spec.js
  src/applications/appeals/995/tests/validations/validations.unit.spec.js
  src/applications/appeals/995/validations/index.js
  src/applications/appeals/995/validations/issues.js
  src/applications/appeals/996/components/AddIssue.jsx
  src/applications/appeals/996/content/addIssue.jsx
  src/applications/appeals/996/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/996/tests/validations/issues.unit.spec.js
  src/applications/appeals/996/validations/issues.js
  src/applications/appeals/shared/content/errorMessages.js
  src/applications/appeals/shared/tests/validations/index.unit.spec.js
  src/applications/appeals/shared/tests/validations/issues.unit.spec.js
  src/applications/appeals/shared/validations/index.js
  src/applications/appeals/shared/validations/issues.js
  src/applications/appeals/testing/components/AddIssue.jsx
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims

#26782 HLR | Update va-additional-info for consistency
  src/applications/appeals/996/content/contestableIssues.jsx
  src/applications/appeals/shared/components/DateSubmitted.jsx
  src/applications/appeals/shared/components/IssuesSubmitted.jsx
Labels: front end, HLR, benefits-team-1, squad-2

#26826 [CST] Removing set-focus from loading indicator
  src/applications/claims-status/containers/YourClaimsPageV2.jsx
Labels: Claim Status Tool

#26830 Fix issue card scrolling
  src/applications/appeals/shared/utils/focus.js
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims

#26845 Add Datadog action attributes to issue card
  src/applications/appeals/995/containers/App.jsx
  src/applications/appeals/shared/components/IssueCard.jsx
  src/applications/appeals/shared/utils/useBrowserMonitoring.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#26829 Move selectionRequired to shared
  src/applications/appeals/10182/tests/validations/issues.unit.spec.js
  src/applications/appeals/995/tests/validations/issues.unit.spec.js
  src/applications/appeals/996/tests/validations/issues.unit.spec.js
  src/applications/appeals/shared/tests/validations/issues.unit.spec.js
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims

#26870 DR | Move ShowIssuesList to shared
  src/applications/appeals/10182/content/issueSummary.js
  src/applications/appeals/996/components/ShowIssuesList.jsx
  src/applications/appeals/996/content/issueSummary.jsx
  src/applications/appeals/996/tests/components/ShowIssuesList.unit.spec.jsx
  src/applications/appeals/shared/components/ShowIssuesList.jsx
  src/applications/appeals/shared/tests/components/ShowIssuesList.unit.spec.jsx
  src/applications/appeals/testing/components/ShowIssuesList.jsx
  src/applications/appeals/testing/content/issueSummary.jsx
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2

#26827 DR | Move getDate to shared
  src/applications/appeals/995/components/EvidenceSummaryLists.jsx
  src/applications/appeals/995/content/IssueSummary.jsx
  src/applications/appeals/995/tests/995.cypress.helpers.js
  src/applications/appeals/995/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceVaRecords.unit.spec.jsx
  src/applications/appeals/995/tests/utils/dates.unit.spec.js
  src/applications/appeals/995/tests/utils/helpers.unit.spec.js
  src/applications/appeals/995/tests/utils/submit.unit.spec.js
  src/applications/appeals/995/tests/validations/date.unit.spec.js
  src/applications/appeals/995/tests/validations/evidence.unit.spec.js
  src/applications/appeals/995/tests/validations/issues.unit.spec.js
  src/applications/appeals/995/utils/dates.js
  src/applications/appeals/996/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/996/tests/utils/dates.unit.spec.js
  src/applications/appeals/996/tests/utils/helpers.unit.spec.js
  src/applications/appeals/996/tests/utils/submit.unit.spec.js
  src/applications/appeals/996/tests/validations/date.unit.spec.js
  src/applications/appeals/996/tests/validations/issues.unit.spec.js
  src/applications/appeals/996/utils/dates.js
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims

#26828 Move maxIssues to shared
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/tests/validations/issues.unit.spec.js
  src/applications/appeals/10182/validations/issues.js
  src/applications/appeals/995/pages/contestableIssues.js
  src/applications/appeals/995/tests/validations/issues.unit.spec.js
  src/applications/appeals/995/validations/issues.js
  src/applications/appeals/996/pages/contestableIssues.js
  src/applications/appeals/996/tests/validations/issues.unit.spec.js
  src/applications/appeals/996/validations/issues.js
  src/applications/appeals/shared/tests/validations/issues.unit.spec.js
  src/applications/appeals/shared/validations/issues.js
  src/applications/appeals/testing/pages/contestableIssues.js
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims
