Repository department-of-veterans-affairs/vets-website, pull requests merged in 2023-08, with the labels that each got.

#25062 Supplemental Claim | Update date validation
  src/applications/appeals/995/components/IssueCard.jsx
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/pages/contestableIssues.js
  src/applications/appeals/995/tests/components/IssueCard.unit.spec.jsx
  src/applications/appeals/995/tests/pages/contestableIssues.unit.spec.js
  src/applications/appeals/995/tests/validations/date.unit.spec.js
  src/applications/appeals/995/tests/validations/issues.unit.spec.js
  src/applications/appeals/995/validations/date.js
  src/applications/appeals/995/validations/issues.js
Labels: bug, front end, benefits-team-1, squad-2, Supplemental Claims

#25063 NOD | Add aria-describedby to evidence radios
  src/applications/appeals/10182/content/evidenceIntro.jsx
  src/applications/appeals/10182/pages/evidenceIntro.js
Labels: 508/Accessibility, front end, NOD, benefits-team-1, squad-2

#25067 NOD | update date validation
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/tests/validations/date.unit.spec.js
  src/applications/appeals/10182/validations/date.js
Labels: front end, NOD, benefits-team-1, squad-2

#25034 DR | Fix verify modal design
  src/applications/appeals/10182/components/NeedsToVerify.jsx
  src/applications/appeals/10182/containers/IntroductionPage.jsx
  src/applications/appeals/10182/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/appeals/995/containers/IntroductionPage.jsx
  src/applications/appeals/996/components/NeedsToVerify.jsx
  src/applications/appeals/996/containers/IntroductionPage.jsx
  src/applications/appeals/996/tests/containers/IntroductionPage.unit.spec.jsx
  src/applications/appeals/shared/components/NeedsToVerify.jsx
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims

#25069 NOD: submit email for v1 endpoint
  src/applications/appeals/10182/config/submit-transformer.js
  src/applications/appeals/10182/tests/schema/submit-transformer.unit.spec.js
  src/applications/appeals/10182/utils/submit.js
Labels: bug, front end, NOD, benefits-team-1, squad-2

#25073 NOD | Add more Datadog hidden content
  src/applications/appeals/10182/components/IssueCard.jsx
  src/applications/appeals/10182/components/ShowIssuesList.jsx
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
  src/applications/appeals/10182/pages/areaOfDisagreement.js
  src/applications/appeals/10182/tests/components/IssueCard.unit.spec.jsx
  src/applications/appeals/10182/tests/components/ShowIssuesList.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/areaOfDisagreement.unit.spec.jsx
  src/applications/appeals/10182/tests/validations/date.unit.spec.js
  src/applications/appeals/996/tests/validations/date.unit.spec.js
  src/platform/user/profile/vap-svc/containers/AddressValidationView.jsx
Labels: front end, NOD, benefits-team-1, squad-2

#25086 NOD & HLR: Fix disagreement title & a11y
  src/applications/appeals/10182/content/areaOfDisagreement.jsx
  src/applications/appeals/10182/pages/areaOfDisagreement.js
  src/applications/appeals/10182/tests/pages/areaOfDisagreement.unit.spec.jsx
  src/applications/appeals/996/content/areaOfDisagreement.jsx
  src/applications/appeals/996/pages/areaOfDisagreement.js
  src/applications/appeals/996/tests/pages/areaOfDisagreement.unit.spec.jsx
Labels: 508/Accessibility, front end, HLR, NOD, benefits-team-1, squad-2

#25012 61414 - [FSR] Remove Combined FSR feature flag
  src/applications/financial-status-report/components/debtsAndCopays/AvailableDebts.jsx
  src/applications/financial-status-report/components/debtsAndCopays/DebtCard.jsx
  src/applications/financial-status-report/components/debtsAndCopays/DebtCheckBox.jsx
  src/applications/financial-status-report/components/resolution/ResolutionDebtCards.jsx
  src/applications/financial-status-report/components/shared/DownloadFormPDF.jsx
  src/applications/financial-status-report/config/chapters/householdAssetsChapter.js
  src/applications/financial-status-report/config/chapters/resolutionOptionsChapter.js
  src/applications/financial-status-report/config/chapters/veteranInformationChapter.js
  src/applications/financial-status-report/containers/App.jsx
  src/applications/financial-status-report/containers/ConfirmationPage.jsx
  src/applications/financial-status-report/mocks/responses.js
  src/applications/financial-status-report/pages/assets/recreationalVehicles/records.js
  src/applications/financial-status-report/pages/index.js
  src/applications/financial-status-report/pages/resolution/comments.js
  src/applications/financial-status-report/pages/resolution/options.js
  src/applications/financial-status-report/pages/veteran/debts.js
  src/applications/financial-status-report/tests/e2e/cfsr-5655.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/efsr-5655-validation.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/efsr-5655.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/fixtures/data/cfsr-maximal.json
  src/applications/financial-status-report/tests/e2e/fixtures/data/cfsr-minimal.json
  src/applications/financial-status-report/tests/e2e/fixtures/data/efsr-maximal.json
  src/applications/financial-status-report/tests/e2e/fixtures/data/maximal.json
  src/applications/financial-status-report/tests/e2e/fixtures/data/minimal.json
  src/applications/financial-status-report/tests/e2e/fsr-5655-alert-cards-combined.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/fsr-5655-alert-cards.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/fsr-5655-contact-loop.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/fsr-5655-fetchDebts-fail.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/fsr-5655-fetchDebts-filter.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/fsr-5655-fetchDebts-success.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/fsr-5655-fetchsuccess.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/fsr-5655.cypress.spec.js
  src/applications/financial-status-report/tests/unit/cfsr-unit-maximal.json
  src/applications/financial-status-report/tests/unit/efsr-transform.unit.spec.jsx
  src/applications/financial-status-report/tests/unit/efsr-unit-maximal.json
  src/applications/financial-status-report/tests/unit/fsr-5655-submit.unit.spec.jsx
  src/applications/financial-status-report/tests/unit/transform.unit.spec.jsx
  src/applications/financial-status-report/tests/unit/unit-maximal.json
  src/applications/financial-status-report/utils/helpers.js
  src/applications/financial-status-report/utils/transform.js
Labels: front end, vsa-benefits-2

#25157 DR | Set up shared area of disagreement code
  src/applications/appeals/shared/components/AreaOfDisagreement.jsx
  src/applications/appeals/shared/constants.js
  src/applications/appeals/shared/content/areaOfDisagreement.jsx
  src/applications/appeals/shared/content/contactInfo.js
  src/applications/appeals/shared/pages/areaOfDisagreement.js
  src/applications/appeals/shared/sass/appeals.scss
  src/applications/appeals/shared/tests/components/AreaOfDisagreement.unit.spec.jsx
  src/applications/appeals/shared/tests/components/NeedsTpVerify.unit.spec.jsx
  src/applications/appeals/shared/tests/content/areaOfDisagreement.unit.spec.jsx
  src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx
  src/applications/appeals/shared/tests/utils/areaOfDisagreement.unit.spec.js
  src/applications/appeals/shared/tests/utils/dates.unit.spec.js
  src/applications/appeals/shared/tests/utils/helpers.unit.spec.js
  src/applications/appeals/shared/tests/utils/issues.unit.spec.js
  src/applications/appeals/shared/tests/utils/replace.unit.spec.js
  src/applications/appeals/shared/tests/utils/submit.unit.spec.js
  src/applications/appeals/shared/tests/utils/ui.unit.spec.js
  src/applications/appeals/shared/tests/validatiions/areaOfDisagreements.unit.spec.js
  src/applications/appeals/shared/tests/validatiions/contactInfo.unit.spec.js
  src/applications/appeals/shared/utils/areaOfDisagreement.js
  src/applications/appeals/shared/utils/dates.js
  src/applications/appeals/shared/utils/helpers.js
  src/applications/appeals/shared/utils/issues.js
  src/applications/appeals/shared/utils/replace.js
  src/applications/appeals/shared/utils/submit.js
  src/applications/appeals/shared/utils/ui.js
  src/applications/appeals/shared/validations/areaOfDisagreement.js
  src/applications/appeals/shared/validations/contactInfo.js
Labels: 508/Accessibility, front end, HLR, NOD, benefits-team-1, squad-2

#25180 526 | Update ITF content & add back link
  src/applications/disability-benefits/all-claims/components/ITFBanner.jsx
  src/applications/disability-benefits/all-claims/content/itfWrapper.jsx
Labels: front end, 526, benefits-team-1, squad-2, disability-experience

#25185 526 | Fix margin between ITF navigation link & button
  src/applications/disability-benefits/all-claims/components/ITFBanner.jsx
Labels: front end, 526, benefits-team-1, squad-2, disability-experience

#25184 63393 - [SW] Midpoint Review - IA links and typo updates (63343)
  src/applications/financial-status-report/components/alerts/AlertCard.jsx
  src/applications/financial-status-report/tests/e2e/streamlined-waiver-long.cypress.spec.js
  src/applications/financial-status-report/tests/e2e/streamlined-waiver-short.cypress.spec.js
Labels: front end, vsa-benefits-2

#25226 Revert ITF error message
  src/applications/disability-benefits/all-claims/components/ITFBanner.jsx
  src/applications/disability-benefits/all-claims/content/itfWrapper.jsx
  src/applications/disability-benefits/all-claims/tests/components/ITFBanner.unit.spec.jsx
Labels: front end, 526, benefits-team-1, squad-2, disability-experience

#25217 Decision Reviews | Show no loaded issues alert initially-only
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/995/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/content/contestableIssues.jsx
  src/applications/appeals/995/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/996/components/ContestableIssuesWidget.jsx
  src/applications/appeals/996/content/contestableIssues.jsx
  src/applications/appeals/996/tests/components/ContestableIssuesWidget.unit.spec.jsx
Labels: 508/Accessibility, front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#25246 NOD | Rename data to `appealingVHADenial`
  src/applications/appeals/10182/pages/appealingVhaDenial.js
  src/applications/appeals/10182/tests/fixtures/data/maximal-test.json
  src/applications/appeals/10182/tests/fixtures/data/minimal-test.json
  src/applications/appeals/10182/tests/pages/appealingVhaDenial.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/utils/submit.js
Labels: bug, front end, NOD, benefits-team-1, squad-2

#25256 63713 - [SW] Staging Review: Accessibility Feedback -HTML markup is not valid
  src/applications/financial-status-report/pages/assets/realEstate/enhancedIndex.js
  src/applications/financial-status-report/pages/assets/recreationalVehicles/index.js
  src/applications/financial-status-report/pages/assets/vehicles/index.js
  src/applications/financial-status-report/pages/bankruptcy/index.js
  src/applications/financial-status-report/pages/expenses/repayments/installmentContracts.js
  src/applications/financial-status-report/pages/income/spouse/benefits/index.js
  src/applications/financial-status-report/pages/income/spouse/spouseInfo.js
Labels: front end, vsa-benefits-2

#25278 SW - Conditionally Display VA Alert Texts
  src/applications/financial-status-report/containers/ConfirmationPage.jsx
Labels: front end, vsa-benefits-2

#25241 Decision Reviews | Display & submit unique API-loaded issues
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/components/IssueCard.jsx
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/definitions.js
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/utils/replace.js
  src/applications/appeals/10182/utils/submit.js
  src/applications/appeals/10182/validations/date.js
  src/applications/appeals/995/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/components/EvidenceSummaryLists.jsx
  src/applications/appeals/995/components/IssueCard.jsx
  src/applications/appeals/995/containers/App.jsx
  src/applications/appeals/995/containers/IntroductionPage.jsx
  src/applications/appeals/995/tests/utils/helpers.unit.spec.js
  src/applications/appeals/995/tests/utils/replace.unit.spec.js
  src/applications/appeals/995/tests/utils/submit.unit.spec.js
  src/applications/appeals/995/utils/contactInfo.js
  src/applications/appeals/995/utils/dates.js
  src/applications/appeals/995/utils/helpers.js
  src/applications/appeals/995/utils/replace.js
  src/applications/appeals/995/utils/submit.js
  src/applications/appeals/995/validations/date.js
  src/applications/appeals/995/validations/evidence.js
  src/applications/appeals/996/components/ContestableIssuesWidget.jsx
  src/applications/appeals/996/components/IssueCard.jsx
  src/applications/appeals/996/containers/Form0996App.jsx
  src/applications/appeals/996/tests/fixtures/data/migrated/maximal-test-v1-to-v2.json
  src/applications/appeals/996/tests/utils/helpers.unit.spec.js
  src/applications/appeals/996/tests/utils/replace.unit.spec.js
  src/applications/appeals/996/tests/utils/submit.unit.spec.js
  src/applications/appeals/996/utils/dates.js
  src/applications/appeals/996/utils/disagreement.js
  src/applications/appeals/996/utils/helpers.js
  src/applications/appeals/996/utils/replace.js
  src/applications/appeals/996/utils/submit.js
  src/applications/appeals/996/validations/date.js
  src/applications/appeals/shared/constants.js
  src/applications/appeals/shared/definitions.js
  src/applications/appeals/shared/tests/utils/issues.unit.spec.js
  src/applications/appeals/shared/tests/utils/replace.unit.spec.js
  src/applications/appeals/shared/utils/areaOfDisagreement.js
  src/applications/appeals/shared/utils/dates.js
  src/applications/appeals/shared/utils/issues.js
  src/applications/appeals/shared/utils/replace.js
  src/applications/appeals/shared/utils/submit.js
Labels: front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#25197 Add `:index` support to Cypress pageHooks
  src/applications/appeals/10182/tests/10182-notice-of-disagreement.cypress.spec.js
  src/platform/testing/e2e/cypress/support/form-tester/README.md
  src/platform/testing/e2e/cypress/support/form-tester/index.js
Labels: front end, testing, NOD, benefits-team-1, squad-2

#25266 DR | Refactor "upload" and "focus" utilities into shared directory
  src/applications/appeals/10182/components/AddIssue.jsx
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/issueSummary.unit.spec.jsx
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/utils/upload.js
  src/applications/appeals/995/utils/upload.js
  src/applications/appeals/996/components/AddIssue.jsx
  src/applications/appeals/996/components/ContestableIssuesWidget.jsx
  src/applications/appeals/996/components/IssueCard.jsx
  src/applications/appeals/996/constants.js
  src/applications/appeals/996/content/addIssue.jsx
  src/applications/appeals/996/content/contestableIssues.jsx
  src/applications/appeals/996/pages/addIssue.js
  src/applications/appeals/996/pages/areaOfDisagreement.js
  src/applications/appeals/996/pages/contestableIssues.js
  src/applications/appeals/996/pages/informalConferenceRep.js
  src/applications/appeals/996/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/996/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/996/tests/components/IssueCardV2.unit.spec.jsx
  src/applications/appeals/996/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/appeals/996/tests/containers/FormApp.unit.spec.jsx
  src/applications/appeals/996/tests/hlr.cypress.helpers.js
  src/applications/appeals/996/tests/hlr.cypress.spec.js
  src/applications/appeals/996/tests/pages/issueSummary.unit.spec.jsx
  src/applications/appeals/996/tests/utils/disagreement.unit.spec.js
  src/applications/appeals/996/tests/utils/focus.unit.spec.js
  src/applications/appeals/996/tests/utils/helpers.unit.spec.js
  src/applications/appeals/996/tests/utils/submit.unit.spec.js
  src/applications/appeals/996/tests/validations/issues.unit.spec.js
  src/applications/appeals/996/tests/validations/validations.unit.spec.js
  src/applications/appeals/996/utils/disagreement.js
  src/applications/appeals/996/utils/focus.js
  src/applications/appeals/996/utils/helpers.js
  src/applications/appeals/996/utils/submit.js
  src/applications/appeals/996/validations/index.js
  src/applications/appeals/996/validations/issues.js
  src/applications/appeals/shared/constants.js
  src/applications/appeals/shared/tests/utils/focus.unit.spec.js
  src/applications/appeals/shared/utils/focus.js
  src/applications/appeals/shared/utils/upload.js
Labels: front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#25310 NOD | Update review & submit error messaging
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/constants.js
  src/applications/appeals/10182/content/boardReview.jsx
  src/applications/appeals/10182/content/contestableIssues.jsx
  src/applications/appeals/10182/content/extensionReason.jsx
  src/applications/appeals/10182/content/hearingType.js
  src/applications/appeals/10182/pages/boardReview.js
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/pages/extensionReason.jsx
  src/applications/appeals/10182/pages/hearingType.js
  src/applications/appeals/10182/tests/10182-notice-of-disagreement.cypress.spec.js
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/boardReview.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/extensionReason.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/hearingType.unit.spec.jsx
  src/applications/appeals/10182/validations/issues.js
  src/applications/appeals/995/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/pages/contestableIssues.js
  src/applications/appeals/995/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/995/validations/issues.js
  src/applications/appeals/996/components/ContestableIssuesWidget.jsx
  src/applications/appeals/996/constants.js
  src/applications/appeals/996/content/contestableIssues.jsx
  src/applications/appeals/996/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/996/validations/issues.js
  src/applications/appeals/shared/content/contestableIssues.jsx
Labels: front end, NOD, benefits-team-1, squad-2

#25317 Add Datadog action name to hide PII
  src/applications/appeals/10182/components/IssueCard.jsx
Labels: front end, NOD, analytics, benefits-team-1, squad-2

#25329 NOD | Retry failed load of contestable issues
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/tests/components/ContestableIssuesWidget.unit.spec.jsx
  src/applications/appeals/10182/tests/pages/contestableIssues.unit.spec.jsx
  src/applications/appeals/shared/content/contestableIssues.jsx
Labels: front end, NOD, benefits-team-1, squad-2

#25365 NOD | Fix string replace JS error
  src/applications/appeals/shared/constants.js
  src/applications/appeals/shared/tests/utils/replace.unit.spec.js
  src/applications/appeals/shared/utils/replace.js
Labels: bug, front end, NOD, benefits-team-1, squad-2

#25370 Style check status as action link
  src/applications/appeals/10182/containers/ConfirmationPage.jsx
  src/applications/appeals/10182/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/appeals/996/containers/ConfirmationPage.jsx
  src/applications/appeals/996/tests/containers/ConfirmationPage.unit.spec.jsx
Labels: 508/Accessibility, front end, HLR, NOD, benefits-team-1, squad-2

#25363 NOD | Add Datadog action name to hide PII
  src/applications/appeals/10182/components/IssueCard.jsx
  src/applications/appeals/10182/components/ShowIssuesList.jsx
  src/applications/appeals/10182/components/VeteranInformation.jsx
  src/applications/appeals/10182/containers/ConfirmationPage.jsx
  src/applications/appeals/10182/tests/components/IssueCard.unit.spec.jsx
  src/applications/appeals/10182/tests/components/ShowIssuesList.unit.spec.jsx
  src/applications/appeals/10182/tests/components/VeteranInformation.unit.spec.jsx
  src/applications/appeals/10182/tests/containers/ConfirmationPage.unit.spec.jsx
  src/applications/appeals/shared/content/areaOfDisagreement.jsx
  src/applications/appeals/shared/content/contestableIssues.jsx
  src/applications/appeals/shared/tests/content/areaOfDisagreement.unit.spec.jsx
  src/applications/appeals/shared/tests/pages/areaOfDisagreement.unit.spec.jsx
  src/platform/forms-system/src/js/components/ContactInfo.jsx
  src/platform/forms-system/src/js/components/ContactInfoReview.jsx
  src/platform/forms-system/src/js/fields/FileField.jsx
  src/platform/forms-system/src/js/review/PhoneNumberWidget.jsx
  src/platform/forms-system/test/js/components/ContactInfo.unit.spec.jsx
  src/platform/forms-system/test/js/components/ContactInfoReview.unit.spec.jsx
  src/platform/forms-system/test/js/fields/FileField.unit.spec.jsx
  src/platform/user/profile/vap-svc/components/AddressField/AddressView.jsx
  src/platform/user/profile/vap-svc/components/PhoneField/PhoneView.jsx
  src/platform/user/profile/vap-svc/containers/AddressValidationModal.jsx
  src/platform/user/profile/vap-svc/containers/AddressValidationView.jsx
Labels: front end, NOD, benefits-team-1, squad-2

#25358 Dbex/63748 itf expiration fix
  src/applications/disability-benefits/all-claims/content/itfWrapper.jsx
Labels: front end, 526ez-Defects

#25423 Appeals | Build appeals testing framework
  src/applications/appeals/testing/app-entry.jsx
  src/applications/appeals/testing/config/form.js
  src/applications/appeals/testing/containers/App.jsx
  src/applications/appeals/testing/containers/ConfirmationPage.jsx
  src/applications/appeals/testing/containers/IntroductionPage.jsx
  src/applications/appeals/testing/manifest.json
  src/applications/appeals/testing/reducers/index.js
  src/applications/appeals/testing/routes.jsx
  src/applications/appeals/testing/sass/appeals-testing.scss
  src/applications/appeals/testing/tests/appeals-testing.cypress.spec.js
  src/applications/appeals/testing/tests/fixtures/data/test-data.json
  src/platform/forms/constants.js
  src/platform/forms/tests/forms.unit.spec.js
Labels: front end, testing, NOD, benefits-team-1, squad-2

#24716 59051 - [FSR] - Downtime dependency update
  src/applications/combined-debt-portal/combined/containers/CombinedPortalApp.jsx
  src/applications/financial-status-report/config/form.js
  src/applications/financial-status-report/wizard/WizardContainer.jsx
  src/applications/financial-status-report/wizard/pages/Submit.jsx
Labels: front end, vsa-benefits-2

#25408 DR | Refactor "date validations" into shared directory
  src/applications/appeals/10182/validations/date.js
  src/applications/appeals/995/validations/date.js
  src/applications/appeals/996/validations/date.js
  src/applications/appeals/shared/validations/date.js
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims

#25404 Supplemental Claim | Move authorization info inside checkbox slot
  src/applications/appeals/995/components/EvidencePrivateRecordsAuthorization.jsx
  src/applications/appeals/995/content/evidencePrivateRecordsAuthorization.jsx
Labels: 508/Accessibility, front end, benefits-team-1, squad-2, Supplemental Claims

#25463 Adding env check to update region in speech token calls
  src/applications/virtual-agent/components/webchat/WebChat.jsx
Labels: bug, rx
