Repository department-of-veterans-affairs/vets-website, pull requests merged in 2023-09, with the labels that each got.

#25485 DR | Refactor "evidence" and "index" validations into shared directory
  src/applications/appeals/995/validations/evidence.js
  src/applications/appeals/995/validations/index.js
  src/applications/appeals/996/validations/index.js
  src/applications/appeals/shared/validations/evidence.js
  src/applications/appeals/shared/validations/index.js
Labels: front end, benefits-team-1, squad-2, Supplemental Claims

#25544 64162 - [FSR] Installment contract date required tag
  src/applications/financial-status-report/components/householdExpenses/InstallmentContract.jsx
Labels: front end, vsa-benefits-2

#25545 DR | Add related content to message-aria-describedby
  src/applications/appeals/10182/components/AddIssue.jsx
  src/applications/appeals/10182/content/addIssue.jsx
  src/applications/appeals/995/components/AddIssue.jsx
  src/applications/appeals/995/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/components/Notice5103.jsx
  src/applications/appeals/995/content/addIssue.jsx
  src/applications/appeals/995/content/notice5103.jsx
  src/applications/appeals/996/components/AddIssue.jsx
  src/applications/appeals/996/content/addIssue.jsx
Labels: 508/Accessibility, front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#25565 DR Testing | Update prototype (part 1)
  src/applications/appeals/testing/components/AddIssue.jsx
  src/applications/appeals/testing/components/ReviewPage.jsx
  src/applications/appeals/testing/components/TaskList.jsx
  src/applications/appeals/testing/containers/App.jsx
  src/applications/appeals/testing/containers/IntroductionPage.jsx
  src/applications/appeals/testing/content/addIssue.jsx
  src/applications/appeals/testing/content/issueSummary.js
  src/applications/appeals/testing/pages/addIssue.js
Labels: front end, NOD, benefits-team-1, squad-2

#25588 NOD prototype updates (part 2)
  src/applications/appeals/testing/components/ContactInformation.jsx
  src/applications/appeals/testing/components/ContestableIssuesWidget.jsx
  src/applications/appeals/testing/components/EditContactInfo.jsx
  src/applications/appeals/testing/components/ReviewPage.jsx
  src/applications/appeals/testing/components/TaskList.jsx
  src/applications/appeals/testing/constants.js
  src/applications/appeals/testing/containers/App.jsx
  src/applications/appeals/testing/containers/IntroductionPage.jsx
  src/applications/appeals/testing/content/GetFormHelp.jsx
  src/applications/appeals/testing/pages/areaOfDisagreement.js
  src/applications/appeals/testing/pages/contactInfo copy.js
  src/applications/appeals/testing/pages/contactInfo.js
  src/applications/appeals/testing/utils/contactInfo.js
Labels: front end, NOD, benefits-team-1, squad-2

#25610 NOD prototype | Add `uswds` prop to file uploads
  src/applications/appeals/testing/utils/additionalInfoUpload.js
  src/applications/appeals/testing/utils/evidenceUpload.js
  src/platform/forms-system/src/js/fields/FileField.jsx
  src/platform/forms-system/src/js/utilities/file/ShowPdfPassword.jsx
  src/platform/forms-system/test/js/fields/FileField.unit.spec.jsx
  src/platform/forms-system/test/js/utilities/file.unit.spec.js
Labels: front end, testing, NOD, benefits-team-1, squad-2

#25635 NOD prototype | Update content
  src/applications/appeals/testing/components/AddIssue.jsx
  src/applications/appeals/testing/components/ReviewPage.jsx
  src/applications/appeals/testing/sass/appeals-testing.scss
Labels: testing, NOD, benefits-team-1, squad-2

#25659 64913 - [FSR] - addError sentry notification
  src/applications/financial-status-report/components/debtsAndCopays/EnhancedBenefitsEdit.jsx
Labels: front end, vsa-benefits-2

#25711 NOD Prototype | Fix typo and hide some task list links
  src/applications/appeals/testing/config/form.js
  src/applications/appeals/testing/containers/IntroductionPage.jsx
Labels: front end, NOD, benefits-team-1, squad-2

#25625 Supplemental Claim | Update e2e tests
  src/applications/appeals/995/tests/995-supplemental-claim.cypress.spec.js
  src/platform/testing/e2e/cypress/support/commands/formHelpers.js
Labels: front end, testing, benefits-team-1, squad-2, Supplemental Claims

#25715 NOD Prototype | Fix scroll to target
  src/applications/appeals/testing/components/ReviewPage.jsx
  src/applications/appeals/testing/components/TaskList.jsx
  src/applications/appeals/testing/containers/App.jsx
  src/applications/appeals/testing/containers/ConfirmationPage.jsx
  src/applications/appeals/testing/utils/focus.js
Labels: front end, NOD, benefits-team-1, squad-2

#25467 DR | Refactor date error messages
  src/applications/appeals/10182/content/addIssue.jsx
  src/applications/appeals/10182/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/10182/tests/validations/date.unit.spec.js
  src/applications/appeals/10182/validations/date.js
  src/applications/appeals/995/constants.js
  src/applications/appeals/995/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceVaRecords.unit.spec.jsx
  src/applications/appeals/995/tests/validations/date.unit.spec.js
  src/applications/appeals/995/tests/validations/evidence.unit.spec.js
  src/applications/appeals/995/validations/date.js
  src/applications/appeals/996/content/addIssue.jsx
  src/applications/appeals/996/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/996/tests/validations/date.unit.spec.js
  src/applications/appeals/996/validations/date.js
  src/applications/appeals/shared/validations/date.js
  src/applications/appeals/testing/content/addIssue.jsx
Labels: front end, HLR, Tech Debt, NOD, benefits-team-1, squad-2, Supplemental Claims

#25745 NOD prototype | Fix review page
  src/applications/appeals/testing/components/ReviewPage.jsx
  src/applications/appeals/testing/config/form.js
  src/applications/appeals/testing/pages/contestableIssues.js
  src/applications/appeals/testing/pages/extensionRequest.js
  src/applications/appeals/testing/tests/fixtures/data/full-test-data.json
Labels: front end, testing, NOD, benefits-team-1, squad-2

#25752 SW - Fix Console Warning for Submit / Button Type
  src/applications/financial-status-report/components/employment/EmploymentHistoryWidget.jsx
  src/applications/financial-status-report/components/employment/EmploymentQuestion.jsx
  src/applications/financial-status-report/components/employment/SpouseEmploymentHistoryWidget.jsx
  src/applications/financial-status-report/components/employment/SpouseEmploymentQuestion.jsx
  src/applications/financial-status-report/components/householdIncome/OtherIncomeSummary.jsx
  src/applications/financial-status-report/components/householdIncome/SpouseOtherIncomeSummary.jsx
  src/applications/financial-status-report/components/otherAssets/OtherAssetsSummary.jsx
  src/applications/financial-status-report/components/otherExpenses/OtherExpensesSummary.jsx
  src/applications/financial-status-report/components/utilityBills/UtilityBillSummary.jsx
Labels: front end, vsa-benefits-2

#25678 PR for DR | Refactor "issues" validations into shared directory
  src/applications/appeals/10182/components/AddIssue.jsx
  src/applications/appeals/10182/components/ContestableIssuesWidget.jsx
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/content/issueSummary.js
  src/applications/appeals/10182/pages/contestableIssues.js
  src/applications/appeals/10182/tests/validations/issues.unit.spec.js
  src/applications/appeals/10182/validations/issues.js
  src/applications/appeals/995/components/AddIssue.jsx
  src/applications/appeals/995/components/ContestableIssuesWidget.jsx
  src/applications/appeals/995/components/EvidencePrivateRecords.jsx
  src/applications/appeals/995/components/EvidenceVaRecords.jsx
  src/applications/appeals/995/containers/ConfirmationPage.jsx
  src/applications/appeals/995/content/IssueSummary.jsx
  src/applications/appeals/995/pages/contestableIssues.js
  src/applications/appeals/995/tests/utils/helpers.unit.spec.js
  src/applications/appeals/995/tests/validations/issues.unit.spec.js
  src/applications/appeals/995/utils/evidence.js
  src/applications/appeals/995/utils/helpers.js
  src/applications/appeals/995/validations/issues.js
  src/applications/appeals/996/components/AddIssue.jsx
  src/applications/appeals/996/components/ContestableIssuesWidget.jsx
  src/applications/appeals/996/containers/ConfirmationPage.jsx
  src/applications/appeals/996/containers/Form0996App.jsx
  src/applications/appeals/996/content/issueSummary.jsx
  src/applications/appeals/996/pages/contestableIssues.js
  src/applications/appeals/996/tests/utils/helpers.unit.spec.js
  src/applications/appeals/996/tests/validations/issues.unit.spec.js
  src/applications/appeals/996/utils/helpers.js
  src/applications/appeals/996/validations/issues.js
  src/applications/appeals/shared/validations/evidence.js
  src/applications/appeals/shared/validations/issues.js
  src/applications/appeals/testing/components/AddIssue.jsx
  src/applications/appeals/testing/pages/contestableIssues.js
Labels: front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#25782 Supplemental Claims | Skip flaky unit tests
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
Labels: bug, front end, benefits-team-1, squad-2, Supplemental Claims

#25811 NOD | Move RUM init to shared & require login
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/10182/hooks/useBrowserMonitoring.jsx
  src/applications/appeals/10182/utils/feature-toggles.js
  src/applications/appeals/shared/utils/useBrowserMonitoring.jsx
Labels: front end, NOD, benefits-team-1, squad-2

#25861 HLR | Add RUM monitoring
  src/applications/appeals/10182/containers/FormApp.jsx
  src/applications/appeals/996/components/IssueCard.jsx
  src/applications/appeals/996/components/ShowIssuesList.jsx
  src/applications/appeals/996/containers/Form0996App.jsx
  src/applications/appeals/996/tests/components/IssueCard.unit.spec.jsx
  src/applications/appeals/996/tests/components/IssueCardV2.unit.spec.jsx
  src/platform/utilities/feature-toggles/featureFlagNames.js
Labels: front end, HLR, benefits-team-1, squad-2

#25881 DR | Set submitted zipcode based on country code
  src/applications/appeals/10182/tests/utils/submit.unit.spec.js
  src/applications/appeals/10182/utils/submit.js
  src/applications/appeals/995/tests/utils/submit.unit.spec.js
  src/applications/appeals/995/utils/submit.js
  src/applications/appeals/996/tests/utils/submit.unit.spec.js
  src/applications/appeals/996/utils/submit.js
Labels: bug, front end, HLR, NOD, benefits-team-1, squad-2, Supplemental Claims

#25914 DR | Refactor & clean up ui functions
  src/applications/appeals/995/components/ContactInfo.jsx
  src/applications/appeals/995/components/EvidenceSummaryLists.jsx
  src/applications/appeals/995/content/evidenceUpload.jsx
  src/applications/appeals/995/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/995/tests/components/EvidencePrivateLimitation.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidencePrivateRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidencePrivateRecordsRequest.unit.spec.jsx
  src/applications/appeals/995/tests/components/EvidenceVaRecords.unit.spec.jsx
  src/applications/appeals/995/tests/components/PrimaryPhone.unit.spec.jsx
  src/applications/appeals/995/tests/components/PrimaryPhoneReview.unit.spec.jsx
  src/applications/appeals/995/tests/components/VeteranInformation.unit.spec.jsx
  src/applications/appeals/995/tests/pages/contactInfo.unit.spec.jsx
  src/applications/appeals/995/tests/pages/contestableIssues.unit.spec.js
  src/applications/appeals/995/tests/pages/primaryPhone.unit.spec.jsx
  src/applications/appeals/995/tests/utils/helpers.unit.spec.js
  src/applications/appeals/995/utils/helpers.js
  src/applications/appeals/995/utils/ui.js
  src/applications/appeals/996/tests/components/AddIssue.unit.spec.js
  src/applications/appeals/996/tests/pages/informalConferenceRep.unit.spec.js
  src/applications/appeals/996/tests/utils/helpers.unit.spec.js
  src/applications/appeals/996/utils/helpers.js
  src/applications/appeals/996/utils/ui.js
  src/applications/appeals/shared/tests/utils/ui.unit.spec.js
  src/applications/appeals/shared/utils/ui.js
  src/applications/appeals/testing/utils/areaOfDisagreement.js
Labels: front end, HLR, Tech Debt, benefits-team-1, squad-2, Supplemental Claims

#25834 60297 - eFSR] - Collab cycle staging review Content doesn’t align with style guidance in VA.gov content style guide. (02.04.1) (Post Launch)
  src/applications/financial-status-report/components/householdExpenses/InstallmentContractSummary.jsx
  src/applications/financial-status-report/tests/e2e/efsr-5655.cypress.spec.js
Labels: front end, vsa-benefits-2
